(SYMBOL-SYMBOL-ALISTP-FORWARD-TO-SYMBOL-ALISTP
 (39 39 (:REWRITE DEFAULT-CAR))
 (8 8 (:REWRITE DEFAULT-CDR))
 )
(SYMBOL-SYMBOL-ALISTP-FORWARD-TO-ALISTP)
(SYMBOL-ALISTP-WHEN-SYMBOL-SYMBOL-ALISTP)
(SYMBOL-SYMBOL-ALISTP-OF-CONS-OF-CONS
 (12 12 (:REWRITE DEFAULT-CAR))
 (6 6 (:REWRITE DEFAULT-CDR))
 (2 2 (:DEFINITION NULL))
 )
(SYMBOLP-OF-CDR-OF-ASSOC-EQUAL-WHEN-SYMBOL-SYMBOL-ALISTP
 (41 41 (:REWRITE DEFAULT-CAR))
 (15 15 (:REWRITE DEFAULT-CDR))
 )
