(ALL-<= (2 2 (:REWRITE DEFAULT-CAR))
        (1 1 (:REWRITE DEFAULT-CDR)))
(ALL-<=-OF-CONS)
(USE-ALL-<=-FOR-CAR)
(USE-ALL-<=-FOR-CAR-OF-LAST)
(ALL-<=-OF-APPEND)
(ALL-<=-OF-UNION-EQUAL)
(ALL-<=-WHEN-NOT-CONSP)
(ALL-<=-WHEN-NOT-CONSP-CHEAP)
(ALL-<=-OF-REVAPPEND)
(ALL-<=-OF-CDR)
(ALL-<=-OF-NTHCDR)
(ALL-<=-OF-FIRSTN)
(ALL-<=-OF-REMOVE1-EQUAL)
(ALL-<=-OF-REMOVE-EQUAL)
(ALL-<=-OF-LAST)
(ALL-<=-OF-TAKE)
(ALL-<=-WHEN-PERM)
(ALL-<=-OF-TRUE-LIST-FIX)
(PERM-IMPLIES-EQUAL-ALL-<=-1)
(USE-ALL-<=)
(USE-ALL-<=-2)
(ALL-<=-OF-ADD-TO-SET-EQUAL)
(ALL-<=-MONOTONE (35 19 (:REWRITE DEFAULT-<-2))
                 (35 19 (:REWRITE DEFAULT-<-1))
                 (32 32
                     (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                 (29 25 (:REWRITE ALL-<=-WHEN-NOT-CONSP))
                 (26 20 (:REWRITE USE-ALL-<=))
                 (25 25
                     (:REWRITE ALL-<=-WHEN-NOT-CONSP-CHEAP))
                 (24 4 (:REWRITE ALL-<=-OF-CDR))
                 (20 20 (:REWRITE USE-ALL-<=-2))
                 (17 17 (:REWRITE DEFAULT-CAR))
                 (8 8 (:REWRITE DEFAULT-CDR))
                 (6 6 (:TYPE-PRESCRIPTION MEMBERP)))
(<=-OF-NTH-WHEN-ALL-<= (41 23 (:REWRITE USE-ALL-<=))
                       (23 23 (:REWRITE USE-ALL-<=-2))
                       (21 21 (:REWRITE DEFAULT-<-1))
                       (18 18 (:TYPE-PRESCRIPTION MEMBERP))
                       (18 16 (:REWRITE ALL-<=-WHEN-NOT-CONSP))
                       (17 17 (:REWRITE ALL-<=-MONOTONE))
                       (14 14 (:REWRITE DEFAULT-CAR))
                       (14 2 (:REWRITE ALL-<=-OF-CDR))
                       (12 12
                           (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                       (6 6 (:REWRITE DEFAULT-CDR))
                       (5 5 (:REWRITE ZP-OPEN))
                       (2 2 (:REWRITE DEFAULT-+-2))
                       (2 2 (:REWRITE DEFAULT-+-1)))
(<=-OF-NTH-WHEN-ALL-<=-FREE (99 12 (:REWRITE USE-ALL-<=-FOR-CAR))
                            (34 27 (:REWRITE DEFAULT-<-1))
                            (28 28 (:REWRITE USE-ALL-<=-2))
                            (28 28 (:REWRITE USE-ALL-<=))
                            (25 25
                                (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                            (18 18 (:REWRITE ALL-<=-MONOTONE))
                            (18 16 (:REWRITE ALL-<=-WHEN-NOT-CONSP))
                            (14 14 (:REWRITE DEFAULT-CAR))
                            (14 2 (:REWRITE ALL-<=-OF-CDR))
                            (7 7 (:REWRITE DEFAULT-CDR))
                            (5 5 (:REWRITE ZP-OPEN))
                            (2 2 (:REWRITE DEFAULT-+-2))
                            (2 2 (:REWRITE DEFAULT-+-1)))
