(PAIR-WITH-RATIONAL-CDRP)
(CDR-<)
(ALL-PAIR-WITH-RATIONAL-CDRP)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-CONS-FOR-DEFMERGESORT
     (126 7 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (35 35 (:TYPE-PRESCRIPTION LEN))
     (14 7 (:REWRITE DEFAULT-<-2))
     (10 2 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (8 8 (:REWRITE DEFAULT-CDR))
     (7 7 (:REWRITE USE-ALL-CONSP-2))
     (7 7 (:REWRITE USE-ALL-CONSP))
     (7 7 (:REWRITE USE-ALL-<-2))
     (7 7 (:REWRITE USE-ALL-<))
     (7 7 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (7 7 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (7 7 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (7 7
        (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (7 7 (:REWRITE DEFAULT-<-1))
     (7 7 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (7 7
        (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (7 7
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (7 7 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (7 7
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (7 7
        (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (6 2
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (5 5 (:REWRITE USE-ALL-RATIONALP-2))
     (5 5 (:REWRITE USE-ALL-RATIONALP))
     (4 4 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (4 4 (:TYPE-PRESCRIPTION ALL-CONSP))
     (4 2
        (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (3 3 (:REWRITE DEFAULT-CAR))
     (2 2
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (2 2
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (2 2
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (2 2
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (2 2
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (2 2 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP)))
(USE-ALL-PAIR-WITH-RATIONAL-CDRP-FOR-CAR-FOR-DEFMERGESORT
     (71 4 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (18 6
         (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (15 3 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (9 3
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (8 4 (:REWRITE DEFAULT-<-2))
     (7 7 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (7 7 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (7 7 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (7 7
        (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (6 6 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (6 6 (:TYPE-PRESCRIPTION ALL-CONSP))
     (6 3
        (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (4 4 (:REWRITE USE-ALL-CONSP-2))
     (4 4 (:REWRITE USE-ALL-CONSP))
     (4 4 (:REWRITE USE-ALL-<-2))
     (4 4 (:REWRITE USE-ALL-<))
     (4 4 (:REWRITE DEFAULT-CDR))
     (4 4 (:REWRITE DEFAULT-CAR))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (4 4
        (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (4 4
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (4 4 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (4 4
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (3 3
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (3 3
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (3 3
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (3 3
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (3 3
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (3 3 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (2 2 (:REWRITE USE-ALL-RATIONALP-2))
     (2 2 (:REWRITE USE-ALL-RATIONALP)))
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-CDR-FOR-DEFMERGESORT
     (36 2 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (10 10 (:TYPE-PRESCRIPTION LEN))
     (5 1 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (4 2 (:REWRITE DEFAULT-<-2))
     (4 1
        (:REWRITE USE-ALL-PAIR-WITH-RATIONAL-CDRP-FOR-CAR-FOR-DEFMERGESORT))
     (3 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (2 2 (:TYPE-PRESCRIPTION ALL-CONSP))
     (2 2 (:REWRITE USE-ALL-CONSP-2))
     (2 2 (:REWRITE USE-ALL-CONSP))
     (2 2 (:REWRITE USE-ALL-<-2))
     (2 2 (:REWRITE USE-ALL-<))
     (2 2 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (2 2 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (2 2 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (2 2
        (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (2 2 (:REWRITE DEFAULT-<-1))
     (2 2 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (2 2
        (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (2 2
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (2 2 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (2 2
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (2 2
        (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (2 1
        (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (1 1
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (1 1 (:REWRITE USE-ALL-RATIONALP-2))
     (1 1 (:REWRITE USE-ALL-RATIONALP))
     (1 1
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (1 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (1 1
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (1 1 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP)))
(ALL-PAIR-WITH-RATIONAL-CDRP)
(MERGE-CDR-<
     (28 14
         (:TYPE-PRESCRIPTION TRUE-LISTP-REVAPPEND-TYPE-PRESCRIPTION)))
(CONSP-OF-MERGE-CDR-<
     (1023 69 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (368 38 (:REWRITE DEFAULT-CDR))
     (123 51 (:REWRITE DEFAULT-<-2))
     (102 102 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (100 100 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (100 100 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (100 100
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (84 51 (:REWRITE DEFAULT-<-1))
     (69 69
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (66 22
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (51 51 (:REWRITE USE-ALL-<-2))
     (51 51 (:REWRITE USE-ALL-<))
     (51 51
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (47 47 (:REWRITE USE-ALL-CONSP-2))
     (47 47 (:REWRITE USE-ALL-CONSP))
     (47 47 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (39 39 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (39 39
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (36 36 (:REWRITE DEFAULT-CAR))
     (22 22 (:REWRITE USE-ALL-RATIONALP-2))
     (22 22 (:REWRITE USE-ALL-RATIONALP))
     (11 11 (:REWRITE USE-ALL-<=-2))
     (11 11 (:REWRITE USE-ALL-<=))
     (11 1 (:REWRITE LEN-OF-CDR))
     (6 3
        (:TYPE-PRESCRIPTION TRUE-LISTP-REVAPPEND-TYPE-PRESCRIPTION))
     (5 3 (:REWRITE DEFAULT-+-2))
     (3 3 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (3 3 (:REWRITE DEFAULT-+-1))
     (1 1
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN)))
(MERGE-SORT-CDR-<)
(CONSP-OF-MERGE-SORT-CDR-<
     (123 7 (:REWRITE DEFAULT-CDR))
     (38 38 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (38 19 (:REWRITE DEFAULT-<-2))
     (37 37 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (37 37 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (37 37
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (31 31
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (25 25 (:REWRITE USE-ALL-CONSP-2))
     (25 25 (:REWRITE USE-ALL-CONSP))
     (25 25 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (19 19 (:REWRITE USE-ALL-<-2))
     (19 19 (:REWRITE USE-ALL-<))
     (19 19 (:REWRITE DEFAULT-<-1))
     (19 19
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (15 15 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (15 15
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (12 6
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-MV-NTH-1-OF-SPLIT-LIST-FAST))
     (12 6 (:REWRITE DEFAULT-+-2))
     (8 1 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (6 6 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (6 6 (:REWRITE DEFAULT-+-1))
     (4 4
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (1 1 (:REWRITE USE-ALL-<=-2))
     (1 1 (:REWRITE USE-ALL-<=)))
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-MV-NTH-0-OF-SPLIT-LIST-FAST-AUX)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-MV-NTH-0-OF-SPLIT-LIST-FAST)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-MV-NTH-1-OF-SPLIT-LIST-FAST-AUX)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-MV-NTH-1-OF-SPLIT-LIST-FAST)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-MERGE-CDR-<)
(TRUE-LISTP-OF-MERGE-CDR-<)
(TRUE-LISTP-OF-MERGE-SORT-CDR-<)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-MERGE-SORT-CDR-<)
(MERGE-SORT-CDR-<)
(PERM-OF-MERGE-CDR-<)
(PERM-OF-MERGE-SORT-CDR-<)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-CONS)
(USE-ALL-PAIR-WITH-RATIONAL-CDRP-FOR-CAR)
(USE-ALL-PAIR-WITH-RATIONAL-CDRP-FOR-CAR-OF-LAST)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-APPEND)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-UNION-EQUAL)
(ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-NOT-CONSP)
(ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-NOT-CONSP-CHEAP)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-REVAPPEND)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-CDR)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-NTHCDR)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-FIRSTN)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-REMOVE1-EQUAL)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-REMOVE-EQUAL)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-LAST)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-TAKE)
(ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-PERM)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-TRUE-LIST-FIX)
(PERM-IMPLIES-EQUAL-ALL-PAIR-WITH-RATIONAL-CDRP-1)
(USE-ALL-PAIR-WITH-RATIONAL-CDRP)
(USE-ALL-PAIR-WITH-RATIONAL-CDRP-2)
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-ADD-TO-SET-EQUAL)
(PRINT-SYMBOLS (36 2 (:REWRITE CONSP-FROM-LEN-CHEAP))
               (11 1 (:REWRITE LEN-OF-CDR))
               (10 2
                   (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
               (5 5 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
               (5 5 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
               (5 5 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
               (5 5
                  (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
               (4 4 (:REWRITE DEFAULT-CDR))
               (4 4 (:REWRITE DEFAULT-CAR))
               (3 3
                  (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
               (3 3
                  (:REWRITE SYMBOLP-OF-CAR-WHEN-BOUNDED-DAG-EXPRP))
               (3 2 (:REWRITE DEFAULT-<-2))
               (2 2 (:REWRITE USE-ALL-CONSP-2))
               (2 2 (:REWRITE USE-ALL-CONSP))
               (2 2 (:REWRITE USE-ALL-<-2))
               (2 2 (:REWRITE USE-ALL-<))
               (2 2 (:REWRITE DEFAULT-<-1))
               (2 2 (:REWRITE CONSP-WHEN-LEN-GREATER))
               (2 2
                  (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
               (2 2
                  (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
               (1 1 (:REWRITE DEFAULT-+-2))
               (1 1 (:REWRITE DEFAULT-+-1))
               (1 1
                  (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
               (1 1 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
               (1 1
                  (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH)))
(PRINT-SYMBOLS-4-PER-LINE
     (10821 539 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (4240 583 (:REWRITE DEFAULT-CDR))
     (2941 147 (:REWRITE LEN-OF-NTHCDR))
     (1422 146 (:DEFINITION NFIX))
     (1275 966 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (1095 774 (:REWRITE DEFAULT-<-2))
     (1088 98 (:REWRITE LEN-OF-CDR))
     (807 807 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (807 807 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (807 807
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (802 774 (:REWRITE DEFAULT-<-1))
     (774 774 (:REWRITE USE-ALL-<-2))
     (774 774 (:REWRITE USE-ALL-<))
     (774 774
          (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (481 150 (:REWRITE COMMUTATIVITY-OF-+))
     (480 480 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (477 416 (:REWRITE DEFAULT-+-2))
     (451 416 (:REWRITE DEFAULT-+-1))
     (421 399 (:REWRITE DEFAULT-CAR))
     (383 383
          (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (383 383
          (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (364 4 (:DEFINITION ACL2-COUNT))
     (333 333 (:REWRITE USE-ALL-CONSP-2))
     (333 333 (:REWRITE USE-ALL-CONSP))
     (306 306
          (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
     (297 297 (:REWRITE USE-ALL-<=-2))
     (297 297 (:REWRITE USE-ALL-<=))
     (213 213
          (:REWRITE SYMBOLP-OF-CAR-WHEN-BOUNDED-DAG-EXPRP))
     (198 198 (:REWRITE NTH-WHEN-NOT-CDDR))
     (150 150
          (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (93 87 (:REWRITE NTHCDR-WHEN-EQUAL-OF-LEN))
     (86 86 (:REWRITE NTHCDR-WHEN-NOT-POSP))
     (86 86
         (:REWRITE NTHCDR-WHEN-NOT-CONSP-CHEAP))
     (40 4 (:DEFINITION INTEGER-ABS))
     (14 2 (:REWRITE EQUAL-OF-LEN-AND-0))
     (14 2 (:DEFINITION LENGTH))
     (6 6 (:REWRITE FOLD-CONSTS-IN-+))
     (4 4 (:REWRITE DEFAULT-UNARY-MINUS))
     (2 2 (:REWRITE USE-ALL-RATIONALP-2))
     (2 2 (:REWRITE USE-ALL-RATIONALP))
     (2 2
        (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
     (2 2
        (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (2 2 (:REWRITE DEFAULT-REALPART))
     (2 2 (:REWRITE DEFAULT-NUMERATOR))
     (2 2 (:REWRITE DEFAULT-IMAGPART))
     (2 2 (:REWRITE DEFAULT-DENOMINATOR))
     (2 2 (:REWRITE DEFAULT-COERCE-2))
     (2 2 (:REWRITE DEFAULT-COERCE-1)))
(PRINT-FUNCTION-COUNTS
     (86 6 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (19 6
         (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (19 4 (:REWRITE DEFAULT-CAR))
     (16 4 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (15 3 (:REWRITE DEFAULT-CDR))
     (10 4
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (8 8 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (8 8 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (8 8 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (8 8
        (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (8 4 (:REWRITE DEFAULT-<-2))
     (8 4
        (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (6 6 (:TYPE-PRESCRIPTION ALL-CONSP))
     (6 6
        (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (5 5 (:REWRITE USE-ALL-CONSP-2))
     (5 5 (:REWRITE USE-ALL-CONSP))
     (5 5 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (5 5
        (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (4 4
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (4 4 (:REWRITE USE-ALL-<-2))
     (4 4 (:REWRITE USE-ALL-<))
     (4 4
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (4 4
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (4 4
        (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (4 4
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (4 4 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (4 4
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (3 3
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (3 3 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (1 1
        (:REWRITE CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX)))
(TRUE-LISTP-OF-ACONS-UNIQUE
     (158 10 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (108 54
          (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-CAR-WHEN-SYMBOL-TERM-ALISTP))
     (87 12 (:REWRITE DEFAULT-CAR))
     (54 54
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (43 10
         (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (17 17 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (17 17 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (17 17 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (17 17
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (10 10
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (10 5 (:REWRITE DEFAULT-<-2))
     (8 8
        (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
     (6 6
        (:REWRITE CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (5 5 (:REWRITE USE-ALL-CONSP-2))
     (5 5 (:REWRITE USE-ALL-CONSP))
     (5 5 (:REWRITE USE-ALL-<-2))
     (5 5 (:REWRITE USE-ALL-<))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-<-1))
     (5 5 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (5 5
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (5 5 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (5 5
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (3 3
        (:REWRITE EQUAL-OF-NON-NATP-AND-CAAR-WHEN-WHEN-BOUNDED-NATP-ALISTP)))
(NAT-LISTP-OF-STRIP-CDRS-OF-ACONS-UNIQUE
     (579 35 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (271 46 (:REWRITE DEFAULT-CDR))
     (220 110
          (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-CAR-WHEN-SYMBOL-TERM-ALISTP))
     (184 8 (:REWRITE USE-ALL-<-FOR-CAR))
     (146 46 (:REWRITE DEFAULT-CAR))
     (110 110
          (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (88 8 (:REWRITE USE-ALL-NATP-FOR-CAR))
     (88 8 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
     (73 57 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (64 16 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
     (57 57 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (57 57 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (57 57
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (50 34 (:REWRITE DEFAULT-<-2))
     (40 40 (:TYPE-PRESCRIPTION ALL-NATP))
     (35 35
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (34 34 (:REWRITE USE-ALL-<-2))
     (34 34 (:REWRITE USE-ALL-<))
     (34 34 (:REWRITE DEFAULT-<-1))
     (34 34
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (32 16
         (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
     (32 8 (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
     (18 18 (:REWRITE USE-ALL-<=-2))
     (18 18 (:REWRITE USE-ALL-<=))
     (18 18
         (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (18 18
         (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (16 16 (:TYPE-PRESCRIPTION ALL-<))
     (16 16 (:REWRITE USE-ALL-CONSP-2))
     (16 16 (:REWRITE USE-ALL-CONSP))
     (16 16 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (16 16
         (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
     (16 16 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
     (16 16 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (16 16
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (16 8
         (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
     (16 8
         (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
     (11 11 (:REWRITE USE-ALL-NATP-2))
     (11 11 (:REWRITE USE-ALL-NATP))
     (11 11
         (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (8 8 (:TYPE-PRESCRIPTION ALL-INTEGERP))
     (8 8
        (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
     (8 8
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
     (8 8 (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
     (8 8 (:REWRITE ALL-<-WHEN-NOT-CONSP))
     (8 8 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
     (8 8 (:REWRITE ALL-<-TRANSITIVE-FREE))
     (8 8 (:REWRITE ALL-<-TRANSITIVE))
     (7 7
        (:REWRITE CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (4 4
        (:REWRITE EQUAL-OF-NON-NATP-AND-CAAR-WHEN-WHEN-BOUNDED-NATP-ALISTP)))
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-ACONS-UNIQUE
     (225 14 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (158 79
          (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-CAR-WHEN-SYMBOL-TERM-ALISTP))
     (104 14 (:REWRITE DEFAULT-CAR))
     (79 79
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (60 11
         (:REWRITE ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-NOT-CONSP))
     (56 14
         (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (23 23 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (23 23 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (23 23 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (23 23
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (16 8 (:REWRITE DEFAULT-<-2))
     (14 14
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (10 10 (:TYPE-PRESCRIPTION ACONS-UNIQUE))
     (9 3
        (:REWRITE USE-ALL-PAIR-WITH-RATIONAL-CDRP))
     (8 8 (:REWRITE USE-ALL-CONSP-2))
     (8 8 (:REWRITE USE-ALL-CONSP))
     (8 8 (:REWRITE USE-ALL-<-2))
     (8 8 (:REWRITE USE-ALL-<))
     (8 8 (:REWRITE DEFAULT-CDR))
     (8 8 (:REWRITE DEFAULT-<-1))
     (8 8 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (8 8
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (8 8 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (8 8
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (7 7
        (:REWRITE CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (6 6 (:TYPE-PRESCRIPTION MEMBERP))
     (5 5 (:REWRITE USE-ALL-RATIONALP-2))
     (5 5 (:REWRITE USE-ALL-RATIONALP))
     (4 4
        (:REWRITE EQUAL-OF-NON-NATP-AND-CAAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (3 3
        (:REWRITE USE-ALL-PAIR-WITH-RATIONAL-CDRP-2)))
(TABULATE-DAG-FNS-AUX
     (2037 109 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (1501 52
           (:REWRITE WEAK-DAGP-AUX-WHEN-PSEUDO-DAGP-AUX-2))
     (1224 39 (:REWRITE USE-ALL-<-FOR-CAR))
     (927 36 (:DEFINITION TOP-NODENUM))
     (884 442
          (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-CAR-WHEN-SYMBOL-TERM-ALISTP))
     (560 256 (:REWRITE DEFAULT-CAR))
     (544 27 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
     (465 465
          (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (464 27 (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
     (395 28 (:REWRITE PSEUDO-DAGP-AUX-OF-CDR))
     (346 83 (:REWRITE DEFAULT-+-2))
     (265 151 (:REWRITE DEFAULT-CDR))
     (246 9 (:DEFINITION STRIP-CDRS))
     (237 222 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (222 222 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (222 222 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (222 222
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (178 23 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (176 124 (:REWRITE DEFAULT-<-2))
     (156 18
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (124 124 (:REWRITE USE-ALL-<-2))
     (124 124 (:REWRITE USE-ALL-<))
     (124 124 (:REWRITE DEFAULT-<-1))
     (124 124
          (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (124 52
          (:REWRITE WEAK-DAGP-AUX-WHEN-PSEUDO-DAGP))
     (121 121
          (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
     (110 110 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (109 109
          (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (106 106
          (:REWRITE CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (90 45
         (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
     (83 83 (:REWRITE USE-ALL-CONSP-2))
     (83 83 (:REWRITE USE-ALL-CONSP))
     (83 83 (:REWRITE DEFAULT-+-1))
     (83 83 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (70 26 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (66 66 (:TYPE-PRESCRIPTION ALL-<))
     (61 61
         (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (61 23
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (59 59 (:REWRITE USE-ALL-NATP-2))
     (59 59 (:REWRITE USE-ALL-NATP))
     (57 57
         (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
     (57 3 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (54 27
         (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
     (54 27
         (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
     (52 52 (:TYPE-PRESCRIPTION ALL-CONSP))
     (52 52
         (:REWRITE WEAK-DAGP-AUX-WHEN-PSEUDO-DAGP-AUX))
     (51 3 (:LINEAR LEN-OF-CDR-LINEAR))
     (50 25
         (:REWRITE BOUNDED-DAG-EXPRP-WHEN-MYQUOTEP-CHEAP))
     (46 23
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (45 45 (:REWRITE USE-ALL-<=-2))
     (45 45 (:REWRITE USE-ALL-<=))
     (45 45
         (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (45 45
         (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
     (45 45 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
     (45 45 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (45 45
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (42 42
         (:REWRITE NATP-OF-CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (42 21
         (:REWRITE INTEGERP-OF-CAR-OF-CAR-WHEN-WEAK-DAGP-CHEAP))
     (42 21
         (:REWRITE INTEGERP-OF-CAR-OF-CAR-WHEN-WEAK-DAGP-AUX-CHEAP))
     (39 39
         (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
     (35 7 (:REWRITE ALL-CONSP-OF-CDR))
     (34 34
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (33 33
         (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (33 33
         (:REWRITE <-OF-0-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (27 27 (:TYPE-PRESCRIPTION ALL-INTEGERP))
     (27 27
         (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
     (27 27
         (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
     (27 27 (:REWRITE ALL-<-WHEN-NOT-CONSP))
     (27 27 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
     (27 27 (:REWRITE ALL-<-TRANSITIVE-FREE))
     (27 27 (:REWRITE ALL-<-TRANSITIVE))
     (27 27
         (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (26 26
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (25 25 (:TYPE-PRESCRIPTION MYQUOTEP))
     (25 25
         (:REWRITE BOUNDED-DAG-EXPRP-WHEN-SYMBOLP-CHEAP))
     (25 25
         (:REWRITE BOUNDED-DAG-EXPRP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
     (23 23
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (23 23
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (23 23
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (21 21 (:TYPE-PRESCRIPTION WEAK-DAGP))
     (21 21
         (:REWRITE INTEGERP-OF-CAAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (21 21
         (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (21 7 (:REWRITE FOLD-CONSTS-IN-+))
     (19 19
         (:REWRITE PSEUDO-DAGP-AUX-OF-CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (18 18 (:REWRITE USE-ALL-RATIONALP-2))
     (18 18 (:REWRITE USE-ALL-RATIONALP))
     (9 9
        (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
     (8 8
        (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (7 7
        (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (7 7 (:REWRITE EQUAL-OF-LEN-AND-0))
     (4 4
        (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP)))
(TRUE-LISTP-OF-TABULATE-DAG-FNS-AUX
     (773 44 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (299 19 (:REWRITE DEFAULT-+-2))
     (286 46 (:REWRITE DEFAULT-CDR))
     (273 11 (:REWRITE LEN-OF-CDR))
     (248 2
          (:REWRITE ACL2-NUMBERP-OF-LOOKUP-EQUAL))
     (160 2 (:DEFINITION NAT-LISTP))
     (136 8 (:REWRITE EQUAL-OF-LEN-AND-0))
     (115 25
          (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (82 2 (:DEFINITION STRIP-CDRS))
     (72 2 (:DEFINITION NATP))
     (67 65 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (65 65 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (65 65 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (65 65
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (48 48 (:REWRITE DEFAULT-CAR))
     (44 44
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (39 22 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE USE-ALL-<-FOR-CAR))
     (28 28 (:REWRITE USE-ALL-CONSP-2))
     (28 28 (:REWRITE USE-ALL-CONSP))
     (28 28 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (24 18
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-CONSP-CHEAP))
     (24 8
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (22 22 (:REWRITE USE-ALL-<-2))
     (22 22 (:REWRITE USE-ALL-<))
     (22 22 (:REWRITE DEFAULT-<-1))
     (22 22
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (20 20 (:TYPE-PRESCRIPTION NAT-LISTP))
     (19 19 (:REWRITE DEFAULT-+-1))
     (18 18
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (18 2 (:REWRITE USE-ALL-NATP-FOR-CAR))
     (18 2 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
     (16 8 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (16 8
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (16 8
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (12 12
         (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
     (11 11
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (10 10 (:TYPE-PRESCRIPTION STRIP-CDRS))
     (10 10 (:TYPE-PRESCRIPTION ALL-NATP))
     (9 9 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (9 9
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (8 8
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (8 8 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (8 8 (:TYPE-PRESCRIPTION ALL-CONSP))
     (8 8 (:REWRITE USE-ALL-RATIONALP-2))
     (8 8 (:REWRITE USE-ALL-RATIONALP))
     (8 8
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (8 8
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (8 8
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (8 4
        (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
     (8 4 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
     (7 7
        (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
     (4 4 (:TYPE-PRESCRIPTION ALL-<))
     (4 4
        (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
     (4 4 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
     (4 2
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
     (4 2
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
     (4 2 (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
     (2 2 (:TYPE-PRESCRIPTION ALL-INTEGERP))
     (2 2 (:REWRITE USE-ALL-NATP-2))
     (2 2 (:REWRITE USE-ALL-NATP))
     (2 2 (:REWRITE USE-ALL-<=-2))
     (2 2 (:REWRITE USE-ALL-<=))
     (2 2
        (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
     (2 2
        (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (2 2
        (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (2 2
        (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (2 2
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
     (2 2 (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
     (2 2 (:REWRITE ALL-<-WHEN-NOT-CONSP))
     (2 2 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
     (2 2 (:REWRITE ALL-<-TRANSITIVE-FREE))
     (2 2 (:REWRITE ALL-<-TRANSITIVE)))
(ALISTP-OF-TABULATE-DAG-FNS-AUX
     (2158 130 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (615 99 (:REWRITE DEFAULT-CDR))
     (471 40 (:REWRITE DEFAULT-+-2))
     (372 3
          (:REWRITE ACL2-NUMBERP-OF-LOOKUP-EQUAL))
     (240 3 (:DEFINITION NAT-LISTP))
     (188 175 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (176 47 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (173 173 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (173 173 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (173 173
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (159 103 (:REWRITE DEFAULT-CAR))
     (150 80 (:REWRITE DEFAULT-<-2))
     (130 130
          (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (123 3 (:DEFINITION STRIP-CDRS))
     (112 47
          (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (108 3 (:DEFINITION NATP))
     (100 100 (:REWRITE USE-ALL-CONSP-2))
     (100 100 (:REWRITE USE-ALL-CONSP))
     (100 100 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (94 47
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (80 80 (:REWRITE USE-ALL-<-2))
     (80 80 (:REWRITE USE-ALL-<))
     (80 80 (:REWRITE DEFAULT-<-1))
     (80 80
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (65 65 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (65 65 (:TYPE-PRESCRIPTION ALL-CONSP))
     (57 3 (:REWRITE USE-ALL-<-FOR-CAR))
     (54 54 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (54 54
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (51 51
         (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (47 47
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (47 47
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (47 47
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (47 47
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (46 46
         (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (42 2 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (40 40 (:REWRITE DEFAULT-+-1))
     (39 29
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-CONSP-CHEAP))
     (39 13
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (32 26
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (32 26 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (30 30 (:TYPE-PRESCRIPTION NAT-LISTP))
     (29 29
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (27 3 (:REWRITE USE-ALL-NATP-FOR-CAR))
     (27 3 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
     (23 23
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (15 15 (:TYPE-PRESCRIPTION STRIP-CDRS))
     (15 15 (:TYPE-PRESCRIPTION ALL-NATP))
     (14 14
         (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
     (13 13 (:REWRITE USE-ALL-RATIONALP-2))
     (13 13 (:REWRITE USE-ALL-RATIONALP))
     (12 6
         (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
     (12 6 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
     (6 6 (:TYPE-PRESCRIPTION ALL-<))
     (6 6
        (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
     (6 6 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
     (6 3
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
     (6 3
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
     (6 3 (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
     (3 3 (:TYPE-PRESCRIPTION ALL-INTEGERP))
     (3 3 (:REWRITE USE-ALL-NATP-2))
     (3 3 (:REWRITE USE-ALL-NATP))
     (3 3 (:REWRITE USE-ALL-<=-2))
     (3 3 (:REWRITE USE-ALL-<=))
     (3 3
        (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
     (3 3
        (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (3 3
        (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (3 3
        (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (3 3
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
     (3 3 (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
     (3 3 (:REWRITE ALL-<-WHEN-NOT-CONSP))
     (3 3 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
     (3 3 (:REWRITE ALL-<-TRANSITIVE-FREE))
     (3 3 (:REWRITE ALL-<-TRANSITIVE)))
(TABULATE-DAG-FNS
     (20 10
         (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-CAR-WHEN-SYMBOL-TERM-ALISTP))
     (10 10
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP)))
(RATIONALP-OF-LOOKUP-EQUAL
     (1150 66 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (914 62
          (:REWRITE ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-NOT-CONSP))
     (816 32
          (:REWRITE ALL-PAIR-WITH-RATIONAL-CDRP-OF-CDR))
     (396 40 (:REWRITE LEN-OF-CDR))
     (135 19 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (130 22
          (:REWRITE USE-ALL-PAIR-WITH-RATIONAL-CDRP-FOR-CAR))
     (118 118 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (112 112 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (112 112 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (112 112
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (95 95 (:REWRITE DEFAULT-CDR))
     (88 54 (:REWRITE DEFAULT-<-2))
     (66 66 (:REWRITE USE-ALL-CONSP-2))
     (66 66 (:REWRITE USE-ALL-CONSP))
     (66 66 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (66 66
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (62 62
         (:REWRITE ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-NOT-CONSP-CHEAP))
     (57 19
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (54 54 (:TYPE-PRESCRIPTION ALL-CONSP))
     (54 54 (:REWRITE USE-ALL-<-2))
     (54 54 (:REWRITE USE-ALL-<))
     (54 54 (:REWRITE DEFAULT-<-1))
     (54 54
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (48 42 (:REWRITE DEFAULT-+-2))
     (42 42 (:REWRITE DEFAULT-+-1))
     (40 40 (:REWRITE DEFAULT-CAR))
     (40 8 (:REWRITE ALL-CONSP-OF-CDR))
     (38 38 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (38 19
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (33 33 (:REWRITE USE-ALL-RATIONALP-2))
     (33 33 (:REWRITE USE-ALL-RATIONALP))
     (32 32
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-CONSP-CHEAP))
     (32 32
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (32 32
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (30 30 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (30 30
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (27 27
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (27 27 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (24 8 (:REWRITE FOLD-CONSTS-IN-+))
     (22 22
         (:REWRITE USE-ALL-PAIR-WITH-RATIONAL-CDRP-2))
     (22 22
         (:REWRITE USE-ALL-PAIR-WITH-RATIONAL-CDRP))
     (19 19
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (19 19
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (19 19
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (19 19
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (8 8
        (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (4 4 (:REWRITE EQUAL-OF-LEN-AND-0)))
(ALL-PAIR-WITH-RATIONAL-CDRP-OF-TABULATE-DAG-FNS-AUX
     (1811 105 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (716 37 (:REWRITE DEFAULT-+-2))
     (621 22
          (:REWRITE ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-NOT-CONSP))
     (620 5
          (:REWRITE ACL2-NUMBERP-OF-LOOKUP-EQUAL))
     (599 91 (:REWRITE DEFAULT-CDR))
     (400 5 (:DEFINITION NAT-LISTP))
     (205 5 (:DEFINITION STRIP-CDRS))
     (180 5 (:DEFINITION NATP))
     (160 149 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (148 148 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (148 148 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (148 148
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (114 62 (:REWRITE DEFAULT-<-2))
     (105 105
          (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (97 97 (:REWRITE DEFAULT-CAR))
     (95 5 (:REWRITE USE-ALL-<-FOR-CAR))
     (72 72 (:REWRITE USE-ALL-CONSP-2))
     (72 72 (:REWRITE USE-ALL-CONSP))
     (72 72 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (62 62 (:REWRITE USE-ALL-<-2))
     (62 62 (:REWRITE USE-ALL-<))
     (62 62 (:REWRITE DEFAULT-<-1))
     (62 62
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (56 46
         (:TYPE-PRESCRIPTION TABULATE-DAG-FNS-AUX))
     (50 50 (:TYPE-PRESCRIPTION NAT-LISTP))
     (47 18 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (46 36
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-CONSP-CHEAP))
     (45 5 (:REWRITE USE-ALL-NATP-FOR-CAR))
     (45 5 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
     (43 16
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (39 22
         (:REWRITE ALL-PAIR-WITH-RATIONAL-CDRP-WHEN-NOT-CONSP-CHEAP))
     (39 18
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (38 38 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (38 38
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (37 37 (:REWRITE DEFAULT-+-1))
     (36 36
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (36 18
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (25 25 (:TYPE-PRESCRIPTION STRIP-CDRS))
     (25 25 (:TYPE-PRESCRIPTION ALL-NATP))
     (22 22 (:TYPE-PRESCRIPTION ACONS-UNIQUE))
     (21 21 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (21 21 (:TYPE-PRESCRIPTION ALL-CONSP))
     (21 1 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (20 10
         (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
     (20 10 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
     (19 19
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (18 18
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (18 18
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (18 18
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (18 18
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (14 14 (:REWRITE USE-ALL-RATIONALP-2))
     (14 14 (:REWRITE USE-ALL-RATIONALP))
     (13 13
         (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
     (10 10 (:TYPE-PRESCRIPTION ALL-<))
     (10 10
         (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
     (10 10 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
     (10 5
         (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
     (10 5
         (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
     (10 5 (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
     (5 5 (:TYPE-PRESCRIPTION ALL-INTEGERP))
     (5 5 (:REWRITE USE-ALL-NATP-2))
     (5 5 (:REWRITE USE-ALL-NATP))
     (5 5 (:REWRITE USE-ALL-<=-2))
     (5 5 (:REWRITE USE-ALL-<=))
     (5 5
        (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
     (5 5
        (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (5 5
        (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (5 5
        (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (5 5
        (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
     (5 5 (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
     (5 5 (:REWRITE ALL-<-WHEN-NOT-CONSP))
     (5 5 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
     (5 5 (:REWRITE ALL-<-TRANSITIVE-FREE))
     (5 5 (:REWRITE ALL-<-TRANSITIVE))
     (4 4
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (4 4 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP)))
(ALISTP-OF-MERGE-CDR-<
     (4813 296 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (1225 87 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (821 95 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (410 14 (:REWRITE ALL-CONSP-OF-REVAPPEND))
     (395 371 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (371 371 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (371 371 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (371 371
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (357 165 (:REWRITE DEFAULT-CAR))
     (296 296
          (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (269 269 (:REWRITE USE-ALL-<-2))
     (269 269 (:REWRITE USE-ALL-<))
     (269 269
          (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (260 260 (:REWRITE USE-ALL-CONSP-2))
     (260 260 (:REWRITE USE-ALL-CONSP))
     (260 260 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (241 87
          (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (222 222
          (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (222 222
          (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (213 213
          (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (207 207
          (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (190 190 (:TYPE-PRESCRIPTION ALL-CONSP))
     (174 87
          (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (165 15 (:REWRITE LEN-OF-CDR))
     (154 154 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (109 95
          (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (102 34
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (87 87
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (87 87
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (87 87
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (87 87
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (34 34 (:REWRITE USE-ALL-RATIONALP-2))
     (34 34 (:REWRITE USE-ALL-RATIONALP))
     (32 32 (:REWRITE USE-ALL-<=-2))
     (32 32 (:REWRITE USE-ALL-<=))
     (24 24
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (20 4 (:REWRITE ALL-CONSP-OF-CDR))
     (15 15 (:REWRITE DEFAULT-+-2))
     (15 15 (:REWRITE DEFAULT-+-1))
     (6 6
        (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN)))
(CONSP-OF-CAR-WHEN-ALISTP
     (177 13 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (64 4 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (48 4 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (35 5 (:REWRITE DEFAULT-CAR))
     (16 8 (:REWRITE DEFAULT-<-2))
     (15 15 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (13 13 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (13 13 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (13 13
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (13 13
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (12 4
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (12 2 (:REWRITE ALISTP-OF-CDR))
     (11 11 (:REWRITE USE-ALL-CONSP-2))
     (11 11 (:REWRITE USE-ALL-CONSP))
     (11 11 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (8 8 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (8 8 (:TYPE-PRESCRIPTION ALL-CONSP))
     (8 8 (:REWRITE USE-ALL-<-2))
     (8 8 (:REWRITE USE-ALL-<))
     (8 8 (:REWRITE DEFAULT-<-1))
     (8 8
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (8 8 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (8 8
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (8 4
        (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (7 7
        (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (7 7
        (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (4 4
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (4 4
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (4 4
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (4 4
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (4 4
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (2 2 (:REWRITE DEFAULT-CDR))
     (2 1 (:REWRITE DEFAULT-+-2))
     (1 1 (:REWRITE DEFAULT-+-1)))
(ALISTP-OF-MV-NTH-0-OF-SPLIT-LIST-FAST-AUX
     (2339 153 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (675 46 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (464 52 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (361 104 (:REWRITE DEFAULT-CDR))
     (248 124 (:REWRITE DEFAULT-<-2))
     (182 182 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (182 182 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (182 182 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (182 182
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (175 175
          (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (167 167
          (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (153 153
          (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (147 147 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (147 60 (:REWRITE DEFAULT-CAR))
     (132 46
          (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (131 124 (:REWRITE DEFAULT-<-1))
     (129 129 (:REWRITE USE-ALL-CONSP-2))
     (129 129 (:REWRITE USE-ALL-CONSP))
     (124 124 (:REWRITE USE-ALL-<-2))
     (124 124 (:REWRITE USE-ALL-<))
     (124 124
          (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (108 108
          (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (108 108
          (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (104 104 (:TYPE-PRESCRIPTION ALL-CONSP))
     (92 46
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (86 86 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (56 28 (:REWRITE DEFAULT-+-2))
     (52 52
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (46 46
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (46 46
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (46 46
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (46 46
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (45 9 (:REWRITE ALL-CONSP-OF-CDR))
     (28 28 (:REWRITE DEFAULT-+-1))
     (20 20
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (14 14
         (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (10 10 (:REWRITE USE-ALL-<=-2))
     (10 10 (:REWRITE USE-ALL-<=))
     (2 2
        (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN)))
(ALISTP-OF-MV-NTH-1-OF-SPLIT-LIST-FAST-AUX
     (2004 124 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (628 45 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (421 51 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (319 87 (:REWRITE DEFAULT-CDR))
     (234 118 (:REWRITE DEFAULT-<-2))
     (209 209 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (209 209 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (209 209 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (209 209
          (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (162 162
          (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (161 161
          (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (156 55 (:REWRITE DEFAULT-CAR))
     (139 118 (:REWRITE DEFAULT-<-1))
     (129 45
          (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (124 124
          (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (118 118 (:REWRITE USE-ALL-<-2))
     (118 118 (:REWRITE USE-ALL-<))
     (118 118
          (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (117 117 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (106 106 (:REWRITE USE-ALL-CONSP-2))
     (106 106 (:REWRITE USE-ALL-CONSP))
     (102 102 (:TYPE-PRESCRIPTION ALL-CONSP))
     (97 97 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (97 97
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (95 48 (:REWRITE DEFAULT-+-2))
     (90 45
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (84 84 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (51 51
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (48 48 (:REWRITE DEFAULT-+-1))
     (45 45
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (45 45
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (45 45
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (45 45
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (45 9 (:REWRITE ALL-CONSP-OF-CDR))
     (24 12 (:REWRITE DEFAULT-*-2))
     (19 19 (:REWRITE USE-ALL-<=-2))
     (19 19 (:REWRITE USE-ALL-<=))
     (18 18
         (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (14 14
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (12 12 (:REWRITE DEFAULT-*-1))
     (2 2
        (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN)))
(ALISTP-OF-MV-NTH-0-OF-SPLIT-LIST-FAST
     (86 4 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (68 1 (:DEFINITION ALISTP))
     (65 1 (:DEFINITION SPLIT-LIST-FAST-AUX))
     (14 1 (:REWRITE LEN-OF-CDR))
     (10 4
         (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (8 8 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (8 8 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (8 8 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (8 8
        (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (8 4 (:REWRITE DEFAULT-<-2))
     (6 1 (:REWRITE ALISTP-OF-CDR))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 1 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (4 4 (:REWRITE USE-ALL-CONSP-2))
     (4 4 (:REWRITE USE-ALL-CONSP))
     (4 4 (:REWRITE USE-ALL-<-2))
     (4 4 (:REWRITE USE-ALL-<))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (4 4
        (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (4 4
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (3 3
        (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (3 3
        (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (3 3 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (3 3
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (3 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (2 2 (:TYPE-PRESCRIPTION ALL-CONSP))
     (2 2 (:REWRITE DEFAULT-CAR))
     (2 1 (:REWRITE DEFAULT-+-2))
     (2 1
        (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (1 1
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (1 1
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (1 1 (:REWRITE EQUAL-OF-LEN-AND-0))
     (1 1 (:REWRITE DEFAULT-+-1))
     (1 1
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (1 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (1 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (1 1
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (1 1 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP)))
(ALISTP-OF-MV-NTH-1-OF-SPLIT-LIST-FAST
     (86 4 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (68 1 (:DEFINITION ALISTP))
     (65 1 (:DEFINITION SPLIT-LIST-FAST-AUX))
     (14 1 (:REWRITE LEN-OF-CDR))
     (10 4
         (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (8 8 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (8 8 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (8 8 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (8 8
        (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (8 4 (:REWRITE DEFAULT-<-2))
     (6 1 (:REWRITE ALISTP-OF-CDR))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 1 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (4 4 (:REWRITE USE-ALL-CONSP-2))
     (4 4 (:REWRITE USE-ALL-CONSP))
     (4 4 (:REWRITE USE-ALL-<-2))
     (4 4 (:REWRITE USE-ALL-<))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (4 4
        (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (4 4
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (3 3
        (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (3 3
        (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (3 3 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (3 3
        (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (3 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (2 2 (:TYPE-PRESCRIPTION ALL-CONSP))
     (2 2 (:REWRITE DEFAULT-CAR))
     (2 1 (:REWRITE DEFAULT-+-2))
     (2 1
        (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (1 1
        (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (1 1
        (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (1 1 (:REWRITE EQUAL-OF-LEN-AND-0))
     (1 1 (:REWRITE DEFAULT-+-1))
     (1 1
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (1 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (1 1
        (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (1 1
        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (1 1 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP)))
(ALISTP-OF-MERGE-SORT-CDR-<
     (277 16 (:REWRITE CONSP-OF-MERGE-SORT-CDR-<))
     (190 21 (:REWRITE DEFAULT-CDR))
     (189 11 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (141 12 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (77 12 (:REWRITE DEFAULT-CAR))
     (72 12 (:REWRITE ALISTP-OF-CDR))
     (69 36 (:REWRITE DEFAULT-<-2))
     (67 62 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (61 61 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (61 61 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (61 61
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (60 4
         (:REWRITE CONSP-OF-MV-NTH-0-OF-SPLIT-LIST-FAST))
     (54 54
         (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (45 45 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (37 37 (:REWRITE USE-ALL-CONSP-2))
     (37 37 (:REWRITE USE-ALL-CONSP))
     (36 36 (:REWRITE USE-ALL-<-2))
     (36 36 (:REWRITE USE-ALL-<))
     (36 36 (:REWRITE DEFAULT-<-1))
     (36 36
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (33 11
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
     (32 32
         (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
     (32 32
         (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
     (30 30 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (30 30
         (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (30 4
         (:REWRITE CONSP-OF-MV-NTH-1-OF-SPLIT-LIST-FAST))
     (24 24 (:TYPE-PRESCRIPTION ALL-CONSP))
     (22 22 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (22 11
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (16 8 (:REWRITE DEFAULT-+-2))
     (13 1 (:REWRITE ALL-CONSP-OF-CDR))
     (12 12
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (11 11
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (11 11
         (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
     (11 11
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
     (11 11
         (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
     (10 10
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-MV-NTH-0-OF-SPLIT-LIST-FAST))
     (8 8
        (:TYPE-PRESCRIPTION TRUE-LISTP-OF-MV-NTH-1-OF-SPLIT-LIST-FAST))
     (8 8 (:REWRITE DEFAULT-+-1))
     (8 1 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (6 6
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (4 4 (:REWRITE USE-ALL-<=-2))
     (4 4 (:REWRITE USE-ALL-<=)))
(DAG-INFO-FN
     (108 3 (:DEFINITION TABULATE-DAG-FNS-AUX))
     (92 46
         (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-CAR-WHEN-SYMBOL-TERM-ALISTP))
     (57 3 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (46 46
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (33 3 (:REWRITE LEN-OF-CDR))
     (13 12 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (12 12 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (12 12 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (12 12
         (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (12 12 (:REWRITE DEFAULT-CDR))
     (11 11 (:REWRITE DEFAULT-CAR))
     (9 3
        (:REWRITE LOOKUP-EQ-BECOMES-LOOKUP-EQUAL))
     (8 1 (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (4 4 (:REWRITE USE-ALL-<-2))
     (4 4 (:REWRITE USE-ALL-<))
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (3 3 (:REWRITE USE-ALL-CONSP-2))
     (3 3 (:REWRITE USE-ALL-CONSP))
     (3 3
        (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
     (3 3
        (:REWRITE LOOKUP-EQUAL-WHEN-NOT-CONSP-CHEAP))
     (3 3
        (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (3 3 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE DEFAULT-+-1))
     (3 3 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (3 3
        (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (3 3
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (2 2 (:TYPE-PRESCRIPTION ALL-DARGP))
     (2 1
        (:REWRITE ALL-DARGP-WHEN-ALL-MYQUOTEP-CHEAP))
     (1 1 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
     (1 1 (:REWRITE USE-ALL-<=-2))
     (1 1 (:REWRITE USE-ALL-<=))
     (1 1
        (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
     (1 1
        (:REWRITE ALL-DARGP-WHEN-NOT-CONSP-CHEAP))
     (1 1 (:REWRITE ALL-DARGP-WHEN-NOT-CONSP))
     (1 1
        (:REWRITE ALL-DARGP-WHEN-ALL-DARGP-LESS-THAN))
     (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
