(MAKE-DAG-INDICES-AUX
 (1497 1497 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (940 470
      (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (470 470
      (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (468 36 (:DEFINITION NTH))
 (268 134
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (228 57
      (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (180 72 (:REWRITE NTH-WHEN-NOT-CDDR))
 (180 18
      (:LINEAR <-OF-NTH-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-LINEAR))
 (144 18
      (:LINEAR NONNEG-OF-NTH-OF-DARGS-OF-AREF1))
 (144 18
      (:LINEAR <-OF-NTH-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (134 39
      (:REWRITE DAG-VARIABLE-ALISTP-FORWARD-TO-ALIST))
 (114 114
      (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (101 21
      (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (85 85 (:REWRITE USE-ALL-CONSP-2))
 (85 85 (:REWRITE USE-ALL-CONSP))
 (82 79 (:REWRITE DEFAULT-+-1))
 (79 79 (:REWRITE DEFAULT-+-2))
 (76 76
     (:TYPE-PRESCRIPTION DAG-VARIABLE-ALISTP))
 (60 5
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (57 57
     (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (57 57
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (56 32 (:REWRITE DEFAULT-<-1))
 (55 15 (:REWRITE USE-ALL-CONSP-FOR-CAR))
 (50 50 (:REWRITE DEFAULT-CDR))
 (39 39
     (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
 (38 38
     (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (38 32 (:REWRITE DEFAULT-<-2))
 (35 15
     (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
 (34 34
     (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
 (33 33 (:REWRITE DEFAULT-CAR))
 (32 32 (:REWRITE USE-ALL-<=-2))
 (32 32 (:REWRITE USE-ALL-<=))
 (32 32 (:REWRITE USE-ALL-<-2))
 (32 32 (:REWRITE USE-ALL-<))
 (32 32
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (31
   10
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (30 15
     (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
 (30 10
     (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (28 2
     (:REWRITE ALL-DARGP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (24 12
     (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DIMENSIONS))
 (24 6
     (:REWRITE NOT-<-OF-ALEN1-WHEN-PSEUDO-DAG-ARRAYP))
 (20 20 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
 (20 20 (:TYPE-PRESCRIPTION ALL-CONSP))
 (20 3
     (:REWRITE DAG-VARIABLE-ALISTP-OF-CONS-OF-CONS))
 (15 15
     (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
 (15 15
     (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
 (15 15
     (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
 (14 14 (:LINEAR ARRAY2P-LINEAR))
 (14 1
     (:REWRITE SYMBOLP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-2))
 (12 12 (:REWRITE ZP-OPEN))
 (10 10 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (10 10 (:REWRITE USE-ALL-RATIONALP-2))
 (10 10 (:REWRITE USE-ALL-RATIONALP))
 (10 10
     (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (10 10
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (10 10
     (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
 (10 10 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
 (10 5
     (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (8 8
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (7 7 (:REWRITE <-OF-+-OF-1-STRENGTHEN))
 (6 3 (:REWRITE DEFAULT-UNARY-MINUS))
 (5 5 (:REWRITE USE-ALL-NATP-2))
 (5 5 (:REWRITE USE-ALL-NATP))
 (5 5
    (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (4 4
    (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NO-ATOMS-CHEAP))
 (2 2
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (2 1
    (:REWRITE SYMBOLP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP)))
(MV-NTH-0-OF-MAKE-DAG-INDICES-AUX
 (597 26
      (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (468 26
      (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (460 230
      (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (328 164
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (230 230
      (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (196 49
      (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (184
   23
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (164 164
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (158 89 (:REWRITE DEFAULT-<-2))
 (158 89 (:REWRITE DEFAULT-<-1))
 (156 78
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (156 78
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (138 46
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (135 45 (:REWRITE FOLD-CONSTS-IN-+))
 (98 49 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (92 23
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (89 89 (:REWRITE USE-ALL-<=-2))
 (89 89 (:REWRITE USE-ALL-<=))
 (89 89 (:REWRITE USE-ALL-<-2))
 (89 89 (:REWRITE USE-ALL-<))
 (89 89
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (78
    78
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (77 77 (:REWRITE DEFAULT-+-2))
 (77 77 (:REWRITE DEFAULT-+-1))
 (52 52 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (52 52 (:REWRITE USE-ALL-CONSP-2))
 (52 52 (:REWRITE USE-ALL-CONSP))
 (51 26
     (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (49 49 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (49 49 (:TYPE-PRESCRIPTION ARRAY1P))
 (46 46 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (46 46 (:REWRITE USE-ALL-RATIONALP-2))
 (46 46 (:REWRITE USE-ALL-RATIONALP))
 (33 33
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (33 33
     (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (31 31 (:REWRITE DEFAULT-CAR))
 (25 25 (:REWRITE USE-ALL-NATP-2))
 (25 25 (:REWRITE USE-ALL-NATP))
 (25 25
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (23 23
     (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (23 23
     (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (23 23
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (1 1 (:TYPE-PRESCRIPTION ALL-DARGP)))
(MV-NTH-1-OF-MAKE-DAG-INDICES-AUX
 (412 18
      (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (324 18
      (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (254 127
      (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (206 103
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (133 67 (:REWRITE DEFAULT-<-2))
 (133 67 (:REWRITE DEFAULT-<-1))
 (132 44
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (132 33
      (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (127 127
      (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (120
   15
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (108 54
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (108 54
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (103 103
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (96 32 (:REWRITE FOLD-CONSTS-IN-+))
 (67 67 (:REWRITE USE-ALL-<=-2))
 (67 67 (:REWRITE USE-ALL-<=))
 (67 67 (:REWRITE USE-ALL-<-2))
 (67 67 (:REWRITE USE-ALL-<))
 (67 67
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (66 33 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (60 60 (:REWRITE DEFAULT-+-2))
 (60 60 (:REWRITE DEFAULT-+-1))
 (60 15
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (54
    54
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (44 44 (:REWRITE USE-ALL-RATIONALP-2))
 (44 44 (:REWRITE USE-ALL-RATIONALP))
 (36 36 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (34 34 (:REWRITE USE-ALL-CONSP-2))
 (34 34 (:REWRITE USE-ALL-CONSP))
 (34 18
     (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (33 33 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (33 33 (:TYPE-PRESCRIPTION ARRAY1P))
 (30 30 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (27 27 (:REWRITE USE-ALL-NATP-2))
 (27 27 (:REWRITE USE-ALL-NATP))
 (27 27
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (27 27
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (27 27
     (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (21 21 (:REWRITE DEFAULT-CAR))
 (15 15
     (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (15 15
     (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (15 15
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (2 2 (:TYPE-PRESCRIPTION ALL-DARGP))
 (2 2
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS)))
(MV-NTH-2-OF-MAKE-DAG-INDICES-AUX
 (254 127
      (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (166 83
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (137 6 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (133 67 (:REWRITE DEFAULT-<-2))
 (133 67 (:REWRITE DEFAULT-<-1))
 (132 44
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (127 127
      (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (124 31
      (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (108 6
      (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (83 83
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (67 67 (:REWRITE USE-ALL-<=-2))
 (67 67 (:REWRITE USE-ALL-<=))
 (67 67 (:REWRITE USE-ALL-<-2))
 (67 67 (:REWRITE USE-ALL-<))
 (67 67
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (62 31 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (48 16 (:REWRITE FOLD-CONSTS-IN-+))
 (44 44 (:REWRITE USE-ALL-RATIONALP-2))
 (44 44 (:REWRITE USE-ALL-RATIONALP))
 (40 40 (:REWRITE DEFAULT-+-2))
 (40 40 (:REWRITE DEFAULT-+-1))
 (40
   5
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (36 18
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (36 18
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (31 31 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (31 31 (:TYPE-PRESCRIPTION ARRAY1P))
 (27 27 (:REWRITE USE-ALL-NATP-2))
 (27 27 (:REWRITE USE-ALL-NATP))
 (27 27
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (27 27
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (27 27
     (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (22 22 (:REWRITE USE-ALL-CONSP-2))
 (22 22 (:REWRITE USE-ALL-CONSP))
 (20 5
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (18
    18
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (12 12 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (11 6
     (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (10 10 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (8 8 (:REWRITE DEFAULT-CAR))
 (5 5
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (5 5
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (5 5
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (2 2
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (1 1 (:TYPE-PRESCRIPTION ALL-DARGP)))
(DAG-PARENT-ARRAYP-OF-MV-NTH-0-OF-MAKE-DAG-INDICES-AUX
 (2020 1010
       (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (1924 962
       (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (1406 7
       (:REWRITE ALL-DARGP-LESS-THAN-WHEN-ALL-<))
 (1316 5 (:DEFINITION BOUNDED-DAG-EXPRP))
 (1304 20 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
 (1030 111 (:REWRITE DEFAULT-<-1))
 (999 53
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (828 1
      (:REWRITE RATIONALP-OF-ALEN1-WHEN-ARRAY1P))
 (824 1
      (:REWRITE ARRAY1P-OF-ADD-TO-PARENTS-OF-ATOMS-WITH-NAME))
 (777 777 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (721 14 (:DEFINITION NAT-LISTP))
 (588 7 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
 (572 7
      (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-WHEN-<-SIMPLE))
 (560 7
      (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-WHEN-BOUNDED-DAG-EXPRP))
 (406 7 (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
 (371 14 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
 (370 185
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (370 185
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (317 14
      (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (296 1
      (:REWRITE ALL-DARGP-OF-DARGS-WHEN-DAG-EXPRP0))
 (276 6
      (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-BOUNDED-DAG-EXPRP-OF-AREF1))
 (252 14
      (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (248 62
      (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (209
   9
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (189 111 (:REWRITE DEFAULT-<-2))
 (185
    185
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (167 20 (:REWRITE ALL-<-WHEN-NOT-CONSP))
 (161 14 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
 (154 7
      (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP))
 (120 20
      (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
 (111 111 (:REWRITE USE-ALL-<=-2))
 (111 111 (:REWRITE USE-ALL-<=))
 (111 111 (:REWRITE USE-ALL-<-2))
 (111 111 (:REWRITE USE-ALL-<))
 (111 111
      (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (105 105 (:TYPE-PRESCRIPTION NAT-LISTP))
 (102 27
      (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (97 27
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (77 14 (:REWRITE USE-ALL-NATP-FOR-CAR))
 (60 60 (:REWRITE USE-ALL-CONSP-2))
 (60 60 (:REWRITE USE-ALL-CONSP))
 (60 15
     (:REWRITE NOT-<-OF-ALEN1-WHEN-PSEUDO-DAG-ARRAYP))
 (54 54 (:TYPE-PRESCRIPTION ALL-<))
 (53 53 (:REWRITE USE-ALL-RATIONALP-2))
 (53 53 (:REWRITE USE-ALL-RATIONALP))
 (50 50 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (50 30 (:REWRITE DEFAULT-+-2))
 (50 2
     (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (49 49 (:TYPE-PRESCRIPTION ALL-NATP))
 (49 14
     (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
 (48 6
     (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (45 45
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (45 45
     (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (42 7
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP-CHEAP))
 (41 41 (:REWRITE USE-ALL-NATP-2))
 (41 41 (:REWRITE USE-ALL-NATP))
 (41 41
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (37 37 (:REWRITE DEFAULT-CAR))
 (36 36 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (30 30 (:REWRITE DEFAULT-+-1))
 (30 30 (:LINEAR ARRAY2P-LINEAR))
 (28 14 (:REWRITE USE-ALL-<-FOR-CAR))
 (28 14
     (:REWRITE INTEGERP-OF-CAR-WHEN-NAT-LISTP-CHEAP))
 (28 14
     (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
 (28 14
     (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
 (28 14
     (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
 (25 25
     (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (23 14
     (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (22 22
     (:REWRITE PSEUDO-DAG-ARRAYP-MONOTONE))
 (22 1 (:REWRITE ALL-DARGP-WHEN-NOT-CONSP))
 (21 6
     (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (20 20 (:REWRITE ALL-<-TRANSITIVE-FREE))
 (20 20 (:REWRITE ALL-<-TRANSITIVE))
 (18 18
     (:TYPE-PRESCRIPTION BOUNDED-DAG-EXPRP))
 (18 3
     (:REWRITE ALL-<-OF-ALEN1-WHEN-PSEUDO-DAG-ARRAYP-LIST))
 (17 3
     (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (16 16 (:REWRITE DEFAULT-CDR))
 (16 2 (:DEFINITION LEN))
 (15 5
     (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (14 14 (:TYPE-PRESCRIPTION ALL-INTEGERP))
 (14 14
     (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
 (14 14
     (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
 (14 7
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-ALL-MYQUOTEP-CHEAP))
 (12 12 (:TYPE-PRESCRIPTION LEN))
 (12 12 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (12 2
     (:REWRITE ALL-DARGP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (11 11
     (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (10 5
     (:REWRITE BOUNDED-DAG-EXPRP-WHEN-MYQUOTEP-CHEAP))
 (9 9
    (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NO-ATOMS-CHEAP))
 (9 9
    (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (7 7
    (:REWRITE ALL-DARGP-LESS-THAN-MONOTONE))
 (6 6
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-LIST))
 (6 6
    (:REWRITE DAG-EXPRP0-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (6 6
    (:REWRITE DAG-EXPRP0-WHEN-BOUNDED-DAG-EXPRP))
 (6 6
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (6 1
    (:REWRITE ALL-DARGP-WHEN-NOT-CONSP-CHEAP))
 (5 5 (:TYPE-PRESCRIPTION MYQUOTEP))
 (5 5
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-SYMBOLP-CHEAP))
 (5 5
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (5 5 (:REWRITE BOUNDED-DAG-EXPRP-MONOTONE))
 (4 4 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (4 4 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (4 4
    (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (3 3
    (:REWRITE PSEUDO-DAG-ARRAYP-LIST-WHEN-ALL-DARGP-LESS-THAN-SPECIAL-ALT))
 (3 3
    (:REWRITE PSEUDO-DAG-ARRAYP-LIST-WHEN-ALL-DARGP-LESS-THAN-SPECIAL))
 (3 3
    (:REWRITE PSEUDO-DAG-ARRAYP-LIST-WHEN-ALL-DARGP-LESS-THAN))
 (3 3
    (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-BETTER))
 (2 2
    (:REWRITE ALL-DARGP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (2 1
    (:REWRITE ALL-DARGP-WHEN-ALL-MYQUOTEP-CHEAP))
 (1 1
    (:REWRITE ARRAY1P-WHEN-PSEUDO-DAG-ARRAYP))
 (1 1
    (:REWRITE ALL-DARGP-WHEN-ALL-DARGP-LESS-THAN)))
(ALEN1-OF-MV-NTH-0-OF-MAKE-DAG-INDICES-AUX
 (1840 866 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (866 866 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (348 174
      (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (300 150
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (296 1
      (:REWRITE ALL-DARGP-OF-DARGS-WHEN-DAG-EXPRP0))
 (270 2
      (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-BOUNDED-DAG-EXPRP-OF-AREF1))
 (244 1 (:DEFINITION BOUNDED-DAG-EXPRP))
 (188 1
      (:REWRITE ALL-DARGP-LESS-THAN-WHEN-ALL-<))
 (183 8 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (176 2 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
 (144 8
      (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (143
   7
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (120 30
      (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (114 38
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (108 108
      (:TYPE-PRESCRIPTION ADD-TO-PARENTS-OF-ATOMS-WITH-NAME))
 (106 58 (:REWRITE DEFAULT-<-2))
 (106 58 (:REWRITE DEFAULT-<-1))
 (103 2 (:DEFINITION NAT-LISTP))
 (94 47
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (94 47
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (84 1 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
 (81 21
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (71 21
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (58 58 (:REWRITE USE-ALL-<=-2))
 (58 58 (:REWRITE USE-ALL-<=))
 (58 58 (:REWRITE USE-ALL-<-2))
 (58 58 (:REWRITE USE-ALL-<))
 (58 58
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (58 1 (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
 (53 2 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
 (50 31 (:REWRITE DEFAULT-+-2))
 (47
    47
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (40 40 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (38 38 (:REWRITE USE-ALL-RATIONALP-2))
 (38 38 (:REWRITE USE-ALL-RATIONALP))
 (31 31 (:REWRITE DEFAULT-+-1))
 (25 25
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (25 25
     (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (25 1
     (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (23 23 (:REWRITE USE-ALL-NATP-2))
 (23 23 (:REWRITE USE-ALL-NATP))
 (23 23
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (23 2 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
 (23 2 (:REWRITE ALL-<-WHEN-NOT-CONSP))
 (22 22 (:REWRITE USE-ALL-CONSP-2))
 (22 22 (:REWRITE USE-ALL-CONSP))
 (22 1 (:REWRITE ALL-DARGP-WHEN-NOT-CONSP))
 (22 1
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP))
 (20 20
     (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (18 18 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (18 3
     (:REWRITE ALL-DARGP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (16 2
     (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (15 15 (:TYPE-PRESCRIPTION NAT-LISTP))
 (15 8
     (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (14 14 (:REWRITE DEFAULT-CAR))
 (12 4 (:REWRITE FOLD-CONSTS-IN-+))
 (12 2 (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
 (11 2 (:REWRITE USE-ALL-NATP-FOR-CAR))
 (8 8
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (8 1
    (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (8 1
    (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-OF-AREF1))
 (8 1 (:DEFINITION LEN))
 (7 7 (:TYPE-PRESCRIPTION ALL-NATP))
 (7 7
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (7 2
    (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (7 2
    (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
 (6 6 (:TYPE-PRESCRIPTION LEN))
 (6 6 (:TYPE-PRESCRIPTION ALL-<))
 (6 1
    (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (6 1
    (:REWRITE ALL-DARGP-WHEN-NOT-CONSP-CHEAP))
 (6 1
    (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP-CHEAP))
 (5 5 (:REWRITE PSEUDO-DAG-ARRAYP-MONOTONE))
 (4 4 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (4 4
    (:TYPE-PRESCRIPTION BOUNDED-DAG-EXPRP))
 (4 2 (:REWRITE USE-ALL-<-FOR-CAR))
 (4 2
    (:REWRITE INTEGERP-OF-CAR-WHEN-NAT-LISTP-CHEAP))
 (4 2
    (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
 (4 2
    (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
 (4 2
    (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
 (3 3 (:REWRITE DEFAULT-CDR))
 (3 3
    (:REWRITE ALL-DARGP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION ALL-INTEGERP))
 (2 2
    (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
 (2 2 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (2 2 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (2 2
    (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (2 2
    (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
 (2 2
    (:REWRITE DAG-EXPRP0-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (2 2
    (:REWRITE DAG-EXPRP0-WHEN-BOUNDED-DAG-EXPRP))
 (2 2 (:REWRITE ALL-<-TRANSITIVE-FREE))
 (2 2 (:REWRITE ALL-<-TRANSITIVE))
 (2 1
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-MYQUOTEP-CHEAP))
 (2 1
    (:REWRITE ALL-DARGP-WHEN-ALL-MYQUOTEP-CHEAP))
 (2 1
    (:REWRITE ALL-DARGP-LESS-THAN-WHEN-ALL-MYQUOTEP-CHEAP))
 (2 1
    (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-WHEN-BOUNDED-DAG-EXPRP))
 (2 1
    (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-WHEN-<-SIMPLE))
 (1 1 (:TYPE-PRESCRIPTION MYQUOTEP))
 (1 1
    (:TYPE-PRESCRIPTION ALL-DARGP-LESS-THAN))
 (1 1
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-SYMBOLP-CHEAP))
 (1 1
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (1 1
    (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-BETTER))
 (1 1 (:REWRITE BOUNDED-DAG-EXPRP-MONOTONE))
 (1 1
    (:REWRITE ALL-DARGP-WHEN-ALL-DARGP-LESS-THAN))
 (1 1
    (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NO-ATOMS-CHEAP))
 (1 1
    (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (1 1
    (:REWRITE ALL-DARGP-LESS-THAN-MONOTONE))
 (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(BOUNDED-DAG-PARENT-ENTRIESP-OF-MV-NTH-0-OF-MAKE-DAG-INDICES-AUX
 (2927 2927 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (1184 84 (:DEFINITION NTH))
 (918 459
      (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (900 225
      (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (700 70
      (:LINEAR <-OF-NTH-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-LINEAR))
 (688 344
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (560 70
      (:LINEAR NONNEG-OF-NTH-OF-DARGS-OF-AREF1))
 (560 70
      (:LINEAR <-OF-NTH-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (459 459
      (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (450 450
      (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (420 168 (:REWRITE NTH-WHEN-NOT-CDDR))
 (344
    344
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (321 184 (:REWRITE DEFAULT-<-1))
 (282 141
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (270 4 (:DEFINITION BOUNDED-DAG-EXPRP))
 (267 16
      (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (225 225
      (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (225 225
      (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (218 218 (:REWRITE DEFAULT-+-2))
 (218 218 (:REWRITE DEFAULT-+-1))
 (218 6
      (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-WHEN-<-SIMPLE))
 (196 184 (:REWRITE DEFAULT-<-2))
 (192 16
      (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (184 184 (:REWRITE USE-ALL-<=-2))
 (184 184 (:REWRITE USE-ALL-<=))
 (184 184 (:REWRITE USE-ALL-<-2))
 (184 184 (:REWRITE USE-ALL-<))
 (184 184
      (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (174 27
      (:REWRITE BOUNDED-DAG-PARENT-ENTRIESP-MONOTONE-GEN))
 (158 6
      (:REWRITE ALL-DARGP-LESS-THAN-WHEN-ALL-<))
 (141 141
      (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (123 41
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (122 122 (:REWRITE USE-ALL-CONSP-2))
 (122 122 (:REWRITE USE-ALL-CONSP))
 (116 6
      (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-WHEN-BOUNDED-DAG-EXPRP))
 (103 40 (:REWRITE ZP-OPEN))
 (92 8 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
 (88
   11
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (84 84 (:REWRITE DEFAULT-CDR))
 (78 6
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP))
 (70 7 (:DEFINITION NFIX))
 (60 60 (:REWRITE <-OF-+-OF-1-STRENGTHEN))
 (56 14
     (:REWRITE NOT-<-OF-ALEN1-WHEN-PSEUDO-DAG-ARRAYP))
 (56 8 (:REWRITE ALL-<-WHEN-NOT-CONSP))
 (55 55 (:REWRITE DEFAULT-CAR))
 (41 41 (:REWRITE USE-ALL-RATIONALP-2))
 (41 41 (:REWRITE USE-ALL-RATIONALP))
 (40 40
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (40 40
     (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (38 38 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (32 8 (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
 (32 4
     (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (30 4
     (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (28 2
     (:REWRITE ALL-DARGP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (27 27
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (27 16
     (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (26 26 (:LINEAR ARRAY2P-LINEAR))
 (24 6
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP-CHEAP))
 (24 4
     (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (24 4
     (:REWRITE ALL-<-OF-ALEN1-WHEN-PSEUDO-DAG-ARRAYP-LIST))
 (20 20 (:REWRITE USE-ALL-NATP-2))
 (20 20 (:REWRITE USE-ALL-NATP))
 (16 16 (:TYPE-PRESCRIPTION ALL-<))
 (16 4
     (:REWRITE DAG-EXPRP0-OF-AREF1-WHEN-BOUNDED-DAG-EXPRP-OF-AREF1))
 (14 14
     (:TYPE-PRESCRIPTION BOUNDED-DAG-EXPRP))
 (12 6
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-ALL-MYQUOTEP-CHEAP))
 (11 11
     (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (10 10
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NO-ATOMS-CHEAP))
 (8 8
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-LIST))
 (8 8 (:REWRITE ALL-<-TRANSITIVE-FREE))
 (8 8 (:REWRITE ALL-<-TRANSITIVE))
 (8 8
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (8 4
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-MYQUOTEP-CHEAP))
 (7 7 (:TYPE-PRESCRIPTION NFIX))
 (7 7 (:REWRITE INTEGERP-OF-ALEN1))
 (6 6
    (:REWRITE ALL-DARGP-LESS-THAN-OF-DARGS-OF-AREF1))
 (6 6
    (:REWRITE ALL-DARGP-LESS-THAN-MONOTONE))
 (4 4 (:TYPE-PRESCRIPTION MYQUOTEP))
 (4 4
    (:REWRITE PSEUDO-DAG-ARRAYP-LIST-WHEN-ALL-DARGP-LESS-THAN-SPECIAL-ALT))
 (4 4
    (:REWRITE PSEUDO-DAG-ARRAYP-LIST-WHEN-ALL-DARGP-LESS-THAN-SPECIAL))
 (4 4
    (:REWRITE PSEUDO-DAG-ARRAYP-LIST-WHEN-ALL-DARGP-LESS-THAN))
 (4 4
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-SYMBOLP-CHEAP))
 (4 4
    (:REWRITE BOUNDED-DAG-EXPRP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (4 4
    (:REWRITE BOUNDED-DAG-EXPRP-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-BETTER))
 (4 4
    (:REWRITE BOUNDED-DAG-EXPRP-MONOTONE)))
(MAKE-DAG-INDICES
     (425 292 (:TYPE-PRESCRIPTION ALEN1-TYPE))
     (292 292 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
     (10 10 (:REWRITE USE-ALL-<=-2))
     (10 10 (:REWRITE USE-ALL-<=))
     (10 10 (:REWRITE USE-ALL-<-2))
     (10 10 (:REWRITE USE-ALL-<))
     (10 10 (:REWRITE DEFAULT-<-2))
     (10 10 (:REWRITE DEFAULT-<-1))
     (10 10
         (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (4 4 (:REWRITE <-OF-+-OF-1-STRENGTHEN))
     (3 3
        (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
     (2 2
        (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (2 1
        (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
     (1 1
        (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX)))
(MV-NTH-0-OF-MAKE-DAG-INDICES
 (78 1 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (23 1 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (18 1
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (11 1 (:DEFINITION NATP))
 (10 4 (:REWRITE DEFAULT-<-1))
 (9 3
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (8
   1
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (7 7
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (7 4 (:REWRITE DEFAULT-<-2))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (4 4 (:REWRITE USE-ALL-<=-2))
 (4 4 (:REWRITE USE-ALL-<=))
 (4 4 (:REWRITE USE-ALL-<-2))
 (4 4 (:REWRITE USE-ALL-<))
 (4 4
    (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (4 2
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (4 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (4 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (4 1 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (3 3
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (3 3
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (3 3 (:REWRITE USE-ALL-RATIONALP-2))
 (3 3 (:REWRITE USE-ALL-RATIONALP))
 (2 2
    (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (2 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (2 2 (:TYPE-PRESCRIPTION NO-ATOMS))
 (2 2
    (:TYPE-PRESCRIPTION DAG-PARENT-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (2 2 (:REWRITE USE-ALL-CONSP-2))
 (2 2 (:REWRITE USE-ALL-CONSP))
 (2 2
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (2 2 (:REWRITE <-OF-+-OF-1-STRENGTHEN))
 (2 1 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (2 1
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (1 1 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (1 1 (:TYPE-PRESCRIPTION ARRAY1P))
 (1 1 (:REWRITE USE-ALL-NATP-2))
 (1 1 (:REWRITE USE-ALL-NATP))
 (1 1
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (1 1
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (1 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (1 1
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (1 1
    (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (1 1 (:REWRITE DEFAULT-CAR))
 (1 1
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS)))
(MV-NTH-1-OF-MAKE-DAG-INDICES
 (78 1 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (23 1 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (18 1
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (11 1 (:DEFINITION NATP))
 (8
   1
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (7 7
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (6 3 (:REWRITE DEFAULT-<-2))
 (6 3 (:REWRITE DEFAULT-<-1))
 (6 2
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (4 2
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (4 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (4 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (4 1 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (3 3
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (3 3
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (3 3 (:REWRITE USE-ALL-<=-2))
 (3 3 (:REWRITE USE-ALL-<=))
 (3 3 (:REWRITE USE-ALL-<-2))
 (3 3 (:REWRITE USE-ALL-<))
 (3 3
    (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (2 2
    (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (2 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (2 2 (:TYPE-PRESCRIPTION NO-ATOMS))
 (2 2
    (:TYPE-PRESCRIPTION DAG-PARENT-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (2 2 (:REWRITE USE-ALL-RATIONALP-2))
 (2 2 (:REWRITE USE-ALL-RATIONALP))
 (2 2 (:REWRITE USE-ALL-CONSP-2))
 (2 2 (:REWRITE USE-ALL-CONSP))
 (2 2
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (2 1 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (2 1
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (1 1 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (1 1 (:TYPE-PRESCRIPTION ARRAY1P))
 (1 1 (:REWRITE USE-ALL-NATP-2))
 (1 1 (:REWRITE USE-ALL-NATP))
 (1 1
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (1 1
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (1 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (1 1
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (1 1
    (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (1 1 (:REWRITE DEFAULT-CAR))
 (1 1
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(MV-NTH-2-OF-MAKE-DAG-INDICES
 (78 1 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (23 1 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (18 1
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (11 1 (:DEFINITION NATP))
 (8
   1
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (6 3 (:REWRITE DEFAULT-<-2))
 (6 3 (:REWRITE DEFAULT-<-1))
 (6 2
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (4 2
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (4 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (4 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (4 1 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (3 3
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (3 3
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (3 3 (:REWRITE USE-ALL-<=-2))
 (3 3 (:REWRITE USE-ALL-<=))
 (3 3 (:REWRITE USE-ALL-<-2))
 (3 3 (:REWRITE USE-ALL-<))
 (3 3
    (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (2 2
    (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (2 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (2 2 (:TYPE-PRESCRIPTION NO-ATOMS))
 (2 2
    (:TYPE-PRESCRIPTION DAG-PARENT-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (2 2 (:REWRITE USE-ALL-RATIONALP-2))
 (2 2 (:REWRITE USE-ALL-RATIONALP))
 (2 2 (:REWRITE USE-ALL-CONSP-2))
 (2 2 (:REWRITE USE-ALL-CONSP))
 (2 2
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (2 1 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (2 1
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (1 1 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (1 1 (:TYPE-PRESCRIPTION ARRAY1P))
 (1 1 (:REWRITE USE-ALL-NATP-2))
 (1 1 (:REWRITE USE-ALL-NATP))
 (1 1
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (1 1
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (1 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (1 1
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (1 1
    (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (1 1 (:REWRITE DEFAULT-CAR))
 (1 1
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(MAKE-DAG-INDICES-WITH-LEN (549 378 (:TYPE-PRESCRIPTION ALEN1-TYPE))
                           (378 378 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
                           (14 14 (:REWRITE USE-ALL-<=-2))
                           (14 14 (:REWRITE USE-ALL-<=))
                           (14 14 (:REWRITE USE-ALL-<-2))
                           (14 14 (:REWRITE USE-ALL-<))
                           (14 14 (:REWRITE DEFAULT-<-2))
                           (14 14 (:REWRITE DEFAULT-<-1))
                           (14 14
                               (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
                           (4 4 (:REWRITE <-OF-+-OF-1-STRENGTHEN))
                           (3 3
                              (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
                           (2 2
                              (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
                           (2 2
                              (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN)))
(MV-NTH-1-OF-MAKE-DAG-INDICES-WITH-LEN
 (78 1 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (23 1 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (18 1
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (11 1 (:DEFINITION NATP))
 (8
   1
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (7 7
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (6 3 (:REWRITE DEFAULT-<-2))
 (6 3 (:REWRITE DEFAULT-<-1))
 (6 2
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (4 2
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (4 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (4 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (4 1 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (3 3
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (3 3
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (3 3 (:REWRITE USE-ALL-<=-2))
 (3 3 (:REWRITE USE-ALL-<=))
 (3 3 (:REWRITE USE-ALL-<-2))
 (3 3 (:REWRITE USE-ALL-<))
 (3 3
    (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (2 2
    (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (2 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (2 2 (:TYPE-PRESCRIPTION NO-ATOMS))
 (2 2
    (:TYPE-PRESCRIPTION DAG-PARENT-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (2 2 (:REWRITE USE-ALL-RATIONALP-2))
 (2 2 (:REWRITE USE-ALL-RATIONALP))
 (2 2 (:REWRITE USE-ALL-CONSP-2))
 (2 2 (:REWRITE USE-ALL-CONSP))
 (2 2
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (2 1 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (2 1
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (1 1 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (1 1 (:TYPE-PRESCRIPTION ARRAY1P))
 (1 1 (:REWRITE USE-ALL-NATP-2))
 (1 1 (:REWRITE USE-ALL-NATP))
 (1 1
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (1 1
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (1 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (1 1
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (1 1
    (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (1 1 (:REWRITE DEFAULT-CAR))
 (1 1
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(MV-NTH-2-OF-MAKE-DAG-INDICES-WITH-LEN
 (78 1 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (23 1 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (18 1
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (11 1 (:DEFINITION NATP))
 (8
   1
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (6 3 (:REWRITE DEFAULT-<-2))
 (6 3 (:REWRITE DEFAULT-<-1))
 (6 2
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (4 2
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (4 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (4 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (4 1 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (3 3
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (3 3
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (3 3 (:REWRITE USE-ALL-<=-2))
 (3 3 (:REWRITE USE-ALL-<=))
 (3 3 (:REWRITE USE-ALL-<-2))
 (3 3 (:REWRITE USE-ALL-<))
 (3 3
    (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (2 2
    (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (2 2
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (2 2 (:TYPE-PRESCRIPTION NO-ATOMS))
 (2 2
    (:TYPE-PRESCRIPTION DAG-PARENT-ARRAYP))
 (2 2 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (2 2 (:REWRITE USE-ALL-RATIONALP-2))
 (2 2 (:REWRITE USE-ALL-RATIONALP))
 (2 2 (:REWRITE USE-ALL-CONSP-2))
 (2 2 (:REWRITE USE-ALL-CONSP))
 (2 2
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (2 1 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (2 1
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (1 1 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (1 1 (:TYPE-PRESCRIPTION ARRAY1P))
 (1 1 (:REWRITE USE-ALL-NATP-2))
 (1 1 (:REWRITE USE-ALL-NATP))
 (1 1
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (1 1
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (1 1
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (1 1
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (1 1
    (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (1 1 (:REWRITE DEFAULT-CAR))
 (1 1
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(ALEN1-OF-MV-NTH-0-OF-MAKE-DAG-INDICES-WITH-LEN
 (99 1 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (80 40
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (74 37
     (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (71 37
     (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (68 68 (:TYPE-PRESCRIPTION NATP))
 (63 63 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (48
   1
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (37 37
     (:TYPE-PRESCRIPTION DAG-PARENT-ARRAYP))
 (29 2
     (:REWRITE NOT-<-OF-ALEN1-WHEN-PSEUDO-DAG-ARRAYP))
 (23 1 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (23 1
     (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (18 1
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (13 4
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (9 7 (:REWRITE DEFAULT-<-1))
 (8 1 (:DEFINITION LEN))
 (7 7 (:REWRITE USE-ALL-<=-2))
 (7 7 (:REWRITE USE-ALL-<=))
 (7 7 (:REWRITE USE-ALL-<-2))
 (7 7 (:REWRITE USE-ALL-<))
 (7 7 (:REWRITE DEFAULT-<-2))
 (7 7
    (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (6 6 (:TYPE-PRESCRIPTION LEN))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (6 3 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (4 4
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (4 3 (:REWRITE DEFAULT-+-2))
 (3 3
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (3 3
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (3 3 (:REWRITE DEFAULT-+-1))
 (2 2 (:TYPE-PRESCRIPTION NO-ATOMS))
 (2 2 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (2 2 (:REWRITE USE-ALL-CONSP-2))
 (2 2 (:REWRITE USE-ALL-CONSP))
 (2 2
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (2 2 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (2 2 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (2 2
    (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (2 2
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (2 2 (:REWRITE DEFAULT-CAR))
 (2 2
    (:REWRITE ARRAY1P-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:LINEAR ARRAY2P-LINEAR))
 (2 1
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (1 1
    (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
 (1 1 (:REWRITE PSEUDO-DAG-ARRAYP-MONOTONE))
 (1 1
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (1 1 (:REWRITE DEFAULT-CDR))
 (1 1
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(DAG-PARENT-ARRAYP-OF-MV-NTH-0-OF-MAKE-DAG-INDICES-WITH-LEN
 (99 1 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (96 48
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (90 45
     (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (87 45
     (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (84 84 (:TYPE-PRESCRIPTION NATP))
 (48
   1
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (29 2
     (:REWRITE NOT-<-OF-ALEN1-WHEN-PSEUDO-DAG-ARRAYP))
 (23 1 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (23 1
     (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (18 1
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (13 13 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (13 4
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (10 8 (:REWRITE DEFAULT-<-1))
 (8 8 (:REWRITE USE-ALL-<=-2))
 (8 8 (:REWRITE USE-ALL-<=))
 (8 8 (:REWRITE USE-ALL-<-2))
 (8 8 (:REWRITE USE-ALL-<))
 (8 8 (:REWRITE DEFAULT-<-2))
 (8 8
    (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (8 1 (:DEFINITION LEN))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (6 6 (:TYPE-PRESCRIPTION LEN))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (6 3
    (:TYPE-PRESCRIPTION
         TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (6 3 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (4 4
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (4 3 (:REWRITE DEFAULT-+-2))
 (3 3
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (3 3
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (3 3 (:REWRITE DEFAULT-+-1))
 (2 2 (:TYPE-PRESCRIPTION NO-ATOMS))
 (2 2 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (2 2 (:REWRITE USE-ALL-CONSP-2))
 (2 2 (:REWRITE USE-ALL-CONSP))
 (2 2
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (2 2 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (2 2 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (2 2
    (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (2 2
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (2 2 (:REWRITE DEFAULT-CAR))
 (2 2
    (:REWRITE ARRAY1P-WHEN-PSEUDO-DAG-ARRAYP))
 (2 2 (:LINEAR ARRAY2P-LINEAR))
 (2 1
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (1 1
    (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
 (1 1 (:REWRITE PSEUDO-DAG-ARRAYP-MONOTONE))
 (1 1
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (1 1 (:REWRITE DEFAULT-CDR))
 (1 1
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS))
 (1 1 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(BOUNDED-DAG-PARENT-ENTRIESP-OF-MV-NTH-0-OF-MAKE-DAG-INDICES-WITH-LEN
 (226 226 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (96 2 (:DEFINITION MAKE-DAG-INDICES-AUX))
 (34 2 (:REWRITE NO-ATOMS-WHEN-ALL-MYQUOTEP))
 (24 2
     (:REWRITE ALL-MYQUOTEP-WHEN-NOT-CONSP))
 (20 20 (:REWRITE USE-ALL-<=-2))
 (20 20 (:REWRITE USE-ALL-<=))
 (20 20 (:REWRITE USE-ALL-<-2))
 (20 20 (:REWRITE USE-ALL-<))
 (20 20 (:REWRITE DEFAULT-<-2))
 (20 20 (:REWRITE DEFAULT-<-1))
 (20 20
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (16
   2
   (:REWRITE
        NOT-EQUAL-OF-CAR-AND-QUOTE-WHEN-LEN-WRONG-AND-PSEUDO-DAG-ARRAYP-AUX))
 (12 6
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (8 4
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-AREF1-WHEN-DAG-PARENT-ARRAYP))
 (8 2
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (6 6
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (6 6
    (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (6 6
    (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (4 4
    (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (4 4
    (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (4 4 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (4 4
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (4 4 (:TYPE-PRESCRIPTION NO-ATOMS))
 (4 4 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (4 4 (:REWRITE USE-ALL-CONSP-2))
 (4 4 (:REWRITE USE-ALL-CONSP))
 (4 2
    (:REWRITE ALL-MYQUOTEP-WHEN-NO-ATOMS-AND-ALL-DARGP-CHEAP))
 (3 3 (:REWRITE <-OF-+-OF-1-STRENGTHEN))
 (2 2
    (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
 (2 2
    (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (2 2
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (2 2 (:REWRITE PSEUDO-DAG-ARRAYP-MONOTONE))
 (2 2
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (2 2 (:REWRITE DEFAULT-CAR))
 (2 2
    (:REWRITE BOUNDED-DAG-PARENT-ENTRIESP-MONOTONE-GEN))
 (2 2
    (:REWRITE BOUNDED-DAG-PARENT-ENTRIESP-MONOTONE))
 (2 2 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (2 2
    (:REWRITE ADD-TO-PARENTS-OF-ATOMS-WITH-NAME-WHEN-NO-ATOMS)))
(BOUNDED-DAG-PARENT-ARRAYP-OF-MV-NTH-0-OF-MAKE-DAG-INDICES-WITH-LEN
     (150 75 (:TYPE-PRESCRIPTION ALEN1-TYPE))
     (75 75 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
     (75 75 (:TYPE-PRESCRIPTION ARRAY1P))
     (3 3 (:REWRITE USE-ALL-<=-2))
     (3 3 (:REWRITE USE-ALL-<=))
     (3 3 (:REWRITE USE-ALL-<-2))
     (3 3 (:REWRITE USE-ALL-<))
     (3 3 (:REWRITE DEFAULT-<-2))
     (3 3 (:REWRITE DEFAULT-<-1))
     (3 3
        (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (1 1
        (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
     (1 1 (:REWRITE PSEUDO-DAG-ARRAYP-MONOTONE))
     (1 1
        (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (1 1 (:REWRITE DEFAULT-+-2))
     (1 1 (:REWRITE DEFAULT-+-1)))
