(MATCH-HYP-WITH-NODENUM-TO-ASSUME-FALSE
     (21523 31 (:REWRITE ALL-AXE-TREEP-OF-CDR-2))
     (12998 55
            (:REWRITE AXE-TREEP-WHEN-PSEUDO-TERMP))
     (9372 77 (:DEFINITION PSEUDO-TERM-LISTP))
     (8900 48
           (:REWRITE ALL-AXE-TREEP-WHEN-PSEUDO-TERM-LISTP))
     (5454 31 (:REWRITE ALL-AXE-TREEP-OF-CDR))
     (4992 55 (:REWRITE AXE-TREEP-WHEN-DARGP))
     (3943 865
           (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
     (3198 44 (:REWRITE NATP-OF-NTH-FROM-ALL-NATP))
     (3100 14 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
     (3072 34 (:DEFINITION NAT-LISTP))
     (2209 879 (:REWRITE DEFAULT-CDR))
     (2010 1198 (:REWRITE NTH-WHEN-<=-LEN-CHEAP))
     (1712 88
           (:REWRITE <-OF-+-ARG2-WHEN-NEGATIVE-CONSTANT))
     (1685 30 (:DEFINITION MYQUOTEP))
     (1499 50
           (:REWRITE ALL-AXE-TREEP-WHEN-ALL-DARGP))
     (1423 1423 (:TYPE-PRESCRIPTION ALL-DARGP))
     (1366 1300
           (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (1333 491 (:REWRITE ALL-DARGP-WHEN-NOT-CONSP))
     (1300 1300
           (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
     (1300 1300
           (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
     (1300 1300
           (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
     (1198 1198 (:REWRITE NTH-WHEN-ZP-CHEAP))
     (1198 1198
           (:REWRITE NTH-WHEN-NOT-CONSP-CHEAP))
     (1198 1198 (:REWRITE NTH-WHEN-NOT-CDDR))
     (1183 16 (:REWRITE AXE-TREEP-OF-NTH))
     (1032 565 (:TYPE-PRESCRIPTION ALEN1-TYPE))
     (986 493
          (:REWRITE ALL-DARGP-WHEN-ALL-MYQUOTEP-CHEAP))
     (865 865
          (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
     (853 353 (:REWRITE DEFAULT-+-2))
     (845 445
          (:REWRITE LEN-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
     (624 340 (:REWRITE DEFAULT-<-2))
     (565 565 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
     (553 30 (:DEFINITION QUOTEP))
     (497 30 (:REWRITE DARGP-WHEN-CONSP-CHEAP))
     (493 493 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
     (493 493
          (:REWRITE ALL-DARGP-WHEN-NOT-CONSP-CHEAP))
     (493 493
          (:REWRITE ALL-DARGP-WHEN-ALL-DARGP-LESS-THAN))
     (430 215
          (:REWRITE PSEUDO-TERM-LISTP-WHEN-SYMBOL-LISTP-CHEAP))
     (386 386
          (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
     (386 66
          (:REWRITE INTEGERP-OF-NTH-WHEN-ALL-INTEGERP))
     (364 182
          (:REWRITE NTH-0-OF-NTH-0-WHEN-PSEUDO-DAGP-CHEAP))
     (353 353 (:REWRITE DEFAULT-+-1))
     (346 340 (:REWRITE DEFAULT-<-1))
     (340 340 (:REWRITE USE-ALL-<-2))
     (340 340 (:REWRITE USE-ALL-<))
     (340 340 (:REWRITE <-WHEN-BOUNDED-AXE-TREEP))
     (340 340
          (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (328 328
          (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
     (318 318 (:REWRITE USE-ALL-CONSP-2))
     (318 318 (:REWRITE USE-ALL-CONSP))
     (318 318 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (282 44
          (:REWRITE NATP-OF-NTH-WHEN-ALL-DARGP))
     (275 37 (:REWRITE ALL-DARGP-OF-CDR))
     (268 134
          (:TYPE-PRESCRIPTION
               TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
     (267 138
          (:REWRITE SYMBOL-OF-NTH-0-WHEN-AXE-TREEP))
     (254 242
          (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
     (254 242
          (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
     (220 119
          (:REWRITE LEN-OF-NTH-1-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
     (215 215
          (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
     (185 185
          (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
     (182 182 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
     (168 168
          (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
     (156 156
          (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
     (144 144 (:TYPE-PRESCRIPTION ALL-NATP))
     (140 140
          (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
     (135 135
          (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (128 128 (:TYPE-PRESCRIPTION ALL-INTEGERP))
     (128 64
          (:REWRITE ALL-NATP-IMPLIES-ALL-INTEGERP-CHEAP))
     (112 112
          (:REWRITE NOT-CDDR-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
     (112 28 (:REWRITE +-COMBINE-CONSTANTS))
     (108 108 (:TYPE-PRESCRIPTION NAT-LISTP))
     (108 108
          (:REWRITE EQUAL-OF-+-COMBINE-CONSTANTS))
     (107 58
          (:REWRITE SYMBOL-LISTP-OF-NTH1-OF-NTH-0-WHEN-AXE-TREEP))
     (96 96
         (:REWRITE TRUE-LISTP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
     (76 4 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (74 74 (:REWRITE USE-ALL-<=-2))
     (74 74 (:REWRITE USE-ALL-<=))
     (70 70
         (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
     (68 4 (:LINEAR LEN-OF-CDR-LINEAR))
     (66 66
         (:REWRITE INTEGERP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
     (64 64
         (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
     (64 64
         (:REWRITE ALL-INTEGERP-WHEN-NOT-CONSP-CHEAP))
     (60 60
         (:REWRITE NOT-<-OF-NTH-WHEN-ALL-DARGP-LESS-THAN-GEN-CONSTANT))
     (60 60
         (:REWRITE <-OF-NTH-WHEN-ALL-DARGP-LESS-THAN-FREE))
     (59 59 (:REWRITE DEFAULT-COERCE-2))
     (59 59 (:REWRITE DEFAULT-COERCE-1))
     (55 55
         (:REWRITE AXE-TREEP-WHEN-SYMBOLP-CHEAP))
     (55 55
         (:REWRITE AXE-TREEP-WHEN-NOT-CONSP-AND-NOT-SYMBOLP-CHEAP))
     (55 55
         (:REWRITE AXE-TREEP-WHEN-EQUAL-OF-CAR-AND-QUOTE-CHEAP))
     (52 52
         (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN))
     (50 50 (:REWRITE USE-ALL-NATP-2))
     (50 50 (:REWRITE USE-ALL-NATP))
     (50 50
         (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (50 50
         (:REWRITE <-OF-1-AND-LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
     (44 44
         (:REWRITE NATP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN-GEN))
     (44 22
         (:REWRITE <-OF-NTH-OF-0-WHEN-ALL-<-CHEAP))
     (44 22
         (:REWRITE <-OF-NTH-OF-0-AND-0-WHEN-ALL-NATP-CHEAP))
     (44 22
         (:REWRITE <-OF-NTH-0-WHEN-ALL-DARGP-LESS-THAN))
     (31 31
         (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (30 30 (:REWRITE USE-ALL-DARGP-2))
     (30 30 (:REWRITE USE-ALL-DARGP))
     (30 30
         (:REWRITE MYQUOTEP-WHEN-DARGP-LESS-THAN))
     (30 30
         (:REWRITE MYQUOTEP-WHEN-BOUNDED-DAG-EXPRP))
     (30 30 (:REWRITE MYQUOTEP-WHEN-AXE-TREEP))
     (30 30
         (:REWRITE DARGP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
     (30 30
         (:REWRITE DARGP-WHEN-DARGP-LESS-THAN))
     (28 14
         (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
     (24 12
         (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
     (24 12 (:REWRITE DARGP-WHEN-NATP-CHEAP))
     (24 12 (:REWRITE DARGP-WHEN-MYQUOTEP-CHEAP))
     (22 22
         (:TYPE-PRESCRIPTION ALL-DARGP-LESS-THAN))
     (22 22 (:TYPE-PRESCRIPTION ALL-<))
     (22 22
         (:REWRITE <-OF-0-WHEN-ALL-DARGP-LESS-THAN))
     (18 9
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DIMENSIONS))
     (14 14
         (:REWRITE DARGP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
     (14 14
         (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
     (14 14 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
     (14 7 (:REWRITE LEN-OF-NTH-OF-DARGS))
     (7 7 (:TYPE-PRESCRIPTION DAG-EXPRP0))
     (6 6 (:REWRITE <-OF-+-OF-1-STRENGTHEN)))
(SYMBOL-ALISTP-OF-MATCH-HYP-WITH-NODENUM-TO-ASSUME-FALSE
 (507 25 (:REWRITE CONSP-FROM-LEN-CHEAP))
 (119 119 (:TYPE-PRESCRIPTION LEN))
 (91 16 (:REWRITE DEFAULT-CAR))
 (89 5 (:REWRITE LEN-OF-CDR))
 (81 18
     (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
 (72 12 (:REWRITE DEFAULT-CDR))
 (53 35 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (48 24
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (48 24
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (42 42
     (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (36 9 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (35 35 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (35 35 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (35 35
     (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (32 4 (:REWRITE EQUAL-OF-LEN-AND-0))
 (30 15
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (25 25
     (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
 (24 24
     (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (24
    24
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (24 24
     (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (24 12 (:REWRITE DEFAULT-<-2))
 (21 3
     (:REWRITE LEN-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (18 9 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (18 9 (:REWRITE NTH-WHEN-<=-LEN-CHEAP))
 (16 16 (:REWRITE USE-ALL-CONSP-2))
 (16 16 (:REWRITE USE-ALL-CONSP))
 (16 16 (:REWRITE CONSP-WHEN-LEN-GREATER))
 (15 15
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (12 12 (:REWRITE USE-ALL-<-2))
 (12 12 (:REWRITE USE-ALL-<))
 (12 12 (:REWRITE DEFAULT-<-1))
 (12 12 (:REWRITE <-WHEN-BOUNDED-AXE-TREEP))
 (12 12
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (12 9 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
 (12 9
     (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
 (9 9 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (9 9 (:TYPE-PRESCRIPTION ARRAY1P))
 (9 9 (:REWRITE NTH-WHEN-ZP-CHEAP))
 (9 9 (:REWRITE NTH-WHEN-NOT-CONSP-CHEAP))
 (9 9 (:REWRITE NTH-WHEN-NOT-CDDR))
 (9 5 (:REWRITE DEFAULT-+-2))
 (6 6
    (:TYPE-PRESCRIPTION SYMBOLP-OF-NTH-0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (6 3 (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
 (6 3 (:REWRITE LEN-OF-NTH-OF-DARGS))
 (6 3
    (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (5 5 (:REWRITE DEFAULT-+-1))
 (3 3 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (3 3 (:TYPE-PRESCRIPTION AXE-TREEP))
 (3 3 (:TYPE-PRESCRIPTION ALL-DARGP))
 (3 3
    (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (3 3
    (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
 (1 1
    (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN)))
(TRUE-LISTP-WHEN-ALISTP)
(TRUE-LISTP-OF-MATCH-HYP-WITH-NODENUM-TO-ASSUME-FALSE
 (507 25 (:REWRITE CONSP-FROM-LEN-CHEAP))
 (119 119 (:TYPE-PRESCRIPTION LEN))
 (91 16 (:REWRITE DEFAULT-CAR))
 (89 5 (:REWRITE LEN-OF-CDR))
 (81 18
     (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
 (72 12 (:REWRITE DEFAULT-CDR))
 (53 35 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (48 24
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (48 24
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (42 42
     (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (36 9 (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (35 35 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (35 35 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (35 35
     (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (32 4 (:REWRITE EQUAL-OF-LEN-AND-0))
 (30 15
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (25 25
     (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
 (24 24
     (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (24
    24
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (24 24
     (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (24 12 (:REWRITE DEFAULT-<-2))
 (21 3
     (:REWRITE LEN-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (18 9 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (18 9 (:REWRITE NTH-WHEN-<=-LEN-CHEAP))
 (16 16 (:REWRITE USE-ALL-CONSP-2))
 (16 16 (:REWRITE USE-ALL-CONSP))
 (16 16 (:REWRITE CONSP-WHEN-LEN-GREATER))
 (15 15
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (12 12 (:REWRITE USE-ALL-<-2))
 (12 12 (:REWRITE USE-ALL-<))
 (12 12 (:REWRITE DEFAULT-<-1))
 (12 12 (:REWRITE <-WHEN-BOUNDED-AXE-TREEP))
 (12 12
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (12 9 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
 (12 9
     (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
 (9 9 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (9 9 (:TYPE-PRESCRIPTION ARRAY1P))
 (9 9 (:REWRITE NTH-WHEN-ZP-CHEAP))
 (9 9 (:REWRITE NTH-WHEN-NOT-CONSP-CHEAP))
 (9 9 (:REWRITE NTH-WHEN-NOT-CDDR))
 (9 5 (:REWRITE DEFAULT-+-2))
 (6 6
    (:TYPE-PRESCRIPTION SYMBOLP-OF-NTH-0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (6 3 (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
 (6 3 (:REWRITE LEN-OF-NTH-OF-DARGS))
 (6 3
    (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (5 5 (:REWRITE DEFAULT-+-1))
 (3 3 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (3 3 (:TYPE-PRESCRIPTION AXE-TREEP))
 (3 3 (:TYPE-PRESCRIPTION ALL-DARGP))
 (3 3
    (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (3 3
    (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
 (1 1
    (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN)))
(TRUE-LISTP-OF-MATCH-HYP-WITH-NODENUM-TO-ASSUME-FALSE-TYPE
 (218 21 (:REWRITE DEFAULT-CDR))
 (192 96
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (192 96
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (189 189
      (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (174 120 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (156 78
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (118 118 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (118 118 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (118 118
      (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (108 108
      (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (97 18 (:REWRITE DEFAULT-CAR))
 (96
    96
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (96 96
     (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (96 24
     (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (92 46 (:REWRITE DEFAULT-<-2))
 (78 78
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (76 76
     (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
 (63 63 (:REWRITE USE-ALL-CONSP-2))
 (63 63 (:REWRITE USE-ALL-CONSP))
 (63 63 (:REWRITE CONSP-WHEN-LEN-GREATER))
 (61 33 (:REWRITE DEFAULT-+-2))
 (55 3 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
 (48 24 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (46 46 (:REWRITE USE-ALL-<-2))
 (46 46 (:REWRITE USE-ALL-<))
 (46 46 (:REWRITE DEFAULT-<-1))
 (46 46 (:REWRITE <-WHEN-BOUNDED-AXE-TREEP))
 (46 46
     (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (46 37 (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
 (46 37
     (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
 (46 1 (:DEFINITION ALISTP))
 (42 12
     (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (33 33 (:REWRITE DEFAULT-+-1))
 (33 9
     (:REWRITE LEN-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (24 24 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (24 24 (:TYPE-PRESCRIPTION ARRAY1P))
 (21 15 (:REWRITE NTH-WHEN-<=-LEN-CHEAP))
 (18 18
     (:TYPE-PRESCRIPTION SYMBOLP-OF-NTH-0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (18 9 (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
 (18 9 (:REWRITE LEN-OF-NTH-OF-DARGS))
 (15 15 (:REWRITE NTH-WHEN-ZP-CHEAP))
 (15 15 (:REWRITE NTH-WHEN-NOT-CONSP-CHEAP))
 (15 15 (:REWRITE NTH-WHEN-NOT-CDDR))
 (12 3
     (:REWRITE PSEUDO-DAG-ARRAYP-AUX-WHEN-PSEUDO-DAGP-AUX))
 (10 10
     (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
 (9 9 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (9 9 (:TYPE-PRESCRIPTION AXE-TREEP))
 (9 9 (:TYPE-PRESCRIPTION ALL-DARGP))
 (9 9
    (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-DAGP-AUX))
 (6 6
    (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
 (5 5
    (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
 (5 1 (:REWRITE USE-ALL-CONSP-FOR-CAR))
 (3 3
    (:REWRITE PSEUDO-DAGP-AUX-WHEN-NOT-CONSP-CHEAP))
 (3 3
    (:REWRITE PSEUDO-DAG-ARRAYP-AUX-MONOTONE))
 (3 1
    (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
 (2 2 (:TYPE-PRESCRIPTION ALL-CONSP))
 (2 2
    (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
 (2 2
    (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
 (2 1
    (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
 (2 1 (:REWRITE ALISTP-OF-CDR))
 (1 1
    (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
 (1 1
    (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
 (1 1
    (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
 (1 1
    (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
 (1 1
    (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
 (1 1
    (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
 (1 1 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP)))
(ALL-DARGP-OF-MATCH-HYP-WITH-NODENUM-TO-ASSUME-FALSE
 (14101 28 (:DEFINITION PSEUDO-TERMP))
 (8326 14 (:REWRITE ALL-AXE-TREEP-OF-CDR-2))
 (7090 19
       (:REWRITE AXE-TREEP-WHEN-PSEUDO-TERMP))
 (6567 35 (:DEFINITION PSEUDO-TERM-LISTP))
 (5586 22
       (:REWRITE ALL-AXE-TREEP-WHEN-PSEUDO-TERM-LISTP))
 (4636 68 (:REWRITE TRUE-LISTP-WHEN-ALISTP))
 (4256 83 (:DEFINITION ALISTP))
 (3574 14 (:REWRITE ALL-AXE-TREEP-OF-CDR))
 (2477 582
       (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
 (1631 78 (:DEFINITION LENGTH))
 (1450 480 (:REWRITE DEFAULT-CDR))
 (1118 27 (:DEFINITION SYMBOL-LISTP))
 (1013 606 (:REWRITE NTH-WHEN-<=-LEN-CHEAP))
 (977 19 (:REWRITE AXE-TREEP-WHEN-DARGP))
 (800 34
      (:REWRITE <-OF-+-ARG2-WHEN-NEGATIVE-CONSTANT))
 (790 771 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (788 6 (:DEFINITION DARGP))
 (761 9 (:REWRITE AXE-TREEP-OF-NTH))
 (753 753 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (753 753 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (753 753
      (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (748 240 (:REWRITE ALL-DARGP-WHEN-NOT-CONSP))
 (644 12 (:DEFINITION MYQUOTEP))
 (606 606 (:REWRITE NTH-WHEN-ZP-CHEAP))
 (606 606 (:REWRITE NTH-WHEN-NOT-CONSP-CHEAP))
 (606 606 (:REWRITE NTH-WHEN-NOT-CDDR))
 (582 582
      (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (555 224
      (:REWRITE LEN-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (484 242
      (:REWRITE ALL-DARGP-WHEN-ALL-MYQUOTEP-CHEAP))
 (419 213 (:REWRITE DEFAULT-<-2))
 (410 410 (:TYPE-PRESCRIPTION ALISTP))
 (406 83 (:REWRITE ALISTP-OF-CDR))
 (378 6 (:DEFINITION STRIP-CDRS))
 (364 182 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (336 124 (:REWRITE DEFAULT-+-2))
 (300 300
      (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
 (242 242 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (242 242
      (:REWRITE ALL-DARGP-WHEN-ALL-DARGP-LESS-THAN))
 (242 12 (:DEFINITION QUOTEP))
 (232 232 (:REWRITE <-WHEN-BOUNDED-AXE-TREEP))
 (229 229 (:REWRITE USE-ALL-CONSP-2))
 (229 229 (:REWRITE USE-ALL-CONSP))
 (229 229 (:REWRITE CONSP-WHEN-LEN-GREATER))
 (225 222
      (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
 (215 55
      (:REWRITE SYMBOL-OF-NTH-0-WHEN-AXE-TREEP))
 (213 213 (:REWRITE USE-ALL-<-2))
 (213 213 (:REWRITE USE-ALL-<))
 (213 213 (:REWRITE DEFAULT-<-1))
 (213 213
      (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (210 210 (:TYPE-PRESCRIPTION PSEUDO-TERMP))
 (207 207 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
 (206 203
      (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
 (199 53
      (:REWRITE LEN-OF-NTH-1-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (182 182 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (182 182 (:TYPE-PRESCRIPTION ARRAY1P))
 (176 88
      (:REWRITE PSEUDO-TERM-LISTP-WHEN-SYMBOL-LISTP-CHEAP))
 (170 8 (:REWRITE NATP-OF-NTH-FROM-ALL-NATP))
 (168 168
      (:TYPE-PRESCRIPTION PSEUDO-TERM-LISTP))
 (150 150
      (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
 (150 150
      (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
 (124 124 (:REWRITE DEFAULT-+-1))
 (112 56
      (:REWRITE NTH-0-OF-NTH-0-WHEN-PSEUDO-DAGP-CHEAP))
 (105 14 (:REWRITE ALL-DARGP-OF-CDR))
 (101 73 (:REWRITE EQUAL-OF-LEN-AND-0))
 (90 8 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
 (88 88
     (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
 (87 3
     (:REWRITE ACL2-NUMBERP-OF-NTH-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (80 13 (:REWRITE DARGP-WHEN-CONSP-CHEAP))
 (78 78
     (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
 (74 74
     (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
 (74 8 (:DEFINITION NAT-LISTP))
 (68 68
     (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
 (64 8 (:REWRITE NATP-OF-NTH-WHEN-ALL-DARGP))
 (63 63
     (:REWRITE NOT-CDDR-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (63 63
     (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (56 56 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
 (56 56
     (:REWRITE EQUAL-OF-+-COMBINE-CONSTANTS))
 (53 28
     (:REWRITE SYMBOL-LISTP-OF-NTH1-OF-NTH-0-WHEN-AXE-TREEP))
 (50 50
     (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (49 49
     (:REWRITE TRUE-LISTP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (48 24
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (42 42
     (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
 (38 2 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
 (34 2 (:LINEAR LEN-OF-CDR-LINEAR))
 (32 8 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
 (30 30
     (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN))
 (30 30
     (:REWRITE <-OF-1-AND-LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (28 28 (:REWRITE DEFAULT-COERCE-2))
 (28 28 (:REWRITE DEFAULT-COERCE-1))
 (19 19
     (:REWRITE AXE-TREEP-WHEN-SYMBOLP-CHEAP))
 (19 19
     (:REWRITE AXE-TREEP-WHEN-NOT-CONSP-AND-NOT-SYMBOLP-CHEAP))
 (19 19
     (:REWRITE AXE-TREEP-WHEN-EQUAL-OF-CAR-AND-QUOTE-CHEAP))
 (16 16 (:TYPE-PRESCRIPTION NAT-LISTP))
 (16 16 (:TYPE-PRESCRIPTION ALL-NATP))
 (16 8
     (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
 (15 15
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (13 13 (:REWRITE USE-ALL-DARGP-2))
 (13 13 (:REWRITE USE-ALL-DARGP))
 (13 13
     (:REWRITE DARGP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (13 13
     (:REWRITE DARGP-WHEN-DARGP-LESS-THAN))
 (12 12 (:REWRITE USE-ALL-NATP-2))
 (12 12 (:REWRITE USE-ALL-NATP))
 (12 12
     (:REWRITE MYQUOTEP-WHEN-DARGP-LESS-THAN))
 (12 12
     (:REWRITE MYQUOTEP-WHEN-BOUNDED-DAG-EXPRP))
 (12 12 (:REWRITE MYQUOTEP-WHEN-AXE-TREEP))
 (12 6 (:REWRITE DARGP-WHEN-MYQUOTEP-CHEAP))
 (8 8
    (:REWRITE NATP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (8 8
    (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
 (7 7
    (:REWRITE DARGP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (6 6 (:TYPE-PRESCRIPTION STRIP-CDRS))
 (6 6 (:TYPE-PRESCRIPTION MYQUOTEP))
 (6 3 (:REWRITE LEN-OF-NTH-OF-DARGS))
 (6 3
    (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (4 4
    (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
 (3 3
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (3 3 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (2 2 (:REWRITE USE-ALL-<=-2))
 (2 2 (:REWRITE USE-ALL-<=)))
(ALL-DARGP-LESS-THAN-OF-MATCH-HYP-WITH-NODENUM-TO-ASSUME-FALSE
 (14101 28 (:DEFINITION PSEUDO-TERMP))
 (8326 14 (:REWRITE ALL-AXE-TREEP-OF-CDR-2))
 (7090 19
       (:REWRITE AXE-TREEP-WHEN-PSEUDO-TERMP))
 (6567 35 (:DEFINITION PSEUDO-TERM-LISTP))
 (5586 22
       (:REWRITE ALL-AXE-TREEP-WHEN-PSEUDO-TERM-LISTP))
 (4636 68 (:REWRITE TRUE-LISTP-WHEN-ALISTP))
 (4256 83 (:DEFINITION ALISTP))
 (3574 14 (:REWRITE ALL-AXE-TREEP-OF-CDR))
 (2481 584
       (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
 (1631 78 (:DEFINITION LENGTH))
 (1479 482 (:REWRITE DEFAULT-CDR))
 (1118 27 (:DEFINITION SYMBOL-LISTP))
 (1017 608 (:REWRITE NTH-WHEN-<=-LEN-CHEAP))
 (977 19 (:REWRITE AXE-TREEP-WHEN-DARGP))
 (800 34
      (:REWRITE <-OF-+-ARG2-WHEN-NEGATIVE-CONSTANT))
 (794 774 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (788 6 (:DEFINITION DARGP))
 (761 9 (:REWRITE AXE-TREEP-OF-NTH))
 (756 756 (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (756 756 (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (756 756
      (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (651 239 (:REWRITE ALL-DARGP-WHEN-NOT-CONSP))
 (644 12 (:DEFINITION MYQUOTEP))
 (608 608 (:REWRITE NTH-WHEN-ZP-CHEAP))
 (608 608 (:REWRITE NTH-WHEN-NOT-CONSP-CHEAP))
 (608 608 (:REWRITE NTH-WHEN-NOT-CDDR))
 (584 584
      (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (561 226
      (:REWRITE LEN-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (482 241
      (:REWRITE ALL-DARGP-WHEN-ALL-MYQUOTEP-CHEAP))
 (441 7 (:DEFINITION STRIP-CDRS))
 (421 214 (:REWRITE DEFAULT-<-2))
 (410 410 (:TYPE-PRESCRIPTION ALISTP))
 (406 83 (:REWRITE ALISTP-OF-CDR))
 (364 182 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (336 124 (:REWRITE DEFAULT-+-2))
 (303 303
      (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
 (242 242 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (242 12 (:DEFINITION QUOTEP))
 (241 241
      (:REWRITE ALL-DARGP-WHEN-ALL-DARGP-LESS-THAN))
 (233 233 (:REWRITE <-WHEN-BOUNDED-AXE-TREEP))
 (231 231 (:REWRITE USE-ALL-CONSP-2))
 (231 231 (:REWRITE USE-ALL-CONSP))
 (231 231 (:REWRITE CONSP-WHEN-LEN-GREATER))
 (226 223
      (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
 (215 55
      (:REWRITE SYMBOL-OF-NTH-0-WHEN-AXE-TREEP))
 (214 214 (:REWRITE USE-ALL-<-2))
 (214 214 (:REWRITE USE-ALL-<))
 (214 214 (:REWRITE DEFAULT-<-1))
 (214 214
      (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (210 210 (:TYPE-PRESCRIPTION PSEUDO-TERMP))
 (207 207 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
 (207 204
      (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
 (199 53
      (:REWRITE LEN-OF-NTH-1-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (182 182 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (182 182 (:TYPE-PRESCRIPTION ARRAY1P))
 (176 88
      (:REWRITE PSEUDO-TERM-LISTP-WHEN-SYMBOL-LISTP-CHEAP))
 (170 8 (:REWRITE NATP-OF-NTH-FROM-ALL-NATP))
 (168 168
      (:TYPE-PRESCRIPTION PSEUDO-TERM-LISTP))
 (150 150
      (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
 (150 150
      (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
 (124 124 (:REWRITE DEFAULT-+-1))
 (112 56
      (:REWRITE NTH-0-OF-NTH-0-WHEN-PSEUDO-DAGP-CHEAP))
 (105 14 (:REWRITE ALL-DARGP-OF-CDR))
 (101 73 (:REWRITE EQUAL-OF-LEN-AND-0))
 (97 1 (:REWRITE ALL-<-WHEN-NOT-CONSP))
 (90 8 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
 (88 88
     (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
 (87 3
     (:REWRITE ACL2-NUMBERP-OF-NTH-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (79 12 (:REWRITE DARGP-WHEN-CONSP-CHEAP))
 (78 78
     (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
 (77 1
     (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP))
 (74 74
     (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
 (74 8 (:DEFINITION NAT-LISTP))
 (68 68
     (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
 (64 8 (:REWRITE NATP-OF-NTH-WHEN-ALL-DARGP))
 (63 63
     (:REWRITE NOT-CDDR-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (63 63
     (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (56 56 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
 (56 56
     (:REWRITE EQUAL-OF-+-COMBINE-CONSTANTS))
 (53 28
     (:REWRITE SYMBOL-LISTP-OF-NTH1-OF-NTH-0-WHEN-AXE-TREEP))
 (50 50
     (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (49 49
     (:REWRITE TRUE-LISTP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (48 24
     (:TYPE-PRESCRIPTION
          TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (42 42
     (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
 (38 2 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
 (34 2 (:LINEAR LEN-OF-CDR-LINEAR))
 (32 8 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
 (30 30
     (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN))
 (30 30
     (:REWRITE <-OF-1-AND-LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (28 28 (:REWRITE DEFAULT-COERCE-2))
 (28 28 (:REWRITE DEFAULT-COERCE-1))
 (19 19
     (:REWRITE AXE-TREEP-WHEN-SYMBOLP-CHEAP))
 (19 19
     (:REWRITE AXE-TREEP-WHEN-NOT-CONSP-AND-NOT-SYMBOLP-CHEAP))
 (19 19
     (:REWRITE AXE-TREEP-WHEN-EQUAL-OF-CAR-AND-QUOTE-CHEAP))
 (16 16 (:TYPE-PRESCRIPTION NAT-LISTP))
 (16 8
     (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
 (15 15
     (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (12 12 (:TYPE-PRESCRIPTION DARGP))
 (12 12 (:REWRITE USE-ALL-NATP-2))
 (12 12 (:REWRITE USE-ALL-NATP))
 (12 12 (:REWRITE USE-ALL-DARGP-2))
 (12 12 (:REWRITE USE-ALL-DARGP))
 (12 12
     (:REWRITE MYQUOTEP-WHEN-DARGP-LESS-THAN))
 (12 12
     (:REWRITE MYQUOTEP-WHEN-BOUNDED-DAG-EXPRP))
 (12 12 (:REWRITE MYQUOTEP-WHEN-AXE-TREEP))
 (12 12
     (:REWRITE DARGP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (12 12
     (:REWRITE DARGP-WHEN-DARGP-LESS-THAN))
 (12 6 (:REWRITE DARGP-WHEN-NATP-CHEAP))
 (12 6 (:REWRITE DARGP-WHEN-MYQUOTEP-CHEAP))
 (8 8
    (:REWRITE NATP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (8 8
    (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
 (7 7 (:TYPE-PRESCRIPTION MYQUOTEP))
 (7 7
    (:REWRITE DARGP-OF-NTH-WHEN-ALL-DARGP-LESS-THAN))
 (6 3 (:REWRITE LEN-OF-NTH-OF-DARGS))
 (6 3
    (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (5 5 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
 (5 5 (:REWRITE ALL-<-TRANSITIVE-FREE))
 (5 5 (:REWRITE ALL-<-TRANSITIVE))
 (4 4
    (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
 (3 3
    (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (3 3 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (2 2 (:REWRITE USE-ALL-<=-2))
 (2 2 (:REWRITE USE-ALL-<=))
 (2 1
    (:REWRITE DARGP-LESS-THAN-WHEN-MYQUOTEP-CHEAP))
 (2 1
    (:REWRITE ALL-DARGP-LESS-THAN-WHEN-NOT-CONSP-CHEAP))
 (2 1
    (:REWRITE ALL-DARGP-LESS-THAN-WHEN-ALL-MYQUOTEP-CHEAP))
 (2 1 (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
 (1 1 (:REWRITE USE-ALL-DARGP-LESS-THAN-2))
 (1 1 (:REWRITE USE-ALL-DARGP-LESS-THAN))
 (1 1
    (:REWRITE DARGP-LESS-THAN-WHEN-QUOTEP-CHEAP))
 (1 1
    (:REWRITE DARGP-LESS-THAN-WHEN-EQUAL-OF-NTH-0-AND-QUOTE))
 (1 1
    (:REWRITE DARGP-LESS-THAN-WHEN-EQUAL-OF-CAR-AND-QUOTE))
 (1 1 (:REWRITE DARGP-LESS-THAN-MONO))
 (1 1
    (:REWRITE ALL-DARGP-LESS-THAN-MONOTONE)))
(MATCH-HYP-WITH-NODENUM-TO-ASSUME-FALSE-BINDS-ALL-VARS
 (44754 73 (:REWRITE ALL-AXE-TREEP-OF-CDR-2))
 (43193 19 (:DEFINITION ALL-AXE-TREEP))
 (33177 112
        (:REWRITE AXE-TREEP-WHEN-PSEUDO-TERMP))
 (27959 275 (:REWRITE TRUE-LISTP-WHEN-ALISTP))
 (26477 387 (:DEFINITION ALISTP))
 (15614 106
        (:REWRITE ALL-AXE-TREEP-WHEN-PSEUDO-TERM-LISTP))
 (15485 155 (:DEFINITION PSEUDO-TERM-LISTP))
 (8673 112 (:REWRITE AXE-TREEP-WHEN-DARGP))
 (7291 699 (:REWRITE USE-ALL-CONSP-FOR-CAR))
 (6864 24 (:DEFINITION DARGP))
 (5217 2874 (:REWRITE DEFAULT-CAR))
 (5089 474 (:REWRITE ALISTP-OF-CDR))
 (4685 1347
       (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
 (4192 56 (:DEFINITION NATP))
 (3926 124 (:DEFINITION NAT-LISTP))
 (3913 3337
       (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (3866 2420 (:REWRITE DEFAULT-CDR))
 (3368 64 (:REWRITE USE-ALL-<-FOR-CAR))
 (3337 3337
       (:REWRITE LEN-WHEN-PSEUDO-DAGP-AUX))
 (3337 3337
       (:REWRITE LEN-WHEN-DARGP-LESS-THAN))
 (3337 3337
       (:REWRITE LEN-WHEN-BOUNDED-DAG-EXPRP-AND-QUOTEP))
 (3295 999 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
 (3154 210
       (:REWRITE <-OF-+-ARG2-WHEN-NEGATIVE-CONSTANT))
 (3138 152 (:REWRITE USE-ALL-NATP-FOR-CAR))
 (3098 148 (:REWRITE ALL-NATP-WHEN-NAT-LISTP))
 (2758 61 (:DEFINITION MYQUOTEP))
 (2200 1149 (:REWRITE DEFAULT-<-2))
 (2097 699
       (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP))
 (2060 204 (:REWRITE ALL-DARGP-WHEN-NOT-CONSP))
 (1998 1998 (:TYPE-PRESCRIPTION ALL-CONSP))
 (1779 1779
       (:REWRITE CONSP-WHEN-LEN-EQUAL-CONSTANT))
 (1744 300 (:REWRITE ALL-CONSP-OF-CDR))
 (1398 1398 (:TYPE-PRESCRIPTION PSEUDO-DAGP))
 (1398 699
       (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
 (1304 100
       (:REWRITE ALL-<-OF-0-WHEN-NAT-LISTP))
 (1264 100 (:REWRITE ALL-<-OF-0-WHEN-ALL-NATP))
 (1149 1149 (:REWRITE USE-ALL-<-2))
 (1149 1149 (:REWRITE USE-ALL-<))
 (1149 1149 (:REWRITE DEFAULT-<-1))
 (1149 1149
       (:REWRITE <-WHEN-BOUNDED-AXE-TREEP))
 (1149 1149
       (:REWRITE <-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (1136 1136 (:REWRITE USE-ALL-CONSP-2))
 (1136 1136 (:REWRITE USE-ALL-CONSP))
 (1136 1136 (:REWRITE CONSP-WHEN-LEN-GREATER))
 (1111 567 (:REWRITE DEFAULT-+-2))
 (1065 1045
       (:REWRITE <-OF-LEN-WHEN-NTH-NON-NIL))
 (1065 1045
       (:REWRITE <-OF-LEN-WHEN-INTEGERP-OF-NTH))
 (1045 1045
       (:REWRITE CAR-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
 (1006 61 (:REWRITE DARGP-WHEN-CONSP-CHEAP))
 (999 999
      (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
 (999 61 (:DEFINITION QUOTEP))
 (904 36 (:REWRITE ALL-<-OF-CDR))
 (900 12 (:DEFINITION SYMBOL-ALISTP))
 (898 449
      (:REWRITE PSEUDO-TERM-LISTP-WHEN-SYMBOL-LISTP-CHEAP))
 (898 48 (:REWRITE ALL-NATP-OF-CDR))
 (748 748 (:TYPE-PRESCRIPTION NAT-LISTP))
 (745 745
      (:REWRITE ALISTP-WHEN-PSEUDO-DAGP-AUX))
 (745 745
      (:REWRITE ALISTP-WHEN-BOUNDED-NATP-ALISTP))
 (705 15 (:DEFINITION STRIP-CARS))
 (699 699
      (:REWRITE TRUE-LISTP-OF-CAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
 (699 699
      (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX-2))
 (699 699
      (:REWRITE CONSP-OF-CAR-WHEN-PSEUDO-DAGP-AUX))
 (618 89 (:REWRITE ALL-DARGP-OF-CDR))
 (580 295
      (:REWRITE SYMBOLP-OF-CAR-WHEN-AXE-TREEP-CHEAP))
 (567 567 (:REWRITE DEFAULT-+-1))
 (506 506 (:TYPE-PRESCRIPTION ALL-NATP))
 (449 449
      (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
 (412 206
      (:REWRITE ALL-DARGP-WHEN-ALL-MYQUOTEP-CHEAP))
 (385 385
      (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
 (349 30 (:DEFINITION MEMBER-EQUAL))
 (301 301
      (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
 (296 148
      (:REWRITE ALL-NATP-WHEN-NAT-LISTP-CHEAP))
 (289 289
      (:REWRITE SYMBOLP-WHEN-BOUNDED-DAG-EXPRP))
 (289 289
      (:REWRITE SYMBOLP-OF-CAR-WHEN-BOUNDED-DAG-EXPRP))
 (275 275
      (:REWRITE TRUE-LISTP-WHEN-PSEUDO-DAGP-AUX))
 (256 27 (:REWRITE USE-ALL-DARGP-FOR-CAR))
 (240 8 (:DEFINITION BINARY-APPEND))
 (236 118
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-SIMPLE))
 (236 118
      (:TYPE-PRESCRIPTION
           TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX-SIMPLE))
 (210 210 (:TYPE-PRESCRIPTION NATP))
 (208 208
      (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP-AUX))
 (206 206 (:TYPE-PRESCRIPTION ALL-MYQUOTEP))
 (206 206
      (:REWRITE ALL-DARGP-WHEN-ALL-DARGP-LESS-THAN))
 (200 200 (:TYPE-PRESCRIPTION ALL-<))
 (192 52 (:REWRITE +-COMBINE-CONSTANTS))
 (188 188
      (:REWRITE EQUAL-OF-+-COMBINE-CONSTANTS))
 (183 183
      (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
 (173 173
      (:REWRITE TRUE-LISTP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
 (157 113
      (:REWRITE AXE-TREEP-WHEN-EQUAL-OF-CAR-AND-QUOTE-CHEAP))
 (152 152 (:REWRITE USE-ALL-NATP-2))
 (152 152 (:REWRITE USE-ALL-NATP))
 (152 152
      (:REWRITE NATP-WHEN-ALL-DARGP-LESS-THAN-GEN))
 (152 38
      (:REWRITE AREF1-WHEN-TOO-LARGE-CHEAP))
 (148 148
      (:REWRITE ALL-NATP-WHEN-NOT-CONSP-CHEAP))
 (148 148 (:REWRITE ALL-NATP-WHEN-NOT-CONSP))
 (140 70
      (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1))
 (140 70
      (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-NATP-CHEAP))
 (140 70
      (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-INTEGERP-CHEAP))
 (130 130
      (:TYPE-PRESCRIPTION TYPE-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP-AUX))
 (118
    118
    (:TYPE-PRESCRIPTION TRUE-LISTP-OF-DARGS-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (118 118
      (:TYPE-PRESCRIPTION PSEUDO-DAG-ARRAYP))
 (113 113
      (:REWRITE AXE-TREEP-WHEN-NOT-CONSP-AND-NOT-SYMBOLP-CHEAP))
 (110 110
      (:REWRITE AXE-TREEP-WHEN-SYMBOLP-CHEAP))
 (109 109
      (:REWRITE QUOTE-LEMMA-FOR-ALL-DARGP-LESS-THAN-GEN-ALT))
 (107 107 (:REWRITE DEFAULT-COERCE-2))
 (107 107 (:REWRITE DEFAULT-COERCE-1))
 (101 61
      (:REWRITE DARGP-WHEN-EQUAL-OF-QUOTE-AND-CAR-CHEAP))
 (100 100
      (:REWRITE ALL-<-WHEN-NOT-CONSP-CHEAP))
 (100 100 (:REWRITE ALL-<-WHEN-NOT-CONSP))
 (100 100 (:REWRITE ALL-<-TRANSITIVE-FREE-2))
 (100 100 (:REWRITE ALL-<-TRANSITIVE-FREE))
 (100 100 (:REWRITE ALL-<-TRANSITIVE))
 (89 89
     (:REWRITE EQUAL-OF-NON-NATP-AND-CAAR-WHEN-WHEN-BOUNDED-NATP-ALISTP))
 (76 38 (:TYPE-PRESCRIPTION ALEN1-TYPE))
 (76 38 (:REWRITE NTH-WHEN-<=-LEN-CHEAP))
 (70 70
     (:TYPE-PRESCRIPTION SYMBOLP-OF-CAR-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (70 70 (:TYPE-PRESCRIPTION ALL-INTEGERP))
 (70 70
     (:REWRITE INTEGERP-WHEN-DARGP-LESS-THAN))
 (70 70
     (:REWRITE INTEGERP-OF-CAR-WHEN-ALL-DARGP-LESS-THAN))
 (64 64 (:REWRITE USE-ALL-<=-2))
 (64 64 (:REWRITE USE-ALL-<=))
 (64 64
     (:REWRITE NOT-<-OF-CAR-WHEN-ALL-DARGP-LESS-THAN-2))
 (64 64
     (:REWRITE NONNEG-WHEN-DARGP-LESS-THAN))
 (61 61 (:TYPE-PRESCRIPTION DARGP))
 (61 61 (:REWRITE USE-ALL-DARGP-2))
 (61 61 (:REWRITE USE-ALL-DARGP))
 (61 61
     (:REWRITE MYQUOTEP-WHEN-DARGP-LESS-THAN))
 (61 61
     (:REWRITE MYQUOTEP-WHEN-BOUNDED-DAG-EXPRP))
 (61 61 (:REWRITE MYQUOTEP-WHEN-AXE-TREEP))
 (61 61
     (:REWRITE DARGP-WHEN-DARGP-LESS-THAN))
 (58 38 (:REWRITE NTH-WHEN-NOT-CONSP-CHEAP))
 (58 38 (:REWRITE NTH-WHEN-NOT-CDDR))
 (48 24
     (:REWRITE SYMBOL-ALISTP-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
 (48 24 (:REWRITE DARGP-WHEN-MYQUOTEP-CHEAP))
 (44 44 (:TYPE-PRESCRIPTION STRIP-CARS))
 (42 24 (:REWRITE DARGP-WHEN-NATP-CHEAP))
 (42 11
     (:REWRITE UNIFY-TREE-WITH-DAG-NODE-MONO))
 (40 40
     (:TYPE-PRESCRIPTION SYMBOLP-OF-NTH-0-OF-AREF1-WHEN-PSEUDO-DAG-ARRAYP))
 (40 20 (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP))
 (40 20 (:REWRITE LEN-OF-NTH-OF-DARGS))
 (40 20
     (:REWRITE LEN-OF-NTH-0-WHEN-AXE-TREEP-CHEAP))
 (40 20
     (:REWRITE LEN-OF-AREF1-WHEN-QUOTEP-AND-PSEUDO-DAG-ARRAYP-AUX))
 (38 38 (:TYPE-PRESCRIPTION POSP-OF-ALEN1))
 (38 38 (:TYPE-PRESCRIPTION ARRAY1P))
 (38 38 (:REWRITE NTH-WHEN-ZP-CHEAP))
 (24 24 (:TYPE-PRESCRIPTION MYQUOTEP))
 (20 20 (:TYPE-PRESCRIPTION DAG-EXPRP0))
 (20 20
     (:REWRITE LEN-OF-NTH-WHEN-ALL-DARGP-LESS-THAN)))
