(ALL-CDRS-RATIONALP (17 2 (:REWRITE CONSP-FROM-LEN-CHEAP))
                    (10 2 (:REWRITE DEFAULT-CDR))
                    (5 2
                       (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
                    (4 4 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
                    (3 1 (:REWRITE USE-ALL-CONSP))
                    (2 2 (:TYPE-PRESCRIPTION MEMBERP))
                    (2 1 (:REWRITE DEFAULT-<-2))
                    (1 1 (:REWRITE USE-ALL-CONSP-2))
                    (1 1 (:REWRITE DEFAULT-CAR))
                    (1 1 (:REWRITE DEFAULT-<-1))
                    (1 1 (:REWRITE CONSP-WHEN-LEN-GREATER))
                    (1 1
                       (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
                    (1 1 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP)))
(ALL-CDRS-RATIONALP-OF-CONS)
(USE-ALL-CDRS-RATIONALP-FOR-CAR)
(USE-ALL-CDRS-RATIONALP-FOR-CAR-OF-LAST (2 2 (:TYPE-PRESCRIPTION LAST)))
(ALL-CDRS-RATIONALP-OF-APPEND)
(ALL-CDRS-RATIONALP-OF-UNION-EQUAL)
(ALL-CDRS-RATIONALP-WHEN-NOT-CONSP)
(ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP)
(ALL-CDRS-RATIONALP-OF-REVAPPEND)
(ALL-CDRS-RATIONALP-OF-CDR)
(ALL-CDRS-RATIONALP-OF-NTHCDR)
(ALL-CDRS-RATIONALP-OF-FIRSTN)
(ALL-CDRS-RATIONALP-OF-REMOVE1-EQUAL)
(ALL-CDRS-RATIONALP-OF-REMOVE-EQUAL)
(ALL-CDRS-RATIONALP-OF-LAST)
(ALL-CDRS-RATIONALP-OF-TAKE)
(ALL-CDRS-RATIONALP-WHEN-PERM)
(ALL-CDRS-RATIONALP-OF-TRUE-LIST-FIX)
(PERM-IMPLIES-EQUAL-ALL-CDRS-RATIONALP-1)
(USE-ALL-CDRS-RATIONALP)
(USE-ALL-CDRS-RATIONALP-2)
(ALL-CDRS-RATIONALP-OF-ADD-TO-SET-EQUAL)
(MERGE-BY-CDR->
     (316 36 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (138 26 (:REWRITE DEFAULT-CDR))
     (114 6 (:DEFINITION TRUE-LISTP))
     (112 112 (:TYPE-PRESCRIPTION MEMBERP))
     (100 30 (:REWRITE DEFAULT-<-2))
     (96 12
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (94 22 (:REWRITE USE-ALL-CONSP))
     (78 78 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (78 30 (:REWRITE DEFAULT-<-1))
     (54 14 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (28 14
         (:TYPE-PRESCRIPTION TRUE-LISTP-REVAPPEND-TYPE-PRESCRIPTION))
     (22 22 (:REWRITE USE-ALL-CONSP-2))
     (22 22 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (16 16
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP))
     (16 16
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
     (14 14 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (14 14 (:REWRITE DEFAULT-CAR))
     (12 12
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (12 12 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (12 11 (:REWRITE DEFAULT-+-2))
     (12 11 (:REWRITE DEFAULT-+-1))
     (4 4 (:REWRITE FOLD-CONSTS-IN-+)))
(ACL2-COUNT-OF-EVENS-BOUND
     (6189 3216 (:REWRITE DEFAULT-+-2))
     (4141 3216 (:REWRITE DEFAULT-+-1))
     (1828 1228 (:REWRITE DEFAULT-<-2))
     (1386 1228 (:REWRITE DEFAULT-<-1))
     (573 503 (:REWRITE DEFAULT-CAR))
     (567 567 (:REWRITE USE-ALL-CONSP-2))
     (567 567 (:REWRITE USE-ALL-CONSP))
     (567 567 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (441 441 (:REWRITE DEFAULT-UNARY-MINUS))
     (300 57 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (238 238 (:REWRITE DEFAULT-DENOMINATOR))
     (225 225
          (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (219 219 (:REWRITE DEFAULT-COERCE-2))
     (219 219 (:REWRITE DEFAULT-COERCE-1))
     (212 212 (:REWRITE DEFAULT-NUMERATOR))
     (211 211
          (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (203 203 (:REWRITE DEFAULT-REALPART))
     (203 203 (:REWRITE DEFAULT-IMAGPART))
     (114 114 (:TYPE-PRESCRIPTION ALL-CONSP))
     (114 57
          (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (72 57 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (57 57
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (57 57
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (47 47 (:REWRITE EQUAL-OF-LEN-AND-0))
     (46 46 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (46 46 (:REWRITE USE-ALL-CDRS-RATIONALP)))
(<-OF-ACL2-COUNT-OF-EVENS
     (1663 928 (:REWRITE DEFAULT-+-2))
     (1171 928 (:REWRITE DEFAULT-+-1))
     (456 114 (:DEFINITION INTEGER-ABS))
     (450 301 (:REWRITE DEFAULT-<-2))
     (351 147 (:REWRITE DEFAULT-CAR))
     (345 32 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (341 301 (:REWRITE DEFAULT-<-1))
     (249 249 (:REWRITE USE-ALL-CONSP-2))
     (249 249 (:REWRITE USE-ALL-CONSP))
     (249 249 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (228 57 (:DEFINITION LENGTH))
     (185 40 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (173 8 (:REWRITE ACL2-COUNT-OF-EVENS-BOUND))
     (114 114 (:REWRITE DEFAULT-UNARY-MINUS))
     (92 92
         (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (81 8 (:REWRITE ALL-CONSP-OF-CDR))
     (80 80 (:TYPE-PRESCRIPTION ALL-CONSP))
     (75 75
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (64 32
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (57 57 (:REWRITE DEFAULT-REALPART))
     (57 57 (:REWRITE DEFAULT-NUMERATOR))
     (57 57 (:REWRITE DEFAULT-IMAGPART))
     (57 57 (:REWRITE DEFAULT-DENOMINATOR))
     (57 57 (:REWRITE DEFAULT-COERCE-2))
     (57 57 (:REWRITE DEFAULT-COERCE-1))
     (40 40
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (32 32
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (10 10 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (10 10 (:REWRITE USE-ALL-CDRS-RATIONALP)))
(ALISTP-OF-MERGE-BY-CDR->
     (2825 296 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (792 98 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (421 397 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (368 46
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (318 114 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (280 14 (:REWRITE ALL-CONSP-OF-REVAPPEND))
     (248 248 (:REWRITE USE-ALL-CONSP-2))
     (248 248 (:REWRITE USE-ALL-CONSP))
     (248 248 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (230 46
          (:REWRITE USE-ALL-CDRS-RATIONALP-FOR-CAR))
     (228 228 (:TYPE-PRESCRIPTION ALL-CONSP))
     (196 98
          (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (190 176 (:REWRITE DEFAULT-CAR))
     (128 114
          (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (98 98
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (92 92
         (:TYPE-PRESCRIPTION ALL-CDRS-RATIONALP))
     (46 46 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (46 46 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (46 46
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP))
     (46 46
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
     (30 6 (:REWRITE LEN-OF-CDR))
     (30 6 (:REWRITE ALL-CONSP-OF-CDR))
     (6 6 (:REWRITE DEFAULT-+-2))
     (6 6 (:REWRITE DEFAULT-+-1))
     (6 6
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN)))
(MERGE-SORT-BY-CDR->
     (7268 572 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (4960 2615 (:REWRITE DEFAULT-+-2))
     (3447 2615 (:REWRITE DEFAULT-+-1))
     (1519 1017 (:REWRITE DEFAULT-<-2))
     (1161 1017 (:REWRITE DEFAULT-<-1))
     (563 563 (:REWRITE USE-ALL-CONSP-2))
     (563 563 (:REWRITE USE-ALL-CONSP))
     (563 563 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (506 486 (:REWRITE DEFAULT-CAR))
     (359 359 (:REWRITE DEFAULT-UNARY-MINUS))
     (300 60 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (242 242
          (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (198 198 (:REWRITE DEFAULT-DENOMINATOR))
     (183 183
          (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (178 178 (:REWRITE DEFAULT-COERCE-2))
     (178 178 (:REWRITE DEFAULT-COERCE-1))
     (170 170 (:REWRITE DEFAULT-NUMERATOR))
     (161 161 (:REWRITE DEFAULT-REALPART))
     (161 161 (:REWRITE DEFAULT-IMAGPART))
     (148 16 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (120 120 (:TYPE-PRESCRIPTION ALL-CONSP))
     (120 60
          (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (60 60
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (60 60
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (60 60 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (48 48 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (48 48 (:REWRITE USE-ALL-CDRS-RATIONALP)))
(ALL-CONPS-OF-EVENS (236 19 (:REWRITE CONSP-FROM-LEN-CHEAP))
                    (207 8 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
                    (130 10 (:REWRITE DEFAULT-CDR))
                    (59 19 (:REWRITE USE-ALL-CONSP))
                    (40 40 (:TYPE-PRESCRIPTION MEMBERP))
                    (37 19 (:REWRITE DEFAULT-<-2))
                    (37 5 (:REWRITE LEN-OF-CDR))
                    (36 18
                        (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
                    (34 30 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
                    (26 26 (:TYPE-PRESCRIPTION EVENS))
                    (19 19 (:REWRITE USE-ALL-CONSP-2))
                    (19 19 (:REWRITE DEFAULT-<-1))
                    (19 19 (:REWRITE CONSP-WHEN-LEN-GREATER))
                    (9 5 (:REWRITE DEFAULT-+-2))
                    (5 5 (:REWRITE DEFAULT-CAR))
                    (5 5 (:REWRITE DEFAULT-+-1))
                    (5 5
                       (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
                    (4 4 (:REWRITE EQUAL-OF-LEN-AND-0)))
(ALL-CONSP-OF-MERGE-BY-CDR->
     (719 78 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (617 26 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (362 54 (:REWRITE USE-ALL-CONSP))
     (308 308 (:TYPE-PRESCRIPTION MEMBERP))
     (236 44 (:REWRITE DEFAULT-CDR))
     (216 66 (:REWRITE DEFAULT-<-2))
     (216 10 (:DEFINITION REVAPPEND))
     (192 24
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (162 66 (:REWRITE DEFAULT-<-1))
     (120 24
          (:REWRITE USE-ALL-CDRS-RATIONALP-FOR-CAR))
     (115 115 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (54 54 (:REWRITE USE-ALL-CONSP-2))
     (54 54 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (48 48
         (:TYPE-PRESCRIPTION ALL-CDRS-RATIONALP))
     (44 44 (:REWRITE DEFAULT-CAR))
     (24 24 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (24 24 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (24 24
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP))
     (24 24
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP)))
(ALL-CONSP-OF-MERGE-SORT-BY-CDR->
     (1312 121 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (937 12 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (874 89 (:REWRITE DEFAULT-CDR))
     (707 9 (:DEFINITION MERGE-BY-CDR->))
     (651 15 (:DEFINITION EVENS))
     (332 90 (:REWRITE USE-ALL-CONSP))
     (242 242 (:TYPE-PRESCRIPTION MEMBERP))
     (207 70 (:REWRITE DEFAULT-<-2))
     (178 166 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (144 18
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (142 70 (:REWRITE DEFAULT-<-1))
     (90 90 (:REWRITE USE-ALL-CONSP-2))
     (90 90 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (90 18
         (:REWRITE USE-ALL-CDRS-RATIONALP-FOR-CAR))
     (71 40 (:REWRITE DEFAULT-+-2))
     (66 66 (:TYPE-PRESCRIPTION EVENS))
     (51 51 (:REWRITE DEFAULT-CAR))
     (40 40 (:REWRITE DEFAULT-+-1))
     (36 36
         (:TYPE-PRESCRIPTION ALL-CDRS-RATIONALP))
     (24 2 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (24 1
         (:REWRITE ALL-CONSP-OF-MERGE-BY-CDR->))
     (18 18 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (18 18 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (18 18
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (18 18
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP))
     (18 18
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
     (18 18 (:DEFINITION REVAPPEND))
     (12 12
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (9 9
        (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN)))
(ALL-CDRS-RATIONALP-OF-EVENS
     (234 19 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (189 8
          (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
     (129 11 (:REWRITE DEFAULT-CDR))
     (38 18
         (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
     (37 5 (:REWRITE LEN-OF-CDR))
     (35 31 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (35 18 (:REWRITE DEFAULT-<-2))
     (26 26 (:TYPE-PRESCRIPTION EVENS))
     (18 18 (:REWRITE USE-ALL-CONSP-2))
     (18 18 (:REWRITE USE-ALL-CONSP))
     (18 18 (:REWRITE DEFAULT-<-1))
     (18 18 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (9 5 (:REWRITE DEFAULT-+-2))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE DEFAULT-+-1))
     (5 5
        (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (5 1 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (4 4 (:TYPE-PRESCRIPTION MEMBERP))
     (4 4 (:REWRITE EQUAL-OF-LEN-AND-0))
     (1 1 (:REWRITE USE-ALL-CDRS-RATIONALP-2)))
(ALL-CDRS-RATIONALP-OF-MERGE-BY-CDR->
     (715 78 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (483 26
          (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
     (256 24
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (254 46 (:REWRITE DEFAULT-CDR))
     (244 64 (:REWRITE DEFAULT-<-2))
     (198 26 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (192 64 (:REWRITE DEFAULT-<-1))
     (172 172 (:TYPE-PRESCRIPTION MEMBERP))
     (160 10 (:DEFINITION REVAPPEND))
     (117 117 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (52 52 (:REWRITE USE-ALL-CONSP-2))
     (52 52 (:REWRITE USE-ALL-CONSP))
     (52 52 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (44 44 (:REWRITE DEFAULT-CAR))
     (26 26 (:REWRITE USE-ALL-CDRS-RATIONALP-2)))
(ALL-CDRS-RATIONALP-OF-MERGE-SORT-BY-CDR->
     (1282 121 (:REWRITE CONSP-FROM-LEN-CHEAP))
     (871 27
          (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
     (810 89 (:REWRITE DEFAULT-CDR))
     (695 9 (:DEFINITION MERGE-BY-CDR->))
     (585 15 (:DEFINITION EVENS))
     (229 70 (:REWRITE DEFAULT-<-2))
     (200 18
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (178 166 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (176 70 (:REWRITE DEFAULT-<-1))
     (90 90 (:REWRITE USE-ALL-CONSP-2))
     (90 90 (:REWRITE USE-ALL-CONSP))
     (90 90 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (86 18 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (78 18
         (:REWRITE USE-ALL-CDRS-RATIONALP-FOR-CAR))
     (71 40 (:REWRITE DEFAULT-+-2))
     (68 68 (:TYPE-PRESCRIPTION MEMBERP))
     (66 66 (:TYPE-PRESCRIPTION EVENS))
     (51 51 (:REWRITE DEFAULT-CAR))
     (40 40 (:REWRITE DEFAULT-+-1))
     (27 27
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP))
     (18 18 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (18 18
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (18 18 (:DEFINITION REVAPPEND))
     (18 1
         (:REWRITE ALL-CDRS-RATIONALP-OF-MERGE-BY-CDR->))
     (14 2 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (9 9
        (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN)))
(MERGE-SORT-BY-CDR-> (732 62 (:REWRITE CONSP-FROM-LEN-CHEAP))
                     (472 2 (:DEFINITION MERGE-SORT-BY-CDR->))
                     (438 52 (:REWRITE DEFAULT-CDR))
                     (366 8 (:DEFINITION EVENS))
                     (178 2 (:DEFINITION MERGE-BY-CDR->))
                     (126 44 (:REWRITE USE-ALL-CONSP))
                     (122 110 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
                     (106 36 (:REWRITE DEFAULT-<-2))
                     (90 90 (:TYPE-PRESCRIPTION MEMBERP))
                     (68 36 (:REWRITE DEFAULT-<-1))
                     (62 32 (:REWRITE DEFAULT-+-2))
                     (60 4
                         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                     (44 44 (:REWRITE USE-ALL-CONSP-2))
                     (44 44 (:REWRITE CONSP-WHEN-LEN-GREATER))
                     (40 4
                         (:REWRITE USE-ALL-CDRS-RATIONALP-FOR-CAR))
                     (36 4 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
                     (32 32 (:REWRITE DEFAULT-+-1))
                     (20 4 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
                     (20 4
                         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
                     (16 16 (:REWRITE DEFAULT-CAR))
                     (16 4 (:REWRITE FOLD-CONSTS-IN-+))
                     (12 12
                         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
                     (12 4 (:REWRITE USE-ALL-CDRS-RATIONALP))
                     (6 6
                        (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
                     (4 4 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
                     (4 4
                        (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
                     (4 4
                        (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP))
                     (4 4 (:DEFINITION REVAPPEND)))
(ALISTP-OF-EVENS (166 11 (:REWRITE USE-ALL-CONSP-FOR-CAR))
                 (80 20 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
                 (77 10 (:REWRITE ALL-CONSP-OF-CDR))
                 (72 15 (:REWRITE LEN-OF-CDR))
                 (64 2 (:REWRITE ALL-CONPS-OF-EVENS))
                 (51 27 (:REWRITE DEFAULT-CDR))
                 (49 47 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
                 (43 43 (:TYPE-PRESCRIPTION ALL-CONSP))
                 (40 25 (:REWRITE DEFAULT-<-2))
                 (25 25 (:REWRITE USE-ALL-CONSP-2))
                 (25 25 (:REWRITE USE-ALL-CONSP))
                 (25 25 (:REWRITE DEFAULT-<-1))
                 (25 25 (:REWRITE CONSP-WHEN-LEN-GREATER))
                 (23 19 (:REWRITE DEFAULT-CAR))
                 (20 20
                     (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
                 (20 10
                     (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
                 (15 15 (:REWRITE DEFAULT-+-2))
                 (15 15 (:REWRITE DEFAULT-+-1))
                 (10 10
                     (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
                 (10 10
                     (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
                 (9 3 (:REWRITE FOLD-CONSTS-IN-+))
                 (3 3
                    (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN)))
(ALISTP-OF-ODDS (126 8 (:REWRITE CONSP-FROM-LEN-CHEAP))
                (68 1 (:DEFINITION EVENS))
                (59 59 (:TYPE-PRESCRIPTION LEN))
                (46 6 (:REWRITE DEFAULT-CDR))
                (39 5 (:REWRITE LEN-OF-CDR))
                (20 3 (:REWRITE USE-ALL-CONSP-FOR-CAR))
                (17 8 (:REWRITE DEFAULT-<-2))
                (15 15 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
                (13 7
                    (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
                (10 5 (:REWRITE DEFAULT-+-2))
                (8 8 (:TYPE-PRESCRIPTION ALL-CONSP))
                (8 8 (:REWRITE USE-ALL-CONSP-2))
                (8 8 (:REWRITE USE-ALL-CONSP))
                (8 8 (:REWRITE DEFAULT-<-1))
                (8 8 (:REWRITE CONSP-WHEN-LEN-GREATER))
                (6 3
                   (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
                (5 5 (:REWRITE DEFAULT-+-1))
                (5 1 (:REWRITE ALL-CONSP-OF-CDR))
                (4 4 (:REWRITE EQUAL-OF-LEN-AND-0))
                (4 4 (:REWRITE DEFAULT-CAR))
                (4 4
                   (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
                (4 4 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
                (4 1 (:REWRITE FOLD-CONSTS-IN-+))
                (3 3
                   (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
                (3 3
                   (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
                (1 1
                   (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN)))
(ALISTP-OF-MERGE-SORT-BY-CDR->
     (1813 8 (:DEFINITION MERGE-BY-CDR->))
     (1453 176 (:REWRITE DEFAULT-CDR))
     (1373 16
           (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1325 16
           (:REWRITE USE-ALL-CDRS-RATIONALP-FOR-CAR))
     (1311 42 (:DEFINITION EVENS))
     (1245 16
           (:REWRITE ALL-CDRS-RATIONALP-OF-MERGE-SORT-BY-CDR->))
     (1099 51
           (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP))
     (909 136 (:REWRITE DEFAULT-<-1))
     (825 136 (:REWRITE DEFAULT-<-2))
     (684 22 (:REWRITE USE-ALL-CONSP-FOR-CAR))
     (492 46 (:REWRITE ALL-CONSP-WHEN-NOT-CONSP))
     (481 10
          (:REWRITE ALL-CONSP-OF-MERGE-SORT-BY-CDR->))
     (334 291 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
     (248 248 (:TYPE-PRESCRIPTION EVENS))
     (245 16
          (:REWRITE ALL-CDRS-RATIONALP-OF-EVENS))
     (236 2 (:REWRITE ALISTP-OF-MERGE-BY-CDR->))
     (205 205 (:REWRITE USE-ALL-CONSP-2))
     (205 205 (:REWRITE USE-ALL-CONSP))
     (205 205 (:REWRITE CONSP-WHEN-LEN-GREATER))
     (133 77 (:REWRITE DEFAULT-+-2))
     (118 2
          (:REWRITE ALL-CONSP-OF-MERGE-BY-CDR->))
     (117 97 (:REWRITE DEFAULT-CAR))
     (102 102
          (:TYPE-PRESCRIPTION ALL-CDRS-RATIONALP))
     (92 92 (:TYPE-PRESCRIPTION ALL-CONSP))
     (77 77 (:REWRITE DEFAULT-+-1))
     (73 7 (:REWRITE ALL-CONPS-OF-EVENS))
     (71 51
         (:REWRITE ALL-CDRS-RATIONALP-WHEN-NOT-CONSP-CHEAP))
     (54 46
         (:REWRITE ALL-CONSP-WHEN-NOT-CONSP-CHEAP))
     (45 5 (:REWRITE ALL-CONSP-OF-CDR))
     (44 22
         (:REWRITE CONSP-OF-CAR-WHEN-SYMBOL-TERM-ALISTP-CHEAP))
     (33 5 (:REWRITE ALL-CDRS-RATIONALP-OF-CDR))
     (29 29
         (:REWRITE CONSP-OF-CDR-WHEN-LEN-KNOWN))
     (22 22
         (:TYPE-PRESCRIPTION SYMBOL-TERM-ALISTP))
     (21 21
         (:REWRITE LEN-OF-CDDR-WHEN-EQUAL-OF-LEN))
     (21 3 (:LINEAR LEN-OF-CDR-LINEAR-STRONG))
     (16 16 (:REWRITE USE-ALL-CDRS-RATIONALP-2))
     (16 16 (:REWRITE USE-ALL-CDRS-RATIONALP))
     (16 16 (:DEFINITION REVAPPEND))
     (12 12 (:TYPE-PRESCRIPTION ODDS)))
