(FTY::TMP-DEFFIXTYPE-IDEMPOTENT
 (33 33 (:TYPE-PRESCRIPTION PSEUDO-EVENT-FORM-FIX))
 )
(PSEUDO-EVENT-FORM-EQUIV$INLINE
 (4 4 (:TYPE-PRESCRIPTION PSEUDO-EVENT-FORM-FIX))
 )
(PSEUDO-EVENT-FORM-EQUIV-IS-AN-EQUIVALENCE)
(PSEUDO-EVENT-FORM-EQUIV-IMPLIES-EQUAL-PSEUDO-EVENT-FORM-FIX-1)
(PSEUDO-EVENT-FORM-FIX-UNDER-PSEUDO-EVENT-FORM-EQUIV)
(EQUAL-OF-PSEUDO-EVENT-FORM-FIX-1-FORWARD-TO-PSEUDO-EVENT-FORM-EQUIV)
(EQUAL-OF-PSEUDO-EVENT-FORM-FIX-2-FORWARD-TO-PSEUDO-EVENT-FORM-EQUIV)
(PSEUDO-EVENT-FORM-EQUIV-OF-PSEUDO-EVENT-FORM-FIX-1-FORWARD)
(PSEUDO-EVENT-FORM-EQUIV-OF-PSEUDO-EVENT-FORM-FIX-2-FORWARD)
