(X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR
 (32 16
     (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (16 16 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (8 2
    (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (4
  4
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (4
  4
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (4
  4
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (4 2 (:REWRITE X86ISA::MEMBER-P-CDR))
 (2 2
    (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (2 2
    (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (2 2
    (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (1
   1
   (:REWRITE X86ISA::XLATE-EQUIV-ENTRIES-AND-SET-ACCESSED-AND/OR-DIRTY-BIT)))
(X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR
 (40 2 (:REWRITE LOGTAIL-IDENTITY))
 (16 2
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (16 2
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (10 4
     (:REWRITE X86ISA::RM-LOW-64-IN-APP-VIEW))
 (6 2 (:DEFINITION X86ISA::APP-VIEW$INLINE))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (4 4 (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (4 4
    (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (4 4
    (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (4 4
    (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (4
  4
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (4
  4
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (4 2
    (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (4 2
    (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4 2
    (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (2 2 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (2
  2
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (2 1 (:REWRITE X86ISA::MEMBER-P-CDR))
 (1 1
    (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET)))
(X86ISA::XLATE-EQUIV-MEMORY-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR-CONG
 (482 7
      (:DEFINITION X86ISA::OPEN-QWORD-PADDR-LIST))
 (319 35 (:REWRITE IFIX-WHEN-INTEGERP))
 (307 49
      (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
 (304 14 (:DEFINITION X86ISA::ADDR-RANGE))
 (227 7 (:DEFINITION BINARY-APPEND))
 (198 14 (:DEFINITION INTEGER-LISTP))
 (171 7 (:REWRITE X86ISA::CAR-ADDR-RANGE))
 (112 112 (:TYPE-PRESCRIPTION INTEGER-LISTP))
 (100
    100
    (:TYPE-PRESCRIPTION X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (79 35 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (73 7 (:REWRITE LOGHEAD-IDENTITY))
 (48 6
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-3BITS-P))
 (42 28 (:REWRITE DEFAULT-CDR))
 (35 11
     (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (32 16 (:REWRITE DEFAULT-+-2))
 (28 28
     (:REWRITE X86ISA::NEG-ADDR-RANGE=NIL))
 (28 28
     (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
 (28 14
     (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
 (26 14
     (:REWRITE X86ISA::MEMBER-P-AND-MULT-8-QWORD-PADDR-LISTP))
 (24 12 (:REWRITE X86ISA::MEMBER-P-CDR))
 (22
  22
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (22
  22
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (21 21 (:REWRITE DEFAULT-CAR))
 (18 18 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
 (16 16 (:REWRITE DEFAULT-+-1))
 (14 14
     (:TYPE-PRESCRIPTION X86ISA::TRUE-LISTP-ADDR-RANGE))
 (14 14
     (:TYPE-PRESCRIPTION X86ISA::CONSP-ADDR-RANGE))
 (14 7 (:REWRITE X86ISA::CDR-ADDR-RANGE))
 (12 12 (:TYPE-PRESCRIPTION X86ISA::3BITS-P))
 (12 12
     (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (12 6
     (:REWRITE X86ISA::3BITS-P-WHEN-UNSIGNED-BYTE-P))
 (11 11
     (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (11 11
     (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (10 10
     (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (8 8
    (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (8 4
    (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (7 7
    (:TYPE-PRESCRIPTION X86ISA::MEMBER-P-PHYSICAL-ADDRESS-P))
 (7 7 (:TYPE-PRESCRIPTION IFIX))
 (7 7
    (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV)))
(X86ISA::XLATE-EQUIV-MEMORY-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR-CONG
 (40 2 (:REWRITE LOGTAIL-IDENTITY))
 (16 2
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (16 2
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (10 4
     (:REWRITE X86ISA::RM-LOW-64-IN-APP-VIEW))
 (6 3
    (:REWRITE X86ISA::XLATE-EQUIV-ENTRIES-AND-SET-ACCESSED-AND/OR-DIRTY-BIT))
 (6 2 (:DEFINITION X86ISA::APP-VIEW$INLINE))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (4 4 (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (4 4
    (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (4 4
    (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (4 4
    (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (4
  4
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (4
  4
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (4 2
    (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (4 2
    (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4 2
    (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (2 2 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (2
  2
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (2
  2
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (2
  2
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES)))
(X86ISA::IA32E-LA-TO-PA-PML4-TABLE-IN-APP-VIEW)
(X86ISA::XLATE-EQUIV-ENTRIES-AND-IA32E-PML4EBITS->PDPT)
(X86ISA::XLATE-EQUIV-MEMORY-AND-IA32E-LA-TO-PA-PML4-TABLE
 (2809 313
       (:REWRITE X86ISA::4K-ALIGNED-PHYSICAL-ADDRESS-HELPER))
 (2057 413 (:REWRITE LOGHEAD-IDENTITY))
 (1126 1126
       (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (912 48
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-1))
 (912 48 (:LINEAR LOGHEAD-UPPER-BOUND))
 (772 388
      (:REWRITE X86ISA::CANONICAL-ADDRESS-P-AND-LOGEXT-48))
 (761 761
      (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (745 43
      (:REWRITE X86ISA::PAGE-PRESENT=0-AND-PAGING-ENTRY-NO-PAGE-FAULT-P))
 (676 388 (:REWRITE LOGEXT-IDENTITY))
 (509 317
      (:REWRITE X86ISA::RM-LOW-64-IN-APP-VIEW))
 (480 96
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (480 96
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (413 413
      (:REWRITE X86ISA::LOGHEAD-ZERO-SMALLER))
 (413 413
      (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (381 321
      (:REWRITE BITOPS::LOGAND-WITH-BITMASK))
 (323 33 (:REWRITE ASH-0))
 (317
   317
   (:REWRITE X86ISA::WEED-OUT-IRRELEVANT-LOGAND-WHEN-FIRST-OPERAND-CONSTANT))
 (317 317 (:REWRITE X86ISA::LOGAND-REDUNDANT))
 (317
  317
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (317
  317
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (312 312
      (:TYPE-PRESCRIPTION X86ISA::PAGE-PRESENT))
 (312 312
      (:TYPE-PRESCRIPTION X86ISA::N01P-PAGE-PRESENT))
 (308
  308
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (308
  308
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (288 48
      (:DEFINITION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (278 65
      (:REWRITE X86ISA::IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-IN-APP-VIEW))
 (240 48
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-PREFIXES-P))
 (234 78 (:LINEAR X86ISA::N01P-PAGE-PRESENT))
 (232 232
      (:TYPE-PRESCRIPTION X86ISA::IA32E-PML4EBITS->PDPT$INLINE))
 (203 29 (:REWRITE ZIP-OPEN))
 (192 192
      (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (192 192
      (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (192 96
      (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (192 96
      (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (156 156
      (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (144 144 (:TYPE-PRESCRIPTION SIGNED-BYTE-P))
 (144 48
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-2))
 (96 96
     (:TYPE-PRESCRIPTION X86ISA::PREFIXES-P$INLINE))
 (96 96
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-UNSIGNED-BYTE-P-SMALLER))
 (96 96
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-SIGNED-BYTE-P-SMALLER))
 (96 96
     (:REWRITE BITOPS::SIGNED-BYTE-P-MONOTONICITY))
 (96 96
     (:REWRITE BITOPS::SIGNED-BYTE-P-INCR))
 (96 48
     (:REWRITE X86ISA::PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (62 33 (:REWRITE RIGHT-SHIFT-TO-LOGTAIL))
 (60 60 (:TYPE-PRESCRIPTION BITMASKP$INLINE))
 (49 18
     (:REWRITE X86ISA::PAGE-DIR-PTR-TABLE-LOWER-12-BITS-ERROR))
 (48 48
     (:TYPE-PRESCRIPTION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (48 48
     (:REWRITE X86ISA::CANONICAL-ADDRESS-P-LIMITS-THM-3))
 (44
  9
  (:REWRITE
       X86ISA::XR-AND-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-IN-NON-MARKING-VIEW))
 (43 43
     (:REWRITE
          X86ISA::MV-NTH-0-PAGING-ENTRY-NO-PAGE-FAULT-P-AND-SIMILAR-ENTRIES))
 (33 33
     (:REWRITE X86ISA::IA32E-PML4EBITS->PDPT-OF-WRITE-WITH-MASK))
 (33
  33
  (:REWRITE
   X86ISA::IA32E-PML4EBITS->PDPT$INLINE-OF-IA32E-PML4EBITS-FIX-X-NORMALIZE-CONST))
 (32
  4
  (:REWRITE
    X86ISA::UNSIGNED-BYTE-P-WHEN-SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-SEGMENT-SELECTORBITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-RFLAGSBITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-MXCSRBITS-P))
 (32
  4
  (:REWRITE
   X86ISA::UNSIGNED-BYTE-P-WHEN-INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-FP-STATUSBITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-EVEX-PREFIXES-P))
 (32
  4
  (:REWRITE
      X86ISA::UNSIGNED-BYTE-P-WHEN-DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-CR0BITS-P))
 (32
  4
  (:REWRITE
      X86ISA::UNSIGNED-BYTE-P-WHEN-CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (32
    4
    (:REWRITE
         X86ISA::UNSIGNED-BYTE-P-WHEN-CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-32BITS-P))
 (32 4
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-16BITS-P))
 (29 29 (:TYPE-PRESCRIPTION ZIP))
 (24
  5
  (:REWRITE
   X86ISA::MV-NTH-2-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-SYSTEM-LEVEL-NON-MARKING-VIEW))
 (24 4
     (:REWRITE X86ISA::ACCESSED-BIT-SET-ACCESSED-BIT-IDENTITY))
 (20 8 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (16 4
     (:REWRITE X86ISA::IA32E-LA-TO-PA-PML4-TABLE-IN-APP-VIEW))
 (9 9
    (:REWRITE X86ISA::IA32E-PAGE-TABLESBITS->A-OF-WRITE-WITH-MASK))
 (9
  9
  (:REWRITE
   X86ISA::IA32E-PAGE-TABLESBITS->A$INLINE-OF-IA32E-PAGE-TABLESBITS-FIX-X-NORMALIZE-CONST))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::SEGMENT-SELECTORBITS-P))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::RFLAGSBITS-P$INLINE))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::MXCSRBITS-P))
 (8 8
    (:TYPE-PRESCRIPTION
         X86ISA::INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::FP-STATUSBITS-P))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::EVEX-PREFIXES-P$INLINE))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::CR0BITS-P$INLINE))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (8 8
    (:TYPE-PRESCRIPTION X86ISA::CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (8 8 (:TYPE-PRESCRIPTION X86ISA::32BITS-P))
 (8 8 (:TYPE-PRESCRIPTION X86ISA::16BITS-P))
 (8 8 (:REWRITE UNSIGNED-BYTE-P-LOGHEAD))
 (8
  4
  (:REWRITE
    X86ISA::SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::SEGMENT-SELECTORBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::RFLAGSBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::MXCSRBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8
  4
  (:REWRITE
   X86ISA::INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::FP-STATUSBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::EVEX-PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (8
  4
  (:REWRITE
      X86ISA::DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::CR0BITS-P-WHEN-UNSIGNED-BYTE-P))
 (8
  4
  (:REWRITE
      X86ISA::CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE
         X86ISA::CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::32BITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 4
    (:REWRITE X86ISA::16BITS-P-WHEN-UNSIGNED-BYTE-P))
 (8 2
    (:REWRITE BITOPS::CANCEL-LOGEXT-UNDER-LOGHEAD))
 (5 5 (:REWRITE DEFAULT-<-2))
 (5 5 (:REWRITE DEFAULT-<-1))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::N01P-ACCESSED-BIT))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::ACCESSED-BIT))
 (4 4 (:REWRITE BITOPS::LOGHEAD-OF-0-I)))
(X86ISA::XLATE-EQUIV-MEMORY-AND-MV-NTH-0-IA32E-LA-TO-PA-PML4-TABLE-CONG)
(X86ISA::XLATE-EQUIV-MEMORY-AND-MV-NTH-1-IA32E-LA-TO-PA-PML4-TABLE-CONG)
(X86ISA::XLATE-EQUIV-STRUCTURES-AND-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE
 (3040 695 (:REWRITE LOGHEAD-IDENTITY))
 (2656 368
       (:REWRITE X86ISA::4K-ALIGNED-PHYSICAL-ADDRESS-HELPER))
 (1529 1529
       (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (1106 1106
       (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (932 695
      (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (928 722
      (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (836 44
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-1))
 (836 44 (:LINEAR LOGHEAD-UPPER-BOUND))
 (803 451
      (:REWRITE X86ISA::CANONICAL-ADDRESS-P-AND-LOGEXT-48))
 (715 451 (:REWRITE LOGEXT-IDENTITY))
 (690 690
      (:REWRITE X86ISA::LOGHEAD-ZERO-SMALLER))
 (556 450
      (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-MARKING-VIEW-TYPE))
 (520 98
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (520 98
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (514 356
      (:REWRITE X86ISA::RM-LOW-64-IN-APP-VIEW))
 (422 372
      (:REWRITE BITOPS::LOGAND-WITH-BITMASK))
 (384 384
      (:TYPE-PRESCRIPTION X86ISA::CTRI-IS-N64P))
 (370
   370
   (:REWRITE X86ISA::WEED-OUT-IRRELEVANT-LOGAND-WHEN-FIRST-OPERAND-CONSTANT))
 (370 370 (:REWRITE X86ISA::LOGAND-REDUNDANT))
 (356
  356
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (356
  356
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (340
  340
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (340 5
      (:DEFINITION X86ISA::OPEN-QWORD-PADDR-LIST))
 (316 316 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (264 44
      (:DEFINITION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (233 53 (:REWRITE ASH-0))
 (230 14
      (:REWRITE X86ISA::PAGE-PRESENT=0-AND-PAGING-ENTRY-NO-PAGE-FAULT-P))
 (220 44
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-PREFIXES-P))
 (215 35
      (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
 (215 10 (:DEFINITION X86ISA::ADDR-RANGE))
 (196 196
      (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (196 196
      (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (196 98
      (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (196 98
      (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (179 179
      (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (160 5 (:DEFINITION BINARY-APPEND))
 (144 144
      (:TYPE-PRESCRIPTION X86ISA::IA32E-PML4EBITS->PDPT$INLINE))
 (140 10 (:DEFINITION INTEGER-LISTP))
 (132 132 (:TYPE-PRESCRIPTION SIGNED-BYTE-P))
 (132 44
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-2))
 (126 18 (:REWRITE ZIP-OPEN))
 (120 5 (:REWRITE X86ISA::CAR-ADDR-RANGE))
 (118 118
      (:TYPE-PRESCRIPTION X86ISA::MSRI-IS-N64P))
 (113 57
      (:REWRITE X86ISA::IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-IN-APP-VIEW))
 (96 96
     (:TYPE-PRESCRIPTION X86ISA::PAGE-PRESENT))
 (96 96
     (:TYPE-PRESCRIPTION X86ISA::N01P-PAGE-PRESENT))
 (96 12
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-RFLAGSBITS-P))
 (96 12
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-MXCSRBITS-P))
 (96 12
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-EVEX-PREFIXES-P))
 (96 12
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-CR0BITS-P))
 (96 12
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-32BITS-P))
 (88 88
     (:TYPE-PRESCRIPTION X86ISA::PREFIXES-P$INLINE))
 (88 88
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-UNSIGNED-BYTE-P-SMALLER))
 (88 88
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-SIGNED-BYTE-P-SMALLER))
 (88 88
     (:REWRITE BITOPS::SIGNED-BYTE-P-MONOTONICITY))
 (88 88
     (:REWRITE BITOPS::SIGNED-BYTE-P-INCR))
 (88 44
     (:REWRITE X86ISA::PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (80 80 (:TYPE-PRESCRIPTION INTEGER-LISTP))
 (80 10
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-CR4BITS-P))
 (80 10
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-22BITS-P))
 (78
  30
  (:REWRITE
   X86ISA::MV-NTH-2-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-SYSTEM-LEVEL-NON-MARKING-VIEW))
 (72 24 (:LINEAR X86ISA::N01P-PAGE-PRESENT))
 (71 53 (:REWRITE RIGHT-SHIFT-TO-LOGTAIL))
 (65 29 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (62 17
     (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (58 58
     (:REWRITE X86ISA::SEGMENT-SELECTORBITS->RPL-OF-WRITE-WITH-MASK))
 (58
  58
  (:REWRITE
   X86ISA::SEGMENT-SELECTORBITS->RPL$INLINE-OF-SEGMENT-SELECTORBITS-FIX-X-NORMALIZE-CONST))
 (58 58
     (:REWRITE X86ISA::RFLAGSBITS->AC-OF-WRITE-WITH-MASK))
 (58 58
     (:REWRITE
          X86ISA::RFLAGSBITS->AC$INLINE-OF-RFLAGSBITS-FIX-X-NORMALIZE-CONST))
 (58 58
     (:REWRITE X86ISA::IA32_EFERBITS->NXE-OF-WRITE-WITH-MASK))
 (58
  58
  (:REWRITE
   X86ISA::IA32_EFERBITS->NXE$INLINE-OF-IA32_EFERBITS-FIX-X-NORMALIZE-CONST))
 (58 58
     (:REWRITE X86ISA::CR4BITS->SMEP-OF-WRITE-WITH-MASK))
 (58
    58
    (:REWRITE X86ISA::CR4BITS->SMEP$INLINE-OF-CR4BITS-FIX-X-NORMALIZE-CONST))
 (58 58
     (:REWRITE X86ISA::CR4BITS->SMAP-OF-WRITE-WITH-MASK))
 (58
    58
    (:REWRITE X86ISA::CR4BITS->SMAP$INLINE-OF-CR4BITS-FIX-X-NORMALIZE-CONST))
 (58 58
     (:REWRITE X86ISA::CR3BITS->PDB-OF-WRITE-WITH-MASK))
 (58 58
     (:REWRITE X86ISA::CR3BITS->PDB$INLINE-OF-CR3BITS-FIX-X-NORMALIZE-CONST))
 (58 58
     (:REWRITE X86ISA::CR0BITS->WP-OF-WRITE-WITH-MASK))
 (58 58
     (:REWRITE X86ISA::CR0BITS->WP$INLINE-OF-CR0BITS-FIX-X-NORMALIZE-CONST))
 (53 53
     (:REWRITE X86ISA::IA32E-PML4EBITS->PDPT-OF-WRITE-WITH-MASK))
 (53
  53
  (:REWRITE
   X86ISA::IA32E-PML4EBITS->PDPT$INLINE-OF-IA32E-PML4EBITS-FIX-X-NORMALIZE-CONST))
 (50 50 (:TYPE-PRESCRIPTION BITMASKP$INLINE))
 (44 44
     (:TYPE-PRESCRIPTION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (44 44
     (:REWRITE X86ISA::CANONICAL-ADDRESS-P-LIMITS-THM-3))
 (42 21 (:REWRITE X86ISA::MEMBER-P-CDR))
 (39
  23
  (:REWRITE
   X86ISA::XLATE-EQUIV-MEMORY-WITH-MV-NTH-2-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE))
 (32 32
     (:TYPE-PRESCRIPTION X86ISA::WM-LOW-64))
 (30 20 (:REWRITE DEFAULT-CDR))
 (24 24
     (:TYPE-PRESCRIPTION X86ISA::RFLAGSBITS-P$INLINE))
 (24 24
     (:TYPE-PRESCRIPTION X86ISA::MXCSRBITS-P))
 (24 24
     (:TYPE-PRESCRIPTION X86ISA::EVEX-PREFIXES-P$INLINE))
 (24 24
     (:TYPE-PRESCRIPTION X86ISA::CR0BITS-P$INLINE))
 (24 24
     (:TYPE-PRESCRIPTION X86ISA::32BITS-P))
 (24 12
     (:REWRITE X86ISA::RFLAGSBITS-P-WHEN-UNSIGNED-BYTE-P))
 (24 12
     (:REWRITE X86ISA::MXCSRBITS-P-WHEN-UNSIGNED-BYTE-P))
 (24 12
     (:REWRITE X86ISA::EVEX-PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (24 12
     (:REWRITE X86ISA::CR0BITS-P-WHEN-UNSIGNED-BYTE-P))
 (24 12
     (:REWRITE X86ISA::32BITS-P-WHEN-UNSIGNED-BYTE-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-3BITS-P))
 (22 6
     (:REWRITE X86ISA::PAGE-DIR-PTR-TABLE-LOWER-12-BITS-ERROR))
 (21 21
     (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (20 20
     (:TYPE-PRESCRIPTION X86ISA::CR4BITS-P$INLINE))
 (20 20
     (:TYPE-PRESCRIPTION X86ISA::22BITS-P))
 (20 20
     (:REWRITE X86ISA::NEG-ADDR-RANGE=NIL))
 (20 20
     (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
 (20 10
     (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
 (20 10 (:REWRITE DEFAULT-+-2))
 (20 10
     (:REWRITE X86ISA::CR4BITS-P-WHEN-UNSIGNED-BYTE-P))
 (20 10
     (:REWRITE X86ISA::22BITS-P-WHEN-UNSIGNED-BYTE-P))
 (18 18 (:TYPE-PRESCRIPTION ZIP))
 (17 17
     (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (17 17
     (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (16 16
     (:TYPE-PRESCRIPTION X86ISA::64-BIT-MODEP))
 (16
  2
  (:REWRITE
    X86ISA::UNSIGNED-BYTE-P-WHEN-SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (16 2
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-SEGMENT-SELECTORBITS-P))
 (16
  2
  (:REWRITE
   X86ISA::UNSIGNED-BYTE-P-WHEN-INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (16 2
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-FP-STATUSBITS-P))
 (16
  2
  (:REWRITE
      X86ISA::UNSIGNED-BYTE-P-WHEN-DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (16
  2
  (:REWRITE
      X86ISA::UNSIGNED-BYTE-P-WHEN-CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (16
    2
    (:REWRITE
         X86ISA::UNSIGNED-BYTE-P-WHEN-CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (16 2
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-16BITS-P))
 (15 15 (:REWRITE DEFAULT-CAR))
 (14 14
     (:REWRITE
          X86ISA::MV-NTH-0-PAGING-ENTRY-NO-PAGE-FAULT-P-AND-SIMILAR-ENTRIES))
 (10 10
     (:TYPE-PRESCRIPTION X86ISA::TRUE-LISTP-ADDR-RANGE))
 (10 10
     (:TYPE-PRESCRIPTION X86ISA::CONSP-ADDR-RANGE))
 (10 10
     (:REWRITE X86ISA::MEMBER-P-AND-MULT-8-QWORD-PADDR-LISTP))
 (10 10 (:REWRITE DEFAULT-+-1))
 (10 5 (:REWRITE X86ISA::CDR-ADDR-RANGE))
 (8 2
    (:REWRITE X86ISA::IA32E-LA-TO-PA-PML4-TABLE-IN-APP-VIEW))
 (8 2
    (:REWRITE BITOPS::CANCEL-LOGEXT-UNDER-LOGHEAD))
 (6 6 (:TYPE-PRESCRIPTION X86ISA::3BITS-P))
 (6 6
    (:REWRITE X86ISA::ACCESSED-BIT-SET-ACCESSED-BIT-IDENTITY))
 (6 3
    (:REWRITE X86ISA::3BITS-P-WHEN-UNSIGNED-BYTE-P))
 (6
  2
  (:REWRITE
   X86ISA::MV-NTH-2-PAGING-ENTRY-NO-PAGE-FAULT-P-WITH-XLATE-EQUIV-STRUCTURES))
 (5 5
    (:TYPE-PRESCRIPTION X86ISA::MEMBER-P-PHYSICAL-ADDRESS-P))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::SEGMENT-SELECTORBITS-P))
 (4 4
    (:TYPE-PRESCRIPTION
         X86ISA::INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::FP-STATUSBITS-P))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (4 4
    (:TYPE-PRESCRIPTION X86ISA::CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (4 4 (:TYPE-PRESCRIPTION X86ISA::16BITS-P))
 (4 4 (:REWRITE UNSIGNED-BYTE-P-LOGHEAD))
 (4 4 (:REWRITE BITOPS::LOGHEAD-OF-0-I))
 (4
  2
  (:REWRITE
    X86ISA::SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4 2
    (:REWRITE X86ISA::SEGMENT-SELECTORBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4
  2
  (:REWRITE
   X86ISA::INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4 2
    (:REWRITE X86ISA::FP-STATUSBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4
  2
  (:REWRITE
      X86ISA::DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4
  2
  (:REWRITE
      X86ISA::CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4 2
    (:REWRITE
         X86ISA::CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (4 2
    (:REWRITE X86ISA::16BITS-P-WHEN-UNSIGNED-BYTE-P))
 (2 2
    (:REWRITE X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-TRANSITIVE)))
(X86ISA::XLATE-EQUIV-STRUCTURES-AND-TWO-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE-CONG)
(X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-WITH-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE
 (5235 213 (:LINEAR LOGHEAD-UPPER-BOUND))
 (5017 395
       (:REWRITE X86ISA::4K-ALIGNED-PHYSICAL-ADDRESS-HELPER))
 (4698 174 (:REWRITE ASH-0))
 (4640 232
       (:REWRITE UNSIGNED-BYTE-P-OF-LOGTAIL))
 (4176 116 (:REWRITE ZIP-OPEN))
 (3461 553
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-PREFIXES-P))
 (2378 174 (:REWRITE LOGTAIL-IDENTITY))
 (2106 2106
       (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (1818 294
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (1818 294
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (1802 321
       (:REWRITE X86ISA::PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (1691 89
       (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-1))
 (1490 1490
       (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (1470 882
       (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (1249 537
       (:REWRITE X86ISA::CANONICAL-ADDRESS-P-AND-LOGEXT-48))
 (922 922
      (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (882 882
      (:REWRITE X86ISA::LOGHEAD-ZERO-SMALLER))
 (874 874
      (:TYPE-PRESCRIPTION X86ISA::PREFIXES-P$INLINE))
 (793 463
      (:REWRITE X86ISA::RM-LOW-64-IN-APP-VIEW))
 (588 588
      (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (588 588
      (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (588 294
      (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (588 294
      (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (580 290
      (:TYPE-PRESCRIPTION BITOPS::LOGTAIL-NATP))
 (540 445
      (:REWRITE BITOPS::LOGAND-WITH-BITMASK))
 (534 89
      (:DEFINITION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (479 238 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (463
  463
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (463
  463
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (446 22
      (:REWRITE X86ISA::PAGE-DIR-PTR-TABLE-LOWER-12-BITS-ERROR))
 (398
   398
   (:REWRITE X86ISA::WEED-OUT-IRRELEVANT-LOGAND-WHEN-FIRST-OPERAND-CONSTANT))
 (398 398 (:REWRITE X86ISA::LOGAND-REDUNDANT))
 (318
  318
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (288 18
      (:REWRITE X86ISA::PAGE-PRESENT=0-AND-PAGING-ENTRY-NO-PAGE-FAULT-P))
 (261 89
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-2))
 (250 250
      (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-UNSIGNED-BYTE-P-SMALLER))
 (250 250
      (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-SIGNED-BYTE-P-SMALLER))
 (250 250
      (:REWRITE BITOPS::SIGNED-BYTE-P-MONOTONICITY))
 (235 174 (:REWRITE RIGHT-SHIFT-TO-LOGTAIL))
 (182 182
      (:REWRITE BITOPS::SIGNED-BYTE-P-INCR))
 (164 68
      (:REWRITE X86ISA::IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-IN-APP-VIEW))
 (160 40
      (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (146 73 (:REWRITE X86ISA::MEMBER-P-CDR))
 (126
  126
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (120
    120
    (:TYPE-PRESCRIPTION X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (116 116 (:TYPE-PRESCRIPTION ZIP))
 (104 16
      (:REWRITE FTY::UNSIGNED-BYTE-P-1-WHEN-BITP))
 (95 95 (:TYPE-PRESCRIPTION BITMASKP$INLINE))
 (90 30 (:LINEAR X86ISA::N01P-PAGE-PRESENT))
 (89 89
     (:TYPE-PRESCRIPTION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (89 89
     (:REWRITE X86ISA::CANONICAL-ADDRESS-P-LIMITS-THM-3))
 (73 73
     (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (68 7
     (:REWRITE BITOPS::CANCEL-LOGEXT-UNDER-LOGHEAD))
 (66
  15
  (:REWRITE
       X86ISA::XR-AND-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-IN-NON-MARKING-VIEW))
 (60
  21
  (:REWRITE
   X86ISA::MV-NTH-2-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE-SYSTEM-LEVEL-NON-MARKING-VIEW))
 (60
  8
  (:REWRITE
       X86ISA::PAGE-DIR-PTR-TABLE-LOWER-12-BITS-VALUE-OF-ADDRESS-WHEN-ERROR))
 (48 8
     (:REWRITE X86ISA::PAGE-DIR-PTR-TABLE-LOWER-12-BITS))
 (45
  21
  (:REWRITE
   X86ISA::XLATE-EQUIV-MEMORY-WITH-MV-NTH-2-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE))
 (40 40 (:TYPE-PRESCRIPTION BITP-LOGHEAD-1))
 (40 40
     (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (40 40
     (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (39
  39
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (32 32
     (:TYPE-PRESCRIPTION
          X86ISA::N52P-MV-NTH-1-IA32E-LA-TO-PA-PAGE-DIR-PTR-TABLE))
 (32 32 (:TYPE-PRESCRIPTION BITP))
 (32 16
     (:REWRITE FTY::BITP-WHEN-UNSIGNED-BYTE-P-1))
 (28 4 (:REWRITE X86ISA::LOGHEAD-UNEQUAL))
 (24 24
     (:TYPE-PRESCRIPTION X86ISA::64-BIT-MODEP))
 (24
  3
  (:REWRITE
    X86ISA::UNSIGNED-BYTE-P-WHEN-SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-SEGMENT-SELECTORBITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-RFLAGSBITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-MXCSRBITS-P))
 (24
  3
  (:REWRITE
   X86ISA::UNSIGNED-BYTE-P-WHEN-INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-FP-STATUSBITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-EVEX-PREFIXES-P))
 (24
  3
  (:REWRITE
      X86ISA::UNSIGNED-BYTE-P-WHEN-DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-CR0BITS-P))
 (24
  3
  (:REWRITE
      X86ISA::UNSIGNED-BYTE-P-WHEN-CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (24
    3
    (:REWRITE
         X86ISA::UNSIGNED-BYTE-P-WHEN-CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-32BITS-P))
 (24 3
     (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-16BITS-P))
 (18 18
     (:REWRITE
          X86ISA::MV-NTH-0-PAGING-ENTRY-NO-PAGE-FAULT-P-AND-SIMILAR-ENTRIES))
 (17
  17
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (13
  13
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR))
 (12 3
     (:REWRITE X86ISA::IA32E-LA-TO-PA-PML4-TABLE-IN-APP-VIEW))
 (9
  9
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::SEGMENT-SELECTORBITS-P))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::RFLAGSBITS-P$INLINE))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::MXCSRBITS-P))
 (6 6
    (:TYPE-PRESCRIPTION
         X86ISA::INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::FP-STATUSBITS-P))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::EVEX-PREFIXES-P$INLINE))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::CR0BITS-P$INLINE))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P))
 (6 6 (:TYPE-PRESCRIPTION X86ISA::32BITS-P))
 (6 6 (:TYPE-PRESCRIPTION X86ISA::16BITS-P))
 (6 6 (:REWRITE UNSIGNED-BYTE-P-LOGHEAD))
 (6 6 (:REWRITE BITOPS::LOGHEAD-OF-0-I))
 (6 6
    (:REWRITE X86ISA::ACCESSED-BIT-SET-ACCESSED-BIT-IDENTITY))
 (6
  3
  (:REWRITE
    X86ISA::SYSTEM-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::SEGMENT-SELECTORBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::RFLAGSBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::MXCSRBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6
  3
  (:REWRITE
   X86ISA::INTERRUPT/TRAP-GATE-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::FP-STATUSBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::EVEX-PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (6
  3
  (:REWRITE
      X86ISA::DATA-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::CR0BITS-P-WHEN-UNSIGNED-BYTE-P))
 (6
  3
  (:REWRITE
      X86ISA::CODE-SEGMENT-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE
         X86ISA::CALL-GATE-DESCRIPTOR-ATTRIBUTESBITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::32BITS-P-WHEN-UNSIGNED-BYTE-P))
 (6 3
    (:REWRITE X86ISA::16BITS-P-WHEN-UNSIGNED-BYTE-P))
 (3 3
    (:REWRITE
         BITOPS::PART-SELECT-WIDTH-LOW$INLINE-OF-NFIX-WIDTH-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         BITOPS::PART-SELECT-WIDTH-LOW$INLINE-OF-NFIX-LOW-NORMALIZE-CONST))
 (3
   3
   (:REWRITE BITOPS::PART-SELECT-WIDTH-LOW$INLINE-OF-IFIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE X86ISA::IA32E-PML4EBITS->PDPT-OF-WRITE-WITH-MASK))
 (3
  3
  (:REWRITE
   X86ISA::IA32E-PML4EBITS->PDPT$INLINE-OF-IA32E-PML4EBITS-FIX-X-NORMALIZE-CONST)))
(X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-WITH-TWO-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE
 (2664 160 (:REWRITE LOGHEAD-IDENTITY))
 (1952
  44
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (1500 60 (:LINEAR LOGHEAD-UPPER-BOUND))
 (1440 72
       (:REWRITE UNSIGNED-BYTE-P-OF-LOGTAIL))
 (1440 36 (:REWRITE ASH-0))
 (1296 36 (:REWRITE ZIP-OPEN))
 (1248 24
       (:REWRITE X86ISA::4K-ALIGNED-PHYSICAL-ADDRESS-HELPER))
 (1088 16
       (:DEFINITION X86ISA::OPEN-QWORD-PADDR-LIST))
 (1056 168
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-PREFIXES-P))
 (864 152 (:REWRITE IFIX-WHEN-INTEGERP))
 (720 720
      (:TYPE-PRESCRIPTION X86ISA::N64P-RM-LOW-64))
 (720 36 (:REWRITE LOGTAIL-IDENTITY))
 (688 112
      (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
 (688 32 (:DEFINITION X86ISA::ADDR-RANGE))
 (580
  16
  (:REWRITE
   X86ISA::MULTIPLE-OF-8-DISJOINT-WITH-ADDR-RANGE-AND-OPEN-QWORD-PADDR-LIST-TO-MEMBER-P))
 (568 568 (:TYPE-PRESCRIPTION LOGHEAD-TYPE))
 (552 96
      (:REWRITE X86ISA::PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (528 84
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (528 84
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (512 16 (:DEFINITION BINARY-APPEND))
 (456 24
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-1))
 (448 32 (:DEFINITION INTEGER-LISTP))
 (384 16 (:REWRITE X86ISA::CAR-ADDR-RANGE))
 (320 152 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (288 144
      (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (268 268
      (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (264 264
      (:TYPE-PRESCRIPTION X86ISA::PREFIXES-P$INLINE))
 (256 256 (:TYPE-PRESCRIPTION INTEGER-LISTP))
 (256 256
      (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (252 60
      (:REWRITE X86ISA::CANONICAL-ADDRESS-P-AND-LOGEXT-48))
 (232
    232
    (:TYPE-PRESCRIPTION X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (204 60 (:REWRITE LOGEXT-IDENTITY))
 (196 196
      (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (168 168
      (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (168 168
      (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (168 84
      (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (168 84
      (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (144 144
      (:REWRITE X86ISA::LOGHEAD-ZERO-SMALLER))
 (144 72
      (:TYPE-PRESCRIPTION BITOPS::LOGTAIL-NATP))
 (144 24
      (:DEFINITION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (128 16
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-3BITS-P))
 (114 38
      (:DEFINITION X86ISA::APP-VIEW$INLINE))
 (104 44
      (:REWRITE X86ISA::RM-LOW-64-IN-APP-VIEW))
 (104 32
      (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (96 96 (:TYPE-PRESCRIPTION NFIX))
 (96 64 (:REWRITE DEFAULT-CDR))
 (96 32
     (:REWRITE X86ISA::MEMBER-P-AND-MULT-8-QWORD-PADDR-LISTP))
 (76 38
     (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (72 72 (:TYPE-PRESCRIPTION SIGNED-BYTE-P))
 (72 72
     (:TYPE-PRESCRIPTION X86ISA::NATP-PML4-TABLE-ENTRY-ADDR))
 (72 18
     (:REWRITE X86ISA::IA32E-LA-TO-PA-PML4-TABLE-IN-APP-VIEW))
 (64 64
     (:REWRITE X86ISA::NEG-ADDR-RANGE=NIL))
 (64 64
     (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
 (64 32 (:REWRITE X86ISA::MEMBER-P-CDR))
 (64 32
     (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
 (64 32 (:REWRITE DEFAULT-+-2))
 (48 48
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-UNSIGNED-BYTE-P-SMALLER))
 (48 48
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-SIGNED-BYTE-P-SMALLER))
 (48 48
     (:REWRITE BITOPS::SIGNED-BYTE-P-MONOTONICITY))
 (48 48
     (:REWRITE BITOPS::SIGNED-BYTE-P-INCR))
 (48
  48
  (:REWRITE
   X86ISA::MULT-8-QWORD-PADDR-LISTP-GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (48 48 (:REWRITE DEFAULT-CAR))
 (48 24
     (:REWRITE UNSIGNED-BYTE-P-OF-LOGHEAD))
 (48 24
     (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-2))
 (44
  44
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (44 36 (:REWRITE RIGHT-SHIFT-TO-LOGTAIL))
 (38 38 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (36 36 (:TYPE-PRESCRIPTION ZIP))
 (36 36
     (:TYPE-PRESCRIPTION X86ISA::NATP-PAGE-DIRECTORY-ENTRY-ADDR))
 (36 36
     (:TYPE-PRESCRIPTION X86ISA::NATP-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (36 24
     (:REWRITE BITOPS::LOGAND-WITH-NEGATED-BITMASK))
 (36 24
     (:REWRITE BITOPS::LOGAND-WITH-BITMASK))
 (32 32
     (:TYPE-PRESCRIPTION X86ISA::TRUE-LISTP-ADDR-RANGE))
 (32 32
     (:TYPE-PRESCRIPTION X86ISA::CONSP-ADDR-RANGE))
 (32 32 (:TYPE-PRESCRIPTION X86ISA::3BITS-P))
 (32 32
     (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (32 32
     (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (32 32
     (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (32 32 (:REWRITE DEFAULT-+-1))
 (32 16
     (:TYPE-PRESCRIPTION
          X86ISA::MEMBER-P-PHYSICAL-ADDRESS-P-PHYSICAL-ADDRESS-LISTP))
 (32 16 (:REWRITE X86ISA::CDR-ADDR-RANGE))
 (32 16
     (:REWRITE X86ISA::3BITS-P-WHEN-UNSIGNED-BYTE-P))
 (24 24
     (:TYPE-PRESCRIPTION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (24 24 (:TYPE-PRESCRIPTION BITMASKP$INLINE))
 (24
   24
   (:REWRITE X86ISA::WEED-OUT-IRRELEVANT-LOGAND-WHEN-FIRST-OPERAND-CONSTANT))
 (24 24
     (:REWRITE X86ISA::NEGATIVE-LOGAND-TO-POSITIVE-LOGAND-WITH-INTEGERP-X))
 (24 24 (:REWRITE X86ISA::LOGAND-REDUNDANT))
 (24 24
     (:REWRITE X86ISA::CANONICAL-ADDRESS-P-LIMITS-THM-3))
 (20
  20
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (16 16
     (:TYPE-PRESCRIPTION X86ISA::PHYSICAL-ADDRESS-P$INLINE))
 (16 16
     (:TYPE-PRESCRIPTION X86ISA::MEMBER-P-PHYSICAL-ADDRESS-P))
 (16 16
     (:TYPE-PRESCRIPTION X86ISA::DISJOINT-P))
 (12
  12
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (8
  8
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (4
  4
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR))
 (4
  4
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (4
  4
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR)))
(X86ISA::XLATE-EQUIV-MEMORY-WITH-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE
 (2798 172 (:REWRITE LOGHEAD-IDENTITY))
 (1792 34
       (:REWRITE X86ISA::4K-ALIGNED-PHYSICAL-ADDRESS-HELPER))
 (1661 69 (:LINEAR LOGHEAD-UPPER-BOUND))
 (1400 70
       (:REWRITE UNSIGNED-BYTE-P-OF-LOGTAIL))
 (1400 35 (:REWRITE ASH-0))
 (1260 35 (:REWRITE ZIP-OPEN))
 (1080 174
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-PREFIXES-P))
 (828 828
      (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
 (700 700
      (:TYPE-PRESCRIPTION X86ISA::N64P-RM-LOW-64))
 (700 35 (:REWRITE LOGTAIL-IDENTITY))
 (646 34
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-1))
 (622 622 (:TYPE-PRESCRIPTION LOGHEAD-TYPE))
 (620 103
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (620 103
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (558 104
      (:REWRITE X86ISA::PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (350 78
      (:REWRITE X86ISA::CANONICAL-ADDRESS-P-AND-LOGEXT-48))
 (321 321
      (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (312 172
      (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (282 78 (:REWRITE LOGEXT-IDENTITY))
 (278 278
      (:TYPE-PRESCRIPTION X86ISA::PREFIXES-P$INLINE))
 (277 277
      (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (234 234
      (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (206 206
      (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (206 206
      (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (206 103
      (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (206 103
      (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (204 34
      (:DEFINITION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (172 172
      (:REWRITE X86ISA::LOGHEAD-ZERO-SMALLER))
 (160 160 (:TYPE-PRESCRIPTION NFIX))
 (140 70
      (:TYPE-PRESCRIPTION BITOPS::LOGTAIL-NATP))
 (140 70 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (140 70 (:REWRITE IFIX-WHEN-INTEGERP))
 (104 26
      (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (102 102 (:TYPE-PRESCRIPTION SIGNED-BYTE-P))
 (92 34
     (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-2))
 (78
    78
    (:TYPE-PRESCRIPTION X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (68 68
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-UNSIGNED-BYTE-P-SMALLER))
 (68 68
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-SIGNED-BYTE-P-SMALLER))
 (68 68
     (:REWRITE BITOPS::SIGNED-BYTE-P-MONOTONICITY))
 (68 68
     (:REWRITE BITOPS::SIGNED-BYTE-P-INCR))
 (68 34
     (:REWRITE UNSIGNED-BYTE-P-OF-LOGHEAD))
 (63 34
     (:REWRITE BITOPS::LOGAND-WITH-BITMASK))
 (52
  52
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (52
  52
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (52 35 (:REWRITE RIGHT-SHIFT-TO-LOGTAIL))
 (52 26 (:REWRITE X86ISA::MEMBER-P-CDR))
 (35 35 (:TYPE-PRESCRIPTION ZIP))
 (34 34
     (:TYPE-PRESCRIPTION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (34
   34
   (:REWRITE X86ISA::WEED-OUT-IRRELEVANT-LOGAND-WHEN-FIRST-OPERAND-CONSTANT))
 (34 34
     (:REWRITE X86ISA::NEGATIVE-LOGAND-TO-POSITIVE-LOGAND-WITH-INTEGERP-X))
 (34 34 (:REWRITE X86ISA::LOGAND-REDUNDANT))
 (34 34
     (:REWRITE X86ISA::CANONICAL-ADDRESS-P-LIMITS-THM-3))
 (29 29 (:TYPE-PRESCRIPTION BITMASKP$INLINE))
 (26 26
     (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (26 26
     (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (26 26
     (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (21
  21
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (17 17 (:TYPE-PRESCRIPTION IFIX))
 (11
  11
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (8
  8
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (6
  4
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR))
 (6
  4
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (6 2
    (:DEFINITION X86ISA::MARKING-VIEW$INLINE))
 (4 2
    (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-MARKING-VIEW-TYPE))
 (4 1
    (:REWRITE X86ISA::XR-AND-IA32E-LA-TO-PA-PML4-TABLE-IN-NON-MARKING-VIEW))
 (4
  1
  (:REWRITE
   X86ISA::MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE-SYSTEM-LEVEL-NON-MARKING-VIEW))
 (3
  3
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR)))
(X86ISA::XLATE-EQUIV-MEMORY-WITH-TWO-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE
 (18205
  309
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (16786 1090 (:REWRITE LOGHEAD-IDENTITY))
 (10412 142
        (:DEFINITION X86ISA::OPEN-QWORD-PADDR-LIST))
 (9051 369 (:LINEAR LOGHEAD-UPPER-BOUND))
 (8692 186
       (:REWRITE X86ISA::4K-ALIGNED-PHYSICAL-ADDRESS-HELPER))
 (8184 228 (:REWRITE ASH-0))
 (8160 408
       (:REWRITE UNSIGNED-BYTE-P-OF-LOGTAIL))
 (7710 1118 (:REWRITE IFIX-WHEN-INTEGERP))
 (7344 204 (:REWRITE ZIP-OPEN))
 (6862 994
       (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
 (6484 284 (:DEFINITION X86ISA::ADDR-RANGE))
 (6129 981
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-PREFIXES-P))
 (5354
  142
  (:REWRITE
   X86ISA::MULTIPLE-OF-8-DISJOINT-WITH-ADDR-RANGE-AND-OPEN-QWORD-PADDR-LIST-TO-MEMBER-P))
 (4922 142 (:DEFINITION BINARY-APPEND))
 (4228 284 (:DEFINITION INTEGER-LISTP))
 (4104 4104
       (:TYPE-PRESCRIPTION X86ISA::N64P-RM-LOW-64))
 (4104 228 (:REWRITE LOGTAIL-IDENTITY))
 (3786 142 (:REWRITE X86ISA::CAR-ADDR-RANGE))
 (3502 3502 (:TYPE-PRESCRIPTION LOGHEAD-TYPE))
 (3282 534
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (3282 534
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (3186 573
       (:REWRITE X86ISA::PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (3135 165
       (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-1))
 (2704
    2704
    (:TYPE-PRESCRIPTION X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (2630 1118 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (2272 2272 (:TYPE-PRESCRIPTION INTEGER-LISTP))
 (1867 1867
       (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (1812 948
       (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (1752 432
       (:REWRITE X86ISA::CANONICAL-ADDRESS-P-AND-LOGEXT-48))
 (1653 1653
       (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (1554 1554
       (:TYPE-PRESCRIPTION X86ISA::PREFIXES-P$INLINE))
 (1422 432 (:REWRITE LOGEXT-IDENTITY))
 (1417 1417
       (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (1104 138
       (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-3BITS-P))
 (1068 1068
       (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (1068 1068
       (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (1068 534
       (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (1068 534
       (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (990 165
      (:DEFINITION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (948 948
      (:REWRITE X86ISA::LOGHEAD-ZERO-SMALLER))
 (864 432
      (:TYPE-PRESCRIPTION BITOPS::LOGTAIL-NATP))
 (852 568 (:REWRITE DEFAULT-CDR))
 (852 284
      (:REWRITE X86ISA::MEMBER-P-AND-MULT-8-QWORD-PADDR-LISTP))
 (817 289
      (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (751 751 (:TYPE-PRESCRIPTION NFIX))
 (650 325 (:REWRITE X86ISA::MEMBER-P-CDR))
 (600 600
      (:TYPE-PRESCRIPTION X86ISA::NATP-PML4-TABLE-ENTRY-ADDR))
 (568 568
      (:REWRITE X86ISA::NEG-ADDR-RANGE=NIL))
 (568 568
      (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
 (568 284
      (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
 (568 284 (:REWRITE DEFAULT-+-2))
 (495 495 (:TYPE-PRESCRIPTION SIGNED-BYTE-P))
 (468 468
      (:TYPE-PRESCRIPTION X86ISA::NATP-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (426
  426
  (:REWRITE
   X86ISA::MULT-8-QWORD-PADDR-LISTP-GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (426 426 (:REWRITE DEFAULT-CAR))
 (421 165
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-2))
 (351 117
      (:DEFINITION X86ISA::MARKING-VIEW$INLINE))
 (330 330
      (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-UNSIGNED-BYTE-P-SMALLER))
 (330 330
      (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-SIGNED-BYTE-P-SMALLER))
 (330 330
      (:REWRITE BITOPS::SIGNED-BYTE-P-MONOTONICITY))
 (330 330
      (:REWRITE BITOPS::SIGNED-BYTE-P-INCR))
 (330 165
      (:REWRITE UNSIGNED-BYTE-P-OF-LOGHEAD))
 (325 325
      (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (316 228 (:REWRITE RIGHT-SHIFT-TO-LOGTAIL))
 (314 186
      (:REWRITE BITOPS::LOGAND-WITH-NEGATED-BITMASK))
 (314 186
      (:REWRITE BITOPS::LOGAND-WITH-BITMASK))
 (309
  309
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (289 289
      (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (289 289
      (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (288
     72
     (:REWRITE X86ISA::XR-AND-IA32E-LA-TO-PA-PML4-TABLE-IN-NON-MARKING-VIEW))
 (284 284
      (:TYPE-PRESCRIPTION X86ISA::TRUE-LISTP-ADDR-RANGE))
 (284 284
      (:TYPE-PRESCRIPTION X86ISA::CONSP-ADDR-RANGE))
 (284 284 (:REWRITE DEFAULT-+-1))
 (284 142
      (:TYPE-PRESCRIPTION
           X86ISA::MEMBER-P-PHYSICAL-ADDRESS-P-PHYSICAL-ADDRESS-LISTP))
 (284 142 (:REWRITE X86ISA::CDR-ADDR-RANGE))
 (276 276
      (:TYPE-PRESCRIPTION X86ISA::3BITS-P))
 (276 138
      (:REWRITE X86ISA::3BITS-P-WHEN-UNSIGNED-BYTE-P))
 (256 256
      (:TYPE-PRESCRIPTION BITMASKP$INLINE))
 (234 117
      (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-MARKING-VIEW-TYPE))
 (207
  72
  (:REWRITE
   X86ISA::MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE-SYSTEM-LEVEL-NON-MARKING-VIEW))
 (204 204 (:TYPE-PRESCRIPTION ZIP))
 (198 198
      (:TYPE-PRESCRIPTION X86ISA::NATP-PAGE-DIRECTORY-ENTRY-ADDR))
 (186
   186
   (:REWRITE X86ISA::WEED-OUT-IRRELEVANT-LOGAND-WHEN-FIRST-OPERAND-CONSTANT))
 (186 186
      (:REWRITE X86ISA::NEGATIVE-LOGAND-TO-POSITIVE-LOGAND-WITH-INTEGERP-X))
 (186 186 (:REWRITE X86ISA::LOGAND-REDUNDANT))
 (165 165
      (:TYPE-PRESCRIPTION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (165 165
      (:REWRITE X86ISA::CANONICAL-ADDRESS-P-LIMITS-THM-3))
 (142 142
      (:TYPE-PRESCRIPTION X86ISA::PHYSICAL-ADDRESS-P$INLINE))
 (142 142
      (:TYPE-PRESCRIPTION X86ISA::MEMBER-P-PHYSICAL-ADDRESS-P))
 (142 142
      (:TYPE-PRESCRIPTION X86ISA::DISJOINT-P))
 (140
  140
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (72
  72
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (63
  63
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (16
  16
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR)))
(X86ISA::TWO-PML4-TABLE-WALKS-IA32E-LA-TO-PA-PML4-TABLE
 (618 36 (:REWRITE LOGHEAD-IDENTITY))
 (375 15 (:LINEAR LOGHEAD-UPPER-BOUND))
 (360 18
      (:REWRITE UNSIGNED-BYTE-P-OF-LOGTAIL))
 (360 9 (:REWRITE ASH-0))
 (324 9 (:REWRITE ZIP-OPEN))
 (312 6
      (:REWRITE X86ISA::4K-ALIGNED-PHYSICAL-ADDRESS-HELPER))
 (264 42
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-PREFIXES-P))
 (180 180
      (:TYPE-PRESCRIPTION X86ISA::N64P-RM-LOW-64))
 (180 9 (:REWRITE LOGTAIL-IDENTITY))
 (138 138 (:TYPE-PRESCRIPTION LOGHEAD-TYPE))
 (138 24
      (:REWRITE X86ISA::PREFIXES-P-WHEN-UNSIGNED-BYTE-P))
 (132 21
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-IA32_EFERBITS-P))
 (132 21
      (:REWRITE X86ISA::UNSIGNED-BYTE-P-WHEN-12BITS-P))
 (114 6
      (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-1))
 (72 36
     (:REWRITE X86ISA::LOGHEAD-OF-NON-INTEGERP))
 (66 66
     (:TYPE-PRESCRIPTION X86ISA::PREFIXES-P$INLINE))
 (63 63
     (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
 (63 15
     (:REWRITE X86ISA::CANONICAL-ADDRESS-P-AND-LOGEXT-48))
 (60 60
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (51 15 (:REWRITE LOGEXT-IDENTITY))
 (45 45
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (42 42
     (:TYPE-PRESCRIPTION X86ISA::IA32_EFERBITS-P$INLINE))
 (42 42
     (:TYPE-PRESCRIPTION X86ISA::12BITS-P))
 (42 21
     (:REWRITE X86ISA::IA32_EFERBITS-P-WHEN-UNSIGNED-BYTE-P))
 (42 21
     (:REWRITE X86ISA::12BITS-P-WHEN-UNSIGNED-BYTE-P))
 (36 36
     (:REWRITE X86ISA::LOGHEAD-ZERO-SMALLER))
 (36 18
     (:TYPE-PRESCRIPTION BITOPS::LOGTAIL-NATP))
 (36 18 (:REWRITE IFIX-WHEN-NOT-INTEGERP))
 (36 18 (:REWRITE IFIX-WHEN-INTEGERP))
 (36 6
     (:DEFINITION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (27 18
     (:REWRITE X86ISA::IA32E-LA-TO-PA-PML4-TABLE-IN-APP-VIEW))
 (26 11
     (:REWRITE X86ISA::RM-LOW-64-IN-APP-VIEW))
 (24 24 (:TYPE-PRESCRIPTION NFIX))
 (24 8 (:DEFINITION X86ISA::APP-VIEW$INLINE))
 (18 18 (:TYPE-PRESCRIPTION SIGNED-BYTE-P))
 (16 8
     (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (16 4
     (:REWRITE X86ISA::MEMBER-P-OF-NOT-A-CONSP))
 (12
    12
    (:TYPE-PRESCRIPTION X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES))
 (12 12
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-UNSIGNED-BYTE-P-SMALLER))
 (12 12
     (:REWRITE BITOPS::SIGNED-BYTE-P-WHEN-SIGNED-BYTE-P-SMALLER))
 (12 12
     (:REWRITE BITOPS::SIGNED-BYTE-P-MONOTONICITY))
 (12 12
     (:REWRITE BITOPS::SIGNED-BYTE-P-INCR))
 (12 6 (:REWRITE UNSIGNED-BYTE-P-OF-LOGHEAD))
 (12 6
     (:REWRITE BITOPS::LOGHEAD-OF-LOGHEAD-2))
 (11
  11
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AUX-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (11
  11
  (:REWRITE
   X86ISA::ALL-MEM-EXCEPT-PAGING-STRUCTURES-EQUAL-AND-RM-LOW-64-FROM-REST-OF-MEMORY))
 (11 9 (:REWRITE RIGHT-SHIFT-TO-LOGTAIL))
 (9 9 (:TYPE-PRESCRIPTION ZIP))
 (9 6
    (:REWRITE BITOPS::LOGAND-WITH-NEGATED-BITMASK))
 (9 6
    (:REWRITE BITOPS::LOGAND-WITH-BITMASK))
 (8 8 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (8 4 (:REWRITE X86ISA::MEMBER-P-CDR))
 (6 6
    (:TYPE-PRESCRIPTION X86ISA::CANONICAL-ADDRESS-P$INLINE))
 (6 6 (:TYPE-PRESCRIPTION BITMASKP$INLINE))
 (6
   6
   (:REWRITE X86ISA::WEED-OUT-IRRELEVANT-LOGAND-WHEN-FIRST-OPERAND-CONSTANT))
 (6 6
    (:REWRITE X86ISA::NEGATIVE-LOGAND-TO-POSITIVE-LOGAND-WITH-INTEGERP-X))
 (6 6 (:REWRITE X86ISA::LOGAND-REDUNDANT))
 (6 6
    (:REWRITE X86ISA::CANONICAL-ADDRESS-P-LIMITS-THM-3))
 (5
  5
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PML4-TABLE-ENTRY-ADDR))
 (4 4
    (:REWRITE X86ISA::SUBSET-P-CONS-MEMBER-P-LEMMA))
 (4 4
    (:REWRITE X86ISA::NOT-MEMBER-P-WHEN-DISJOINT-P))
 (4 4
    (:REWRITE X86ISA::MEMBER-P-OF-SUBSET-IS-MEMBER-P-OF-SUPERSET))
 (3
  3
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (2
  2
  (:REWRITE
   X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-IMPLIES-XLATE-EQUIV-ENTRIES))
 (1
  1
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR))
 (1
  1
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-XLATE-EQUIV-ENTRIES-RM-LOW-64-WITH-PAGE-DIR-PTR-TABLE-ENTRY-ADDR))
 (1
  1
  (:REWRITE
   X86ISA::XLATE-EQUIV-STRUCTURES-AND-LOGTAIL-12-RM-LOW-64-WITH-PAGE-DIRECTORY-ENTRY-ADDR)))
(X86ISA::GATHER-ALL-PAGING-STRUCTURE-QWORD-ADDRESSES-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE
 (22 11
     (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (12 12 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (4
  1
  (:REWRITE
   X86ISA::MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE-SYSTEM-LEVEL-NON-MARKING-VIEW))
 (3 1
    (:REWRITE
         X86ISA::XLATE-EQUIV-MEMORY-WITH-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE))
 (3 1
    (:DEFINITION X86ISA::MARKING-VIEW$INLINE))
 (2 2
    (:TYPE-PRESCRIPTION X86ISA::64-BIT-MODEP))
 (2 1
    (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-MARKING-VIEW-TYPE)))
(X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE
 (36 18
     (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-APP-VIEW-TYPE))
 (21 21 (:TYPE-PRESCRIPTION X86ISA::X86P))
 (12
  3
  (:REWRITE
   X86ISA::MV-NTH-2-IA32E-LA-TO-PA-PML4-TABLE-SYSTEM-LEVEL-NON-MARKING-VIEW))
 (9 9
    (:REWRITE X86ISA::XLATE-EQUIV-ENTRIES-AT-QWORD-ADDRESSES-TRANSITIVE))
 (9 3
    (:DEFINITION X86ISA::MARKING-VIEW$INLINE))
 (6 3
    (:TYPE-PRESCRIPTION X86ISA::BOOLEANP-MARKING-VIEW-TYPE)))
