(X86ISA::TTY-BUFFERP)
(X86ISA::TTY-BUFFER-FIX
 (1 1 (:TYPE-PRESCRIPTION X86ISA::TTY-BUFFER-FIX))
 )
(X86ISA::TTY-BUFFERP-OF-TTY-BUFFER-FIX
 (3 3 (:TYPE-PRESCRIPTION X86ISA::TTY-BUFFER-FIX))
 )
(X86ISA::TTY-BUFFER-FIX-IDENTITY-ON-TTY-BUFFERP
 (3 3 (:TYPE-PRESCRIPTION X86ISA::TTY-BUFFER-FIX))
 )
