language: common-lisp
sudo: false # lets try new infrastructure

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=test
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
# CLISP is disabled because it can't load bordeaux-treads which require ASDF >= 3.1
# Example log: https://travis-ci.org/cl-plus-ssl/cl-plus-ssl/jobs/181539210
# (As a workaround we could try to download ASDF 3 ourselves)
#    - LISP=clisp
    - LISP=ecl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh

#  cache:
#    directories:
#      - $HOME/.roswell
#      - $HOME/.config/common-lisp

script:
  - "ros -e '(progn
               (format t \"(lisp-implementation-type): ~A~%\" (lisp-implementation-type))
               (format t \"(lisp-implementation-version): ~A~%\" (lisp-implementation-version))
               (format t \"*features*: ~A~%\" *features*)
               (format t \"(asdf:asdf-version): ~A~%\" (asdf:asdf-version)))'
         -e '(ql:quickload :cl+ssl.test)'
         -e '(let ((results
                  #+ sbcl
                  (coveralls:with-coveralls (:exclude \"test\")
                     (5am:run :cl+ssl))
                  #- sbcl
                  (5am:run :cl+ssl)
                  ))
              (5am:explain! results)
              (unless (5am:results-status results)
                (uiop:quit 1)))'"
