include ../../Makefile-generic
ACL2 = ../../../saved_acl2

# From make dependencies:

ext.cert: ext.lisp
# ext.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic/top-with-meta.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/ihs/ihs-definitions.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/ihs/ihs-lemmas.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/rtl/rel7/arithmetic/top.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/rtl/rel7/arithmetic/extra-rules.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-2/meta/expt.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-2/meta/integerp.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/bind-free/top.cert
# ext.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/floor-mod/floor-mod.cert

top-ext.cert: top-ext.lisp
top-ext.cert: ext.cert
# top-ext.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/bind-free/top.cert
# top-ext.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/floor-mod/floor-mod.cert

