include ../../../Makefile-generic
-include Makefile-deps

# This makefile certifies the m5 model, including a recursive factorial
# method. This is unchanged (well almost) from J's standard Makefile.
