(OSLIB::TEMPFILE-FN)
(OSLIB::TYPE-OF-TEMPFILE-FN)
(OSLIB::STATE-P1-OF-TEMPFILE-FN)
(OSLIB::W-STATE-OF-TEMPFILE-FN)
(OSLIB::DEFAULT-TEMPFILE-AUX
     (137 6 (:DEFINITION BINARY-APPEND))
     (76 24 (:REWRITE STR::CONSP-OF-EXPLODE))
     (57 20 (:REWRITE DEFAULT-CDR))
     (57 20 (:REWRITE DEFAULT-CAR))
     (21 9
         (:REWRITE STR::DIGIT-LISTP-WHEN-NOT-CONSP))
     (19 12
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (18 6
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (16 16 (:REWRITE STR::NATSTR-NONEMPTY))
     (10 2 (:REWRITE STR::DIGIT-LISTP-OF-APPEND))
     (6 6 (:REWRITE STR::DIGIT-LISTP-OF-CONS))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (5 5
        (:REWRITE CAR-OF-STRING-LIST-FIX-X-NORMALIZE-CONST-UNDER-STREQV))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1)))
(OSLIB::RETURN-TYPE-OF-DEFAULT-TEMPFILE-AUX.TEMPFILE
     (229 10 (:DEFINITION BINARY-APPEND))
     (120 40 (:REWRITE STR::CONSP-OF-EXPLODE))
     (74 19 (:REWRITE DEFAULT-CDR))
     (74 19 (:REWRITE DEFAULT-CAR))
     (53 53
         (:TYPE-PRESCRIPTION STR::STRINGP-OF-NATSTR))
     (42 14
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (26 17
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (24 24 (:REWRITE STR::NATSTR-NONEMPTY))
     (21 9
         (:REWRITE STR::DIGIT-LISTP-WHEN-NOT-CONSP))
     (10 2 (:REWRITE STR::DIGIT-LISTP-OF-APPEND))
     (6 6 (:REWRITE STR::DIGIT-LISTP-OF-CONS))
     (5 5
        (:REWRITE CAR-OF-STRING-LIST-FIX-X-NORMALIZE-CONST-UNDER-STREQV))
     (4 4
        (:TYPE-PRESCRIPTION STRING-APPEND-LST))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1)))
(OSLIB::STATE-P1-OF-DEFAULT-TEMPFILE-AUX.NEW-STATE
     (137 6 (:DEFINITION BINARY-APPEND))
     (76 24 (:REWRITE STR::CONSP-OF-EXPLODE))
     (52 15 (:REWRITE DEFAULT-CDR))
     (52 15 (:REWRITE DEFAULT-CAR))
     (35 35
         (:TYPE-PRESCRIPTION STR::STRINGP-OF-NATSTR))
     (21 9
         (:REWRITE STR::DIGIT-LISTP-WHEN-NOT-CONSP))
     (19 12
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (18 6
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (16 16 (:REWRITE STR::NATSTR-NONEMPTY))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (10 2 (:REWRITE STR::DIGIT-LISTP-OF-APPEND))
     (8 2 (:DEFINITION STATE-P))
     (6 6 (:REWRITE STR::DIGIT-LISTP-OF-CONS))
     (5 5
        (:REWRITE CAR-OF-STRING-LIST-FIX-X-NORMALIZE-CONST-UNDER-STREQV))
     (4 4
        (:TYPE-PRESCRIPTION STRING-APPEND-LST))
     (4 4 (:TYPE-PRESCRIPTION STATE-P))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1)))
(OSLIB::W-STATE-OF-DEFAULT-TEMPFILE-AUX
     (137 6 (:DEFINITION BINARY-APPEND))
     (76 24 (:REWRITE STR::CONSP-OF-EXPLODE))
     (52 15 (:REWRITE DEFAULT-CDR))
     (52 15 (:REWRITE DEFAULT-CAR))
     (35 35
         (:TYPE-PRESCRIPTION STR::STRINGP-OF-NATSTR))
     (21 9
         (:REWRITE STR::DIGIT-LISTP-WHEN-NOT-CONSP))
     (19 12
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (18 6
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (16 16 (:REWRITE STR::NATSTR-NONEMPTY))
     (10 2 (:REWRITE STR::DIGIT-LISTP-OF-APPEND))
     (6 6 (:REWRITE STR::DIGIT-LISTP-OF-CONS))
     (5 5
        (:REWRITE CAR-OF-STRING-LIST-FIX-X-NORMALIZE-CONST-UNDER-STREQV))
     (4 4
        (:TYPE-PRESCRIPTION STRING-APPEND-LST))
     (4 4 (:DEFINITION NOT))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1)))
(OSLIB::PATHNAME-TO-UNIX
     (6 6
        (:TYPE-PRESCRIPTION TRUE-LISTP-SUBSTITUTE-TYPE-PRESCRIPTION))
     (6 6
        (:TYPE-PRESCRIPTION STRINGP-SUBSTITUTE-TYPE-PRESCRIPTION)))
(OSLIB::DEFAULT-TEMPDIR)
(OSLIB::STRINGP-OF-DEFAULT-TEMPDIR.TEMPDIR
     (36 2 (:DEFINITION SUBSTITUTE-AC))
     (18 18
         (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (16 4 (:REWRITE DEFAULT-CDR))
     (10 4 (:REWRITE DEFAULT-CAR))
     (8 8 (:REWRITE STR::CONSP-OF-EXPLODE))
     (2 2
        (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP)))
(OSLIB::STATE-P1-OF-DEFAULT-TEMPDIR.NEW-STATE
     (36 2 (:DEFINITION SUBSTITUTE-AC))
     (18 18
         (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (16 4 (:REWRITE DEFAULT-CDR))
     (10 4 (:REWRITE DEFAULT-CAR))
     (8 8 (:REWRITE STR::CONSP-OF-EXPLODE))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (4 1 (:DEFINITION STATE-P))
     (2 2 (:TYPE-PRESCRIPTION STATE-P))
     (2 2
        (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP)))
(OSLIB::W-STATE-OF-DEFAULT-TEMPDIR
     (36 2 (:DEFINITION SUBSTITUTE-AC))
     (18 18
         (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (16 4 (:REWRITE DEFAULT-CDR))
     (10 4 (:REWRITE DEFAULT-CAR))
     (8 8 (:REWRITE STR::CONSP-OF-EXPLODE))
     (2 2
        (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP)))
(OSLIB::DEFAULT-TEMPFILE)
(OSLIB::RETURN-TYPE-OF-DEFAULT-TEMPFILE.TEMPFILE)
(OSLIB::STATE-P1-OF-DEFAULT-TEMPFILE.NEW-STATE
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (4 1 (:DEFINITION STATE-P))
     (2 2 (:TYPE-PRESCRIPTION STATE-P)))
(OSLIB::W-STATE-OF-DEFAULT-TEMPFILE)
