## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

include ../dir.mk

# # .PHONY: depend
# # depend:
# # 	sh ../cert.mk

include $(DIR)/books/Makefile-generic
ACL2 = $(DIR)/saved_acl2

BOOKS = fac-source-shallow-canon fac-source-shallow-flatten proof-fac


