# We exclude MinVisor because the "lower" of its two books,
# MinVisor/setup-nested-page-tables.lisp, took over an hour and 38
# minutes to certify with an "Intel(R) Xeon(R) CPU E31280 @ 3.50GHz",
# a very fast machine as of November, 2011.

DIRS = Symbolic Utilities Memory Y86

include ../../../../Makefile-subdirs
