; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for inline assembly
; [GCCM:6.11]
; (https://gcc.gnu.org/onlinedocs/gcc/Using-Assembly-Language-with-C.html).
; These are GCC extensions but Clang supports them too.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; [GCCM] only provides a partial grammar.
; Our ABNF grammar rules formalize that and the rest of the documentated syntax.

; Inline assembly is introduced by the keywords 'asm', '__asm', or '__asm__'.
; [GCCM] describes three instances of this:
; 1. One to specify the assembler name of a function or variable
;    [GCCM:6.11.5](https://gcc.gnu.org/onlinedocs/gcc/Asm-Labels.html).
;    We call this 'assembler name specifier', which seems fitting,
;    although [GCCM] does not seem to use a precise term.
; 2. Basic assembler statements, i.e. instructions without operands
;    [GCCM:6.11.1](https://gcc.gnu.org/onlinedocs/gcc/Basic-Asm.html).
; 3. Extended assembler statements, i.e. instructions with operands
;    [GCCM:6.11.2](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html).

; An assembler name specifier consists of an 'asm' or variant keyword
; followed by a parenthesized sequence of one or more string literals.
; Recall that our grammar captures juxtaposed string literals,
; not just their concatenation; this is why we allow one or more here.

asm-name-specifier = asm-keyword "(" 1*string-literal ")"

; We capture basic and extended assembler statements together,
; with the basic ones as a special case of the extended ones.
; We follow the grammar in
; [GCCM:6.11.2](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html).
; Recall that we use ABNF repetitions of one or more string literals
; in order to capture the string juxtaposition prior to string concatenation.

asm-qualifier = volatile-keyword / inline-keyword / %s"goto"

asm-statement = asm-keyword
                *asm-qualifier
                "("
                1*string-literal
                [ ":" asm-output-operands
                [ ":" asm-input-operands
                [ ":" asm-clobbers
                [ ":" asm-goto-labels ] ] ] ]
                ")"
                ";"

asm-output-operands = [ asm-output-operand *( "," asm-output-operand ) ]

asm-output-operand = [ "[" identifier "]" ] 1*string-literal "(" expression ")"

asm-input-operands = [ asm-input-operand *( "," asm-input-operand ) ]

asm-input-operand = [ "[" identifier "]" ] 1*string-literal "(" expression ")"

asm-clobbers = [ asm-clobber *( "," asm-clobber ) ]

asm-clobber = 1*string-literal

asm-goto-labels = [ identifier *( "," identifier ) ]
