; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for attributes
; [GCCM:6.4.3](https://gcc.gnu.org/onlinedocs/gcc/Attribute-Syntax.html).
; These are GCC extensions but Clang supports them too.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; [GCCM] does not provide an explicit grammar.
; Our ABNF grammar rules formalize the documentated syntax.

; [GCCM] mentions three kinds of attributes:
; empty, names, and names with parameters.
; For now we do not model empty ones.
; We model the other two as consistsing of an attribute name
; optionally followed by a parenthesized list of one or more parameters.
; An attribute name is an identifier or a keyword:
; [GCCM] mentions identifiers and reserved words as attribute names,
; where 'reserved word' is presumably a synonym of 'keyword',
; according to the official nomenclature in [C17] and [C23].

; [GCCM] mentions three kinds of parameters,
; where each kind seems to refer to the whole list of parameters
; (not to individual parameters),
; because otherwise the grouping would be ambiguous.
; The three kinds are
; (i) a single identifier,
; (ii) an identifier followed by a comma
; and by a non-empty comma-separated sequence of expressions,
; and (iii) a possibly empty comma-separated sequence of expressions.
; These three alternatives overlap syntactically,
; because identifiers are expressions.
; Thus, in our grammar rules, we just say that
; attribute parameters are a parenthesized sequence of
; zero or more comma-separated assignment expressions.
; Note that we use assignment expressions, and not more general expressions,
; because otherwise the grouping would be ambiguous,
; if an expression included the comma operator.

attribute-name = identifier / keyword

attribute-parameters =
    "(" [ assignment-expression *( "," assignment-expression ) ] ")"

attribute = attribute-name [ attribute-parameters ]

; An attribute specifiers consists of
; the keyword '__attribute__' or '__attribute',
; followed by zero or more comma-separated attributes
; enclosed in double parentheses.
; We regard each double (open or closed) parenthesis
; as consisting of two separate tokens,
; so that we do not have to define a new kind of token.
; This means that our grammar allows white space and comments
; between the two open or closed parenthesis;
; Clang implementations allow that.

attribute-list = attribute *( "," attribute )

attribute-specifier = attribute-keyword "(" "(" [ attribute-list ] ")" ")"
