; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for the source character set
; in the C23 dialects.
; These rules have no counterparts in the grammar in [C23].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; The 32 graphic characters in [C23:5.3.1], part of the basic character set.

graphic-character = %x21-2f ; ! " # $ % & ' ( ) * + , - . /
                  / %x3a-3f ; : ; < = > ?
                  / %x40    ; @
                  / %x5b-5f ; [ \ ] ^ _
                  / %x60    ; `
                  / %x7b-7e ; { | } ~

; The extended characters [C23:5.3.1]; see characters.abnf.

extended-character = line-feed
                   / carriage-return
                   / safe-nonascii

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Rules that exclude certain characters, used by other rules in the grammar.

extended-character-not-new-line = safe-nonascii

graphic-character-not-star = %x21-29 ; ! " # $ % & ' ( )
                           / %x2b-2f ; + , - . /
                           / %x3a-3f ; : ; < = > ?
                           / %x5b-5f ; [ \ ] ^ _
                           / %x7b-7e ; { | } ~

graphic-character-not-greater-than = %x21-2f ; ! " # $ % & ' ( ) * + , - . /
                                   / %x3a-3d ; : ; < =
                                   / %x3f ; ?
                                   / %x5b-5f ; [ \ ] ^ _
                                   / %x7b-7e ; { | } ~

graphic-character-not-double-quote = %x21 ; !
                                   / %x23-2f ; # $ % & ' ( ) * + , - . /
                                   / %x3a-3f ; : ; < = > ?
                                   / %x5b-5f ; [ \ ] ^ _
                                   / %x7b-7e ; { | } ~

graphic-character-not-star-or-slash = %x21-29 ; ! " # $ % & ' ( )
                                    / %x2b-2e ; + , - .
                                    / %x3a-3f ; : ; < = > ?
                                    / %x5b-5f ; [ \ ] ^ _
                                    / %x7b-7e ; { | } ~

graphic-character-not-single-quote-or-backslash = %x21-26 ; ! " # $ % &
                                                / %x28-2f ; ( ) * + , - . /
                                                / %x3a-3f ; : ; < = > ?
                                                / %x5b    ; [
                                                / %x5d-5f ; ] ^ _
                                                / %x7b-7e ; { | } ~

graphic-character-not-double-quote-or-backslash =
      %x21    ; !
    / %x24-2f ; # $ % & ' ( ) * + , - . /
    / %x3a-3f ; : ; < = > ?
    / %x5b    ; [
    / %x5d-5f ; ] ^ _
    / %x7b-7e ; { | } ~
