; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for the source character set
; in the C17 dialects.
; These rules have no counterparts in the grammar in [C17].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; The 29 graphic characters in [C17:5.2.1/3], part of the basic character set.

graphic-character = %x21-23 ; ! " #
                  / %x25-2f ; % & ' ( ) * + , - . /
                  / %x3a-3f ; : ; < = > ?
                  / %x5b-5f ; [ \ ] ^ _
                  / %x7b-7e ; { | } ~

; The extended characters [C17:5.2.1/1]; see characters.abnf.

extended-character = %x24 ; $
                   / %x40 ; @
                   / %x60 ; `
                   / line-feed
                   / carriage-return
                   / safe-nonascii

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Rules that exclude certain characters, used by other rules in the grammar.

extended-character-not-new-line = %x24 ; $
                                / %x40 ; @
                                / %x60 ; `
                                / safe-nonascii

graphic-character-not-star = %x21-23 ; ! " #
                           / %x25-29 ; % & ' ( )
                           / %x2b-2f ; + , - . /
                           / %x3a-3f ; : ; < = > ?
                           / %x5b-5f ; [ \ ] ^ _
                           / %x7b-7e ; { | } ~

graphic-character-not-greater-than = %x21-23 ; ! " #
                                   / %x25-2f ; % & ' ( ) * + , - . /
                                   / %x3a-3d ; : ; < =
                                   / %x3f ; ?
                                   / %x5b-5f ; [ \ ] ^ _
                                   / %x7b-7e ; { | } ~

graphic-character-not-double-quote = %x21 ; !
                                   / %x23 ; #
                                   / %x25-2f ; % & ' ( ) * + , - . /
                                   / %x3a-3f ; : ; < = > ?
                                   / %x5b-5f ; [ \ ] ^ _
                                   / %x7b-7e ; { | } ~

graphic-character-not-star-or-slash = %x21-23 ; ! " #
                                    / %x25-29 ; % & ' ( )
                                    / %x2b-2e ; + , - .
                                    / %x3a-3f ; : ; < = > ?
                                    / %x5b-5f ; [ \ ] ^ _
                                    / %x7b-7e ; { | } ~

graphic-character-not-single-quote-or-backslash = %x21-23 ; ! " #
                                                / %x25-26 ; % &
                                                / %x28-2f ; ( ) * + , - . /
                                                / %x3a-3f ; : ; < = > ?
                                                / %x5b    ; [
                                                / %x5d-5f ; ] ^ _
                                                / %x7b-7e ; { | } ~

graphic-character-not-double-quote-or-backslash =
      %x21    ; !
    / %x23    ; #
    / %x25-2f ; % & ' ( ) * + , - . /
    / %x3a-3f ; : ; < = > ?
    / %x5b    ; [
    / %x5d-5f ; ] ^ _
    / %x7b-7e ; { | } ~
