; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for comments [C17:6.4.9] [C23:6.4.9].
; These rules have no counterparts in the grammars in [C17] and [C23].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Although [C17:6.4.9/2] and [C23:6.4.9] say that
; the ending new line is not part of the line comment,
; grammatically it is convenient to make it part of the comment,
; so we can enforce that the line comment ends with new line.

comment = block-comment
        / line-comment

block-comment = "/*" rest-of-block-comment

rest-of-block-comment = "*" rest-of-block-comment-after-star
                      / character-not-star rest-of-block-comment

rest-of-block-comment-after-star =
      "/"
    / "*" rest-of-block-comment-after-star
    / character-not-star-or-slash rest-of-block-comment

line-comment = "//" *character-not-new-line new-line
