; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for expressions in all the C dialects
; [C17:6.5] [C23:6.5].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; The standard primary expressions are the same in the C17 and C23 standards
; [C17:6.5.1/1] and [C23:6.5.2].
; As explained in :DOC GRAMMAR,
; instead of a single string literal,
; we allow a juxtaposition of one or more string literals.

primary-expression-std = identifier
                       / constant
                       / 1*string-literal
                       / "(" expression ")"
                       / generic-selection

generic-selection =
    %s"_Generic" "(" assignment-expression "," generic-assoc-list ")"

generic-assoc-list = generic-association
                   / generic-assoc-list "," generic-association

generic-association = type-name ":" assignment-expression
                    / %s"default" ":" assignment-expression

; TODO: add other kinds of expressions
