; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains a grammar rule for floating constants
; in the C23 dialect with GCC extensions
; [C23:6.4.5.3].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; GCC adds floating suffixes for
; the additional floating types of size 16, 32, 64, and 128
; (https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html).

floating-suffix = %i"f"
                / %i"l"
                / %s"df" / %s"DF"
                / %s"dd" / %s"DD"
                / %s"dl" / %s"DL"
                / %i"f" ( "16" / "32" / "64" / "128" ) %s"x"
