; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for identifiers in the C17 dialects
; [C17:6.4.2.1].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; For now we omit universal character names in identifiers.
; These have requirements specified in [C17:D].
; We could add them in the future if needed.

; For now we omit other implementation-defined characters from identifiers.
; We could add them in the future if needed.

identifier = identifier-nondigit
           / identifier identifier-nondigit
           / identifier digit

identifier-nondigit = nondigit
                    ; omit universal-character-name
                    ; omit other implementation-defined character

; The above rule for 'identifier'
; is equivalent to the one in identifiers-c23.abnf,
; but it has a different formulation.
