; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains a grammar rule for lists of identifiers
; [C17:6.7.6/1] [C23:6.10.1].
; In [C17] it is with the rules for declarators,
; while in [C23] it is with the rules for preprocessing directives;
; but the rule is the same in both cases, so we factor it here.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

identifier-list = identifier
                / identifier-list "," identifier
