; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for keywords
; that form subsets for the various C dialects.
; Together with the rules in the dialect-specific files keywords-*.abnf,
; they define the keywords of each C dialect.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Keywords in the Clang, but not GCC, dialects.

keyword-clang = %s"__datasizeof"
              / %s"_ExtInt"
              / %s"__imag"
              / %s"__real"
              / %s"__complex"
              / %s"__complex__"
              / %s"__const"
              / %s"__const__"
              / %s"__nullptr"
              / %s"__typeof_unqual"
              / %s"__typeof_unqual__"
              / %s"_Nonnull"
              / %s"_Null_unspecified"
              / %s"_Nullable"
              / %s"_Nullable_result"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Keywords in the CHERI dialects.

keyword-cheri = %s"__capability"
              / %s"__intcap_t"
              / %s"__uintcap_t"
