; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains a grammar rule for keywords in the GCC dialects.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; The GCC documentation does not seem to have
; a clear list of all their additional keywords in the style of [C17] and [C23].
; The list is inferred from the documentation,
; but the lists may be incomplete, and it will be extended as needed.

keyword-gcc = %s"__float80"
            / %s"__float128"
            / %s"_Float16"
            / %s"_Float16x"
            / %s"_Float32"
            / %s"_Float32x"
            / %s"_Float64"
            / %s"_Float64x"
            / %s"_Float128"
            / %s"_Float128x"
