; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for simple escape sequences
; in the C dialects with extensions (i.e. not standard)
; [C17:6.4.4.4/1] [C23:6.4.5.5].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; The only difference with the rule in simple-escapes-std.abnf is
; the addition of the '\%' escape sequence.
; Although we did not find it in the GCC or Clang or CHERI documentation,
; we encountered it in practical code, and we found this web page:
; https://stackoverflow.com/questions/34142682/what-is-the-backslash-percent-escape-in-c.
; For simplicity, for now we allow it
; on all the dialects with GCC or Clang extensions,
; even though perhaps it is an orthogonal extension.
; We will revisit this choice if needed

simple-escape-sequence = "\'"
                       / "\" double-quote
                       / "\?"
                       / "\\"
                       / %s"\a"
                       / %s"\b"
                       / %s"\f"
                       / %s"\n"
                       / %s"\r"
                       / %s"\t"
                       / %s"\v"
                       / "\%"
