; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for universal character names
; [C17:6.4.3] [C23:6.4.4].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

universal-character-name = %s"\u" hex-quad
                         / %s"\U" hex-quad hex-quad

hex-quad =
  hexadecimal-digit hexadecimal-digit hexadecimal-digit hexadecimal-digit

; The rule for 'hexadecimal-digit' is part of the ones for constants,
; as in [C17] and [C23].
