; C Library
;
; Copyright (C) 2026 Kestrel Institute (http://www.kestrel.edu)
;
; License: A 3-clause BSD license. See the LICENSE file distributed with ACL2.
;
; Author: Alessandro Coglio (www.alessandrocoglio.info)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; See [books]/kestrel/c/syntax/grammar.lisp for background.

; This file contains grammar rules for white space,
; which are common to all the C dialects.
; Although [C17:6.4/3] and [C23:6.4.1] include comments under white space,
; here we mean 'white space characters' as defined there,
; which exclude comments, for which we have separate rules.
; Our rules for white space
; have no counterpart in the grammars in [C17] and [C23].

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

white-space = space
            / horizontal-tab
            / vertical-tab
            / form-feed
            / new-line
