# The following variable should represent the ACL2 source directory.  It is the
# only variable in this Makefile that may need to be edited.
ACL2_SRC = ../../../../..

DIRS = symbol-fns lists syntax bags
include $(ACL2_SRC)/books/Makefile-subdirs
