# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../Makefile-generic

ACL2 = ../../../../../saved_acl2

# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

bad-def.cert: bad-def.lisp

bad-def1.cert: bad-def1.lisp

defpr.cert: defpr.lisp

fix.cert: fix.lisp

primitive.cert: primitive.lisp

tail.cert: tail.lisp
