(TAR-LEN-DECODE-HELPER
     (6 1
        (:REWRITE STR::CHARACTER-LISTP-WHEN-HEX-DIGIT-LISTP))
     (4 1
        (:REWRITE STR::CHARACTER-LISTP-WHEN-DIGIT-LISTP))
     (2 2
        (:REWRITE STR::HEX-DIGIT-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1
        (:REWRITE STR::HEX-DIGIT-LISTP-WHEN-NOT-CONSP))
     (1 1
        (:REWRITE STR::DIGIT-LISTP-WHEN-NOT-CONSP))
     (1 1 (:REWRITE DEFAULT-CAR)))
(TAR-LEN-DECODE
   (12 2
       (:REWRITE STR::CHARACTER-LISTP-WHEN-DIGIT-LISTP))
   (12 1 (:DEFINITION REVAPPEND))
   (7 1
      (:REWRITE STR::CHARACTER-LISTP-WHEN-HEX-DIGIT-LISTP))
   (6 2
      (:REWRITE STR::DIGIT-LISTP-WHEN-NOT-CONSP))
   (5 1
      (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
   (5 1
      (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
   (4 4 (:TYPE-PRESCRIPTION STR::DIGIT-LISTP))
   (4 3 (:REWRITE STR::CONSP-OF-EXPLODE))
   (4 1 (:REWRITE DEFAULT-CDR))
   (4 1 (:REWRITE DEFAULT-CAR))
   (2 2 (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
   (2 2
      (:TYPE-PRESCRIPTION STR::HEX-DIGIT-LISTP))
   (2 2 (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
   (2 2
      (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
   (2 2
      (:REWRITE STR::HEX-DIGIT-LISTP-WHEN-SUBSETP-EQUAL))
   (2 2
      (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
   (2 1
      (:TYPE-PRESCRIPTION TRUE-LISTP-REVAPPEND-TYPE-PRESCRIPTION))
   (2 1
      (:REWRITE STR::HEX-DIGIT-LISTP-WHEN-NOT-CONSP))
   (1 1 (:TYPE-PRESCRIPTION REVAPPEND))
   (1 1
      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP)))
(TAR-NAME-DECODE
 (35 7
     (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
 (27 1 (:REWRITE NTH-WHEN->=-N-LEN-L))
 (24 6 (:REWRITE DEFAULT-CDR))
 (16 10 (:REWRITE DEFAULT-+-2))
 (14 14
     (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
 (14 14
     (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
 (10 10 (:REWRITE DEFAULT-+-1))
 (6 6
    (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (6
  6
  (:REWRITE
   CDR-OF-FAT32-FILENAME-LIST-FIX-X-NORMALIZE-CONST-UNDER-FAT32-FILENAME-LIST-EQUIV))
 (6 5 (:REWRITE DEFAULT-<-2))
 (5 5 (:REWRITE DEFAULT-<-1))
 (5 1
    (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
 (2 2 (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
 (2 2
    (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
 (1 1 (:TYPE-PRESCRIPTION TAR-NAME-DECODE))
 (1 1 (:REWRITE NTH-WHEN-PREFIXP)))
(PROCESS-DIR-FILE
  (348 116
       (:TYPE-PRESCRIPTION ASSOC-WHEN-ZP-LEN))
  (116 116 (:TYPE-PRESCRIPTION ZP))
  (116 116 (:TYPE-PRESCRIPTION LEN))
  (18 2
      (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
  (15 1 (:REWRITE PRINC$-OF-PRINC$))
  (12 4
      (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
  (10 2
      (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
  (4 4 (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
  (4 4 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
  (4 4 (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
  (4 4
     (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
  (2 2 (:REWRITE SUBSETP-MEMBER . 2))
  (2 2 (:REWRITE SUBSETP-MEMBER . 1))
  (2 2
     (:REWRITE FAT32-FILENAME-LIST-P-WHEN-SUBSETP-EQUAL))
  (1 1
     (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
  (1 1
     (:REWRITE FAT32-FILENAME-LIST-P-WHEN-NOT-CONSP)))
(PROCESS-REG-FILE
  (384 128
       (:TYPE-PRESCRIPTION ASSOC-WHEN-ZP-LEN))
  (128 128 (:TYPE-PRESCRIPTION ZP))
  (128 128 (:TYPE-PRESCRIPTION LEN))
  (27 3
      (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
  (20 10 (:REWRITE DEFAULT-<-1))
  (19 4 (:REWRITE PRINC$-OF-PRINC$))
  (18 6
      (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
  (15 3
      (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
  (11 11
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
  (10 10 (:REWRITE DEFAULT-<-2))
  (6 6 (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
  (6 6 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
  (6 6 (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
  (6 6
     (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
  (3 3 (:REWRITE SUBSETP-MEMBER . 2))
  (3 3 (:REWRITE SUBSETP-MEMBER . 1))
  (2 2
     (:REWRITE FILE-TABLE-P-WHEN-SUBSETP-EQUAL))
  (2 2
     (:REWRITE FD-TABLE-P-WHEN-SUBSETP-EQUAL))
  (2 2
     (:REWRITE FAT32-FILENAME-LIST-P-WHEN-SUBSETP-EQUAL))
  (1 1
     (:REWRITE FILE-TABLE-P-WHEN-NOT-CONSP))
  (1 1 (:REWRITE FD-TABLE-P-WHEN-NOT-CONSP))
  (1 1
     (:REWRITE FAT32-FILENAME-LIST-P-WHEN-NOT-CONSP)))
(FD-TABLE-P-OF-PROCESS-REG-FILE
 (381 127
      (:TYPE-PRESCRIPTION ASSOC-WHEN-ZP-LEN))
 (64 20 (:REWRITE PRINC$-OF-PRINC$))
 (64 9 (:DEFINITION ASSOC-EQUAL))
 (52 4 (:DEFINITION REMOVE-ASSOC-EQUAL))
 (39 39 (:REWRITE DEFAULT-CAR))
 (36 12
     (:REWRITE REMOVE-ASSOC-WHEN-ABSENT-1))
 (33 22 (:REWRITE DEFAULT-CDR))
 (20 4
     (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
 (20 4
     (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
 (17 17
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (12 12 (:TYPE-PRESCRIPTION NULL))
 (12 12 (:DEFINITION NULL))
 (8 8 (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
 (8 8 (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
 (8 8
    (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
 (8 8
    (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
 (8 4 (:REWRITE DEFAULT-<-1))
 (7 7
    (:REWRITE HIFAT-SUBSETP-PRESERVES-ASSOC-EQUAL))
 (7 7
    (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-3-LEMMA-8))
 (4 4
    (:TYPE-PRESCRIPTION INTEGERP-OF-LOFAT-PWRITE))
 (4 4
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (4 4 (:REWRITE DEFAULT-<-2))
 (2 2
    (:REWRITE FD-TABLE-P-WHEN-SUBSETP-EQUAL))
 (1 1 (:REWRITE FD-TABLE-P-WHEN-NOT-CONSP)))
(FILE-TABLE-P-OF-PROCESS-REG-FILE
 (381 127
      (:TYPE-PRESCRIPTION ASSOC-WHEN-ZP-LEN))
 (64 20 (:REWRITE PRINC$-OF-PRINC$))
 (64 9 (:DEFINITION ASSOC-EQUAL))
 (52 4 (:DEFINITION REMOVE-ASSOC-EQUAL))
 (39 39 (:REWRITE DEFAULT-CAR))
 (36 12
     (:REWRITE REMOVE-ASSOC-WHEN-ABSENT-1))
 (33 22 (:REWRITE DEFAULT-CDR))
 (20 4
     (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
 (20 4
     (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
 (17 17
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (12 12 (:TYPE-PRESCRIPTION NULL))
 (12 12 (:DEFINITION NULL))
 (8 8 (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
 (8 8 (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
 (8 8
    (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
 (8 8
    (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
 (8 4 (:REWRITE DEFAULT-<-1))
 (7 7
    (:REWRITE HIFAT-SUBSETP-PRESERVES-ASSOC-EQUAL))
 (7 7
    (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-3-LEMMA-8))
 (4 4
    (:TYPE-PRESCRIPTION INTEGERP-OF-LOFAT-PWRITE))
 (4 4
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (4 4 (:REWRITE DEFAULT-<-2))
 (2 2
    (:REWRITE FILE-TABLE-P-WHEN-SUBSETP-EQUAL))
 (1 1
    (:REWRITE FILE-TABLE-P-WHEN-NOT-CONSP)))
(LOFAT-FS-P-OF-PROCESS-REG-FILE
 (3678 1226
       (:TYPE-PRESCRIPTION ASSOC-WHEN-ZP-LEN))
 (2416 19 (:LINEAR GETOPT::DEFOPTIONS-LEMMA-8))
 (2378 19 (:DEFINITION STR::STRPREFIXP$INLINE))
 (2182 42
       (:REWRITE HIFAT-TO-LOFAT-INVERSION-LEMMA-2))
 (1752 282 (:DEFINITION ASSOC-EQUAL))
 (1519 19 (:REWRITE PREFIXP-OF-CONS-LEFT))
 (1367 38
       (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
 (1127 685 (:REWRITE DEFAULT-CDR))
 (1122 985 (:REWRITE DEFAULT-CAR))
 (916 72 (:DEFINITION LEN))
 (627 158 (:REWRITE STR::CONSP-OF-EXPLODE))
 (520 40 (:DEFINITION REMOVE-ASSOC-EQUAL))
 (484 484
      (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
 (450 90
      (:REWRITE M1-DIRECTORY-FILE-P-CORRECTNESS-1))
 (450 90
      (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
 (412 92
      (:REWRITE LOFAT-TO-HIFAT-CORRECTNESS-2))
 (408 128 (:REWRITE PRINC$-OF-PRINC$))
 (370
     370
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (360 120
      (:REWRITE REMOVE-ASSOC-WHEN-ABSENT-1))
 (302 302
      (:TYPE-PRESCRIPTION HIFAT-BOUNDED-FILE-ALIST-P))
 (245 49
      (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
 (213 53
      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (198 47
      (:LINEAR LEN-WHEN-HIFAT-BOUNDED-FILE-ALIST-P
               . 2))
 (198 47
      (:LINEAR LEN-WHEN-HIFAT-BOUNDED-FILE-ALIST-P
               . 1))
 (191 38
      (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
 (180 180
      (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
 (180 180
      (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
 (180 60
      (:REWRITE M1-DIRECTORY-FILE-P-WHEN-M1-FILE-P))
 (153 75 (:REWRITE DEFAULT-+-2))
 (120 120 (:TYPE-PRESCRIPTION NULL))
 (120 120
      (:TYPE-PRESCRIPTION M1-DIRECTORY-FILE-P))
 (120 120
      (:REWRITE M1-REGULAR-FILE-P-CORRECTNESS-1))
 (120 120 (:DEFINITION NULL))
 (116 58 (:REWRITE DEFAULT-<-1))
 (114 38
      (:REWRITE HIFAT-BOUNDED-FILE-ALIST-P-OF-CDR))
 (98 98
     (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
 (98 98
     (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
 (94 94
     (:LINEAR NON-FREE-INDEX-LISTP-CORRECTNESS-6-LEMMA-3))
 (94 94
     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (94 94
     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (94 94 (:LINEAR LEN-WHEN-PREFIXP))
 (84
  84
  (:REWRITE
   FILE-TABLE-ELEMENT->FID$INLINE-OF-FILE-TABLE-ELEMENT-FIX-X-NORMALIZE-CONST))
 (75 75 (:REWRITE DEFAULT-+-1))
 (72
  72
  (:REWRITE
   CDR-OF-FAT32-FILENAME-LIST-FIX-X-NORMALIZE-CONST-UNDER-FAT32-FILENAME-LIST-EQUIV))
 (64
   64
   (:REWRITE
        GET-CLUSTERCHAIN-CONTENTS-OF-UPDATE-DIR-CONTENTS-COINCIDENT-LEMMA-5))
 (64 58 (:REWRITE DEFAULT-<-2))
 (60 60 (:TYPE-PRESCRIPTION M1-FILE-P))
 (60 60
     (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-3-LEMMA-2))
 (60 60
     (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-1))
 (57 19
     (:LINEAR LEN-WHEN-HIFAT-BOUNDED-FILE-ALIST-P
              . 3))
 (55 55
     (:REWRITE HIFAT-SUBSETP-PRESERVES-ASSOC-EQUAL))
 (55 55
     (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-3-LEMMA-8))
 (47 47 (:LINEAR POSITION-WHEN-MEMBER))
 (47 47
     (:LINEAR POSITION-EQUAL-AC-WHEN-MEMBER))
 (47
    47
    (:LINEAR
         DIR-ENT-CLUSTERCHAIN-CONTENTS-OF-LOFAT-PLACE-FILE-COINCIDENT-LEMMA-4
         . 1))
 (47
  47
  (:LINEAR
      DIR-ENT-CLUSTERCHAIN-CONTENTS-OF-LOFAT-PLACE-FILE-COINCIDENT-LEMMA-10))
 (42 42
     (:REWRITE M1-FILE->CONTENTS$INLINE-OF-M1-FILE-FIX-X-NORMALIZE-CONST))
 (42 42
     (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-3))
 (42 3 (:REWRITE ZP-OPEN))
 (38 38 (:REWRITE PREFIXP-TRANSITIVE . 2))
 (38 38 (:REWRITE PREFIXP-TRANSITIVE . 1))
 (38 38
     (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
 (38 38
     (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
 (33 33
     (:REWRITE M1-FILE-OF-M1-FILE-CONTENTS-FIX-CONTENTS-NORMALIZE-CONST))
 (33 33
     (:REWRITE M1-FILE-OF-DIR-ENT-FIX-DIR-ENT-NORMALIZE-CONST))
 (28 28
     (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (19 19
     (:TYPE-PRESCRIPTION STR::STRPREFIXP$INLINE))
 (19 19
     (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
 (12 12
     (:REWRITE M1-FILE->DIR-ENT$INLINE-OF-M1-FILE-FIX-X-NORMALIZE-CONST)))
(LOFAT-FS-P-OF-PROCESS-DIR-FILE
 (164 29
      (:REWRITE LOFAT-TO-HIFAT-CORRECTNESS-2))
 (28 2 (:REWRITE ZP-OPEN))
 (27
   27
   (:REWRITE
        GET-CLUSTERCHAIN-CONTENTS-OF-UPDATE-DIR-CONTENTS-COINCIDENT-LEMMA-5))
 (25 5
     (:REWRITE M1-DIRECTORY-FILE-P-WHEN-M1-FILE-P))
 (20 20
     (:TYPE-PRESCRIPTION M1-REGULAR-FILE-P))
 (18 18 (:REWRITE PRINC$-OF-PRINC$))
 (15 5
     (:REWRITE M1-REGULAR-FILE-P-CORRECTNESS-1))
 (8 4 (:REWRITE DEFAULT-<-2))
 (5 5 (:TYPE-PRESCRIPTION M1-FILE-P))
 (5 5
    (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-3-LEMMA-2))
 (5 5
    (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-1))
 (4 4 (:REWRITE DEFAULT-<-1))
 (4 2
    (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (2 2 (:TYPE-PRESCRIPTION ZP)))
(PROCESS-BLOCK-SEQUENCE
 (12144 92 (:LINEAR GETOPT::DEFOPTIONS-LEMMA-8))
 (11960 92 (:DEFINITION STR::STRPREFIXP$INLINE))
 (11112 3704
        (:TYPE-PRESCRIPTION ASSOC-WHEN-ZP-LEN))
 (10207 63 (:REWRITE NTH-WHEN->=-N-LEN-L))
 (7396 92 (:REWRITE PREFIXP-OF-CONS-LEFT))
 (6604 563 (:DEFINITION LEN))
 (5449 1194 (:REWRITE STR::CONSP-OF-EXPLODE))
 (3805 385
       (:REWRITE FAT32-FILENAME-P-CORRECTNESS-1))
 (3704 3704 (:TYPE-PRESCRIPTION ZP))
 (2878 875 (:REWRITE DEFAULT-CDR))
 (2716
      704
      (:REWRITE FAT32-FILENAME-P-WHEN-MEMBER-EQUAL-OF-FAT32-FILENAME-LIST-P))
 (2342 146 (:DEFINITION BINARY-APPEND))
 (1952 1952
       (:TYPE-PRESCRIPTION HIFAT-BOUNDED-FILE-ALIST-P))
 (1646 544
       (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (1445 722 (:REWRITE DEFAULT-+-2))
 (1396 246
       (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
 (1326 350
       (:LINEAR LEN-WHEN-HIFAT-BOUNDED-FILE-ALIST-P
                . 2))
 (1326 350
       (:LINEAR LEN-WHEN-HIFAT-BOUNDED-FILE-ALIST-P
                . 1))
 (1124 346 (:REWRITE DEFAULT-CAR))
 (1080 10 (:REWRITE SUBSETP-APPEND1))
 (1006 1006 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
 (732 722 (:REWRITE DEFAULT-+-1))
 (704 704
      (:TYPE-PRESCRIPTION FAT32-FILENAME-P))
 (700 700
      (:LINEAR NON-FREE-INDEX-LISTP-CORRECTNESS-6-LEMMA-3))
 (700 700
      (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (700 700
      (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (700 700 (:LINEAR LEN-WHEN-PREFIXP))
 (639 63
      (:REWRITE STR::CHARACTER-LISTP-WHEN-HEX-DIGIT-LISTP))
 (563
  563
  (:REWRITE
   CDR-OF-FAT32-FILENAME-LIST-FIX-X-NORMALIZE-CONST-UNDER-FAT32-FILENAME-LIST-EQUIV))
 (552 184
      (:REWRITE HIFAT-BOUNDED-FILE-ALIST-P-OF-CDR))
 (503 503 (:REWRITE SUBSETP-MEMBER . 2))
 (503 503 (:REWRITE SUBSETP-MEMBER . 1))
 (473 257 (:REWRITE DEFAULT-<-1))
 (412 63
      (:REWRITE STR::CHARACTER-LISTP-WHEN-DIGIT-LISTP))
 (365 365 (:REWRITE PREFIXP-TRANSITIVE . 2))
 (365 365 (:REWRITE PREFIXP-TRANSITIVE . 1))
 (365 365
      (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
 (365 365
      (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
 (350 350 (:LINEAR POSITION-WHEN-MEMBER))
 (350 350
      (:LINEAR POSITION-EQUAL-AC-WHEN-MEMBER))
 (350
    350
    (:LINEAR
         DIR-ENT-CLUSTERCHAIN-CONTENTS-OF-LOFAT-PLACE-FILE-COINCIDENT-LEMMA-4
         . 1))
 (350
  350
  (:LINEAR
      DIR-ENT-CLUSTERCHAIN-CONTENTS-OF-LOFAT-PLACE-FILE-COINCIDENT-LEMMA-10))
 (329 257 (:REWRITE DEFAULT-<-2))
 (320 64 (:LINEAR NTH-WHEN-DIR-ENT-P))
 (294 154
      (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
 (276 92
      (:LINEAR LEN-WHEN-HIFAT-BOUNDED-FILE-ALIST-P
               . 3))
 (266 79
      (:REWRITE STR::HEX-DIGIT-LISTP-WHEN-NOT-CONSP))
 (222 111 (:REWRITE DEFAULT-*-2))
 (217 65
      (:REWRITE STR::DIGIT-LISTP-WHEN-NOT-CONSP))
 (208 48
      (:REWRITE STRINGP-WHEN-NONEMPTY-STRINGP))
 (182 10 (:REWRITE LEN-OF-APPEND))
 (180 20 (:LINEAR PAINFUL-DEBUGGING-LEMMA-20))
 (175 103
      (:REWRITE FAT32-FILENAME-LIST-P-WHEN-NOT-CONSP))
 (164 162
      (:REWRITE STR::HEX-DIGIT-LISTP-WHEN-SUBSETP-EQUAL))
 (149 72
      (:REWRITE STR::HEX-DIGIT-LISTP-OF-CONS))
 (136 62 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (128 128 (:TYPE-PRESCRIPTION DIR-ENT-P))
 (128 128
      (:REWRITE DIR-ENT-P-WHEN-MEMBER-EQUAL-OF-DIR-ENT-LIST-P))
 (128 18 (:DEFINITION ASSOC-EQUAL))
 (111 111 (:REWRITE DEFAULT-*-1))
 (104 8 (:DEFINITION REMOVE-ASSOC-EQUAL))
 (92 92
     (:TYPE-PRESCRIPTION STR::STRPREFIXP$INLINE))
 (88 62 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (80 80
     (:TYPE-PRESCRIPTION NONEMPTY-STRINGP))
 (80 80
     (:REWRITE NONEMPTY-STRINGP-WHEN-MEMBER-EQUAL-OF-NONEMPTY-STRING-LISTP))
 (72 72
     (:TYPE-PRESCRIPTION STR::HEX-DIGIT-LISTP))
 (72 72
     (:TYPE-PRESCRIPTION STR::DIGIT-LISTP))
 (72 24
     (:REWRITE REMOVE-ASSOC-WHEN-ABSENT-1))
 (63 63 (:REWRITE NTH-WHEN-PREFIXP))
 (62 62 (:REWRITE SUBSETP-TRANS2))
 (62 62 (:REWRITE SUBSETP-TRANS))
 (58 58 (:REWRITE STR::DIGIT-LISTP-OF-CONS))
 (48 48
     (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
 (38 38
     (:REWRITE FILE-TABLE-P-WHEN-NOT-CONSP))
 (38 38 (:REWRITE FD-TABLE-P-WHEN-NOT-CONSP))
 (34 34
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (26 2
     (:REWRITE STR::HEX-DIGIT-LISTP-OF-APPEND))
 (24 24 (:TYPE-PRESCRIPTION NULL))
 (22 8 (:REWRITE CONSP-OF-APPEND))
 (16 2 (:REWRITE STR::DIGIT-LISTP-OF-APPEND))
 (14 14
     (:REWRITE HIFAT-SUBSETP-PRESERVES-ASSOC-EQUAL))
 (14 14
     (:REWRITE HIFAT-FIND-FILE-CORRECTNESS-3-LEMMA-8))
 (10 10
     (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (8 8
    (:TYPE-PRESCRIPTION INTEGERP-OF-LOFAT-PWRITE))
 (7 2 (:REWRITE DEFAULT-UNARY-MINUS))
 (2 2 (:REWRITE FOLD-CONSTS-IN-+))
 (1 1
    (:LINEAR POSITION-WHEN-MEMBER-OF-TAKE))
 (1 1 (:LINEAR LISTPOS-COMPLETE)))
