include ../../../Makefile-generic

ACL2 = ../../../../saved_acl2

# Dependencies:

crt.cert: crt.lisp
crt.cert: ../../../rtl/rel1/lib1/basic.cert
crt.cert: ../../../rtl/rel1/support/fp.cert

summary.cert: summary.lisp
summary.cert: crt.cert
