(TRUE-LISTP-WHEN-ARGLISTP
 (12 12 (:REWRITE DEFAULT-CDR))
 (10 10 (:REWRITE DEFAULT-CAR))
 (9 3 (:DEFINITION MEMBER-EQUAL))
 (4 4 (:REWRITE LEGAL-VARIABLE-OR-CONSTANT-NAMEP-IMPLIES-SYMBOLP))
 (4 2 (:DEFINITION TRUE-LISTP))
 )
