(VL::VL-SCARY-TRANSLATE-COMMENT-P)
(VL::VL-COMMENTMAP-TRANSLATE-OFF-WARNINGS
 (92 2 (:DEFINITION MEMBER-EQUAL))
 (59 4
     (:REWRITE VL::VL-WARNING-P-WHEN-MEMBER-EQUAL-OF-VL-WARNINGLIST-P))
 (56 2 (:REWRITE VL::EQUAL-OF-VL-WARNING))
 (55 1 (:REWRITE SUBSETP-OF-CONS))
 (32 19
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
               . 1))
 (26 26 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
 (19 19
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
               . 2))
 (16 4
     (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
 (15 6
     (:REWRITE VL::VL-COMMENTMAP-P-WHEN-NOT-CONSP))
 (14 11 (:REWRITE DEFAULT-CDR))
 (11 11 (:REWRITE SUBSETP-TRANS2))
 (11 11 (:REWRITE SUBSETP-TRANS))
 (10 8 (:REWRITE DEFAULT-CAR))
 (10 2 (:REWRITE SUBSETP-CAR-MEMBER))
 (8 4 (:REWRITE DEFAULT-+-2))
 (7 1 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (6 6
    (:TYPE-PRESCRIPTION VL::TRUE-LISTP-OF-VL-WARNING->ARGS))
 (6 6
    (:TYPE-PRESCRIPTION VL::SYMBOLP-OF-VL-WARNING->TYPE))
 (6 6
    (:TYPE-PRESCRIPTION VL::SYMBOLP-OF-VL-WARNING->FN))
 (6 6
    (:TYPE-PRESCRIPTION VL::STRINGP-OF-VL-WARNING->MSG))
 (6 6
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-WARNING->SUPPRESSEDP))
 (6 6
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-WARNING->FATALP))
 (4 4 (:REWRITE SUBSETP-MEMBER . 2))
 (4 4 (:REWRITE SUBSETP-MEMBER . 1))
 (4 4 (:REWRITE DEFAULT-+-1))
 (4 1 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (3 3
    (:REWRITE-QUOTED-CONSTANT SYMBOL-FIX-UNDER-SYMBOL-EQUIV))
 (2 2
    (:REWRITE-QUOTED-CONSTANT VL::MAYBE-STRING-FIX-UNDER-MAYBE-STRING-EQUIV))
 (2 2
    (:REWRITE VL::VL-WARNING-OF-SYMBOL-FIX-TYPE-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-WARNING-OF-SYMBOL-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-WARNING-OF-STR-FIX-MSG-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-WARNING-OF-LIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-WARNING-OF-BOOL-FIX-SUPPRESSEDP-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-WARNING-OF-BOOL-FIX-FATALP-NORMALIZE-CONST))
 (2
  2
  (:REWRITE VL::VL-WARNING->TYPE$INLINE-OF-VL-WARNING-FIX-X-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     VL::VL-WARNING->SUPPRESSEDP$INLINE-OF-VL-WARNING-FIX-X-NORMALIZE-CONST))
 (2
   2
   (:REWRITE VL::VL-WARNING->MSG$INLINE-OF-VL-WARNING-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-WARNING->FN$INLINE-OF-VL-WARNING-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         VL::VL-WARNING->FATALP$INLINE-OF-VL-WARNING-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         VL::VL-WARNING->CONTEXT$INLINE-OF-VL-WARNING-FIX-X-NORMALIZE-CONST))
 (2
  2
  (:REWRITE VL::VL-WARNING->ARGS$INLINE-OF-VL-WARNING-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE LIST-FIX-WHEN-TRUE-LISTP))
 (2 1 (:REWRITE DEFAULT-<-2))
 (2 1 (:REWRITE DEFAULT-<-1))
 (1 1
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV)))
(VL::VL-WARNINGLIST-P-OF-VL-COMMENTMAP-TRANSLATE-OFF-WARNINGS
 (206 31
      (:REWRITE VL::VL-COMMENTMAP-FIX-WHEN-VL-COMMENTMAP-P))
 (92 9
     (:REWRITE VL::VL-WARNINGLIST-FIX-WHEN-VL-WARNINGLIST-P))
 (75 75
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
               . 2))
 (75 75
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
               . 1))
 (75 25
     (:REWRITE VL::VL-COMMENTMAP-P-WHEN-NOT-CONSP))
 (72 24
     (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
 (52 19 (:REWRITE DEFAULT-CDR))
 (50 50
     (:REWRITE VL::VL-COMMENTMAP-P-WHEN-SUBSETP-EQUAL))
 (48 16
     (:REWRITE VL::CONSP-OF-CAR-WHEN-VL-COMMENTMAP-P))
 (34 19 (:REWRITE DEFAULT-CAR))
 (24 8 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (24 8 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (16 16
     (:REWRITE VL::VL-COMMENTMAP-P-OF-VL-COMMENTMAP-FIX))
 (10 10 (:REWRITE SUBSETP-TRANS2))
 (10 10 (:REWRITE SUBSETP-TRANS))
 (7 7
    (:REWRITE-QUOTED-CONSTANT SYMBOL-FIX-UNDER-SYMBOL-EQUIV))
 (4 4
    (:REWRITE-QUOTED-CONSTANT VL::MAYBE-STRING-FIX-UNDER-MAYBE-STRING-EQUIV))
 (4 4
    (:REWRITE VL::VL-WARNING-OF-SYMBOL-FIX-TYPE-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-WARNING-OF-SYMBOL-FIX-FN-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-WARNING-OF-STR-FIX-MSG-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-WARNING-OF-LIST-FIX-ARGS-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-WARNING-OF-BOOL-FIX-SUPPRESSEDP-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-WARNING-OF-BOOL-FIX-FATALP-NORMALIZE-CONST))
 (3 3
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV)))
