## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

include ../../../../../Makefile-generic
-include Makefile-deps

BOOKS = symbol-manip vector-comp-canon list-defthms-help source_shallow \
	      ihs-defthms-help append-defthms-help computed-hints make-theorems

