ACL2_SYSTEM_BOOKS = ../../../..
include $(ACL2_SYSTEM_BOOKS)/Makefile-generic
ACL2 =  ../../../../../saved_acl2

# Dependencies:

example.cert: example.lisp
example.cert: nary.cert
example.cert: nth-rules.cert
# example.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/floor-mod/floor-mod.cert
# example.cert: $(ACL2_SYSTEM_BOOKS)/ihs/ihs-definitions.cert
# example.cert: $(ACL2_SYSTEM_BOOKS)/ihs/ihs-lemmas.cert

nary.cert: nary.lisp

nth-rules.cert: nth-rules.lisp
