
ACL2_SYSTEM_BOOKS = ../../..

DIRS = sat clause-processors sat-tests bv-smt-solver 

include ${ACL2_SYSTEM_BOOKS}/Makefile-psubdirs

bv-smt-solver: sat clause-processors
sat-tests: sat clause-processors
