#!/bin/sh

# Usage: svnc msg [file file ...]
# which should be equivalent to
# svn commit -m msg [file file ...]
# except that file acl2-svn.txt is always updated, with
# a time stamp so that it will always be committed.

rm -f acl2-svn.txt
echo '"$Revision: $"' > acl2-svn.txt
date >> acl2-svn.txt

if [ $# -lt 1 ] ; then \
    echo "Usage: svnc msg [file file ...]" ; \
    exit 1 ; \
elif [ $# -eq 1 ] ; then \
    svn commit -m \'"$1"\'
else \
    export msg="$1"
    shift 1
    svn commit -m \'"$msg"\' $* acl2-svn.txt
fi
