DIRS = y86-basic y86-two-level y86-two-level-abs
# We could include ../../Makefile-psubdirs instead of
# ../../Makefile-subdirs, but some machines cannot handle the memory
# used for that.
include ../../Makefile-subdirs
