include ../Makefile-generic

#  Put dependencies (from `make -s dependencies', or other sources) below.

no-sqrt.cert: no-sqrt.lisp
no-sqrt.cert: ../arithmetic/top.cert

iter-sqrt.cert: iter-sqrt.lisp
iter-sqrt.cert: ../arithmetic/top.cert

