(SV::NETEVAL-WITNESS-P (4 2
                          (:LINEAR ACL2-COUNT-OF-CONSP-POSITIVE)))
(SV::BOOLEANP-OF-SVAR-P-FOR-NETEVAL-WITNESS-P-KEY-LEMMA)
(SV::BOOLEANP-OF-NETEVAL-WITNESS-P-FOR-NETEVAL-WITNESS-P-VAL-LEMMA)
(SV::BOOLEANP-OF-SVAR-P-FOR-NETEVAL-WITNESS-P-KEY)
(SV::BOOLEANP-OF-NETEVAL-WITNESS-P-FOR-NETEVAL-WITNESS-P-VAL)
(SV::NETEVAL-WITNESS-P-OF-REPEAT)
(SV::NETEVAL-WITNESS-P-OF-REV)
(SV::NETEVAL-WITNESS-P-OF-LIST-FIX)
(SV::TRUE-LISTP-WHEN-NETEVAL-WITNESS-P)
(SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)
(SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P)
(SV::NETEVAL-WITNESS-P-OF-CONS)
(SV::NETEVAL-WITNESS-P-OF-REMOVE-ASSOC
     (142 27
          (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (42 42
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-WITNESS-P-OF-PUT-ASSOC)
(SV::NETEVAL-WITNESS-P-OF-HONS-SHRINK-ALIST)
(SV::NETEVAL-WITNESS-P-OF-HONS-ACONS)
(SV::NETEVAL-WITNESS-P-OF-CDR-OF-HONS-ASSOC-EQUAL-WHEN-NETEVAL-WITNESS-P)
(SV::ALISTP-WHEN-NETEVAL-WITNESS-P-REWRITE)
(SV::ALISTP-WHEN-NETEVAL-WITNESS-P)
(SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P)
(SV::SVAR-P-OF-CAAR-WHEN-NETEVAL-WITNESS-P)
(SV::NETEVAL-WITNESS-FIX$INLINE
     (4 2
        (:LINEAR ACL2-COUNT-OF-CONSP-POSITIVE))
     (4 1
        (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-NETEVAL-WITNESS-P))
     (2 2
        (:TYPE-PRESCRIPTION SV::NETEVAL-WITNESS-P))
     (1 1
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-WITNESS-P-OF-NETEVAL-WITNESS-FIX
     (105 15
          (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-NETEVAL-WITNESS-P))
     (80 34
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (67 7 (:DEFINITION SV::NETEVAL-WITNESS-P))
     (36 4
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVEX-ALIST-P))
     (36 4
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVAR-MAP-P))
     (36 4
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVAR-ALIST-P))
     (28 28 (:REWRITE DEFAULT-CAR))
     (26 10
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (24 4
         (:REWRITE SV::SVAR-P-OF-CAR-WHEN-SVARLIST-P))
     (24 4
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVEX-ENV-P))
     (24 4
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVAR-BOOLMASKS-P))
     (12 12
         (:REWRITE SV::SVEX-ALIST-P-WHEN-SUBSETP-EQUAL))
     (12 12
         (:REWRITE SV::SVAR-MAP-P-WHEN-SUBSETP-EQUAL))
     (12 12
         (:REWRITE SV::SVAR-ALIST-P-WHEN-SUBSETP-EQUAL))
     (12 2
         (:REWRITE SV::SVEX-ALIST-P-OF-CDR-WHEN-SVEX-ALIST-P))
     (12 2
         (:REWRITE SV::SVAR-MAP-P-OF-CDR-WHEN-SVAR-MAP-P))
     (12 2
         (:REWRITE SV::SVAR-ALIST-P-OF-CDR-WHEN-SVAR-ALIST-P))
     (10 10 (:REWRITE DEFAULT-CDR))
     (8 8
        (:REWRITE SV::SVARLIST-P-WHEN-SUBSETP-EQUAL))
     (8 8
        (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (8 4
        (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P))
     (8 2
        (:REWRITE SV::SVEX-ENV-P-OF-CDR-WHEN-SVEX-ENV-P))
     (8 2
        (:REWRITE SV::SVAR-BOOLMASKS-P-OF-CDR-WHEN-SVAR-BOOLMASKS-P))
     (6 6
        (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP))
     (6 6
        (:REWRITE SV::SVEX-ALIST-P-WHEN-NOT-CONSP))
     (6 6
        (:REWRITE SV::SVAR-MAP-P-WHEN-NOT-CONSP))
     (6 6
        (:REWRITE SV::SVAR-BOOLMASKS-P-WHEN-NOT-CONSP))
     (6 6
        (:REWRITE SV::SVAR-ALIST-P-WHEN-NOT-CONSP))
     (4 4
        (:REWRITE SV::SVARLIST-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P
     (34 9
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P)))
(SV::NETEVAL-WITNESS-FIX$INLINE
     (12 4
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (10 10
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (6 2
        (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P)))
(FTY::TMP-DEFFIXTYPE-IDEMPOTENT
     (1 1
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-WITNESS-EQUIV$INLINE)
(SV::NETEVAL-WITNESS-EQUIV-IS-AN-EQUIVALENCE)
(SV::NETEVAL-WITNESS-EQUIV-IMPLIES-EQUAL-NETEVAL-WITNESS-FIX-1)
(SV::NETEVAL-WITNESS-FIX-UNDER-NETEVAL-WITNESS-EQUIV)
(SV::EQUAL-OF-NETEVAL-WITNESS-FIX-1-FORWARD-TO-NETEVAL-WITNESS-EQUIV)
(SV::EQUAL-OF-NETEVAL-WITNESS-FIX-2-FORWARD-TO-NETEVAL-WITNESS-EQUIV)
(SV::NETEVAL-WITNESS-EQUIV-OF-NETEVAL-WITNESS-FIX-1-FORWARD)
(SV::NETEVAL-WITNESS-EQUIV-OF-NETEVAL-WITNESS-FIX-2-FORWARD)
(SV::CONS-OF-NETEVAL-WITNESS-FIX-V-UNDER-NETEVAL-WITNESS-EQUIV
     (23 2
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CONS))
     (6 6
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::CONS-NETEVAL-WITNESS-EQUIV-CONGRUENCE-ON-V-UNDER-NETEVAL-WITNESS-EQUIV)
(SV::CONS-OF-NETEVAL-WITNESS-FIX-Y-UNDER-NETEVAL-WITNESS-EQUIV
     (26 2
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CONS))
     (16 4
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (10 10
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::CONS-NETEVAL-WITNESS-EQUIV-CONGRUENCE-ON-Y-UNDER-NETEVAL-WITNESS-EQUIV)
(SV::NETEVAL-WITNESS-FIX-OF-ACONS
     (25 5
         (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (10 1
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CONS))
     (9 9
        (:TYPE-PRESCRIPTION SV::NETEVAL-WITNESS-P))
     (5 5
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::HONS-ASSOC-EQUAL-OF-NETEVAL-WITNESS-FIX
 (656 70
      (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
 (266 69
      (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
 (180 178
      (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
 (88 22
     (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-NETEVAL-WITNESS-P))
 (84 21
     (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P))
 (43
  8
  (:REWRITE
   SV::NETEVAL-WITNESS-P-OF-CDR-OF-HONS-ASSOC-EQUAL-WHEN-NETEVAL-WITNESS-P)))
(SV::NETEVAL-WITNESS-FIX-OF-APPEND
     (163 21
          (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (70 70
         (:TYPE-PRESCRIPTION SV::NETEVAL-WITNESS-P))
     (48 36
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (32 8
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (25 1
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CONS))
     (16 4
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-NETEVAL-WITNESS-P))
     (16 4
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P)))
(SV::CONSP-CAR-OF-NETEVAL-WITNESS-FIX
     (51 10
         (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (27 27
         (:TYPE-PRESCRIPTION SV::NETEVAL-WITNESS-P))
     (16 4
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (14 14
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (8 2
        (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-NETEVAL-WITNESS-P))
     (8 2
        (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P)))
(SV::NETEVAL-WITNESS-COUNT
     (6 6
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::NATP-OF-NETEVAL-WITNESS-COUNT)
(SV::NETEVAL-WITNESS-COUNT
     (9 9
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (4 4 (:REWRITE DEFAULT-CAR)))
(SV::NETEVAL-WITNESS-COUNT-OF-NETEVAL-WITNESS-FIX-X
     (1 1
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-WITNESS-COUNT-NETEVAL-WITNESS-EQUIV-CONGRUENCE-ON-X)
(SV::NETEVAL-WITNESS-COUNT-OF-CONS
     (134 35
          (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (61 61
         (:TYPE-PRESCRIPTION SV::NETEVAL-WITNESS-P))
     (31 31
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (12 3
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (12 1
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CONS)))
(SV::NETEVAL-WITNESS-COUNT-OF-ACONS
     (16 4
         (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (8 8
        (:TYPE-PRESCRIPTION SV::NETEVAL-WITNESS-P))
     (4 4
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-WITNESS-COUNT-OF-CDAR-NETEVAL-WITNESS-COUNT
     (12 4 (:REWRITE DEFAULT-<-2))
     (12 4 (:REWRITE DEFAULT-<-1))
     (12 4 (:REWRITE DEFAULT-+-2))
     (12 4 (:REWRITE DEFAULT-+-1))
     (12 2
         (:REWRITE SV::SVAR-P-OF-CAR-WHEN-SVARLIST-P))
     (12 2
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVEX-ALIST-P))
     (12 2
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVAR-MAP-P))
     (12 2
         (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVAR-ALIST-P))
     (10 10
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (10 10 (:REWRITE DEFAULT-CAR))
     (8 2
        (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVEX-ENV-P))
     (8 2
        (:REWRITE SV::SVAR-P-OF-CAAR-WHEN-SVAR-BOOLMASKS-P))
     (4 4
        (:REWRITE SV::SVEX-ALIST-P-WHEN-SUBSETP-EQUAL))
     (4 4
        (:REWRITE SV::SVARLIST-P-WHEN-SUBSETP-EQUAL))
     (4 4
        (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (4 4
        (:REWRITE SV::SVAR-MAP-P-WHEN-SUBSETP-EQUAL))
     (4 4
        (:REWRITE SV::SVAR-ALIST-P-WHEN-SUBSETP-EQUAL))
     (4 4 (:REWRITE DEFAULT-CDR))
     (2 2
        (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE SV::SVEX-ALIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE SV::SVARLIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE SV::SVAR-MAP-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE SV::SVAR-BOOLMASKS-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE SV::SVAR-ALIST-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-WITNESS-COUNT-OF-CDR
     (33 10
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (8 2
        (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P))
     (1 1
        (:REWRITE-QUOTED-CONSTANT
             SV::NETEVAL-WITNESS-FIX-UNDER-NETEVAL-WITNESS-EQUIV)))
(SV::NETEVAL-WITNESS-COUNT-OF-CDR-STRONG
     (20 20 (:REWRITE DEFAULT-CDR))
     (6 6
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP)))
(SV::SVEX-NETWORK-JOIN-ENVS)
(SV::SVEX-ENV-P-OF-SVEX-NETWORK-JOIN-ENVS)
(SV::BOUNDP-OF-SVEX-NETWORK-JOIN-ENVS
     (13 1
         (:REWRITE SV::SVEX-ENV-EXTRACT-WHEN-ALIST-KEYS-EQUAL))
     (8 2
        (:REWRITE SV::SVEX-ENV-FIX-WHEN-SVEX-ENV-P))
     (5 1 (:REWRITE SV::SVAR-FIX-WHEN-SVAR-P))
     (5 1 (:DEFINITION BINARY-APPEND))
     (4 4 (:TYPE-PRESCRIPTION SV::SVEX-ENV-P))
     (4 4 (:TYPE-PRESCRIPTION ALIST-KEYS))
     (4 4
        (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (2 2 (:TYPE-PRESCRIPTION SV::SVAR-P))
     (2 2
        (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP))
     (1 1
        (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR)))
(SV::LOOKUP-OF-FN (13 1
                      (:REWRITE SV::SVEX-ENV-EXTRACT-WHEN-ALIST-KEYS-EQUAL))
                  (10 2 (:REWRITE SV::SVAR-FIX-WHEN-SVAR-P))
                  (8 8
                     (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
                  (8 2
                     (:REWRITE SV::SVEX-ENV-FIX-WHEN-SVEX-ENV-P))
                  (5 1 (:DEFINITION BINARY-APPEND))
                  (4 4 (:TYPE-PRESCRIPTION SV::SVEX-ENV-P))
                  (4 4 (:TYPE-PRESCRIPTION SV::SVAR-P))
                  (4 4 (:TYPE-PRESCRIPTION ALIST-KEYS))
                  (2 2
                     (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP))
                  (2 2
                     (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
                  (1 1 (:REWRITE DEFAULT-CDR))
                  (1 1 (:REWRITE DEFAULT-CAR)))
(SV::SVEX-ENVS-EQUIVALENT-IMPLIES-SVEX-ENVS-SIMILAR-SVEX-NETWORK-JOIN-ENVS-2)
(SV::SVEX-ENVS-EQUIVALENT-IMPLIES-SVEX-ENVS-EQUIVALENT-SVEX-NETWORK-JOIN-ENVS-3)
(SV::SVEX-ENVS-SIMILAR-IMPLIES-SVEX-ENVS-SIMILAR-SVEX-NETWORK-JOIN-ENVS-3)
(SV::SVEX-ALIST-EVAL-EQUIV-IMPLIES-SVEX-ENVS-EQUIVALENT-SVEX-NETWORK-JOIN-ENVS-1)
(SV::SVEX-NETWORK-JOIN-ENVS-OF-SVEX-ALIST-FIX-NETWORK)
(SV::SVEX-NETWORK-JOIN-ENVS-SVEX-ALIST-EQUIV-CONGRUENCE-ON-NETWORK)
(SV::SVEX-NETWORK-JOIN-ENVS-OF-SVEX-ENV-FIX-INTERNAL-ENV)
(SV::SVEX-NETWORK-JOIN-ENVS-SVEX-ENV-EQUIV-CONGRUENCE-ON-INTERNAL-ENV)
(SV::SVEX-NETWORK-JOIN-ENVS-OF-SVEX-ENV-FIX-INPUT-ENV)
(SV::SVEX-NETWORK-JOIN-ENVS-SVEX-ENV-EQUIV-CONGRUENCE-ON-INPUT-ENV)
(SV::NETEVAL-WITNESS->NETEVAL
     (36 12
         (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (14 5 (:REWRITE DEFAULT-CDR))
     (13 9
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (11 7 (:REWRITE DEFAULT-CAR))
     (6 2 (:REWRITE DEFAULT-<-2))
     (6 2 (:REWRITE DEFAULT-<-1)))
(SV::SVEX-ENV-P-OF-NETEVAL-WITNESS->NETEVAL
     (95 32
         (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (66 17
         (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP))
     (35 18 (:REWRITE DEFAULT-CAR))
     (22 11
         (:REWRITE SV::CONSP-CAR-OF-NETEVAL-WITNESS-FIX))
     (21 21
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (13 6 (:REWRITE DEFAULT-CDR))
     (8 8
        (:TYPE-PRESCRIPTION SV::SVEX-KIND$INLINE))
     (6 1 (:REWRITE SV::SVEX-EVAL-WHEN-QUOTE))
     (5 1 (:REWRITE SV::SVEX-EVAL-WHEN-FNCALL))
     (4 1 (:DEFINITION EQ))
     (1 1 (:REWRITE SV::SVEX-EVAL-OF-QUOTED)))
(SV::KEYS-SUBSETP-OF-NETEVAL-WITNESS->NETEVAL
     (69 45 (:REWRITE DEFAULT-CAR))
     (61 22
         (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (40 30 (:REWRITE DEFAULT-CDR))
     (28 11
         (:REWRITE SV::CONSP-CAR-OF-NETEVAL-WITNESS-FIX))
     (24 24
         (:TYPE-PRESCRIPTION SV::SVEX-KIND$INLINE))
     (18 3 (:REWRITE SV::SVEX-EVAL-WHEN-QUOTE))
     (15 3 (:REWRITE SV::SVEX-EVAL-WHEN-FNCALL))
     (13 13
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (12 12
         (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (12 3 (:DEFINITION EQ))
     (10 10 (:TYPE-PRESCRIPTION SV::SVAR-P))
     (7 7
        (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
     (5 5
        (:REWRITE SV::SVARLIST-P-WHEN-NOT-CONSP))
     (3 3 (:REWRITE SV::SVEX-EVAL-OF-QUOTED)))
(SV::SVEX-ENV-BOUNDP-OF-NETEVAL-WITNESS->NETEVAL
     (362 245 (:REWRITE DEFAULT-CAR))
     (228 52 (:REWRITE SV::SVAR-FIX-WHEN-SVAR-P))
     (138 102 (:REWRITE DEFAULT-CDR))
     (104 104
          (:TYPE-PRESCRIPTION SV::SVEX-KIND$INLINE))
     (88 88 (:TYPE-PRESCRIPTION SV::SVAR-P))
     (88 88
         (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (78 13 (:REWRITE SV::SVEX-EVAL-WHEN-QUOTE))
     (72 72
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (65 13 (:REWRITE SV::SVEX-EVAL-WHEN-FNCALL))
     (52 13 (:DEFINITION EQ))
     (13 13 (:REWRITE SV::SVEX-EVAL-OF-QUOTED)))
(SV::SVEX-ENV-LOOKUP-OF-NETEVAL-WITNESS->NETEVAL
 (1226 983 (:REWRITE DEFAULT-CAR))
 (1014 39
       (:REWRITE SV::4VEC-P-OF-CDR-OF-HONS-ASSOC-EQUAL-WHEN-SVEX-ENV-P))
 (991 729 (:REWRITE DEFAULT-CDR))
 (652
  29
  (:REWRITE
    SV::NETEVAL-WITNESS-P-OF-CDR-OF-HONS-ASSOC-EQUAL-WHEN-NETEVAL-WITNESS-P))
 (582 118
      (:REWRITE SV::SVEX-EVAL-WHEN-FNCALL))
 (563 147 (:REWRITE SV::SVAR-FIX-WHEN-SVAR-P))
 (464 116 (:DEFINITION EQ))
 (208 208 (:TYPE-PRESCRIPTION SV::SVAR-P))
 (208 208
      (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
 (196 184
      (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
 (118 118 (:REWRITE SV::SVEX-EVAL-OF-QUOTED))
 (40 40
     (:REWRITE-QUOTED-CONSTANT SV::SVEX-ENV-FIX-UNDER-SVEX-ENV-EQUIV))
 (39 39
     (:REWRITE SV::SVEX-ENV-P-OF-NETEVAL-WITNESS->NETEVAL))
 (20 4
     (:REWRITE SV::4VEC-P-WHEN-MAYBE-4VEC-P))
 (8 8 (:TYPE-PRESCRIPTION SV::MAYBE-4VEC-P))
 (8 8
    (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
 (8 4
    (:REWRITE SV::MAYBE-4VEC-P-WHEN-4VEC-P)))
(SV::SVEX-ALIST-EVAL-EQUIV-IMPLIES-EQUAL-NETEVAL-WITNESS->NETEVAL-2
     (276 95
          (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (184 184
          (:TYPE-PRESCRIPTION SV::SVEX-KIND$INLINE))
     (139 24 (:REWRITE SV::SVEX-EVAL-WHEN-QUOTE))
     (124 76 (:REWRITE DEFAULT-CAR))
     (116 24 (:REWRITE SV::SVEX-EVAL-WHEN-FNCALL))
     (97 73 (:REWRITE DEFAULT-CDR))
     (92 23 (:DEFINITION EQ))
     (72 30
         (:REWRITE SV::CONSP-CAR-OF-NETEVAL-WITNESS-FIX))
     (35 35
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (32 8
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDR-WHEN-NETEVAL-WITNESS-P))
     (24 24 (:REWRITE SV::SVEX-EVAL-OF-QUOTED))
     (24 6
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-CDAR-WHEN-NETEVAL-WITNESS-P))
     (14 14
         (:REWRITE SV::NETEVAL-WITNESS-P-OF-NETEVAL-WITNESS-FIX))
     (2 2
        (:REWRITE-QUOTED-CONSTANT SV::SVEX-ENV-FIX-UNDER-SVEX-ENV-EQUIV)))
(SV::SVEX-ENVS-SIMILAR-IMPLIES-EQUAL-NETEVAL-WITNESS->NETEVAL-3
     (90 33
         (:REWRITE SV::NETEVAL-WITNESS-FIX-WHEN-NETEVAL-WITNESS-P))
     (52 20 (:REWRITE DEFAULT-CAR))
     (48 48
         (:TYPE-PRESCRIPTION SV::SVEX-KIND$INLINE))
     (48 18
         (:REWRITE SV::CONSP-CAR-OF-NETEVAL-WITNESS-FIX))
     (36 6 (:REWRITE SV::SVEX-EVAL-WHEN-QUOTE))
     (32 16 (:REWRITE DEFAULT-CDR))
     (30 6 (:REWRITE SV::SVEX-EVAL-WHEN-FNCALL))
     (24 6 (:DEFINITION EQ))
     (19 19
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (6 6 (:REWRITE SV::SVEX-EVAL-OF-QUOTED)))
(SV::NETEVAL-WITNESS->NETEVAL-OF-NIL)
(SV::NETEVAL-WITNESS->NETEVAL
     (48 12 (:REWRITE INTERSECTP-EQUAL-NON-CONS))
     (47 14
         (:REWRITE SV::SVEX-ALIST-P-WHEN-SUBSETP-EQUAL))
     (45 6
         (:REWRITE SV::SVAR-P-OF-CAR-WHEN-SVARLIST-P))
     (30 12
         (:REWRITE INTERSECTP-EQUAL-NON-CONS-1))
     (27 3 (:DEFINITION SUBSETP-EQUAL))
     (20 20 (:REWRITE DEFAULT-CAR))
     (15 15 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (12 12
         (:REWRITE SV::SVARLIST-P-WHEN-SUBSETP-EQUAL))
     (12 12
         (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (12 12 (:REWRITE DEFAULT-CDR))
     (9 9
        (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
     (7 7
        (:REWRITE SV::SVEX-ALIST-P-WHEN-NOT-CONSP))
     (7 7
        (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (6 6
        (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP))
     (6 6
        (:REWRITE SV::SVARLIST-P-WHEN-NOT-CONSP))
     (6 3 (:DEFINITION MEMBER-EQUAL)))
(SV::NETEVAL-WITNESS->NETEVAL-OF-NETEVAL-WITNESS-FIX-X
     (40 40
         (:TYPE-PRESCRIPTION SV::SVEX-KIND$INLINE))
     (31 19 (:REWRITE DEFAULT-CAR))
     (30 5 (:REWRITE SV::SVEX-EVAL-WHEN-QUOTE))
     (26 16 (:REWRITE DEFAULT-CDR))
     (25 5 (:REWRITE SV::SVEX-EVAL-WHEN-FNCALL))
     (22 11
         (:REWRITE SV::CONSP-CAR-OF-NETEVAL-WITNESS-FIX))
     (20 5 (:DEFINITION EQ))
     (11 11
         (:REWRITE SV::NETEVAL-WITNESS-P-WHEN-NOT-CONSP))
     (5 5 (:REWRITE SV::SVEX-EVAL-OF-QUOTED)))
(SV::NETEVAL-WITNESS->NETEVAL-NETEVAL-WITNESS-EQUIV-CONGRUENCE-ON-X)
(SV::NETEVAL-WITNESS->NETEVAL-OF-SVEX-ALIST-FIX-NETWORK)
(SV::NETEVAL-WITNESS->NETEVAL-SVEX-ALIST-EQUIV-CONGRUENCE-ON-NETWORK)
(SV::NETEVAL-WITNESS->NETEVAL-OF-SVEX-ENV-FIX-ENV)
(SV::NETEVAL-WITNESS->NETEVAL-SVEX-ENV-EQUIV-CONGRUENCE-ON-ENV)
(SV::NETEVAL-P)
(SV::NETEVAL-P-SUFF)
(SV::NETEVAL-P-OF-SVEX-ENV-FIX-NETEVAL
     (24 6
         (:REWRITE SV::SVEX-ENV-FIX-WHEN-SVEX-ENV-P))
     (12 12 (:TYPE-PRESCRIPTION SV::SVEX-ENV-P))
     (6 6
        (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-P-SVEX-ENV-EQUIV-CONGRUENCE-ON-NETEVAL)
(SV::NETEVAL-P-OF-SVEX-ENV-FIX-ENV
     (20 5
         (:REWRITE SV::SVEX-ENV-FIX-WHEN-SVEX-ENV-P))
     (10 10 (:TYPE-PRESCRIPTION SV::SVEX-ENV-P))
     (5 5
        (:REWRITE SV::SVEX-ENV-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-P-SVEX-ENV-EQUIV-CONGRUENCE-ON-ENV)
(SV::NETEVAL-P-OF-SVEX-ALIST-FIX-NETWORK
     (30 5
         (:REWRITE SV::SVEX-ALIST-FIX-WHEN-SVEX-ALIST-P))
     (10 10
         (:TYPE-PRESCRIPTION SV::SVEX-ALIST-P))
     (10 10
         (:REWRITE SV::SVEX-ALIST-P-WHEN-SUBSETP-EQUAL))
     (5 5
        (:REWRITE SV::SVEX-ALIST-P-WHEN-NOT-CONSP)))
(SV::NETEVAL-P-SVEX-ALIST-EQUIV-CONGRUENCE-ON-NETWORK)
(SV::SVEX-ENVS-EQUIVALENT-IMPLIES-EQUAL-NETEVAL-P-1)
(SV::SVEX-ENVS-SIMILAR-IMPLIES-EQUAL-NETEVAL-P-3)
(SV::SVEX-ALIST-EVAL-EQUIV-IMPLIES-EQUAL-NETEVAL-P-2)
(SV::NETEVAL-P-OF-NIL)
