include ../../../../Makefile-generic

# BOOKS = float-extra2 round-extra2 mult-proofs float round mult basic-extra basic arith-extra arith bvecp-raw-helpers simple-loop-helpers-extra simple-loop-helpers bits-extra bits
 
# Dependencies:
-include Makefile-deps
