(AIGNET::STYPE-COUNT-OF-LOOKUP-ID-OF-FANIN-COUNT
 (307 7
      (:REWRITE AIGNET::LOOKUP-ID-OUT-OF-BOUNDS))
 (116 4
      (:REWRITE AIGNET::LOOKUP-ID-OF-FANIN-COUNT))
 (106 16 (:REWRITE AIGNET::STYPE-BY-CTYPE))
 (105 39
      (:TYPE-PRESCRIPTION AIGNET::TRUE-LISTP-LOOKUP-ID-OF-NODE-LISTP))
 (68 2
     (:LINEAR AIGNET::FANIN-COUNT-WHEN-AIGNET-EXTENSION-BIND-INVERSE))
 (66 66 (:TYPE-PRESCRIPTION AIGNET::REGP))
 (60 2
     (:LINEAR AIGNET::FANIN-COUNT-OF-CDR-WEAK))
 (59 59
     (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (53 36
     (:REWRITE AIGNET::FANIN-COUNT-OF-ATOM))
 (50 50
     (:REWRITE AIGNET::STYPE$INLINE-OF-NODE-FIX-X-NORMALIZE-CONST))
 (45 45
     (:REWRITE AIGNET::STYPE-COUNT-OF-STYPE-FIX-TYPE-NORMALIZE-CONST))
 (45 45
     (:REWRITE AIGNET::STYPE-COUNT-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (44 9
     (:REWRITE AIGNET::AIGNET-EXTENSION-P-CDR))
 (44 4
     (:REWRITE AIGNET::LOOKUP-ID-OF-FANIN-COUNT-OF-SUFFIX))
 (42 42 (:REWRITE DEFAULT-CDR))
 (42
  42
  (:REWRITE
       AIGNET::CDR-OF-NODE-LIST-FIX-X-NORMALIZE-CONST-UNDER-NODE-LIST-EQUIV))
 (40 20 (:REWRITE DEFAULT-+-2))
 (39 39
     (:TYPE-PRESCRIPTION AIGNET::LOOKUP-ID))
 (38 38
     (:REWRITE AIGNET::CTYPE-OF-STYPE-FIX-X-NORMALIZE-CONST))
 (38 14
     (:REWRITE AIGNET::FANIN-NODE-P-BY-CTYPE))
 (36 36
     (:REWRITE AIGNET::FANIN-COUNT-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (36 36
     (:REWRITE AIGNET::FANIN-COUNT-OF-AIGNET-NORM-X-NORMALIZE-CONST))
 (34 29 (:REWRITE DEFAULT-CAR))
 (33 11
     (:REWRITE AIGNET::LOOKUP-ID-IN-BOUNDS-WHEN-POSITIVE))
 (30 10
     (:REWRITE AIGNET::STYPE-FIX-IDEMPOTENT))
 (27
  27
  (:REWRITE AIGNET::CAR-OF-NODE-LIST-FIX-X-NORMALIZE-CONST-UNDER-NODE-EQUIV))
 (21 10 (:REWRITE NFIX-WHEN-NOT-NATP))
 (20 20 (:TYPE-PRESCRIPTION AIGNET::STYPEP))
 (20 20 (:REWRITE DEFAULT-+-1))
 (18 18
     (:REWRITE AIGNET::AIGNET-EXTENSION-P-TRANSITIVE-RW))
 (18 18
     (:LINEAR AIGNET::AIGNET-EXTENSION-IMPLIES-STYPE-COUNT-GTE))
 (17 17
     (:LINEAR AIGNET::STYPE-COUNT-WHEN-AIGNET-EXTENSION))
 (15 7 (:REWRITE DEFAULT-<-2))
 (15 7 (:REWRITE DEFAULT-<-1))
 (14 14
     (:REWRITE AIGNET::FANIN-NODE-P-OF-NODE-FIX-X-NORMALIZE-CONST))
 (12 12
     (:REWRITE AIGNET::REGP-OF-STYPE-FIX-X-NORMALIZE-CONST))
 (11 11 (:TYPE-PRESCRIPTION POSP))
 (9 9
    (:REWRITE AIGNET::AIGNET-EXTENSION-P-SELF))
 (7 7
    (:TYPE-PRESCRIPTION AIGNET::FANIN-NODE-P))
 (7 7
    (:REWRITE AIGNET::LOOKUP-ID-OF-NODE-LIST-FIX-AIGNET-NORMALIZE-CONST))
 (7 7
    (:REWRITE AIGNET::LOOKUP-ID-OF-NFIX-ID-NORMALIZE-CONST))
 (7 7
    (:REWRITE AIGNET::LOOKUP-ID-IN-EXTENSION))
 (7 7
    (:REWRITE AIGNET::AIGNET-EXTENSION-SIMPLIFY-LOOKUP-ID))
 (4 4
    (:REWRITE AIGNET-EXTENSION-P-OF-NODE-LIST-FIX-OLD-NORMALIZE-CONST))
 (4 4
    (:REWRITE AIGNET-EXTENSION-P-OF-NODE-LIST-FIX-NEW-NORMALIZE-CONST))
 (3 3
    (:TYPE-PRESCRIPTION AIGNET::NODE-LIST-FIX$INLINE))
 (3 3 (:TYPE-PRESCRIPTION LNFIX$INLINE))
 (3 3
    (:LINEAR AIGNET::STYPE-COUNT-CDR-WHEN-AIGNET-EXTENSION-P))
 (3 3
    (:LINEAR AIGNET::STYPE-COUNT-CDR-WHEN-AIGNET-EXTENSION-INVERSE))
 (2 2
    (:LINEAR AIGNET::FANIN-COUNT-WHEN-AIGNET-EXTENSION))
 (2 2
    (:LINEAR AIGNET::FANIN-COUNT-CDR-WHEN-AIGNET-EXTENSION-STRONG))
 (2 2
    (:LINEAR AIGNET::FANIN-COUNT-CDR-WHEN-AIGNET-EXTENSION-INVERSE))
 (2 2
    (:LINEAR AIGNET::AIGNET-EXTENSION-IMPLIES-FANIN-COUNT-GTE)))
(AIGNET::CTYPE-GATE-IMPLIES-PI-COUNT-SAME
 (2710 23
       (:REWRITE AIGNET::LOOKUP-ID-OUT-OF-BOUNDS))
 (1249 36
       (:LINEAR AIGNET::FANIN-COUNT-OF-CDR-WEAK))
 (902 12 (:REWRITE NATP-WHEN-INTEGERP))
 (862 38
      (:LINEAR AIGNET::FANIN-COUNT-WHEN-AIGNET-EXTENSION-BIND-INVERSE))
 (718 121 (:REWRITE DEFAULT-CAR))
 (532 16
      (:REWRITE AIGNET::LOOKUP-ID-IN-BOUNDS-WHEN-POSITIVE))
 (485 3 (:REWRITE POSP-REDEFINITION))
 (430 64 (:REWRITE AIGNET::STYPE-BY-CTYPE))
 (412 31 (:REWRITE NFIX-WHEN-NOT-NATP))
 (340 258
      (:REWRITE AIGNET::FANIN-COUNT-OF-ATOM))
 (296 12 (:REWRITE NATP-WHEN-GTE-0))
 (270 270 (:TYPE-PRESCRIPTION AIGNET::REGP))
 (258 258
      (:REWRITE AIGNET::FANIN-COUNT-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (258 258
      (:REWRITE AIGNET::FANIN-COUNT-OF-AIGNET-NORM-X-NORMALIZE-CONST))
 (226 113 (:REWRITE DEFAULT-+-2))
 (221 221
      (:REWRITE AIGNET::STYPE$INLINE-OF-NODE-FIX-X-NORMALIZE-CONST))
 (215 215
      (:REWRITE AIGNET::CTYPE-OF-STYPE-FIX-X-NORMALIZE-CONST))
 (203 7
      (:REWRITE AIGNET::LOOKUP-ID-OF-FANIN-COUNT))
 (183 183 (:REWRITE DEFAULT-CDR))
 (183
  183
  (:REWRITE
       AIGNET::CDR-OF-NODE-LIST-FIX-X-NORMALIZE-CONST-UNDER-NODE-LIST-EQUIV))
 (158 158
      (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (154 35
      (:REWRITE AIGNET::AIGNET-EXTENSION-P-CDR))
 (151 3 (:REWRITE ZP-WHEN-GT-0))
 (117
  117
  (:REWRITE AIGNET::CAR-OF-NODE-LIST-FIX-X-NORMALIZE-CONST-UNDER-NODE-EQUIV))
 (117 62 (:REWRITE DEFAULT-<-1))
 (113 113 (:REWRITE DEFAULT-+-1))
 (96 62 (:REWRITE DEFAULT-<-2))
 (93 9
     (:REWRITE AIGNET::LOOKUP-ID-OF-FANIN-COUNT-OF-SUFFIX))
 (90 90
     (:REWRITE AIGNET::FANIN-NODE-P-OF-NODE-FIX-X-NORMALIZE-CONST))
 (77 77
     (:REWRITE AIGNET::STYPE-COUNT-OF-STYPE-FIX-TYPE-NORMALIZE-CONST))
 (77 77
     (:REWRITE AIGNET::STYPE-COUNT-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (70 70
     (:REWRITE AIGNET::AIGNET-EXTENSION-P-TRANSITIVE-RW))
 (48 48
     (:REWRITE AIGNET::REGP-OF-STYPE-FIX-X-NORMALIZE-CONST))
 (39 13
     (:REWRITE AIGNET::STYPE-FIX-IDEMPOTENT))
 (38 38
     (:LINEAR AIGNET::FANIN-COUNT-WHEN-AIGNET-EXTENSION))
 (38 38
     (:LINEAR AIGNET::AIGNET-EXTENSION-IMPLIES-FANIN-COUNT-GTE))
 (36 36
     (:LINEAR AIGNET::FANIN-COUNT-CDR-WHEN-AIGNET-EXTENSION-STRONG))
 (36 36
     (:LINEAR AIGNET::FANIN-COUNT-CDR-WHEN-AIGNET-EXTENSION-INVERSE))
 (35 35
     (:REWRITE AIGNET::AIGNET-EXTENSION-P-SELF))
 (26 26 (:TYPE-PRESCRIPTION AIGNET::STYPEP))
 (24 3 (:REWRITE ZP-WHEN-INTEGERP))
 (23 23
     (:REWRITE AIGNET::LOOKUP-ID-OF-NODE-LIST-FIX-AIGNET-NORMALIZE-CONST))
 (23 23
     (:REWRITE AIGNET::LOOKUP-ID-OF-NFIX-ID-NORMALIZE-CONST))
 (23 23
     (:REWRITE AIGNET::LOOKUP-ID-IN-EXTENSION))
 (23 23
     (:REWRITE AIGNET::AIGNET-EXTENSION-SIMPLIFY-LOOKUP-ID))
 (22 22
     (:LINEAR AIGNET::AIGNET-EXTENSION-IMPLIES-STYPE-COUNT-GTE))
 (21 21
     (:LINEAR AIGNET::STYPE-COUNT-WHEN-AIGNET-EXTENSION))
 (16 16 (:TYPE-PRESCRIPTION POSP))
 (13 13
     (:TYPE-PRESCRIPTION AIGNET::FANIN-NODE-P))
 (12 12 (:TYPE-PRESCRIPTION NATP))
 (8 8 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
 (7 7
    (:REWRITE AIGNET-EXTENSION-P-OF-NODE-LIST-FIX-OLD-NORMALIZE-CONST))
 (7 7
    (:REWRITE AIGNET-EXTENSION-P-OF-NODE-LIST-FIX-NEW-NORMALIZE-CONST))
 (6 6
    (:TYPE-PRESCRIPTION AIGNET::NODE-LIST-FIX$INLINE))
 (6 6 (:TYPE-PRESCRIPTION LNFIX$INLINE))
 (5 5
    (:LINEAR AIGNET::STYPE-COUNT-CDR-WHEN-AIGNET-EXTENSION-P))
 (5 5
    (:LINEAR AIGNET::STYPE-COUNT-CDR-WHEN-AIGNET-EXTENSION-INVERSE))
 (3 3
    (:REWRITE AIGNET::CAR-LOOKUP-ID-OF-AIGNET-NORM-X-NORMALIZE-CONST)))
(AIGNET::AIGNET-ROLLBACK-ONE-GATE
 (42 2 (:REWRITE DEFAULT-CAR))
 (32 1
     (:REWRITE AIGNET::LOOKUP-ID-IN-BOUNDS-WHEN-POSITIVE))
 (30 3
     (:REWRITE AIGNET::LOOKUP-ID-OUT-OF-BOUNDS))
 (23 16 (:REWRITE DEFAULT-+-2))
 (19 12
     (:REWRITE AIGNET::FANIN-COUNT-OF-ATOM))
 (18 18
     (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (18 11 (:REWRITE DEFAULT-<-2))
 (17 2 (:REWRITE AIGNET::STYPE-BY-CTYPE))
 (16 16 (:REWRITE DEFAULT-+-1))
 (16 10
     (:REWRITE AIGNET::STYPE-COUNT-OF-ATOM))
 (16 2 (:REWRITE ZP-WHEN-GT-0))
 (14 11 (:REWRITE DEFAULT-<-1))
 (13 13
     (:TYPE-PRESCRIPTION AIGNET::CTYPE-FIX))
 (12 12
     (:REWRITE AIGNET::FANIN-COUNT-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (12 12
     (:REWRITE AIGNET::FANIN-COUNT-OF-AIGNET-NORM-X-NORMALIZE-CONST))
 (11 11 (:TYPE-PRESCRIPTION AIGNET::REGP))
 (10 10
     (:REWRITE-QUOTED-CONSTANT AIGNET::STYPE-FIX-UNDER-STYPE-EQUIV))
 (10 10
     (:REWRITE AIGNET::STYPE-COUNT-OF-STYPE-FIX-TYPE-NORMALIZE-CONST))
 (10 10
     (:REWRITE AIGNET::STYPE-COUNT-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (10 1
     (:REWRITE AIGNET::LOOKUP-ID-OF-FANIN-COUNT))
 (5 1
    (:REWRITE AIGNET::LOOKUP-ID-OF-FANIN-COUNT-OF-SUFFIX))
 (4 4
    (:REWRITE AIGNET::STYPE$INLINE-OF-NODE-FIX-X-NORMALIZE-CONST))
 (4 4
    (:LINEAR AIGNET::STYPE-COUNT-WHEN-AIGNET-EXTENSION-BIND-INVERSE))
 (4 4
    (:LINEAR AIGNET::STYPE-COUNT-WHEN-AIGNET-EXTENSION))
 (4 4
    (:LINEAR AIGNET::AIGNET-EXTENSION-IMPLIES-STYPE-COUNT-GTE))
 (4 2
    (:REWRITE AIGNET::NODE-LISTP-WHEN-NOT-CONSP))
 (3 3
    (:REWRITE AIGNET::PO-COUNT-OF-AIGNET-NORM-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE AIGNET::LOOKUP-ID-OF-NODE-LIST-FIX-AIGNET-NORMALIZE-CONST))
 (3 3
    (:REWRITE AIGNET::LOOKUP-ID-OF-NFIX-ID-NORMALIZE-CONST))
 (3 3
    (:REWRITE AIGNET::LOOKUP-ID-IN-EXTENSION-INVERSE))
 (3 3
    (:REWRITE AIGNET::LOOKUP-ID-IN-EXTENSION))
 (3 3
    (:REWRITE AIGNET::AIGNET-EXTENSION-SIMPLIFY-LOOKUP-ID))
 (3 2 (:REWRITE NFIX-WHEN-NOT-NATP))
 (3 2 (:REWRITE NFIX-WHEN-NATP))
 (3 1
    (:REWRITE AIGNET::FANIN-NODE-P-BY-CTYPE))
 (2 2
    (:TYPE-PRESCRIPTION AIGNET::FANIN-NODE-P))
 (2 2
    (:REWRITE AIGNET::REGP-OF-STYPE-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE AIGNET::REG-COUNT-OF-AIGNET-NORM-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE AIGNET::PI-COUNT-OF-AIGNET-NORM-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE AIGNET::CTYPE-OF-STYPE-FIX-X-NORMALIZE-CONST))
 (2
  2
  (:REWRITE AIGNET::CAR-OF-NODE-LIST-FIX-X-NORMALIZE-CONST-UNDER-NODE-EQUIV))
 (2 2
    (:REWRITE AIGNET::AIGNET-NODES-OK-OF-SUFFIX-INVERSE))
 (2
  2
  (:REWRITE AIGNET::AIGNET-NODES-OK-OF-NODE-LIST-FIX-AIGNET-NORMALIZE-CONST))
 (2 2
    (:REWRITE AIGNET::AIGNET-NODES-OK-OF-EXTENSION))
 (2 2
    (:REWRITE AIGNET::AIGNET-EXTENSION-P-TRANSITIVE-RW))
 (2 2
    (:LINEAR AIGNET::FANIN-COUNT-WHEN-AIGNET-EXTENSION-BIND-INVERSE))
 (2 2
    (:LINEAR AIGNET::FANIN-COUNT-WHEN-AIGNET-EXTENSION))
 (2 2
    (:LINEAR AIGNET::AIGNET-EXTENSION-IMPLIES-FANIN-COUNT-GTE))
 (1 1 (:TYPE-PRESCRIPTION POSP))
 (1 1
    (:REWRITE AIGNET::FANIN-NODE-P-OF-NODE-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE AIGNET::CAR-LOOKUP-ID-OF-AIGNET-NORM-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE AIGNET::AIGNET-EXTENSION-SIMPLIFY-AIGNET-IDP)))
