include ../../../../../Makefile-generic

# From make dependencies:

reflexive-macros.cert: reflexive-macros.lisp
reflexive-macros.cert: reflexive.cert

reflexive.cert: reflexive.lisp
# reflexive.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic/top-with-meta.cert
