## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

include dir.mk

include $(DIR)/books/Makefile-subdirs

DIRS = books factorial Fibonacci TEA RC6 AES

.PHONY: depend
depend:
	sh cert.sh

# $(DIRS):
# 	$(MAKE) -C $@


