# EDIT THE FOLLOWING by replacing the directory with your ACL2 distributed
# books directory.  You are welcome to omit this line, or not as you prefer, in
# your contribution.

ACL2_SYSTEM_BOOKS = ../../../..
ACL2 ?= ../../../../../saved_acl2

DIRS = generic-modules instantiations

include $(ACL2_SYSTEM_BOOKS)/Makefile-subdirs

include $(ACL2_SYSTEM_BOOKS)/Makefile-generic
