# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../Makefile-generic

ACL2 = ../../../../../saved_acl2

# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

flat-ackermann.cert: flat-ackermann.lisp
flat-ackermann.cert: flat.cert

flat-nested.cert: flat-nested.lisp
flat-nested.cert: flat.cert

flat-primitive.cert: flat-primitive.lisp
flat-primitive.cert: flat.cert

flat-reverse.cert: flat-reverse.lisp
flat-reverse.cert: flat.cert

flat-tail.cert: flat-tail.lisp
flat-tail.cert: flat.cert

flat-z.cert: flat-z.lisp
flat-z.cert: flat.cert

flat.cert: flat.lisp
