(C::MSGP-WHEN-STRINGP)
(C::MSGP-WHEN-CONSP-AND-STRINGP-AND-CHARACTER-ALISTP)
(C::PPRINT-INDENT (8 1 (:REWRITE REPEAT-WHEN-ZP))
                  (6 6 (:REWRITE DEFAULT-<-2))
                  (6 6 (:REWRITE DEFAULT-<-1))
                  (6 1 (:REWRITE ZP-OPEN))
                  (2 2 (:REWRITE DEFAULT-*-2))
                  (2 2 (:REWRITE DEFAULT-*-1))
                  (1 1 (:TYPE-PRESCRIPTION ZP)))
(C::MSGP-OF-PPRINT-INDENT)
(C::PPRINT-INDENT-OF-NFIX-LEVEL)
(C::PPRINT-INDENT-OF-NFIX-LEVEL-NORMALIZE-CONST)
(C::PPRINT-INDENT-NAT-EQUIV-CONGRUENCE-ON-LEVEL)
(C::PPRINT-COMMA-SEP (6 6 (:REWRITE DEFAULT-CDR))
                     (1 1 (:REWRITE MSG-LISTP-WHEN-NOT-CONSP)))
(C::MSGP-OF-PPRINT-COMMA-SEP
  (158 16 (:DEFINITION MEMBER-EQUAL))
  (39 39 (:REWRITE DEFAULT-CDR))
  (32 32 (:REWRITE SUBSETP-MEMBER . 2))
  (32 32 (:REWRITE SUBSETP-MEMBER . 1))
  (32 32 (:REWRITE DEFAULT-CAR))
  (10 10 (:REWRITE C::MSGP-WHEN-STRINGP))
  (4 4
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
  (1 1 (:REWRITE SUBSETP-TRANS2))
  (1 1 (:REWRITE SUBSETP-TRANS)))
(C::PPRINT-IDENT)
(C::MSGP-OF-PPRINT-IDENT)
(C::PPRINT-IDENT-OF-IDENT-FIX-ID)
(C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST)
(C::PPRINT-IDENT-IDENT-EQUIV-CONGRUENCE-ON-ID)
(C::PPRINT-ICONST-TYSUFFIX)
(C::MSGP-OF-PPRINT-ICONST-TYSUFFIX
 (3 1
    (:REWRITE C::MSGP-WHEN-CONSP-AND-STRINGP-AND-CHARACTER-ALISTP))
 (1
  1
  (:REWRITE
   C::ICONST-TYSUFFIX-KIND$INLINE-OF-ICONST-TYSUFFIX-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-ICONST-TYSUFFIX-OF-ICONST-TYSUFFIX-FIX-TS)
(C::PPRINT-ICONST-TYSUFFIX-OF-ICONST-TYSUFFIX-FIX-TS-NORMALIZE-CONST)
(C::PPRINT-ICONST-TYSUFFIX-ICONST-TYSUFFIX-EQUIV-CONGRUENCE-ON-TS)
(C::PPRINT-DEC-CONST)
(C::MSGP-OF-PPRINT-DEC-CONST)
(C::PPRINT-DEC-CONST-OF-NFIX-N)
(C::PPRINT-DEC-CONST-OF-NFIX-N-NORMALIZE-CONST)
(C::PPRINT-DEC-CONST-NAT-EQUIV-CONGRUENCE-ON-N)
(C::PPRINT-OCT-CONST)
(C::MSGP-OF-PPRINT-OCT-CONST)
(C::PPRINT-OCT-CONST-OF-NFIX-N
     (8 4
        (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (4 4
        (:TYPE-PRESCRIPTION STR::STRINGP-OF-NATSTR8))
     (3 3 (:REWRITE DEFAULT-<-2))
     (3 3 (:REWRITE DEFAULT-<-1)))
(C::PPRINT-OCT-CONST-OF-NFIX-N-NORMALIZE-CONST)
(C::PPRINT-OCT-CONST-NAT-EQUIV-CONGRUENCE-ON-N)
(C::PPRINT-HEX-CONST)
(C::MSGP-OF-PPRINT-HEX-CONST)
(C::PPRINT-HEX-CONST-OF-NFIX-N)
(C::PPRINT-HEX-CONST-OF-NFIX-N-NORMALIZE-CONST)
(C::PPRINT-HEX-CONST-NAT-EQUIV-CONGRUENCE-ON-N)
(C::PPRINT-ICONST)
(C::MSGP-OF-PPRINT-ICONST
 (68 55 (:REWRITE DEFAULT-CAR))
 (36 36
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (24 24 (:REWRITE DEFAULT-CDR))
 (20
   20
   (:REWRITE
        C::PPRINT-ICONST-TYSUFFIX-OF-ICONST-TYSUFFIX-FIX-TS-NORMALIZE-CONST))
 (19 19
     (:REWRITE C::ICONST->TYPE$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST))
 (10
  10
  (:REWRITE C::ICONST-BASE-KIND$INLINE-OF-ICONST-BASE-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::ICONST->BASE$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::ICONST->VALUE$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::ICONST->UNSIGNEDP$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-OCT-CONST-OF-NFIX-N-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-HEX-CONST-OF-NFIX-N-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-DEC-CONST-OF-NFIX-N-NORMALIZE-CONST))
 (2 2
    (:REWRITE MSGP-WHEN-MEMBER-EQUAL-OF-MSG-LISTP))
 (2 1 (:REWRITE C::MSGP-WHEN-STRINGP)))
(C::PPRINT-ICONST-OF-ICONST-FIX-C
 (4 4
    (:REWRITE C::PPRINT-OCT-CONST-OF-NFIX-N-NORMALIZE-CONST))
 (4
   4
   (:REWRITE
        C::PPRINT-ICONST-TYSUFFIX-OF-ICONST-TYSUFFIX-FIX-TS-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-HEX-CONST-OF-NFIX-N-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-DEC-CONST-OF-NFIX-N-NORMALIZE-CONST))
 (4
  4
  (:REWRITE C::ICONST-BASE-KIND$INLINE-OF-ICONST-BASE-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::ICONST->VALUE$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::ICONST->UNSIGNEDP$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::ICONST->TYPE$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST))
 (3 1 (:REWRITE C::ICONST-FIX-WHEN-ICONSTP))
 (2 2 (:TYPE-PRESCRIPTION C::ICONSTP))
 (2 2
    (:REWRITE C::ICONST->BASE$INLINE-OF-ICONST-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-ICONST-OF-ICONST-FIX-C-NORMALIZE-CONST)
(C::PPRINT-ICONST-ICONST-EQUIV-CONGRUENCE-ON-C)
(C::PPRINT-CONST)
(C::MSGP-OF-PPRINT-CONST)
(C::PPRINT-CONST-OF-CONST-FIX-C
     (3 3
        (:REWRITE C::CONST-KIND$INLINE-OF-CONST-FIX-X-NORMALIZE-CONST))
     (3 3
        (:REWRITE C::CONST-INT->GET$INLINE-OF-CONST-FIX-X-NORMALIZE-CONST))
     (3 1 (:REWRITE C::CONST-FIX-WHEN-CONSTP))
     (2 2 (:TYPE-PRESCRIPTION C::CONSTP))
     (2 2
        (:REWRITE C::PPRINT-ICONST-OF-ICONST-FIX-C-NORMALIZE-CONST))
     (2 1 (:REWRITE C::CONST-FIX-WHEN-FLOAT))
     (2 1 (:REWRITE C::CONST-FIX-WHEN-ENUM))
     (2 1 (:REWRITE C::CONST-FIX-WHEN-CHAR)))
(C::PPRINT-CONST-OF-CONST-FIX-C-NORMALIZE-CONST)
(C::PPRINT-CONST-CONST-EQUIV-CONGRUENCE-ON-C)
(C::PPRINT-UNOP)
(C::MSGP-OF-PPRINT-UNOP
     (4 1
        (:REWRITE C::MSGP-WHEN-CONSP-AND-STRINGP-AND-CHARACTER-ALISTP))
     (1 1
        (:REWRITE C::UNOP-KIND$INLINE-OF-UNOP-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-UNOP-OF-UNOP-FIX-OP)
(C::PPRINT-UNOP-OF-UNOP-FIX-OP-NORMALIZE-CONST)
(C::PPRINT-UNOP-UNOP-EQUIV-CONGRUENCE-ON-OP)
(C::PPRINT-BINOP)
(C::MSGP-OF-PPRINT-BINOP
     (29 1
         (:REWRITE C::MSGP-WHEN-CONSP-AND-STRINGP-AND-CHARACTER-ALISTP))
     (1 1
        (:REWRITE C::BINOP-KIND$INLINE-OF-BINOP-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-BINOP-OF-BINOP-FIX-OP)
(C::PPRINT-BINOP-OF-BINOP-FIX-OP-NORMALIZE-CONST)
(C::PPRINT-BINOP-BINOP-EQUIV-CONGRUENCE-ON-OP)
(C::PPRINT-TYSPECSEQ)
(C::MSGP-OF-PPRINT-TYSPECSEQ
  (11 1
      (:REWRITE C::MSGP-WHEN-CONSP-AND-STRINGP-AND-CHARACTER-ALISTP))
  (1 1
     (:REWRITE C::TYSPECSEQ-KIND$INLINE-OF-TYSPECSEQ-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS)
(C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS-NORMALIZE-CONST)
(C::PPRINT-TYSPECSEQ-TYSPECSEQ-EQUIV-CONGRUENCE-ON-TSS)
(C::PPRINT-TYNAME)
(C::MSGP-OF-PPRINT-TYNAME)
(C::PPRINT-TYNAME-OF-TYNAME-FIX-TN)
(C::PPRINT-TYNAME-OF-TYNAME-FIX-TN-NORMALIZE-CONST)
(C::PPRINT-TYNAME-TYNAME-EQUIV-CONGRUENCE-ON-TN)
(C::EXPR-GRADEP)
(C::CONSP-WHEN-EXPR-GRADEP)
(C::EXPR-GRADE-KIND$INLINE)
(C::EXPR-GRADE-KIND-POSSIBILITIES)
(C::EXPR-GRADE-FIX$INLINE)
(C::EXPR-GRADEP-OF-EXPR-GRADE-FIX)
(C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP)
(C::EXPR-GRADE-FIX$INLINE)
(FTY::TMP-DEFFIXTYPE-IDEMPOTENT)
(C::EXPR-GRADE-EQUIV$INLINE)
(C::EXPR-GRADE-EQUIV-IS-AN-EQUIVALENCE)
(C::EXPR-GRADE-EQUIV-IMPLIES-EQUAL-EXPR-GRADE-FIX-1)
(C::EXPR-GRADE-FIX-UNDER-EXPR-GRADE-EQUIV)
(C::EQUAL-OF-EXPR-GRADE-FIX-1-FORWARD-TO-EXPR-GRADE-EQUIV)
(C::EQUAL-OF-EXPR-GRADE-FIX-2-FORWARD-TO-EXPR-GRADE-EQUIV)
(C::EXPR-GRADE-EQUIV-OF-EXPR-GRADE-FIX-1-FORWARD)
(C::EXPR-GRADE-EQUIV-OF-EXPR-GRADE-FIX-2-FORWARD)
(C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X
     (1 1
        (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP)))
(C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST)
(C::EXPR-GRADE-KIND$INLINE-EXPR-GRADE-EQUIV-CONGRUENCE-ON-X)
(C::CONSP-OF-EXPR-GRADE-FIX)
(C::TAG-WHEN-EXPR-GRADEP-FORWARD
 (17
   17
   (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST)))
(C::TAG-OF-EXPR-GRADE-FIX)
(C::EXPR-GRADE-TOP)
(C::RETURN-TYPE-OF-EXPR-GRADE-TOP)
(C::EXPR-GRADE-FIX-WHEN-TOP
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2
   2
   (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST)))
(C::EQUAL-OF-EXPR-GRADE-TOP
 (3
   3
   (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST)))
(C::EXPR-GRADE-ASSIGNMENT)
(C::RETURN-TYPE-OF-EXPR-GRADE-ASSIGNMENT)
(C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP)))
(C::EQUAL-OF-EXPR-GRADE-ASSIGNMENT
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP)))
(C::EXPR-GRADE-CONDITIONAL)
(C::RETURN-TYPE-OF-EXPR-GRADE-CONDITIONAL)
(C::EXPR-GRADE-FIX-WHEN-CONDITIONAL
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EQUAL-OF-EXPR-GRADE-CONDITIONAL
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EXPR-GRADE-LOGICAL-OR)
(C::RETURN-TYPE-OF-EXPR-GRADE-LOGICAL-OR)
(C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EQUAL-OF-EXPR-GRADE-LOGICAL-OR
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EXPR-GRADE-LOGICAL-AND)
(C::RETURN-TYPE-OF-EXPR-GRADE-LOGICAL-AND)
(C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EQUAL-OF-EXPR-GRADE-LOGICAL-AND
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EXPR-GRADE-IOR)
(C::RETURN-TYPE-OF-EXPR-GRADE-IOR)
(C::EXPR-GRADE-FIX-WHEN-IOR
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EQUAL-OF-EXPR-GRADE-IOR
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EXPR-GRADE-XOR)
(C::RETURN-TYPE-OF-EXPR-GRADE-XOR)
(C::EXPR-GRADE-FIX-WHEN-XOR
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EQUAL-OF-EXPR-GRADE-XOR
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EXPR-GRADE-AND)
(C::RETURN-TYPE-OF-EXPR-GRADE-AND)
(C::EXPR-GRADE-FIX-WHEN-AND
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EQUAL-OF-EXPR-GRADE-AND
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT)))
(C::EXPR-GRADE-EQUALITY)
(C::RETURN-TYPE-OF-EXPR-GRADE-EQUALITY)
(C::EXPR-GRADE-FIX-WHEN-EQUALITY
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EQUAL-OF-EXPR-GRADE-EQUALITY
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EXPR-GRADE-RELATIONAL)
(C::RETURN-TYPE-OF-EXPR-GRADE-RELATIONAL)
(C::EXPR-GRADE-FIX-WHEN-RELATIONAL
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EQUAL-OF-EXPR-GRADE-RELATIONAL
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EXPR-GRADE-SHIFT)
(C::RETURN-TYPE-OF-EXPR-GRADE-SHIFT)
(C::EXPR-GRADE-FIX-WHEN-SHIFT
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EQUAL-OF-EXPR-GRADE-SHIFT
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EXPR-GRADE-ADDITIVE)
(C::RETURN-TYPE-OF-EXPR-GRADE-ADDITIVE)
(C::EXPR-GRADE-FIX-WHEN-ADDITIVE
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EQUAL-OF-EXPR-GRADE-ADDITIVE
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND)))
(C::EXPR-GRADE-MULTIPLICATIVE)
(C::RETURN-TYPE-OF-EXPR-GRADE-MULTIPLICATIVE)
(C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EQUAL-OF-EXPR-GRADE-MULTIPLICATIVE
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EXPR-GRADE-CAST)
(C::RETURN-TYPE-OF-EXPR-GRADE-CAST)
(C::EXPR-GRADE-FIX-WHEN-CAST
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EQUAL-OF-EXPR-GRADE-CAST
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EXPR-GRADE-UNARY)
(C::RETURN-TYPE-OF-EXPR-GRADE-UNARY)
(C::EXPR-GRADE-FIX-WHEN-UNARY
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EQUAL-OF-EXPR-GRADE-UNARY
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EXPR-GRADE-POSTFIX)
(C::RETURN-TYPE-OF-EXPR-GRADE-POSTFIX)
(C::EXPR-GRADE-FIX-WHEN-POSTFIX
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-UNARY))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EQUAL-OF-EXPR-GRADE-POSTFIX
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-UNARY))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EXPR-GRADE-PRIMARY)
(C::RETURN-TYPE-OF-EXPR-GRADE-PRIMARY)
(C::EXPR-GRADE-FIX-WHEN-PRIMARY
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
 (2 2
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-UNARY))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-POSTFIX))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (1 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (1 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EQUAL-OF-EXPR-GRADE-PRIMARY
 (3 3
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-UNARY))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-POSTFIX))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (2 2 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (2 2
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EXPR-GRADE-FIX-REDEF
 (154
    154
    (:REWRITE C::EXPR-GRADE-KIND$INLINE-OF-EXPR-GRADE-FIX-X-NORMALIZE-CONST))
 (3 1
    (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
 (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP)))
(C::EXPR->GRADE)
(C::EXPR-GRADEP-OF-EXPR->GRADE
     (1 1
        (:REWRITE C::EXPR-KIND$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-BINARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::BINOP-KIND$INLINE-OF-BINOP-FIX-X-NORMALIZE-CONST)))
(C::EXPR->GRADE-OF-EXPR-FIX-EXPR
     (8 1 (:REWRITE C::EXPR-FIX-WHEN-EXPRP))
     (5 1 (:REWRITE C::EXPRP-WHEN-EXPR-OPTIONP))
     (3 3 (:TYPE-PRESCRIPTION C::EXPRP))
     (3 3
        (:REWRITE C::EXPR-BINARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (2 2 (:TYPE-PRESCRIPTION C::EXPR-OPTIONP))
     (2 2
        (:REWRITE C::EXPR-KIND$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (2 2
        (:REWRITE C::BINOP-KIND$INLINE-OF-BINOP-FIX-X-NORMALIZE-CONST))
     (2 1
        (:REWRITE C::EXPR-OPTIONP-WHEN-EXPRP)))
(C::EXPR->GRADE-OF-EXPR-FIX-EXPR-NORMALIZE-CONST)
(C::EXPR->GRADE-EXPR-EQUIV-CONGRUENCE-ON-EXPR)
(C::EXPR-GRADE-INDEX)
(C::NATP-OF-EXPR-GRADE-INDEX)
(C::EXPR-GRADE-INDEX-OF-EXPR-GRADE-FIX-GRADE)
(C::EXPR-GRADE-INDEX-OF-EXPR-GRADE-FIX-GRADE-NORMALIZE-CONST)
(C::EXPR-GRADE-INDEX-EXPR-GRADE-EQUIV-CONGRUENCE-ON-GRADE)
(C::EXPR-GRADE-<=)
(C::BOOLEANP-OF-EXPR-GRADE-<=)
(C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE1
   (17 17
       (:TYPE-PRESCRIPTION C::EXPR-GRADE-KIND$INLINE))
   (5 5
      (:REWRITE C::EXPR-GRADE-INDEX-OF-EXPR-GRADE-FIX-GRADE-NORMALIZE-CONST))
   (4 2 (:REWRITE DEFAULT-<-2))
   (4 2 (:REWRITE DEFAULT-<-1))
   (3 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
   (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-UNARY))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-PRIMARY))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-POSTFIX))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE1-NORMALIZE-CONST)
(C::EXPR-GRADE-<=-EXPR-GRADE-EQUIV-CONGRUENCE-ON-GRADE1)
(C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE2
   (17 17
       (:TYPE-PRESCRIPTION C::EXPR-GRADE-KIND$INLINE))
   (5 5
      (:REWRITE C::EXPR-GRADE-INDEX-OF-EXPR-GRADE-FIX-GRADE-NORMALIZE-CONST))
   (4 2 (:REWRITE DEFAULT-<-2))
   (4 2 (:REWRITE DEFAULT-<-1))
   (3 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-EXPR-GRADEP))
   (2 2 (:TYPE-PRESCRIPTION C::EXPR-GRADEP))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-UNARY))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-PRIMARY))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-POSTFIX))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
   (2 1 (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
   (2 1
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE)))
(C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE2-NORMALIZE-CONST)
(C::EXPR-GRADE-<=-EXPR-GRADE-EQUIV-CONGRUENCE-ON-GRADE2)
(C::BINOP-EXPECTED-GRADES)
(C::EXPR-GRADEP-OF-BINOP-EXPECTED-GRADES.LEFT-GRADE
     (1 1
        (:REWRITE C::BINOP-KIND$INLINE-OF-BINOP-FIX-X-NORMALIZE-CONST)))
(C::EXPR-GRADEP-OF-BINOP-EXPECTED-GRADES.RIGHT-GRADE
     (1 1
        (:REWRITE C::BINOP-KIND$INLINE-OF-BINOP-FIX-X-NORMALIZE-CONST)))
(C::BINOP-EXPECTED-GRADES-OF-BINOP-FIX-OP)
(C::BINOP-EXPECTED-GRADES-OF-BINOP-FIX-OP-NORMALIZE-CONST)
(C::BINOP-EXPECTED-GRADES-BINOP-EQUIV-CONGRUENCE-ON-OP)
(C::PPRINT-EXPR
 (48 48
     (:REWRITE C::EXPR-COUNT-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (42 14 (:REWRITE DEFAULT-<-2))
 (42 14 (:REWRITE DEFAULT-<-1))
 (39 39
     (:REWRITE C::EXPR-KIND$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (8 8
    (:REWRITE C::EXPR-LIST-COUNT-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-UNARY->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-PREINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-PREDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-POSTINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-POSTDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-COND->THEN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-COND->TEST$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-COND->ELSE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-CAST->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-CALL->ARGS$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-BINARY->ARG2$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-BINARY->ARG1$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE DEFAULT-CDR))
 (2 2 (:REWRITE DEFAULT-CAR))
 (2
  2
  (:REWRITE C::CDR-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST-UNDER-EXPR-LIST-EQUIV))
 (2 2
    (:REWRITE C::CAR-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST-UNDER-EXPR-EQUIV)))
(C::PPRINT-EXPR-FLAG
 (48 48
     (:REWRITE C::EXPR-COUNT-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (42 14 (:REWRITE DEFAULT-<-2))
 (42 14 (:REWRITE DEFAULT-<-1))
 (39 39
     (:REWRITE C::EXPR-KIND$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (8 8
    (:REWRITE C::EXPR-LIST-COUNT-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-UNARY->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-PREINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-PREDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-POSTINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-POSTDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-COND->THEN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-COND->TEST$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-COND->ELSE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-CAST->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-CALL->ARGS$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-BINARY->ARG2$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-BINARY->ARG1$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE DEFAULT-CDR))
 (2 2 (:REWRITE DEFAULT-CAR))
 (2
  2
  (:REWRITE C::CDR-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST-UNDER-EXPR-LIST-EQUIV))
 (2 2
    (:REWRITE C::CAR-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST-UNDER-EXPR-EQUIV)))
(FLAG::FLAG-EQUIV-LEMMA)
(C::PPRINT-EXPR-FLAG-EQUIVALENCES)
(C::FLAG-LEMMA-FOR-RETURN-TYPE-OF-PPRINT-EXPR.PART
 (676 175 (:REWRITE C::MSGP-WHEN-STRINGP))
 (494 350
      (:REWRITE MSGP-WHEN-MEMBER-EQUAL-OF-MSG-LISTP))
 (255 211 (:REWRITE DEFAULT-CAR))
 (213 213
      (:REWRITE C::EXPR-KIND$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (137 137
      (:REWRITE C::EXPR-UNARY->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (120 10 (:DEFINITION MEMBER-EQUAL))
 (104
     104
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (99 99 (:REWRITE DEFAULT-CDR))
 (97 97
     (:REWRITE C::EXPR-UNARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (87 87
     (:REWRITE C::UNOP-KIND$INLINE-OF-UNOP-FIX-X-NORMALIZE-CONST))
 (66 17 (:REWRITE MSG-LISTP-WHEN-NOT-CONSP))
 (51 51 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
 (49 49
     (:REWRITE C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE2-NORMALIZE-CONST))
 (49 49
     (:REWRITE C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE1-NORMALIZE-CONST))
 (49 49
     (:REWRITE C::EXPR->GRADE-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
 (22 22
     (:REWRITE C::EXPR-BINARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (21 21
     (:REWRITE C::PPRINT-UNOP-OF-UNOP-FIX-OP-NORMALIZE-CONST))
 (21 1 (:REWRITE SUBSETP-OF-CONS))
 (20 20 (:REWRITE SUBSETP-MEMBER . 2))
 (20 20 (:REWRITE SUBSETP-MEMBER . 1))
 (19 19
     (:REWRITE C::BINOP-EXPECTED-GRADES-OF-BINOP-FIX-OP-NORMALIZE-CONST))
 (12 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (11 11
     (:REWRITE C::EXPR-COND->ELSE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::EXPR-BINARY->ARG2$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (10 10
     (:REWRITE C::EXPR-COND->THEN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (10 10
     (:REWRITE C::EXPR-CAST->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (10 10
     (:REWRITE C::EXPR-CALL->ARGS$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::EXPR-PREINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::EXPR-PREDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::EXPR-POSTINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::EXPR-POSTDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::EXPR-COND->TEST$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::EXPR-BINARY->ARG1$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (8 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (6 6 (:REWRITE SUBSETP-TRANS2))
 (6 6 (:REWRITE SUBSETP-TRANS))
 (5 5
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-BINOP-OF-BINOP-FIX-OP-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::PPRINT-TYNAME-OF-TYNAME-FIX-TN-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::EXPR-CAST->TYPE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::EXPR-CALL->FUN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::PPRINT-CONST-OF-CONST-FIX-C-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-IDENT->GET$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::EXPR-CONST->GET$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST)))
(C::RETURN-TYPE-OF-PPRINT-EXPR.PART)
(C::RETURN-TYPE-OF-PPRINT-EXPR-LIST.PARTS)
(C::PPRINT-EXPR
     (36 36
         (:REWRITE C::EXPR-KIND$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (25 25
         (:REWRITE C::UNOP-KIND$INLINE-OF-UNOP-FIX-X-NORMALIZE-CONST))
     (9 9
        (:REWRITE C::EXPR-UNARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (3 3
        (:REWRITE C::EXPR-LISTP-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE CAR-OF-BOOLEAN-LIST-FIX-X-NORMALIZE-CONST-UNDER-IFF))
     (1 1
        (:REWRITE C::EXPR-UNARY->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-COND->THEN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-COND->TEST$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-COND->ELSE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-CAST->TYPE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-CAST->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-CALL->FUN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-CALL->ARGS$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-BINARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-BINARY->ARG2$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR-BINARY->ARG1$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
     (1 1
        (:REWRITE C::EXPR->GRADE-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1
        (:REWRITE C::BINOP-EXPECTED-GRADES-OF-BINOP-FIX-OP-NORMALIZE-CONST)))
(C::FLAG-LEMMA-FOR-PPRINT-EXPR-OF-EXPR-FIX-EXPR
 (1819 1819
       (:TYPE-PRESCRIPTION C::EXPR-GRADE-KIND$INLINE))
 (497 96
      (:REWRITE C::EXPRP-WHEN-EXPR-OPTIONP))
 (333 333
      (:REWRITE C::EXPR-KIND$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-XOR))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-UNARY))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-TOP))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-SHIFT))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-RELATIONAL))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-PRIMARY))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-POSTFIX))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-MULTIPLICATIVE))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-OR))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-LOGICAL-AND))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-IOR))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-EQUALITY))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-CONDITIONAL))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-CAST))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-ASSIGNMENT))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-AND))
 (214 107
      (:REWRITE C::EXPR-GRADE-FIX-WHEN-ADDITIVE))
 (209 96
      (:REWRITE C::EXPR-OPTIONP-WHEN-EXPRP))
 (192 192
      (:TYPE-PRESCRIPTION C::EXPR-OPTIONP))
 (144 144
      (:REWRITE C::UNOP-KIND$INLINE-OF-UNOP-FIX-X-NORMALIZE-CONST))
 (135 135
      (:REWRITE C::EXPR-UNARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (119 119
      (:REWRITE C::EXPR-UNARY->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (85 85
     (:REWRITE C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE2-NORMALIZE-CONST))
 (85 85
     (:REWRITE C::EXPR->GRADE-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
 (68 68
     (:REWRITE C::EXPR-GRADE-<=-OF-EXPR-GRADE-FIX-GRADE1-NORMALIZE-CONST))
 (65 54 (:REWRITE DEFAULT-CDR))
 (65 54 (:REWRITE DEFAULT-CAR))
 (49 45
     (:REWRITE C::EXPR-LISTP-WHEN-NOT-CONSP))
 (44 11
     (:REWRITE C::EXPRP-OF-CAR-WHEN-EXPR-LISTP))
 (44 11
     (:REWRITE C::EXPR-LISTP-OF-CDR-WHEN-EXPR-LISTP))
 (28 28
     (:REWRITE C::PPRINT-UNOP-OF-UNOP-FIX-OP-NORMALIZE-CONST))
 (21 21
     (:REWRITE C::EXPR-CALL->ARGS$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (13 13
     (:REWRITE C::EXPR-BINARY->OP$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (12 12
     (:REWRITE C::BINOP-EXPECTED-GRADES-OF-BINOP-FIX-OP-NORMALIZE-CONST))
 (11
  11
  (:REWRITE C::CDR-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST-UNDER-EXPR-LIST-EQUIV))
 (11 11
     (:REWRITE C::CAR-OF-EXPR-LIST-FIX-X-NORMALIZE-CONST-UNDER-EXPR-EQUIV))
 (9 9
    (:REWRITE C::EXPR-BINARY->ARG2$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::EXPR-BINARY->ARG1$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (8 8
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-PREINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-PREDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-POSTINC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-POSTDEC->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-COND->THEN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-COND->TEST$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-COND->ELSE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (7 7
    (:REWRITE C::EXPR-CAST->ARG$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::EXPR-IDENT->GET$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::EXPR-CONST->GET$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::EXPR-CAST->TYPE$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::EXPR-CALL->FUN$INLINE-OF-EXPR-FIX-X-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-TYNAME-OF-TYNAME-FIX-TN-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-CONST-OF-CONST-FIX-C-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::PPRINT-BINOP-OF-BINOP-FIX-OP-NORMALIZE-CONST)))
(C::PPRINT-EXPR-OF-EXPR-FIX-EXPR)
(C::PPRINT-EXPR-OF-EXPR-GRADE-FIX-EXPECTED-GRADE)
(C::PPRINT-EXPR-LIST-OF-EXPR-LIST-FIX-EXPRS)
(C::PPRINT-EXPR-LIST-OF-EXPR-GRADE-FIX-EXPECTED-GRADE)
(C::PPRINT-EXPR-OF-EXPR-FIX-EXPR-NORMALIZE-CONST)
(C::PPRINT-EXPR-EXPR-EQUIV-CONGRUENCE-ON-EXPR)
(C::PPRINT-EXPR-OF-EXPR-GRADE-FIX-EXPECTED-GRADE-NORMALIZE-CONST)
(C::PPRINT-EXPR-EXPR-GRADE-EQUIV-CONGRUENCE-ON-EXPECTED-GRADE)
(C::PPRINT-EXPR-LIST-OF-EXPR-LIST-FIX-EXPRS-NORMALIZE-CONST)
(C::PPRINT-EXPR-LIST-EXPR-LIST-EQUIV-CONGRUENCE-ON-EXPRS)
(C::PPRINT-EXPR-LIST-OF-EXPR-GRADE-FIX-EXPECTED-GRADE-NORMALIZE-CONST)
(C::PPRINT-EXPR-LIST-EXPR-GRADE-EQUIV-CONGRUENCE-ON-EXPECTED-GRADE)
(C::PPRINT-LINE-BLANK)
(C::MSGP-OF-PPRINT-LINE-BLANK)
(C::PPRINT-LINE)
(C::MSGP-OF-PPRINT-LINE
  (8 7 (:REWRITE DEFAULT-CAR))
  (4 4
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
  (3 3 (:REWRITE DEFAULT-CDR))
  (1 1
     (:REWRITE C::PPRINT-INDENT-OF-NFIX-LEVEL-NORMALIZE-CONST)))
(C::PPRINT-DECL
 (13 10 (:REWRITE DEFAULT-CAR))
 (6 6
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (4 4 (:REWRITE DEFAULT-CDR))
 (3 3
    (:REWRITE-QUOTED-CONSTANT C::EXPR-GRADE-FIX-UNDER-EXPR-GRADE-EQUIV))
 (3
  3
  (:REWRITE C::PPRINT-EXPR-OF-EXPR-GRADE-FIX-EXPECTED-GRADE-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::PPRINT-EXPR-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::DECL->INIT$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (2 2 (:REWRITE DEFAULT-<-2))
 (2 2 (:REWRITE DEFAULT-<-1))
 (2 2
    (:REWRITE C::DECL->NAME$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::DECL->TYPE$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST)))
(C::MSGP-OF-PPRINT-DECL)
(C::PPRINT-DECL-OF-DECL-FIX-DECL
 (3 3
    (:REWRITE C::DECL->NAME$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::DECL->INIT$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST))
 (3 1 (:REWRITE C::DECL-FIX-WHEN-DECLP))
 (2 2 (:TYPE-PRESCRIPTION C::DECLP))
 (2 2
    (:REWRITE-QUOTED-CONSTANT C::EXPR-GRADE-FIX-UNDER-EXPR-GRADE-EQUIV))
 (2 2
    (:REWRITE C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (2
  2
  (:REWRITE C::PPRINT-EXPR-OF-EXPR-GRADE-FIX-EXPECTED-GRADE-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::PPRINT-EXPR-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
 (2 2 (:REWRITE DEFAULT-<-2))
 (2 2 (:REWRITE DEFAULT-<-1))
 (2 2
    (:REWRITE C::DECL->TYPE$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-DECL-OF-DECL-FIX-DECL-NORMALIZE-CONST)
(C::PPRINT-DECL-DECL-EQUIV-CONGRUENCE-ON-DECL)
(C::PPRINT-DECL-OF-NFIX-LEVEL
 (3 3 (:REWRITE DEFAULT-<-2))
 (3 3 (:REWRITE DEFAULT-<-1))
 (2 2
    (:REWRITE-QUOTED-CONSTANT C::EXPR-GRADE-FIX-UNDER-EXPR-GRADE-EQUIV))
 (2 2
    (:REWRITE C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (2
  2
  (:REWRITE C::PPRINT-EXPR-OF-EXPR-GRADE-FIX-EXPECTED-GRADE-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::PPRINT-EXPR-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::DECL->TYPE$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::DECL->NAME$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::DECL->INIT$INLINE-OF-DECL-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-DECL-OF-NFIX-LEVEL-NORMALIZE-CONST)
(C::PPRINT-DECL-NAT-EQUIV-CONGRUENCE-ON-LEVEL)
(C::PPRINT-LABEL)
(C::MSGP-OF-PPRINT-LABEL
 (7 1 (:REWRITE C::MSGP-WHEN-STRINGP))
 (5 4 (:REWRITE DEFAULT-CAR))
 (2 2
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (2 2
    (:REWRITE MSGP-WHEN-MEMBER-EQUAL-OF-MSG-LISTP))
 (2 2
    (:REWRITE C::LABEL-NAME->GET$INLINE-OF-LABEL-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::LABEL-KIND$INLINE-OF-LABEL-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE DEFAULT-CDR))
 (2 2
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV)))
(C::PPRINT-LABEL-OF-LABEL-FIX-LAB
     (3 3
        (:REWRITE C::LABEL-NAME->GET$INLINE-OF-LABEL-FIX-X-NORMALIZE-CONST))
     (3 1 (:REWRITE C::LABEL-FIX-WHEN-LABELP))
     (2 2 (:TYPE-PRESCRIPTION C::LABELP))
     (2 2
        (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
     (2 2
        (:REWRITE C::LABEL-KIND$INLINE-OF-LABEL-FIX-X-NORMALIZE-CONST))
     (2 1 (:REWRITE C::LABEL-FIX-WHEN-DEFAULT)))
(C::PPRINT-LABEL-OF-LABEL-FIX-LAB-NORMALIZE-CONST)
(C::PPRINT-LABEL-LABEL-EQUIV-CONGRUENCE-ON-LAB)
(C::PPRINT-STMT
 (2576 8 (:DEFINITION C::PPRINT-STMT))
 (720 360 (:REWRITE APPEND-WHEN-NOT-CONSP))
 (720 120 (:DEFINITION BINARY-APPEND))
 (360 120 (:REWRITE FOLD-CONSTS-IN-+))
 (240 120 (:REWRITE APPEND-OF-CONS))
 (185 170 (:REWRITE DEFAULT-CAR))
 (172
  172
  (:REWRITE C::PPRINT-EXPR-OF-EXPR-GRADE-FIX-EXPECTED-GRADE-NORMALIZE-CONST))
 (172 172
      (:REWRITE C::PPRINT-EXPR-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
 (145 145 (:REWRITE DEFAULT-CDR))
 (135 135 (:REWRITE DEFAULT-+-2))
 (135 135 (:REWRITE DEFAULT-+-1))
 (39 39
     (:REWRITE C::STMT-KIND$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (39 15 (:REWRITE DEFAULT-<-2))
 (39 15 (:REWRITE DEFAULT-<-1))
 (36 36
     (:REWRITE C::STMT-COUNT-OF-STMT-FIX-X-NORMALIZE-CONST))
 (24 24
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (20 20
     (:REWRITE-QUOTED-CONSTANT C::EXPR-GRADE-FIX-UNDER-EXPR-GRADE-EQUIV))
 (13 13
     (:REWRITE C::STMT-FOR->NEXT$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-WHILE->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-SWITCH->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-LABELED->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-IFELSE->THEN$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-IFELSE->ELSE$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-IF->THEN$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-FOR->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-FOR->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-DOWHILE->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (11 11
     (:REWRITE C::STMT-COMPOUND->ITEMS$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (10 10
     (:REWRITE C::PPRINT-LABEL-OF-LABEL-FIX-LAB-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-WHILE->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-SWITCH->CTRL$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-RETURN->VALUE$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-LABELED->LABEL$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-IFELSE->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-IF->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-GOTO->TARGET$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-FOR->INIT$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-EXPR->GET$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::STMT-DOWHILE->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (8 8
    (:REWRITE
         C::BLOCK-ITEM-LIST-COUNT-OF-BLOCK-ITEM-LIST-FIX-X-NORMALIZE-CONST))
 (8 1 (:DEFINITION C::PPRINT-BLOCK-ITEM))
 (5 5
    (:REWRITE C::BLOCK-ITEM-KIND$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (4 4
    (:REWRITE
         C::BLOCK-ITEM-STMT->GET$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::BLOCK-ITEM-COUNT-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::BLOCK-ITEM-LISTP-WHEN-NOT-CONSP))
 (2
  2
  (:REWRITE
   C::CDR-OF-BLOCK-ITEM-LIST-FIX-X-NORMALIZE-CONST-UNDER-BLOCK-ITEM-LIST-EQUIV))
 (2
  2
  (:REWRITE
     C::CAR-OF-BLOCK-ITEM-LIST-FIX-X-NORMALIZE-CONST-UNDER-BLOCK-ITEM-EQUIV))
 (2 2
    (:REWRITE
         C::BLOCK-ITEM-DECL->GET$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP))
 (1 1
    (:REWRITE C::PPRINT-DECL-OF-NFIX-LEVEL-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-DECL-OF-DECL-FIX-DECL-NORMALIZE-CONST)))
(C::PPRINT-STMT-FLAG
 (36 36
     (:REWRITE C::STMT-COUNT-OF-STMT-FIX-X-NORMALIZE-CONST))
 (36 12 (:REWRITE DEFAULT-<-2))
 (36 12 (:REWRITE DEFAULT-<-1))
 (9 9
    (:REWRITE C::STMT-KIND$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (8 8
    (:REWRITE
         C::BLOCK-ITEM-LIST-COUNT-OF-BLOCK-ITEM-LIST-FIX-X-NORMALIZE-CONST))
 (4 4
    (:REWRITE C::BLOCK-ITEM-COUNT-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-WHILE->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-SWITCH->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-LABELED->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-IFELSE->THEN$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-IFELSE->ELSE$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-IF->THEN$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-FOR->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-DOWHILE->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::STMT-COMPOUND->ITEMS$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE DEFAULT-CDR))
 (2 2 (:REWRITE DEFAULT-CAR))
 (2
  2
  (:REWRITE
   C::CDR-OF-BLOCK-ITEM-LIST-FIX-X-NORMALIZE-CONST-UNDER-BLOCK-ITEM-LIST-EQUIV))
 (2
  2
  (:REWRITE
     C::CAR-OF-BLOCK-ITEM-LIST-FIX-X-NORMALIZE-CONST-UNDER-BLOCK-ITEM-EQUIV))
 (2 2
    (:REWRITE
         C::BLOCK-ITEM-STMT->GET$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (1
   1
   (:REWRITE C::BLOCK-ITEM-KIND$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST)))
(FLAG::FLAG-EQUIV-LEMMA)
(C::PPRINT-STMT-FLAG-EQUIVALENCES)
(C::FLAG-LEMMA-FOR-RETURN-TYPE-OF-PPRINT-STMT.LINES
 (2074 82 (:REWRITE SUBSETP-OF-CONS))
 (1623 42 (:REWRITE SUBSETP-APPEND1))
 (1128 94 (:DEFINITION MEMBER-EQUAL))
 (690 293 (:REWRITE SUBSETP-TRANS2))
 (685 191 (:REWRITE MSG-LISTP-WHEN-NOT-CONSP))
 (531 531 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
 (358 188 (:REWRITE SUBSETP-MEMBER . 2))
 (310 89 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (283 283 (:REWRITE SUBSETP-TRANS))
 (232 89 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (206 206
      (:REWRITE C::STMT-KIND$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (188 188 (:TYPE-PRESCRIPTION C::PPRINT-LINE))
 (188 188 (:REWRITE SUBSETP-MEMBER . 1))
 (149 75 (:REWRITE DEFAULT-+-2))
 (115 115 (:REWRITE DEFAULT-CDR))
 (115 115 (:REWRITE DEFAULT-CAR))
 (75 75 (:REWRITE DEFAULT-+-1))
 (74 74
     (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (64 16 (:DEFINITION BINARY-APPEND))
 (59 59 (:REWRITE SUBSETP-NIL))
 (40 40
     (:REWRITE C::STMT-FOR->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (40 40
     (:REWRITE C::STMT-FOR->NEXT$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (40 40
     (:REWRITE C::STMT-FOR->INIT$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (40 40
     (:REWRITE C::STMT-FOR->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (19
  19
  (:REWRITE C::PPRINT-EXPR-OF-EXPR-GRADE-FIX-EXPECTED-GRADE-NORMALIZE-CONST))
 (19 19
     (:REWRITE C::PPRINT-EXPR-OF-EXPR-FIX-EXPR-NORMALIZE-CONST))
 (10 10
     (:REWRITE C::STMT-RETURN->VALUE$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (10
    10
    (:REWRITE C::BLOCK-ITEM-KIND$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-WHILE->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-SWITCH->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-LABELED->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-IFELSE->THEN$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-IFELSE->ELSE$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-IF->THEN$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-DOWHILE->BODY$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE C::STMT-COMPOUND->ITEMS$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE
         C::BLOCK-ITEM-STMT->GET$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-WHILE->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-SWITCH->CTRL$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-LABELED->LABEL$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-IFELSE->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-IF->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-GOTO->TARGET$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-EXPR->GET$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::STMT-DOWHILE->TEST$INLINE-OF-STMT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-LABEL-OF-LABEL-FIX-LAB-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-DECL-OF-NFIX-LEVEL-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-DECL-OF-DECL-FIX-DECL-NORMALIZE-CONST))
 (1
   1
   (:REWRITE
        C::BLOCK-ITEM-DECL->GET$INLINE-OF-BLOCK-ITEM-FIX-X-NORMALIZE-CONST)))
(C::RETURN-TYPE-OF-PPRINT-STMT.LINES)
(C::RETURN-TYPE-OF-PPRINT-BLOCK-ITEM.LINES)
(C::RETURN-TYPE-OF-PPRINT-BLOCK-ITEM-LIST.LINES)
(C::PPRINT-PARAM-DECL)
(C::MSGP-OF-PPRINT-PARAM-DECL
 (9 7 (:REWRITE DEFAULT-CAR))
 (4 4
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (3 3 (:REWRITE DEFAULT-CDR))
 (2 2
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (2
   2
   (:REWRITE C::PARAM-DECL->NAME$INLINE-OF-PARAM-DECL-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS-NORMALIZE-CONST))
 (1
  1
  (:REWRITE C::PARAM-DECL->TYPE$INLINE-OF-PARAM-DECL-FIX-X-NORMALIZE-CONST)))
(C::PPRINT-PARAM-DECL-OF-PARAM-DECL-FIX-PARAM)
(C::PPRINT-PARAM-DECL-OF-PARAM-DECL-FIX-PARAM-NORMALIZE-CONST)
(C::PPRINT-PARAM-DECL-PARAM-DECL-EQUIV-CONGRUENCE-ON-PARAM)
(C::PPRINT-PARAM-DECL-LIST (3 3
                              (:REWRITE C::PARAM-DECL-LISTP-WHEN-NOT-CONSP))
                           (1 1 (:REWRITE DEFAULT-CDR))
                           (1 1 (:REWRITE DEFAULT-CAR)))
(C::MSG-LISTP-OF-PPRINT-PARAM-DECL-LIST
 (30 8 (:REWRITE MSG-LISTP-WHEN-NOT-CONSP))
 (21 1 (:REWRITE SUBSETP-OF-CONS))
 (12 1 (:DEFINITION MEMBER-EQUAL))
 (8 2 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (6 6 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
 (6 2 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (5 5 (:REWRITE SUBSETP-TRANS2))
 (5 5 (:REWRITE SUBSETP-TRANS))
 (2 2
    (:TYPE-PRESCRIPTION C::PPRINT-PARAM-DECL))
 (2 2 (:REWRITE SUBSETP-MEMBER . 2))
 (2 2 (:REWRITE SUBSETP-MEMBER . 1))
 (2 2 (:REWRITE DEFAULT-CDR))
 (2 2 (:REWRITE DEFAULT-CAR))
 (1 1
    (:REWRITE C::PPRINT-PARAM-DECL-OF-PARAM-DECL-FIX-PARAM-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
    C::CAR-OF-PARAM-DECL-LIST-FIX-X-NORMALIZE-CONST-UNDER-PARAM-DECL-EQUIV)))
(C::PPRINT-PARAM-DECL-LIST-OF-PARAM-DECL-LIST-FIX-PARAMS
 (85 44 (:REWRITE DEFAULT-CDR))
 (76 13
     (:REWRITE C::PARAM-DECL-LIST-FIX-WHEN-PARAM-DECL-LISTP))
 (39
  39
  (:REWRITE
     C::CAR-OF-PARAM-DECL-LIST-FIX-X-NORMALIZE-CONST-UNDER-PARAM-DECL-EQUIV))
 (32 30 (:REWRITE DEFAULT-CAR))
 (28 28
     (:REWRITE C::PPRINT-PARAM-DECL-OF-PARAM-DECL-FIX-PARAM-NORMALIZE-CONST))
 (24 6
     (:REWRITE C::PARAM-DECL-LISTP-OF-CDR-WHEN-PARAM-DECL-LISTP))
 (20 19
     (:REWRITE C::PARAM-DECL-LISTP-WHEN-NOT-CONSP))
 (6
  6
  (:REWRITE
   C::CDR-OF-PARAM-DECL-LIST-FIX-X-NORMALIZE-CONST-UNDER-PARAM-DECL-LIST-EQUIV)))
(C::PPRINT-PARAM-DECL-LIST-OF-PARAM-DECL-LIST-FIX-PARAMS-NORMALIZE-CONST)
(C::PPRINT-PARAM-DECL-LIST-PARAM-DECL-LIST-EQUIV-CONGRUENCE-ON-PARAMS)
(C::PPRINT-FUNDEF
 (12 10 (:REWRITE DEFAULT-CAR))
 (6 6
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (4
  4
  (:REWRITE
    C::PPRINT-PARAM-DECL-LIST-OF-PARAM-DECL-LIST-FIX-PARAMS-NORMALIZE-CONST))
 (4 4 (:REWRITE DEFAULT-CDR))
 (3 3
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (3 3
    (:REWRITE C::FUNDEF->PARAMS$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS-NORMALIZE-CONST))
 (2 2
    (:REWRITE C::FUNDEF->NAME$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::FUNDEF->RESULT$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::FUNDEF->BODY$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST)))
(C::MSG-LISTP-OF-PPRINT-FUNDEF
 (6 1 (:DEFINITION BINARY-APPEND))
 (4 4
    (:REWRITE MSG-LISTP-WHEN-SUBSETP-EQUAL))
 (4 1 (:REWRITE MSG-LISTP-WHEN-NOT-CONSP))
 (1 1
    (:REWRITE C::PPRINT-TYSPECSEQ-OF-TYSPECSEQ-FIX-TSS-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
    C::PPRINT-PARAM-DECL-LIST-OF-PARAM-DECL-LIST-FIX-PARAMS-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::PPRINT-IDENT-OF-IDENT-FIX-ID-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::FUNDEF->RESULT$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::FUNDEF->PARAMS$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::FUNDEF->NAME$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE C::FUNDEF->BODY$INLINE-OF-FUNDEF-FIX-X-NORMALIZE-CONST))
 (1 1 (:REWRITE DEFAULT-CDR))
 (1 1 (:REWRITE DEFAULT-CAR)))
(C::PPRINT-EXT-DECL)
(C::MSG-LISTP-OF-PPRINT-EXT-DECL)
(C::PPRINT-EXT-DECL-LIST (3 3
                            (:REWRITE C::EXT-DECL-LISTP-WHEN-NOT-CONSP))
                         (2 2 (:REWRITE DEFAULT-CAR))
                         (1 1 (:REWRITE DEFAULT-CDR)))
(C::MSG-LISTP-OF-PPRINT-EXT-DECL-LIST
     (59 2 (:REWRITE SUBSETP-APPEND1))
     (47 1 (:REWRITE SUBSETP-OF-CONS))
     (32 12 (:REWRITE SUBSETP-TRANS2))
     (32 8 (:REWRITE MSG-LISTP-WHEN-NOT-CONSP))
     (21 8 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (20 8 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (12 12 (:REWRITE SUBSETP-TRANS))
     (10 1 (:DEFINITION MEMBER-EQUAL))
     (6 1 (:DEFINITION BINARY-APPEND))
     (5 5 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (3 3 (:REWRITE DEFAULT-CDR))
     (3 3 (:REWRITE DEFAULT-CAR))
     (2 2 (:REWRITE SUBSETP-MEMBER . 2))
     (2 2 (:REWRITE SUBSETP-MEMBER . 1)))
(C::PPRINT-TRANSUNIT)
(C::MSG-LISTP-OF-PPRINT-TRANSUNIT)
(C::PPRINTED-LINES-TO-CHANNEL)
(C::PPRINTED-LINES-TO-FILE)
