include ../../../../Makefile-generic

# BOOKS = basic bits-old bits float reps log logn logn2log simplify-model-helpers logn rom-helpers bvecp-raw-helpers simple-loop-helpers add mult round top
# Dependencies:

-include Makefile-deps
