(DIVIDE-TEST-VECTOR)
(PROCESSED-STV-P-OF-DIVIDE-TEST-VECTOR)
(DIVIDE-TEST-VECTOR-MOD)
(DIVIDE-RESETS-QUOTIENT
 (3 3 (:REWRITE GL::SHAPE-SPEC-OBJ-IN-RANGE-BACKCHAIN-INTEGER-2))
 )
(DIVIDE-RESETS-EVERYTHING
 (3 3 (:REWRITE GL::SHAPE-SPEC-OBJ-IN-RANGE-BACKCHAIN-INTEGER-2))
 )
