include ../../../Makefile-generic

# Override default setting since solutions.lisp is not intended to be certified.
BOOKS = find-path1 find-path2 find-path3 helpers linear-find-path

-include Makefile-deps
