include ../Makefile-generic

# Dependencies:



bash.cert: bash.lisp

beta-reduce.cert: beta-reduce.lisp

book-thms.cert: book-thms.lisp

bstar.cert: bstar.lisp
bstar.cert: pack.cert

computed-hint.cert: computed-hint.lisp

cws.cert: cws.lisp
cws.cert: progndollar.cert

defmac.cert: defmac.lisp

defopener.cert: defopener.lisp
defopener.cert: bash.cert

defp.cert: defp.lisp
defp.cert: defpun.cert

defpun-exec-domain-example.cert: defpun-exec-domain-example.lisp
# defpun-exec-domain-example.cert: $(ACL2_SYSTEM_BOOKS)/tools/defpun.cert
# defpun-exec-domain-example.cert: $(ACL2_SYSTEM_BOOKS)/make-event/eval.cert

defpun.cert: defpun.lisp

dump-events.cert: dump-events.lisp

expander.cert: expander.lisp

find-lemmas.cert: find-lemmas.lisp

hacker.cert: hacker.lisp
hacker.cert: hacker.acl2

pack.cert: pack.lisp

priorities.cert: priorities.lisp

progndollar.cert: progndollar.lisp

simplify-defuns.cert: simplify-defuns.lisp
simplify-defuns.cert: file-io.cert

sticky-disable.cert: sticky-disable.lisp

untranslate-patterns.cert: untranslate-patterns.lisp
untranslate-patterns.cert: symbol-btree.cert
# untranslate-patterns.cert: $(ACL2_SYSTEM_BOOKS)/tools/untranslate-patterns.cert