ACL2 ?= ../../../saved_acl2
include ../../Makefile-generic

BOOKS = from-rtl arithmetic evenp bit-functions logcar loghead ash \
	basics c-functions logpair byte-p logapp loglist logical-logops \
	bit-twiddling-logops hacks eric lshu super-ihs iter-sqrt logtail \
	unsigned-byte-p logbitp logext logcons logcdr min-max logbit meta inductions \
	fast carry logior-logapp-crock signed-byte-p-overflow plus-logapp-suck

-include Makefile-deps
