include ../../../../Makefile-generic


# Override default setting since build.lisp is not intended to be certified.
BOOKS = ctl defung fast-sets fixpoints meta models perm relations semantics sets syntax

-include Makefile-deps
