(CDR-OF-NAT-LIST-FIX
     (732 5
          (:REWRITE NAT-LIST-FIX-WHEN-NAT-LISTP))
     (708 10 (:DEFINITION NAT-LISTP))
     (530 54
          (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (464 34 (:DEFINITION INTEGER-LISTP))
     (432 10 (:DEFINITION NATP))
     (312 16
          (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (244 54
          (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (72 72
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (62 62 (:REWRITE DEFAULT-CAR))
     (26 10
         (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (24 23 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (14 14 (:REWRITE DEFAULT-<-2))
     (14 14 (:REWRITE DEFAULT-<-1))
     (1 1
        (:REWRITE-QUOTED-CONSTANT NAT-LIST-FIX-UNDER-NAT-LIST-EQUIV))
     (1 1 (:DEFINITION NOT)))
(CAR-OF-NAT-LIST-FIX-WHEN-CONSP
     (105 10 (:REWRITE DEFAULT-<-1))
     (90 12
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (79 7
         (:REWRITE NAT-LIST-FIX-WHEN-NAT-LISTP))
     (66 6 (:DEFINITION INTEGER-LISTP))
     (65 5
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (62 4
         (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
     (60 8
         (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
     (58 37 (:REWRITE DEFAULT-CAR))
     (55 7 (:DEFINITION NAT-LISTP))
     (54 2 (:DEFINITION ACL2-NUMBER-LISTP))
     (44 4 (:DEFINITION RATIONAL-LISTP))
     (42 42 (:TYPE-PRESCRIPTION INTEGER-LISTP))
     (28 28 (:TYPE-PRESCRIPTION RATIONAL-LISTP))
     (23 23 (:TYPE-PRESCRIPTION NAT-LISTP))
     (18 1 (:DEFINITION NATP))
     (15 15 (:REWRITE DEFAULT-CDR))
     (14 14
         (:TYPE-PRESCRIPTION ACL2-NUMBER-LISTP))
     (12 12
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (12 6
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (10 10 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (10 10 (:REWRITE DEFAULT-<-2))
     (8 8
        (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
     (8 4
        (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
     (7 7 (:REWRITE CONSP-OF-NAT-LIST-FIX))
     (6 3
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (4 4
        (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP))
     (4 2
        (:REWRITE ACL2-NUMBER-LISTP-OF-CDR-WHEN-ACL2-NUMBER-LISTP))
     (2 1
        (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP)))
(CAR-OF-NAT-LIST-FIX-IFF-CONSP
     (70 3
         (:REWRITE NAT-LIST-FIX-WHEN-NAT-LISTP))
     (58 2 (:DEFINITION NAT-LISTP))
     (45 6
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (36 2 (:DEFINITION NATP))
     (33 3 (:DEFINITION INTEGER-LISTP))
     (21 21 (:TYPE-PRESCRIPTION INTEGER-LISTP))
     (15 15 (:TYPE-PRESCRIPTION NAT-LISTP))
     (6 6
        (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (6 5 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (6 3
        (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (5 5 (:REWRITE DEFAULT-CDR))
     (4 2 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (4 2
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (3 3 (:REWRITE DEFAULT-<-2))
     (3 3 (:REWRITE DEFAULT-<-1)))
(REV-OF-NAT-LIST-FIX
     (31973 112
            (:REWRITE NAT-LIST-FIX-WHEN-NAT-LISTP))
     (27076 315 (:DEFINITION NAT-LISTP))
     (26437 1247
            (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (18720 275 (:DEFINITION NATP))
     (18574 941 (:DEFINITION INTEGER-LISTP))
     (17575 13 (:DEFINITION BINARY-APPEND))
     (16783 1488
            (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (16595 127 (:REWRITE INTEGER-LISTP-OF-REV))
     (15793 85 (:REWRITE NAT-LISTP-OF-REV))
     (15484 13 (:REWRITE CDR-OF-NAT-LIST-FIX))
     (14676 547
            (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (7791 412 (:REWRITE LIST-FIX-WHEN-TRUE-LISTP))
     (6820 200 (:REWRITE CDR-OF-LIST-FIX))
     (5879 162 (:REWRITE NAT-LISTP-OF-LIST-FIX))
     (5065 250
           (:REWRITE INTEGER-LISTP-OF-LIST-FIX))
     (4656 786
           (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (4539 412 (:REWRITE LIST-FIX-WHEN-LEN-ZERO))
     (4361 393 (:DEFINITION TRUE-LISTP))
     (3140 2390
           (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (2631 2499 (:REWRITE DEFAULT-CDR))
     (2590 2590 (:TYPE-PRESCRIPTION LEN))
     (2221 2221 (:TYPE-PRESCRIPTION TRUE-LIST-FIX))
     (2026 13
           (:REWRITE CAR-OF-NAT-LIST-FIX-WHEN-CONSP))
     (1923 1923 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1923 379 (:DEFINITION LEN))
     (1601 1469 (:REWRITE DEFAULT-CAR))
     (1548 1548
           (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (1548 774 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (1428 881 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (1038 275
           (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (774 774
          (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (774 774 (:REWRITE SET::IN-SET))
     (772 386 (:REWRITE DEFAULT-+-2))
     (729 358 (:REWRITE DEFAULT-<-1))
     (600 600 (:REWRITE CONSP-OF-LIST-FIX))
     (424 212 (:REWRITE CAR-OF-LIST-FIX))
     (412 412 (:REWRITE LIST-FIX-WHEN-NOT-CONSP))
     (386 386 (:REWRITE DEFAULT-+-1))
     (358 358 (:REWRITE DEFAULT-<-2))
     (307 9
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (304 8
          (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
     (298 34
          (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
     (298 4 (:DEFINITION ACL2-NUMBER-LISTP))
     (266 18 (:DEFINITION RATIONAL-LISTP))
     (145 145 (:REWRITE CONSP-OF-REV))
     (116 28
          (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
     (52 26 (:REWRITE CONSP-OF-NAT-LIST-FIX))
     (40 40
         (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
     (12 6
         (:REWRITE ACL2-NUMBER-LISTP-OF-CDR-WHEN-ACL2-NUMBER-LISTP))
     (8 8
        (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP))
     (1 1
        (:REWRITE-QUOTED-CONSTANT NAT-LIST-FIX-UNDER-NAT-LIST-EQUIV)))
(NAT-LIST-FIX-OF-TRUE-LIST-FIX)
