include ../../../../../Makefile-generic


det-macros.cert: det-macros.lisp

meta.cert: meta.lisp
meta.cert: ../../../../../arithmetic/top-with-meta.cert

records.cert: records.lisp
records.cert: total-order.cert

seq.cert: seq.lisp

total-order.cert: total-order.lisp
