#|-*-Makefile-*-=============================================================|#
#|                                                                           |#
#| records/fast                                                              |#
#|===========================================================================|#

# RAMS Makefile
# Use "make help" for more information

# Enter the path to the make directory, e.g., MAKEDIR = ../make

MAKEDIR = ../../make

# Enter the external libraries depended upon, e.g., LIBS = :bags :lists, or
# leave this blank if there are no external dependencies.

LIBS =

# Enter the names of the books to certify, e.g., BOOKS = book1 book2

BOOKS = log2 memtree memory-impl private memory

# At this point, we turn over control to RAMS and
# it handles everything else.

include $(MAKEDIR)/Makefile.top
