## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

# # .PHONY: depend
# # depend:
# # 	sh ../cert.mk

include ../../../../../Makefile-generic
-include Makefile-deps

BOOKS = fac-source-shallow-canon fac-source-shallow-flatten proof-fac


