(BVIF)
(INTEGERP-OF-BVIF)
(NATP-OF-BVIF)
(BVCHOP-OF-BVIF
     (1029 385
           (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (685 231 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (572 44 (:DEFINITION EXPT))
     (480 56 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (478 454 (:REWRITE DEFAULT-<-1))
     (454 454 (:REWRITE DEFAULT-<-2))
     (396 52
          (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (385 385
          (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (385 385
          (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (385 385 (:REWRITE UBP-LONGER-BETTER))
     (327 327 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (299 231
          (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (279 279 (:TYPE-PRESCRIPTION POSP))
     (267 267
          (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (231 231
          (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (132 44 (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP))
     (132 44 (:REWRITE DEFAULT-*-2))
     (132 44 (:REWRITE COMMUTATIVITY-OF-+))
     (88 88 (:REWRITE DEFAULT-+-2))
     (88 88 (:REWRITE DEFAULT-+-1))
     (74 37 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (57 57 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (44 44 (:REWRITE ZIP-OPEN))
     (44 44 (:REWRITE DEFAULT-*-1))
     (40 20 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (38 38
         (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (37 37
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (20 20 (:TYPE-PRESCRIPTION NATP))
     (20 20
         (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (20 20 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (8 8 (:REWRITE BVCHOP-BOUND))
     (7 7
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (7 7 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(BVIF-SAME-BRANCHES
     (29 5 (:REWRITE BVCHOP-IDENTITY))
     (25 5 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (22 1 (:DEFINITION EXPT))
     (18 9 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (18 6 (:REWRITE DEFAULT-<-2))
     (17 5
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (17 5
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (10 10 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (9 9
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 8 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (7 1 (:DEFINITION NATP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 2 (:REWRITE DEFAULT-*-2))
     (6 2 (:REWRITE COMMUTATIVITY-OF-+))
     (5 5 (:TYPE-PRESCRIPTION POSP))
     (5 5
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (5 5 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (4 4 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (4 4 (:REWRITE UBP-LONGER-BETTER))
     (4 4
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (4 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-+-1))
     (4 4
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (4 4
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (2 2 (:REWRITE DEFAULT-*-1))
     (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (1 1 (:REWRITE ZIP-OPEN))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P)))
(BVIF-WHEN-TRUE (22 1 (:DEFINITION EXPT))
                (21 3 (:REWRITE BVCHOP-IDENTITY))
                (18 3 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
                (14 7 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
                (14 5 (:REWRITE DEFAULT-<-2))
                (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
                (12 3
                    (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
                (12 3
                    (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
                (8 8 (:TYPE-PRESCRIPTION POWER-OF-2P))
                (7 7
                   (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
                (7 1 (:DEFINITION NATP))
                (6 6 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
                (6 3
                   (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
                (6 3
                   (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
                (6 2 (:REWRITE DEFAULT-*-2))
                (6 2 (:REWRITE COMMUTATIVITY-OF-+))
                (5 5 (:REWRITE DEFAULT-<-1))
                (4 4 (:TYPE-PRESCRIPTION NATP))
                (4 4 (:REWRITE DEFAULT-+-2))
                (4 4 (:REWRITE DEFAULT-+-1))
                (3 3 (:TYPE-PRESCRIPTION POSP))
                (3 3
                   (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
                (3 3
                   (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
                (3 3 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
                (3 3 (:REWRITE UBP-LONGER-BETTER))
                (3 3
                   (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                (3 3
                   (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
                (3 3 (:REWRITE BVCHOP-SUBST-CONSTANT))
                (3 3
                   (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
                (3 3
                   (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
                (2 2 (:REWRITE DEFAULT-*-1))
                (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
                (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
                (1 1 (:REWRITE ZIP-OPEN))
                (1 1
                   (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
                (1 1
                   (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
                (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P)))
(BVIF-WHEN-FALSE (22 1 (:DEFINITION EXPT))
                 (21 3 (:REWRITE BVCHOP-IDENTITY))
                 (18 3 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
                 (14 7 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
                 (14 5 (:REWRITE DEFAULT-<-2))
                 (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
                 (12 3
                     (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
                 (12 3
                     (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
                 (8 8 (:TYPE-PRESCRIPTION POWER-OF-2P))
                 (7 7
                    (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
                 (7 1 (:DEFINITION NATP))
                 (6 6 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
                 (6 3
                    (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
                 (6 3
                    (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
                 (6 2 (:REWRITE DEFAULT-*-2))
                 (6 2 (:REWRITE COMMUTATIVITY-OF-+))
                 (5 5 (:REWRITE DEFAULT-<-1))
                 (4 4 (:TYPE-PRESCRIPTION NATP))
                 (4 4 (:REWRITE DEFAULT-+-2))
                 (4 4 (:REWRITE DEFAULT-+-1))
                 (3 3 (:TYPE-PRESCRIPTION POSP))
                 (3 3
                    (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
                 (3 3
                    (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
                 (3 3 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
                 (3 3 (:REWRITE UBP-LONGER-BETTER))
                 (3 3
                    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                 (3 3
                    (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
                 (3 3 (:REWRITE BVCHOP-SUBST-CONSTANT))
                 (3 3
                    (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
                 (3 3
                    (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
                 (2 2 (:REWRITE DEFAULT-*-1))
                 (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
                 (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
                 (1 1 (:REWRITE ZIP-OPEN))
                 (1 1
                    (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
                 (1 1
                    (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
                 (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P)))
(BVIF-OF-NOT (28 4 (:REWRITE BVCHOP-IDENTITY))
             (24 4 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
             (16 8 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
             (16 4 (:REWRITE DEFAULT-<-2))
             (16 4
                 (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
             (16 4
                 (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
             (8 8 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
             (8 8 (:TYPE-PRESCRIPTION POWER-OF-2P))
             (8 8
                (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
             (8 4
                (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
             (8 4
                (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
             (4 4 (:TYPE-PRESCRIPTION POSP))
             (4 4 (:TYPE-PRESCRIPTION NATP))
             (4 4
                (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
             (4 4
                (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
             (4 4 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
             (4 4 (:REWRITE UBP-LONGER-BETTER))
             (4 4
                (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
             (4 4 (:REWRITE DEFAULT-<-1))
             (4 4
                (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
             (4 4 (:REWRITE BVCHOP-SUBST-CONSTANT))
             (4 4
                (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
             (4 4
                (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM)))
(EQUAL-OF-CONSTANT-AND-BVIF-OF-CONSTANT-AND-CONSTANT
     (175 21 (:REWRITE BVCHOP-IDENTITY))
     (68 17
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (54 26
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (52 4 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (52 4 (:DEFINITION EXPT))
     (50 25 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (49 17 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (44 32 (:REWRITE DEFAULT-<-1))
     (32 32 (:REWRITE DEFAULT-<-2))
     (29 29 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (26 26
         (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (26 26
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (26 26 (:REWRITE UBP-LONGER-BETTER))
     (25 25
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (21 21 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (17 17 (:TYPE-PRESCRIPTION POSP))
     (17 17
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (17 17
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (17 17
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (14 2
         (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (12 4 (:REWRITE DEFAULT-*-2))
     (12 4 (:REWRITE COMMUTATIVITY-OF-+))
     (8 8 (:TYPE-PRESCRIPTION BOOLEANP))
     (8 8
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (8 8 (:REWRITE DEFAULT-+-2))
     (8 8 (:REWRITE DEFAULT-+-1))
     (8 4 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (7 3 (:REWRITE BOOL-FIX-DOES-NOTHING))
     (6 2 (:REWRITE BOOL-FIX-WHEN-BOOLEANP))
     (5 5
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4 (:REWRITE ZIP-OPEN))
     (4 4 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (4 4
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (4 4
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (4 4 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (4 4 (:REWRITE DEFAULT-*-1))
     (4 4 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (4 4
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (4 4
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER)))
(BVIF-WHEN-TRUE-CHEAP
     (22 1 (:DEFINITION EXPT))
     (21 3 (:REWRITE BVCHOP-IDENTITY))
     (18 3 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (14 7 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (14 5 (:REWRITE DEFAULT-<-2))
     (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (12 3
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (12 3
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (8 8 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (7 7
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (7 1 (:DEFINITION NATP))
     (6 6 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (6 3
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (6 3
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (6 2 (:REWRITE DEFAULT-*-2))
     (6 2 (:REWRITE COMMUTATIVITY-OF-+))
     (5 5 (:REWRITE DEFAULT-<-1))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-+-1))
     (3 3 (:TYPE-PRESCRIPTION POSP))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (3 3 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (3 3 (:REWRITE UBP-LONGER-BETTER))
     (3 3
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (3 3
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (3 3 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (3 3
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (3 3
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (2 2 (:REWRITE DEFAULT-*-1))
     (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (1 1 (:REWRITE ZIP-OPEN))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P)))
(BVIF-WHEN-NOT-NIL
     (22 1 (:DEFINITION EXPT))
     (15 3 (:REWRITE BVCHOP-IDENTITY))
     (13 3 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (10 5 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (10 4 (:REWRITE DEFAULT-<-2))
     (9 3
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (9 3
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (7 1 (:DEFINITION NATP))
     (6 6 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (6 3
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (6 3
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (6 2 (:REWRITE DEFAULT-*-2))
     (6 2 (:REWRITE COMMUTATIVITY-OF-+))
     (5 5
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (4 4 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-+-1))
     (3 3 (:TYPE-PRESCRIPTION POSP))
     (3 3
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (3 3 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (2 2 (:REWRITE UBP-LONGER-BETTER))
     (2 2
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (2 2 (:REWRITE DEFAULT-*-1))
     (2 2
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (2 2
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (1 1 (:REWRITE ZIP-OPEN))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P)))
(BVIF-WHEN-NIL (22 1 (:DEFINITION EXPT))
               (15 3 (:REWRITE BVCHOP-IDENTITY))
               (13 3 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
               (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
               (10 5 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
               (10 4 (:REWRITE DEFAULT-<-2))
               (9 3
                  (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
               (9 3
                  (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
               (7 1 (:DEFINITION NATP))
               (6 6 (:TYPE-PRESCRIPTION POWER-OF-2P))
               (6 3
                  (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
               (6 3
                  (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
               (6 2 (:REWRITE DEFAULT-*-2))
               (6 2 (:REWRITE COMMUTATIVITY-OF-+))
               (5 5
                  (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
               (4 4 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
               (4 4 (:TYPE-PRESCRIPTION NATP))
               (4 4 (:REWRITE DEFAULT-<-1))
               (4 4 (:REWRITE DEFAULT-+-2))
               (4 4 (:REWRITE DEFAULT-+-1))
               (3 3 (:TYPE-PRESCRIPTION POSP))
               (3 3
                  (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
               (3 3 (:REWRITE BVCHOP-SUBST-CONSTANT))
               (2 2
                  (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
               (2 2
                  (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
               (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
               (2 2 (:REWRITE UBP-LONGER-BETTER))
               (2 2
                  (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
               (2 2 (:REWRITE DEFAULT-*-1))
               (2 2
                  (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
               (2 2
                  (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
               (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
               (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
               (1 1 (:REWRITE ZIP-OPEN))
               (1 1
                  (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
               (1 1
                  (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
               (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
               (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(BVIF-OF-0-ARG1 (28 2 (:REWRITE BVCHOP-IDENTITY))
                (16 2
                    (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
                (8 2 (:REWRITE DEFAULT-<-1))
                (2 2 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
                (2 2
                   (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
                (2 2
                   (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
                (2 2
                   (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
                (2 2 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
                (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
                (2 2 (:REWRITE UBP-LONGER-BETTER))
                (2 2
                   (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                (2 2 (:REWRITE DEFAULT-<-2))
                (2 2 (:REWRITE BVCHOP-SUBST-CONSTANT))
                (2 2
                   (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
                (2 2
                   (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
                (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(EQUAL-OF-BVIF-SAME-1
     (39 3 (:DEFINITION EXPT))
     (24 8 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (23 8
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (22 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (21 21 (:REWRITE DEFAULT-<-2))
     (21 21 (:REWRITE DEFAULT-<-1))
     (16 8 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (16 3 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (14 10 (:REWRITE UBP-LONGER-BETTER))
     (11 11 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (9 3 (:REWRITE DEFAULT-*-2))
     (9 3 (:REWRITE COMMUTATIVITY-OF-+))
     (8 8 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (8 8 (:TYPE-PRESCRIPTION POSP))
     (8 8
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (8 8
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (8 8
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (7 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (6 6 (:REWRITE DEFAULT-+-2))
     (6 6 (:REWRITE DEFAULT-+-1))
     (3 3 (:REWRITE ZIP-OPEN))
     (3 3 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (3 3
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (3 3 (:REWRITE DEFAULT-*-1))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (2 2 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(EQUAL-OF-BVIF-SAME-2
     (39 3 (:DEFINITION EXPT))
     (24 8 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (23 8
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (22 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (21 21 (:REWRITE DEFAULT-<-2))
     (21 21 (:REWRITE DEFAULT-<-1))
     (16 8 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (16 3 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (14 10 (:REWRITE UBP-LONGER-BETTER))
     (11 11 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (9 3 (:REWRITE DEFAULT-*-2))
     (9 3 (:REWRITE COMMUTATIVITY-OF-+))
     (8 8 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (8 8 (:TYPE-PRESCRIPTION POSP))
     (8 8
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (8 8
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (8 8
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (7 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (6 6 (:REWRITE DEFAULT-+-2))
     (6 6 (:REWRITE DEFAULT-+-1))
     (3 3 (:REWRITE ZIP-OPEN))
     (3 3 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (3 3
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (3 3 (:REWRITE DEFAULT-*-1))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (2 2 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(BVIF-OF-BVCHOP-ARG3
     (68 8 (:REWRITE BVCHOP-IDENTITY))
     (37 7 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (30 15 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (26 8 (:REWRITE DEFAULT-<-2))
     (25 7
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (25 7
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (16 16 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (16 8
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (16 8
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (15 15 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (15 15
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (12 1
         (:REWRITE UNSIGNED-BYTE-P-BVCHOP-SAME))
     (9 8
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (8 8 (:TYPE-PRESCRIPTION POSP))
     (8 8 (:TYPE-PRESCRIPTION NATP))
     (8 8
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (8 8
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (8 8 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (8 8 (:REWRITE UBP-LONGER-BETTER))
     (8 8 (:REWRITE DEFAULT-<-1))
     (8 8 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (7 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (7 1 (:DEFINITION NATP))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (2 2 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (1 1 (:TYPE-PRESCRIPTION NATP-OF-BVCHOP))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P)))
(BVIF-OF-BVCHOP-ARG4
     (68 8 (:REWRITE BVCHOP-IDENTITY))
     (37 7 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (30 15 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (26 8 (:REWRITE DEFAULT-<-2))
     (25 7
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (25 7
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (16 16 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (16 8
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (16 8
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (15 15 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (15 15
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (12 1
         (:REWRITE UNSIGNED-BYTE-P-BVCHOP-SAME))
     (9 8
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (8 8 (:TYPE-PRESCRIPTION POSP))
     (8 8 (:TYPE-PRESCRIPTION NATP))
     (8 8
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (8 8
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (8 8 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (8 8 (:REWRITE UBP-LONGER-BETTER))
     (8 8 (:REWRITE DEFAULT-<-1))
     (8 8 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (7 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (7 1 (:DEFINITION NATP))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (2 2 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (1 1 (:TYPE-PRESCRIPTION NATP-OF-BVCHOP))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P)))
(BVIF-EQUAL-0-0-1
     (8 1
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (4 1 (:REWRITE DEFAULT-<-1))
     (2 2
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (1 1
        (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (1 1
        (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (1 1 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE UBP-LONGER-BETTER))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (1 1
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM)))
(BVIF-EQUAL-0-0-1-ALT
     (8 1
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (4 1 (:REWRITE DEFAULT-<-1))
     (1 1
        (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (1 1
        (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (1 1 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE UBP-LONGER-BETTER))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (1 1
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM)))
(MYIF-0-1-BECOMES-BVIF (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
                       (1 1 (:REWRITE MYIF-WHEN-NIL))
                       (1 1
                          (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
                       (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(MYIF-BECOMES-BVIF-WHEN-SIZES-ARE-1
     (16 2
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (8 2 (:REWRITE DEFAULT-<-1))
     (2 2
        (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (2 2
        (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (2 2 (:REWRITE UBP-LONGER-BETTER))
     (2 2
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (2 2 (:REWRITE DEFAULT-<-2))
     (2 2
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (2 2
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(BVIF-BECOMES-MYIF
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (2 2 (:REWRITE UBP-LONGER-BETTER))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(EQUAL-OF-BVIF-CONSTANTS
     (8 8 (:TYPE-PRESCRIPTION BOOLEANP))
     (7 3 (:REWRITE BOOL-FIX-DOES-NOTHING))
     (6 2 (:REWRITE DEFAULT-<-2))
     (6 2 (:REWRITE BOOL-FIX-WHEN-BOOLEANP))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (4 4 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (4 4 (:REWRITE UBP-LONGER-BETTER))
     (3 3
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (2 2 (:REWRITE DEFAULT-<-1))
     (2 2
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (2 2
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(EQUAL-OF-BVIF-CONSTANTS2
     (3 1 (:REWRITE DEFAULT-<-2))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (2 2 (:REWRITE UBP-LONGER-BETTER))
     (2 2
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (1 1
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM)))
(TRIM-OF-BVIF (26 2 (:DEFINITION EXPT))
              (13 13 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
              (6 2 (:REWRITE DEFAULT-*-2))
              (6 2 (:REWRITE COMMUTATIVITY-OF-+))
              (5 5 (:REWRITE DEFAULT-<-2))
              (5 5 (:REWRITE DEFAULT-<-1))
              (4 4 (:REWRITE DEFAULT-+-2))
              (4 4 (:REWRITE DEFAULT-+-1))
              (4 2 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
              (2 2 (:TYPE-PRESCRIPTION POWER-OF-2P))
              (2 2 (:REWRITE ZIP-OPEN))
              (2 2
                 (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
              (2 2
                 (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
              (2 2 (:REWRITE DEFAULT-*-1)))
(BVIF-OF-MYIF-T-NIL
     (28 4 (:REWRITE BVCHOP-IDENTITY))
     (24 4 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (16 8 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (16 4 (:REWRITE DEFAULT-<-2))
     (16 4
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (16 4
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (8 8 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (8 8 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (8 8
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (8 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (4 4 (:TYPE-PRESCRIPTION POSP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (4 4
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (4 4 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (4 4 (:REWRITE UBP-LONGER-BETTER))
     (4 4
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (4 4 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (4 4
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (4 4
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 1 (:REWRITE MYIF-T-NIL))
     (2 2 (:TYPE-PRESCRIPTION BOOLEANP))
     (2 2 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(MYIF-OF-BVIF-BECOMES-BVIF-ARG1
     (25 5 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (19 5
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (15 5 (:REWRITE DEFAULT-<-2))
     (10 5
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (8 4 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (7 5
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (5 5 (:TYPE-PRESCRIPTION POSP))
     (5 5 (:TYPE-PRESCRIPTION NATP))
     (5 5 (:REWRITE DEFAULT-<-1))
     (5 5 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (5 5
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (5 5
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (4 4 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(MYIF-OF-BVIF-BECOMES-BVIF-ARG2
     (25 5 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (19 5
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (15 5 (:REWRITE DEFAULT-<-2))
     (10 5
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (8 4 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (7 5
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (5 5 (:TYPE-PRESCRIPTION POSP))
     (5 5 (:TYPE-PRESCRIPTION NATP))
     (5 5 (:REWRITE DEFAULT-<-1))
     (5 5 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (5 5
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (5 5
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (4 4 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-TRIM-CONSTANT-ARG1)
(BVIF-TRIM-CONSTANT-ARG2)
(UNSIGNED-BYTE-P-OF-BVIF-GEN2
     (28 4 (:REWRITE BVCHOP-IDENTITY))
     (20 10 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (16 4
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (15 15 (:REWRITE DEFAULT-<-2))
     (15 15 (:REWRITE DEFAULT-<-1))
     (14 2
         (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (12 4 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (10 10 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (10 10
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (9 9
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (9 9
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (9 9 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (9 9 (:REWRITE UBP-LONGER-BETTER))
     (8 8
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (8 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (4 4 (:TYPE-PRESCRIPTION POSP))
     (4 4
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (4 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (4 4
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (4 4 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(IF-BECOMES-BVIF-1
     (16 2
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (8 2 (:REWRITE DEFAULT-<-1))
     (2 2
        (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (2 2
        (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (2 2 (:REWRITE UBP-LONGER-BETTER))
     (2 2
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (2 2 (:REWRITE DEFAULT-<-2))
     (2 2
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (2 2
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(BVIF-NUMERIC-BOUND
     (13 1 (:DEFINITION EXPT))
     (9 4 (:REWRITE DEFAULT-<-2))
     (8 4 (:REWRITE DEFAULT-<-1))
     (3 1 (:REWRITE DEFAULT-*-2))
     (3 1 (:REWRITE COMMUTATIVITY-OF-+))
     (2 2
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (2 2 (:REWRITE DEFAULT-+-2))
     (2 2 (:REWRITE DEFAULT-+-1))
     (2 2 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (2 2
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (2 2
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (1 1 (:REWRITE ZIP-OPEN))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (1 1 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE UBP-LONGER-BETTER))
     (1 1 (:REWRITE DEFAULT-*-1)))
(BVIF-OF-BVIF-TIGHTEN-ARG1
     (1496 92 (:REWRITE BVCHOP-IDENTITY))
     (616 108
          (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (408 24 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (260 20 (:DEFINITION EXPT))
     (218 58
          (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (207 143 (:REWRITE DEFAULT-<-1))
     (192 192
          (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (170 58 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (154 18
          (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (148 74 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (143 143 (:REWRITE DEFAULT-<-2))
     (108 108
          (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (108 108
          (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (108 108 (:REWRITE UBP-LONGER-BETTER))
     (92 92 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (90 90 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (90 72
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (74 74
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (72 72 (:TYPE-PRESCRIPTION POSP))
     (72 72
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (60 20 (:REWRITE DEFAULT-*-2))
     (60 20 (:REWRITE COMMUTATIVITY-OF-+))
     (58 58
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (40 40 (:REWRITE DEFAULT-+-2))
     (40 40 (:REWRITE DEFAULT-+-1))
     (32 16 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (26 18 (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP))
     (22 22
         (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (20 20 (:REWRITE ZIP-OPEN))
     (20 20
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (20 20 (:REWRITE DEFAULT-*-1))
     (20 20
         (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (20 20
         (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (16 16 (:TYPE-PRESCRIPTION NATP))
     (16 16
         (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (16 16 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (4 4 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (4 4 (:REWRITE BVCHOP-BOUND))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-OF-BVIF-TIGHTEN-ARG2
     (1496 92 (:REWRITE BVCHOP-IDENTITY))
     (616 108
          (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (408 24 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (260 20 (:DEFINITION EXPT))
     (218 58
          (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (207 143 (:REWRITE DEFAULT-<-1))
     (192 192
          (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (170 58 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (154 18
          (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (148 74 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (143 143 (:REWRITE DEFAULT-<-2))
     (108 108
          (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (108 108
          (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (108 108 (:REWRITE UBP-LONGER-BETTER))
     (92 92 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (90 90 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (90 72
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (74 74
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (72 72 (:TYPE-PRESCRIPTION POSP))
     (72 72
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (60 20 (:REWRITE DEFAULT-*-2))
     (60 20 (:REWRITE COMMUTATIVITY-OF-+))
     (58 58
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (40 40 (:REWRITE DEFAULT-+-2))
     (40 40 (:REWRITE DEFAULT-+-1))
     (32 16 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (26 18 (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP))
     (22 22
         (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (20 20 (:REWRITE ZIP-OPEN))
     (20 20
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (20 20 (:REWRITE DEFAULT-*-1))
     (20 20
         (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (20 20
         (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (16 16 (:TYPE-PRESCRIPTION NATP))
     (16 16
         (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (16 16 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (4 4 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (4 4 (:REWRITE BVCHOP-BOUND))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-SAME-TESTS-AND-VALS
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (26 8 (:REWRITE DEFAULT-<-2))
     (24 12 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (22 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 1 (:DEFINITION EXPT))
     (13 13 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 12
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (8 8 (:REWRITE DEFAULT-<-1))
     (7 7 (:TYPE-PRESCRIPTION NATP))
     (7 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (7 1 (:DEFINITION NATP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (6 2 (:REWRITE DEFAULT-*-2))
     (6 2 (:REWRITE COMMUTATIVITY-OF-+))
     (4 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-+-1))
     (2 2 (:REWRITE DEFAULT-*-1))
     (2 2 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (1 1 (:REWRITE ZIP-OPEN))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (1 1 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(BVIF-SAME-TESTS-AND-VALS2
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (22 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (7 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-SAME-TESTS
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (22 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (7 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-SAME-TESTS2
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (22 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (7 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-TEST-TEST2-TEST
     (70 10 (:REWRITE BVCHOP-IDENTITY))
     (60 10 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (40 10 (:REWRITE DEFAULT-<-2))
     (40 10
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (37 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (34 17 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (20 20 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (17 17 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (17 17
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (16 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (10 10 (:TYPE-PRESCRIPTION POSP))
     (10 10 (:TYPE-PRESCRIPTION NATP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (10 10 (:REWRITE UBP-LONGER-BETTER))
     (10 10
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (10 10 (:REWRITE DEFAULT-<-1))
     (10 10 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (10 10
         (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (10 10
         (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (5 5 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-TEST-TEST2-TEST-ALT
     (70 10 (:REWRITE BVCHOP-IDENTITY))
     (60 10 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (40 10 (:REWRITE DEFAULT-<-2))
     (40 10
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (37 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (34 17 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (20 20 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (17 17 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (17 17
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (16 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (10 10 (:TYPE-PRESCRIPTION POSP))
     (10 10 (:TYPE-PRESCRIPTION NATP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (10 10 (:REWRITE UBP-LONGER-BETTER))
     (10 10
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (10 10 (:REWRITE DEFAULT-<-1))
     (10 10 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (10 10
         (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (10 10
         (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (5 5 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-TEST-TEST2-TEST-ALT2
     (70 10 (:REWRITE BVCHOP-IDENTITY))
     (60 10 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (40 10 (:REWRITE DEFAULT-<-2))
     (40 10
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (37 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (34 17 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (20 20 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (17 17 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (17 17
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (16 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (10 10 (:TYPE-PRESCRIPTION POSP))
     (10 10 (:TYPE-PRESCRIPTION NATP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (10 10 (:REWRITE UBP-LONGER-BETTER))
     (10 10
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (10 10 (:REWRITE DEFAULT-<-1))
     (10 10 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (10 10
         (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (10 10
         (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (5 5 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-TEST-TEST2-TEST-ALT3
     (70 10 (:REWRITE BVCHOP-IDENTITY))
     (60 10 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (40 10 (:REWRITE DEFAULT-<-2))
     (40 10
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (37 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (34 17 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (20 20 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (20 10
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (17 17 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (17 17
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (16 10
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (10 10 (:TYPE-PRESCRIPTION POSP))
     (10 10 (:TYPE-PRESCRIPTION NATP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (10 10
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (10 10 (:REWRITE UBP-LONGER-BETTER))
     (10 10
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (10 10 (:REWRITE DEFAULT-<-1))
     (10 10 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (10 10
         (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (10 10
         (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (5 5 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(<-OF-BVIF-CONSTANTS-FALSE
     (44 2 (:DEFINITION EXPT))
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (35 13 (:REWRITE DEFAULT-<-2))
     (28 14 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (26 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (24 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 13 (:REWRITE DEFAULT-<-1))
     (16 16 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (14 14
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (14 2 (:DEFINITION NATP))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (12 4 (:REWRITE DEFAULT-*-2))
     (12 4 (:REWRITE COMMUTATIVITY-OF-+))
     (9 9
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (9 9
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (9 9
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 8 (:TYPE-PRESCRIPTION NATP))
     (8 8 (:REWRITE DEFAULT-+-2))
     (8 8 (:REWRITE DEFAULT-+-1))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (4 4 (:REWRITE DEFAULT-*-1))
     (4 4 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (4 2 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (2 2 (:REWRITE ZIP-OPEN))
     (2 2
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (2 2
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (2 2 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(<-OF-BVIF-CONSTANTS-TRUE
     (44 2 (:DEFINITION EXPT))
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (35 13 (:REWRITE DEFAULT-<-2))
     (28 14 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (26 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (24 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 13 (:REWRITE DEFAULT-<-1))
     (16 16 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (14 14
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (14 2 (:DEFINITION NATP))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (12 4 (:REWRITE DEFAULT-*-2))
     (12 4 (:REWRITE COMMUTATIVITY-OF-+))
     (9 9
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (9 9
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (9 9
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 8 (:TYPE-PRESCRIPTION NATP))
     (8 8 (:REWRITE DEFAULT-+-2))
     (8 8 (:REWRITE DEFAULT-+-1))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (4 4 (:REWRITE DEFAULT-*-1))
     (4 4 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (4 2 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (2 2 (:REWRITE ZIP-OPEN))
     (2 2
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (2 2
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (2 2 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(BVIF-OF-BVIF-SAME-1
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-OF-BVIF-SAME-2
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-OF-BVIF-SAME-3
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-OF-BVIF-SAME-4
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(UNSIGNED-BYTE-P-OF-BVIF
     (14 2 (:REWRITE BVCHOP-IDENTITY))
     (8 2
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (6 3 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (6 2 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (4 2
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (3 3 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (3 3 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (3 3 (:REWRITE UBP-LONGER-BETTER))
     (3 3
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE DEFAULT-<-2))
     (3 3 (:REWRITE DEFAULT-<-1))
     (2 2 (:TYPE-PRESCRIPTION POSP))
     (2 2
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (2 2
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (2 2
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (2 2 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (1 1
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(UNSIGNED-BYTE-P-OF-BVIF-GEN
     (28 4 (:REWRITE BVCHOP-IDENTITY))
     (20 10 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (16 4
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (15 15 (:REWRITE DEFAULT-<-2))
     (15 15 (:REWRITE DEFAULT-<-1))
     (14 2
         (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (12 4 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (10 10 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (10 10
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (9 9
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (9 9
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (9 9 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (9 9 (:REWRITE UBP-LONGER-BETTER))
     (8 8
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (8 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (4 4 (:TYPE-PRESCRIPTION POSP))
     (4 4
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (4 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (4 4
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (4 4 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(BVIF-EQUAL-BVIF-SAME-TEST-AND-ELSE-PART
     (84 6 (:REWRITE BVCHOP-IDENTITY))
     (48 6
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (24 6 (:REWRITE DEFAULT-<-1))
     (24 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (6 6
        (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (6 6 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (6 6
        (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (6 6 (:REWRITE DEFAULT-<-2))
     (6 6
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (6 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (6 6
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (6 6
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (6 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (2 2 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (2 2 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(BVIF-EQUAL-BVIF-SAME-TEST-AND-THEN-PART
     (84 6 (:REWRITE BVCHOP-IDENTITY))
     (48 6
         (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (24 6 (:REWRITE DEFAULT-<-1))
     (24 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (6 6
        (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (6 6 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (6 6
        (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (6 6 (:REWRITE DEFAULT-<-2))
     (6 6
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (6 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (6 6
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (6 6
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (6 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (2 2 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (2 2 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(USBP-OF-BVIF (14 2 (:REWRITE BVCHOP-IDENTITY))
              (8 2
                 (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
              (6 3 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
              (6 2 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
              (4 2
                 (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
              (3 3 (:TYPE-PRESCRIPTION POWER-OF-2P))
              (3 3
                 (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
              (3 3
                 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
              (3 3 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
              (3 3 (:REWRITE UBP-LONGER-BETTER))
              (3 3
                 (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
              (3 3 (:REWRITE DEFAULT-<-2))
              (3 3 (:REWRITE DEFAULT-<-1))
              (2 2 (:TYPE-PRESCRIPTION POSP))
              (2 2
                 (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
              (2 2
                 (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
              (2 2
                 (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
              (2 2 (:REWRITE BVCHOP-SUBST-CONSTANT))
              (1 1
                 (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
              (1 1
                 (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
              (1 1
                 (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
              (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(USBP-OF-BVIF-GEN
     (28 4 (:REWRITE BVCHOP-IDENTITY))
     (20 10 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (16 4
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (15 15 (:REWRITE DEFAULT-<-2))
     (15 15 (:REWRITE DEFAULT-<-1))
     (14 2
         (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (12 4 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (10 10 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (10 10
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (9 9
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (9 9
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (9 9 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (9 9 (:REWRITE UBP-LONGER-BETTER))
     (8 8
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (8 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (4 4 (:TYPE-PRESCRIPTION POSP))
     (4 4
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (4 4
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (4 4
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (4 4 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-WHEN-SIZE-IS-NEGATIVE-LIMITED))
     (3 3
        (:REWRITE UNSIGNED-BYTE-P-FALSE-WHEN-NOT-LONGER))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP)))
(BVIF-TRIM-CONSTANT-1)
(BVIF-TRIM-CONSTANT-2)
(BVIF-OF-MYIF-1
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-2))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-1))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-OF-MYIF-2
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-2))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-1))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVCHOP-OF-MYIF
     (90 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (74 2 (:DEFINITION NATP))
     (68 4 (:REWRITE INTEGERP-OF-MYIF-STRONG))
     (54 5
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (48 24 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (44 2 (:DEFINITION EXPT))
     (35 5 (:REWRITE BVCHOP-IDENTITY))
     (34 34 (:TYPE-PRESCRIPTION MYIF))
     (30 5 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (28 28
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (27 9 (:REWRITE DEFAULT-<-1))
     (26 26 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (24 9 (:REWRITE DEFAULT-<-2))
     (20 5
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (13 7
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (12 4 (:REWRITE DEFAULT-*-2))
     (12 4 (:REWRITE COMMUTATIVITY-OF-+))
     (10 10 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (10 5
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (8 8 (:REWRITE DEFAULT-+-2))
     (8 8 (:REWRITE DEFAULT-+-1))
     (7 7 (:TYPE-PRESCRIPTION NATP))
     (7 7
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (7 7
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (7 5
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (5 5 (:TYPE-PRESCRIPTION POSP))
     (5 5
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (5 5
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (5 5 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (5 5 (:REWRITE UBP-LONGER-BETTER))
     (5 5 (:REWRITE MYIF-WHEN-NOT-NIL))
     (5 5 (:REWRITE MYIF-WHEN-NIL))
     (5 5
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (5 5 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (4 4 (:REWRITE DEFAULT-*-1))
     (4 4 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (4 2 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (2 2 (:REWRITE ZIP-OPEN))
     (2 2
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (2 2
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (2 2 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (1 1 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (1 1 (:REWRITE BVIF-TRIM-CONSTANT-2))
     (1 1 (:REWRITE BVIF-TRIM-CONSTANT-1))
     (1 1 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(BVIF-OF-MYIF-ARG2
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-2))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-1))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(BVIF-OF-MYIF-ARG1
     (42 6 (:REWRITE BVCHOP-IDENTITY))
     (36 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (24 6 (:REWRITE DEFAULT-<-2))
     (24 6
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (23 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (22 11 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (11 11 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (11 11
         (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (8 6
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (6 6
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (6 6 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (6 6 (:REWRITE UBP-LONGER-BETTER))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (6 6
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (6 6
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVIF-WHEN-TRUE-CHEAP))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-2))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-1))
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
(MYIF-SAME-ARG1-ARG2-WHEN-BOOLEANP
     (1 1 (:REWRITE MYIF-WHEN-NOT-NIL))
     (1 1 (:REWRITE MYIF-WHEN-NIL))
     (1 1
        (:REWRITE MYIF-OF-CONSTANT-WHEN-NOT-NIL)))
(BVIF-OF-BOOL-FIX
     (22 1 (:DEFINITION EXPT))
     (15 3 (:REWRITE BVCHOP-IDENTITY))
     (13 3 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (13 1 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (10 5 (:REWRITE INTEGERP-WHEN-POWER-OF-2P))
     (10 4 (:REWRITE DEFAULT-<-2))
     (9 3
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (9 3
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (7 1 (:DEFINITION NATP))
     (6 6 (:TYPE-PRESCRIPTION POWER-OF-2P))
     (6 3
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (6 3
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (6 2 (:REWRITE DEFAULT-*-2))
     (6 2 (:REWRITE COMMUTATIVITY-OF-+))
     (5 5
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (4 4 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4 (:TYPE-PRESCRIPTION BOOLEANP))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-+-1))
     (3 3 (:TYPE-PRESCRIPTION POSP))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-2))
     (3 3 (:REWRITE BVIF-TRIM-CONSTANT-1))
     (3 3
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (3 3 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (3 1 (:REWRITE BOOL-FIX-WHEN-BOOLEANP))
     (3 1 (:REWRITE BOOL-FIX-DOES-NOTHING))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-WHEN-<=-CHEAP))
     (2 2
        (:REWRITE UNSIGNED-BYTE-P-FROM-BOUNDS))
     (2 2 (:REWRITE UNSIGNED-BYTE-P-FROM-BOUND))
     (2 2 (:REWRITE UBP-LONGER-BETTER))
     (2 2
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (2 2 (:REWRITE DEFAULT-*-1))
     (2 2
        (:REWRITE ACL2-NUMBERP-WHEN-UNSIGNED-BYTE-P))
     (2 2
        (:REWRITE ACL2-NUMBERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (2 2 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (2 1 (:REWRITE NATP-WHEN-POWER-OF-2P))
     (1 1 (:REWRITE ZIP-OPEN))
     (1 1
        (:REWRITE SIZE-NON-NEGATIVE-WHEN-UNSIGNED-BYTE-P-FREE))
     (1 1
        (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (1 1 (:REWRITE NATP-WHEN-UNSIGNED-BYTE-P))
     (1 1
        (:REWRITE EQUAL-OF-CONSTANT-AND-BVIF-OF-CONSTANT-AND-CONSTANT))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
