(BVMINUS)
(INTEGERP-OF-BVMINUS)
(NATP-OF-BVMINUS)
(BVMINUS-WHEN-ARG2-IS-NOT-AN-INTEGER
     (88 4 (:DEFINITION EXPT))
     (54 4 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (50 8 (:DEFINITION NATP))
     (42 42 (:TYPE-PRESCRIPTION IFIX))
     (24 8 (:REWRITE DEFAULT-*-2))
     (22 17 (:REWRITE DEFAULT-<-2))
     (21 17 (:REWRITE DEFAULT-<-1))
     (21 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (20 20 (:TYPE-PRESCRIPTION NATP))
     (20 4
         (:LINEAR BVCHOP-UPPER-BOUND-LINEAR-STRONG))
     (18 18 (:REWRITE DEFAULT-+-2))
     (18 18 (:REWRITE DEFAULT-+-1))
     (18 6 (:REWRITE BVCHOP-IDENTITY))
     (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (12 6
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (12 6
         (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (10 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (10 6
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (8 8 (:REWRITE DEFAULT-*-1))
     (8 8 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (6 6 (:TYPE-PRESCRIPTION POSP))
     (6 6
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (5 5
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (4 4 (:REWRITE ZIP-OPEN))
     (2 2
        (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (2 2 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (2 2
        (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
     (1 1
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (1 1 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(BVMINUS-WHEN-SIZE-IS-NOT-POSITIVE)
(BVMINUS-WHEN-SIZE-IS-NOT-INTEGERP)
(BVMINUS-SAME)
(BVMINUS-SUBST-VALUE-ARG-2
     (554 26 (:DEFINITION EXPT))
     (150 50 (:REWRITE DEFAULT-*-2))
     (145 49 (:REWRITE BVCHOP-IDENTITY))
     (141 112 (:REWRITE DEFAULT-<-2))
     (138 138 (:TYPE-PRESCRIPTION NATP))
     (134 39 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (124 112 (:REWRITE DEFAULT-<-1))
     (121 114 (:REWRITE DEFAULT-+-1))
     (116 114 (:REWRITE DEFAULT-+-2))
     (116 24
          (:LINEAR BVCHOP-UPPER-BOUND-LINEAR-STRONG))
     (95 95 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (94 47
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (84 84 (:TYPE-PRESCRIPTION IFIX))
     (80 42
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (74 39
         (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (64 39
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (55 11 (:REWRITE BVCHOP-SUM-DROP-BVCHOP))
     (50 50 (:REWRITE DEFAULT-*-1))
     (49 49 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (48 48 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (47 47 (:TYPE-PRESCRIPTION POSP))
     (39 39
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (29 29
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (26 26 (:REWRITE ZIP-OPEN))
     (23 23
         (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (23 23 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (23 23
         (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
     (20 20 (:TYPE-PRESCRIPTION FIX))
     (8 8 (:REWRITE DEFAULT-UNARY-MINUS))
     (7 3 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (4 1
        (:REWRITE UNSIGNED-BYTE-P-BVCHOP-SAME))
     (3 3
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (3 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (1 1
        (:REWRITE BVCHOP-SUM-DROP-BVCHOP-ALT)))
(BVMINUS-SUBST-VALUE-ARG-3
     (1079 83 (:DEFINITION EXPT))
     (435 271 (:REWRITE DEFAULT-+-2))
     (413 271 (:REWRITE DEFAULT-+-1))
     (249 83 (:REWRITE DEFAULT-*-2))
     (232 232 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (214 164 (:REWRITE DEFAULT-<-1))
     (190 164 (:REWRITE DEFAULT-<-2))
     (185 185 (:TYPE-PRESCRIPTION POSP))
     (182 70 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (126 42
          (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (97 33 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (93 14 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (83 83 (:REWRITE ZIP-OPEN))
     (83 83 (:REWRITE DEFAULT-*-1))
     (70 70
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (70 70
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (70 70
         (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (70 70
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (69 46 (:REWRITE DEFAULT-UNARY-MINUS))
     (38 14 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (34 34
         (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (14 14
         (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (14 14 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (14 14
         (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
     (11 11 (:REWRITE FOLD-CONSTS-IN-+))
     (7 7 (:TYPE-PRESCRIPTION NATP))
     (2 2 (:REWRITE BVCHOP-NUMERIC-BOUND))
     (2 2 (:REWRITE BVCHOP-BOUND)))
(BVMINUS-OF-0 (88 4 (:DEFINITION EXPT))
              (38 8 (:DEFINITION NATP))
              (38 4 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
              (24 8 (:REWRITE DEFAULT-*-2))
              (22 22 (:TYPE-PRESCRIPTION IFIX))
              (22 17 (:REWRITE DEFAULT-<-2))
              (21 6 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
              (20 20 (:TYPE-PRESCRIPTION NATP))
              (20 4
                  (:LINEAR BVCHOP-UPPER-BOUND-LINEAR-STRONG))
              (19 17 (:REWRITE DEFAULT-<-1))
              (18 18 (:REWRITE DEFAULT-+-2))
              (18 18 (:REWRITE DEFAULT-+-1))
              (18 6 (:REWRITE BVCHOP-IDENTITY))
              (12 12 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
              (12 6
                  (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
              (12 6
                  (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
              (12 6
                  (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
              (8 8 (:REWRITE DEFAULT-*-1))
              (8 8 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
              (8 6
                 (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
              (8 6
                 (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
              (6 6 (:TYPE-PRESCRIPTION POSP))
              (6 6
                 (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
              (6 6 (:REWRITE BVCHOP-SUBST-CONSTANT))
              (5 5
                 (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
              (4 4 (:REWRITE ZIP-OPEN))
              (2 2
                 (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
              (2 2 (:REWRITE BVCHOP-SUM-SUBST-CONST))
              (2 2
                 (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
              (1 1
                 (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
              (1 1 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(EQUAL-OF-0-AND-BVMINUS
     (198 66 (:REWRITE BVCHOP-IDENTITY))
     (139 139
          (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (81 17 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (61 61
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (55 55
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (55 55 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (55 55
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (55 55
         (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (55 55
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (48 16 (:DEFINITION NATP))
     (37 27 (:REWRITE DEFAULT-+-2))
     (36 27 (:REWRITE DEFAULT-+-1))
     (34 34 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (22 19 (:REWRITE DEFAULT-<-1))
     (19 19 (:REWRITE DEFAULT-<-2))
     (19 12 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (16 16 (:TYPE-PRESCRIPTION NATP))
     (15 15
         (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (9 9 (:REWRITE DEFAULT-UNARY-MINUS))
     (1 1
        (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (1 1 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (1 1 (:REWRITE BVCHOP-NUMERIC-BOUND))
     (1 1
        (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT)))
(UNSIGNED-BYTE-P-OF-BVMINUS-GEN-BETTER
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1))
     (3 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (3 1 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (3 1 (:REWRITE BVCHOP-IDENTITY))
     (2 1
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (1 1 (:TYPE-PRESCRIPTION POSP))
     (1 1 (:REWRITE DEFAULT-UNARY-MINUS))
     (1 1 (:REWRITE DEFAULT-+-2))
     (1 1 (:REWRITE DEFAULT-+-1))
     (1 1
        (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (1 1
        (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (1 1
        (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (1 1
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER-CHEAP))
     (1 1
        (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (1 1
        (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (1 1 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (1 1 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (1 1
        (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT)))
(BVMINUS-OF-BVCHOP-ARG2
     (203 174 (:REWRITE DEFAULT-<-2))
     (198 198 (:TYPE-PRESCRIPTION NATP))
     (194 62 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (187 174 (:REWRITE DEFAULT-<-1))
     (180 60 (:REWRITE DEFAULT-*-2))
     (172 57 (:REWRITE BVCHOP-IDENTITY))
     (147 31
          (:LINEAR BVCHOP-UPPER-BOUND-LINEAR-STRONG))
     (143 42 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (140 133 (:REWRITE DEFAULT-+-1))
     (135 133 (:REWRITE DEFAULT-+-2))
     (114 114
          (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (84 84 (:TYPE-PRESCRIPTION IFIX))
     (84 44
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (80 42
         (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (67 42
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (60 60 (:REWRITE DEFAULT-*-1))
     (57 57 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (55 11 (:REWRITE BVCHOP-SUM-DROP-BVCHOP))
     (49 49 (:TYPE-PRESCRIPTION POSP))
     (42 42
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (32 32 (:REWRITE ZIP-OPEN))
     (30 30
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (23 23
         (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (23 23 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (23 23
         (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
     (20 20 (:TYPE-PRESCRIPTION FIX))
     (8 8 (:REWRITE DEFAULT-UNARY-MINUS))
     (8 4 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (4 4
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (4 1 (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP))
     (3 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY)))
(BVMINUS-OF-BVCHOP-ARG2-SAME
     (554 26 (:DEFINITION EXPT))
     (150 50 (:REWRITE DEFAULT-*-2))
     (145 49 (:REWRITE BVCHOP-IDENTITY))
     (141 112 (:REWRITE DEFAULT-<-2))
     (138 138 (:TYPE-PRESCRIPTION NATP))
     (134 39 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (124 112 (:REWRITE DEFAULT-<-1))
     (121 114 (:REWRITE DEFAULT-+-1))
     (116 114 (:REWRITE DEFAULT-+-2))
     (116 24
          (:LINEAR BVCHOP-UPPER-BOUND-LINEAR-STRONG))
     (95 95 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (94 47
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-POSP))
     (84 84 (:TYPE-PRESCRIPTION IFIX))
     (80 42
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (74 39
         (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (64 39
         (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (55 11 (:REWRITE BVCHOP-SUM-DROP-BVCHOP))
     (50 50 (:REWRITE DEFAULT-*-1))
     (49 49 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (48 48 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR-2))
     (47 47 (:TYPE-PRESCRIPTION POSP))
     (39 39
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (29 29
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (26 26 (:REWRITE ZIP-OPEN))
     (23 23
         (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (23 23 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (23 23
         (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
     (20 20 (:TYPE-PRESCRIPTION FIX))
     (8 8 (:REWRITE DEFAULT-UNARY-MINUS))
     (7 3 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (4 1
        (:REWRITE UNSIGNED-BYTE-P-BVCHOP-SAME))
     (3 3
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (3 1
        (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (1 1
        (:REWRITE BVCHOP-SUM-DROP-BVCHOP-ALT)))
(BVMINUS-OF-BVCHOP-ARG3
     (3173 446 (:REWRITE BVCHOP-IDENTITY))
     (2865 81 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (2142 39 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (2106 162 (:DEFINITION EXPT))
     (962 324 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (859 859
          (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (580 419 (:REWRITE DEFAULT-+-2))
     (579 549 (:REWRITE DEFAULT-<-1))
     (549 549 (:REWRITE DEFAULT-<-2))
     (503 324
          (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (486 162 (:REWRITE DEFAULT-*-2))
     (430 419 (:REWRITE DEFAULT-+-1))
     (395 395 (:TYPE-PRESCRIPTION POSP))
     (337 337
          (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (324 324
          (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (324 324
          (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (312 312 (:TYPE-PRESCRIPTION IFIX))
     (162 162 (:REWRITE ZIP-OPEN))
     (162 162 (:REWRITE DEFAULT-*-1))
     (154 154
          (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (154 154 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (154 154
          (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
     (98 98 (:TYPE-PRESCRIPTION NATP))
     (94 94 (:TYPE-PRESCRIPTION FIX))
     (13 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (12 4
         (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (12 4 (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP))
     (7 7
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE))
     (7 3 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE)))
(BVMINUS-OF-BVCHOP-ARG3-SAME
     (1109 41 (:REWRITE UNSIGNED-BYTE-P-OF-0-ARG1))
     (962 74 (:DEFINITION EXPT))
     (869 37 (:LINEAR <=-OF-BVCHOP-SAME-LINEAR))
     (272 199 (:REWRITE DEFAULT-+-2))
     (268 94 (:REWRITE BVCHOP-WITH-N-NEGATIVE))
     (222 74 (:REWRITE DEFAULT-*-2))
     (210 199 (:REWRITE DEFAULT-+-1))
     (204 189 (:REWRITE DEFAULT-<-1))
     (189 189 (:REWRITE DEFAULT-<-2))
     (168 168 (:REWRITE BVCHOP-SUBST-CONSTANT))
     (159 94
          (:REWRITE BVCHOP-WHEN-I-IS-NOT-AN-INTEGER))
     (148 148 (:TYPE-PRESCRIPTION IFIX))
     (123 123 (:TYPE-PRESCRIPTION POSP))
     (95 95
         (:REWRITE BVCHOP-WHEN-SIZE-IS-NOT-NATP))
     (94 94
         (:REWRITE BVCHOP-WITH-N-NOT-AN-INTEGER))
     (94 94
         (:REWRITE BVCHOP-WHEN-NOT-NATP-ARG1-CHEAP))
     (74 74 (:REWRITE ZIP-OPEN))
     (74 74 (:REWRITE DEFAULT-*-1))
     (64 64
         (:REWRITE BVCHOP-SUM-SUBST-CONST-ARG2))
     (64 64 (:REWRITE BVCHOP-SUM-SUBST-CONST))
     (64 64
         (:REWRITE BVCHOP-CHOP-LEADING-CONSTANT))
     (46 46 (:TYPE-PRESCRIPTION FIX))
     (35 35 (:TYPE-PRESCRIPTION NATP))
     (13 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (12 4
         (:REWRITE UNSIGNED-BYTE-P-OF-BVCHOP-WHEN-ALREADY))
     (9 5 (:REWRITE BVCHOP-IMPOSSIBLE-VALUE))
     (5 5
        (:REWRITE EQUAL-CONSTANT-WHEN-BVCHOP-EQUAL-CONSTANT-FALSE)))
