(BVCAT-OF-BITNOT-AND-BITNOT
     (10 4
         (:REWRITE BITXOR-WHEN-Y-IS-NOT-AN-INTEGER))
     (8 3
        (:REWRITE BVCAT-WHEN-LOWVAL-IS-NOT-AN-INTEGER))
     (8 3
        (:REWRITE BVCAT-WHEN-HIGHVAL-IS-NOT-AN-INTEGER))
     (5 4
        (:REWRITE BITXOR-WHEN-CONSTANT-IS-NOT-USB-ARG1))
     (4 4 (:TYPE-PRESCRIPTION BITXOR-TYPE))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-FREE))
     (4 4
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (4 4
        (:REWRITE BITXOR-WHEN-X-IS-NOT-AN-INTEGER))
     (4 4
        (:REWRITE BITXOR-WHEN-CONSTANT-IS-NOT-USB-ARG2))
     (4 4
        (:REWRITE BITXOR-SUBST-ARG2-ONE-VERSION))
     (4 4 (:REWRITE BITXOR-SUBST-ARG2))
     (4 4
        (:REWRITE BITXOR-SUBST-ARG1-ONE-VERSION))
     (4 4 (:REWRITE BITXOR-SUBST-ARG1))
     (4 4 (:REWRITE BITXOR-COMMUTATIVE-ALT))
     (3 3
        (:REWRITE BVCAT-WHEN-LOWSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-HIGHSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-ARG2-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG2))
     (3 3 (:REWRITE BVCAT-TIGHTEN-UPPER-SIZE))
     (3 3 (:REWRITE BVCAT-TIGHTEN-LOW-ARG))
     (3 3 (:REWRITE BVCAT-TIGHTEN-HIGH-ARG))
     (3 3 (:REWRITE BVCAT-SUBST-1))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG2))
     (2 2 (:REWRITE BVNOT-WHEN-NOT-NATP-SIZE))
     (1 1 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P)))
(BVCAT-OF-BVNOT-AND-BITNOT
     (8 3
        (:REWRITE BVCAT-WHEN-LOWVAL-IS-NOT-AN-INTEGER))
     (8 3
        (:REWRITE BVCAT-WHEN-HIGHVAL-IS-NOT-AN-INTEGER))
     (5 2
        (:REWRITE BITXOR-WHEN-Y-IS-NOT-AN-INTEGER))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-FREE))
     (4 4
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE BVNOT-WHEN-NOT-NATP-SIZE))
     (3 3
        (:REWRITE BVCAT-WHEN-LOWSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-HIGHSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-ARG2-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG2))
     (3 3 (:REWRITE BVCAT-TIGHTEN-UPPER-SIZE))
     (3 3 (:REWRITE BVCAT-TIGHTEN-LOW-ARG))
     (3 3 (:REWRITE BVCAT-TIGHTEN-HIGH-ARG))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG2))
     (3 2
        (:REWRITE BITXOR-WHEN-CONSTANT-IS-NOT-USB-ARG1))
     (2 2 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (2 2 (:TYPE-PRESCRIPTION BITXOR-TYPE))
     (2 2
        (:REWRITE BVNOT-WHEN-SIZE-IS-NOT-POSITIVE))
     (2 2
        (:REWRITE BVNOT-WHEN-SIZE-IS-NOT-INTEGERP))
     (2 2
        (:REWRITE BITXOR-WHEN-X-IS-NOT-AN-INTEGER))
     (2 2
        (:REWRITE BITXOR-WHEN-CONSTANT-IS-NOT-USB-ARG2))
     (2 2
        (:REWRITE BITXOR-SUBST-ARG2-ONE-VERSION))
     (2 2 (:REWRITE BITXOR-SUBST-ARG2))
     (2 2
        (:REWRITE BITXOR-SUBST-ARG1-ONE-VERSION))
     (2 2 (:REWRITE BITXOR-SUBST-ARG1))
     (2 2 (:REWRITE BITXOR-COMMUTATIVE-ALT))
     (2 1 (:REWRITE NOT-<-WHEN-SBVLT-ALT))
     (1 1
        (:REWRITE USE-<=-BOUND-TO-DROP-<=-HYP))
     (1 1 (:REWRITE NOT-<-WHEN-SBVLT))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1 (:REWRITE DEFAULT-+-2))
     (1 1 (:REWRITE DEFAULT-+-1))
     (1 1 (:REWRITE BOUND-WHEN-USB2))
     (1 1 (:REWRITE <-WHEN-BVLT))
     (1 1 (:REWRITE <-TIGHTEN-WHEN-SLICE-IS-0))
     (1 1
        (:REWRITE <-OF-CONSTANT-WHEN-UNSIGNED-BYTE-P-SIZE-PARAM)))
(BVCAT-OF-BITNOT-AND-BVNOT
     (8 3
        (:REWRITE BVCAT-WHEN-LOWVAL-IS-NOT-AN-INTEGER))
     (8 3
        (:REWRITE BVCAT-WHEN-HIGHVAL-IS-NOT-AN-INTEGER))
     (5 2
        (:REWRITE BITXOR-WHEN-Y-IS-NOT-AN-INTEGER))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-FREE))
     (4 4
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (3 3 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE DEFAULT-+-1))
     (3 3 (:REWRITE BVNOT-WHEN-NOT-NATP-SIZE))
     (3 3
        (:REWRITE BVCAT-WHEN-LOWSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-HIGHSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-ARG2-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG2))
     (3 3 (:REWRITE BVCAT-TIGHTEN-UPPER-SIZE))
     (3 3 (:REWRITE BVCAT-TIGHTEN-LOW-ARG))
     (3 3 (:REWRITE BVCAT-TIGHTEN-HIGH-ARG))
     (3 3 (:REWRITE BVCAT-SUBST-1))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG2))
     (3 2
        (:REWRITE BITXOR-WHEN-CONSTANT-IS-NOT-USB-ARG1))
     (2 2 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (2 2 (:TYPE-PRESCRIPTION BITXOR-TYPE))
     (2 2
        (:REWRITE BVNOT-WHEN-SIZE-IS-NOT-POSITIVE))
     (2 2
        (:REWRITE BVNOT-WHEN-SIZE-IS-NOT-INTEGERP))
     (2 2
        (:REWRITE BITXOR-WHEN-X-IS-NOT-AN-INTEGER))
     (2 2
        (:REWRITE BITXOR-WHEN-CONSTANT-IS-NOT-USB-ARG2))
     (2 2
        (:REWRITE BITXOR-SUBST-ARG2-ONE-VERSION))
     (2 2 (:REWRITE BITXOR-SUBST-ARG2))
     (2 2
        (:REWRITE BITXOR-SUBST-ARG1-ONE-VERSION))
     (2 2 (:REWRITE BITXOR-SUBST-ARG1))
     (2 2 (:REWRITE BITXOR-COMMUTATIVE-ALT))
     (2 1 (:REWRITE NOT-<-WHEN-SBVLT-ALT))
     (1 1
        (:REWRITE USE-<=-BOUND-TO-DROP-<=-HYP))
     (1 1 (:REWRITE NOT-<-WHEN-SBVLT))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1 (:REWRITE BOUND-WHEN-USB2))
     (1 1 (:REWRITE <-WHEN-BVLT))
     (1 1 (:REWRITE <-TIGHTEN-WHEN-SLICE-IS-0))
     (1 1
        (:REWRITE <-OF-CONSTANT-WHEN-UNSIGNED-BYTE-P-SIZE-PARAM)))
(BVCAT-OF-BVNOT-AND-BVNOT
     (8 3
        (:REWRITE BVCAT-WHEN-LOWVAL-IS-NOT-AN-INTEGER))
     (8 3
        (:REWRITE BVCAT-WHEN-HIGHVAL-IS-NOT-AN-INTEGER))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (4 4
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-FREE))
     (4 4
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (4 4
        (:REWRITE BVNOT-WHEN-SIZE-IS-NOT-POSITIVE))
     (4 4
        (:REWRITE BVNOT-WHEN-SIZE-IS-NOT-INTEGERP))
     (4 4 (:REWRITE BVNOT-WHEN-NOT-NATP-SIZE))
     (4 2 (:REWRITE NOT-<-WHEN-SBVLT-ALT))
     (3 3 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE DEFAULT-+-1))
     (3 3
        (:REWRITE BVCAT-WHEN-LOWSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-HIGHSIZE-IS-NOT-POSP))
     (3 3
        (:REWRITE BVCAT-WHEN-ARG2-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-TRIM-CONSTANT-ARG2))
     (3 3 (:REWRITE BVCAT-TIGHTEN-UPPER-SIZE))
     (3 3 (:REWRITE BVCAT-TIGHTEN-LOW-ARG))
     (3 3 (:REWRITE BVCAT-TIGHTEN-HIGH-ARG))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG4))
     (3 3 (:REWRITE BVCAT-FIX-CONSTANT-ARG2))
     (2 2 (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
     (2 2
        (:REWRITE USE-<=-BOUND-TO-DROP-<=-HYP))
     (2 2 (:REWRITE NOT-<-WHEN-SBVLT))
     (2 2 (:REWRITE DEFAULT-<-2))
     (2 2 (:REWRITE DEFAULT-<-1))
     (2 2 (:REWRITE BOUND-WHEN-USB2))
     (2 2 (:REWRITE <-WHEN-BVLT))
     (2 2 (:REWRITE <-TIGHTEN-WHEN-SLICE-IS-0))
     (2 2
        (:REWRITE <-OF-CONSTANT-WHEN-UNSIGNED-BYTE-P-SIZE-PARAM)))
(BVXOR-OF-LEFTROTATE-TRIM-8-32-ARG2)
(BVXOR-OF-LEFTROTATE-TRIM-8-32-ARG1)
(BVXOR-OF-LEFTROTATE32-TRIM-8-ARG2)
(BVXOR-OF-LEFTROTATE32-TRIM-8-ARG1)
(LEFTROTATE-32-OF-BVXOR-32-WHEN-CONSTANT
     (8 3
        (:REWRITE BVXOR-WHEN-Y-IS-NOT-AN-INTEGER))
     (8 3
        (:REWRITE BVXOR-WHEN-X-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVXOR-WITH-SMALLER-ARG-2))
     (3 3 (:REWRITE BVXOR-WITH-SMALLER-ARG-1))
     (3 3
        (:REWRITE BVXOR-WHEN-SIZE-IS-NOT-POSITIVE))
     (3 3
        (:REWRITE BVXOR-WHEN-SIZE-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVXOR-TRIM-ARG2))
     (3 3 (:REWRITE BVXOR-TRIM-ARG1))
     (3 3 (:REWRITE BVXOR-TIGHTEN))
     (3 3 (:REWRITE BVXOR-SUBST-ARG3))
     (3 3 (:REWRITE BVXOR-SUBST-ARG2))
     (3 3 (:REWRITE BVXOR-COMMUTATIVE-ALT))
     (2 2
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (2 2
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-FREE))
     (2 2
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM)))
(LEFTROTATE32-OF-BVXOR-32-WHEN-CONSTANT
     (8 3
        (:REWRITE BVXOR-WHEN-Y-IS-NOT-AN-INTEGER))
     (8 3
        (:REWRITE BVXOR-WHEN-X-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVXOR-WITH-SMALLER-ARG-2))
     (3 3 (:REWRITE BVXOR-WITH-SMALLER-ARG-1))
     (3 3
        (:REWRITE BVXOR-WHEN-SIZE-IS-NOT-POSITIVE))
     (3 3
        (:REWRITE BVXOR-WHEN-SIZE-IS-NOT-AN-INTEGER))
     (3 3 (:REWRITE BVXOR-TRIM-ARG2))
     (3 3 (:REWRITE BVXOR-TRIM-ARG1))
     (3 3 (:REWRITE BVXOR-TIGHTEN))
     (3 3 (:REWRITE BVXOR-SUBST-ARG3))
     (3 3 (:REWRITE BVXOR-SUBST-ARG2))
     (3 3 (:REWRITE BVXOR-COMMUTATIVE-ALT))
     (2 2
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-SIZE-ARG))
     (2 2
        (:REWRITE INTEGERP-WHEN-UNSIGNED-BYTE-P-FREE))
     (2 2
        (:REWRITE INTEGERP-FROM-UNSIGNED-BYTE-P-SIZE-PARAM))
     (1 1
        (:REWRITE LEFTROTATE-32-OF-BVXOR-32-WHEN-CONSTANT)))
(BVCHOP-OF-1-WHEN-BITP)
(BITP-WHEN-EQUAL-OF-GETBIT-1)
(BITP-WHEN-EQUAL-OF-GETBIT-2)
(BITP-WHEN-EQUAL-OF-BITXOR-1)
(BITP-WHEN-EQUAL-OF-BITXOR-2)
(BITP-WHEN-EQUAL-1)
(BITP-WHEN-EQUAL-2)
