include ../../../../../../Makefile-generic

# Pasted in from "make dependencies":



bi-phi-m.cert: bi-phi-m.lisp
# bi-phi-m.cert: $(ACL2_SYSTEM_BOOKS)/data-structures/list-defuns.cert
# bi-phi-m.cert: $(ACL2_SYSTEM_BOOKS)/data-structures/list-defthms.cert
# bi-phi-m.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/bind-free/top.cert






