DIRS =	symbol-fns \
	util \
	adviser \
	nary \
	lists \
	osets \
	syntax \
	bags \
	alists \
	records \
	paths \
	maps \
	dtrees \
	defpun \
	defstructure \
	super-ihs \
	gacc \
	gensym \
        generalize \
	quantification \
	termination

include ../Makefile-subdirs
