(C$::COMPILE-RUN-READ-IENV-C)
(C$::MAYBE-MSGP-OF-COMPILE-RUN-READ-IENV-C.ER?
 (16 16 (:REWRITE MSGP-WHEN-MEMBER-EQUAL-OF-MSG-LISTP))
 )
(C$::STRING-LISTP-OF-COMPILE-RUN-READ-IENV-C.LINES)
(C$::IENV-C-OUT-TO-IENV
 (10798 10798 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (10 10 (:REWRITE-QUOTED-CONSTANT C::STANDARD-FIX-UNDER-STANDARD-EQUIV))
 )
(C$::MAYBE-MSGP-OF-IENV-C-OUT-TO-IENV.ER?
 (94 94 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (93 93 (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
 (6 6 (:REWRITE MSGP-WHEN-MEMBER-EQUAL-OF-MSG-LISTP))
 (2 2 (:REWRITE-QUOTED-CONSTANT C::STANDARD-FIX-UNDER-STANDARD-EQUIV))
 )
(C$::IENVP-OF-IENV-C-OUT-TO-IENV.IENV
 (4 4 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 (3 3 (:LINEAR LEN-POSITIVE-WHEN-CONSP-LINEAR-CHEAP))
 (2 2 (:REWRITE-QUOTED-CONSTANT C::STANDARD-FIX-UNDER-STANDARD-EQUIV))
 )
(C$::INFER-IENV-PROG)
(C$::MAYBE-MSGP-OF-INFER-IENV-PROG.ER?
 (5 1 (:REWRITE MAYBE-MSGP-WHEN-MSGP))
 (2 2 (:TYPE-PRESCRIPTION MSGP))
 (2 2 (:REWRITE MSGP-WHEN-MEMBER-EQUAL-OF-MSG-LISTP))
 )
(C$::IENVP-OF-INFER-IENV-PROG.IENV)
(C$::INFER-IENV-PROCESS-INPUTS-AND-GEN-EVENT)
(C$::MAYBE-MSGP-OF-INFER-IENV-PROCESS-INPUTS-AND-GEN-EVENT.ER?
 (12 12 (:REWRITE MSGP-WHEN-MEMBER-EQUAL-OF-MSG-LISTP))
 )
(C$::PSEUDO-EVENT-FORMP-OF-INFER-IENV-PROCESS-INPUTS-AND-GEN-EVENT.EVENT)
(C$::INFER-IENV-FN)
(C$::PSEUDO-EVENT-FORMP-OF-INFER-IENV-FN.EVENT)
