(GACC::WORD-SIZE)
(GACC::MAX-OFFSET (7 7
                     (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
                  (5 4 (:REWRITE DEFAULT-<-1))
                  (4 4 (:REWRITE DEFAULT-<-2))
                  (2 2 (:REWRITE DEFAULT-+-2))
                  (2 2 (:REWRITE DEFAULT-+-1))
                  (1 1
                     (:REWRITE INTEGERP-*-CONSTANT-MEANS-1)))
(GACC::MAX-OFFSET-TYPE-PRESCRIPTION-TEST)
(GACC::NON-NEGATIVE-INTEGERP-MAX-OFFSET)
(GACC::MAX-OFFSET-OF-NON-POSITIVE
     (3 2 (:REWRITE DEFAULT-<-2))
     (2 2
        (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
     (2 2 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (2 2 (:REWRITE DEFAULT-<-1))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1)))
(GACC::MAX-OFFSET-OF-NON-INTEGER
     (6 1
        (:REWRITE GACC::MAX-OFFSET-OF-NON-POSITIVE))
     (2 1 (:REWRITE DEFAULT-<-2))
     (1 1
        (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
     (1 1 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (1 1 (:REWRITE DEFAULT-<-1)))
(GACC::MAX-OFFSET-REWRITES-TO-FLOOR
     (393 13 (:REWRITE FLOOR-=-X/Y . 3))
     (333 97
          (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (183 14 (:REWRITE FLOOR-OF-INTEGER-BY-1))
     (179 161 (:REWRITE DEFAULT-<-2))
     (174 161 (:REWRITE DEFAULT-<-1))
     (163 13 (:REWRITE FLOOR-=-X/Y . 2))
     (161 129 (:REWRITE DEFAULT-+-2))
     (153 107 (:REWRITE DEFAULT-*-2))
     (145 145
          (:TYPE-PRESCRIPTION FLOOR-TYPE-1 . 2))
     (145 145
          (:TYPE-PRESCRIPTION FLOOR-TYPE-1 . 1))
     (136 129 (:REWRITE DEFAULT-+-1))
     (132 86
          (:REWRITE INTEGERP-SUM-TAKE-OUT-KNOWN-INTEGER))
     (130 13 (:REWRITE FLOOR-TYPE-3 . 3))
     (124 13 (:REWRITE FLOOR-TYPE-3 . 2))
     (122 26 (:REWRITE CANCEL-FLOOR-+-BASIC))
     (121 13 (:REWRITE RTL1))
     (121 13 (:REWRITE FLOOR-TYPE-4 . 3))
     (121 13 (:REWRITE FLOOR-DETERMINED-1))
     (107 107 (:REWRITE DEFAULT-*-1))
     (105 13 (:REWRITE FLOOR-TYPE-4 . 2))
     (99 23 (:REWRITE <-*-/-RIGHT-COMMUTED))
     (52 26
         (:REWRITE FLOOR-WHEN-I-IS-NOT-AN-ACL2-NUMBERP))
     (48 12 (:REWRITE COMMUTATIVITY-OF-*))
     (43 43
         (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (43 43
         (:REWRITE INTEGERP-SUM-OF-ODDS-OVER-2-LEADING-CONSTANT))
     (43 43 (:REWRITE INTEGERP-+-MINUS-*-2))
     (35 35 (:REWRITE INTEGERP-+-MINUS-*-4))
     (26 26
         (:REWRITE FLOOR-WHEN-J-IS-NOT-AN-ACL2-NUMBERP))
     (26 2 (:LINEAR FLOOR-TYPE-2 . 2))
     (20 2 (:LINEAR FLOOR-TYPE-1 . 1))
     (13 2 (:LINEAR FLOOR-TYPE-1 . 2))
     (2 2
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (2 2 (:REWRITE CLR-DIFFERENTIAL)))
(GACC::DUAL-INDUCT (11 11
                       (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
                   (9 8 (:REWRITE DEFAULT-<-1))
                   (8 8 (:REWRITE DEFAULT-<-2))
                   (3 3
                      (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
                   (2 2 (:REWRITE DEFAULT-+-2))
                   (2 2 (:REWRITE DEFAULT-+-1)))
(GACC::<=MAX-OFFSET (135 27 (:REWRITE <-+-CONSTANT-CONSTANT))
                    (102 78 (:REWRITE DEFAULT-+-2))
                    (90 85 (:REWRITE DEFAULT-<-1))
                    (89 85 (:REWRITE DEFAULT-<-2))
                    (87 78 (:REWRITE DEFAULT-+-1))
                    (60 35
                        (:REWRITE GACC::MAX-OFFSET-OF-NON-INTEGER))
                    (27 9 (:REWRITE FOLD-CONSTS-IN-+))
                    (10 10
                        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1)))
(GACC::MULTIPLE-OF-8)
(GACC::MULTIPLE-OF-8-FW-TO-INTEGERP-OF-*-1/8)
(GACC::MAX-OFFSET-WHEN-MULTIPLE-OF-8
     (18 3 (:REWRITE <-+-CONSTANT-CONSTANT))
     (15 12 (:REWRITE DEFAULT-*-2))
     (12 12 (:REWRITE DEFAULT-*-1))
     (12 3 (:REWRITE <-*-/-LEFT-COMMUTED))
     (10 2
         (:REWRITE GACC::MULTIPLE-OF-8-FW-TO-INTEGERP-OF-*-1/8))
     (10 1 (:REWRITE RTL1))
     (10 1 (:REWRITE FLOOR-SIMPLE-CASES))
     (10 1 (:REWRITE FLOOR-DETERMINED-1))
     (8 4
        (:REWRITE FLOOR-WHEN-I-IS-NOT-AN-ACL2-NUMBERP))
     (8 2 (:LINEAR X*Y>1-POSITIVE))
     (7 7 (:REWRITE DEFAULT-+-2))
     (7 7 (:REWRITE DEFAULT-+-1))
     (7 6 (:REWRITE DEFAULT-<-2))
     (6 6 (:REWRITE DEFAULT-<-1))
     (4 4
        (:REWRITE FLOOR-WHEN-J-IS-NOT-AN-ACL2-NUMBERP))
     (3 2
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (2 2 (:REWRITE INTEGERP-+-MINUS-*-4))
     (2 2 (:LINEAR GACC::<=MAX-OFFSET))
     (2 1 (:REWRITE FLOOR-OF-INTEGER-BY-1))
     (1 1 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1 (:REWRITE RATIONALP-*)))
(GACC::RX-REC (27 26 (:REWRITE DEFAULT-+-2))
              (26 26 (:REWRITE DEFAULT-+-1))
              (21 21
                  (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
              (21 21 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
              (17 13 (:REWRITE DEFAULT-<-1))
              (14 13 (:REWRITE DEFAULT-<-2))
              (12 12
                  (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
              (7 7 (:REWRITE DEFAULT-UNARY-MINUS)))
(GACC::INTEGERP-RX-REC)
(GACC::RX-REC-NON-NEGATIVE
     (56 56
         (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (48 40 (:REWRITE DEFAULT-<-1))
     (46 46 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (44 44 (:REWRITE DEFAULT-+-2))
     (44 44 (:REWRITE DEFAULT-+-1))
     (40 40 (:REWRITE DEFAULT-<-2))
     (30 14 (:REWRITE FOLD-CONSTS-IN-+))
     (30 6 (:REWRITE COMMUTATIVITY-OF-+))
     (21 6 (:REWRITE <-+-CONSTANT-CONSTANT))
     (17 17
         (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
     (17 17
         (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
     (12 2 (:REWRITE COMMUTATIVITY-2-OF-+))
     (12 2 (:REWRITE ASSOCIATIVITY-OF-+))
     (3 3
        (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-RHS)))
(GACC::RX-REC-NON-INTEGER-PTR
     (84 84 (:REWRITE DEFAULT-+-2))
     (84 84 (:REWRITE DEFAULT-+-1))
     (48 48
         (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (48 16 (:REWRITE FOLD-CONSTS-IN-+))
     (45 45 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (41 41 (:REWRITE DEFAULT-<-2))
     (41 41 (:REWRITE DEFAULT-<-1))
     (40 40
         (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
     (40 40
         (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
     (28 8 (:REWRITE <-+-CONSTANT-CONSTANT))
     (5 5 (:REWRITE CLR-DIFFERENTIAL))
     (4 4
        (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-RHS)))
(GACC::RX-REC-WHEN-MAX-IS-LESS-THAN-OFF
     (15 15
         (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (9 9
        (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
     (9 9 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (9 9 (:REWRITE DEFAULT-<-2))
     (9 9 (:REWRITE DEFAULT-<-1))
     (8 4 (:DEFINITION IFIX))
     (6 3
        (:REWRITE GACC::RX-REC-NON-INTEGER-PTR))
     (4 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-+-1))
     (2 2
        (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
     (2 2
        (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
     (2 2 (:REWRITE CLR-DIFFERENTIAL)))
(GACC::LOGHEAD8-OF-RX-REC
 (1166 30 (:DEFINITION LOGHEAD*-BETTER))
 (563 54 (:REWRITE LOGHEAD-IDENTITY))
 (335 30 (:REWRITE UNSIGNED-BYTE-P-OF-LOGCDR))
 (270 36 (:REWRITE LOGCAR-IDENTITY))
 (185 36 (:REWRITE LOGCAR-EVENP))
 (162 96
      (:REWRITE UNSIGNED-BYTE-P-WHEN-N-IS-NON-POSITIVE))
 (140 140 (:TYPE-PRESCRIPTION LOGAPP-TYPE))
 (138 12 (:REWRITE UNSIGNED-BYTE-P-LOGAPP))
 (138 6 (:REWRITE LOGCAR-LOGAPP))
 (119 60
      (:REWRITE LOGHEAD-WHEN-I-IS-NOT-AN-INTEGERP))
 (102
  96
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-TWO))
 (96
  96
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-ONE))
 (96 96
     (:REWRITE UNSIGNED-BYTE-P-OF-EXPT-CONST-VERSION))
 (77 36
     (:REWRITE LOGCAR-WHEN-I-IS-NOT-AN-INTEGERP))
 (77 36 (:REWRITE EVENP-WHEN-NOT-INTEGERP))
 (72 72 (:TYPE-PRESCRIPTION EVENP))
 (60 60
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-POSITIVE))
 (60 60
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-AN-INTEGERP))
 (59 30
     (:REWRITE LOGCDR-WHEN-I-IS-NOT-AN-INTEGERP))
 (31 31
     (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
 (31 23 (:REWRITE DEFAULT-<-1))
 (30 30 (:TYPE-PRESCRIPTION LOGCDR-TYPE))
 (30 30 (:REWRITE LOGHEAD-SUBST2))
 (30 30 (:REWRITE LOGHEAD-SUBST))
 (26 26
     (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
 (26 26
     (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
 (24 23 (:REWRITE DEFAULT-<-2))
 (20 20 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
 (20 7
     (:REWRITE GACC::RX-REC-WHEN-MAX-IS-LESS-THAN-OFF))
 (18 18 (:REWRITE DEFAULT-+-2))
 (18 18 (:REWRITE DEFAULT-+-1))
 (8 7
    (:REWRITE GACC::RX-REC-NON-INTEGER-PTR))
 (7 7 (:REWRITE CLR-DIFFERENTIAL))
 (6 6
    (:REWRITE GACC::UNSIGNED-BYTE-P-OF-RD))
 (3 3
    (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-INTEGERP))
 (3 3
    (:TYPE-PRESCRIPTION EXPT-2-POSITIVE-RATIONAL-TYPE))
 (2 2
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (2 2 (:REWRITE <-+-CONSTANT-CONSTANT))
 (1 1 (:REWRITE LOGHEAD-COMPARE-HACK)))
(GACC::RX-REC-NON-INTEGER-OFF
     (122 51
          (:REWRITE GACC::RX-REC-WHEN-MAX-IS-LESS-THAN-OFF))
     (58 58
         (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (47 40 (:REWRITE DEFAULT-<-2))
     (44 40 (:REWRITE DEFAULT-<-1))
     (33 33
         (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
     (33 33
         (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
     (20 20 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (16 16 (:REWRITE DEFAULT-+-2))
     (16 16 (:REWRITE DEFAULT-+-1))
     (11 11
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (4 4 (:REWRITE CLR-DIFFERENTIAL)))
(GACC::UNSIGNED-BYTE-P-OF-RX-REC-HELPER
 (669 28 (:REWRITE UNSIGNED-BYTE-P-PLUS))
 (198 9
      (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-RHS))
 (182 182
      (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
 (155 41 (:REWRITE <-+-CONSTANT-CONSTANT))
 (153 9 (:REWRITE 0-<-*))
 (141 141 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
 (130 123 (:REWRITE DEFAULT-+-2))
 (127 123 (:REWRITE DEFAULT-+-1))
 (117 18 (:DEFINITION IFF))
 (111 109 (:REWRITE DEFAULT-<-2))
 (111 109 (:REWRITE DEFAULT-<-1))
 (108 9 (:REWRITE <-*-0))
 (78 3 (:LINEAR EXPT-LESS-THAN-1-HACK))
 (78 3 (:LINEAR EXPT->-1))
 (75 19
     (:REWRITE GACC::RX-REC-WHEN-MAX-IS-LESS-THAN-OFF))
 (62 4
     (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-2-ON-LHS))
 (41 40
     (:REWRITE UNSIGNED-BYTE-P-OF-EXPT-CONST-VERSION))
 (40
  40
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-TWO))
 (40
  40
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-ONE))
 (38 38 (:REWRITE CLR-DIFFERENTIAL))
 (36 36
     (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
 (32 18 (:REWRITE FOLD-CONSTS-IN-+))
 (27 11
     (:REWRITE UNSIGNED-BYTE-P-WHEN-N-IS-NOT-AN-INTEGERP))
 (26 10
     (:REWRITE *-PRESERVES->=-FOR-NONNEGATIVES))
 (23 22 (:REWRITE DEFAULT-*-2))
 (22 22 (:REWRITE DEFAULT-*-1))
 (15 10
     (:REWRITE GACC::RX-REC-NON-INTEGER-PTR))
 (14 14
     (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
 (14 14
     (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
 (14 2
     (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-LHS))
 (12 12 (:REWRITE X*Y>1-POSITIVE-LEMMA))
 (12 12
     (:REWRITE *-PRESERVES->-FOR-NONNEGATIVES-1))
 (11 11 (:REWRITE DEFAULT-UNARY-MINUS))
 (10 10
     (:REWRITE GACC::RX-REC-NON-INTEGER-OFF))
 (6 6
    (:LINEAR EXPT-IS-INCREASING-FOR-BASE>1))
 (6 1 (:REWRITE ASSOCIATIVITY-OF-+))
 (5 1 (:REWRITE <-*-Y-X-Y))
 (1 1 (:TYPE-PRESCRIPTION POWER2P))
 (1 1
    (:REWRITE COMBINE-CONSTANTS-IN-EQUAL-OF-TIMES))
 (1 1 (:INDUCTION UBP-INDUCTION)))
(GACC::UNSIGNED-BYTE-P-OF-RX-REC
 (328 6 (:REWRITE UNSIGNED-BYTE-P-PLUS))
 (136 4 (:LINEAR X*Y>1-POSITIVE))
 (134 6 (:REWRITE /R-WHEN-ABS-NUMERATOR=1))
 (128 128
      (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
 (126 8 (:REWRITE 0-<-*))
 (114 8 (:LINEAR EXPT->-1))
 (94 79 (:REWRITE DEFAULT-<-2))
 (91 16 (:DEFINITION IFF))
 (91 8 (:REWRITE <-*-0))
 (88 79 (:REWRITE DEFAULT-<-1))
 (66 3
     (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-RHS))
 (64 6 (:REWRITE <-1-EXPT))
 (58 1 (:REWRITE <-UNARY-/-POSITIVE-LEFT))
 (50 1 (:REWRITE <-*-/-LEFT))
 (45 42 (:REWRITE DEFAULT-+-1))
 (44 42 (:REWRITE DEFAULT-+-2))
 (44 2 (:REWRITE NUMERATOR-WHEN-INTEGERP))
 (40 9 (:REWRITE <-*-LEFT-CANCEL))
 (39 26 (:REWRITE DEFAULT-*-2))
 (36 26 (:REWRITE DEFAULT-*-1))
 (35 35 (:REWRITE CLR-DIFFERENTIAL))
 (33 25
     (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
 (32 2 (:REWRITE EQUAL-1-HACK))
 (30 2
     (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-2-ON-LHS))
 (26 24 (:REWRITE EXPT-WITH-VIOLATED-GUARDS))
 (24 2 (:REWRITE INTEGERP-EXPT))
 (20 4
     (:REWRITE *-PRESERVES->=-FOR-NONNEGATIVES))
 (18 16
     (:REWRITE UNSIGNED-BYTE-P-OF-EXPT-CONST-VERSION))
 (17 16
     (:LINEAR EXPT-IS-INCREASING-FOR-BASE>1))
 (15
  15
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-ONE))
 (15 13
     (:REWRITE EXPT-WHEN-I-IS-NOT-AN-INTEGERP))
 (15 3 (:REWRITE DEFAULT-UNARY-/))
 (14 2 (:REWRITE EQUAL-BIT-1))
 (12 6
     (:REWRITE GACC::RX-REC-NON-INTEGER-PTR))
 (11 11
     (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (9 9 (:REWRITE X*Y>1-POSITIVE-LEMMA))
 (9 9 (:REWRITE DEFAULT-UNARY-MINUS))
 (9 9
    (:REWRITE *-PRESERVES->-FOR-NONNEGATIVES-1))
 (9 1 (:REWRITE X*Y>1-POSITIVE))
 (8 8
    (:REWRITE GACC::RX-REC-NON-INTEGER-OFF))
 (7 1 (:REWRITE COMMUTATIVITY-OF-*))
 (6 2 (:REWRITE DEFAULT-NUMERATOR))
 (5 5 (:REWRITE <-+-CONSTANT-CONSTANT))
 (4 1
    (:REWRITE EXPT-IS-INCREASING-FOR-BASE>1))
 (2 2 (:TYPE-PRESCRIPTION POWER2P))
 (2 2
    (:REWRITE EXPT-IS-WEAKLY-DECREASING-FOR-POS-BASE<1))
 (1 1
    (:REWRITE EXPT-IS-DECREASING-FOR-POS-BASE<1))
 (1 1
    (:REWRITE COMBINE-CONSTANTS-IN-EQUAL-OF-TIMES)))
(GACC::RX)
(GACC::INTEGERP-RX)
(GACC::RX-NON-NEGATIVE-REWRITE)
(GACC::RX-NON-NEGATIVE-TYPE-PRESCRIPTION)
(GACC::RX-NON-NEGATIVE-LINEAR)
(GACC::RX-WHEN-SIZE-IS-NOT-AN-INTEGERP
     (3 2
        (:REWRITE GACC::RX-REC-NON-INTEGER-PTR))
     (3 1
        (:REWRITE GACC::MAX-OFFSET-WHEN-MULTIPLE-OF-8))
     (2 2
        (:TYPE-PRESCRIPTION GACC::MULTIPLE-OF-8))
     (2 2
        (:REWRITE GACC::RX-REC-WHEN-MAX-IS-LESS-THAN-OFF))
     (2 2
        (:REWRITE GACC::RX-REC-NON-INTEGER-OFF))
     (2 2
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1)))
(GACC::RX-WHEN-SIZE-IS-NOT-POSITIVE
     (3 2
        (:REWRITE GACC::RX-REC-NON-INTEGER-PTR))
     (3 1
        (:REWRITE GACC::MAX-OFFSET-WHEN-MULTIPLE-OF-8))
     (2 2
        (:TYPE-PRESCRIPTION GACC::MULTIPLE-OF-8))
     (2 2
        (:REWRITE GACC::RX-REC-WHEN-MAX-IS-LESS-THAN-OFF))
     (2 2
        (:REWRITE GACC::RX-REC-NON-INTEGER-OFF))
     (2 2
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (2 1
        (:REWRITE GACC::MAX-OFFSET-OF-NON-INTEGER))
     (2 1 (:REWRITE DEFAULT-<-2))
     (1 1
        (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
     (1 1 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1 (:REWRITE DEFAULT-<-1)))
(GACC::UNSIGNED-BYTE-P-OF-RX
     (4 3 (:REWRITE DEFAULT-<-2))
     (4 3 (:REWRITE DEFAULT-<-1))
     (3 3
        (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
     (3 3 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (3 3
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (3 3 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE DEFAULT-+-1))
     (3 3 (:REWRITE DEFAULT-*-2))
     (3 3 (:REWRITE DEFAULT-*-1))
     (2 2
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (2 1
        (:REWRITE GACC::RX-REC-NON-INTEGER-PTR))
     (1 1
        (:REWRITE GACC::RX-REC-WHEN-MAX-IS-LESS-THAN-OFF))
     (1 1
        (:REWRITE GACC::RX-REC-NON-INTEGER-OFF))
     (1 1 (:REWRITE CLR-DIFFERENTIAL)))
(GACC::SIGNED-BYTE-P-OF-RX-GEN
 (29 14 (:REWRITE DEFAULT-<-1))
 (26 2 (:REWRITE FALSIFY-SIGNED-BYTE-P))
 (22 14 (:REWRITE DEFAULT-<-2))
 (20 16
     (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
 (18 2 (:REWRITE SBP-BOUND))
 (17 17 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
 (17 1
     (:REWRITE UNSIGNED-BYTE-P-WHEN-N-IS-NOT-AN-INTEGERP))
 (13 7 (:REWRITE DEFAULT-+-1))
 (12 7 (:REWRITE DEFAULT-+-2))
 (11 1
     (:REWRITE UNSIGNED-BYTE-P-WHEN-N-IS-NON-POSITIVE))
 (9 4 (:REWRITE <-+-CONSTANT-CONSTANT))
 (8 2 (:REWRITE DEFAULT-UNARY-MINUS))
 (6 4 (:REWRITE EXPT-WITH-VIOLATED-GUARDS))
 (5 5
    (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
 (4 4
    (:REWRITE SIGNED-BYTE-P-UNSIGNED-BYTE-P))
 (4 4 (:REWRITE SIGNED-BYTE-P-SUBTYPE))
 (4 4
    (:REWRITE BACKCHAIN-SIGNED-BYTE-P-TO-UNSIGNED-BYTE-P))
 (4 2 (:REWRITE MINUS-CANCELLATION-ON-LEFT))
 (4 2
    (:REWRITE EXPT-WHEN-I-IS-NOT-AN-INTEGERP))
 (3 3 (:REWRITE SBP-BOUND-1))
 (3 3
    (:REWRITE GACC::RX-WHEN-SIZE-IS-NOT-POSITIVE))
 (3 3
    (:REWRITE GACC::RX-WHEN-SIZE-IS-NOT-AN-INTEGERP))
 (3 3 (:REWRITE CLR-DIFFERENTIAL))
 (3 2 (:REWRITE INTEGERP-+-MINUS-*-2))
 (2 2
    (:REWRITE INTEGERP-SUM-OF-ODDS-OVER-2-LEADING-CONSTANT))
 (2 2
    (:REWRITE INTEGER-RANGE-P-EXTEND-UPPER))
 (2 2
    (:REWRITE INTEGER-RANGE-P-EXTEND-LOWER))
 (2 2
    (:REWRITE EXPONENTS-ADD-FOR-NONNEG-EXPONENTS))
 (2 2 (:REWRITE EXPONENTS-ADD))
 (1 1 (:REWRITE UNSIGNED-BYTE-P-SUBTYPE))
 (1
  1
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-TWO))
 (1
  1
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-ONE))
 (1 1
    (:REWRITE UNSIGNED-BYTE-P-OF-EXPT-CONST-VERSION))
 (1 1 (:REWRITE RATIONALP-+)))
(GACC::WX-REC (27 26 (:REWRITE DEFAULT-+-2))
              (26 26 (:REWRITE DEFAULT-+-1))
              (21 21
                  (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
              (21 21 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
              (17 13 (:REWRITE DEFAULT-<-1))
              (14 13 (:REWRITE DEFAULT-<-2))
              (12 12
                  (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
              (7 7 (:REWRITE DEFAULT-UNARY-MINUS)))
(GACC::WX-REC-WHEN-BASE-IS-NOT-AN-INTEGERP
 (1208 40 (:DEFINITION LOGHEAD*-BETTER))
 (660 80 (:REWRITE LOGHEAD-IDENTITY))
 (340 40 (:REWRITE LOGCAR-IDENTITY))
 (312 40 (:REWRITE UNSIGNED-BYTE-P-OF-LOGCDR))
 (272 272
      (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
 (216 36 (:REWRITE LOGTAIL-UNSIGNED-BYTE-P))
 (208 40 (:REWRITE LOGTAIL-IDENTITY))
 (172 172
      (:REWRITE UNSIGNED-BYTE-P-WHEN-N-IS-NON-POSITIVE))
 (172
  172
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-TWO))
 (172
  172
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-ONE))
 (172 172
      (:REWRITE UNSIGNED-BYTE-P-OF-EXPT-CONST-VERSION))
 (172 40 (:REWRITE LOGCAR-EVENP))
 (132 80
      (:REWRITE LOGHEAD-WHEN-I-IS-NOT-AN-INTEGERP))
 (120 120
      (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
 (96 12 (:REWRITE LOGTAIL-LOGTAIL))
 (84 84 (:TYPE-PRESCRIPTION LOGTAIL-TYPE))
 (84 84 (:REWRITE DEFAULT-+-2))
 (84 84 (:REWRITE DEFAULT-+-1))
 (80 80 (:TYPE-PRESCRIPTION EVENP))
 (80 80
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-POSITIVE))
 (80 80
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-AN-INTEGERP))
 (52 40
     (:REWRITE LOGCDR-WHEN-I-IS-NOT-AN-INTEGERP))
 (52 40
     (:REWRITE LOGCAR-WHEN-I-IS-NOT-AN-INTEGERP))
 (52 40 (:REWRITE EVENP-WHEN-NOT-INTEGERP))
 (48 16 (:REWRITE FOLD-CONSTS-IN-+))
 (45 45 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
 (41 41 (:REWRITE DEFAULT-<-2))
 (41 41 (:REWRITE DEFAULT-<-1))
 (40 40 (:TYPE-PRESCRIPTION LOGCDR-TYPE))
 (40 40 (:REWRITE LOGHEAD-SUBST2))
 (40 40 (:REWRITE LOGHEAD-SUBST))
 (28 8 (:REWRITE <-+-CONSTANT-CONSTANT))
 (5 5 (:REWRITE CLR-DIFFERENTIAL))
 (4 4
    (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-RHS)))
(GACC::WX-REC-WHEN-OFF-IS-NOT-AN-INTEGERP
 (1316 42 (:DEFINITION LOGHEAD*-BETTER))
 (770 84 (:REWRITE LOGHEAD-IDENTITY))
 (447 3 (:REWRITE GACC::WR==R))
 (441 3 (:DEFINITION GACC::WR==R-HYP))
 (374 42 (:REWRITE LOGCAR-IDENTITY))
 (348 42 (:REWRITE UNSIGNED-BYTE-P-OF-LOGCDR))
 (306 306
      (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
 (288 48 (:REWRITE LOGTAIL-UNSIGNED-BYTE-P))
 (244 46 (:REWRITE LOGTAIL-IDENTITY))
 (201 201
      (:REWRITE UNSIGNED-BYTE-P-WHEN-N-IS-NON-POSITIVE))
 (201
  201
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-TWO))
 (201
  201
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-ONE))
 (201 201
      (:REWRITE UNSIGNED-BYTE-P-OF-EXPT-CONST-VERSION))
 (184 42 (:REWRITE LOGCAR-EVENP))
 (142 84
      (:REWRITE LOGHEAD-WHEN-I-IS-NOT-AN-INTEGERP))
 (123 3 (:LINEAR LOGHEAD-UPPER-BOUND))
 (120 3 (:LINEAR LOGHEAD-NONNEGATIVE-LINEAR))
 (100 100
      (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
 (84 84 (:TYPE-PRESCRIPTION EVENP))
 (84 84
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-POSITIVE))
 (84 84
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-AN-INTEGERP))
 (58 42
     (:REWRITE LOGCDR-WHEN-I-IS-NOT-AN-INTEGERP))
 (58 42
     (:REWRITE LOGCAR-WHEN-I-IS-NOT-AN-INTEGERP))
 (58 42 (:REWRITE EVENP-WHEN-NOT-INTEGERP))
 (42 42 (:TYPE-PRESCRIPTION LOGCDR-TYPE))
 (42 42 (:REWRITE LOGHEAD-SUBST2))
 (42 42 (:REWRITE LOGHEAD-SUBST))
 (37 37 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
 (37 37 (:REWRITE DEFAULT-<-2))
 (37 37 (:REWRITE DEFAULT-<-1))
 (30 6
     (:LINEAR GACC::RD-NON-NEGATIVE-LINEAR))
 (28 28 (:REWRITE DEFAULT-+-2))
 (28 28 (:REWRITE DEFAULT-+-1))
 (21 21
     (:TYPE-PRESCRIPTION GACC::RD-NON-NEGATIVE-TYPE-PRESCRIPTION))
 (21 21
     (:TYPE-PRESCRIPTION GACC::RD-INTEGERP-TYPE-PRESCRIPTION))
 (21 21 (:TYPE-PRESCRIPTION LOGHEAD-TYPE))
 (15 3 (:LINEAR LOGHEAD-LEQ))
 (11 11 (:REWRITE CLR-DIFFERENTIAL))
 (9 9
    (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
 (9 9
    (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
 (3 3 (:TYPE-PRESCRIPTION GACC::WR==R-HYP)))
(GACC::WX-REC-WHEN-MAX-IS-NOT-AN-INTEGERP
 (1316 42 (:DEFINITION LOGHEAD*-BETTER))
 (770 84 (:REWRITE LOGHEAD-IDENTITY))
 (489 5 (:REWRITE GACC::WR==R))
 (479 5 (:DEFINITION GACC::WR==R-HYP))
 (374 42 (:REWRITE LOGCAR-IDENTITY))
 (348 42 (:REWRITE UNSIGNED-BYTE-P-OF-LOGCDR))
 (306 306
      (:TYPE-PRESCRIPTION UNSIGNED-BYTE-P))
 (288 48 (:REWRITE LOGTAIL-UNSIGNED-BYTE-P))
 (244 46 (:REWRITE LOGTAIL-IDENTITY))
 (223 223 (:REWRITE DEFAULT-+-2))
 (223 223 (:REWRITE DEFAULT-+-1))
 (201 201
      (:REWRITE UNSIGNED-BYTE-P-WHEN-N-IS-NON-POSITIVE))
 (201
  201
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-TWO))
 (201
  201
  (:REWRITE
       UNSIGNED-BYTE-P-REWRITES-TO-LOWER-BOUND-WHEN-WE-KNOW-UPPER-BOUND-ONE))
 (201 201
      (:REWRITE UNSIGNED-BYTE-P-OF-EXPT-CONST-VERSION))
 (184 42 (:REWRITE LOGCAR-EVENP))
 (180 30 (:REWRITE <-+-CONSTANT-CONSTANT))
 (162 74 (:REWRITE FOLD-CONSTS-IN-+))
 (142 84
      (:REWRITE LOGHEAD-WHEN-I-IS-NOT-AN-INTEGERP))
 (128 16 (:REWRITE LOGTAIL-LOGTAIL))
 (123 3 (:LINEAR LOGHEAD-UPPER-BOUND))
 (120 3 (:LINEAR LOGHEAD-NONNEGATIVE-LINEAR))
 (112 112 (:TYPE-PRESCRIPTION LOGTAIL-TYPE))
 (111 111
      (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
 (103 103
      (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
 (103 103 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
 (84 84 (:TYPE-PRESCRIPTION EVENP))
 (84 84
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-POSITIVE))
 (84 84
     (:REWRITE LOGHEAD-WHEN-SIZE-IS-NOT-AN-INTEGERP))
 (84 14 (:REWRITE COMMUTATIVITY-2-OF-+))
 (73 73 (:REWRITE DEFAULT-<-2))
 (73 73 (:REWRITE DEFAULT-<-1))
 (58 42
     (:REWRITE LOGCDR-WHEN-I-IS-NOT-AN-INTEGERP))
 (58 42
     (:REWRITE LOGCAR-WHEN-I-IS-NOT-AN-INTEGERP))
 (58 42 (:REWRITE EVENP-WHEN-NOT-INTEGERP))
 (42 42 (:TYPE-PRESCRIPTION LOGCDR-TYPE))
 (42 42 (:REWRITE LOGHEAD-SUBST2))
 (42 42 (:REWRITE LOGHEAD-SUBST))
 (40 8
     (:LINEAR GACC::RD-NON-NEGATIVE-LINEAR))
 (33 33
     (:TYPE-PRESCRIPTION GACC::RD-NON-NEGATIVE-TYPE-PRESCRIPTION))
 (33 33
     (:TYPE-PRESCRIPTION GACC::RD-INTEGERP-TYPE-PRESCRIPTION))
 (30 30
     (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-RHS))
 (21 21 (:TYPE-PRESCRIPTION LOGHEAD-TYPE))
 (15 3 (:LINEAR LOGHEAD-LEQ))
 (13 13
     (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
 (13 13
     (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
 (13 13 (:REWRITE CLR-DIFFERENTIAL))
 (12 2 (:REWRITE ASSOCIATIVITY-OF-+))
 (5 5 (:TYPE-PRESCRIPTION GACC::WR==R-HYP)))
(GACC::WX-REC-WHEN-VALUE-IS-NOT-AN-INTEGERP
     (162 162
          (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (156 156 (:REWRITE DEFAULT-+-2))
     (156 156 (:REWRITE DEFAULT-+-1))
     (90 42 (:REWRITE FOLD-CONSTS-IN-+))
     (88 18 (:REWRITE <-+-CONSTANT-CONSTANT))
     (85 85 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (84 4 (:REWRITE GACC::WR==R))
     (76 4 (:DEFINITION GACC::WR==R-HYP))
     (71 71 (:REWRITE DEFAULT-<-2))
     (71 71 (:REWRITE DEFAULT-<-1))
     (36 6 (:REWRITE COMMUTATIVITY-2-OF-+))
     (36 6 (:REWRITE ASSOCIATIVITY-OF-+))
     (24 24
         (:TYPE-PRESCRIPTION GACC::RD-NON-NEGATIVE-TYPE-PRESCRIPTION))
     (24 24
         (:TYPE-PRESCRIPTION GACC::RD-INTEGERP-TYPE-PRESCRIPTION))
     (20 4
         (:LINEAR GACC::RD-NON-NEGATIVE-LINEAR))
     (14 14
         (:REWRITE MOVE-NEGATED-TERM-TO-OTHER-SIDE-OF-<-TERM-1-ON-RHS))
     (13 13 (:REWRITE CLR-DIFFERENTIAL))
     (8 8
        (:REWRITE GACC::RD-SUBST-WHEN-WR-EQUAL))
     (8 8
        (:REWRITE GACC::RD-SUBST-WHEN-CLR-EQUAL))
     (4 4 (:TYPE-PRESCRIPTION GACC::WR==R-HYP)))
(GACC::WX-REC-WHEN-MAX-<=-OFF
     (18 18
         (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (12 8
         (:REWRITE GACC::WX-REC-WHEN-VALUE-IS-NOT-AN-INTEGERP))
     (8 4
        (:REWRITE GACC::WX-REC-WHEN-BASE-IS-NOT-AN-INTEGERP))
     (4 4
        (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
     (4 4 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1)))
(GACC::WX)
(GACC::WX-WHEN-SIZE-IS-NOT-AN-INTEGERP
     (4 2
        (:REWRITE GACC::WX-REC-WHEN-MAX-<=-OFF))
     (3 3
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (3 2
        (:REWRITE GACC::WX-REC-WHEN-VALUE-IS-NOT-AN-INTEGERP))
     (3 2
        (:REWRITE GACC::WX-REC-WHEN-BASE-IS-NOT-AN-INTEGERP))
     (3 1
        (:REWRITE GACC::MAX-OFFSET-WHEN-MULTIPLE-OF-8))
     (2 2
        (:TYPE-PRESCRIPTION GACC::MULTIPLE-OF-8))
     (2 2 (:TYPE-PRESCRIPTION IFIX))
     (2 2
        (:REWRITE GACC::WX-REC-WHEN-OFF-IS-NOT-AN-INTEGERP))
     (2 2
        (:REWRITE GACC::WX-REC-WHEN-MAX-IS-NOT-AN-INTEGERP)))
(GACC::WX-WHEN-SIZE-IS-NOT-POSITIVE
     (4 2
        (:REWRITE GACC::WX-REC-WHEN-MAX-<=-OFF))
     (3 3
        (:REWRITE INTEGERP-*-CONSTANT-MEANS-1))
     (3 2
        (:REWRITE GACC::WX-REC-WHEN-VALUE-IS-NOT-AN-INTEGERP))
     (3 2
        (:REWRITE GACC::WX-REC-WHEN-BASE-IS-NOT-AN-INTEGERP))
     (3 1
        (:REWRITE GACC::MAX-OFFSET-WHEN-MULTIPLE-OF-8))
     (2 2
        (:TYPE-PRESCRIPTION GACC::MULTIPLE-OF-8))
     (2 2 (:TYPE-PRESCRIPTION IFIX))
     (2 2
        (:REWRITE GACC::WX-REC-WHEN-OFF-IS-NOT-AN-INTEGERP))
     (2 2
        (:REWRITE GACC::WX-REC-WHEN-MAX-IS-NOT-AN-INTEGERP))
     (2 1
        (:REWRITE GACC::MAX-OFFSET-OF-NON-INTEGER))
     (2 1 (:REWRITE DEFAULT-<-2))
     (1 1
        (:REWRITE REMOVE-REDUNDANT-LESS-THANS))
     (1 1 (:REWRITE REMOVE-REDUNDANT-<=-HYPS))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1 (:REWRITE DEFAULT-<-1)))
