## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

include ../dir.mk

include $(DIR)/books/Makefile-generic
ACL2 = $(DIR)/saved_acl2

BOOKS = RC6-source-shallow-canon RC6-source-shallow-flatten proof-RC6


