#!/bin/csh

echo ""
echo "This will take you back to a state close to the original state."
echo ""

echo -n "Do you really want to do it (y or n) ? "
set ok=$<

if ($ok != "y") then
    exit
endif

/bin/rm -r *~

cd mace-1.3.4
make realclean
cd ..

cd otter-3.0.6/source
make realclean
cd ../..

cd ivy-sources
make realclean
cd ..
