(BIT-LISTP-IS-DAB-DIGIT-LISTP-OF-2
     (170 25
          (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (140 9 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (128 11 (:DEFINITION INTEGER-LISTP))
     (120 10
          (:REWRITE DAB-DIGITP-OF-CAR-WHEN-DAB-DIGIT-LISTP))
     (119 4 (:DEFINITION NAT-LISTP))
     (57 8 (:REWRITE BITP-OF-CAR-WHEN-BIT-LISTP))
     (40 40 (:REWRITE DEFAULT-CAR))
     (34 34
         (:REWRITE DAB-DIGIT-LISTP-WHEN-SUBSETP-EQUAL))
     (32 32
         (:REWRITE BIT-LISTP-WHEN-SUBSETP-EQUAL))
     (24 12
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (22 22
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (20 20 (:REWRITE DEFAULT-CDR))
     (20 20
         (:REWRITE DAB-DIGITP-WHEN-MEMBER-EQUAL-OF-DAB-DIGIT-LISTP))
     (16 16
         (:REWRITE BITP-WHEN-MEMBER-EQUAL-OF-BIT-LISTP))
     (15 15 (:REWRITE DEFAULT-<-2))
     (15 15 (:REWRITE DEFAULT-<-1))
     (14 2
         (:REWRITE DAB-DIGIT-LISTP-OF-CDR-WHEN-DAB-DIGIT-LISTP))
     (14 2
         (:REWRITE BIT-LISTP-OF-CDR-WHEN-BIT-LISTP))
     (8 8
        (:REWRITE NATP-LISTP-WHEN-DAB-DIGIT-LISTP))
     (8 8 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (8 4
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (7 7
        (:REWRITE-QUOTED-CONSTANT DAB-BASE-FIX-UNDER-DAB-BASE-EQUIV))
     (4 4 (:DEFINITION NULL)))
(BIT-LIST-FIX-IS-DAB-DIGIT-LISTP-OF-2
     (329 3
          (:REWRITE DAB-DIGIT-FIX-WHEN-DAB-DIGITP))
     (260 31
          (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (222 10
          (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (217 17 (:DEFINITION INTEGER-LISTP))
     (205 4 (:DEFINITION NAT-LISTP))
     (65 23
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (48 6
         (:REWRITE DAB-DIGIT-LIST-FIX-WHEN-DAB-DIGIT-LISTP))
     (48 6
         (:REWRITE BIT-LIST-FIX-WHEN-BIT-LISTP))
     (37 35 (:REWRITE DEFAULT-CAR))
     (35 33 (:REWRITE DEFAULT-CDR))
     (34 34
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (33 3 (:REWRITE BFIX-BITP))
     (22 22
         (:REWRITE DAB-DIGIT-LISTP-WHEN-SUBSETP-EQUAL))
     (22 22
         (:REWRITE BIT-LISTP-WHEN-SUBSETP-EQUAL))
     (21 21 (:TYPE-PRESCRIPTION DAB-DIGIT-LISTP))
     (21 6
         (:REWRITE DAB-DIGITP-OF-CAR-WHEN-DAB-DIGIT-LISTP))
     (18 3 (:REWRITE BITP-OF-CAR-WHEN-BIT-LISTP))
     (17 17 (:REWRITE DEFAULT-<-2))
     (17 17 (:REWRITE DEFAULT-<-1))
     (12 12
         (:REWRITE DAB-DIGITP-WHEN-MEMBER-EQUAL-OF-DAB-DIGIT-LISTP))
     (12 11
         (:REWRITE DAB-DIGIT-LISTP-WHEN-NOT-CONSP))
     (12 11 (:REWRITE BIT-LISTP-WHEN-NOT-CONSP))
     (12 2
         (:REWRITE DAB-DIGIT-LISTP-OF-CDR-WHEN-DAB-DIGIT-LISTP))
     (12 2
         (:REWRITE BIT-LISTP-OF-CDR-WHEN-BIT-LISTP))
     (10 5
         (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (8 8
        (:REWRITE NATP-LISTP-WHEN-DAB-DIGIT-LISTP))
     (8 8 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (6 6
        (:REWRITE BITP-WHEN-MEMBER-EQUAL-OF-BIT-LISTP))
     (4 4
        (:REWRITE-QUOTED-CONSTANT DAB-BASE-FIX-UNDER-DAB-BASE-EQUIV))
     (3 3 (:TYPE-PRESCRIPTION DAB-DIGITP))
     (3 3 (:TYPE-PRESCRIPTION BITP))
     (3 3 (:DEFINITION BITP)))
(BIT-LISTP-GUARD-IS-T)
(BIT-LIST-FIX-GUARD-IS-DAB-DIGIT-LISTP-OF-2)
(BEBITS=>NAT)
(NATP-OF-BEBITS=>NAT)
(BEBITS=>NAT-OF-BIT-LIST-FIX-DIGITS)
(BEBITS=>NAT-BIT-LIST-EQUIV-CONGRUENCE-ON-DIGITS)
(LEBITS=>NAT)
(NATP-OF-LEBITS=>NAT)
(LEBITS=>NAT-OF-BIT-LIST-FIX-DIGITS)
(LEBITS=>NAT-BIT-LIST-EQUIV-CONGRUENCE-ON-DIGITS)
(NAT=>BEBITS (10 5
                 (:TYPE-PRESCRIPTION CONSP-OF-NAT=>BENDIAN))
             (5 5 (:TYPE-PRESCRIPTION ZP)))
(BIT-LISTP-OF-NAT=>BEBITS)
(NAT=>BEBITS-OF-NFIX-WIDTH)
(NAT=>BEBITS-NAT-EQUIV-CONGRUENCE-ON-WIDTH)
(NAT=>BEBITS-OF-NFIX-NAT)
(NAT=>BEBITS-NAT-EQUIV-CONGRUENCE-ON-NAT)
(LEN-OF-NAT=>BEBITS)
(NAT=>LEBITS (10 5
                 (:TYPE-PRESCRIPTION CONSP-OF-NAT=>LENDIAN))
             (5 5 (:TYPE-PRESCRIPTION ZP)))
(BIT-LISTP-OF-NAT=>LEBITS)
(NAT=>LEBITS-OF-NFIX-WIDTH)
(NAT=>LEBITS-NAT-EQUIV-CONGRUENCE-ON-WIDTH)
(NAT=>LEBITS-OF-NFIX-NAT)
(NAT=>LEBITS-NAT-EQUIV-CONGRUENCE-ON-NAT)
(LEN-OF-NAT=>LEBITS)
(NAT=>BEBITS* (10 5
                  (:TYPE-PRESCRIPTION CONSP-OF-NAT=>BENDIAN*))
              (5 5 (:TYPE-PRESCRIPTION ZP)))
(BIT-LISTP-OF-NAT=>BEBITS*)
(NAT=>BEBITS*-OF-NFIX-NAT)
(NAT=>BEBITS*-NAT-EQUIV-CONGRUENCE-ON-NAT)
(NAT=>LEBITS* (10 5
                  (:TYPE-PRESCRIPTION CONSP-OF-NAT=>LENDIAN*))
              (5 5 (:TYPE-PRESCRIPTION ZP)))
(BIT-LISTP-OF-NAT=>LEBITS*)
(NAT=>LEBITS*-OF-NFIX-NAT)
(NAT=>LEBITS*-NAT-EQUIV-CONGRUENCE-ON-NAT)
(NAT=>BEBITS+)
(BIT-LISTP-OF-NAT=>BEBITS+)
(NAT=>BEBITS+-OF-NFIX-NAT)
(NAT=>BEBITS+-NAT-EQUIV-CONGRUENCE-ON-NAT)
(NAT=>LEBITS+)
(BIT-LISTP-OF-NAT=>LEBITS+)
(NAT=>LEBITS+-OF-NFIX-NAT)
(NAT=>LEBITS+-NAT-EQUIV-CONGRUENCE-ON-NAT)
(BEBITS=>NAT-OF-NAT=>BEBITS)
(LEBITS=>NAT-OF-NAT=>LEBITS)
(BEBITS=>NAT-OF-NAT=>BEBITS*)
(LEBITS=>NAT-OF-NAT=>LEBITS*)
(BEBITS=>NAT-OF-NAT=>BEBITS+)
(LEBITS=>NAT-OF-NAT=>LEBITS+)
(NAT=>BEBITS-INJECTIVITY)
(NAT=>LEBITS-INJECTIVITY)
(NAT=>BEBITS*-INJECTIVITY)
(NAT=>LEBITS*-INJECTIVITY)
(NAT=>BEBITS+-INJECTIVITY)
(NAT=>LEBITS+-INJECTIVITY)
(NAT=>BEBITS-OF-BEBITS=>NAT)
(NAT=>LEBITS-OF-LEBITS=>NAT)
(NAT=>BEBITS*-OF-BEBITS=>NAT)
(NAT=>LEBITS*-OF-LEBITS=>NAT)
(NAT=>BEBITS+-OF-BEBITS=>NAT)
(NAT=>LEBITS+-OF-LEBITS=>NAT)
(BEBITS=>NAT-INJECTIVITY)
(LEBITS=>NAT-INJECTIVITY)
(BEBITS=>NAT-INJECTIVITY*)
(LEBITS=>NAT-INJECTIVITY*)
(BEBITS=>NAT-INJECTIVITY+)
(LEBITS=>NAT-INJECTIVITY+)
(LEN-OF-NAT=>BEBITS*-LEQ-WIDTH)
(LEN-OF-NAT=>LEBITS*-LEQ-WIDTH)
(LEN-0-OF-NAT=>BEBITS*)
(LEN-0-OF-NAT=>LEBITS*)
(CONSP-OF-NAT=>BEBITS*-IFF-NOT-ZP
     (10 5
         (:TYPE-PRESCRIPTION CONSP-OF-NAT=>BENDIAN*)))
(CONSP-OF-NAT=>LEBITS*-IFF-NOT-ZP
     (10 5
         (:TYPE-PRESCRIPTION CONSP-OF-NAT=>LENDIAN*)))
(TRIM-BENDIAN*-OFNAT=>BEBITS*
     (10 5
         (:TYPE-PRESCRIPTION CONSP-OF-NAT=>BENDIAN*))
     (5 5 (:TYPE-PRESCRIPTION ZP)))
(TRIM-LENDIAN*-OFNAT=>LEBITS*
     (10 5
         (:TYPE-PRESCRIPTION CONSP-OF-NAT=>LENDIAN*))
     (5 5 (:TYPE-PRESCRIPTION ZP)))
(BEBITS=>NAT-OF-APPEND)
(LEBITS=>NAT-OF-APPEND)
(BEBITS=>NAT-OF-ALL-ZERO-CONSTANT)
(LEBITS=>NAT-OF-ALL-ZERO-CONSTANT)
(BEBITS=>NAT-UPPER-BOUND)
(LEBITS=>NAT-UPPER-BOUND)
