(KEYWORD-TO-ACL2-PACKAGE)
(KEYWORDS-TO-ACL2-PACKAGE-AUX
     (8 4
        (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP-CHEAP))
     (5 5 (:REWRITE DEFAULT-CAR))
     (4 4 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
     (4 4
        (:REWRITE DEFAULT-SYMBOL-PACKAGE-NAME))
     (2 2 (:REWRITE DEFAULT-CDR)))
(LEN-OF-KEYWORDS-TO-ACL2-PACKAGE-AUX (61 30 (:REWRITE DEFAULT-+-2))
                                     (39 30 (:REWRITE DEFAULT-+-1))
                                     (21 19 (:REWRITE DEFAULT-CDR))
                                     (4 4 (:REWRITE FOLD-CONSTS-IN-+))
                                     (4 4 (:REWRITE DEFAULT-CAR)))
(SYMBOL-LISTP-OF-KEYWORDS-TO-ACL2-PACKAGE-AUX
     (51 10 (:REWRITE SYMBOL-LISTP-OF-CDR))
     (24 10
         (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP-CHEAP))
     (15 13 (:REWRITE DEFAULT-CAR))
     (14 12 (:REWRITE DEFAULT-CDR)))
(TRUE-LISTP-OF-KEYWORDS-TO-ACL2-PACKAGE-AUX (15 13 (:REWRITE DEFAULT-CDR))
                                            (3 3 (:REWRITE DEFAULT-CAR)))
(CONSP-OF-KEYWORDS-TO-ACL2-PACKAGE-AUX (5 5 (:REWRITE DEFAULT-CDR))
                                       (4 4 (:REWRITE DEFAULT-CAR)))
(KEYWORDS-TO-ACL2-PACKAGE)
(LEN-OF-KEYWORDS-TO-ACL2-PACKAGE)
(SYMBOL-LISTP-OF-KEYWORDS-TO-ACL2-PACKAGE)
(CONSP-OF-KEYWORDS-TO-ACL2-PACKAGE)
