(MY-<)
(MY-<=)
(POLARITY-TEST-THEOREM
 (2 2 (:REWRITE DEFAULT-<-2))
 (2 2 (:REWRITE DEFAULT-<-1))
 )
(POLARITY-TEST
 (1 1 (:REWRITE DEFAULT-<-2))
 (1 1 (:REWRITE DEFAULT-<-1))
 )
(POLARITY-TEST-THEOREM3
 (2 2 (:REWRITE DEFAULT-<-2))
 (2 2 (:REWRITE DEFAULT-<-1))
 )
(FOO)
(NOT-CONSP-WHEN-TRUE-LISTP-WEAKEN
 (2 1 (:DEFINITION TRUE-LISTP))
 (1 1 (:REWRITE DEFAULT-CDR))
 )
(TEST)
