(MILAWA::LOGIC.STRIP-CONCLUSIONS-OF-RESTN)
(MILAWA::LOGIC.STRIP-CONCLUSIONS-OF-FIRSTN)
(MILAWA::TACTIC.CREWRITE-FIRST-OKP
 (749
  7
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (707 14
      (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-WHEN-NOT-CONSP))
 (343
  7
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (321
  3
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (303 6
      (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-WHEN-NOT-CONSP))
 (258 32
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (191 31
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (152 32
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (147
  3
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (80 5
     (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (71 6 (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (66 5
     (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (54 54
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (54 54
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (54 54
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (46 1
     (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (42 42
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (42 42
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (37
    1
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (34 5
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (31 1 (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (30 10
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (30 5
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (26 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (26 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (26 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (26 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (26 26
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (26 26
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (26 26
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (26 26
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (26 26 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (14
  14
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (14
  14
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (10 10 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (10 10 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (10 10
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (10 10
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (10 10 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (10 10
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (7
  7
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (7
  7
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (6
  6
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (6
  6
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (6 6
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (6 6
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (6 6
    (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (5 5
    (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (5 5
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (5 5
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (5 5
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (5 5
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (5 5
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (5 5
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (5 5
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (4 4
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (4 4
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP))
 (3
  3
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (3
  3
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (2 2
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TRUE-LISTP-OF-RW.CREWRITE-CLAUSE-PLAN->FORCED-GOALS))
 (1 1
    (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE))
 (1 1
    (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END)))
(MILAWA::BOOLEANP-OF-TACTIC.CREWRITE-FIRST-OKP
 (148 7
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (129 7
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (120 18
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (110 2 (:REWRITE MILAWA::APP-WHEN-NOT-CONSP))
 (107
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (107
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (101 2
      (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-WHEN-NOT-CONSP))
 (101 2
      (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-WHEN-NOT-CONSP))
 (76 2
     (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (74 2
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (69 4 (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (67 15
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (62 2 (:DEFINITION NOT))
 (59 18
     (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (49
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (49
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (43 7
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (43 7
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (37
    1
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (34 4 (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (22 22
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (22 22
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (22 22
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (22 22
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (22 22
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (14 14 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (14 14
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (14 14
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (14 14 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (14 14
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (12 4
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (9 9 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (9 9
    (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (9 9
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (9 9
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (9 9 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (8 8
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (8 8
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (8 8
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (7 7
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (7 7
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (7 7
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (7 7
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (7 7
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (7 7
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (6 1
    (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (5 5
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (5 5
    (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (5 5
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (5 5
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (5 5
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (5 5
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (4 4 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (4 4
    (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (4 4
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (4 4
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (4 4
    (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (3 3
    (:REWRITE MILAWA::TRUE-LISTP-OF-RW.CREWRITE-CLAUSE-PLAN->FORCED-GOALS))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (2 2
    (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (2 2
    (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (2 2
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP))
 (1
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (1
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (1
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (1
  1
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (1 1
    (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP)))
(MILAWA::TACTIC.CREWRITE-FIRST-TAC
 (550 10
      (:REWRITE MILAWA::APP-WHEN-NOT-CONSP))
 (525 91
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (467 17
      (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (416 10
      (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (406
     10
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (310 10
      (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (215 5
      (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (207 52
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (195
    5
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (140 5
      (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (101 101
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (101 101
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (91 91
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (84 84
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (84 84
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (84 84
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (81 81
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (81 81
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (70 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (68 68
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (68 68
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (49 1
     (:REWRITE MILAWA::MAPP-WHEN-RW.FAST-CACHEMAPP))
 (46 1
     (:REWRITE MILAWA::RW.FAST-CACHEMAPP-WHEN-NOT-CONSP))
 (46 1
     (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-NOT-CONSP))
 (46 1
     (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-CONSP))
 (40 1
     (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (37 1
     (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (34 1
     (:REWRITE MILAWA::MAPP-WHEN-RW.CACHEMAPP))
 (31 1
     (:REWRITE MILAWA::RW.CACHEMAPP-WHEN-NOT-CONSP))
 (30 30
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (30 30
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (30 30
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (30 30
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (30 30 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (30 10
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (30 5
     (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (26 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (26 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (26 26
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (17 17
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (17 17
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (17 17
     (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (15 15
     (:REWRITE MILAWA::TRUE-LISTP-OF-RW.CREWRITE-CLAUSE-PLAN->FORCED-GOALS))
 (10 10 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (10 10
     (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-SUBSET-OF-SOMEP-ALT))
 (10 10
     (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-SUBSET-OF-SOMEP))
 (10
    10
    (:REWRITE
         MILAWA::LOGIC.TERM-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LISTP-ALT))
 (10
   10
   (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LISTP))
 (10 10
     (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-LOOKUP-IN-LOGIC.CALLMAPP))
 (10 10
     (:REWRITE MILAWA::LOGIC.TERM-LISTP-OF-RW.TRACE-LIST-RHSES-FREE))
 (10
   10
   (:REWRITE MILAWA::LOGIC.TERM-LISTP-OF-CAR-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (10 10
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (10 10
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (10 10
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (10 10
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (10 10
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (10 10
     (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (10 10
     (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (9
  9
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (9
  9
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (8 8
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
 (6
  6
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP-ALT))
 (6
  6
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP))
 (6 6
    (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-ALL-SUPERSET-OF-SOMEP-ALT))
 (6 6
    (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-ALL-SUPERSET-OF-SOMEP))
 (6
  6
  (:REWRITE
    MILAWA::LOGIC.TERM-LIST-LISTP-OF-SUBSETP-WHEN-LOGIC.TERM-LIST-LISTP-ALT))
 (6
   6
   (:REWRITE
        MILAWA::LOGIC.TERM-LIST-LISTP-OF-SUBSETP-WHEN-LOGIC.TERM-LIST-LISTP))
 (6
  6
  (:REWRITE
   MILAWA::FORCING-LOGIC.TERM-LIST-LISTP-OF-RW.CCSTEP-LIST-LIST-OBLIGATIONS-FREE))
 (6 6
    (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-SUPERSET-OF-SOME-IS-NON-CONSP))
 (6 6
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (6 6
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (6 6
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (6 6
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (5 5
    (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (4 4
    (:REWRITE MILAWA::LOOKUP-WHEN-MEMBERP-OF-SUBMAPP1))
 (4 4
    (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-TWO))
 (4 4
    (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-ONE))
 (1
   1
   (:REWRITE MILAWA::RW.FAST-CACHEMAPP-OF-SUBSET-WHEN-RW.FAST-CACHEMAPP-ALT))
 (1 1
    (:REWRITE MILAWA::RW.FAST-CACHEMAPP-OF-SUBSET-WHEN-RW.FAST-CACHEMAPP))
 (1 1
    (:REWRITE MILAWA::RW.CACHEMAPP-OF-SUBSET-WHEN-RW.CACHEMAPP-ALT))
 (1 1
    (:REWRITE MILAWA::RW.CACHEMAPP-OF-SUBSET-WHEN-RW.CACHEMAPP))
 (1 1
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (1 1
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP)))
(MILAWA::FORCING-TACTIC.SKELETONP-OF-TACTIC.CREWRITE-FIRST-TAC
 (220 4 (:REWRITE MILAWA::APP-WHEN-NOT-CONSP))
 (210 32
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (140 4
      (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (138 3
      (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (136
     4
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (124 4 (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (111
    3
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (93 3 (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (61 14
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (38 38
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (38 38
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (38 38
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (36 36
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (36 36
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (32 32
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (28 28
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (28 28
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (12 4
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (10 10
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (10 10
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (10 10
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (7 7
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (7 7
    (:REWRITE MILAWA::TRUE-LISTP-OF-RW.CREWRITE-CLAUSE-PLAN->FORCED-GOALS))
 (7 7 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (7 7
    (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (7 7
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (7 7
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (7 7 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (5
  5
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP-ALT))
 (5
  5
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP))
 (5 5
    (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-ALL-SUPERSET-OF-SOMEP-ALT))
 (5 5
    (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-ALL-SUPERSET-OF-SOMEP))
 (5
  5
  (:REWRITE
    MILAWA::LOGIC.TERM-LIST-LISTP-OF-SUBSETP-WHEN-LOGIC.TERM-LIST-LISTP-ALT))
 (5
   5
   (:REWRITE
        MILAWA::LOGIC.TERM-LIST-LISTP-OF-SUBSETP-WHEN-LOGIC.TERM-LIST-LISTP))
 (5
  5
  (:REWRITE
   MILAWA::FORCING-LOGIC.TERM-LIST-LISTP-OF-RW.CCSTEP-LIST-LIST-OBLIGATIONS-FREE))
 (5 5
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (5 5
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (5 5
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (5 5
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (4 4 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (4
  4
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (4
  4
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-SUBSET-OF-SOMEP-ALT))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-SUBSET-OF-SOMEP))
 (4 4
    (:REWRITE
         MILAWA::LOGIC.TERM-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LISTP-ALT))
 (4
   4
   (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LISTP))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-LOOKUP-IN-LOGIC.CALLMAPP))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-OF-RW.TRACE-LIST-RHSES-FREE))
 (4
   4
   (:REWRITE MILAWA::LOGIC.TERM-LISTP-OF-CAR-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (4 4
    (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (4 4
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (4 4
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (4 4
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (4 4
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (4 4
    (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (4 4
    (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (3 3
    (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (3 3
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (3 3
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (3 3
    (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (2 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP)))
(MILAWA::FORCING-TACTIC.CREWRITE-FIRST-OKP-OF-TACTIC.CREWRITE-FIRST-TAC
 (330 6 (:REWRITE MILAWA::APP-WHEN-NOT-CONSP))
 (288 46
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (204 6
      (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (198
     6
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (186 6 (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (185
    5
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (155 5 (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (138 3
      (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (95 22
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (92 2
     (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (52 52
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (52 52
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (52 52
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (52 52
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (52 52
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (46 46
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (42 42
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (42 42
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (38 38
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (38 38
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (18 6
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (12 2
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (12 2
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (11 11
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (11 11
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (11 11
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (11 11
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (11 11
     (:REWRITE MILAWA::TRUE-LISTP-OF-RW.CREWRITE-CLAUSE-PLAN->FORCED-GOALS))
 (11 11
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (11 11
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (11 11
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (11 11
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (11 11 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (9 9
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (9 9
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (9 9
    (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (8 8
    (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (8 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
 (8 2
    (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (6 6 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (6 6
    (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (6 6
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (6 6
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (6 6
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (6 6
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (6 6
    (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (4 4 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (4 4
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (4 4
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (4 4 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-SUBSET-OF-SOMEP-ALT))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-SUBSET-OF-SOMEP))
 (4 4
    (:REWRITE
         MILAWA::LOGIC.TERM-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LISTP-ALT))
 (4
   4
   (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LISTP))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-WHEN-LOOKUP-IN-LOGIC.CALLMAPP))
 (4 4
    (:REWRITE MILAWA::LOGIC.TERM-LISTP-OF-RW.TRACE-LIST-RHSES-FREE))
 (4
   4
   (:REWRITE MILAWA::LOGIC.TERM-LISTP-OF-CAR-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (4 4
    (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (3 3
    (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (2 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (2 2
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (2 2
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (2 2
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (2 2
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (2 2
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (2 2
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (2 2
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (2 2
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (2 2
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS)))
(MILAWA::TACTIC.CREWRITE-FIRST-COMPILE)
(MILAWA::TACTIC.CREWRITE-FIRST-COMPILE
 (7302 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (5461 69
       (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (3874 220
       (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (3854
  38
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (3636 72
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-WHEN-NOT-CONSP))
 (3570
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (3366 68
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-WHEN-NOT-CONSP))
 (3344 1191
       (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (3271 221
       (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (3174 14 (:REWRITE MILAWA::CONSP-OF-RESTN))
 (3084 16
       (:REWRITE MILAWA::LOGIC.DISJOIN-FORMULAS-WHEN-SINGLETON-LIST))
 (3056 418
       (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (2919
     93
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (2742 69
       (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (2573 43
       (:REWRITE MILAWA::ZP-WHEN-NATP-CHEAP))
 (2445 32
       (:REWRITE MILAWA::LOGIC.TERM-LIST-FORMULAS-WHEN-NOT-CONSP))
 (2150
    62
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (1764
  36
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (1678 40
       (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP))
 (1657 1657
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (1657 1657
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (1636
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (1605 1605
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (1559 16 (:REWRITE MILAWA::ANTISYMMETRY-OF-<))
 (1518 33
       (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (1502 1502
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (1502 1502
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (1502 1502
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (1502 1502
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (1496 1496
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (1465 1465
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (1465 1465
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (1452 1452
       (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (1452 1452
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (1409 16
       (:REWRITE MILAWA::CDR-OF-LOGIC.TERM-LIST-FORMULAS))
 (1403 32
       (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-FORMULAS))
 (1266 39
       (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (1225 202
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (1216 18
       (:REWRITE MILAWA::EQUAL-OF-LEN-AND-ZERO))
 (1199 202
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (950 418 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (947 947
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (947 947
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (946 946
      (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (945 45
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (603 30
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (543 15
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (483 161
      (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (446 446
      (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (446 446
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (446 446
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (446 446
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (446 446
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (442 442
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (442 442
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (442 442 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (418 418
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (418 418
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (418 418
      (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (363 363
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (363 363
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (363 363
      (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (345 345
      (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (334 334
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (334 334
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (334 334
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (334 334
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (334 334
      (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (334 334
      (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (221 221
      (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (220 220
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (220 220
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (220 220
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (220 220
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (220 220
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (197 197
      (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (171 171
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (161 161
      (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (118 30
      (:REWRITE MILAWA::RESTN-WHEN-NOT-NATP))
 (115 43
      (:REWRITE MILAWA::ZP-WHEN-NOT-NATP-CHEAP))
 (94 30
     (:REWRITE MILAWA::NFIX-WHEN-NOT-NATP-CHEAP))
 (73 9
     (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP))
 (72
  72
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (72
  72
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (62 30
     (:REWRITE MILAWA::NFIX-WHEN-ZP-CHEAP))
 (55 55
     (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP))
 (42
  42
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (42
    42
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (40 40 (:REWRITE MILAWA::LEN-WHEN-TUPLEP))
 (40 40
     (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP-OF-CDR-CHEAP))
 (39 39
     (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (38
  38
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (38
  38
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (38 1 (:REWRITE MILAWA::MEMBERP-OF-CAR))
 (36 36
     (:REWRITE
          MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (35 35
     (:REWRITE
          MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (34 16
     (:REWRITE MILAWA::LESS-WHEN-ZP-RIGHT-CHEAP))
 (16 16
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-FOUR))
 (16 16
     (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP-ALT))
 (16 16
     (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP))
 (15 15
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (15 15
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (12 3
     (:REWRITE MILAWA::SUBSETP-WHEN-PREFIXP-CHEAP))
 (10 10
     (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE))
 (9 9
    (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP-ALT))
 (3 3
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-TWO))
 (3 3
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-ONE))
 (3 3
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CONS))
 (3 3
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CDR))
 (3 3
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-TWO))
 (3 3
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-ONE))
 (3 3
    (:REWRITE MILAWA::ORDERED-SUBSETP-OF-CDR-WHEN-ORDERED-SUBSETP))
 (3 3
    (:REWRITE MILAWA::CONSP-OF-RW.CREWRITE-CLAUSE-PLAN->CLAUSE-PRIME)))
(MILAWA::FORCING-LOGIC.APPEAL-LISTP-OF-TACTIC.CREWRITE-FIRST-COMPILE
 (7269 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (3638
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (3638
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (3434 68
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-WHEN-NOT-CONSP))
 (3434 68
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-WHEN-NOT-CONSP))
 (3386 1222
       (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (3174 195
       (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (3084 16
       (:REWRITE MILAWA::LOGIC.DISJOIN-FORMULAS-WHEN-SINGLETON-LIST))
 (2957
     95
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (2639 199
       (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (2527 65
       (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (2445 32
       (:REWRITE MILAWA::LOGIC.TERM-LIST-FORMULAS-WHEN-NOT-CONSP))
 (2281 65
       (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (2224
    64
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (1667 1667
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (1667 1667
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (1666
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (1666
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (1630 1630
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (1564 34
       (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (1523 1523
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (1523 1523
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (1523 1523
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (1523 1523
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (1509 1509
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (1478 1478
       (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (1478 1478
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (1477 1477
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (1477 1477
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (1423 28
       (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP))
 (1409 16
       (:REWRITE MILAWA::CDR-OF-LOGIC.TERM-LIST-FORMULAS))
 (1403 32
       (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-FORMULAS))
 (1394 41
       (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (1268 372
       (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (1149 184
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (1105 184
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (995 927
      (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (945 45
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (928 928
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (928 928
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (872 12
      (:REWRITE MILAWA::ZP-WHEN-NATP-CHEAP))
 (603 30
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (543 15
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (483 2 (:REWRITE MILAWA::FIRSTN-OF-TOO-MANY))
 (474 158
      (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (455 455
      (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (455 455
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (455 455
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (455 455
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (455 455
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (444 372 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (422 6
      (:REWRITE MILAWA::EQUAL-OF-LEN-AND-ZERO))
 (401 401
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (401 401
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (401 401
      (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (384 384
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (384 384
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (384 384 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (372 372
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (372 372
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (372 372
      (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (372 372
      (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (339 339
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (339 339
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (339 339
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (339 339
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (338 338
      (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (338 338
      (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (316 2 (:REWRITE MILAWA::ANTISYMMETRY-OF-<))
 (277 2 (:REWRITE MILAWA::SUBSETP-OF-CONS))
 (199 199
      (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (195 195
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (195 195
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (195 195
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (195 195
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (195 195
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (186 186
      (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (159 159
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (158 158
      (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (145 1
      (:REWRITE MILAWA::SUBSETP-WHEN-NOT-CONSP))
 (122 26
      (:REWRITE MILAWA::RESTN-WHEN-NOT-NATP))
 (112 1 (:REWRITE MILAWA::CONSP-OF-FIRSTN))
 (71 10
     (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (56 56
     (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP))
 (55 1 (:REWRITE MILAWA::|(< 0 (len x))|))
 (43
  43
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (43
    43
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (41 41
     (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (37 37
     (:REWRITE
          MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (36 12
     (:REWRITE MILAWA::ZP-WHEN-NOT-NATP-CHEAP))
 (35 1
     (:REWRITE MILAWA::SUBSETP-WHEN-NOT-CONSP-TWO))
 (34 34
     (:REWRITE
          MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (34
    34
    (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (32 32
     (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP-OF-CDR-CHEAP))
 (32 1 (:REWRITE MILAWA::MEMBERP-OF-CAR))
 (30 30
     (:REWRITE MILAWA::FORCING-CONS-LISTP-OF-TACTIC.SKELETON->GOALS))
 (28 28 (:REWRITE MILAWA::LEN-WHEN-TUPLEP))
 (24 6
     (:REWRITE MILAWA::SUBSETP-WHEN-PREFIXP-CHEAP))
 (22 6
     (:REWRITE MILAWA::NFIX-WHEN-NOT-NATP-CHEAP))
 (15 15
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (15 15
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (14 6 (:REWRITE MILAWA::NFIX-WHEN-ZP-CHEAP))
 (12 12
     (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE))
 (10 10
     (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP-ALT))
 (7 7
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CONS))
 (7 7
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CDR))
 (7 7
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-TWO))
 (7 7
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-ONE))
 (6 6
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-TWO))
 (6 6
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-ONE))
 (6 2
    (:REWRITE MILAWA::LESS-WHEN-ZP-RIGHT-CHEAP))
 (3 3
    (:REWRITE MILAWA::ORDERED-SUBSETP-OF-CDR-WHEN-ORDERED-SUBSETP))
 (3 3
    (:REWRITE MILAWA::CONSP-OF-RW.CREWRITE-CLAUSE-PLAN->CLAUSE-PRIME))
 (3 3
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP-ALT))
 (3 3
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP))
 (2 2
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-FOUR))
 (1 1
    (:REWRITE MILAWA::SUBSETP-OF-FIRSTN-WHEN-IN-RANGE)))
(MILAWA::FORCING-LOGIC.STRIP-CONCLUSIONS-OF-TACTIC.CREWRITE-FIRST-COMPILE
 (11958 2530
        (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (6462 357
       (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (5885
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (5885
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (5680 2106
       (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (5555 110
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-WHEN-NOT-CONSP))
 (5555 110
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-WHEN-NOT-CONSP))
 (5481 357
       (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (4984 28
       (:REWRITE MILAWA::LOGIC.DISJOIN-FORMULAS-WHEN-SINGLETON-LIST))
 (4982 24
       (:REWRITE MILAWA::FIRSTN-OF-TOO-MANY))
 (4904 675
       (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (4652 118
       (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (4614 118
       (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (4130 75
       (:REWRITE MILAWA::ZP-WHEN-NATP-CHEAP))
 (4104
     132
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (3940 54
       (:REWRITE MILAWA::LOGIC.TERM-LIST-FORMULAS-WHEN-NOT-CONSP))
 (3149
    89
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (2793 2793
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (2793 2793
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (2761 71
       (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (2750 2750
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (2695
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (2695
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (2559 2559
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (2559 2559
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (2559 2559
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (2559 2559
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (2530 2530
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (2530 55
       (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (2482 2482
       (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (2482 2482
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (2479 2479
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (2479 2479
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (2326 66
       (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (2278 26
       (:REWRITE MILAWA::CDR-OF-LOGIC.TERM-LIST-FORMULAS))
 (2262 52
       (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-FORMULAS))
 (2004 323
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (1951 323
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (1938 29
       (:REWRITE MILAWA::EQUAL-OF-LEN-AND-ZERO))
 (1621 675 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (1516 72
       (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (1474 1474
       (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (1474 1474
       (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (1473 1473
       (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (966 48
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (870 24
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (795 795
      (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (795 795
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (795 795
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (795 795
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (795 795
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (789 263
      (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (725 725
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (725 725
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (725 725 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (675 675
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (675 675
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (675 675
      (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (671 19
      (:REWRITE MILAWA::LEN-OF-LOGIC.STRIP-CONCLUSIONS))
 (632 4 (:REWRITE MILAWA::ANTISYMMETRY-OF-<))
 (630 630
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (630 630
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (630 630
      (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (615 615
      (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (560 560
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (560 560
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (560 560
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (558 558
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (557 557
      (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (557 557
      (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (357 357
      (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (357 357
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (357 357
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (357 357
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (357 357
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (357 357
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (322 322
      (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (273 273
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (212 44
      (:REWRITE MILAWA::NFIX-WHEN-NOT-NATP-CHEAP))
 (191 75
      (:REWRITE MILAWA::ZP-WHEN-NOT-NATP-CHEAP))
 (128 44
      (:REWRITE MILAWA::NFIX-WHEN-ZP-CHEAP))
 (122 26
      (:REWRITE MILAWA::RESTN-WHEN-NOT-NATP))
 (110
  110
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (110
  110
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (110
  110
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (110
  110
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (109 18
      (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP))
 (98 98
     (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP-OF-CDR-CHEAP))
 (89 89
     (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP))
 (71 71 (:REWRITE MILAWA::LEN-WHEN-TUPLEP))
 (66 66
     (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (58
  58
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (58
    58
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (55 55
     (:REWRITE
          MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (55
    55
    (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP))
 (55
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (55
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (55
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (55
  55
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (54 54
     (:REWRITE
          MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (52 48
     (:REWRITE MILAWA::FORCING-CONS-LISTP-OF-TACTIC.SKELETON->GOALS))
 (38 1 (:REWRITE MILAWA::MEMBERP-OF-CAR))
 (33 1 (:REWRITE MILAWA::|(< 0 (len x))|))
 (24 24
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (24 24
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (18 18
     (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP-ALT))
 (12 4
     (:REWRITE MILAWA::LESS-WHEN-ZP-RIGHT-CHEAP))
 (8 2
    (:REWRITE MILAWA::SUBSETP-WHEN-PREFIXP-CHEAP))
 (6 6
    (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE))
 (6 6
    (:REWRITE MILAWA::CONSP-OF-RW.CREWRITE-CLAUSE-PLAN->CLAUSE-PRIME))
 (4 4
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-FOUR))
 (4 4
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP-ALT))
 (4 4
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP))
 (2 2
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-TWO))
 (2 2
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-ONE))
 (2 2
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CONS))
 (2 2
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CDR))
 (2 2
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-TWO))
 (2 2
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-ONE))
 (2 2
    (:REWRITE MILAWA::ORDERED-SUBSETP-OF-CDR-WHEN-ORDERED-SUBSETP)))
(MILAWA::FORCING-LOGIC.PROOF-LISTP-OF-TACTIC.CREWRITE-FIRST-COMPILE
 (50559 6843
        (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (47740 1364
        (:REWRITE MILAWA::MEMBERP-WHEN-NOT-CONSP))
 (26805 4841
        (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (17732 1364
        (:REWRITE MILAWA::MEMBERP-WHEN-NOT-SUPERSET-OF-SOMEP-CHEAP))
 (17732 1364
        (:REWRITE MILAWA::MEMBERP-WHEN-NOT-SUBSET-OF-SOMEP-CHEAP))
 (12415 384
        (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (11569 325
        (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (8184 1364
       (:REWRITE MILAWA::MEMBERP-WHEN-LOGIC.ALL-TERMS-LARGER-CHEAP))
 (6845 6845
       (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (6845 6845
       (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (5828 248
       (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (4999 4999
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (4999 4999
       (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (4966 1692
       (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (4962 4962
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (4855 4855
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (4855 4855
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (4855 4855
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (4855 4855
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (4841 4841
       (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (4809 4809
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (4809 4809
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (4682 4682
       (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (4682 4682
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (3638
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (3638
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-OF-CAR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (3434 68
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-WHEN-NOT-CONSP))
 (3434 68
       (:REWRITE MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-WHEN-NOT-CONSP))
 (3084 16
       (:REWRITE MILAWA::LOGIC.DISJOIN-FORMULAS-WHEN-SINGLETON-LIST))
 (2957
     95
     (:REWRITE MILAWA::CONSP-OF-CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS))
 (2575 370
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (2529 67
       (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (2445 32
       (:REWRITE MILAWA::LOGIC.TERM-LIST-FORMULAS-WHEN-NOT-CONSP))
 (2283 67
       (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (2226
    66
    (:REWRITE
         MILAWA::CLAUSE.MAKE-CLAUSES-FROM-ARBITRARY-FORMULAS-WHEN-NOT-CONSP))
 (1911 370
       (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (1860 1860
       (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (1666
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (1666
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-CDR-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (1564 34
       (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (1454 558
       (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (1426 31
       (:REWRITE MILAWA::TACTIC.WORLD-LIST-ENV-OKP-WHEN-NOT-CONSP))
 (1426 31
       (:REWRITE MILAWA::TACTIC.WORLD-LIST-ATBLP-WHEN-NOT-CONSP))
 (1423 28
       (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP))
 (1409 16
       (:REWRITE MILAWA::CDR-OF-LOGIC.TERM-LIST-FORMULAS))
 (1403 32
       (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-FORMULAS))
 (1394 41
       (:REWRITE MILAWA::APP-WHEN-NOT-CONSP-TWO))
 (1364
  1364
  (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUPERSET-OF-SOMEP-OF-SMALLER-ALT))
 (1364
      1364
      (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUPERSET-OF-SOMEP-OF-SMALLER))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUBSETP-TWO-ALT))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUBSETP-TWO))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-OBVIOUS-ALT))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-OBVIOUS))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-NOT-CONSP))
 (1364
   1364
   (:REWRITE
        MILAWA::SUPERSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUPERSET-OF-SOMEP-ALT))
 (1364
  1364
  (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUPERSET-OF-SOMEP))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-FIND-SUBSET))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-ALL-SUPERSET-OF-SOMEP-ALT))
 (1364 1364
       (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-ALL-SUPERSET-OF-SOMEP))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSETP-TWO-ALT))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSETP-TWO))
 (1364
      1364
      (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSET-OF-SOMEP-OF-SMALLER-ALT))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSET-OF-SOMEP-OF-SMALLER))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-OBVIOUS-ALT))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-OBVIOUS))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-NOT-CONSP))
 (1364
  1364
  (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUBSET-OF-SOMEP-ALT))
 (1364
      1364
      (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUBSET-OF-SOMEP))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-FIND-SUPERSET))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-ALL-SUBSET-OF-SOMEP-ALT))
 (1364 1364
       (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-ALL-SUBSET-OF-SOMEP))
 (1364 1364
       (:REWRITE MILAWA::NOT-IN-SUBSET-WHEN-NOT-IN-SUPERSET-TWO))
 (1364 1364
       (:REWRITE MILAWA::NOT-IN-SUBSET-WHEN-NOT-IN-SUPERSET-ONE))
 (1364 1364
       (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-MEMBER-OF-NONEP-ALT))
 (1364 1364
       (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-MEMBER-OF-NONEP))
 (1364 1364
       (:REWRITE MILAWA::MEMBERP-WHEN-DISJOINTP-TWO))
 (1364 1364
       (:REWRITE MILAWA::MEMBERP-WHEN-DISJOINTP-ONE))
 (1364
  1364
  (:REWRITE
    MILAWA::LOGIC.ALL-TERMS-LARGERP-WHEN-NOT-LOGIC.ALL-TERMS-LARGERP-BADGUY))
 (1364 1364
       (:REWRITE MILAWA::LOGIC.ALL-TERMS-LARGERP-WHEN-NOT-CONSP))
 (1364
  1364
  (:REWRITE
   MILAWA::LOGIC.ALL-TERMS-LARGERP-OF-SUBSETP-WHEN-LOGIC.ALL-TERMS-LARGERP-ALT))
 (1364
  1364
  (:REWRITE
    MILAWA::LOGIC.ALL-TERMS-LARGERP-OF-SUBSETP-WHEN-LOGIC.ALL-TERMS-LARGERP))
 (1364
  1364
  (:REWRITE
       MILAWA::ALL-TERMS-LARGER-WHEN-ALL-TERMS-LARGER-THAN-SOMETHING-BIGGER))
 (1077 49
       (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (965 105
      (:REWRITE MILAWA::ZP-WHEN-NATP-CHEAP))
 (775 31 (:REWRITE MILAWA::LESS-OF-ONE-LEFT))
 (744 124
      (:REWRITE MILAWA::CONSP-OF-LOOKUP-UNDER-IFF))
 (703 703
      (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (703 703
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (703 703
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (703 703
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (703 703
      (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (685 34
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (630 558 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (620 620
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (620 620
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (617 17
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (606 606
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (606 606
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (606 606 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (561 561
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (561 561
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (561 561
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (561 561
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (560 560
      (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (560 560
      (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (558 558
      (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (483 2 (:REWRITE MILAWA::FIRSTN-OF-TOO-MANY))
 (474 158
      (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (422 6
      (:REWRITE MILAWA::EQUAL-OF-LEN-AND-ZERO))
 (401 401
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (401 401
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (401 401
      (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (384 384
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (384 384
      (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (384 384
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (384 384
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (384 384
      (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (375 375
      (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (368 8
      (:REWRITE MILAWA::LOGIC.PROOFP-WHEN-NOT-CONSP))
 (325 325
      (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (316 2 (:REWRITE MILAWA::ANTISYMMETRY-OF-<))
 (277 2 (:REWRITE MILAWA::SUBSETP-OF-CONS))
 (248 248
      (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (220 4
      (:REWRITE MILAWA::LOGIC.TERM-LIST-ATBLP-WHEN-LOGIC.VARIABLE-LISTP))
 (212 2
      (:REWRITE MILAWA::LOGIC.VARIABLE-LISTP-WHEN-NOT-CONSP))
 (161 161
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (158 158
      (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (145 1
      (:REWRITE MILAWA::SUBSETP-WHEN-NOT-CONSP))
 (130 4
      (:REWRITE MILAWA::LOGIC.TERM-LIST-ATBLP-WHEN-LOGIC.CONSTANT-LISTP))
 (129 105
      (:REWRITE MILAWA::ZP-WHEN-NOT-NATP-CHEAP))
 (124 124
      (:REWRITE MILAWA::LOOKUP-WHEN-MEMBERP-OF-SUBMAPP1))
 (124 124
      (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-TWO))
 (124 124
      (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-ONE))
 (124 28
      (:REWRITE MILAWA::RESTN-WHEN-NOT-NATP))
 (122 2
      (:REWRITE MILAWA::LOGIC.CONSTANT-LISTP-WHEN-NOT-CONSP))
 (112 1 (:REWRITE MILAWA::CONSP-OF-FIRSTN))
 (93 31 (:REWRITE MILAWA::LESS-OF-ONE-RIGHT))
 (71 10
     (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LISTP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (68
  68
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-OF-SUBSETP-WHEN-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (56 56
     (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP))
 (55 1 (:REWRITE MILAWA::|(< 0 (len x))|))
 (41
  41
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (41
    41
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (41 41
     (:REWRITE MILAWA::APP-OF-SINGLETON-LIST-CHEAP))
 (39
  39
  (:REWRITE
       MILAWA::LOGIC.PROOF-LISTP-WHEN-MEMBERP-OF-LOGIC.PROOF-LIST-LISTP-ALT))
 (39 39
     (:REWRITE
          MILAWA::LOGIC.PROOF-LISTP-WHEN-MEMBERP-OF-LOGIC.PROOF-LIST-LISTP))
 (39 39
     (:REWRITE MILAWA::LOGIC.PROOF-LISTP-IN-LARGER-THEOREM-SET))
 (39 39
     (:REWRITE MILAWA::LOGIC.PROOF-LISTP-IN-LARGER-AXIOM-SET))
 (38 34
     (:REWRITE MILAWA::FORCING-CONS-LISTP-OF-TACTIC.SKELETON->GOALS))
 (35
  35
  (:REWRITE MILAWA::LOGIC.PROOF-LISTP-OF-SUBSETP-WHEN-LOGIC.PROOF-LISTP-ALT))
 (35 35
     (:REWRITE
          MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (35 1
     (:REWRITE MILAWA::SUBSETP-WHEN-NOT-CONSP-TWO))
 (34 34
     (:REWRITE
          MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (34
    34
    (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP-ALT))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLANP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LISTP))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP-ALT))
 (34
  34
  (:REWRITE
   MILAWA::RW.CREWRITE-CLAUSE-PLAN-OKP-WHEN-MEMBERP-OF-RW.CREWRITE-CLAUSE-PLAN-LIST-OKP))
 (32 32
     (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP-OF-CDR-CHEAP))
 (32 8
     (:REWRITE MILAWA::SUBSETP-WHEN-PREFIXP-CHEAP))
 (31
  31
  (:REWRITE
   MILAWA::TACTIC.WORLD-LIST-ENV-OKP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ENV-OKP-ALT))
 (31
  31
  (:REWRITE
   MILAWA::TACTIC.WORLD-LIST-ENV-OKP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ENV-OKP))
 (31
  31
  (:REWRITE
   MILAWA::TACTIC.WORLD-LIST-ATBLP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ATBLP-ALT))
 (31
  31
  (:REWRITE
    MILAWA::TACTIC.WORLD-LIST-ATBLP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ATBLP))
 (28 28 (:REWRITE MILAWA::LEN-WHEN-TUPLEP))
 (22 6
     (:REWRITE MILAWA::NFIX-WHEN-NOT-NATP-CHEAP))
 (17 17
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (17 17
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (16 16
     (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE))
 (14 6 (:REWRITE MILAWA::NFIX-WHEN-ZP-CHEAP))
 (10 10
     (:REWRITE MILAWA::LOGIC.APPEALP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LISTP-ALT))
 (9 9
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CONS))
 (9 9
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-ORDERED-SUBSETP-OF-CDR))
 (9 9
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-TWO))
 (9 9
    (:REWRITE MILAWA::ORDERED-SUBSETP-WHEN-NOT-CONSP-ONE))
 (9 9
    (:REWRITE MILAWA::LOGIC.PROOFP-WHEN-MEMBERP-OF-LOGIC.PROOF-LISTP-ALT))
 (9 9
    (:REWRITE MILAWA::LOGIC.PROOFP-IN-LARGER-THEOREM-SET))
 (9 9
    (:REWRITE MILAWA::LOGIC.PROOFP-IN-LARGER-AXIOM-SET))
 (8 8
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-TWO))
 (8 8
    (:REWRITE MILAWA::SUBSETP-TRANSITIVE-ONE))
 (6 2
    (:REWRITE MILAWA::LESS-WHEN-ZP-RIGHT-CHEAP))
 (5 5
    (:REWRITE MILAWA::ORDERED-SUBSETP-OF-CDR-WHEN-ORDERED-SUBSETP))
 (4
  4
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-ATBLP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-ATBLP-ALT))
 (4
  4
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-ATBLP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-ATBLP))
 (4 4
    (:REWRITE
         MILAWA::LOGIC.TERM-LIST-ATBLP-WHEN-LOOKUP-IN-LOGIC.CALLMAP-ATBLP))
 (4
  4
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-ATBLP-WHEN-LOGIC.TERM-LIST-ATBLP-IN-SMALLER-ARITY-TABLE-ALT))
 (4
  4
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-ATBLP-WHEN-LOGIC.TERM-LIST-ATBLP-IN-SMALLER-ARITY-TABLE))
 (4
  4
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-ATBLP-OF-CAR-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (4 4
    (:REWRITE MILAWA::FORCING-LOGIC.TERM-LIST-ATBLP-OF-LOGIC.=RHSES-FREE))
 (3 3
    (:REWRITE MILAWA::CONSP-OF-RW.CREWRITE-CLAUSE-PLAN->CLAUSE-PRIME))
 (3 3
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP-ALT))
 (3 3
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP))
 (2 2
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-FOUR))
 (2
  2
  (:REWRITE
      MILAWA::LOGIC.VARIABLE-LISTP-OF-SUBSETP-WHEN-LOGIC.VARIABLE-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.VARIABLE-LISTP-OF-SUBSETP-WHEN-LOGIC.VARIABLE-LISTP))
 (2
  2
  (:REWRITE
      MILAWA::LOGIC.CONSTANT-LISTP-OF-SUBSETP-WHEN-LOGIC.CONSTANT-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.CONSTANT-LISTP-OF-SUBSETP-WHEN-LOGIC.CONSTANT-LISTP))
 (1 1
    (:REWRITE MILAWA::SUBSETP-OF-FIRSTN-WHEN-IN-RANGE)))
