(MILAWA::TACTIC.UREWRITE-ALL-OKP
 (2610 6
       (:REWRITE MILAWA::RW.TRACE-LIST-LISTP-WHEN-NOT-CONSP))
 (1866 79
       (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (1434 45
       (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (1326 6
       (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (1254 24
       (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (1001 11
       (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (960 18
      (:REWRITE MILAWA::NONE-CONSP-OF-CDR-WHEN-NONE-CONSP))
 (888 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (876 24
      (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-CONSP))
 (732 18
      (:REWRITE MILAWA::CONS-LISTP-OF-CDR-WHEN-CONS-LISTP))
 (472 13
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (440 13
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (426 171
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (417 194
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (333 46
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (322 7
      (:REWRITE MILAWA::TUPLEP-WHEN-TRUE-LISTP))
 (322 7
      (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (269 7
      (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (245 7
      (:REWRITE MILAWA::TUPLEP-WHEN-NOT-CONSP))
 (212 212
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (212 212
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (194 194
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (189 189
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (189 189
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (145 5
      (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (102 102
      (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (102 102
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (102 102
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (97 97
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (97 97
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (97 97
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (97 97
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (97 97
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (84 13
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (79 79
     (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (78 13
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (59 59
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (59 59
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (58 58
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (58 58
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (58 58
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (54 18
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (45 45
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (45 45
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (45 45
     (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (44 44
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (44 44
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (44 44
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (44 44
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (44 44 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (41 41
     (:REWRITE MILAWA::CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (41
    41
    (:REWRITE MILAWA::CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (35 5
     (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (26 26 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (26 26
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (26 26
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (26 26 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (26 26
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (24 24
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (24 24
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (24 24
     (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (24 24
     (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (24 24
     (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (24 24
     (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (23 23
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (18 18 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (13 13
     (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (13 13
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (13 13
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (13 13
     (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (13 13
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (13 13
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (13 13
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (11 11
     (:REWRITE MILAWA::NATP-OF-CAR-WHEN-NAT-LISTP))
 (11 11
     (:REWRITE MILAWA::CDR-OF-CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (11
  11
  (:REWRITE
       MILAWA::CDR-OF-CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (8 8
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (7 7 (:REWRITE MILAWA::TUPLEP-WHEN-ZP))
 (7 7
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP-ALT))
 (7 7
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP))
 (7 7
    (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (6 6
    (:REWRITE MILAWA::TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (6 6
    (:REWRITE MILAWA::SECOND-UNDER-IFF-WHEN-LOGIC.TERM-LISTP-WITH-LEN-FREE))
 (6
   6
   (:REWRITE
        MILAWA::RW.TRACE-LIST-LISTP-OF-SUBSETP-WHEN-RW.TRACE-LIST-LISTP-ALT))
 (6
  6
  (:REWRITE MILAWA::RW.TRACE-LIST-LISTP-OF-SUBSETP-WHEN-RW.TRACE-LIST-LISTP))
 (6 6
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (6 6
    (:REWRITE MILAWA::FIRST-UNDER-IFF-WHEN-LOGIC.TERM-LISTP-WITH-LEN-FREE))
 (6 6
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP))
 (1 1
    (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE)))
(MILAWA::BOOLEANP-OF-TACTIC.UREWRITE-ALL-OKP
 (435 1
      (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (221 1
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (209 4
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (167 2
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (160 3
      (:REWRITE MILAWA::NONE-CONSP-OF-CDR-WHEN-NONE-CONSP))
 (148 7
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (146 4
      (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-CONSP))
 (144 4 (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (129 7
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (123 25
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (122 3
      (:REWRITE MILAWA::CONS-LISTP-OF-CDR-WHEN-CONS-LISTP))
 (108 6 (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (67 22
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (65 25
     (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (62 2 (:DEFINITION NOT))
 (57 1
     (:REWRITE MILAWA::RW.FAST-UREWRITE-LIST-LIST-REMOVAL))
 (49 8
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (47 1
     (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (47 1
     (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-NOT-CONSP))
 (46 1
     (:REWRITE MILAWA::TUPLEP-WHEN-TRUE-LISTP))
 (43 7
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (42 7
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (35 1
     (:REWRITE MILAWA::TUPLEP-WHEN-NOT-CONSP))
 (30 2
     (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (28 28
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (28 28
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (25 25
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (16 16
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (16 16
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (16 16
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (14 14 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (14 14
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (14 14
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (14 14 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (14 14
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (13 2
     (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (11 11
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (10 10
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (10 10
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (10 10
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (9 9 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (9 9
    (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (9 9
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (9 9
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (9 9 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (9 3
    (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (7 7
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (7 7
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (7 7
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (7 7
    (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (7 7
    (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (7 7
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (7 7
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (7 7
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (6 6
    (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (5 5
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (4 4
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (4 4
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (4 4
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (4 4
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (4 4
    (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (3 3 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (3 3
    (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (3 3
    (:REWRITE MILAWA::CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (3 3
    (:REWRITE MILAWA::CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (2 2
    (:REWRITE MILAWA::NATP-OF-CAR-WHEN-NAT-LISTP))
 (2 2
    (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (2
  1
  (:REWRITE MILAWA::FORCING-LOGIC.TERM-LIST-LISTP-OF-TACTIC.SKELETON->GOALS))
 (1 1 (:REWRITE MILAWA::TUPLEP-WHEN-ZP))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP))
 (1 1
    (:REWRITE MILAWA::TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (1
  1
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP-ALT))
 (1
  1
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP))
 (1 1
    (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-ALL-SUPERSET-OF-SOMEP-ALT))
 (1 1
    (:REWRITE MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-ALL-SUPERSET-OF-SOMEP))
 (1
  1
  (:REWRITE
    MILAWA::LOGIC.TERM-LIST-LISTP-OF-SUBSETP-WHEN-LOGIC.TERM-LIST-LISTP-ALT))
 (1
   1
   (:REWRITE
        MILAWA::LOGIC.TERM-LIST-LISTP-OF-SUBSETP-WHEN-LOGIC.TERM-LIST-LISTP))
 (1 1
    (:REWRITE MILAWA::FORCING-TACTIC.SKELETONP-OF-TACTIC.SKELETON->HISTORY))
 (1
  1
  (:REWRITE
   MILAWA::FORCING-LOGIC.TERM-LIST-LISTP-OF-RW.CCSTEP-LIST-LIST-OBLIGATIONS-FREE))
 (1 1
    (:REWRITE MILAWA::CDR-OF-CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (1
  1
  (:REWRITE
       MILAWA::CDR-OF-CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (1 1
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP)))
(MILAWA::TACTIC.UREWRITE-ALL-TAC
 (78 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (74 2
     (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (72 2
     (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (62 2
     (:REWRITE MILAWA::CONSP-OF-RW.UREWRITE-LIST-LIST))
 (56 2
     (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (49 1
     (:REWRITE MILAWA::MAPP-WHEN-RW.FAST-CACHEMAPP))
 (46 1
     (:REWRITE MILAWA::RW.FAST-CACHEMAPP-WHEN-NOT-CONSP))
 (46 1
     (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (34 1
     (:REWRITE MILAWA::MAPP-WHEN-RW.CACHEMAPP))
 (31 1
     (:REWRITE MILAWA::RW.CACHEMAPP-WHEN-NOT-CONSP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (18 8
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (18 8
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (16 16
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (16 16
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (16 16
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (14 8
     (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (13 3
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (12 2
     (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (10 10
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (10 10
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (10 10
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (8 8
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (8 8
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (8 8
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (4 4 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (4 4
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (4 4
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (4 4 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (4 4
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (4 4
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
 (4 4 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (4 4
    (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (4 4
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (4 4
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (4 4 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (4 4
    (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (2 2
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (2 2
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP))
 (2 2
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (2
  2
  (:REWRITE
   MILAWA::FORCING-LOGIC.TERM-LIST-LISTP-OF-RW.CCSTEP-LIST-LIST-OBLIGATIONS-FREE))
 (1
   1
   (:REWRITE MILAWA::RW.FAST-CACHEMAPP-OF-SUBSET-WHEN-RW.FAST-CACHEMAPP-ALT))
 (1 1
    (:REWRITE MILAWA::RW.FAST-CACHEMAPP-OF-SUBSET-WHEN-RW.FAST-CACHEMAPP))
 (1 1
    (:REWRITE MILAWA::RW.CACHEMAPP-OF-SUBSET-WHEN-RW.CACHEMAPP-ALT))
 (1 1
    (:REWRITE MILAWA::RW.CACHEMAPP-OF-SUBSET-WHEN-RW.CACHEMAPP))
 (1 1
    (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE)))
(MILAWA::FORCING-TACTIC.SKELETONP-OF-TACTIC.UREWRITE-ALL-TAC
 (144 4
      (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (138 3
      (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (136 4
      (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (124 4
      (:REWRITE MILAWA::CONSP-OF-RW.UREWRITE-LIST-LIST))
 (90 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (18 18
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (18 3
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (16 16
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (16 16
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (16 16
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (14 14
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (14 14
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (14 14
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (12 2
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (12 2
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (8 2
    (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (4 4 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (4 4
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (4 4
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (4 4 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (4 4
    (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (4 4
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (3 3
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (3 3
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (3 3
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (3 3
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (3 3 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (3 3
    (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (3 3
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (3 3
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (3 3 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (3 3
    (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (2 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
 (2 2
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (2 2
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.TERM-LIST-LISTP-WHEN-MEMBERP-OF-LOGIC.TERM-LIST-LIST-LISTP))
 (2 2
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (2
  2
  (:REWRITE
   MILAWA::FORCING-LOGIC.TERM-LIST-LISTP-OF-RW.CCSTEP-LIST-LIST-OBLIGATIONS-FREE))
 (2 2
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (2 2
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (2 2
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (2 2
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (2 2
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (2 2
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS)))
(MILAWA::FORCING-TACTIC.UREWRITE-ALL-OKP-OF-TACTIC.UREWRITE-ALL-TAC
 (216 6
      (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (210 6
      (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (186 6
      (:REWRITE MILAWA::CONSP-OF-RW.UREWRITE-LIST-LIST))
 (138 3
      (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (135 21
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (92 2
     (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (30 5
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (28 1
     (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (27 27
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (27 27
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (27 27
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (26 26
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (26 26
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (26 26
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (24 4
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (24 4
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (21 21
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (21 21
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (21 21
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (20 20
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (20 20
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (16 4
     (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (12 12
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (12 12
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (12 12
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (12 12
     (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (8 8 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (8 8
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (8 8
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (8 8 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (8 8
    (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (8 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
 (7 7 (:REWRITE MILAWA::LEN-WHEN-TUPLEP))
 (7 7
    (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP-OF-CDR-CHEAP))
 (7 7
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (7 7
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (7 7
    (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (6 6 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (6 6
    (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (6 6
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (6 6
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (6 6 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (6 1
    (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (5 5
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (4 4
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (4 4
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (4 4
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (4 4
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (4 4
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (4 4
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (4 4
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (4 4
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (4 4
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (3 3
    (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (2 2
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP))
 (2 2
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (2
   2
   (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP)))
(MILAWA::TACTIC.UREWRITE-ALL-COMPILE)
(MILAWA::TACTIC.UREWRITE-ALL-COMPILE
 (1884 8
       (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (884 4
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (836 16
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (720 20
      (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (668 8
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (640 12
      (:REWRITE MILAWA::NONE-CONSP-OF-CDR-WHEN-NONE-CONSP))
 (627 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (584 16
      (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-CONSP))
 (540 30
      (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (488 12
      (:REWRITE MILAWA::CONS-LISTP-OF-CDR-WHEN-CONS-LISTP))
 (337 9
      (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (313 117
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (308 93
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (256 19
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (230 5
      (:REWRITE MILAWA::LOGIC.APPEAL-LISTP-WHEN-NOT-CONSP))
 (202 19
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (184 4
      (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (161 38
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (138 3
      (:REWRITE MILAWA::TUPLEP-WHEN-TRUE-LISTP))
 (138 3
      (:REWRITE MILAWA::LOGIC.STRIP-CONCLUSIONS-WHEN-NOT-CONSP))
 (129 129
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (129 129
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (124 124
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (124 124
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (124 124
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (124 124
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (124 4
      (:REWRITE MILAWA::CONSP-OF-RW.UREWRITE-LIST-LIST))
 (120 120
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (120 120
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (120 120
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (120 120
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (120 3
      (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (117 117
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (117 19
      (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (116 4
      (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (114 19
      (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (113 113
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (113 113
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (111 3
      (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (105 3
      (:REWRITE MILAWA::TUPLEP-WHEN-NOT-CONSP))
 (93 3
     (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-LIST-FORMULAS))
 (92 92
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (92 92
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (92 92
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (49 49
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (49 49
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (49 49
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (49 49
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (49 49
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (46 46
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (46 46
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (46 46
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (39 39
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (39 39
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (39 39
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (39 39
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (39 39 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (38 38 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (38 38
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (38 38
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (38 38 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (38 38
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (36 12
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (31 31
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (31 31
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (30 30
     (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (28 4
     (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (20 20
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (20 20
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (20 20
     (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (19 19
     (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (19 19
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (19 19
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (19 19
     (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (19 19
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (19 19
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (19 19
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (16 16
     (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (16 16
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (16 16
     (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (16 16
     (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (16 16
     (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (16 16
     (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (16 16
     (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (16 16
     (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (15 15
     (:REWRITE MILAWA::CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (15
    15
    (:REWRITE MILAWA::CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (13 13
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (12 12 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (8 8
    (:REWRITE MILAWA::NATP-OF-CAR-WHEN-NAT-LISTP))
 (7
  7
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (7 7
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (7 7
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (6 6
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (5 5
    (:REWRITE MILAWA::CDR-OF-CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (5
  5
  (:REWRITE
       MILAWA::CDR-OF-CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (4 4
    (:REWRITE MILAWA::TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (4 4
    (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE))
 (3 3 (:REWRITE MILAWA::TUPLEP-WHEN-ZP))
 (3 3
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP-ALT))
 (3 3
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP))
 (3 3
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP)))
(MILAWA::FORCING-LOGIC.APPEAL-LISTP-OF-TACTIC.UREWRITE-ALL-COMPILE
 (942 4
      (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (442 2
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (432 12
      (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (418 8
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (351 65
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (333 3
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (324 18
      (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (320 6
      (:REWRITE MILAWA::NONE-CONSP-OF-CDR-WHEN-NONE-CONSP))
 (292 8
      (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-CONSP))
 (244 6
      (:REWRITE MILAWA::CONS-LISTP-OF-CDR-WHEN-CONS-LISTP))
 (184 4
      (:REWRITE MILAWA::LOGIC.STRIP-CONCLUSIONS-WHEN-NOT-CONSP))
 (163 65
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (160 4
      (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (149 5
      (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (148 4
      (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (146 46
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (124 4
      (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-LIST-FORMULAS))
 (92 8
     (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (92 2
     (:REWRITE MILAWA::LOGIC.APPEAL-LISTP-WHEN-NOT-CONSP))
 (71 71
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (71 71
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (71 71
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (71 71
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (71 71
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (71 71
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (69 8
     (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (65 65
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (64 64
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (64 64
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (62 2
     (:REWRITE MILAWA::CONSP-OF-RW.UREWRITE-LIST-LIST))
 (58 17
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (52 52
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (52 52
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (52 52
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (49 8
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (48 8
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (46 1
     (:REWRITE MILAWA::TUPLEP-WHEN-TRUE-LISTP))
 (46 1
     (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (35 1
     (:REWRITE MILAWA::TUPLEP-WHEN-NOT-CONSP))
 (29 1
     (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (21 21
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (21 21
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (21 21
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (18 18
     (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (18 6
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (17 17 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (17 17
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (17 17
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (16 16 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (16 16
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (16 16
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (16 16 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (16 16
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (14 14
     (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (9 9
    (:REWRITE MILAWA::CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (9 9
    (:REWRITE MILAWA::CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (8 8
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (8 8
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (8 8
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (8 8
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (8 8
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (8 8
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (7 7
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (7 7
    (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (7 1
    (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (6 6 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (3 3
    (:REWRITE MILAWA::NATP-OF-CAR-WHEN-NAT-LISTP))
 (3 3
    (:REWRITE MILAWA::CDR-OF-CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (3
  3
  (:REWRITE
       MILAWA::CDR-OF-CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (2
  2
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP))
 (1 1 (:REWRITE MILAWA::TUPLEP-WHEN-ZP))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP))
 (1 1
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP))
 (1 1
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP)))
(MILAWA::FORCING-LOGIC.STRIP-CONCLUSIONS-OF-TACTIC.UREWRITE-ALL-COMPILE
 (942 4
      (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (442 2
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (432 12
      (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (418 8
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (363 69
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (333 3
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (324 18
      (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (320 6
      (:REWRITE MILAWA::NONE-CONSP-OF-CDR-WHEN-NONE-CONSP))
 (292 8
      (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-CONSP))
 (244 6
      (:REWRITE MILAWA::CONS-LISTP-OF-CDR-WHEN-CONS-LISTP))
 (242 8
      (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (212 8
      (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (186 6
      (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-LIST-FORMULAS))
 (184 4
      (:REWRITE MILAWA::LOGIC.STRIP-CONCLUSIONS-WHEN-NOT-CONSP))
 (171 69
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (149 5
      (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (146 46
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (92 8
     (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (92 2
     (:REWRITE MILAWA::LOGIC.APPEAL-LISTP-WHEN-NOT-CONSP))
 (77 77
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (77 77
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (77 77
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (77 77
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (75 75
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (75 75
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (75 75
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (75 75
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (75 75
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (75 75
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (69 69
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (69 8
     (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (68 68
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (68 68
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (62 2
     (:REWRITE MILAWA::CONSP-OF-RW.UREWRITE-LIST-LIST))
 (58 17
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (52 52
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (52 52
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (52 52
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (49 8
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (48 8
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (46 1
     (:REWRITE MILAWA::TUPLEP-WHEN-TRUE-LISTP))
 (46 1
     (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (35 1
     (:REWRITE MILAWA::TUPLEP-WHEN-NOT-CONSP))
 (29 1
     (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (27 27
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (21 21
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (21 21
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (21 21
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (18 18
     (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (18 18
     (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (18 6
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (17 17
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (17 17 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (17 17
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (17 17
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (16 16 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (16 16
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (16 16
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (16 16 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (16 16
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (9 9
    (:REWRITE MILAWA::CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (9 9
    (:REWRITE MILAWA::CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (8 8
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (8 8
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (8 8
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (8 8
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (8 8
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (8 8
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (8 8
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (7 7
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (7 7
    (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (7 1
    (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (6 6 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (3 3
    (:REWRITE MILAWA::NATP-OF-CAR-WHEN-NAT-LISTP))
 (3 3
    (:REWRITE MILAWA::CDR-OF-CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (3
  3
  (:REWRITE
       MILAWA::CDR-OF-CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (2
  2
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP))
 (1 1 (:REWRITE MILAWA::TUPLEP-WHEN-ZP))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP))
 (1 1
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP))
 (1 1
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP)))
(MILAWA::FORCING-LOGIC.PROOF-LISTP-OF-TACTIC.UREWRITE-ALL-COMPILE
 (2888 392
       (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (2850 104
       (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (2730 78
       (:REWRITE MILAWA::MEMBERP-WHEN-NOT-CONSP))
 (1485 259
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (1014 78
       (:REWRITE MILAWA::MEMBERP-WHEN-NOT-SUPERSET-OF-SOMEP-CHEAP))
 (1014 78
       (:REWRITE MILAWA::MEMBERP-WHEN-NOT-SUBSET-OF-SOMEP-CHEAP))
 (942 4
      (:REWRITE MILAWA::RW.TRACE-LIST-LIST-RHSES-WHEN-NOT-CONSP))
 (688 20
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (645 16
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (468 78
      (:REWRITE MILAWA::MEMBERP-WHEN-LOGIC.ALL-TERMS-LARGER-CHEAP))
 (442 2
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-NONE-CONSP))
 (432 12
      (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (418 8
      (:REWRITE MILAWA::NONE-CONSP-WHEN-NOT-CONSP))
 (392 392
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (392 392
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (376 16
      (:REWRITE MILAWA::LOOKUP-WHEN-NOT-CONSP))
 (333 3
      (:REWRITE MILAWA::CONSP-OF-CAR-WHEN-CONS-LISTP))
 (320 6
      (:REWRITE MILAWA::NONE-CONSP-OF-CDR-WHEN-NONE-CONSP))
 (292 8
      (:REWRITE MILAWA::CONS-LISTP-WHEN-NOT-CONSP))
 (265 265
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (265 265
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (265 265
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (265 265
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (265 265
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (265 265
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (263 263
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (263 263
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (263 263
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (263 263
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (259 259
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (258 258
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (258 258
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (251 251
      (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (251 251
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (249 95
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (246 76
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (244 6
      (:REWRITE MILAWA::CONS-LISTP-OF-CDR-WHEN-CONS-LISTP))
 (184 4
      (:REWRITE MILAWA::LOGIC.STRIP-CONCLUSIONS-WHEN-NOT-CONSP))
 (160 4
      (:REWRITE MILAWA::LOGIC.DISJOIN-EACH-FORMULA-LIST-WHEN-NOT-CONSP))
 (149 5
      (:REWRITE MILAWA::RW.UREWRITE-LIST-LIST-WHEN-NOT-CONSP))
 (148 4
      (:REWRITE MILAWA::LOGIC.TERM-LIST-LIST-FORMULAS-WHEN-NOT-CONSP))
 (140 20
      (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (124 4
      (:REWRITE MILAWA::CONSP-OF-LOGIC.TERM-LIST-LIST-FORMULAS))
 (104 104
      (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (101 20
      (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (92 2
     (:REWRITE MILAWA::TACTIC.WORLD-LIST-ENV-OKP-WHEN-NOT-CONSP))
 (92 2
     (:REWRITE MILAWA::TACTIC.WORLD-LIST-ATBLP-WHEN-NOT-CONSP))
 (92 2
     (:REWRITE MILAWA::LOGIC.PROOF-LISTP-WHEN-NOT-CONSP))
 (92 2
     (:REWRITE MILAWA::LOGIC.APPEAL-LISTP-WHEN-NOT-CONSP))
 (78
  78
  (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUPERSET-OF-SOMEP-OF-SMALLER-ALT))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUPERSET-OF-SOMEP-OF-SMALLER))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUBSETP-TWO-ALT))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-SUBSETP-TWO))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-OBVIOUS-ALT))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-OBVIOUS))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-NOT-CONSP))
 (78
   78
   (:REWRITE
        MILAWA::SUPERSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUPERSET-OF-SOMEP-ALT))
 (78
  78
  (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUPERSET-OF-SOMEP))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-FIND-SUBSET))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-ALL-SUPERSET-OF-SOMEP-ALT))
 (78 78
     (:REWRITE MILAWA::SUPERSET-OF-SOMEP-WHEN-ALL-SUPERSET-OF-SOMEP))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSETP-TWO-ALT))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSETP-TWO))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSET-OF-SOMEP-OF-SMALLER-ALT))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-SUBSET-OF-SOMEP-OF-SMALLER))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-OBVIOUS-ALT))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-OBVIOUS))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-NOT-CONSP))
 (78
  78
  (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUBSET-OF-SOMEP-ALT))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-MEMBERP-OF-ALL-SUBSET-OF-SOMEP))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-FIND-SUPERSET))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-ALL-SUBSET-OF-SOMEP-ALT))
 (78 78
     (:REWRITE MILAWA::SUBSET-OF-SOMEP-WHEN-ALL-SUBSET-OF-SOMEP))
 (78 78
     (:REWRITE MILAWA::NOT-IN-SUBSET-WHEN-NOT-IN-SUPERSET-TWO))
 (78 78
     (:REWRITE MILAWA::NOT-IN-SUBSET-WHEN-NOT-IN-SUPERSET-ONE))
 (78 78
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-MEMBER-OF-NONEP-ALT))
 (78 78
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-MEMBER-OF-NONEP))
 (78 78
     (:REWRITE MILAWA::MEMBERP-WHEN-DISJOINTP-TWO))
 (78 78
     (:REWRITE MILAWA::MEMBERP-WHEN-DISJOINTP-ONE))
 (78
  78
  (:REWRITE
    MILAWA::LOGIC.ALL-TERMS-LARGERP-WHEN-NOT-LOGIC.ALL-TERMS-LARGERP-BADGUY))
 (78 78
     (:REWRITE MILAWA::LOGIC.ALL-TERMS-LARGERP-WHEN-NOT-CONSP))
 (78
  78
  (:REWRITE
   MILAWA::LOGIC.ALL-TERMS-LARGERP-OF-SUBSETP-WHEN-LOGIC.ALL-TERMS-LARGERP-ALT))
 (78
  78
  (:REWRITE
    MILAWA::LOGIC.ALL-TERMS-LARGERP-OF-SUBSETP-WHEN-LOGIC.ALL-TERMS-LARGERP))
 (78
  78
  (:REWRITE
       MILAWA::ALL-TERMS-LARGER-WHEN-ALL-TERMS-LARGER-THAN-SOMETHING-BIGGER))
 (72 31
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (62 2
     (:REWRITE MILAWA::CONSP-OF-RW.UREWRITE-LIST-LIST))
 (50 2 (:REWRITE MILAWA::LESS-OF-ONE-LEFT))
 (48 8
     (:REWRITE MILAWA::CONSP-OF-LOOKUP-UNDER-IFF))
 (46 1
     (:REWRITE MILAWA::TUPLEP-WHEN-TRUE-LISTP))
 (46 1
     (:REWRITE MILAWA::TACTIC.WORLD-LISTP-WHEN-NOT-CONSP))
 (43 43
     (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (43 43
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (43 43
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (43 43
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (43 43
     (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (35 35
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (35 35
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (35 35
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (35 1
     (:REWRITE MILAWA::TUPLEP-WHEN-NOT-CONSP))
 (32 32
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (32 32
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (31 31
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (31 31
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (31 31
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (31 31
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (31 31 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (29 1
     (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (28 28 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (28 28 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (28 28
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (20 20
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (20 20
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (20 20
     (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (20 20
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (20 20
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (20 20
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (18 6
     (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (17 17
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (17 17
     (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (16 16
     (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (16 16
     (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (14 14
     (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (12 12
     (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (9 9
    (:REWRITE MILAWA::CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (9 9
    (:REWRITE MILAWA::CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (8 8
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP-ALT))
 (8 8
    (:REWRITE MILAWA::NONE-CONSP-OF-SUBSETP-WHEN-NONE-CONSP))
 (8 8
    (:REWRITE MILAWA::LOOKUP-WHEN-MEMBERP-OF-SUBMAPP1))
 (8 8
    (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-TWO))
 (8 8
    (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-ONE))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-WHEN-MEMBERP-OF-CONS-LIST-LISTP))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP-ALT))
 (8 8
    (:REWRITE MILAWA::CONS-LISTP-OF-SUBSETP-WHEN-CONS-LISTP))
 (7 7
    (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-ONE))
 (7 7
    (:REWRITE MILAWA::CONSP-OF-CDR-OF-CDR-OF-CDR-WITH-LEN-FREE))
 (7 1
    (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (6 6
    (:REWRITE MILAWA::ZP-WHEN-NOT-NATP-CHEAP))
 (6 6 (:REWRITE MILAWA::ZP-WHEN-NATP-CHEAP))
 (6 6 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (6 2 (:REWRITE MILAWA::LESS-OF-ONE-RIGHT))
 (3 3
    (:REWRITE MILAWA::NATP-OF-CAR-WHEN-NAT-LISTP))
 (3 3
    (:REWRITE MILAWA::CDR-OF-CDR-OF-CDR-WITH-LEN-FREE-PAST-THE-END))
 (3
  3
  (:REWRITE
       MILAWA::CDR-OF-CDR-OF-CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (2
  2
  (:REWRITE
   MILAWA::TACTIC.WORLD-LIST-ENV-OKP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ENV-OKP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::TACTIC.WORLD-LIST-ENV-OKP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ENV-OKP))
 (2
  2
  (:REWRITE
   MILAWA::TACTIC.WORLD-LIST-ATBLP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ATBLP-ALT))
 (2
  2
  (:REWRITE
    MILAWA::TACTIC.WORLD-LIST-ATBLP-OF-SUBSETP-WHEN-TACTIC.WORLD-LIST-ATBLP))
 (2
  2
  (:REWRITE
       MILAWA::LOGIC.PROOF-LISTP-WHEN-MEMBERP-OF-LOGIC.PROOF-LIST-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.PROOF-LISTP-WHEN-MEMBERP-OF-LOGIC.PROOF-LIST-LISTP))
 (2
  2
  (:REWRITE MILAWA::LOGIC.PROOF-LISTP-OF-SUBSETP-WHEN-LOGIC.PROOF-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::LOGIC.PROOF-LISTP-OF-SUBSETP-WHEN-LOGIC.PROOF-LISTP))
 (2 2
    (:REWRITE MILAWA::LOGIC.PROOF-LISTP-IN-LARGER-THEOREM-SET))
 (2 2
    (:REWRITE MILAWA::LOGIC.PROOF-LISTP-IN-LARGER-AXIOM-SET))
 (2
  2
  (:REWRITE
     MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP-ALT))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-WHEN-MEMBERP-OF-LOGIC.APPEAL-LIST-LISTP))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::LOGIC.APPEAL-LISTP-OF-SUBSETP-WHEN-LOGIC.APPEAL-LISTP))
 (1 1 (:REWRITE MILAWA::TUPLEP-WHEN-ZP))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TUPLEP-WHEN-MEMBERP-OF-TUPLE-LISTP))
 (1 1
    (:REWRITE
         MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP-ALT))
 (1 1
    (:REWRITE MILAWA::TACTIC.WORLD-LISTP-OF-SUBSETP-WHEN-TACTIC.WORLD-LISTP))
 (1 1
    (:REWRITE MILAWA::<-OF-CAR-WHEN-ALL-AT-LEASTP)))
