# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../../Makefile-generic

ACL2 = ../../../../../../saved_acl2

# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

soundness.cert: soundness.lisp

total-order-easy-direction.cert: total-order-easy-direction.lisp

total-order.cert: total-order.lisp
