# Jared: someone needs to fix this directory who understands it.
# I am taking out the include of Makefile-deps so that it does not confuse the
# new Makefile-big thing.
# I am leaving in the include of Makefile-generic so that one can attempt to 
# type "make" here, but that seems to be completely broken since all of these
# books have defaxioms and such.

include ../../Makefile-generic


