# This directory provides support for its parent directory.  See in
# particular ../embedded-defaxioms.lisp.

# Thus, do not include Makefile-deps, which Jared says can confuse the
# new Makefile-big thing.  We include Makefile-generic for historic
# reasons, and because it might be necessary now or down the road.

include ../../Makefile-generic
