include ../Makefile-generic

# Dependencies:

set-theory.cert: set-theory.lisp
set-theory.cert: total-ordering.cert
set-theory.cert: ../ordinals/e0-ordinal.cert
set-theory.cert: ../arithmetic/top-with-meta.cert
set-theory.cert: set-theory.acl2

total-ordering.cert: total-ordering.lisp




