include ../../../../../../Makefile-generic

# Pasted in from "make dependencies":

circuit-scheduling.cert: circuit-scheduling.lisp
circuit-scheduling.cert: ../../generic-modules/GeNoC-scheduling.cert
circuit-scheduling.cert: intersect.cert

intersect.cert: intersect.lisp
# intersect.cert: $(ACL2_SYSTEM_BOOKS)/data-structures/list-defuns.cert
# intersect.cert: $(ACL2_SYSTEM_BOOKS)/data-structures/list-defthms.cert

packet-scheduling.cert: packet-scheduling.lisp
packet-scheduling.cert: ../../generic-modules/GeNoC-scheduling.cert
packet-scheduling.cert: intersect.cert
