include ../../../../../../Makefile-generic

# Override default setting since only the solutions are to be certified.

BOOKS = solution1 solution2 solution3 solution4 solution5 solution6

-include Makefile-deps
