#!/bin/csh

if ($#argv != 1) then
    echo "Need 1 arg: ivy or sivy script"
    exit(1)
endif

echo ""
echo "These 5 should succeed:"
echo ""

$1 prove    p-implies-p      |& egrep "has been|failed"
$1 refute   p-and-not-p      |& egrep "has been|failed"
$1 disprove p                |& egrep "has been|failed"
$1 model    p                |& egrep "has been|failed"
../util/checker sound-proof  |& egrep "have been|failed"

echo ""
echo "These 5 should fail:"
echo ""

$1 prove    p                  |& egrep "has been|failed"
$1 refute   p                  |& egrep "has been|failed"
$1 disprove p-implies-p        |& egrep "has been|failed"
$1 model    p-and-not-p        |& egrep "has been|failed"
../util/checker unsound-proof  |& egrep "have been|failed"

