(CHK-CURRENT-PACKAGE)
(SET-CURRENT-PACKAGE)
(SET-CURRENT-PACKAGE-STATE)
(SET-PPR-FLAT-RIGHT-MARGIN)
(SET-IPRINT-AR
 (3 3 (:TYPE-PRESCRIPTION COMPRESS1))
 )
(BLOCK-IPRINT-AR)
(OVERRIDE-GLOBAL-EVISC-TABLE)
(FMT1-TO-STRING-FN
 (6 6 (:TYPE-PRESCRIPTION COMPRESS1))
 )
(PRINT-TO-STRING)
