include ../Makefile-generic
-include Makefile-deps

# Added manually, based on *default-arith-book-alist*:
# proof-by-arith.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/bind-free/top.cert
# proof-by-arith.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/floor-mod/floor-mod.cert
# proof-by-arith.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic/top-with-meta.cert
# proof-by-arith.cert: $(ACL2_SYSTEM_BOOKS)/rtl/rel5/arithmetic/top.cert

# Added manually:

stobj-test.cert: stobj-test.acl2x

double-cert-test-1.cert: double-cert-test-1.acl2x

acl2x-help-test.cert: acl2x-help-test.acl2x
