## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

# Edited out by Matt Kaufmann:
# include dir.mk

# Edit by Matt Kaufmann:
# include $(DIR)/books/Makefile-subdirs
include ../../../../Makefile-subdirs

DIRS = books factorial Fibonacci TEA RC6 AES

# 3 lines edited out by Matt Kaufmann:
#.PHONY: depend
#depend:
#	sh cert.sh

# $(DIRS):
# 	$(MAKE) -C $@


