include ../../../Makefile-generic

# Don't alphabetize this list!
BOOKS = arith basic bits log logn float reps round \
        rtl rtlarr bvecp-raw-helpers bvecp-helpers simple-loop-helpers \
        simplify-model-helpers util add top rom-helpers clocks package-defs \
        openers mult \
	logn2log    \
	top

-include Makefile-deps
