include ../../../../../../Makefile-generic


# Dependencies:

alist-thms.cert: alist-thms.lisp

defun-weak-sk.cert: defun-weak-sk.lisp

ihs.cert: ihs.lisp
ihs.cert: ../../../../../../ihs/ihs-definitions.cert
ihs.cert: ../../../../../../ihs/ihs-lemmas.cert

meta.cert: meta.lisp
meta.cert: ../../../../../../arithmetic/top-with-meta.cert

nth-thms.cert: nth-thms.lisp
