include ../../../../Makefile-generic

# Don't alphabetize this list!
# [Matt K.: Not sure why not, or why we even need this list!  So, I'm
# commenting it out.]
#BOOKS = base arith basic bits log float reps round \
#        rtl rtlarr bvecp-raw-helpers bvecp-helpers simple-loop-helpers \
#        simplify-model-helpers util add top rom-helpers clocks package-defs \
#        openers mult 

-include Makefile-deps
