include ../../../Makefile-generic

# We skip some books for "make fasl" etc., i.e., for
# compiling already-certified books:
# - aof.acl2 specifies no compilation
# - knuth-arch.lisp: depends on aof
BOOKS_SKIP_COMP := aof knuth-arch

-include Makefile-deps
