## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

include ../../../../../Makefile-generic
-include Makefile-deps

BOOKS = AES-source-shallow-canon AES-source-shallow-flatten proof-AES


