include ../../Makefile-generic
ACL2 = ../../../saved_acl2

compose-c-c-partial.cert: compose-c-c-partial.lisp
# compose-c-c-partial.cert: $(ACL2_SYSTEM_BOOKS)/ordinals/e0-ordinal.cert
# compose-c-c-partial.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-2/meta/top.cert

compose-c-c-total.cert: compose-c-c-total.lisp
# compose-c-c-total.cert: $(ACL2_SYSTEM_BOOKS)/ordinals/e0-ordinal.cert
# compose-c-c-total.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-2/meta/top.cert
