# Note that ACL2 and ACL2_SYSTEM_BOOKS should be defined, e.g.:
# bash
# ACL2_DIR=/Users/kaufmann/acl2/v6-2/acl2-sources
# export ACL2=${ACL2_DIR}/saved_acl2
# export ACL2_SYSTEM_BOOKS=${ACL2_DIR}/books

include $(ACL2_SYSTEM_BOOKS)/Makefile-generic
-include Makefile-deps
