include ../../../../Makefile-generic

# Pasted in from "make dependencies":

ptest-fib.cert: ptest-fib.lisp

ptest-if-normalization.cert: ptest-if-normalization.lisp

ptest-mergesort.cert: ptest-mergesort.lisp
# ptest-mergesort.cert: $(ACL2_SYSTEM_BOOKS)/finite-set-theory/osets/sets.cert
