include ../../../Makefile-generic


# Override default setting since define-u-package.lisp is not intended to be certified.
BOOKS = b-ops-aux-def b-ops-aux basic-def basic-lemmas exercise ihs model proof table-def trivia utils

-include Makefile-deps
