(PRIMES::BABY-JUBJUB-SUBGROUP-PRIME)
(PRIMES::PRIMEP-OF-BABY-JUBJUB-SUBGROUP-PRIME-CONSTANT)
(PRIMES::PRIMEP-OF-BABY-JUBJUB-SUBGROUP-PRIME)
(PRIMES::BABY-JUBJUB-SUBGROUP-PRIME-LINEAR)
(RTL::PRIMEP1720939445)
(RTL::PRIMEP1682520437
 (1 1 (:REWRITE DEFAULT-CDR))
 (1 1 (:REWRITE DEFAULT-CAR))
 )
