(PRIMES::BABY-JUBJUB-SUBGROUP-PRIME)
(PRIMES::PRIMEP-OF-BABY-JUBJUB-SUBGROUP-PRIME-CONSTANT)
(PRIMES::PRIMEP-OF-BABY-JUBJUB-SUBGROUP-PRIME)
(PRIMES::BABY-JUBJUB-SUBGROUP-PRIME-LINEAR)
(DM::PRIMEP1474583107)
(DM::PRIMEP1430130819
 (1 1 (:REWRITE DEFAULT-CDR))
 (1 1 (:REWRITE DEFAULT-CAR))
 )
