# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../Makefile-generic


# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

dickson.cert: dickson.lisp
dickson.cert: ../../../../ordinals/ordinals.cert
#dickson.cert: ordinal-arith.cert

#ordinal-arith.cert: ordinal-arith.lisp
#ordinal-arith.cert: ../../../../ordinals/ordinal-definitions.cert
#ordinal-arith.cert: ../../../../ordinals/ordinal-addition.cert
#ordinal-arith.cert: ../../../../ordinals/ordinal-exponentiation.cert
#ordinal-arith.cert: ../../../../ordinals/ordinal-isomorphism.cert
