include ../Makefile-generic

# Dependencies:

acl2-agp.cert: acl2-agp.lisp
acl2-agp.cert: acl2-asg.cert
acl2-agp.cert: acl2-agp.acl2

acl2-asg.cert: acl2-asg.lisp
acl2-asg.cert: acl2-asg.acl2

acl2-crg.cert: acl2-crg.lisp
acl2-crg.cert: acl2-agp.cert
acl2-crg.cert: acl2-crg.acl2
