include ../../../../Makefile-generic

ACL2 = ../../../../../saved_acl2

# Dependencies:

defmul.cert: defmul.lisp
defmul.cert: multiset.cert

multiset.cert: multiset.lisp
multiset.cert: ../../../../ordinals/e0-ordinal.cert
