## Lee Pike <leepike@galois.com>
## Galois Connections, Inc.
## March, 2006

## Makefile for mCrytpol Verifying Compiler ACL2 books

include ../dir.mk

include $(DIR)/books/Makefile-generic
ACL2 = $(DIR)/saved_acl2

# .PHONY: depend
# depend:
# 	sh ../cert.mk


BOOKS = fibs-source-shallow-canon fibs-source-shallow-flatten proof-fibs


