include ../../../Makefile-generic


# Dependencies:

exercises.cert: exercises.lisp
exercises.cert: tiny.cert

tiny.cert: tiny.lisp
tiny.cert: ../../../arithmetic/top.cert
tiny.cert: ../../../data-structures/list-defthms.cert
tiny.cert: ../../../meta/meta.cert
tiny.cert: ../../../ihs/logops-lemmas.cert
tiny.cert: ../../../ihs/quotient-remainder-lemmas.cert
