(TREESET::BST<$INLINE)
(TREESET::BST<-IRREFLEXIVE)
(TREESET::BST<-ASYMMETRIC
 (1 1 (:REWRITE <<-TRICHOTOMY))
 )
(TREESET::BST<-TRANSITIVE
 (57 16 (:REWRITE <<-TRICHOTOMY))
 (49 9 (:REWRITE <<-ASYMMETRIC))
 )
(TREESET::BST<-TRICHOTOMY)
(TREESET::BST<-WITH-HASHES$INLINE)
