include ../../../../../Makefile-generic

# Pasted in from "make dependencies":

generate-degenerate.cert: generate-degenerate.lisp
generate-degenerate.cert: ../abstract-reductions/convergent.cert
# generate-degenerate.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic/top-with-meta.cert
generate-degenerate.cert: generate-degenerate.acl2

