(SMT::IS-TYPE-DECL)
(SMT::BOOLEANP-OF-IS-TYPE-DECL)
(SMT::RECOVER-TYPE-DECL-LIST
     (72 12
         (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FUNC-ALISTP))
     (48 12
         (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FTY-TYPES-P))
     (48 12
         (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FTY-INFO-ALIST-P))
     (48 12
         (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FTY-FIELD-ALIST-P))
     (46 46
         (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
     (42 42 (:REWRITE DEFAULT-CAR))
     (41 41 (:REWRITE DEFAULT-CDR))
     (24 24
         (:REWRITE SMT::FUNC-ALISTP-WHEN-SUBSETP-EQUAL))
     (18 18
         (:REWRITE SMT::FTY-INFO-ALIST-P-WHEN-NOT-CONSP))
     (16 8 (:REWRITE DEFAULT-+-2))
     (12 12
         (:REWRITE SMT::FUNC-ALISTP-WHEN-NOT-CONSP))
     (12 12
         (:REWRITE SMT::FTY-TYPES-P-WHEN-NOT-CONSP))
     (12 12
         (:REWRITE SMT::FTY-FIELD-ALIST-P-WHEN-NOT-CONSP))
     (12 2
         (:REWRITE SMT::PSEUDO-TERMP-OF-CAAR-WHEN-PSEUDO-TERM-ALISTP))
     (8 8 (:REWRITE DEFAULT-+-1))
     (4 4
        (:REWRITE SMT::PSEUDO-TERM-ALISTP-WHEN-SUBSETP-EQUAL))
     (4 4
        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (4 4
        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (4 4 (:LINEAR LEN-WHEN-PREFIXP))
     (2 2 (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
     (2 2
        (:REWRITE SMT::PSEUDO-TERM-ALISTP-WHEN-NOT-CONSP))
     (2 2
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN)))
(SMT::DECL-LISTP-OF-RECOVER-TYPE-DECL-LIST
     (1421 89
           (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
     (1269 66 (:DEFINITION SYMBOL-LISTP))
     (633 103
          (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
     (311 307 (:REWRITE DEFAULT-CAR))
     (208 48
          (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FUNC-ALISTP))
     (183 179 (:REWRITE DEFAULT-CDR))
     (144 48
          (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FTY-TYPES-P))
     (144 48
          (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FTY-INFO-ALIST-P))
     (144 48
          (:REWRITE SMT::SYMBOLP-OF-CAAR-WHEN-FTY-FIELD-ALIST-P))
     (137 137
          (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
     (120 29
          (:REWRITE SMT::DECL-LISTP-WHEN-NOT-CONSP))
     (94 2 (:DEFINITION MEMBER-EQUAL))
     (78 39 (:REWRITE DEFAULT-+-2))
     (68 17
         (:REWRITE SMT::FTY-INFO-ALIST-FIX-WHEN-FTY-INFO-ALIST-P))
     (66 2 (:REWRITE SMT::EQUAL-OF-DECL))
     (64 64
         (:REWRITE SMT::FUNC-ALISTP-WHEN-SUBSETP-EQUAL))
     (60 4
         (:REWRITE SMT::DECL-P-WHEN-MEMBER-EQUAL-OF-DECL-LISTP))
     (56 1 (:REWRITE SUBSETP-OF-CONS))
     (49 49
         (:REWRITE SMT::FTY-INFO-ALIST-P-WHEN-NOT-CONSP))
     (39 39 (:REWRITE DEFAULT-+-1))
     (32 32
         (:REWRITE SMT::FUNC-ALISTP-WHEN-NOT-CONSP))
     (32 32
         (:REWRITE SMT::FTY-TYPES-P-WHEN-NOT-CONSP))
     (32 32
         (:REWRITE SMT::FTY-FIELD-ALIST-P-WHEN-NOT-CONSP))
     (28 28
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (28 28
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (28 28 (:LINEAR LEN-WHEN-PREFIXP))
     (14 14
         (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (14 2
         (:REWRITE SMT::HINT-PAIR-FIX-WHEN-HINT-PAIR-P))
     (13 13 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (12 12
         (:TYPE-PRESCRIPTION SMT::DECL->TYPE-REQFIX))
     (12 12
         (:TYPE-PRESCRIPTION SMT::DECL->TYPE$INLINE))
     (12 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (10 2 (:REWRITE SUBSETP-CAR-MEMBER))
     (9 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (8 8 (:REWRITE SUBSETP-TRANS2))
     (8 8 (:REWRITE SUBSETP-TRANS))
     (6 6
        (:TYPE-PRESCRIPTION SMT::DECL->NAME$INLINE))
     (4 4 (:TYPE-PRESCRIPTION SMT::HINT-PAIR))
     (4 4 (:REWRITE SYMBOL-FIX-WHEN-SYMBOLP))
     (4 4 (:REWRITE SUBSETP-MEMBER . 2))
     (4 4 (:REWRITE SUBSETP-MEMBER . 1))
     (4 4
        (:REWRITE SMT::HINT-PAIR-P-WHEN-MEMBER-EQUAL-OF-HINT-PAIR-LISTP))
     (2 2 (:TYPE-PRESCRIPTION SMT::HINT-PAIR-P))
     (2 2
        (:REWRITE-QUOTED-CONSTANT SMT::TRUE-LIST-FIX-UNDER-TRUE-LIST-EQUIV))
     (2 2
        (:REWRITE SMT::HINT-PAIR-P-OF-HINT-PAIR)))
(SMT::RECOVER-TYPE-HYP)
