#!/bin/csh

if ($#argv != 1) then
    echo "Need 1 arg: ivy or sivy script"
    exit(1)
endif

$1 prove     cd-cn19             |& egrep "We are trying|has been|failed"
$1 prove     comb-sk-w           |& egrep "We are trying|has been|failed"
$1 model     comb-sw-not-weak    |& egrep "We are trying|has been|failed"
$1 prove     group-comm          |& egrep "We are trying|has been|failed"
$1 disprove  group-noncomm       |& egrep "We are trying|has been|failed"
$1 model     group-noncomm-model |& egrep "We are trying|has been|failed"
$1 prove     group-x2            |& egrep "We are trying|has been|failed"
$1 refute    group-x2-refute     |& egrep "We are trying|has been|failed"
$1 prove     lifsch              |& egrep "We are trying|has been|failed"
$1 prove     steam               |& egrep "We are trying|has been|failed"
$1 disprove  steam-x             |& egrep "We are trying|has been|failed"

../util/checker otter-cn.output |& egrep "We are checking|have been|failed"
