include ../../../../Makefile-generic


# Dependencies:

rTarai6.cert: rTarai6.lisp
rTarai6.cert: tarai5.cert

rTarai7.cert: rTarai7.lisp
rTarai7.cert: rTarai6.cert

rTarai8.cert: rTarai8.lisp
rTarai8.cert: rTarai7.cert

rTarai9.cert: rTarai9.lisp
rTarai9.cert: rTarai8.cert

tarai1.cert: tarai1.lisp

tarai10.cert: tarai10.lisp

tarai11.cert: tarai11.lisp

tarai2.cert: tarai2.lisp

tarai3.cert: tarai3.lisp

tarai4.cert: tarai4.lisp

tarai5.cert: tarai5.lisp
tarai5.cert: tarai1.cert
tarai5.cert: tarai2.cert
tarai5.cert: tarai3.cert
tarai5.cert: tarai4.cert

tarai6.cert: tarai6.lisp
tarai6.cert: tarai5.cert

tarai7.cert: tarai7.lisp
tarai7.cert: tarai5.cert

tarai8.cert: tarai8.lisp
tarai8.cert: tarai5.cert

tarai9.cert: tarai9.lisp
tarai9.cert: tarai5.cert
tarai9.cert: tarai6.cert
tarai9.cert: tarai7.cert
tarai9.cert: tarai8.cert
