(ECURVE::SECP256K1-GENERATOR)
(ECURVE::POINTP-OF-SECP256K1-GENERATOR)
(ECURVE::POINT-IN-PXP-P-OF-SECP256K1-GENERATOR)
(ECURVE::LEMMA)
(ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P-OF-SECP256K1-GENERATOR)
(ECURVE::SECP256K1-PARAMS-DEFINE-VALID-ELLIPTIC-CURVE
     (138 6 (:REWRITE COMMUTATIVITY-OF-*))
     (110 1 (:LINEAR MOD-BOUND-LINEAR-ARG1))
     (105 3 (:REWRITE MOD-WHEN-MULTIPLE))
     (105 3
          (:REWRITE MOD-WHEN-INTEGERP-OF-QUOTIENT))
     (104 1 (:LINEAR MOD-BOUND-LINEAR-ARG2))
     (102 6 (:REWRITE DISTRIBUTIVITY))
     (54 18 (:REWRITE DEFAULT-*-2))
     (36 18 (:REWRITE DEFAULT-*-1))
     (36 6 (:REWRITE COMMUTATIVITY-OF-+))
     (30 12 (:REWRITE DEFAULT-+-2))
     (30 12 (:REWRITE DEFAULT-+-1))
     (12 3
         (:REWRITE MOD-WHEN-RATIONALP-ARG1-AND-NOT-RATIONALP-ARG2))
     (12 3
         (:REWRITE MOD-WHEN-NOT-RATIONALP-ARG1-AND-RATIONALP-ARG2))
     (12 3
         (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG1))
     (3 3
        (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG2))
     (3 3
        (:REWRITE MOD-WHEN-EQUAL-OF-MOD-AND-0-FREE-CHEAP)))
(ECURVE::SECP256K1-HAS-SQUARE-ROOT? (3 3 (:REWRITE DEFAULT-<-2))
                                    (3 3 (:REWRITE DEFAULT-<-1)))
(ECURVE::SECP256K1-SQRT (3 3 (:REWRITE DEFAULT-<-2))
                        (3 3 (:REWRITE DEFAULT-<-1))
                        (2 1 (:REWRITE DEFAULT-*-2))
                        (2 1 (:REWRITE DEFAULT-*-1)))
(ECURVE::SECP256K1+)
(ECURVE::POINTP-OF-SECP256K1+)
(ECURVE::POINT-IN-PXP-P-OF-SECP256K1+
     (7 1
        (:REWRITE ECURVE::CLOSURE-OF-CURVE-GROUP-+))
     (2 2
        (:TYPE-PRESCRIPTION ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P))
     (1 1 (:TYPE-PRESCRIPTION RTL::PRIMEP))
     (1 1
        (:REWRITE PRIMES::PRIMEP-OF-SECP256K1-FIELD-PRIME-CONSTANT)))
(ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P-OF-SECP256K1+)
(ECURVE::SECP256K1*)
(ECURVE::POINTP-OF-SECP256K1*)
(ECURVE::POINT-IN-PXP-P-OF-SECP256K1* (1 1 (:REWRITE DEFAULT-<-2))
                                      (1 1 (:REWRITE DEFAULT-<-1)))
(ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P-OF-SECP256K1*
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1)))
(ECURVE::SECP256K1-NEGATE)
(ECURVE::POINTP-OF-SECP256K1-NEGATE)
(ECURVE::POINT-IN-PXP-P-OF-SECP256K1-NEGATE)
