(TMP-DEFTYPES-NATP-OF-NFIX)
(TMP-DEFTYPES-NFIX-WHEN-NATP (2 2 (:REWRITE DEFAULT-<-2))
                             (2 2 (:REWRITE DEFAULT-<-1)))
(ECURVE::SHORT-WEIERSTRASS-P (8 8 (:DEFINITION STRIP-CARS)))
(ECURVE::CONSP-WHEN-SHORT-WEIERSTRASS-P)
(ECURVE::SHORT-WEIERSTRASS-FIX$INLINE)
(ECURVE::SHORT-WEIERSTRASS-P-OF-SHORT-WEIERSTRASS-FIX
 (363 13 (:REWRITE MOD-WHEN-MULTIPLE))
 (363 13
      (:REWRITE MOD-WHEN-INTEGERP-OF-QUOTIENT))
 (345 345 (:REWRITE DEFAULT-CDR))
 (326 26 (:REWRITE COMMUTATIVITY-OF-*))
 (220 17 (:REWRITE PFIELD::FEP-HOLDS))
 (212 102 (:REWRITE DEFAULT-*-2))
 (194 10 (:REWRITE DISTRIBUTIVITY))
 (181 13 (:REWRITE MOD-WHEN-<))
 (170 170 (:REWRITE DEFAULT-CAR))
 (156 102 (:REWRITE DEFAULT-*-1))
 (148 94 (:REWRITE DEFAULT-<-1))
 (129 129 (:TYPE-PRESCRIPTION NATP))
 (115 94 (:REWRITE DEFAULT-<-2))
 (80 16 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
 (79 33 (:REWRITE DEFAULT-+-2))
 (75 33 (:REWRITE DEFAULT-+-1))
 (40 13
     (:REWRITE MOD-WHEN-RATIONALP-ARG1-AND-NOT-RATIONALP-ARG2))
 (40 13
     (:REWRITE MOD-WHEN-NOT-RATIONALP-ARG1-AND-RATIONALP-ARG2))
 (40 13
     (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG1))
 (27 9 (:DEFINITION NATP))
 (26 26 (:REWRITE DEFAULT-UNARY-/))
 (17 17
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (13 13
     (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG2))
 (13 13
     (:REWRITE MOD-WHEN-EQUAL-OF-MOD-AND-0-FREE-CHEAP))
 (8 8
    (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG2))
 (8 8
    (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG1)))
(ECURVE::SHORT-WEIERSTRASS-FIX-WHEN-SHORT-WEIERSTRASS-P
     (4 4 (:DEFINITION STRIP-CARS)))
(ECURVE::SHORT-WEIERSTRASS-FIX$INLINE (4 4 (:DEFINITION STRIP-CARS)))
(FTY::TMP-DEFFIXTYPE-IDEMPOTENT)
(ECURVE::SHORT-WEIERSTRASS-EQUIV$INLINE)
(ECURVE::SHORT-WEIERSTRASS-EQUIV-IS-AN-EQUIVALENCE)
(ECURVE::SHORT-WEIERSTRASS-EQUIV-IMPLIES-EQUAL-SHORT-WEIERSTRASS-FIX-1)
(ECURVE::SHORT-WEIERSTRASS-FIX-UNDER-SHORT-WEIERSTRASS-EQUIV)
(ECURVE::EQUAL-OF-SHORT-WEIERSTRASS-FIX-1-FORWARD-TO-SHORT-WEIERSTRASS-EQUIV)
(ECURVE::EQUAL-OF-SHORT-WEIERSTRASS-FIX-2-FORWARD-TO-SHORT-WEIERSTRASS-EQUIV)
(ECURVE::SHORT-WEIERSTRASS-EQUIV-OF-SHORT-WEIERSTRASS-FIX-1-FORWARD)
(ECURVE::SHORT-WEIERSTRASS-EQUIV-OF-SHORT-WEIERSTRASS-FIX-2-FORWARD)
(ECURVE::SHORT-WEIERSTRASS->P$INLINE (4 4 (:DEFINITION STRIP-CARS)))
(ECURVE::NATP-OF-SHORT-WEIERSTRASS->P)
(ECURVE::SHORT-WEIERSTRASS->P$INLINE-OF-SHORT-WEIERSTRASS-FIX-X
     (642 642 (:TYPE-PRESCRIPTION NATP))
     (390 214
          (:REWRITE ECURVE::SHORT-WEIERSTRASS-FIX-WHEN-SHORT-WEIERSTRASS-P))
     (176 176
          (:TYPE-PRESCRIPTION ECURVE::SHORT-WEIERSTRASS-P)))
(ECURVE::SHORT-WEIERSTRASS->P$INLINE-OF-SHORT-WEIERSTRASS-FIX-X-NORMALIZE-CONST)
(ECURVE::SHORT-WEIERSTRASS->P$INLINE-SHORT-WEIERSTRASS-EQUIV-CONGRUENCE-ON-X)
(ECURVE::SHORT-WEIERSTRASS->A$INLINE (4 4 (:DEFINITION STRIP-CARS)))
(ECURVE::NATP-OF-SHORT-WEIERSTRASS->A)
(ECURVE::SHORT-WEIERSTRASS->A$INLINE-OF-SHORT-WEIERSTRASS-FIX-X
     (642 642 (:TYPE-PRESCRIPTION NATP))
     (390 214
          (:REWRITE ECURVE::SHORT-WEIERSTRASS-FIX-WHEN-SHORT-WEIERSTRASS-P))
     (176 176
          (:TYPE-PRESCRIPTION ECURVE::SHORT-WEIERSTRASS-P)))
(ECURVE::SHORT-WEIERSTRASS->A$INLINE-OF-SHORT-WEIERSTRASS-FIX-X-NORMALIZE-CONST)
(ECURVE::SHORT-WEIERSTRASS->A$INLINE-SHORT-WEIERSTRASS-EQUIV-CONGRUENCE-ON-X)
(ECURVE::SHORT-WEIERSTRASS->B$INLINE (4 4 (:DEFINITION STRIP-CARS)))
(ECURVE::NATP-OF-SHORT-WEIERSTRASS->B)
(ECURVE::SHORT-WEIERSTRASS->B$INLINE-OF-SHORT-WEIERSTRASS-FIX-X
     (642 642 (:TYPE-PRESCRIPTION NATP))
     (390 214
          (:REWRITE ECURVE::SHORT-WEIERSTRASS-FIX-WHEN-SHORT-WEIERSTRASS-P))
     (176 176
          (:TYPE-PRESCRIPTION ECURVE::SHORT-WEIERSTRASS-P)))
(ECURVE::SHORT-WEIERSTRASS->B$INLINE-OF-SHORT-WEIERSTRASS-FIX-X-NORMALIZE-CONST)
(ECURVE::SHORT-WEIERSTRASS->B$INLINE-SHORT-WEIERSTRASS-EQUIV-CONGRUENCE-ON-X)
(ECURVE::SHORT-WEIERSTRASS)
(ECURVE::SHORT-WEIERSTRASS-P-OF-SHORT-WEIERSTRASS
 (363 13 (:REWRITE MOD-WHEN-MULTIPLE))
 (363 13
      (:REWRITE MOD-WHEN-INTEGERP-OF-QUOTIENT))
 (326 26 (:REWRITE COMMUTATIVITY-OF-*))
 (285 285 (:TYPE-PRESCRIPTION NATP))
 (220 17 (:REWRITE PFIELD::FEP-HOLDS))
 (212 102 (:REWRITE DEFAULT-*-2))
 (194 10 (:REWRITE DISTRIBUTIVITY))
 (181 13 (:REWRITE MOD-WHEN-<))
 (156 102 (:REWRITE DEFAULT-*-1))
 (148 94 (:REWRITE DEFAULT-<-1))
 (115 94 (:REWRITE DEFAULT-<-2))
 (80 16 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
 (79 33 (:REWRITE DEFAULT-+-2))
 (75 33 (:REWRITE DEFAULT-+-1))
 (40 13
     (:REWRITE MOD-WHEN-RATIONALP-ARG1-AND-NOT-RATIONALP-ARG2))
 (40 13
     (:REWRITE MOD-WHEN-NOT-RATIONALP-ARG1-AND-RATIONALP-ARG2))
 (40 13
     (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG1))
 (27 9 (:DEFINITION NATP))
 (26 26 (:REWRITE DEFAULT-UNARY-/))
 (17 17 (:REWRITE DEFAULT-CDR))
 (17 17 (:REWRITE DEFAULT-CAR))
 (17 17
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (13 13
     (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG2))
 (13 13
     (:REWRITE MOD-WHEN-EQUAL-OF-MOD-AND-0-FREE-CHEAP))
 (8 8
    (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG2))
 (8 8
    (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG1)))
(ECURVE::SHORT-WEIERSTRASS->P-OF-SHORT-WEIERSTRASS
     (642 642 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::SHORT-WEIERSTRASS->A-OF-SHORT-WEIERSTRASS
     (642 642 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::SHORT-WEIERSTRASS->B-OF-SHORT-WEIERSTRASS
     (642 642 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::SHORT-WEIERSTRASS-REQUIREMENTS
     (204 86
          (:REWRITE TMP-DEFTYPES-NFIX-WHEN-NATP))
     (118 118 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::SHORT-WEIERSTRASS-OF-FIELDS
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (3 1
        (:REWRITE ECURVE::SHORT-WEIERSTRASS-FIX-WHEN-SHORT-WEIERSTRASS-P))
     (2 2
        (:TYPE-PRESCRIPTION ECURVE::SHORT-WEIERSTRASS-P)))
(ECURVE::SHORT-WEIERSTRASS-FIX-WHEN-SHORT-WEIERSTRASS
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (3 1
        (:REWRITE ECURVE::SHORT-WEIERSTRASS-FIX-WHEN-SHORT-WEIERSTRASS-P))
     (2 2
        (:TYPE-PRESCRIPTION ECURVE::SHORT-WEIERSTRASS-P)))
(ECURVE::EQUAL-OF-SHORT-WEIERSTRASS
 (4
  4
  (:REWRITE
   ECURVE::SHORT-WEIERSTRASS->P$INLINE-OF-SHORT-WEIERSTRASS-FIX-X-NORMALIZE-CONST))
 (4
  4
  (:REWRITE
   ECURVE::SHORT-WEIERSTRASS->B$INLINE-OF-SHORT-WEIERSTRASS-FIX-X-NORMALIZE-CONST))
 (4
  4
  (:REWRITE
   ECURVE::SHORT-WEIERSTRASS->A$INLINE-OF-SHORT-WEIERSTRASS-FIX-X-NORMALIZE-CONST)))
(ECURVE::SHORT-WEIERSTRASS-OF-NFIX-P (6 6 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::SHORT-WEIERSTRASS-OF-NFIX-P-NORMALIZE-CONST)
(ECURVE::SHORT-WEIERSTRASS-NAT-EQUIV-CONGRUENCE-ON-P)
(ECURVE::SHORT-WEIERSTRASS-OF-NFIX-A (6 6 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::SHORT-WEIERSTRASS-OF-NFIX-A-NORMALIZE-CONST)
(ECURVE::SHORT-WEIERSTRASS-NAT-EQUIV-CONGRUENCE-ON-A)
(ECURVE::SHORT-WEIERSTRASS-OF-NFIX-B (6 6 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::SHORT-WEIERSTRASS-OF-NFIX-B-NORMALIZE-CONST)
(ECURVE::SHORT-WEIERSTRASS-NAT-EQUIV-CONGRUENCE-ON-B)
(ECURVE::SHORT-WEIERSTRASS-FIX-REDEF)
(ECURVE::SHORT-WEIERSTRASS-PRIMEP)
(ECURVE::BOOLEANP-OF-SHORT-WEIERSTRASS-PRIMEP)
(ECURVE::SHORT-WEIERSTRASS-PRIMEP-OF-SHORT-WEIERSTRASS-FIX-CURVE)
(ECURVE::SHORT-WEIERSTRASS-PRIMEP-OF-SHORT-WEIERSTRASS-FIX-CURVE-NORMALIZE-CONST)
(ECURVE::SHORT-WEIERSTRASS-PRIMEP-SHORT-WEIERSTRASS-EQUIV-CONGRUENCE-ON-CURVE)
(ECURVE::WEIERSTRASS-ELLIPTIC-CURVE-P
     (15 15
         (:TYPE-PRESCRIPTION NONNEGATIVE-PRODUCT))
     (4 4
        (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (4 4
        (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE))
     (4 4
        (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE)))
(ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P
     (198 12 (:REWRITE DEFAULT-<-1))
     (154 5
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (152 4
          (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
     (149 17
          (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
     (149 2 (:DEFINITION ACL2-NUMBER-LISTP))
     (145 3 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (142 2 (:DEFINITION NAT-LISTP))
     (138 15
          (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (133 9 (:DEFINITION RATIONAL-LISTP))
     (122 9 (:DEFINITION INTEGER-LISTP))
     (58 14
         (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
     (47 14
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (35 35 (:REWRITE DEFAULT-CDR))
     (35 35 (:REWRITE DEFAULT-CAR))
     (20 20
         (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (12 12 (:REWRITE DEFAULT-<-2))
     (6 5
        (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (6 3
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (6 3
        (:REWRITE ACL2-NUMBER-LISTP-OF-CDR-WHEN-ACL2-NUMBER-LISTP))
     (5 5
        (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (5 5
        (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (5 5 (:REWRITE PFIELD::MUL-COMMUTATIVE))
     (5 5 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (4 4 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (4 4
        (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP))
     (2 2 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (2 1
        (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (1 1 (:REWRITE PFIELD::MUL-COMMUTATIVE-2))
     (1 1
        (:REWRITE PFIELD::MUL-COMBINE-CONSTANTS))
     (1 1
        (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP)))
(ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P-OF-INF)
(ECURVE::CURVE-GROUP-+
     (407 33 (:REWRITE DEFAULT-<-1))
     (308 10
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (304 8
          (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
     (298 34
          (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
     (298 4 (:DEFINITION ACL2-NUMBER-LISTP))
     (290 6 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (284 4 (:DEFINITION NAT-LISTP))
     (276 30
          (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (266 18 (:DEFINITION RATIONAL-LISTP))
     (244 18 (:DEFINITION INTEGER-LISTP))
     (116 28
          (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
     (94 28
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (88 88 (:REWRITE DEFAULT-CAR))
     (78 48
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (74 74 (:REWRITE DEFAULT-CDR))
     (71 48
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (62 43
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (53 53 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (50 43
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (48 48
         (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (44 44 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (40 40
         (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
     (36 36
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (34 21
         (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (33 33 (:REWRITE DEFAULT-<-2))
     (15 15
         (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (15 15
         (:REWRITE PFIELD::EQUAL-OF-ADD-COMBINE-CONSTANTS))
     (13 13
         (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (13 13
         (:REWRITE PFIELD::MUL-COMBINE-CONSTANTS))
     (13 13
         (:REWRITE PFIELD::EQUAL-OF-0-AND-ADD-SAFE))
     (13 13
         (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS))
     (12 6
         (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (12 6
         (:REWRITE ACL2-NUMBER-LISTP-OF-CDR-WHEN-ACL2-NUMBER-LISTP))
     (8 8 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (8 8
        (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP))
     (7 7
        (:REWRITE PFIELD::NEG-OF-MUL-WHEN-CONSTANT)))
(ECURVE::POINTP-OF-CURVE-GROUP-+
     (107 17
          (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (100 7 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (87 3 (:DEFINITION NAT-LISTP))
     (83 47
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (76 47
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (76 8 (:DEFINITION INTEGER-LISTP))
     (72 45
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (67 65 (:REWRITE DEFAULT-CAR))
     (56 56 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (55 55 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (55 53 (:REWRITE DEFAULT-CDR))
     (55 45
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (50 50
         (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (46 35
         (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (32 32
         (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (32 32 (:REWRITE DEFAULT-<-2))
     (32 32 (:REWRITE DEFAULT-<-1))
     (22 22
         (:TYPE-PRESCRIPTION PFIELD::NATP-OF-DIV))
     (22 2 (:REWRITE MOD-WHEN-MULTIPLE))
     (22 2
         (:REWRITE MOD-WHEN-INTEGERP-OF-QUOTIENT))
     (17 17
         (:REWRITE PFIELD::MUL-COMBINE-CONSTANTS))
     (16 4 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
     (14 14
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (12 6
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (12 4 (:REWRITE COMMUTATIVITY-OF-*))
     (11 11
         (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS))
     (9 9 (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (9 9 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (8 8
        (:REWRITE PFIELD::NEG-OF-MUL-WHEN-CONSTANT))
     (8 8 (:REWRITE DEFAULT-*-2))
     (8 8 (:REWRITE DEFAULT-*-1))
     (6 6 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (6 3
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (6 2 (:REWRITE MOD-WHEN-<))
     (4 4 (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
     (4 4
        (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (4 4
        (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
     (4 4 (:REWRITE DEFAULT-UNARY-/))
     (2 2
        (:REWRITE MOD-WHEN-RATIONALP-ARG1-AND-NOT-RATIONALP-ARG2))
     (2 2
        (:REWRITE MOD-WHEN-NOT-RATIONALP-ARG1-AND-RATIONALP-ARG2))
     (2 2
        (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG2))
     (2 2
        (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG1))
     (2 2
        (:REWRITE MOD-WHEN-EQUAL-OF-MOD-AND-0-FREE-CHEAP))
     (2 2
        (:REWRITE PFIELD::EQUAL-OF-ADD-COMBINE-CONSTANTS))
     (2 2
        (:REWRITE PFIELD::EQUAL-OF-0-AND-ADD-SAFE)))
(ECURVE::POINT-IN-PXP-P-OF-CURVE-GROUP-+
     (99 54
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (99 6 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (96 54
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (90 12
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (87 3 (:DEFINITION NAT-LISTP))
     (81 81 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (75 75 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (75 45
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (66 42
         (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (66 6 (:DEFINITION INTEGER-LISTP))
     (60 60
         (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (57 45
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (33 33
         (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (32 30 (:REWRITE DEFAULT-CDR))
     (32 30 (:REWRITE DEFAULT-CAR))
     (27 27
         (:TYPE-PRESCRIPTION PFIELD::NATP-OF-DIV))
     (27 27
         (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (24 24 (:REWRITE DEFAULT-<-2))
     (24 24 (:REWRITE DEFAULT-<-1))
     (21 21
         (:REWRITE PFIELD::MUL-COMBINE-CONSTANTS))
     (21 21
         (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS))
     (15 15
         (:REWRITE PFIELD::NEG-OF-MUL-WHEN-CONSTANT))
     (12 12
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (12 6
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (6 6 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (6 6 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (6 3
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (1 1
        (:REWRITE PFIELD::EQUAL-OF-ADD-COMBINE-CONSTANTS))
     (1 1
        (:REWRITE PFIELD::EQUAL-OF-0-AND-ADD-SAFE)))
(ECURVE::CURVE-GROUP-+-LEFT-IDENTITY
     (11 11
         (:TYPE-PRESCRIPTION ECURVE::CURVE-GROUP-+)))
(ECURVE::CURVE-GROUP-+-RIGHT-IDENTITY
     (11 11
         (:TYPE-PRESCRIPTION ECURVE::CURVE-GROUP-+))
     (2 2 (:META CANCEL_IPLUS-EQUAL-CORRECT)))
(ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P-EQUIVALENCE
     (5077 12
           (:REWRITE ECURVE::|x =p -y --> x + y =p 0|))
     (1646 8 (:REWRITE MOD-OF-MINUS-ARG1))
     (1379 4
           (:REWRITE ECURVE::|x + x =p 0 --> x =p 0|))
     (1118 14
           (:LINEAR MOD-BOUND-LINEAR-ARG2-STRONG))
     (940 52 (:REWRITE MOD-WHEN-MULTIPLE))
     (940 52
          (:REWRITE MOD-WHEN-INTEGERP-OF-QUOTIENT))
     (694 14 (:REWRITE ECURVE::NEG-INTRO))
     (476 6 (:LINEAR MOD-BOUND-LINEAR-ARG2))
     (412 92 (:REWRITE COMMUTATIVITY-OF-*))
     (392 160
          (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
     (362 44 (:REWRITE MOD-WHEN-<))
     (360 92 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
     (330 192 (:REWRITE DEFAULT-*-2))
     (328 192 (:REWRITE DEFAULT-*-1))
     (276 92 (:REWRITE DEFAULT-UNARY-/))
     (226 6 (:LINEAR MOD-BOUND-LINEAR-ARG1))
     (216 6 (:REWRITE ECURVE::ADD-OF---ARG2))
     (172 62 (:REWRITE DEFAULT-+-2))
     (167 105 (:REWRITE DEFAULT-<-2))
     (160 160
          (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (160 160
          (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
     (153 105 (:REWRITE DEFAULT-<-1))
     (136 12
          (:REWRITE DISTRIBUTIVITY-OF-MINUS-OVER-+))
     (130 65
          (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (126 6 (:REWRITE PFIELD::ADD-OF-ADD-SAME))
     (112 65
          (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (108 44
          (:REWRITE MOD-WHEN-RATIONALP-ARG1-AND-NOT-RATIONALP-ARG2))
     (88 44
         (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG2))
     (78 78
         (:TYPE-PRESCRIPTION PFIELD::NATP-OF-NEG))
     (76 62 (:REWRITE DEFAULT-+-1))
     (75 58
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (74 74 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (72 8
         (:REWRITE ECURVE::MOD-OF---BECOMES-NEG))
     (64 44
         (:REWRITE MOD-WHEN-NOT-RATIONALP-ARG1-AND-RATIONALP-ARG2))
     (64 44
         (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG1))
     (60 60 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (58 58
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (58 58
         (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (58 58 (:REWRITE PFIELD::MUL-COMMUTATIVE))
     (58 36
         (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (58 2 (:REWRITE COMMUTATIVITY-OF-+))
     (52 52
         (:REWRITE MOD-WHEN-EQUAL-OF-MOD-AND-0-FREE-CHEAP))
     (52 52 (:REWRITE FOLD-CONSTS-IN-+))
     (46 46
         (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS))
     (44 34 (:REWRITE DEFAULT-UNARY-MINUS))
     (36 36
         (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (33 2 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (32 32
         (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG2))
     (32 32
         (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG1))
     (30 4
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (29 1 (:DEFINITION NAT-LISTP))
     (28 2 (:REWRITE PFIELD::MUL-OF-NEG-ARG2))
     (24 24 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (22 2 (:DEFINITION INTEGER-LISTP))
     (20 20
         (:REWRITE PFIELD::NEG-OF-MUL-WHEN-CONSTANT))
     (18 6
         (:LINEAR ECURVE::PRIME-GREATER-THAN-2))
     (17 17 (:REWRITE PFIELD::MUL-COMMUTATIVE-2))
     (17 17
         (:REWRITE PFIELD::MUL-COMBINE-CONSTANTS))
     (16 16 (:TYPE-PRESCRIPTION ECURVE::=P))
     (11 11
         (:REWRITE PFIELD::EQUAL-OF-ADD-COMBINE-CONSTANTS))
     (8 2 (:REWRITE PFIELD::ADD-BOUND))
     (7 7 (:REWRITE DEFAULT-CDR))
     (7 7 (:REWRITE DEFAULT-CAR))
     (4 4
        (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (4 4
        (:REWRITE PFIELD::EQUAL-OF-MUL-CONSTANTS))
     (4 2
        (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (2 2 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE PFIELD::ADD-OF-NEG-OF-MUL-AND-ADD-OF-NEG-OF-MUL-SAME))
     (2 2
        (:REWRITE PFIELD::ADD-OF-MUL-AND-MUL-COMBINE-CONSTANTS))
     (2 1
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP)))
(ECURVE::CURVE-GROUP-+-EQUIVALENCE
     (1394 115 (:REWRITE DEFAULT-+-2))
     (909 480
          (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (891 891 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (777 777
          (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (524 480
          (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (415 212
          (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (401 212
          (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (339 105 (:REWRITE DEFAULT-*-2))
     (311 311 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (299 115 (:REWRITE DEFAULT-+-1))
     (255 149
          (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (222 105 (:REWRITE DEFAULT-*-1))
     (191 191
          (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS))
     (129 129
          (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (116 2
          (:REWRITE ECURVE::|x + x =p 0 --> x =p 0|))
     (114 114 (:REWRITE FOLD-CONSTS-IN-+))
     (99 6 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (90 12
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (87 3 (:DEFINITION NAT-LISTP))
     (86 86
         (:REWRITE PFIELD::NEG-OF-MUL-WHEN-CONSTANT))
     (86 2
         (:REWRITE ECURVE::|x =p -y --> x + y =p 0|))
     (66 9 (:REWRITE ECURVE::NEG-INTRO))
     (66 6 (:DEFINITION INTEGER-LISTP))
     (37 24 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 21 (:REWRITE DEFAULT-<-2))
     (26 21 (:REWRITE DEFAULT-<-1))
     (20 20 (:REWRITE DEFAULT-CDR))
     (20 20 (:REWRITE DEFAULT-CAR))
     (16 1 (:REWRITE PFIELD::EQUAL-OF-NEG))
     (15 1 (:REWRITE ECURVE::ADD-OF---ARG2))
     (12 12
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (12 6
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (10 10 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (9 9 (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (6 6 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (6 3
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (5 5
        (:REWRITE PFIELD::EQUAL-OF-ADD-COMBINE-CONSTANTS))
     (4 4 (:TYPE-PRESCRIPTION ECURVE::=P))
     (4 4
        (:REWRITE PFIELD::EQUAL-OF-0-AND-ADD-SAFE))
     (4 1
        (:REWRITE ECURVE::MOD-OF---BECOMES-NEG)))
(ECURVE::POINTP-AND-POINTP-IN-PXP-OF-CURVE-GROUP-+-ABSTRACT)
(ECURVE::POINT-ON-WEIERSTRASS-ELLIPTIC-CURVE-P-OF-CURVE-GROUP-+-ABSTRACT)
(ECURVE::PRIMEP-OF-5)
(ECURVE::CLOSURE-OF-CURVE-GROUP-+
     (2 1 (:REWRITE DEFAULT-<-2))
     (1 1
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1 1 (:REWRITE DEFAULT-<-1)))
(ECURVE::CURVE-SCALAR-* (8 2 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
                        (7 7 (:REWRITE DEFAULT-<-2))
                        (7 7 (:REWRITE DEFAULT-<-1))
                        (6 6 (:REWRITE DEFAULT-*-2))
                        (6 6 (:REWRITE DEFAULT-*-1))
                        (2 2 (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
                        (2 2
                           (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
                        (2 2
                           (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
                        (2 2 (:REWRITE ZP-OPEN))
                        (2 2 (:META CANCEL_IPLUS-EQUAL-CORRECT))
                        (1 1 (:REWRITE DEFAULT-+-2))
                        (1 1 (:REWRITE DEFAULT-+-1)))
(ECURVE::CLOSURE-OF-CURVE-SCALAR-*
     (46 46 (:REWRITE DEFAULT-*-2))
     (46 46 (:REWRITE DEFAULT-*-1))
     (36 36 (:REWRITE DEFAULT-<-2))
     (36 36 (:REWRITE DEFAULT-<-1))
     (36 9 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
     (9 9 (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
     (9 9
        (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (9 9
        (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
     (9 9 (:REWRITE ZP-OPEN))
     (9 9 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (8 8 (:REWRITE DEFAULT-+-2))
     (8 8 (:REWRITE DEFAULT-+-1)))
(ECURVE::CURVE-SCALAR-* (712 200 (:REWRITE PFIELD::FEP-HOLDS))
                        (426 335 (:REWRITE DEFAULT-<-2))
                        (338 82 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
                        (335 335 (:REWRITE DEFAULT-<-1))
                        (249 242 (:REWRITE DEFAULT-*-2))
                        (242 242 (:REWRITE DEFAULT-*-1))
                        (101 101
                             (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
                        (85 85 (:REWRITE ZP-OPEN))
                        (85 85 (:META CANCEL_IPLUS-EQUAL-CORRECT))
                        (82 82
                            (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
                        (82 82
                            (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
                        (82 82
                            (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
                        (58 55 (:REWRITE DEFAULT-+-2))
                        (55 55 (:REWRITE DEFAULT-+-1))
                        (5 5
                           (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE))
                        (5 5 (:TYPE-PRESCRIPTION MOD)))
(ECURVE::POINTP-OF-CURVE-SCALAR-*
     (20 20 (:REWRITE DEFAULT-<-2))
     (20 20 (:REWRITE DEFAULT-<-1))
     (16 16 (:REWRITE DEFAULT-*-2))
     (16 16 (:REWRITE DEFAULT-*-1))
     (16 4 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
     (16 4
         (:REWRITE ECURVE::CLOSURE-OF-CURVE-SCALAR-*))
     (6 6 (:TYPE-PRESCRIPTION RTL::PRIMEP))
     (6 2
        (:REWRITE ECURVE::CLOSURE-OF-CURVE-GROUP-+))
     (5 5 (:REWRITE ZP-OPEN))
     (4 4 (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
     (4 4
        (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (4 4
        (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
     (4 4 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (3 3 (:TYPE-PRESCRIPTION NATP))
     (2 2 (:REWRITE DEFAULT-+-2))
     (2 2 (:REWRITE DEFAULT-+-1)))
(ECURVE::POINT-IN-PXP-P-OF-CURVE-SCALAR-*
     (22 22 (:REWRITE DEFAULT-<-2))
     (22 22 (:REWRITE DEFAULT-<-1))
     (16 16 (:REWRITE DEFAULT-*-2))
     (16 16 (:REWRITE DEFAULT-*-1))
     (16 4 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
     (12 4
         (:REWRITE ECURVE::CLOSURE-OF-CURVE-SCALAR-*))
     (10 10 (:TYPE-PRESCRIPTION RTL::PRIMEP))
     (6 2
        (:REWRITE ECURVE::CLOSURE-OF-CURVE-GROUP-+))
     (4 4 (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
     (4 4
        (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (4 4
        (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
     (4 4 (:REWRITE ZP-OPEN))
     (4 4 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (2 2 (:REWRITE DEFAULT-+-2))
     (2 2 (:REWRITE DEFAULT-+-1))
     (1 1 (:TYPE-PRESCRIPTION NATP)))
(ECURVE::CURVE-NEGATE
     (194 8 (:REWRITE DEFAULT-<-1))
     (154 5
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (152 4
          (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
     (149 17
          (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
     (149 2 (:DEFINITION ACL2-NUMBER-LISTP))
     (145 3 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (142 2 (:DEFINITION NAT-LISTP))
     (138 15
          (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (133 9 (:DEFINITION RATIONAL-LISTP))
     (122 9 (:DEFINITION INTEGER-LISTP))
     (58 14
         (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
     (47 14
         (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (35 35 (:REWRITE DEFAULT-CDR))
     (34 34 (:REWRITE DEFAULT-CAR))
     (20 20
         (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (8 8 (:REWRITE DEFAULT-<-2))
     (6 3
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (6 3
        (:REWRITE ACL2-NUMBER-LISTP-OF-CDR-WHEN-ACL2-NUMBER-LISTP))
     (4 4 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (4 4
        (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP)))
(ECURVE::CLOSURE-OF-CURVE-NEGATE
     (9273 798 (:META META-INTEGERP-CORRECT))
     (9236 167 (:REWRITE MOD-WHEN-MULTIPLE))
     (9236 167
           (:REWRITE MOD-WHEN-INTEGERP-OF-QUOTIENT))
     (9012 167 (:REWRITE MOD-ZERO . 2))
     (8253 2693 (:TYPE-PRESCRIPTION MOD-ZERO . 1))
     (7594 167 (:REWRITE PFIELD::MOD-WHEN-FEP))
     (7155 130 (:REWRITE PFIELD::FEP-HOLDS))
     (6420 343
           (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
     (6061 167 (:REWRITE MOD-ZERO . 3))
     (5906 165 (:REWRITE MOD-WHEN-<))
     (4539 173 (:REWRITE MOD-X-Y-=-X . 4))
     (4126 4126
           (:TYPE-PRESCRIPTION NOT-INTEGERP-3B))
     (4126 4126
           (:TYPE-PRESCRIPTION NOT-INTEGERP-2B))
     (4126 4126
           (:TYPE-PRESCRIPTION NOT-INTEGERP-1B))
     (3955 1089 (:REWRITE DEFAULT-*-2))
     (2735 227 (:REWRITE DEFAULT-+-2))
     (2693 2693
           (:TYPE-PRESCRIPTION MOD-NONPOSITIVE))
     (2693 2693
           (:TYPE-PRESCRIPTION MOD-NEGATIVE . 2))
     (2693 2693
           (:TYPE-PRESCRIPTION MOD-NEGATIVE . 1))
     (2632 1142
           (:REWRITE SIMPLIFY-PRODUCTS-GATHER-EXPONENTS-<))
     (2541 2541
           (:TYPE-PRESCRIPTION MOD-POSITIVE . 1))
     (2237 1131 (:REWRITE DEFAULT-<-1))
     (2090 2090
           (:TYPE-PRESCRIPTION NOT-INTEGERP-3A))
     (2090 2090
           (:TYPE-PRESCRIPTION NOT-INTEGERP-2A))
     (1415 1131 (:REWRITE DEFAULT-<-2))
     (1386 234 (:LINEAR EXPT-X->=-X))
     (1151 1151
           (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (1151 1151
           (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE))
     (1146 1146 (:REWRITE |(< (- x) (- y))|))
     (1089 1089 (:REWRITE DEFAULT-*-1))
     (1002 17 (:LINEAR MOD-BOUNDS-3))
     (983 234 (:LINEAR EXPT-X->-X))
     (983 234 (:LINEAR EXPT->-1-ONE))
     (983 234 (:LINEAR EXPT-<-1-TWO))
     (967 227 (:REWRITE DEFAULT-+-1))
     (963 234 (:LINEAR EXPT->-1-TWO))
     (963 234 (:LINEAR EXPT-<-1-ONE))
     (885 885
          (:REWRITE NORMALIZE-TERMS-SUCH-AS-1/AX+BX))
     (885 885 (:REWRITE DEFAULT-UNARY-/))
     (794 334 (:REWRITE MOD-COMPLETION))
     (639 179 (:REWRITE MOD-CANCEL-*))
     (627 167
          (:REWRITE MOD-WHEN-RATIONALP-ARG1-AND-NOT-RATIONALP-ARG2))
     (627 167
          (:REWRITE MOD-WHEN-NOT-RATIONALP-ARG1-AND-RATIONALP-ARG2))
     (627 167
          (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG1))
     (604 604 (:REWRITE |(integerp (* c x))|))
     (583 206
          (:REWRITE SIMPLIFY-PRODUCTS-GATHER-EXPONENTS-EQUAL))
     (567 567
          (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
     (548 206
          (:REWRITE PREFER-POSITIVE-ADDENDS-EQUAL))
     (510 468
          (:LINEAR EXPT-IS-INCREASING-FOR-BASE->-1))
     (500 179 (:REWRITE MOD-MINUS-2))
     (468 468
          (:LINEAR EXPT-IS-WEAKLY-INCREASING-FOR-BASE->-1))
     (468 468
          (:LINEAR EXPT-IS-WEAKLY-DECREASING-FOR-POS-BASE-<-1))
     (468 468
          (:LINEAR EXPT-IS-DECREASING-FOR-POS-BASE-<-1))
     (400 8 (:REWRITE |(* y (* x z))|))
     (373 373
          (:TYPE-PRESCRIPTION NOT-INTEGERP-4D))
     (373 373
          (:TYPE-PRESCRIPTION NOT-INTEGERP-3D))
     (373 373
          (:TYPE-PRESCRIPTION NOT-INTEGERP-2D))
     (373 373
          (:TYPE-PRESCRIPTION NOT-INTEGERP-1D))
     (361 8 (:REWRITE |(* (if a b c) x)|))
     (352 16 (:TYPE-PRESCRIPTION NOT-INTEGERP-4C))
     (316 300 (:REWRITE DEFAULT-CAR))
     (288 76 (:REWRITE DEFAULT-UNARY-MINUS))
     (275 275 (:REWRITE |(< 0 (- x))|))
     (274 274
          (:REWRITE REMOVE-WEAK-INEQUALITIES-ONE))
     (273 273
          (:REWRITE SIMPLIFY-TERMS-SUCH-AS-0-<-A+AB))
     (273 273 (:REWRITE |(equal (- x) (- y))|))
     (272 272 (:TYPE-PRESCRIPTION PFIELD::FEP))
     (264 264 (:REWRITE |(equal (- x) 0)|))
     (262 262 (:REWRITE |(expt x (- n))|))
     (262 262 (:REWRITE |(expt 2^i n)|))
     (262 262 (:REWRITE |(expt 1/c n)|))
     (262 262 (:REWRITE |(expt (- x) n)|))
     (258 258 (:REWRITE DEFAULT-EXPT-2))
     (258 258 (:REWRITE DEFAULT-EXPT-1))
     (227 227
          (:REWRITE NORMALIZE-TERMS-SUCH-AS-A/A+B-+-B/A+B))
     (215 167 (:REWRITE MOD-X-Y-=-X . 2))
     (205 205 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (201 201 (:REWRITE SIMPLIFY-MOD-+-MINUS-MOD))
     (200 200
          (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (200 200
          (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-RATIONALP-BASE))
     (200 19 (:REWRITE MOD-+-CANCEL-0-WEAK))
     (197 197
          (:REWRITE SIMPLIFY-TERMS-SUCH-AS-A+AB-=-0))
     (194 194
          (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
     (189 173 (:REWRITE DEFAULT-CDR))
     (167 167
          (:REWRITE MOD-WHEN-NOT-ACL2-NUMBERP-ARG2))
     (167 167
          (:REWRITE MOD-WHEN-EQUAL-OF-MOD-AND-0-FREE-CHEAP))
     (164 164 (:REWRITE |(* c (* d x))|))
     (114 34 (:LINEAR MOD-BOUNDS-2))
     (100 2 (:REWRITE |(< x (if a b c))|))
     (91 65 (:REWRITE |(< (+ c x) d)|))
     (63 63 (:REWRITE FOLD-CONSTS-IN-+))
     (58 8
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (57 57
         (:REWRITE INTEGERP-+-REDUCE-LEADING-RATIONAL-CONSTANT))
     (50 20
         (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
     (47 2 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (46 46 (:REWRITE |(< (+ c x y) d)|))
     (44 4 (:DEFINITION INTEGER-LISTP))
     (43 1 (:DEFINITION NAT-LISTP))
     (39 39 (:REWRITE |(< (- x) 0)|))
     (35 35
         (:REWRITE SIMPLIFY-TERMS-SUCH-AS-A+AB-<-0))
     (27 1 (:REWRITE |(< (+ d x) (+ c y))|))
     (25 5 (:DEFINITION ACL2-NUMBER-LISTP))
     (23 2 (:REWRITE |(equal (if a b c) x)|))
     (16 16 (:TYPE-PRESCRIPTION NOT-INTEGERP-3C))
     (16 16 (:TYPE-PRESCRIPTION NOT-INTEGERP-2C))
     (16 16 (:TYPE-PRESCRIPTION NOT-INTEGERP-1C))
     (9 9 (:REWRITE |(< d (+ c x))|))
     (8 4
        (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (7 7
        (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG2))
     (7 7
        (:REWRITE MOD-OF-*-SUBST-CONSTANT-ARG1))
     (6 6
        (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (6 6
        (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (6 6
        (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (6 6 (:REWRITE |(equal (+ c x) d)|))
     (5 5 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (5 5
        (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP))
     (5 2
        (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (4 4
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (4 4
        (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (4 4
        (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (4 4 (:REWRITE PFIELD::MUL-COMMUTATIVE))
     (4 2
        (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (3 3 (:TYPE-PRESCRIPTION FLOOR-ZERO . 3))
     (3 3 (:TYPE-PRESCRIPTION FLOOR-ZERO . 2))
     (3 3 (:TYPE-PRESCRIPTION FLOOR-ZERO . 1))
     (3 3
        (:TYPE-PRESCRIPTION FLOOR-POSITIVE . 2))
     (3 3
        (:TYPE-PRESCRIPTION FLOOR-POSITIVE . 1))
     (3 3
        (:TYPE-PRESCRIPTION FLOOR-NONPOSITIVE-2))
     (3 3
        (:TYPE-PRESCRIPTION FLOOR-NONPOSITIVE-1))
     (3 3
        (:TYPE-PRESCRIPTION FLOOR-NONNEGATIVE-2))
     (3 3
        (:TYPE-PRESCRIPTION FLOOR-NEGATIVE . 2))
     (3 3
        (:TYPE-PRESCRIPTION FLOOR-NEGATIVE . 1))
     (3 3 (:REWRITE MOD-POSITIVE . 3))
     (3 3 (:REWRITE MOD-POSITIVE . 2))
     (3 3 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (2 2 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (2 2 (:REWRITE MOD-NEGATIVE . 3))
     (2 2 (:REWRITE MOD-NEGATIVE . 2))
     (2 2
        (:REWRITE EQUAL-OF-MOD-OF-+-WHEN-CONSTANTS))
     (2 2
        (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (2 1
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (1 1 (:REWRITE |(< d (+ c x y))|))
     (1 1 (:REWRITE |(< (+ c x) (+ d y))|)))
(ECURVE::POINTP-OF-CURVE-NEGATE
     (33 2 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (30 4
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (29 1 (:DEFINITION NAT-LISTP))
     (22 2 (:DEFINITION INTEGER-LISTP))
     (7 6 (:REWRITE DEFAULT-CDR))
     (7 6 (:REWRITE DEFAULT-CAR))
     (4 4
        (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 2
        (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (2 2 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (2 1
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
     (1 1
        (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (1 1
        (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (1 1 (:META CANCEL_IPLUS-EQUAL-CORRECT)))
(ECURVE::POINT-IN-PXP-P-OF-CURVE-NEGATE
     (33 3 (:REWRITE MOD-WHEN-MULTIPLE))
     (33 3
         (:REWRITE MOD-WHEN-INTEGERP-OF-QUOTIENT))
     (33 2 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
     (30 4
         (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
     (29 1 (:DEFINITION NAT-LISTP))
     (24 6 (:REWRITE MULTIPLE-WHEN-MOD-0-CHEAP))
     (22 2 (:DEFINITION INTEGER-LISTP))
     (18 6 (:REWRITE COMMUTATIVITY-OF-*))
     (12 12 (:REWRITE DEFAULT-*-2))
     (12 12 (:REWRITE DEFAULT-*-1))
     (11 11 (:REWRITE DEFAULT-<-2))
     (11 11 (:REWRITE DEFAULT-<-1))
     (9 9 (:REWRITE DEFAULT-CDR))
     (9 9 (:REWRITE DEFAULT-CAR))
     (6 6 (:TYPE-PRESCRIPTION RATIONALP-OF-MOD))
     (6 6
        (:TYPE-PRESCRIPTION NONNEG-OF-MOD-TYPE-2))
     (6 6
        (:TYPE-PRESCRIPTION INTEGERP-OF-MOD-TYPE))
     (6 6 (:REWRITE DEFAULT-UNARY-MINUS))
     (6 6 (:REWRITE DEFAULT-UNARY-/))
     (4 4
        (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
     (4 4 (:META CANCEL_IPLUS-EQUAL-CORRECT))
     (4 2
        (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
     (3 3
        (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (3 3
        (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (3 3
        (:REWRITE MOD-WHEN-EQUAL-OF-MOD-AND-0-FREE-CHEAP))
     (3 3 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE DEFAULT-+-1))
     (2 2 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
     (2 1
        (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP)))
