
DEFAULT_ACL2_ROOT = ../../../../..

ACL2BOOKS = $(DEFAULT_ACL2_ROOT)/books

include $(ACL2BOOKS)/Makefile-generic

ACL2 = $(DEFAULT_ACL2_ROOT)/saved_acl2

BOOKS = mark defrecord

# Dependencies:

mark.cert: mark.lisp
mark.cert: defrecord.cert

defrecord.cert: defrecord.lisp
