(TEA-ENCRYPT-LOOP$NOT-NORMALIZED)
(TEA-ENCRYPT-LOOP-BASE)
(TEA-ENCRYPT-LOOP-UNROLL
 (10 10 (:DEFINITION MV-NTH))
 )
(TEA-DECRYPT-LOOP$NOT-NORMALIZED)
(TEA-DECRYPT-LOOP-BASE)
(TEA-DECRYPT-LOOP-UNROLL
 (10 10 (:DEFINITION MV-NTH))
 )
(TEA-SPEC-RULES)
