include ../../../../Makefile-generic


# Override default setting since build.lisp is not intended to be certified.
BOOKS = fast-sets fixpoints models relations semantics sets syntax

-include Makefile-deps
