(SV::LEN-OF-NTHCDR
     (124 84 (:REWRITE DEFAULT-+-2))
     (88 84 (:REWRITE DEFAULT-+-1))
     (35 28 (:REWRITE DEFAULT-<-1))
     (34 12 (:REWRITE ZP-WHEN-GT-0))
     (28 28 (:REWRITE DEFAULT-<-2))
     (27 15 (:REWRITE FOLD-CONSTS-IN-+))
     (26 11 (:REWRITE ZP-WHEN-INTEGERP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (13 13 (:REWRITE DEFAULT-UNARY-MINUS))
     (9 9 (:LINEAR INDEX-OF-<-LEN))
     (6 6 (:REWRITE ZP-OPEN))
     (3 3 (:REWRITE NFIX-WHEN-NOT-NATP))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::LEN-EQUAL-0 (10 10
                     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
                 (10 10
                     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
                 (10 10 (:LINEAR LEN-WHEN-PREFIXP))
                 (9 5 (:REWRITE DEFAULT-+-2))
                 (5 5 (:REWRITE DEFAULT-+-1))
                 (5 5 (:LINEAR INDEX-OF-<-LEN))
                 (4 4 (:REWRITE DEFAULT-CDR)))
(SV::SVTV-PARSE-PATH-INDICES (10 5 (:REWRITE DEFAULT-+-2))
                             (7 7 (:REWRITE DEFAULT-CDR))
                             (5 5 (:REWRITE DEFAULT-+-1))
                             (2 1 (:REWRITE DEFAULT-<-2))
                             (2 1 (:REWRITE DEFAULT-<-1))
                             (1 1 (:TYPE-PRESCRIPTION SV::PATH-WIRE)))
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH-INDICES.PATH
 (956 32 (:DEFINITION LEN))
 (525 63 (:REWRITE DEFAULT-CDR))
 (342 48
      (:REWRITE STR::DEC-DIGIT-CHAR-P-OF-CAR-WHEN-DEC-DIGIT-CHAR-LISTP))
 (330 8 (:DEFINITION EXPT))
 (329 71 (:REWRITE DEFAULT-CAR))
 (233 64
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-WHEN-NOT-CONSP))
 (208 48
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-OF-NTHCDR))
 (193 8 (:REWRITE ZIP-OPEN))
 (187 24
      (:REWRITE STR::TAKE-LEADING-DEC-DIGIT-CHARS-WHEN-DEC-DIGIT-CHAR-LISTP))
 (154 77 (:REWRITE DEFAULT-+-2))
 (128 128
      (:TYPE-PRESCRIPTION STR::DEC-DIGIT-CHAR-LISTP))
 (128 48
      (:REWRITE STR::DEC-DIGIT-CHAR-P-WHEN-NONZERO-DEC-DIGIT-CHAR-P))
 (112 56 (:REWRITE STR::CONSP-OF-EXPLODE))
 (87 77 (:REWRITE DEFAULT-+-1))
 (80 80
     (:TYPE-PRESCRIPTION STR::NONZERO-DEC-DIGIT-CHAR-P$INLINE))
 (80 48
     (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (57 8 (:DEFINITION NTHCDR))
 (56 16 (:REWRITE DEFAULT-*-2))
 (34 34
     (:REWRITE SV::PATH-P-WHEN-MEMBER-EQUAL-OF-PATHLIST-P))
 (29 9 (:REWRITE COMMUTATIVITY-OF-+))
 (16 16 (:REWRITE STREQV-OF-STR-FIX))
 (16 16 (:REWRITE STR-FIX-WHEN-STRINGP))
 (16 16 (:REWRITE STR-FIX-DEFAULT))
 (16 16 (:REWRITE DEFAULT-*-1))
 (16 8 (:REWRITE DEFAULT-<-2))
 (8 8 (:REWRITE NTH-WHEN-PREFIXP))
 (8 8 (:REWRITE DEFAULT-<-1))
 (5 2 (:REWRITE FOLD-CONSTS-IN-+))
 (4 4
    (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV)))
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH-INDICES.RANGE-MSB
 (880 28 (:DEFINITION LEN))
 (493 57 (:REWRITE DEFAULT-CDR))
 (320 42
      (:REWRITE STR::DEC-DIGIT-CHAR-P-OF-CAR-WHEN-DEC-DIGIT-CHAR-LISTP))
 (307 61 (:REWRITE DEFAULT-CAR))
 (296 7 (:DEFINITION EXPT))
 (215 57
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-WHEN-NOT-CONSP))
 (183 43
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-OF-NTHCDR))
 (175 7 (:REWRITE ZIP-OPEN))
 (157 21
      (:REWRITE STR::TAKE-LEADING-DEC-DIGIT-CHARS-WHEN-DEC-DIGIT-CHAR-LISTP))
 (146 73 (:REWRITE DEFAULT-+-2))
 (114 114
      (:TYPE-PRESCRIPTION STR::DEC-DIGIT-CHAR-LISTP))
 (114 42
      (:REWRITE STR::DEC-DIGIT-CHAR-P-WHEN-NONZERO-DEC-DIGIT-CHAR-P))
 (98 49 (:REWRITE STR::CONSP-OF-EXPLODE))
 (84 73 (:REWRITE DEFAULT-+-1))
 (72 72
     (:TYPE-PRESCRIPTION STR::NONZERO-DEC-DIGIT-CHAR-P$INLINE))
 (70 42
     (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (60 7 (:DEFINITION NTHCDR))
 (49 14 (:REWRITE DEFAULT-*-2))
 (42 14 (:REWRITE NATP-WHEN-GTE-0))
 (31 9 (:REWRITE COMMUTATIVITY-OF-+))
 (28 21 (:REWRITE DEFAULT-<-2))
 (21 21 (:REWRITE DEFAULT-<-1))
 (14 14 (:REWRITE STREQV-OF-STR-FIX))
 (14 14 (:REWRITE NATP-WHEN-INTEGERP))
 (14 14 (:REWRITE DEFAULT-*-1))
 (12 12 (:REWRITE STR-FIX-WHEN-STRINGP))
 (12 12 (:REWRITE STR-FIX-DEFAULT))
 (10 4 (:REWRITE FOLD-CONSTS-IN-+))
 (7 7 (:REWRITE NTH-WHEN-PREFIXP))
 (4 4
    (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV)))
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH-INDICES.RANGE-LSB
 (880 28 (:DEFINITION LEN))
 (493 57 (:REWRITE DEFAULT-CDR))
 (320 42
      (:REWRITE STR::DEC-DIGIT-CHAR-P-OF-CAR-WHEN-DEC-DIGIT-CHAR-LISTP))
 (307 61 (:REWRITE DEFAULT-CAR))
 (296 7 (:DEFINITION EXPT))
 (215 57
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-WHEN-NOT-CONSP))
 (183 43
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-OF-NTHCDR))
 (175 7 (:REWRITE ZIP-OPEN))
 (157 21
      (:REWRITE STR::TAKE-LEADING-DEC-DIGIT-CHARS-WHEN-DEC-DIGIT-CHAR-LISTP))
 (146 73 (:REWRITE DEFAULT-+-2))
 (114 114
      (:TYPE-PRESCRIPTION STR::DEC-DIGIT-CHAR-LISTP))
 (114 42
      (:REWRITE STR::DEC-DIGIT-CHAR-P-WHEN-NONZERO-DEC-DIGIT-CHAR-P))
 (98 49 (:REWRITE STR::CONSP-OF-EXPLODE))
 (84 73 (:REWRITE DEFAULT-+-1))
 (72 72
     (:TYPE-PRESCRIPTION STR::NONZERO-DEC-DIGIT-CHAR-P$INLINE))
 (70 42
     (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (60 7 (:DEFINITION NTHCDR))
 (49 14 (:REWRITE DEFAULT-*-2))
 (42 14 (:REWRITE NATP-WHEN-GTE-0))
 (31 9 (:REWRITE COMMUTATIVITY-OF-+))
 (28 21 (:REWRITE DEFAULT-<-2))
 (21 21 (:REWRITE DEFAULT-<-1))
 (14 14 (:REWRITE STREQV-OF-STR-FIX))
 (14 14 (:REWRITE NATP-WHEN-INTEGERP))
 (14 14 (:REWRITE DEFAULT-*-1))
 (12 12 (:REWRITE STR-FIX-WHEN-STRINGP))
 (12 12 (:REWRITE STR-FIX-DEFAULT))
 (10 4 (:REWRITE FOLD-CONSTS-IN-+))
 (7 7 (:REWRITE NTH-WHEN-PREFIXP))
 (4 4
    (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV)))
(SV::LEN-OF-NTHCDR-1 (15 3 (:DEFINITION LEN))
                     (11 6 (:REWRITE DEFAULT-+-2))
                     (7 6 (:REWRITE DEFAULT-+-1))
                     (4 4
                        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
                     (4 4
                        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
                     (4 4 (:LINEAR LEN-WHEN-PREFIXP))
                     (3 3 (:REWRITE DEFAULT-CDR))
                     (2 2 (:LINEAR INDEX-OF-<-LEN))
                     (2 1 (:REWRITE DEFAULT-<-1))
                     (1 1 (:REWRITE DEFAULT-<-2)))
(SV::SVTV-PARSE-PATH-INDICES
 (1328 2
       (:DEFINITION SV::SVTV-PARSE-PATH-INDICES))
 (1109 191 (:REWRITE DEFAULT-CDR))
 (588 98
      (:REWRITE STR::DEC-DIGIT-CHAR-P-OF-CAR-WHEN-DEC-DIGIT-CHAR-LISTP))
 (554 170 (:REWRITE DEFAULT-CAR))
 (436 221 (:REWRITE DEFAULT-+-2))
 (423 105
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-WHEN-NOT-CONSP))
 (352 71
      (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-OF-NTHCDR))
 (336 30
      (:REWRITE STR::TAKE-LEADING-DEC-DIGIT-CHARS-WHEN-DEC-DIGIT-CHAR-LISTP))
 (326 7 (:DEFINITION EXPT))
 (241 221 (:REWRITE DEFAULT-+-1))
 (210 210
      (:TYPE-PRESCRIPTION STR::DEC-DIGIT-CHAR-LISTP))
 (208 98
      (:REWRITE STR::DEC-DIGIT-CHAR-P-WHEN-NONZERO-DEC-DIGIT-CHAR-P))
 (197 7 (:REWRITE ZIP-OPEN))
 (167 151
      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
 (111 16 (:DEFINITION NTHCDR))
 (110 110
      (:TYPE-PRESCRIPTION STR::NONZERO-DEC-DIGIT-CHAR-P$INLINE))
 (50 30
     (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
 (49 14 (:REWRITE DEFAULT-*-2))
 (35 22 (:REWRITE DEFAULT-<-2))
 (35 22 (:REWRITE DEFAULT-<-1))
 (32 32
     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (32 32
     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (32 32 (:LINEAR LEN-WHEN-PREFIXP))
 (28 28
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (21 21
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (21 21 (:REWRITE NTH-WHEN-PREFIXP))
 (16 16 (:LINEAR INDEX-OF-<-LEN))
 (15 6 (:REWRITE FOLD-CONSTS-IN-+))
 (14 14 (:REWRITE DEFAULT-*-1))
 (12 12 (:REWRITE STREQV-OF-STR-FIX))
 (8 8
    (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
 (4 4
    (:REWRITE STR::REST-OF-PARSE-NAT-FROM-CHARLIST))
 (2 2 (:REWRITE STR-FIX-DEFAULT)))
(SV::SVTV-PARSE-PATH-INDICES-OF-STRING-LIST-FIX-BRACKETED-PARTS
     (5718 303
           (:REWRITE STR::DEC-DIGIT-CHAR-P-OF-CAR-WHEN-DEC-DIGIT-CHAR-LISTP))
     (4886 104 (:DEFINITION EXPT))
     (3812 606
           (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-WHEN-NOT-CONSP))
     (3120 104 (:REWRITE ZIP-OPEN))
     (2472 303
           (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-OF-NTHCDR))
     (2316 1256 (:REWRITE DEFAULT-+-2))
     (1558 1256 (:REWRITE DEFAULT-+-1))
     (1429 503
           (:REWRITE STR::STRING-LIST-FIX-WHEN-STRING-LISTP))
     (1212 1212
           (:TYPE-PRESCRIPTION STR::DEC-DIGIT-CHAR-LISTP))
     (999 999 (:REWRITE STR-FIX-WHEN-STRINGP))
     (999 999 (:REWRITE STR-FIX-DEFAULT))
     (926 926 (:TYPE-PRESCRIPTION STRING-LISTP))
     (909 303
          (:REWRITE STR::DEC-DIGIT-CHAR-P-WHEN-NONZERO-DEC-DIGIT-CHAR-P))
     (892 892
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (892 892
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (892 892 (:LINEAR LEN-WHEN-PREFIXP))
     (728 208 (:REWRITE DEFAULT-*-2))
     (694 347 (:REWRITE STR::CONSP-OF-EXPLODE))
     (679 679
          (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (679 679
          (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (606 606
          (:TYPE-PRESCRIPTION STR::NONZERO-DEC-DIGIT-CHAR-P$INLINE))
     (547 345 (:REWRITE DEFAULT-<-1))
     (449 345 (:REWRITE DEFAULT-<-2))
     (446 446 (:LINEAR INDEX-OF-<-LEN))
     (278 278
          (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
     (270 54 (:LINEAR SV::LEN-OF-NTHCDR-1))
     (230 230 (:REWRITE NTH-WHEN-PREFIXP))
     (208 208 (:REWRITE DEFAULT-*-1))
     (153 139
          (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONG))
     (140 140
          (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
     (128 128 (:REWRITE FOLD-CONSTS-IN-+))
     (88 44 (:REWRITE NFIX-WHEN-NOT-NATP))
     (88 44 (:REWRITE DEFAULT-UNARY-MINUS)))
(SV::SVTV-PARSE-PATH-INDICES-STRING-LIST-EQUIV-CONGRUENCE-ON-BRACKETED-PARTS)
(SV::SVTV-PARSE-PATH-INDICES-OF-BOOL-FIX-LASTP
     (318 6 (:DEFINITION EXPT))
     (240 12
          (:REWRITE STR::DEC-DIGIT-CHAR-P-OF-CAR-WHEN-DEC-DIGIT-CHAR-LISTP))
     (208 6 (:REWRITE ZIP-OPEN))
     (156 24
          (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-WHEN-NOT-CONSP))
     (108 12
          (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-OF-NTHCDR))
     (74 36 (:REWRITE DEFAULT-+-2))
     (48 48
         (:TYPE-PRESCRIPTION STR::DEC-DIGIT-CHAR-LISTP))
     (44 36 (:REWRITE DEFAULT-+-1))
     (42 12 (:REWRITE DEFAULT-*-2))
     (36 12
         (:REWRITE STR::DEC-DIGIT-CHAR-P-WHEN-NONZERO-DEC-DIGIT-CHAR-P))
     (30 18
         (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (27 9 (:REWRITE BOOL-FIX-WHEN-BOOLEANP))
     (24 24
         (:TYPE-PRESCRIPTION STR::NONZERO-DEC-DIGIT-CHAR-P$INLINE))
     (24 12 (:REWRITE STR::CONSP-OF-EXPLODE))
     (18 18
         (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (18 18 (:TYPE-PRESCRIPTION BOOLEANP))
     (18 6 (:REWRITE COMMUTATIVITY-OF-+))
     (12 12 (:REWRITE STREQV-OF-STR-FIX))
     (12 12 (:REWRITE STR-FIX-WHEN-STRINGP))
     (12 12 (:REWRITE STR-FIX-DEFAULT))
     (12 12 (:REWRITE DEFAULT-*-1))
     (12 6 (:REWRITE DEFAULT-<-2))
     (6 6
        (:TYPE-PRESCRIPTION STR::NATP-OF-DEC-DIGIT-CHARS-VALUE))
     (6 6 (:REWRITE NTH-WHEN-PREFIXP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (2 2 (:REWRITE FOLD-CONSTS-IN-+)))
(SV::SVTV-PARSE-PATH-INDICES-IFF-CONGRUENCE-ON-LASTP)
(SV::SVTV-PARSE-PATH-INDICES-OF-STR-FIX-ORIG-X
     (318 6 (:DEFINITION EXPT))
     (240 12
          (:REWRITE STR::DEC-DIGIT-CHAR-P-OF-CAR-WHEN-DEC-DIGIT-CHAR-LISTP))
     (208 6 (:REWRITE ZIP-OPEN))
     (156 24
          (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-WHEN-NOT-CONSP))
     (108 12
          (:REWRITE STR::DEC-DIGIT-CHAR-LISTP-OF-NTHCDR))
     (74 36 (:REWRITE DEFAULT-+-2))
     (48 48
         (:TYPE-PRESCRIPTION STR::DEC-DIGIT-CHAR-LISTP))
     (44 36 (:REWRITE DEFAULT-+-1))
     (42 12 (:REWRITE DEFAULT-*-2))
     (36 12
         (:REWRITE STR::DEC-DIGIT-CHAR-P-WHEN-NONZERO-DEC-DIGIT-CHAR-P))
     (30 18
         (:TYPE-PRESCRIPTION RATIONALP-EXPT-TYPE-PRESCRIPTION))
     (24 24
         (:TYPE-PRESCRIPTION STR::NONZERO-DEC-DIGIT-CHAR-P$INLINE))
     (24 12 (:REWRITE STR::CONSP-OF-EXPLODE))
     (18 18
         (:TYPE-PRESCRIPTION EXPT-TYPE-PRESCRIPTION-NON-ZERO-BASE))
     (18 6 (:REWRITE COMMUTATIVITY-OF-+))
     (12 12 (:REWRITE STR-FIX-DEFAULT))
     (12 12 (:REWRITE DEFAULT-*-1))
     (12 6 (:REWRITE DEFAULT-<-2))
     (6 6
        (:TYPE-PRESCRIPTION STR::NATP-OF-DEC-DIGIT-CHARS-VALUE))
     (6 6 (:REWRITE NTH-WHEN-PREFIXP))
     (6 6 (:REWRITE DEFAULT-<-1))
     (2 2 (:REWRITE FOLD-CONSTS-IN-+)))
(SV::SVTV-PARSE-PATH-INDICES-STREQV-CONGRUENCE-ON-ORIG-X)
(SV::LEN-EQUAL-0 (12 12
                     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
                 (12 12
                     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
                 (12 12 (:LINEAR LEN-WHEN-PREFIXP))
                 (9 5 (:REWRITE DEFAULT-+-2))
                 (6 6 (:LINEAR INDEX-OF-<-LEN))
                 (5 5 (:REWRITE DEFAULT-+-1))
                 (4 4 (:REWRITE DEFAULT-CDR)))
(SV::SVTV-PARSE-PATH/SELECT-AUX
     (194 1 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (117 5 (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (102 5 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (76 1 (:REWRITE PREFIXP-OF-CONS-LEFT))
     (59 59
         (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (54 30 (:REWRITE DEFAULT-CDR))
     (44 22 (:REWRITE DEFAULT-+-2))
     (40 20 (:REWRITE STR::CONSP-OF-EXPLODE))
     (39 1 (:REWRITE PREFIXP-OF-CONS-RIGHT))
     (22 22 (:REWRITE DEFAULT-+-1))
     (16 10 (:REWRITE DEFAULT-CAR))
     (14 9
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (12 12
         (:TYPE-PRESCRIPTION TRUE-LISTP-SUBSEQ-TYPE-PRESCRIPTION))
     (11 6 (:REWRITE DEFAULT-<-2))
     (10 6 (:REWRITE DEFAULT-<-1))
     (10 2 (:REWRITE LISTPOS-WHEN-ATOM-RIGHT))
     (10 2 (:REWRITE LIST-EQUIV-OF-NIL-RIGHT))
     (9 2
        (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (6 6 (:TYPE-PRESCRIPTION PREFIXP))
     (6 6
        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (6 6
        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (6 6 (:LINEAR LEN-WHEN-PREFIXP))
     (5 5 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (5 5 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (5 5
        (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (5 5
        (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (5 1 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (4 4 (:REWRITE STR-FIX-WHEN-STRINGP))
     (4 4 (:REWRITE STR-FIX-DEFAULT))
     (4 4
        (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
     (3 3 (:LINEAR INDEX-OF-<-LEN))
     (2 2 (:REWRITE LISTPOS-WHEN-ATOM-LEFT))
     (2 2
        (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONG))
     (1 1 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (1 1 (:REWRITE SUBLISTP-COMPLETE))
     (1 1
        (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP)))
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH/SELECT-AUX.PATH
     (5238 27 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (3159 135
           (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (2754 135 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (2670 266 (:DEFINITION LEN))
     (2052 27 (:REWRITE PREFIXP-OF-CONS-LEFT))
     (1759 1759
           (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (1197 412 (:REWRITE DEFAULT-CDR))
     (1071 648 (:REWRITE STR::CONSP-OF-EXPLODE))
     (1053 27 (:REWRITE PREFIXP-OF-CONS-RIGHT))
     (1037 1037 (:TYPE-PRESCRIPTION LEN))
     (670 335 (:REWRITE DEFAULT-+-2))
     (538 371
          (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (514 352 (:REWRITE DEFAULT-CAR))
     (335 335 (:REWRITE DEFAULT-+-1))
     (310 62 (:REWRITE LISTPOS-WHEN-ATOM-RIGHT))
     (270 54 (:REWRITE LIST-EQUIV-OF-NIL-RIGHT))
     (243 54
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (162 162 (:TYPE-PRESCRIPTION PREFIXP))
     (162 162
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (162 162
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (162 162 (:LINEAR LEN-WHEN-PREFIXP))
     (152 152
          (:REWRITE SV::PATH-P-WHEN-MEMBER-EQUAL-OF-PATHLIST-P))
     (141 141 (:REWRITE STR-FIX-WHEN-STRINGP))
     (141 141 (:REWRITE STR-FIX-DEFAULT))
     (135 135 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (135 135 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (135 135
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (135 135
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (135 81 (:REWRITE DEFAULT-<-2))
     (135 27 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (108 108
          (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
     (108 81 (:REWRITE DEFAULT-<-1))
     (81 81 (:LINEAR INDEX-OF-<-LEN))
     (69 69 (:REWRITE NTH-WHEN-PREFIXP))
     (62 62 (:REWRITE LISTPOS-WHEN-ATOM-LEFT))
     (54 54
         (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONG))
     (27 27 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (27 27 (:REWRITE SUBLISTP-COMPLETE))
     (27 27
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT)))
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH/SELECT-AUX.RANGE-MSB
     (6402 33 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (3861 165
           (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (3366 165 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (3228 323 (:DEFINITION LEN))
     (2508 33 (:REWRITE PREFIXP-OF-CONS-LEFT))
     (2148 2148
           (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (1454 513 (:REWRITE DEFAULT-CDR))
     (1295 790 (:REWRITE STR::CONSP-OF-EXPLODE))
     (1287 33 (:REWRITE PREFIXP-OF-CONS-RIGHT))
     (1261 1261 (:TYPE-PRESCRIPTION LEN))
     (806 403 (:REWRITE DEFAULT-+-2))
     (639 441 (:REWRITE DEFAULT-CAR))
     (632 451
          (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (403 403 (:REWRITE DEFAULT-+-1))
     (390 78 (:REWRITE LISTPOS-WHEN-ATOM-RIGHT))
     (330 66 (:REWRITE LIST-EQUIV-OF-NIL-RIGHT))
     (297 66
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (294 98 (:REWRITE NATP-WHEN-GTE-0))
     (263 197 (:REWRITE DEFAULT-<-2))
     (230 197 (:REWRITE DEFAULT-<-1))
     (198 198 (:TYPE-PRESCRIPTION PREFIXP))
     (198 198
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (198 198
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (198 198 (:LINEAR LEN-WHEN-PREFIXP))
     (166 166 (:REWRITE STR-FIX-WHEN-STRINGP))
     (166 166 (:REWRITE STR-FIX-DEFAULT))
     (165 165 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (165 165 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (165 165
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (165 165
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (165 33 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (132 132
          (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
     (99 99 (:LINEAR INDEX-OF-<-LEN))
     (98 98 (:REWRITE NATP-WHEN-INTEGERP))
     (80 80 (:REWRITE NTH-WHEN-PREFIXP))
     (78 78 (:REWRITE LISTPOS-WHEN-ATOM-LEFT))
     (66 66
         (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONG))
     (33 33 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (33 33 (:REWRITE SUBLISTP-COMPLETE))
     (33 33
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT)))
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH/SELECT-AUX.RANGE-LSB
     (6402 33 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (3861 165
           (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (3366 165 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (3228 323 (:DEFINITION LEN))
     (2508 33 (:REWRITE PREFIXP-OF-CONS-LEFT))
     (2148 2148
           (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (1454 513 (:REWRITE DEFAULT-CDR))
     (1295 790 (:REWRITE STR::CONSP-OF-EXPLODE))
     (1287 33 (:REWRITE PREFIXP-OF-CONS-RIGHT))
     (1261 1261 (:TYPE-PRESCRIPTION LEN))
     (806 403 (:REWRITE DEFAULT-+-2))
     (639 441 (:REWRITE DEFAULT-CAR))
     (632 451
          (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (403 403 (:REWRITE DEFAULT-+-1))
     (390 78 (:REWRITE LISTPOS-WHEN-ATOM-RIGHT))
     (330 66 (:REWRITE LIST-EQUIV-OF-NIL-RIGHT))
     (297 66
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (294 98 (:REWRITE NATP-WHEN-GTE-0))
     (263 197 (:REWRITE DEFAULT-<-2))
     (230 197 (:REWRITE DEFAULT-<-1))
     (198 198 (:TYPE-PRESCRIPTION PREFIXP))
     (198 198
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (198 198
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (198 198 (:LINEAR LEN-WHEN-PREFIXP))
     (166 166 (:REWRITE STR-FIX-WHEN-STRINGP))
     (166 166 (:REWRITE STR-FIX-DEFAULT))
     (165 165 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (165 165 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (165 165
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (165 165
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (165 33 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (132 132
          (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
     (99 99 (:LINEAR INDEX-OF-<-LEN))
     (98 98 (:REWRITE NATP-WHEN-INTEGERP))
     (80 80 (:REWRITE NTH-WHEN-PREFIXP))
     (78 78 (:REWRITE LISTPOS-WHEN-ATOM-LEFT))
     (66 66
         (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONG))
     (33 33 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (33 33 (:REWRITE SUBLISTP-COMPLETE))
     (33 33
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT)))
(SV::SVTV-PARSE-PATH/SELECT-AUX
     (819 3 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (606 15
          (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (435 15 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (322 119 (:REWRITE DEFAULT-CDR))
     (304 4
          (:DEFINITION SV::SVTV-PARSE-PATH/SELECT-AUX))
     (216 3 (:REWRITE PREFIXP-OF-CONS-LEFT))
     (176 88 (:REWRITE DEFAULT-+-2))
     (126 102
          (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (114 3 (:REWRITE PREFIXP-OF-CONS-RIGHT))
     (88 88 (:REWRITE DEFAULT-+-1))
     (75 66 (:REWRITE DEFAULT-CAR))
     (46 12 (:REWRITE LISTPOS-WHEN-ATOM-RIGHT))
     (40 24
         (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
     (34 34
         (:TYPE-PRESCRIPTION TRUE-LISTP-SUBSEQ-TYPE-PRESCRIPTION))
     (30 6 (:REWRITE LIST-EQUIV-OF-NIL-RIGHT))
     (24 6
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (22 22
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (22 22
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (22 22 (:LINEAR LEN-WHEN-PREFIXP))
     (20 13 (:REWRITE DEFAULT-<-2))
     (18 18 (:TYPE-PRESCRIPTION PREFIXP))
     (18 13 (:REWRITE DEFAULT-<-1))
     (15 15 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (15 15 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (15 15
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (15 15
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (14 14 (:REWRITE NTH-WHEN-PREFIXP))
     (12 12 (:REWRITE LISTPOS-WHEN-ATOM-LEFT))
     (12 3 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (11 11 (:LINEAR INDEX-OF-<-LEN))
     (7 7 (:REWRITE STR-FIX-DEFAULT))
     (3 3 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (3 3 (:REWRITE SUBLISTP-COMPLETE))
     (3 3
        (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (2 2
        (:REWRITE SV::PATH-P-WHEN-MEMBER-EQUAL-OF-PATHLIST-P)))
(SV::SVTV-PARSE-PATH/SELECT-AUX-OF-STRING-LIST-FIX-DOTTED-PARTS
 (15372 126 (:REWRITE SUBLISTP-WHEN-PREFIXP))
 (8064 630
       (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
 (7812 630 (:REWRITE PREFIXP-WHEN-PREFIXP))
 (6174 126 (:REWRITE PREFIXP-OF-CONS-LEFT))
 (3976 3976
       (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
 (3484 3484 (:TYPE-PRESCRIPTION LEN))
 (2646 126 (:REWRITE PREFIXP-OF-CONS-RIGHT))
 (2074 626 (:REWRITE LISTPOS-WHEN-ATOM-RIGHT))
 (1637 591
       (:REWRITE STR::STRING-LIST-FIX-WHEN-STRING-LISTP))
 (1059 1059 (:REWRITE STR-FIX-WHEN-STRINGP))
 (1059 1059 (:REWRITE STR-FIX-DEFAULT))
 (1046 1046 (:TYPE-PRESCRIPTION STRING-LISTP))
 (1008 252
       (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
 (1000 980 (:REWRITE STR::CONSP-OF-EXPLODE))
 (756 756 (:TYPE-PRESCRIPTION PREFIXP))
 (756 756
      (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (756 756 (:LINEAR LEN-WHEN-PREFIXP))
 (756 252 (:REWRITE LIST-EQUIV-OF-NIL-RIGHT))
 (630 630 (:REWRITE PREFIXP-TRANSITIVE . 2))
 (630 630 (:REWRITE PREFIXP-TRANSITIVE . 1))
 (630 630
      (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
 (630 630
      (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
 (630 378 (:REWRITE DEFAULT-<-2))
 (626 626 (:REWRITE LISTPOS-WHEN-ATOM-LEFT))
 (504 504
      (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
 (504 378 (:REWRITE DEFAULT-<-1))
 (504 126 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
 (416 208 (:REWRITE DEFAULT-+-2))
 (378 378 (:LINEAR INDEX-OF-<-LEN))
 (252 252
      (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONG))
 (208 208 (:REWRITE NTH-WHEN-PREFIXP))
 (208 208 (:REWRITE DEFAULT-+-1))
 (126 126 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
 (126 126 (:REWRITE SUBLISTP-COMPLETE))
 (126 126
      (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
 (32
   16
   (:TYPE-PRESCRIPTION SV::RETURN-TYPE-OF-SVTV-PARSE-PATH-INDICES.RANGE-LSB))
 (20 20
     (:REWRITE-QUOTED-CONSTANT SV::NAME-FIX-UNDER-NAME-EQUIV)))
(SV::SVTV-PARSE-PATH/SELECT-AUX-STRING-LIST-EQUIV-CONGRUENCE-ON-DOTTED-PARTS)
(SV::SVTV-PARSE-PATH/SELECT-AUX-OF-STR-FIX-ORIG-X
     (3294 27 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (1728 135
           (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (1674 135 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (1323 27 (:REWRITE PREFIXP-OF-CONS-LEFT))
     (772 772
          (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (761 761 (:TYPE-PRESCRIPTION LEN))
     (567 27 (:REWRITE PREFIXP-OF-CONS-RIGHT))
     (268 62 (:REWRITE LISTPOS-WHEN-ATOM-RIGHT))
     (216 54
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (190 170 (:REWRITE STR::CONSP-OF-EXPLODE))
     (162 162 (:TYPE-PRESCRIPTION PREFIXP))
     (162 162
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (162 162 (:LINEAR LEN-WHEN-PREFIXP))
     (162 54 (:REWRITE LIST-EQUIV-OF-NIL-RIGHT))
     (159 159 (:REWRITE STR-FIX-DEFAULT))
     (135 135 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (135 135 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (135 135
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (135 135
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (135 81 (:REWRITE DEFAULT-<-2))
     (118 59 (:REWRITE DEFAULT-+-2))
     (108 108
          (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONGER))
     (108 81 (:REWRITE DEFAULT-<-1))
     (108 27 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (81 81 (:LINEAR INDEX-OF-<-LEN))
     (62 62 (:REWRITE LISTPOS-WHEN-ATOM-LEFT))
     (59 59 (:REWRITE NTH-WHEN-PREFIXP))
     (59 59 (:REWRITE DEFAULT-+-1))
     (54 54
         (:LINEAR STR::STRRPOS-UPPER-BOUND-STRONG))
     (27 27 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (27 27 (:REWRITE SUBLISTP-COMPLETE))
     (27 27
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT)))
(SV::SVTV-PARSE-PATH/SELECT-AUX-STREQV-CONGRUENCE-ON-ORIG-X)
(SV::SVTV-PARSE-PATH/SELECT)
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH/SELECT.PATH)
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH/SELECT.RANGE-MSB)
(SV::RETURN-TYPE-OF-SVTV-PARSE-PATH/SELECT.RANGE-LSB)
(SV::SVTV-PARSE-PATH/SELECT-OF-STR-FIX-X)
(SV::SVTV-PARSE-PATH/SELECT-STREQV-CONGRUENCE-ON-X)
(SV::SVTV-MOD-ALIAS-GUARD
     (33 30 (:REWRITE NFIX-WHEN-NOT-NATP))
     (26 26 (:REWRITE NTH-WHEN-PREFIXP))
     (23 23
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (23 23
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (19 16 (:REWRITE DEFAULT-<-2))
     (18 16 (:REWRITE DEFAULT-<-1))
     (15 4
         (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
     (14 7 (:REWRITE DEFAULT-+-2))
     (12 2
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (9 9 (:REWRITE DEFAULT-CDR))
     (9 1 (:DEFINITION SUBSETP-EQUAL))
     (8 1 (:DEFINITION TRUE-LISTP))
     (7 7 (:REWRITE DEFAULT-+-1))
     (5 5 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (4 4
        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (4 4
        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (4 4 (:LINEAR LEN-WHEN-PREFIXP))
     (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (3 3
        (:DEFINITION SV::MODDB-MOD-TOTALWIRES-IN-TERMS-OF-WIREOFFSET))
     (3 1 (:REWRITE NATP-WHEN-GTE-0))
     (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (2 2
        (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE SET::IN-SET))
     (2 2
        (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
     (2 2 (:REWRITE DEFAULT-CAR))
     (2 2
        (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
     (2 1 (:DEFINITION MEMBER-EQUAL))
     (1 1
        (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
     (1 1 (:REWRITE NATP-WHEN-INTEGERP))
     (1 1
        (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP))
     (1 1 (:LINEAR INDEX-OF-<-LEN)))
(SV::SVTV-MOD-ALIAS-GUARD-OF-NFIX-MODIDX
 (63 2 (:REWRITE SV::MODDB-FIX-WHEN-MODDBP))
 (60 1 (:DEFINITION SV::MODDBP))
 (39 15 (:REWRITE NFIX-WHEN-NOT-NATP))
 (23 10 (:REWRITE NATP-WHEN-GTE-0))
 (20 20 (:TYPE-PRESCRIPTION NATP))
 (18 12 (:REWRITE DEFAULT-<-1))
 (16 12 (:REWRITE DEFAULT-<-2))
 (15 3 (:DEFINITION LEN))
 (14 14 (:REWRITE NTH-WHEN-PREFIXP))
 (12 12
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (12 12
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (12 2
     (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (11 1 (:DEFINITION TRUE-LISTP))
 (10 10 (:REWRITE NATP-WHEN-INTEGERP))
 (6 6
    (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
 (6 3 (:REWRITE DEFAULT-+-2))
 (6 2
    (:DEFINITION SV::MODDB-MOD-TOTALWIRES-IN-TERMS-OF-WIREOFFSET))
 (6 1 (:DEFINITION LENGTH))
 (5 1
    (:REWRITE SV::MODDB->MODSP-IS-ELAB-MODLIST-P))
 (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
 (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (4 4
    (:TYPE-PRESCRIPTION SV::MODDB-MODS-OK))
 (4 4 (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
 (4 4 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
 (4 4 (:REWRITE DEFAULT-CDR))
 (4 4
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (4 4
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (4 4
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (4 4
    (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (4 4
    (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (4 4 (:LINEAR LISTPOS-COMPLETE))
 (4 4
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (4 4
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (4 4
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (4 4 (:LINEAR LEN-WHEN-PREFIXP))
 (4 4
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (4 4
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (4 4
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (4 1 (:DEFINITION SV::MODDB->NMODS1P))
 (3 3 (:REWRITE DEFAULT-+-1))
 (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (2 2 (:REWRITE SET::IN-SET))
 (2 2
    (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
 (2 2
    (:LINEAR SV::MODDB-MODNAME-GET-INDEX-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MOD-NMODS-BOUND))
 (2 2 (:LINEAR INDEX-OF-<-LEN))
 (1 1 (:TYPE-PRESCRIPTION SV::MODDBP))
 (1 1
    (:TYPE-PRESCRIPTION SV::ELAB-MODLIST-P))
 (1 1
    (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP)))
(SV::SVTV-MOD-ALIAS-GUARD-NAT-EQUIV-CONGRUENCE-ON-MODIDX)
(SV::SVTV-MOD-ALIAS-GUARD-OF-MODDB-FIX-MODDB)
(SV::SVTV-MOD-ALIAS-GUARD-MODDB-EQUIV-CONGRUENCE-ON-MODDB)
(SV::SVTV-MOD-ALIAS-GUARD-OF-LHSLIST-FIX-ALIASES
 (63 2 (:REWRITE SV::MODDB-FIX-WHEN-MODDBP))
 (60 1 (:DEFINITION SV::MODDBP))
 (40 14 (:REWRITE NFIX-WHEN-NOT-NATP))
 (27 12 (:REWRITE NATP-WHEN-GTE-0))
 (24 24 (:TYPE-PRESCRIPTION NATP))
 (19 13 (:REWRITE DEFAULT-<-1))
 (17 13 (:REWRITE DEFAULT-<-2))
 (15 3 (:DEFINITION LEN))
 (14 14 (:REWRITE NTH-WHEN-PREFIXP))
 (12 12
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (12 12
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (12 12 (:REWRITE NATP-WHEN-INTEGERP))
 (12 2
     (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (11 1 (:DEFINITION TRUE-LISTP))
 (6 6
    (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
 (6 3 (:REWRITE DEFAULT-+-2))
 (6 2
    (:DEFINITION SV::MODDB-MOD-TOTALWIRES-IN-TERMS-OF-WIREOFFSET))
 (6 1
    (:REWRITE SV::LHSLIST-FIX-WHEN-LHSLIST-P))
 (6 1 (:DEFINITION LENGTH))
 (5 1
    (:REWRITE SV::MODDB->MODSP-IS-ELAB-MODLIST-P))
 (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
 (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (4 4
    (:TYPE-PRESCRIPTION SV::MODDB-MODS-OK))
 (4 4 (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
 (4 4 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
 (4 4 (:REWRITE DEFAULT-CDR))
 (4 4
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (4 4
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (4 4
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (4 4
    (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (4 4
    (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (4 4 (:LINEAR LISTPOS-COMPLETE))
 (4 4
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (4 4
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (4 4
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (4 4 (:LINEAR LEN-WHEN-PREFIXP))
 (4 4
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (4 4
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (4 4
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (4 1 (:DEFINITION SV::MODDB->NMODS1P))
 (3 3 (:REWRITE DEFAULT-+-1))
 (2 2 (:TYPE-PRESCRIPTION SV::LHSLIST-P))
 (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (2 2
    (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
 (2 2 (:REWRITE SET::IN-SET))
 (2 2
    (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
 (2 2
    (:LINEAR SV::MODDB-MODNAME-GET-INDEX-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MOD-NMODS-BOUND))
 (2 2 (:LINEAR INDEX-OF-<-LEN))
 (1 1 (:TYPE-PRESCRIPTION SV::MODDBP))
 (1 1
    (:TYPE-PRESCRIPTION SV::ELAB-MODLIST-P))
 (1 1
    (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP))
 (1 1
    (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP)))
(SV::SVTV-MOD-ALIAS-GUARD-LHSLIST-EQUIV-CONGRUENCE-ON-ALIASES)
(SV::SVTV-1WIRE->LHS
 (548 216 (:REWRITE DEFAULT-+-2))
 (456 206 (:REWRITE DEFAULT-<-1))
 (337 23 (:REWRITE NATP-WHEN-GTE-0))
 (328 216 (:REWRITE DEFAULT-+-1))
 (324 206 (:REWRITE DEFAULT-<-2))
 (280 20
      (:LINEAR SV::MODDB-PATH->WIREIDX-BOUND))
 (192 32
      (:REWRITE SV::LHS-P-WHEN-MEMBER-EQUAL-OF-LHSLIST-P))
 (170 92 (:REWRITE DEFAULT-UNARY-MINUS))
 (170 34 (:DEFINITION LEN))
 (156 26
      (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (136 8 (:REWRITE SV::LHS-FIX-WHEN-LHS-P))
 (112 16 (:DEFINITION MEMBER-EQUAL))
 (104 13 (:DEFINITION TRUE-LISTP))
 (100 100 (:REWRITE FOLD-CONSTS-IN-+))
 (92 92 (:REWRITE NTH-WHEN-PREFIXP))
 (83 83
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (83 83
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (82 82
     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (82 82
     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (82 82 (:LINEAR LEN-WHEN-PREFIXP))
 (80 80 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
 (64 63 (:REWRITE NFIX-WHEN-NOT-NATP))
 (63 63 (:REWRITE DEFAULT-CDR))
 (52 52 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (52 26 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (41 41 (:LINEAR INDEX-OF-<-LEN))
 (26 26 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (26 26
     (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
 (26 26 (:REWRITE SET::IN-SET))
 (26 26
     (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
 (22 22
     (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
 (21 21
     (:DEFINITION SV::MODDB-MOD-TOTALWIRES-IN-TERMS-OF-WIREOFFSET))
 (16 16
     (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
 (16 16
     (:REWRITE SV::LHS-P-WHEN-SUBSETP-EQUAL))
 (16 16 (:REWRITE DEFAULT-CAR))
 (13 13
     (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP))
 (13 13
     (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
 (8 8 (:REWRITE SV::LHS-P-WHEN-NOT-CONSP))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (2 2 (:LINEAR LISTPOS-COMPLETE))
 (2 2
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (2 2
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (2 2
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (2 2
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (1 1
    (:LINEAR SV::MODDB-MODNAME-GET-INDEX-BOUND))
 (1 1
    (:LINEAR SV::MODDB-FIND-BAD-MOD-NMODS-BOUND)))
(SV::LHS-P-OF-SVTV-1WIRE->LHS.LHS
     (197 80 (:REWRITE DEFAULT-+-2))
     (122 80 (:REWRITE DEFAULT-+-1))
     (59 30 (:REWRITE DEFAULT-<-2))
     (51 30 (:REWRITE DEFAULT-<-1))
     (47 27 (:REWRITE DEFAULT-UNARY-MINUS))
     (35 35 (:REWRITE FOLD-CONSTS-IN-+))
     (18 18
         (:REWRITE SV::LHS-P-WHEN-SUBSETP-EQUAL))
     (18 18
         (:REWRITE SV::LHS-P-WHEN-MEMBER-EQUAL-OF-LHSLIST-P))
     (11 11 (:REWRITE STR-FIX-WHEN-STRINGP))
     (11 11 (:REWRITE STR-FIX-DEFAULT))
     (9 9 (:REWRITE SV::LHS-P-WHEN-NOT-CONSP))
     (7 7
        (:REWRITE-QUOTED-CONSTANT SV::LHS-FIX-UNDER-LHS-EQUIV))
     (7 7 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (1 1
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV)))
(SV::SVTV-1WIRE->LHS-OF-STR-FIX-X)
(SV::SVTV-1WIRE->LHS-STREQV-CONGRUENCE-ON-X)
(SV::SVTV-1WIRE->LHS-OF-NFIX-MODIDX
     (60 30 (:REWRITE DEFAULT-+-2))
     (46 30 (:REWRITE DEFAULT-+-1))
     (25 13 (:REWRITE DEFAULT-<-2))
     (13 13 (:REWRITE DEFAULT-<-1))
     (8 6 (:REWRITE DEFAULT-UNARY-MINUS))
     (7 1 (:REWRITE NFIX-WHEN-NATP))
     (6 6 (:REWRITE FOLD-CONSTS-IN-+))
     (5 1 (:REWRITE NFIX-WHEN-NOT-NATP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 2 (:REWRITE NATP-WHEN-GTE-0))
     (2 2
        (:REWRITE-QUOTED-CONSTANT SV::LHS-FIX-UNDER-LHS-EQUIV))
     (2 2 (:REWRITE STR-FIX-WHEN-STRINGP))
     (2 2 (:REWRITE STR-FIX-DEFAULT))
     (2 2 (:REWRITE NTH-WHEN-PREFIXP))
     (2 2 (:REWRITE NATP-WHEN-INTEGERP)))
(SV::SVTV-1WIRE->LHS-NAT-EQUIV-CONGRUENCE-ON-MODIDX)
(SV::SVTV-1WIRE->LHS-OF-MODDB-FIX-MODDB
     (62 31 (:REWRITE DEFAULT-+-2))
     (62 1 (:REWRITE SV::MODDB-FIX-WHEN-MODDBP))
     (60 1 (:DEFINITION SV::MODDBP))
     (47 31 (:REWRITE DEFAULT-+-1))
     (25 13 (:REWRITE DEFAULT-<-2))
     (13 13 (:REWRITE DEFAULT-<-1))
     (12 2
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (11 1 (:DEFINITION TRUE-LISTP))
     (8 6 (:REWRITE DEFAULT-UNARY-MINUS))
     (7 7 (:TYPE-PRESCRIPTION LEN))
     (6 6 (:REWRITE FOLD-CONSTS-IN-+))
     (6 1 (:DEFINITION LENGTH))
     (5 1
        (:REWRITE SV::MODDB->MODSP-IS-ELAB-MODLIST-P))
     (5 1 (:DEFINITION LEN))
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (4 4 (:REWRITE NTH-WHEN-PREFIXP))
     (4 4
        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (4 4
        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (4 4 (:LINEAR LEN-WHEN-PREFIXP))
     (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (4 1 (:DEFINITION SV::MODDB->NMODS1P))
     (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (2 2
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT SV::LHS-FIX-UNDER-LHS-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (2 2 (:REWRITE STR-FIX-WHEN-STRINGP))
     (2 2 (:REWRITE STR-FIX-DEFAULT))
     (2 2 (:REWRITE SET::IN-SET))
     (2 2
        (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE DEFAULT-CDR))
     (2 2 (:LINEAR INDEX-OF-<-LEN))
     (1 1 (:TYPE-PRESCRIPTION SV::MODDBP))
     (1 1
        (:TYPE-PRESCRIPTION SV::ELAB-MODLIST-P))
     (1 1
        (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
     (1 1
        (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS)))
(SV::SVTV-1WIRE->LHS-MODDB-EQUIV-CONGRUENCE-ON-MODDB)
(SV::SVTV-1WIRE->LHS-OF-LHSLIST-FIX-ALIASES
     (386 156 (:REWRITE DEFAULT-+-2))
     (240 156 (:REWRITE DEFAULT-+-1))
     (106 6 (:REWRITE DEFAULT-CDR))
     (106 6 (:REWRITE DEFAULT-CAR))
     (104 52 (:REWRITE DEFAULT-<-2))
     (94 54 (:REWRITE DEFAULT-UNARY-MINUS))
     (94 52 (:REWRITE DEFAULT-<-1))
     (68 68 (:REWRITE FOLD-CONSTS-IN-+))
     (54 9
         (:REWRITE SV::LHSLIST-FIX-WHEN-LHSLIST-P))
     (21 21 (:REWRITE NTH-WHEN-PREFIXP))
     (18 18 (:TYPE-PRESCRIPTION SV::LHSLIST-P))
     (18 18 (:REWRITE STR-FIX-WHEN-STRINGP))
     (18 18 (:REWRITE STR-FIX-DEFAULT))
     (18 18
         (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
     (14 14
         (:REWRITE-QUOTED-CONSTANT SV::LHS-FIX-UNDER-LHS-EQUIV))
     (9 9
        (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV)))
(SV::SVTV-1WIRE->LHS-LHSLIST-EQUIV-CONGRUENCE-ON-ALIASES)
(SV::SVTV-CONCAT->LHS
 (48 8
     (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (42 3
     (:LINEAR SV::MODDB-PATH->WIREIDX-BOUND))
 (32 4 (:DEFINITION TRUE-LISTP))
 (30 8
     (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
 (28 28 (:REWRITE NTH-WHEN-PREFIXP))
 (27 24 (:REWRITE NFIX-WHEN-NOT-NATP))
 (27 21 (:REWRITE DEFAULT-<-2))
 (27 21 (:REWRITE DEFAULT-<-1))
 (25 25
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (25 25
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (21 21 (:REWRITE DEFAULT-CDR))
 (20 10 (:REWRITE DEFAULT-+-2))
 (18 2 (:DEFINITION SUBSETP-EQUAL))
 (16 16 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (16 8 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (14 14
     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (14 14
     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (14 14 (:LINEAR LEN-WHEN-PREFIXP))
 (13 13 (:REWRITE DEFAULT-CAR))
 (12 4 (:REWRITE NATP-WHEN-GTE-0))
 (10 10 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
 (10 10 (:REWRITE DEFAULT-+-1))
 (8 8 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (8 8 (:REWRITE SET::IN-SET))
 (7 7 (:LINEAR INDEX-OF-<-LEN))
 (6 6
    (:DEFINITION SV::MODDB-MOD-TOTALWIRES-IN-TERMS-OF-WIREOFFSET))
 (5 5
    (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
 (4 4 (:REWRITE NATP-WHEN-INTEGERP))
 (4 4
    (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
 (4 4
    (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
 (4 2 (:DEFINITION MEMBER-EQUAL))
 (2 2
    (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
 (2 2
    (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (2 2 (:LINEAR LISTPOS-COMPLETE))
 (2 2
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (2 2
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (2 2
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (2 2
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (2 1
    (:TYPE-PRESCRIPTION TRUE-LISTP-APPEND))
 (1 1 (:TYPE-PRESCRIPTION BINARY-APPEND))
 (1 1
    (:LINEAR SV::MODDB-MODNAME-GET-INDEX-BOUND))
 (1 1
    (:LINEAR SV::MODDB-FIND-BAD-MOD-NMODS-BOUND)))
(SV::LHS-P-OF-SVTV-CONCAT->LHS.LHS
     (159 30
          (:REWRITE SV::LHS-P-WHEN-SUBSETP-EQUAL))
     (115 7 (:DEFINITION SUBSETP-EQUAL))
     (38 7 (:DEFINITION MEMBER-EQUAL))
     (35 35 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (30 30 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (30 30
         (:REWRITE SV::LHS-P-WHEN-MEMBER-EQUAL-OF-LHSLIST-P))
     (24 24 (:REWRITE DEFAULT-CAR))
     (23 18 (:REWRITE DEFAULT-CDR))
     (20 1 (:REWRITE LIST-FIX-WHEN-TRUE-LISTP))
     (19 1 (:REWRITE LIST-FIX-WHEN-LEN-ZERO))
     (13 13 (:REWRITE SV::LHS-P-WHEN-NOT-CONSP))
     (12 2
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (11 1 (:DEFINITION TRUE-LISTP))
     (7 7 (:TYPE-PRESCRIPTION LEN))
     (7 7
        (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (5 1 (:DEFINITION LEN))
     (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (4 1 (:DEFINITION BINARY-APPEND))
     (3 1 (:REWRITE CDR-OF-LIST-FIX))
     (3 1 (:REWRITE CAR-OF-APPEND))
     (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (2 2 (:REWRITE SET::IN-SET))
     (2 2 (:REWRITE CONSP-OF-APPEND))
     (2 2 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (2 2
        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (2 2
        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (2 2 (:LINEAR LEN-WHEN-PREFIXP))
     (2 1 (:REWRITE DEFAULT-+-2))
     (2 1 (:REWRITE CAR-OF-LIST-FIX))
     (1 1 (:REWRITE LIST-FIX-WHEN-NOT-CONSP))
     (1 1 (:REWRITE LIST-FIX-UNDER-LIST-EQUIV))
     (1 1 (:REWRITE DEFAULT-+-1))
     (1 1 (:REWRITE CONSP-OF-LIST-FIX))
     (1 1 (:REWRITE CDR-OF-APPEND-WHEN-CONSP))
     (1 1 (:LINEAR INDEX-OF-<-LEN)))
(SV::SVTV-CONCAT->LHS-OF-STRING-LIST-FIX-X
     (375 251 (:REWRITE DEFAULT-CDR))
     (339 29
          (:REWRITE STR::STRING-LIST-FIX-WHEN-STRING-LISTP))
     (269 235 (:REWRITE DEFAULT-CAR))
     (265 41 (:DEFINITION STRING-LISTP))
     (220 55 (:DEFINITION BINARY-APPEND))
     (165 165 (:TYPE-PRESCRIPTION STRING-LISTP))
     (110 110 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (12 6
         (:TYPE-PRESCRIPTION TRUE-LISTP-APPEND))
     (6 6 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (6 6 (:TYPE-PRESCRIPTION BINARY-APPEND)))
(SV::SVTV-CONCAT->LHS-STRING-LIST-EQUIV-CONGRUENCE-ON-X)
(SV::SVTV-CONCAT->LHS-OF-NFIX-MODIDX (35 5 (:REWRITE NFIX-WHEN-NATP))
                                     (25 5 (:REWRITE NFIX-WHEN-NOT-NATP))
                                     (20 20 (:TYPE-PRESCRIPTION NATP))
                                     (20 16 (:REWRITE DEFAULT-CAR))
                                     (20 10 (:REWRITE NATP-WHEN-GTE-0))
                                     (18 14 (:REWRITE DEFAULT-CDR))
                                     (16 4 (:DEFINITION BINARY-APPEND))
                                     (10 10 (:REWRITE NATP-WHEN-INTEGERP))
                                     (8 8 (:REWRITE APPEND-WHEN-NOT-CONSP))
                                     (5 5 (:REWRITE DEFAULT-<-2))
                                     (5 5 (:REWRITE DEFAULT-<-1)))
(SV::SVTV-CONCAT->LHS-NAT-EQUIV-CONGRUENCE-ON-MODIDX)
(SV::SVTV-CONCAT->LHS-OF-MODDB-FIX-MODDB
     (310 5 (:REWRITE SV::MODDB-FIX-WHEN-MODDBP))
     (300 5 (:DEFINITION SV::MODDBP))
     (60 10
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (55 5 (:DEFINITION TRUE-LISTP))
     (35 35 (:TYPE-PRESCRIPTION LEN))
     (30 5 (:DEFINITION LENGTH))
     (28 24 (:REWRITE DEFAULT-CDR))
     (25 5
         (:REWRITE SV::MODDB->MODSP-IS-ELAB-MODLIST-P))
     (25 5 (:DEFINITION LEN))
     (20 20 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (20 20 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (20 20
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (20 20
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (20 20 (:LINEAR LEN-WHEN-PREFIXP))
     (20 16 (:REWRITE DEFAULT-CAR))
     (20 10 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (20 5 (:DEFINITION SV::MODDB->NMODS1P))
     (16 4 (:DEFINITION BINARY-APPEND))
     (10 10 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (10 10
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (10 10
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (10 10 (:REWRITE NTH-WHEN-PREFIXP))
     (10 10 (:REWRITE SET::IN-SET))
     (10 10
         (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
     (10 10 (:LINEAR INDEX-OF-<-LEN))
     (10 5 (:REWRITE DEFAULT-+-2))
     (8 8 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION SV::MODDBP))
     (5 5
        (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
     (5 5 (:REWRITE DEFAULT-<-2))
     (5 5 (:REWRITE DEFAULT-<-1))
     (5 5 (:REWRITE DEFAULT-+-1))
     (5 5
        (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS)))
(SV::SVTV-CONCAT->LHS-MODDB-EQUIV-CONGRUENCE-ON-MODDB)
(SV::SVTV-CONCAT->LHS-OF-LHSLIST-FIX-ALIASES
     (30 5
         (:REWRITE SV::LHSLIST-FIX-WHEN-LHSLIST-P))
     (20 16 (:REWRITE DEFAULT-CAR))
     (18 14 (:REWRITE DEFAULT-CDR))
     (16 4 (:DEFINITION BINARY-APPEND))
     (10 10
         (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
     (8 8 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (5 5
        (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP)))
(SV::SVTV-CONCAT->LHS-LHSLIST-EQUIV-CONGRUENCE-ON-ALIASES)
(SV::SVTV-WIRE->LHS!
 (15 4
     (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
 (14 12 (:REWRITE NFIX-WHEN-NOT-NATP))
 (13 13 (:REWRITE NTH-WHEN-PREFIXP))
 (12 2
     (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (11 11
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (11 11
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (10 8 (:REWRITE DEFAULT-<-2))
 (10 8 (:REWRITE DEFAULT-<-1))
 (9 1 (:DEFINITION SUBSETP-EQUAL))
 (8 4 (:REWRITE DEFAULT-+-2))
 (8 1 (:DEFINITION TRUE-LISTP))
 (6 6 (:REWRITE DEFAULT-CDR))
 (5 5 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
 (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (4 4 (:REWRITE DEFAULT-+-1))
 (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (3 1 (:REWRITE NATP-WHEN-GTE-0))
 (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (2 2
    (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
 (2 2 (:REWRITE SET::IN-SET))
 (2 2
    (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
 (2 2 (:REWRITE DEFAULT-CAR))
 (2 2
    (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (2 2
    (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (2 2
    (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (2 2 (:LINEAR LISTPOS-COMPLETE))
 (2 2
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (2 2
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (2 2
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (2 2 (:LINEAR LEN-WHEN-PREFIXP))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (2 2
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (2 2
    (:DEFINITION SV::MODDB-MOD-TOTALWIRES-IN-TERMS-OF-WIREOFFSET))
 (2 1 (:DEFINITION MEMBER-EQUAL))
 (1 1
    (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
 (1 1 (:REWRITE NATP-WHEN-INTEGERP))
 (1 1
    (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP))
 (1 1
    (:LINEAR SV::MODDB-MODNAME-GET-INDEX-BOUND))
 (1 1
    (:LINEAR SV::MODDB-FIND-BAD-MOD-NMODS-BOUND))
 (1 1 (:LINEAR INDEX-OF-<-LEN)))
(SV::LHS-P-OF-SVTV-WIRE->LHS!.LHS
     (3 1
        (:REWRITE SV::LHS-NORM-WHEN-LHS-NORMP))
     (2 2 (:TYPE-PRESCRIPTION SV::LHS-NORMP))
     (2 2
        (:REWRITE SV::LHS-P-WHEN-MEMBER-EQUAL-OF-LHSLIST-P))
     (1 1
        (:REWRITE SV::LHS-NORM-WHEN-NOT-CONSP)))
(SV::SVTV-WIRE->LHS!-OF-STR-FIX-X)
(SV::SVTV-WIRE->LHS!-STREQV-CONGRUENCE-ON-X)
(SV::SVTV-WIRE->LHS!-OF-NFIX-MODIDX)
(SV::SVTV-WIRE->LHS!-NAT-EQUIV-CONGRUENCE-ON-MODIDX)
(SV::SVTV-WIRE->LHS!-OF-MODDB-FIX-MODDB)
(SV::SVTV-WIRE->LHS!-MODDB-EQUIV-CONGRUENCE-ON-MODDB)
(SV::SVTV-WIRE->LHS!-OF-LHSLIST-FIX-ALIASES)
(SV::SVTV-WIRE->LHS!-LHSLIST-EQUIV-CONGRUENCE-ON-ALIASES)
(SV::SVTV-WIRE->LHS)
(SV::LHS-P-OF-SVTV-WIRE->LHS.LHS
     (2 2
        (:REWRITE SV::LHS-P-WHEN-SUBSETP-EQUAL))
     (2 2
        (:REWRITE SV::LHS-P-WHEN-MEMBER-EQUAL-OF-LHSLIST-P))
     (1 1 (:REWRITE SV::LHS-P-WHEN-NOT-CONSP)))
(SV::SVTV-WIRE->LHS-OF-NFIX-MODIDX (7 1 (:REWRITE NFIX-WHEN-NATP))
                                   (5 1 (:REWRITE NFIX-WHEN-NOT-NATP))
                                   (4 4 (:TYPE-PRESCRIPTION NATP))
                                   (4 2 (:REWRITE NATP-WHEN-GTE-0))
                                   (2 2 (:REWRITE NATP-WHEN-INTEGERP))
                                   (1 1 (:REWRITE DEFAULT-<-2))
                                   (1 1 (:REWRITE DEFAULT-<-1)))
(SV::SVTV-WIRE->LHS-NAT-EQUIV-CONGRUENCE-ON-MODIDX)
(SV::SVTV-WIRE->LHS-OF-MODDB-FIX-MODDB
     (62 1 (:REWRITE SV::MODDB-FIX-WHEN-MODDBP))
     (60 1 (:DEFINITION SV::MODDBP))
     (12 2
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (11 1 (:DEFINITION TRUE-LISTP))
     (7 7 (:TYPE-PRESCRIPTION LEN))
     (6 1 (:DEFINITION LENGTH))
     (5 1
        (:REWRITE SV::MODDB->MODSP-IS-ELAB-MODLIST-P))
     (5 1 (:DEFINITION LEN))
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (4 4
        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (4 4
        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (4 4 (:LINEAR LEN-WHEN-PREFIXP))
     (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (4 1 (:DEFINITION SV::MODDB->NMODS1P))
     (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (2 2
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (2 2 (:REWRITE NTH-WHEN-PREFIXP))
     (2 2 (:REWRITE SET::IN-SET))
     (2 2
        (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE DEFAULT-CDR))
     (2 2 (:LINEAR INDEX-OF-<-LEN))
     (2 1 (:REWRITE DEFAULT-+-2))
     (1 1 (:TYPE-PRESCRIPTION SV::MODDBP))
     (1 1
        (:TYPE-PRESCRIPTION SV::ELAB-MODLIST-P))
     (1 1
        (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1 (:REWRITE DEFAULT-+-1))
     (1 1
        (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS)))
(SV::SVTV-WIRE->LHS-MODDB-EQUIV-CONGRUENCE-ON-MODDB)
(SV::SVTV-WIRE->LHS-OF-LHSLIST-FIX-ALIASES
     (6 1
        (:REWRITE SV::LHSLIST-FIX-WHEN-LHSLIST-P))
     (2 2 (:TYPE-PRESCRIPTION SV::LHSLIST-P))
     (2 2
        (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
     (1 1
        (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP)))
(SV::SVTV-WIRE->LHS-LHSLIST-EQUIV-CONGRUENCE-ON-ALIASES)
(SV::MSG-LIST)
(SV::SVTV-WIRES->LHSES
 (103 18
      (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (68 10 (:DEFINITION TRUE-LISTP))
 (42 3
     (:LINEAR SV::MODDB-PATH->WIREIDX-BOUND))
 (34 34 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (34 17 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (33 33 (:REWRITE NTH-WHEN-PREFIXP))
 (32 32 (:REWRITE DEFAULT-CDR))
 (32 10
     (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
 (30 23 (:REWRITE DEFAULT-<-2))
 (30 23 (:REWRITE DEFAULT-<-1))
 (29 29
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
 (29 29
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
 (29 25 (:REWRITE NFIX-WHEN-NOT-NATP))
 (26 6
     (:DEFINITION SV::MODDB-MOD-TOTALWIRES-IN-TERMS-OF-WIREOFFSET))
 (22 11 (:REWRITE DEFAULT-+-2))
 (20 20 (:REWRITE DEFAULT-CAR))
 (20 1
     (:REWRITE SV::MODDB-MOD-INST-WIREOFFSET-GREATER-NORM))
 (18 2 (:DEFINITION SUBSETP-EQUAL))
 (17 17 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (17 17 (:REWRITE SET::IN-SET))
 (16 16
     (:REWRITE TRUE-LIST-LISTP-WHEN-NOT-CONSP))
 (14 14
     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (14 14
     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (14 14 (:LINEAR LEN-WHEN-PREFIXP))
 (12 4 (:REWRITE NATP-WHEN-GTE-0))
 (11 11 (:REWRITE DEFAULT-+-1))
 (10 10 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
 (7 7 (:LINEAR INDEX-OF-<-LEN))
 (6 6
    (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
 (5 5
    (:TYPE-PRESCRIPTION SV::NATP-OF-MODDB-MOD-NINSTS))
 (5 5
    (:TYPE-PRESCRIPTION SV::ELAB-MOD$A-NINSTS))
 (5 5
    (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
 (5 5
    (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS))
 (5 1
    (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
 (4 4 (:REWRITE NATP-WHEN-INTEGERP))
 (4 2 (:DEFINITION MEMBER-EQUAL))
 (3 3
    (:TYPE-PRESCRIPTION BINARY-APPEND-WITHOUT-GUARD))
 (3 3
    (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP))
 (2 2
    (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
 (2 2
    (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (2 2 (:LINEAR LISTPOS-COMPLETE))
 (2 2
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (2 2
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (2 2
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (2 2
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (1 1
    (:LINEAR SV::MODDB-MODNAME-GET-INDEX-BOUND))
 (1 1
    (:LINEAR SV::MODDB-FIND-BAD-MOD-NMODS-BOUND)))
(SV::SVTV-LINES-P-OF-SVTV-WIRES->LHSES.IN-ENTRIES
     (160 8 (:REWRITE LIST-FIX-WHEN-TRUE-LISTP))
     (152 8 (:REWRITE LIST-FIX-WHEN-LEN-ZERO))
     (96 16
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (88 8 (:DEFINITION TRUE-LISTP))
     (72 8
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-LIST-FIX))
     (46 24
         (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (40 40 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (40 8
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (40 8 (:DEFINITION LEN))
     (32 32 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (32 16 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (28 28 (:REWRITE DEFAULT-CDR))
     (22 22 (:REWRITE DEFAULT-CAR))
     (16 16 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (16 16 (:REWRITE SET::IN-SET))
     (16 16
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (16 16
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (16 16 (:LINEAR LEN-WHEN-PREFIXP))
     (16 8 (:REWRITE DEFAULT-+-2))
     (15 15
         (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
     (8 8 (:REWRITE LIST-FIX-WHEN-NOT-CONSP))
     (8 8 (:REWRITE DEFAULT-+-1))
     (8 8 (:REWRITE CONSP-OF-LIST-FIX))
     (8 8 (:LINEAR INDEX-OF-<-LEN))
     (8 2 (:DEFINITION BINARY-APPEND))
     (4 4 (:REWRITE APPEND-WHEN-NOT-CONSP)))
(SV::SVTV-WIRES->LHSES-OF-TRUE-LIST-LIST-FIX-ENTRIES
     (856 24 (:DEFINITION TRUE-LIST-LISTP))
     (660 52 (:DEFINITION TRUE-LISTP))
     (624 104
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (590 11
          (:REWRITE TRUE-LIST-LIST-FIX-WHEN-TRUE-LIST-LISTP))
     (568 12
          (:REWRITE SV::SVTV-ENTRYLIST-P-OF-LIST-FIX))
     (506 18 (:REWRITE LIST-FIX-WHEN-LEN-ZERO))
     (496 12
          (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (374 30
          (:REWRITE TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
     (214 214 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (210 176 (:REWRITE DEFAULT-CDR))
     (200 200 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (200 100 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (164 140 (:REWRITE DEFAULT-CAR))
     (160 28 (:DEFINITION LEN))
     (156 32
          (:REWRITE TRUE-LIST-LISTP-OF-CDR-WHEN-TRUE-LIST-LISTP))
     (148 8 (:LINEAR SV::SUM-OF-LENGTHS-OF-CDR))
     (100 100
          (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (100 100 (:REWRITE SET::IN-SET))
     (100 36
          (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (76 38 (:REWRITE DEFAULT-+-2))
     (64 16 (:DEFINITION BINARY-APPEND))
     (50 49
         (:REWRITE TRUE-LIST-LISTP-WHEN-NOT-CONSP))
     (46 38 (:REWRITE DEFAULT-+-1))
     (32 32
         (:TYPE-PRESCRIPTION SV::NATP-OF-SUM-OF-LENGTHS))
     (32 32 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (32 32
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (32 32
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (32 32 (:LINEAR LEN-WHEN-PREFIXP))
     (30 18 (:REWRITE LIST-FIX-WHEN-NOT-CONSP))
     (20 12 (:REWRITE CONSP-OF-LIST-FIX))
     (16 16 (:LINEAR INDEX-OF-<-LEN))
     (16 8 (:REWRITE DEFAULT-UNARY-MINUS))
     (12 12
         (:REWRITE CONSP-OF-TRUE-LIST-LIST-FIX))
     (8 4
        (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-UNDER-LIST-EQUIV)))
(SV::SVTV-WIRES->LHSES-TRUE-LIST-LIST-EQUIV-CONGRUENCE-ON-ENTRIES)
(SV::SVTV-WIRES->LHSES-OF-NFIX-MODIDX
     (200 10 (:REWRITE LIST-FIX-WHEN-TRUE-LISTP))
     (190 10 (:REWRITE LIST-FIX-WHEN-LEN-ZERO))
     (120 20
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (110 10 (:DEFINITION TRUE-LISTP))
     (90 10
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-LIST-FIX))
     (64 56 (:REWRITE DEFAULT-CAR))
     (62 54 (:REWRITE DEFAULT-CDR))
     (56 30
         (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (50 50 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (50 10
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (50 10 (:DEFINITION LEN))
     (48 12 (:DEFINITION BINARY-APPEND))
     (40 40 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (40 20 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (35 5 (:REWRITE NFIX-WHEN-NATP))
     (25 5 (:REWRITE NFIX-WHEN-NOT-NATP))
     (24 24 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (20 20 (:TYPE-PRESCRIPTION NATP))
     (20 20 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (20 20 (:REWRITE SET::IN-SET))
     (20 20
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (20 20
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (20 20 (:LINEAR LEN-WHEN-PREFIXP))
     (20 10 (:REWRITE NATP-WHEN-GTE-0))
     (20 10 (:REWRITE DEFAULT-+-2))
     (10 10 (:REWRITE NATP-WHEN-INTEGERP))
     (10 10 (:REWRITE LIST-FIX-WHEN-NOT-CONSP))
     (10 10 (:REWRITE DEFAULT-+-1))
     (10 10 (:REWRITE CONSP-OF-LIST-FIX))
     (10 10 (:LINEAR INDEX-OF-<-LEN))
     (5 5 (:REWRITE DEFAULT-<-2))
     (5 5 (:REWRITE DEFAULT-<-1)))
(SV::SVTV-WIRES->LHSES-NAT-EQUIV-CONGRUENCE-ON-MODIDX)
(SV::SVTV-WIRES->LHSES-OF-MODDB-FIX-MODDB
     (310 5 (:REWRITE SV::MODDB-FIX-WHEN-MODDBP))
     (300 5 (:DEFINITION SV::MODDBP))
     (200 10 (:REWRITE LIST-FIX-WHEN-TRUE-LISTP))
     (190 10 (:REWRITE LIST-FIX-WHEN-LEN-ZERO))
     (180 30
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (165 15 (:DEFINITION TRUE-LISTP))
     (90 10
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-LIST-FIX))
     (75 15 (:DEFINITION LEN))
     (72 64 (:REWRITE DEFAULT-CDR))
     (70 70 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (64 56 (:REWRITE DEFAULT-CAR))
     (60 60 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (60 30 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (56 30
         (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (50 10
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (48 12 (:DEFINITION BINARY-APPEND))
     (40 40
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (40 40
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (40 40 (:LINEAR LEN-WHEN-PREFIXP))
     (30 30 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (30 30 (:REWRITE SET::IN-SET))
     (30 15 (:REWRITE DEFAULT-+-2))
     (30 5 (:DEFINITION LENGTH))
     (25 5
         (:REWRITE SV::MODDB->MODSP-IS-ELAB-MODLIST-P))
     (24 24 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (20 20 (:LINEAR INDEX-OF-<-LEN))
     (20 5 (:DEFINITION SV::MODDB->NMODS1P))
     (15 15 (:REWRITE DEFAULT-+-1))
     (10 10
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (10 10
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (10 10 (:REWRITE NTH-WHEN-PREFIXP))
     (10 10 (:REWRITE LIST-FIX-WHEN-NOT-CONSP))
     (10 10
         (:REWRITE SV::ELAB-MODLIST-P-WHEN-SUBSETP-EQUAL))
     (10 10 (:REWRITE CONSP-OF-LIST-FIX))
     (5 5 (:TYPE-PRESCRIPTION SV::MODDBP))
     (5 5
        (:REWRITE SV::ELAB-MODLIST-P-WHEN-NOT-CONSP))
     (5 5 (:REWRITE DEFAULT-<-2))
     (5 5 (:REWRITE DEFAULT-<-1))
     (5 5
        (:LINEAR SV::MODSCOPE-OKP-IMPLIES-TOP-MODIDX-IN-BOUNDS)))
(SV::SVTV-WIRES->LHSES-MODDB-EQUIV-CONGRUENCE-ON-MODDB)
(SV::SVTV-WIRES->LHSES-OF-LHSLIST-FIX-ALIASES
     (200 10 (:REWRITE LIST-FIX-WHEN-TRUE-LISTP))
     (190 10 (:REWRITE LIST-FIX-WHEN-LEN-ZERO))
     (120 20
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (110 10 (:DEFINITION TRUE-LISTP))
     (90 10
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-LIST-FIX))
     (64 56 (:REWRITE DEFAULT-CAR))
     (62 54 (:REWRITE DEFAULT-CDR))
     (56 30
         (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (50 50 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (50 10
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (50 10 (:DEFINITION LEN))
     (48 12 (:DEFINITION BINARY-APPEND))
     (40 40 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (40 20 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (30 5
         (:REWRITE SV::LHSLIST-FIX-WHEN-LHSLIST-P))
     (24 24 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (20 20 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (20 20 (:REWRITE SET::IN-SET))
     (20 20
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (20 20
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (20 20 (:LINEAR LEN-WHEN-PREFIXP))
     (20 10 (:REWRITE DEFAULT-+-2))
     (10 10 (:REWRITE LIST-FIX-WHEN-NOT-CONSP))
     (10 10
         (:REWRITE SV::LHSLIST-P-WHEN-SUBSETP-EQUAL))
     (10 10 (:REWRITE DEFAULT-+-1))
     (10 10 (:REWRITE CONSP-OF-LIST-FIX))
     (10 10 (:LINEAR INDEX-OF-<-LEN))
     (5 5
        (:REWRITE SV::LHSLIST-P-WHEN-NOT-CONSP)))
(SV::SVTV-WIRES->LHSES-LHSLIST-EQUIV-CONGRUENCE-ON-ALIASES)
(SV::SVTV-MAX-LENGTH (21 1 (:DEFINITION SV::SVTV-MAX-LENGTH))
                     (14 2 (:DEFINITION LEN))
                     (11 1 (:DEFINITION MAX))
                     (5 5 (:REWRITE DEFAULT-CDR))
                     (4 2 (:REWRITE DEFAULT-+-2))
                     (3 3
                        (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
                     (3 3 (:REWRITE DEFAULT-CAR))
                     (2 2 (:REWRITE DEFAULT-+-1))
                     (2 1 (:REWRITE DEFAULT-<-2))
                     (2 1 (:REWRITE DEFAULT-<-1)))
(SV::NATP-OF-SVTV-MAX-LENGTH)
(SV::SVTV-MAX-LENGTH-OF-SVTV-LINES-FIX-X
     (49 7 (:DEFINITION LEN))
     (32 6
         (:REWRITE SV::SVTV-LINES-FIX-WHEN-SVTV-LINES-P))
     (25 15 (:REWRITE DEFAULT-CDR))
     (21 3
         (:REWRITE SV::SVTV-LINE-FIX-WHEN-SVTV-LINE-P))
     (14 14
         (:TYPE-PRESCRIPTION SV::SVTV-LINE->ENTRIES$INLINE))
     (14 7 (:REWRITE DEFAULT-<-2))
     (14 7 (:REWRITE DEFAULT-<-1))
     (14 7 (:REWRITE DEFAULT-+-2))
     (12 11
         (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
     (12 3
         (:REWRITE SV::SVTV-LINE-P-OF-CAR-WHEN-SVTV-LINES-P))
     (11 10 (:REWRITE DEFAULT-CAR))
     (8 2
        (:REWRITE SV::SVTV-LINES-P-OF-CDR-WHEN-SVTV-LINES-P))
     (7 7 (:REWRITE DEFAULT-+-1))
     (6 6 (:TYPE-PRESCRIPTION SV::SVTV-LINE-P))
     (6 6
        (:REWRITE SV::CONSP-OF-SVTV-LINES-FIX))
     (6 3
        (:REWRITE SV::CAR-OF-SVTV-LINES-FIX-X-UNDER-SVTV-LINE-EQUIV)))
(SV::SVTV-MAX-LENGTH-SVTV-LINES-EQUIV-CONGRUENCE-ON-X)
(SV::SVTV-ENTRY-P-WHEN-4VEC-P)
(SV::SVTV-EXTEND-ENTRYLIST
     (438 96
          (:REWRITE SV::4VEC-P-WHEN-MAYBE-4VEC-P))
     (228 66
          (:REWRITE SV::MAYBE-4VEC-P-WHEN-4VEC-P))
     (192 192
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (153 18
          (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
     (150 150
          (:TYPE-PRESCRIPTION SV::MAYBE-4VEC-P))
     (108 9 (:DEFINITION SYMBOL-LISTP))
     (88 23
         (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (62 11 (:REWRITE DEFAULT-SYMBOL-NAME))
     (38 38 (:REWRITE DEFAULT-<-2))
     (38 38 (:REWRITE DEFAULT-<-1))
     (36 36 (:REWRITE DEFAULT-CAR))
     (26 26
         (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (18 18
         (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
     (18 18 (:REWRITE NATP-WHEN-INTEGERP))
     (18 18 (:REWRITE FN-CHECK-DEF-FORMALS))
     (18 9
         (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
     (16 16 (:REWRITE NFIX-WHEN-NOT-NATP))
     (14 14 (:REWRITE DEFAULT-CDR))
     (13 13
         (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (10 10 (:REWRITE DEFAULT-+-2))
     (10 10 (:REWRITE DEFAULT-+-1))
     (4 2 (:REWRITE ZP-WHEN-GT-0)))
(SV::SVTV-ENTRYLIST-P-OF-SVTV-EXTEND-ENTRYLIST
     (3379 243
           (:REWRITE SV::SVTV-ENTRY-FIX-OF-SVTV-ENTRY-P))
     (614 614
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (606 606
          (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-FIX))
     (494 185
          (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (420 70
          (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (406 406
          (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-P))
     (280 70
          (:REWRITE SV::SVTV-ENTRY-P-OF-CAR-WHEN-SVTV-ENTRYLIST-P))
     (196 28 (:REWRITE NFIX-WHEN-NATP))
     (140 140
          (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (140 28 (:REWRITE NFIX-WHEN-NOT-NATP))
     (138 46 (:REWRITE ZP-WHEN-GT-0))
     (112 112 (:TYPE-PRESCRIPTION NATP))
     (112 56 (:REWRITE NATP-WHEN-GTE-0))
     (83 83 (:REWRITE DEFAULT-CAR))
     (81 39 (:REWRITE DEFAULT-SYMBOL-NAME))
     (74 74 (:REWRITE DEFAULT-<-2))
     (74 74 (:REWRITE DEFAULT-<-1))
     (70 70
         (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (56 56 (:REWRITE NATP-WHEN-INTEGERP))
     (55 55 (:REWRITE DEFAULT-+-2))
     (55 55 (:REWRITE DEFAULT-+-1))
     (46 46 (:REWRITE ZP-WHEN-INTEGERP))
     (46 46 (:REWRITE ZP-OPEN))
     (3 3
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
     (3 3
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
     (3 3
        (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::LEN-OF-SVTV-EXTEND-ENTRYLIST
 (2711 247
       (:REWRITE SV::SVTV-ENTRY-FIX-OF-SVTV-ENTRY-P))
 (1912 195
       (:REWRITE SV::SVTV-ENTRY-P-WHEN-4VEC-P))
 (486 486
      (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
 (340 340
      (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-P))
 (276 37
      (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
 (247 63 (:REWRITE NFIX-WHEN-NOT-NATP))
 (231 231
      (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-FIX))
 (184 184 (:TYPE-PRESCRIPTION NATP))
 (184 92 (:REWRITE NATP-WHEN-GTE-0))
 (184 37
      (:REWRITE SV::SVTV-ENTRY-P-OF-CAR-WHEN-SVTV-ENTRYLIST-P))
 (177 136 (:REWRITE DEFAULT-+-2))
 (162 35 (:REWRITE ZP-WHEN-INTEGERP))
 (136 136 (:REWRITE DEFAULT-+-1))
 (120 114 (:REWRITE DEFAULT-<-2))
 (114 114 (:REWRITE DEFAULT-<-1))
 (92 92 (:REWRITE NATP-WHEN-INTEGERP))
 (92 92
     (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
 (80 2 (:REWRITE NFIX-EQUAL-TO-NONZERO))
 (62 62
     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (62 62
     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (62 62 (:LINEAR LEN-WHEN-PREFIXP))
 (56 50 (:REWRITE DEFAULT-SYMBOL-NAME))
 (54 9
     (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
 (46 46
     (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
 (46 46
     (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
 (43 43 (:REWRITE DEFAULT-CAR))
 (36 9
     (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
 (31 31 (:LINEAR INDEX-OF-<-LEN))
 (28 28
     (:REWRITE SV::SVTV-ENTRY-P-OF-SVTV-ENTRY-FIX))
 (22 22
     (:REWRITE SV::4VEC-P-OF-4VEC-ZERO-EXT))
 (5 5
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (5 5
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (5 5
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (5 5 (:LINEAR LISTPOS-COMPLETE))
 (5 5
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (5 5
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (5 5
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (5 5
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (5 5
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (5 5
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (4 4 (:REWRITE ZP-OPEN))
 (2 2
    (:REWRITE NFIX-EQUAL-TO-NONZERO-CONST))
 (1 1
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
 (1 1
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
 (1 1
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::SVTV-EXTEND-ENTRYLIST-OF-SVTV-ENTRYLIST-FIX-X
     (830 830
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (804 102
          (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (536 102
          (:REWRITE SV::SVTV-ENTRY-P-OF-CAR-WHEN-SVTV-ENTRYLIST-P))
     (521 89 (:REWRITE NFIX-WHEN-NATP))
     (377 89 (:REWRITE NFIX-WHEN-NOT-NATP))
     (288 288 (:TYPE-PRESCRIPTION NATP))
     (288 144 (:REWRITE NATP-WHEN-GTE-0))
     (285 285
          (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-FIX))
     (268 268
          (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (200 33
          (:REWRITE SV::SVTV-ENTRYLIST-FIX-WHEN-SVTV-ENTRYLIST-P))
     (196 52
          (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (192 32
          (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
     (189 181
          (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (177 51 (:REWRITE ZP-WHEN-INTEGERP))
     (165 165 (:REWRITE DEFAULT-<-2))
     (165 165 (:REWRITE DEFAULT-<-1))
     (159 146 (:REWRITE DEFAULT-CAR))
     (153 51 (:REWRITE ZP-WHEN-GT-0))
     (144 144 (:REWRITE NATP-WHEN-INTEGERP))
     (134 134
          (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (126 42 (:REWRITE FOLD-CONSTS-IN-+))
     (123 123 (:REWRITE DEFAULT-+-2))
     (123 123 (:REWRITE DEFAULT-+-1))
     (88 85 (:REWRITE DEFAULT-SYMBOL-NAME))
     (44 44
         (:REWRITE SV::4VEC-P-OF-4VEC-ZERO-EXT))
     (14 14
         (:REWRITE SV::CONSP-OF-SVTV-ENTRYLIST-FIX))
     (14 7
         (:REWRITE SV::CAR-OF-SVTV-ENTRYLIST-FIX-X-UNDER-SVTV-ENTRY-EQUIV))
     (9 9 (:REWRITE ZP-OPEN))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::SVTV-EXTEND-ENTRYLIST-SVTV-ENTRYLIST-EQUIV-CONGRUENCE-ON-X)
(SV::SVTV-EXTEND-ENTRYLIST-OF-NFIX-LEN
 (1338 82
       (:REWRITE SV::SVTV-ENTRY-FIX-OF-SVTV-ENTRY-P))
 (972 78
      (:REWRITE SV::SVTV-ENTRY-P-WHEN-4VEC-P))
 (621 125
      (:REWRITE SV::4VEC-P-WHEN-MAYBE-4VEC-P))
 (317 101
      (:REWRITE SV::MAYBE-4VEC-P-WHEN-4VEC-P))
 (250 250
      (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
 (225 225
      (:TYPE-PRESCRIPTION SV::MAYBE-4VEC-P))
 (192 30
      (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
 (156 156
      (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-P))
 (128 30
      (:REWRITE SV::SVTV-ENTRY-P-OF-CAR-WHEN-SVTV-ENTRYLIST-P))
 (76 76
     (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-FIX))
 (74 16 (:REWRITE ZP-WHEN-GT-0))
 (64 64
     (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
 (62 14 (:REWRITE NFIX-WHEN-NOT-NATP))
 (48 48 (:TYPE-PRESCRIPTION NATP))
 (48 24 (:REWRITE NATP-WHEN-GTE-0))
 (46 16 (:REWRITE ZP-WHEN-INTEGERP))
 (32 32
     (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
 (32 32
     (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
 (32 4 (:REWRITE NFIX-POSITIVE-TO-NON-ZP))
 (30 30 (:REWRITE DEFAULT-CAR))
 (24 24 (:REWRITE NATP-WHEN-INTEGERP))
 (22 22 (:REWRITE DEFAULT-<-2))
 (22 22 (:REWRITE DEFAULT-<-1))
 (14 14 (:REWRITE DEFAULT-SYMBOL-NAME))
 (12 12 (:TYPE-PRESCRIPTION NFIX))
 (12 12 (:REWRITE ZP-OPEN))
 (12 10 (:REWRITE DEFAULT-+-2))
 (12 2
     (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
 (10 10 (:REWRITE DEFAULT-CDR))
 (10 10 (:REWRITE DEFAULT-+-1))
 (8 2
    (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
 (6 2 (:REWRITE FOLD-CONSTS-IN-+))
 (4 4 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-ORDER-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MODINST-BOUND))
 (2 2
    (:LINEAR SV::MODDB-FIND-BAD-MOD-BOUND))
 (2 2 (:LINEAR LISTPOS-COMPLETE))
 (2 2
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-RSH-WHEN-INDEX-EQUAL))
 (2 2
    (:LINEAR
         SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-IDX-WHEN-INDEX-BOUND))
 (2 2
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-RSH-WHEN-AT-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-UPPER-BOUND))
 (2 2
    (:LINEAR SV::ELAB-MOD-WIRESEARCH-DUMBPIVOT-LOWER-BOUND))
 (2 2
    (:LINEAR SV::BOUND-OF-SVEXARR-VARS-WITNESS-AUX))
 (1 1
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
 (1 1
    (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
 (1 1
    (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::SVTV-EXTEND-ENTRYLIST-NAT-EQUIV-CONGRUENCE-ON-LEN)
(SV::SVTV-EXTEND-ENTRYLIST-OF-SVTV-ENTRY-FIX-LASTVAL
     (1537 321
           (:REWRITE SV::4VEC-P-WHEN-MAYBE-4VEC-P))
     (693 265
          (:REWRITE SV::MAYBE-4VEC-P-WHEN-4VEC-P))
     (642 642
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (561 561
          (:TYPE-PRESCRIPTION SV::MAYBE-4VEC-P))
     (450 61
          (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (344 56 (:REWRITE NFIX-WHEN-NATP))
     (300 61
          (:REWRITE SV::SVTV-ENTRY-P-OF-CAR-WHEN-SVTV-ENTRYLIST-P))
     (248 56 (:REWRITE NFIX-WHEN-NOT-NATP))
     (192 192 (:TYPE-PRESCRIPTION NATP))
     (192 96 (:REWRITE NATP-WHEN-GTE-0))
     (172 172
          (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-FIX))
     (150 150
          (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (110 32 (:REWRITE ZP-WHEN-INTEGERP))
     (106 106 (:REWRITE DEFAULT-<-2))
     (106 106 (:REWRITE DEFAULT-<-1))
     (96 96 (:REWRITE NATP-WHEN-INTEGERP))
     (96 32 (:REWRITE ZP-WHEN-GT-0))
     (88 88 (:REWRITE DEFAULT-+-2))
     (88 88 (:REWRITE DEFAULT-+-1))
     (84 14
         (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
     (78 78 (:REWRITE DEFAULT-CAR))
     (78 26 (:REWRITE FOLD-CONSTS-IN-+))
     (75 75
         (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (75 75
         (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (70 70 (:REWRITE DEFAULT-SYMBOL-NAME))
     (56 14
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (28 28
         (:REWRITE-QUOTED-CONSTANT
              SV::SVTV-ENTRYLIST-FIX-UNDER-SVTV-ENTRYLIST-EQUIV))
     (16 16
         (:REWRITE SV::4VEC-P-OF-4VEC-ZERO-EXT))
     (6 6 (:REWRITE ZP-OPEN))
     (1 1
        (:REWRITE-QUOTED-CONSTANT SV::SVTV-ENTRY-FIX-UNDER-SVTV-ENTRY-EQUIV))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::SVTV-EXTEND-ENTRYLIST-SVTV-ENTRY-EQUIV-CONGRUENCE-ON-LASTVAL)
(SV::SVTV-EXTEND-ENTRYLIST-OF-SVTV-ENTRY-FIX-LASTENT
     (1020 1020
           (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (792 112
          (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (690 690
          (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-FIX))
     (565 91 (:REWRITE NFIX-WHEN-NATP))
     (528 112
          (:REWRITE SV::SVTV-ENTRY-P-OF-CAR-WHEN-SVTV-ENTRYLIST-P))
     (407 91 (:REWRITE NFIX-WHEN-NOT-NATP))
     (316 316 (:TYPE-PRESCRIPTION NATP))
     (316 158 (:REWRITE NATP-WHEN-GTE-0))
     (264 264
          (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (222 74 (:REWRITE ZP-WHEN-GT-0))
     (191 191 (:REWRITE DEFAULT-<-2))
     (191 191 (:REWRITE DEFAULT-<-1))
     (188 74 (:REWRITE ZP-WHEN-INTEGERP))
     (158 158 (:REWRITE NATP-WHEN-INTEGERP))
     (133 133 (:REWRITE DEFAULT-CAR))
     (132 132
          (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
     (132 132
          (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (120 20
          (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
     (114 84 (:REWRITE DEFAULT-SYMBOL-NAME))
     (114 38 (:REWRITE FOLD-CONSTS-IN-+))
     (112 112 (:REWRITE DEFAULT-+-2))
     (112 112 (:REWRITE DEFAULT-+-1))
     (80 20
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
     (36 36 (:REWRITE ZP-OPEN))
     (33 33
         (:REWRITE-QUOTED-CONSTANT
              SV::SVTV-ENTRYLIST-FIX-UNDER-SVTV-ENTRYLIST-EQUIV))
     (30 30
         (:REWRITE SV::4VEC-P-OF-4VEC-ZERO-EXT))
     (6 6
        (:REWRITE-QUOTED-CONSTANT SV::SVTV-ENTRY-FIX-UNDER-SVTV-ENTRY-EQUIV))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
     (1 1
        (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::SVTV-EXTEND-ENTRYLIST-SVTV-ENTRY-EQUIV-CONGRUENCE-ON-LASTENT)
(SV::SVTV-EXTEND-ENTRYLIST-OF-NFIX-WIDTH
    (950 950
         (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
    (810 109
         (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
    (540 109
         (:REWRITE SV::SVTV-ENTRY-P-OF-CAR-WHEN-SVTV-ENTRYLIST-P))
    (448 163 (:REWRITE NFIX-WHEN-NOT-NATP))
    (391 391
         (:TYPE-PRESCRIPTION SV::SVTV-ENTRY-FIX))
    (270 270
         (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
    (252 252 (:TYPE-PRESCRIPTION NATP))
    (252 126 (:REWRITE NATP-WHEN-GTE-0))
    (213 71 (:REWRITE ZP-WHEN-GT-0))
    (190 190 (:REWRITE DEFAULT-<-2))
    (190 190 (:REWRITE DEFAULT-<-1))
    (156 26
         (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
    (154 154 (:REWRITE DEFAULT-+-2))
    (154 154 (:REWRITE DEFAULT-+-1))
    (143 133 (:REWRITE DEFAULT-CAR))
    (135 135
         (:REWRITE SV::SVTV-ENTRYLIST-P-WHEN-NOT-CONSP))
    (135 135
         (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
    (126 126 (:REWRITE NATP-WHEN-INTEGERP))
    (106 97 (:REWRITE DEFAULT-SYMBOL-NAME))
    (104 26
         (:REWRITE SV::SVTV-ENTRYLIST-P-OF-CDR-WHEN-SVTV-ENTRYLIST-P))
    (49 49
        (:REWRITE-QUOTED-CONSTANT
             SV::SVTV-ENTRYLIST-FIX-UNDER-SVTV-ENTRYLIST-EQUIV))
    (15 15 (:REWRITE ZP-OPEN))
    (12 12
        (:REWRITE-QUOTED-CONSTANT SV::SVTV-ENTRY-FIX-UNDER-SVTV-ENTRY-EQUIV))
    (1 1
       (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-LHS-BITPROJ-INDEX-BOUND))
    (1 1
       (:LINEAR SV::LHS-VARS-NORMORDEREDP-IMPLIES-INDEX-BOUND))
    (1 1
       (:LINEAR SV::LHATOM-NORMORDEREDP-IMPLIES-INDEX-BOUND)))
(SV::SVTV-EXTEND-ENTRYLIST-NAT-EQUIV-CONGRUENCE-ON-WIDTH)
(SV::SVTV-EXPAND-LINES
     (5 5 (:REWRITE DEFAULT-CAR))
     (3 3
        (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
     (3 1 (:REWRITE NATP-WHEN-GTE-0))
     (2 2
        (:REWRITE-QUOTED-CONSTANT SV::SVTV-ENTRY-FIX-UNDER-SVTV-ENTRY-EQUIV))
     (1 1 (:REWRITE NATP-WHEN-INTEGERP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1)))
(SV::SVTV-LINES-P-OF-SVTV-EXPAND-LINES
     (33 9
         (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
     (3 3 (:REWRITE DEFAULT-CAR))
     (2 2
        (:REWRITE-QUOTED-CONSTANT SV::SVTV-ENTRY-FIX-UNDER-SVTV-ENTRY-EQUIV))
     (1 1 (:REWRITE DEFAULT-CDR)))
(SV::SVTV-EXPAND-LINES-OF-SVTV-LINES-FIX-X
    (32 6
        (:REWRITE SV::SVTV-LINES-FIX-WHEN-SVTV-LINES-P))
    (27 24 (:REWRITE DEFAULT-CAR))
    (21 3
        (:REWRITE SV::SVTV-LINE-FIX-WHEN-SVTV-LINE-P))
    (18 9
        (:REWRITE SV::CAR-OF-SVTV-LINES-FIX-X-UNDER-SVTV-LINE-EQUIV))
    (18 8 (:REWRITE DEFAULT-CDR))
    (14 14
        (:REWRITE-QUOTED-CONSTANT SV::SVTV-ENTRY-FIX-UNDER-SVTV-ENTRY-EQUIV))
    (12 11
        (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
    (12 3
        (:REWRITE SV::SVTV-LINE-P-OF-CAR-WHEN-SVTV-LINES-P))
    (8 2
       (:REWRITE SV::SVTV-LINES-P-OF-CDR-WHEN-SVTV-LINES-P))
    (6 6 (:TYPE-PRESCRIPTION SV::SVTV-LINE-P))
    (6 6
       (:REWRITE SV::CONSP-OF-SVTV-LINES-FIX)))
(SV::SVTV-EXPAND-LINES-SVTV-LINES-EQUIV-CONGRUENCE-ON-X)
(SV::SVTV-EXPAND-LINES-OF-NFIX-LEN
    (28 4 (:REWRITE NFIX-WHEN-NATP))
    (20 4 (:REWRITE NFIX-WHEN-NOT-NATP))
    (18 18 (:REWRITE DEFAULT-CAR))
    (16 16 (:TYPE-PRESCRIPTION NATP))
    (16 8 (:REWRITE NATP-WHEN-GTE-0))
    (12 12
        (:REWRITE-QUOTED-CONSTANT SV::SVTV-ENTRY-FIX-UNDER-SVTV-ENTRY-EQUIV))
    (8 8 (:REWRITE NATP-WHEN-INTEGERP))
    (4 4 (:REWRITE DEFAULT-CDR))
    (4 4 (:REWRITE DEFAULT-<-2))
    (4 4 (:REWRITE DEFAULT-<-1)))
(SV::SVTV-EXPAND-LINES-NAT-EQUIV-CONGRUENCE-ON-LEN)
(SV::SVTV-LINES->OVERRIDES
     (8 8
        (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (4 4 (:REWRITE NFIX-WHEN-NOT-NATP))
     (3 3
        (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
     (3 1 (:REWRITE NATP-WHEN-GTE-0))
     (2 2
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (1 1 (:REWRITE NATP-WHEN-INTEGERP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1 (:REWRITE DEFAULT-+-2))
     (1 1 (:REWRITE DEFAULT-+-1)))
(SV::SVTV-OVERRIDELINES-P-OF-SVTV-LINES->OVERRIDES.SVTV-OVS
     (29 5 (:REWRITE NFIX-WHEN-NATP))
     (21 5 (:REWRITE NFIX-WHEN-NOT-NATP))
     (16 16 (:TYPE-PRESCRIPTION NATP))
     (16 8 (:REWRITE NATP-WHEN-GTE-0))
     (9 9
        (:REWRITE SV::SVTV-OVERRIDELINES-P-WHEN-NOT-CONSP))
     (8 8 (:REWRITE NATP-WHEN-INTEGERP))
     (6 3 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1))
     (3 3 (:TYPE-PRESCRIPTION NFIX))
     (3 3 (:REWRITE DEFAULT-CDR))
     (3 3 (:REWRITE DEFAULT-+-1))
     (2 2
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (1 1 (:REWRITE DEFAULT-CAR)))
(SV::LHS-OVERRIDELIST-P-OF-SVTV-LINES->OVERRIDES.LHS-OVS
  (345 7 (:DEFINITION MEMBER-EQUAL))
  (344 18
       (:REWRITE SV::LHS-OVERRIDELIST-P-WHEN-SUBSETP-EQUAL))
  (319 5 (:DEFINITION SUBSETP-EQUAL))
  (258 3 (:REWRITE SV::EQUAL-OF-LHS-OVERRIDE))
  (132 6 (:REWRITE SV::EQUAL-OF-SVEX-VAR))
  (122 8
       (:REWRITE SV::LHS-OVERRIDE-P-WHEN-MEMBER-EQUAL-OF-LHS-OVERRIDELIST-P))
  (66 6 (:REWRITE SV::EQUAL-OF-SVAR))
  (48 6 (:REWRITE SV::SVEX-FIX-WHEN-SVEX-P))
  (44 44 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
  (39 9 (:REWRITE NFIX-WHEN-NATP))
  (30 6
      (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
  (30 6 (:REWRITE SV::SVAR-FIX-WHEN-SVAR-P))
  (29 9 (:REWRITE NFIX-WHEN-NOT-NATP))
  (26 26 (:TYPE-PRESCRIPTION NFIX))
  (22 22 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
  (21 21
      (:TYPE-PRESCRIPTION SV::SVEX-KIND$INLINE))
  (21 21
      (:TYPE-PRESCRIPTION SV::SVAR->OVERRIDE-TEST$INLINE))
  (21 21
      (:TYPE-PRESCRIPTION SV::SVAR->NONBLOCKING$INLINE))
  (21 21
      (:TYPE-PRESCRIPTION SV::SVAR->DELAY$INLINE))
  (20 20 (:TYPE-PRESCRIPTION NATP))
  (20 10 (:REWRITE NATP-WHEN-GTE-0))
  (17 17 (:REWRITE DEFAULT-CDR))
  (15 15
      (:TYPE-PRESCRIPTION SV::SVTV-LINE->LHS$INLINE))
  (15 15
      (:TYPE-PRESCRIPTION SV::SVAR->OVERRIDE-VAL$INLINE))
  (15 3 (:REWRITE SV::LHS-FIX-WHEN-LHS-P))
  (14 14 (:REWRITE DEFAULT-CAR))
  (12 12 (:TYPE-PRESCRIPTION SV::SVEX-P))
  (12 12
      (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
  (12 12
      (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
  (12 6
      (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
  (10 10 (:REWRITE NATP-WHEN-INTEGERP))
  (10 5 (:REWRITE DEFAULT-+-2))
  (9 9
     (:TYPE-PRESCRIPTION SV::LHS-OVERRIDE->LHS$INLINE))
  (9 9
     (:REWRITE SV::LHS-OVERRIDELIST-P-WHEN-NOT-CONSP))
  (7 7
     (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
  (6 6
     (:TYPE-PRESCRIPTION SV::SVEX-VAR->NAME$INLINE))
  (6 6 (:TYPE-PRESCRIPTION SV::SVEX-VAR))
  (6 6 (:TYPE-PRESCRIPTION SV::SVAR-P))
  (6 6 (:TYPE-PRESCRIPTION SV::SVAR))
  (6 6
     (:REWRITE SV::SVAR-P-OF-SVEX-VAR->NAME))
  (6 6 (:REWRITE SV::SVAR-P-OF-SVAR))
  (6 6
     (:REWRITE SV::RETURN-TYPE-OF-SVEX-VAR))
  (5 5 (:REWRITE DEFAULT-<-2))
  (5 5 (:REWRITE DEFAULT-<-1))
  (5 5 (:REWRITE DEFAULT-+-1))
  (4 4
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
  (4 4
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
  (3 3 (:TYPE-PRESCRIPTION SV::LHS-P))
  (3 3
     (:TYPE-PRESCRIPTION SV::LHS-OVERRIDE->VAL$INLINE))
  (3 3
     (:TYPE-PRESCRIPTION SV::LHS-OVERRIDE->TEST$INLINE))
  (3 3 (:TYPE-PRESCRIPTION SV::LHS-OVERRIDE))
  (3 3
     (:REWRITE SV::SVEX-P-OF-LHS-OVERRIDE->VAL))
  (3 3
     (:REWRITE SV::SVEX-P-OF-LHS-OVERRIDE->TEST))
  (3 3
     (:REWRITE SV::LHS-P-OF-SVTV-LINE->LHS))
  (3 3
     (:REWRITE SV::LHS-OVERRIDE-P-OF-CAR-WHEN-LHS-OVERRIDELIST-P))
  (1 1 (:REWRITE CDR-CONS))
  (1 1 (:REWRITE CAR-CONS)))
(SV::SVTV-LINES->OVERRIDES-OF-SVTV-LINES-FIX-X
     (105 39 (:REWRITE NFIX-WHEN-NATP))
     (87 39 (:REWRITE NFIX-WHEN-NOT-NATP))
     (55 39 (:REWRITE DEFAULT-CAR))
     (52 36 (:REWRITE DEFAULT-CDR))
     (37 37 (:TYPE-PRESCRIPTION NFIX))
     (36 36 (:TYPE-PRESCRIPTION NATP))
     (36 18 (:REWRITE NATP-WHEN-GTE-0))
     (32 6
         (:REWRITE SV::SVTV-LINES-FIX-WHEN-SVTV-LINES-P))
     (26 26
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (26 26
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (26 13 (:REWRITE DEFAULT-+-2))
     (21 3
         (:REWRITE SV::SVTV-LINE-FIX-WHEN-SVTV-LINE-P))
     (18 18 (:REWRITE NATP-WHEN-INTEGERP))
     (16 4 (:REWRITE FOLD-CONSTS-IN-+))
     (13 13 (:REWRITE DEFAULT-+-1))
     (12 11
         (:REWRITE SV::SVTV-LINES-P-WHEN-NOT-CONSP))
     (12 3
         (:REWRITE SV::SVTV-LINE-P-OF-CAR-WHEN-SVTV-LINES-P))
     (9 9 (:REWRITE DEFAULT-<-2))
     (9 9 (:REWRITE DEFAULT-<-1))
     (9 9
        (:REWRITE SV::CONSP-OF-SVTV-LINES-FIX))
     (8 2
        (:REWRITE SV::SVTV-LINES-P-OF-CDR-WHEN-SVTV-LINES-P))
     (6 6 (:TYPE-PRESCRIPTION SV::SVTV-LINE-P)))
(SV::SVTV-LINES->OVERRIDES-SVTV-LINES-EQUIV-CONGRUENCE-ON-X)
(SV::SVTV-LINES->OVERRIDES-OF-NFIX-INDEX
     (94 44 (:REWRITE NFIX-WHEN-NOT-NATP))
     (38 34 (:REWRITE DEFAULT-CAR))
     (37 33 (:REWRITE DEFAULT-CDR))
     (28 28 (:TYPE-PRESCRIPTION NATP))
     (28 14 (:REWRITE NATP-WHEN-GTE-0))
     (26 26
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (26 26
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (26 13 (:REWRITE DEFAULT-+-2))
     (16 4 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE NATP-WHEN-INTEGERP))
     (13 13 (:REWRITE DEFAULT-+-1))
     (7 7 (:REWRITE DEFAULT-<-2))
     (7 7 (:REWRITE DEFAULT-<-1)))
(SV::SVTV-LINES->OVERRIDES-NAT-EQUIV-CONGRUENCE-ON-INDEX)
