#|-*-Lisp-*-=================================================================|#
#|                                                                           |#
#| coi: Computational Object Inference                                       |#
#|                                                                           |#
#|===========================================================================|#

include ../../../Makefile-generic
BOOKS = compiler-proof compiler zero complex
