include ../../../../Makefile-generic

# BOOKS = mod4 add3-proofs add3 all-ones ash bias-proofs bias bitn bitn-proofs						\
#         bits bits-proofs bvecp-proofs bvecp bvecp-helpers bvecp-lemmas ocat						\
#         lnot-proofs lnot decode-proofs decode encode fast-and ground-zero ireps log-proofs log land0-proofs land0		\
# 	lextra-proofs lextra0 lextra cat-proofs cat cat-def									\
#         lior0-proofs lior0 logand logand-proofs logeqv logior-proofs logior logior1-proofs logior1 lognot logorc1 logs	\
#         logxor lop1-proofs lop1 lop2-proofs lop2 lop3-proofs lop3 lxor0-proofs lxor0 float sumbits merge model-helpers  \
# 	badguys mulcat-proofs mulcat rewrite-theory rnd rom-helpers rtl rtlarr						\
#         setbits-proofs setbits setbitn-proofs setbitn shft sgn simple-loop-helpers					\
#         sticky-proofs sticky trunc-proofs trunc bits-trunc-proofs bits-trunc away-proofs away near-proofs		\
# 	near near+-proofs near+ oddr-proofs oddr rnd util log-equal lop1 lop2 lop3 ereps-proofs ereps ireps		\
# 	stick-proofs stick drnd-original merge2 fadd clocks openers package-defs simplify-model-helpers                          \
# 	top1 land lior lxor guards \
# 	fadd-extra fadd-extra0 float-extra round-extra top

# Dependencies:
-include Makefile-deps
