(VL::VL-PARSE-PROGRAM-DECLARATION-AUX-FN
  (1042 5
        (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
  (881 4 (:REWRITE SUBLISTP-WHEN-PREFIXP))
  (735 118 (:REWRITE LEN-WHEN-ATOM))
  (509 12
       (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
  (450 12 (:REWRITE PREFIXP-WHEN-PREFIXP))
  (369 13 (:REWRITE VL::NTH-WHEN-TOO-BIG))
  (336 9 (:REWRITE VL::NATP-WHEN-POSP))
  (256 256
       (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
  (252 252
       (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
  (238 3 (:REWRITE NATP-POSP))
  (202 20 (:LINEAR VL::LEN-OF-CDR-STRONG))
  (172 9 (:REWRITE NTH-WITH-LARGE-INDEX))
  (148 12
       (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
  (148 12
       (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
  (142 9 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
  (135 3
       (:REWRITE VL::VL-TOKENLIST-P-WHEN-NOT-CONSP))
  (108 6
       (:REWRITE VL::NATP-OF-CAR-WHEN-NAT-LISTP))
  (97 9 (:REWRITE NATP-RW))
  (82 82 (:REWRITE DEFAULT-CDR))
  (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
  (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
  (70 70
      (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
  (70 70
      (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
  (70 70 (:LINEAR LEN-WHEN-PREFIXP))
  (68 4
      (:REWRITE VL::NAT-LISTP-WHEN-NO-NILS-IN-VL-MAYBE-NAT-LISTP))
  (63 63 (:REWRITE CONSP-BY-LEN))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                . 2))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                . 1))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                . 2))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                . 1))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                . 2))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                . 1))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                . 2))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                . 1))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                . 2))
  (61 61
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                . 1))
  (60 3
      (:LINEAR LOWER-BOUND-OF-CAR-WHEN-NAT-LISTP))
  (57 5 (:REWRITE LEN-WHEN-PREFIXP))
  (51 3
      (:REWRITE TRUE-LISTP-WHEN-SYMBOL-LISTP-REWRITE))
  (51 3 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
  (47 3 (:REWRITE POSP-RW))
  (44 9 (:REWRITE NTH-WHEN-ATOM))
  (44 9 (:REWRITE VL::NTH-OF-ATOM))
  (43 8 (:REWRITE DEFAULT-CAR))
  (42 12 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
  (42 4
      (:REWRITE INTEGERP-OF-CAR-WHEN-NAT-LISTP))
  (42 3
      (:REWRITE TRUE-LISTP-WHEN-STRING-LISTP-REWRITE))
  (40 6 (:REWRITE VL::INTEGERP-WHEN-NATP))
  (40 2
      (:REWRITE VL::NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
  (39 39 (:LINEAR LEQ-POSITION-EQUAL-LEN))
  (39 39 (:LINEAR INDEX-OF-<-LEN))
  (39 20 (:REWRITE DEFAULT-<-2))
  (38 4
      (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
  (37 7
      (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
  (36 3
      (:REWRITE TRUE-LISTP-WHEN-CHARACTER-LISTP-REWRITE))
  (36 2
      (:REWRITE VL::POSP-OF-CAR-WHEN-POS-LISTP))
  (35 35
      (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
  (34 3 (:REWRITE TRUE-LISTP-WHEN-ATOM))
  (28 28 (:TYPE-PRESCRIPTION PREFIXP))
  (25 20 (:REWRITE DEFAULT-<-1))
  (24 24
      (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
  (24 24
      (:REWRITE NAT-LISTP-WHEN-SUBSETP-EQUAL))
  (24 18
      (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
  (24 10 (:REWRITE SET::DOUBLE-CONTAINMENT))
  (23 3
      (:REWRITE VL::VL-TOKENLIST-P-OF-CAR-WHEN-VL-TOKENLISTLIST-P))
  (21 3 (:REWRITE |(< 0 (len x))|))
  (20 20 (:META CANCEL_PLUS-LESSP-CORRECT))
  (20 6 (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
  (20 2
      (:REWRITE VL::VL-TOKEN-P-WHEN-VL-EXTINTTOKEN-P))
  (20 2
      (:REWRITE VL::VL-IDTOKEN-P-WHEN-WRONG-TAG))
  (18 18
      (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
  (18 18
      (:REWRITE NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
  (18 18 (:META CANCEL_TIMES-EQUAL-CORRECT))
  (18 18 (:META CANCEL_PLUS-EQUAL-CORRECT))
  (18 3
      (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
  (18 3
      (:REWRITE VL::CONSP-OF-CAR-WHEN-VL-COMMENTMAP-P))
  (17 4
      (:REWRITE VL::VL-TOKEN-P-WHEN-MEMBER-EQUAL-OF-VL-TOKENLIST-P))
  (17 3
      (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
  (17 3
      (:REWRITE VL::ALISTP-WHEN-ALL-HAVE-LEN))
  (16 4
      (:REWRITE VL::POS-LISTP-WHEN-NOT-CONSP))
  (16 4
      (:REWRITE VL::NAT-LISTP-WHEN-NOT-CONSP))
  (16 4 (:REWRITE MEMBER-WHEN-ATOM))
  (16 4
      (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
  (16 1
      (:REWRITE VL::VL-EXTINTTOKEN-P-WHEN-TOKEN-OF-TYPE-EXTINTTOKEN))
  (12 12 (:TYPE-PRESCRIPTION POSP))
  (12 12
      (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
  (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
  (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
  (12 12
      (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
  (12 12
      (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
  (12 12
      (:REWRITE NAT-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
  (12 12
      (:REWRITE INTEGERP-WHEN-MEMBER-EQUAL-OF-INTEGER-LISTP))
  (12 6
      (:REWRITE SYMBOL-LISTP-WHEN-SUBSETP-EQUAL))
  (12 5
      (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
  (12 3
      (:REWRITE VL::STRING-LISTP-WHEN-NO-NILS-IN-VL-MAYBE-STRING-LISTP))
  (12 2
      (:REWRITE VL::POS-LISTP-OF-CDR-WHEN-POS-LISTP))
  (12 2
      (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
  (11 11 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
  (10 5 (:REWRITE SET::NONEMPTY-MEANS-SET))
  (9 9 (:REWRITE NTH-WHEN-ZP))
  (9 3
     (:REWRITE VL::SYMBOL-LISTP-WHEN-SUBSETP-EQUAL-OF-SYMBOL-LISTP
               . 1))
  (9 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-TIMETOKEN-P))
  (9 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-SYSIDTOKEN-P))
  (9 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-REALTOKEN-P))
  (9 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-INTTOKEN-P))
  (8 8 (:TYPE-PRESCRIPTION SUBLISTP))
  (8 8
     (:REWRITE VL::POS-LISTP-WHEN-SUBSETP-EQUAL))
  (8 8
     (:REWRITE VL::NAT-LISTP-WHEN-SUBSETP-EQUAL))
  (8 8
     (:REWRITE INTEGER-LISTP-WHEN-SUBSETP-EQUAL))
  (8 8 (:REWRITE CAR-WHEN-ALL-EQUALP))
  (8 3
     (:REWRITE VL::VL-TOKENLISTLIST-P-WHEN-NOT-CONSP))
  (8 3
     (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
  (8 3
     (:REWRITE VL::ALL-HAVE-LEN-WHEN-NOT-CONSP))
  (8 3 (:REWRITE ALISTP-WHEN-ATOM))
  (8 2
     (:REWRITE VL::VL-MATCH-TOKEN-FAILS-GRACEFULLY))
  (7 7 (:REWRITE FN-CHECK-DEF-FORMALS))
  (6 6 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
  (6 6
     (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
  (6 6
     (:TYPE-PRESCRIPTION CONSP-MEMBER-EQUAL))
  (6 6 (:TYPE-PRESCRIPTION VL::ALL-HAVE-LEN))
  (6 6 (:TYPE-PRESCRIPTION ALISTP))
  (6 6
     (:REWRITE VL::VL-TOKENLISTLIST-P-WHEN-SUBSETP-EQUAL))
  (6 6
     (:REWRITE VL::VL-TOKENLIST-P-WHEN-SUBSETP-EQUAL))
  (6 6
     (:REWRITE VL::VL-TOKENLIST-P-WHEN-MEMBER-EQUAL-OF-VL-TOKENLISTLIST-P))
  (6 6
     (:REWRITE VL::VL-COMMENTMAP-P-WHEN-SUBSETP-EQUAL))
  (6 6
     (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
  (6 6
     (:REWRITE VL::SYMBOL-LISTP-WHEN-MEMBER-EQUAL-OF-SYMBOL-LIST-LISTP))
  (6 6
     (:REWRITE VL::SYMBOL-LISTP-OF-ALIST-VALS-OF-VL-FULL-KEYWORD-TABLE))
  (6 6
     (:REWRITE STRING-LISTP-WHEN-SUBSETP-EQUAL))
  (6 6
     (:REWRITE VL::STRING-LISTP-WHEN-MEMBER-EQUAL-OF-STRING-LIST-LISTP))
  (6 6
     (:REWRITE VL::POSP-WHEN-MEMBER-EQUAL-OF-POS-LISTP))
  (6 6 (:REWRITE NTH-WHEN-PREFIXP))
  (6 6
     (:REWRITE CHARACTER-LISTP-WHEN-SUBSETP-EQUAL))
  (6 3
     (:REWRITE SYMBOL-LISTP-WHEN-BOOLEAN-LISTP))
  (6 3
     (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
  (6 3
     (:REWRITE CONSP-OF-CAR-WHEN-ATOM-LISTP))
  (6 3
     (:REWRITE STR::CHARACTER-LISTP-WHEN-OCT-DIGIT-CHAR-LISTP))
  (6 3
     (:REWRITE STR::CHARACTER-LISTP-WHEN-HEX-DIGIT-CHAR-LISTP))
  (6 3
     (:REWRITE STR::CHARACTER-LISTP-WHEN-DEC-DIGIT-CHAR-LISTP))
  (5 5 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
  (5 5
     (:REWRITE VL::VL-MATCH-ANY-FN-COUNT-STRONG-ON-VALUE))
  (5 5 (:REWRITE SUBSETP-MEMBER . 2))
  (5 5 (:REWRITE SUBSETP-MEMBER . 1))
  (5 5
     (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
  (5 5 (:REWRITE SET::IN-SET))
  (5 1
     (:REWRITE VL::VL-TIMETOKEN-P-WHEN-TOKEN-OF-TYPE-TIMETOKEN))
  (5 1
     (:REWRITE VL::VL-SYSIDTOKEN-P-WHEN-TOKEN-OF-TYPE-SYSIDTOKEN))
  (5 1
     (:REWRITE VL::VL-REALTOKEN-P-WHEN-TOKEN-OF-TYPE-REALTOKEN))
  (5 1
     (:REWRITE VL::VL-INTTOKEN-P-WHEN-TOKEN-OF-TYPE-INTTOKEN))
  (4 4
     (:REWRITE VL::VL-IDTOKEN-P-WHEN-MEMBER-EQUAL-OF-VL-IDTOKEN-LIST-P))
  (4 4 (:REWRITE SUBSETP-MEMBER . 4))
  (4 4 (:REWRITE SUBSETP-MEMBER . 3))
  (4 4 (:REWRITE SUBLISTP-COMPLETE))
  (4 4 (:REWRITE INTERSECTP-MEMBER . 3))
  (4 4 (:REWRITE INTERSECTP-MEMBER . 2))
  (3 3
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-TIMETOKEN-P))
  (3 3
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-SYSIDTOKEN-P))
  (3 3
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-REALTOKEN-P))
  (3 3
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-INTTOKEN-P))
  (3 3
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-EXTINTTOKEN-P))
  (3 3
     (:REWRITE VL::VL-COMMENTMAP-P-WHEN-NOT-CONSP))
  (3 3
     (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
  (3 3
     (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
  (3 3
     (:REWRITE VL::SYMBOL-LISTP-WHEN-SUBSETP-EQUAL-OF-SYMBOL-LISTP
               . 2))
  (3 3
     (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (3 3
     (:REWRITE VL::STRING-LISTP-WHEN-SUBSETP-EQUAL-OF-STRING-LISTP
               . 2))
  (3 3
     (:REWRITE VL::STRING-LISTP-WHEN-SUBSETP-EQUAL-OF-STRING-LISTP
               . 1))
  (3 3
     (:REWRITE STRING-LISTP-WHEN-NOT-CONSP))
  (3 3
     (:REWRITE CHARACTER-LISTP-WHEN-NOT-CONSP))
  (3 3
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
  (2 1
     (:REWRITE VL::TAG-WHEN-VL-TIMETOKEN-P))
  (2 1
     (:REWRITE VL::TAG-WHEN-VL-SYSIDTOKEN-P))
  (2 1
     (:REWRITE VL::TAG-WHEN-VL-STRINGTOKEN-P))
  (2 1
     (:REWRITE VL::TAG-WHEN-VL-REALTOKEN-P))
  (2 1 (:REWRITE VL::TAG-WHEN-VL-INTTOKEN-P))
  (2 1 (:REWRITE VL::TAG-WHEN-VL-IDTOKEN-P))
  (2 1
     (:REWRITE VL::TAG-WHEN-VL-EXTINTTOKEN-P))
  (1 1
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-STRINGTOKEN-P)))
(VL::VL-PARSE-PROGRAM-DECLARATION-AUX-FAILS-GRACEFULLY
     (779 5
          (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (579 5 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (542 271
          (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?-FN-WHEN-ATOM-OF-TOKENS))
     (308 36 (:REWRITE LEN-WHEN-ATOM))
     (303 15 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (185 15
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (185 15
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (114 15
          (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (92 92
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (92 92
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (92 46
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (90 5 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (90 5 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (70 5 (:REWRITE LEN-WHEN-PREFIXP))
     (46 46 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                   . 2))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                   . 1))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                   . 2))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                   . 1))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (46 46
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (46 46 (:REWRITE CONSP-BY-LEN))
     (35 35 (:TYPE-PRESCRIPTION PREFIXP))
     (30 30
         (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
     (15 15
         (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
     (15 15 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (15 15 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (15 15
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (15 15
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (12 12
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (12 12
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (12 12 (:LINEAR LEN-WHEN-PREFIXP))
     (10 10 (:TYPE-PRESCRIPTION SUBLISTP))
     (10 10 (:META CANCEL_TIMES-EQUAL-CORRECT))
     (10 10 (:META CANCEL_PLUS-EQUAL-CORRECT))
     (10 5 (:REWRITE DEFAULT-<-1))
     (7 5 (:REWRITE DEFAULT-<-2))
     (6 6 (:LINEAR LEQ-POSITION-EQUAL-LEN))
     (6 6 (:LINEAR INDEX-OF-<-LEN))
     (6 6
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (5 5
        (:REWRITE VL::VL-MATCH-ANY-FN-COUNT-STRONG-ON-VALUE))
     (5 5 (:REWRITE SUBLISTP-COMPLETE))
     (5 5 (:META CANCEL_PLUS-LESSP-CORRECT)))
(VL::VL-WARNING-P-OF-VL-PARSE-PROGRAM-DECLARATION-AUX
     (628 6
          (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (466 4 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (420 210
          (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?-FN-WHEN-ATOM-OF-TOKENS))
     (272 34 (:REWRITE LEN-WHEN-ATOM))
     (244 12 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (148 12
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (148 12
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (94 12
         (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (76 38
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (58 6 (:REWRITE LEN-WHEN-PREFIXP))
     (38 38 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                   . 1))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                   . 1))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (38 38 (:REWRITE CONSP-BY-LEN))
     (28 28 (:TYPE-PRESCRIPTION PREFIXP))
     (24 24
         (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
     (12 12
         (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (12 12
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (12 12
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (12 12 (:LINEAR LEN-WHEN-PREFIXP))
     (12 6 (:REWRITE DEFAULT-<-1))
     (10 10
         (:REWRITE VL::VL-WARNING-P-WHEN-MEMBER-EQUAL-OF-VL-WARNINGLIST-P))
     (8 8 (:TYPE-PRESCRIPTION SUBLISTP))
     (8 8 (:META CANCEL_TIMES-EQUAL-CORRECT))
     (8 8 (:META CANCEL_PLUS-EQUAL-CORRECT))
     (8 6 (:REWRITE DEFAULT-<-2))
     (6 6
        (:REWRITE VL::VL-MATCH-ANY-FN-COUNT-STRONG-ON-VALUE))
     (6 6 (:META CANCEL_PLUS-LESSP-CORRECT))
     (6 6 (:LINEAR LEQ-POSITION-EQUAL-LEN))
     (6 6 (:LINEAR INDEX-OF-<-LEN))
     (6 6
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (4 4 (:REWRITE SUBLISTP-COMPLETE)))
(VL::VL-PARSE-PROGRAM-DECLARATION-AUX-RESULT
     (628 6
          (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (466 4 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (272 34 (:REWRITE LEN-WHEN-ATOM))
     (244 12 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (148 12
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (148 12
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (94 12
         (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (78 78
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (78 39
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (58 6 (:REWRITE LEN-WHEN-PREFIXP))
     (39 39 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                   . 2))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                   . 1))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                   . 2))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                   . 1))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (39 39
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (39 39 (:REWRITE CONSP-BY-LEN))
     (28 28 (:TYPE-PRESCRIPTION PREFIXP))
     (24 24
         (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
     (18 2 (:REWRITE SET::DOUBLE-CONTAINMENT))
     (12 12
         (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (12 12
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (12 12
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (12 12 (:LINEAR LEN-WHEN-PREFIXP))
     (12 6 (:REWRITE DEFAULT-<-1))
     (10 10 (:META CANCEL_TIMES-EQUAL-CORRECT))
     (10 10 (:META CANCEL_PLUS-EQUAL-CORRECT))
     (8 8 (:TYPE-PRESCRIPTION SUBLISTP))
     (8 6 (:REWRITE DEFAULT-<-2))
     (6 6
        (:REWRITE VL::VL-MATCH-ANY-FN-COUNT-STRONG-ON-VALUE))
     (6 6 (:META CANCEL_PLUS-LESSP-CORRECT))
     (6 6 (:LINEAR LEQ-POSITION-EQUAL-LEN))
     (6 6 (:LINEAR INDEX-OF-<-LEN))
     (6 6
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (4 4 (:REWRITE SUBLISTP-COMPLETE))
     (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (2 2 (:REWRITE SET::IN-SET)))
(VL::VL-PARSE-PROGRAM-DECLARATION-AUX-COUNT-STRONG
     (3101 18
           (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (2437 17 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (1453 144 (:REWRITE LEN-WHEN-ATOM))
     (1254 51 (:REWRITE PREFIXP-WHEN-PREFIXP))
     (958 51
          (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (578 51
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (578 51
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (376 376
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (376 188
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (348 348
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (306 17 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (289 17 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (239 18 (:REWRITE LEN-WHEN-PREFIXP))
     (224 14 (:REWRITE VL::VL-MATCH-UNDER-IFF))
     (188 188 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                    . 2))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                    . 1))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                    . 2))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                    . 1))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                    . 2))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                    . 1))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                    . 2))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                    . 1))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                    . 2))
     (188 188
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                    . 1))
     (188 188 (:REWRITE CONSP-BY-LEN))
     (119 119 (:TYPE-PRESCRIPTION PREFIXP))
     (102 102
          (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
     (96 96
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (96 96
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (96 96 (:LINEAR LEN-WHEN-PREFIXP))
     (53 53 (:LINEAR LEQ-POSITION-EQUAL-LEN))
     (53 53 (:LINEAR INDEX-OF-<-LEN))
     (51 51
         (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
     (51 51 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (51 51 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (51 51
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (51 51
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (48 48
         (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (36 20 (:REWRITE SET::DOUBLE-CONTAINMENT))
     (34 34 (:TYPE-PRESCRIPTION SUBLISTP))
     (30 30 (:META CANCEL_TIMES-EQUAL-CORRECT))
     (30 30 (:META CANCEL_PLUS-EQUAL-CORRECT))
     (30 18 (:REWRITE DEFAULT-<-2))
     (29 18 (:REWRITE DEFAULT-<-1))
     (20 20 (:META CANCEL_PLUS-LESSP-CORRECT))
     (17 17 (:REWRITE SUBLISTP-COMPLETE)))
(VL::VL-PARSE-PROGRAM-DECLARATION-FN
 (1400 30 (:REWRITE VL::NATP-WHEN-POSP))
 (1321 41 (:REWRITE VL::NTH-WHEN-TOO-BIG))
 (1022 10 (:REWRITE NATP-POSP))
 (912 456
      (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?-FN-WHEN-ATOM-OF-TOKENS))
 (762 76 (:LINEAR VL::LEN-OF-CDR-STRONG))
 (740 263 (:REWRITE LEN-WHEN-ATOM))
 (641 30 (:REWRITE NTH-WITH-LARGE-INDEX))
 (527 30 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
 (504 504
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
 (504 504
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (486 27
      (:REWRITE VL::NATP-OF-CAR-WHEN-NAT-LISTP))
 (456 456 (:TYPE-PRESCRIPTION ATOM))
 (415 10
      (:REWRITE VL::VL-TOKENLIST-P-WHEN-NOT-CONSP))
 (412 30 (:REWRITE NATP-RW))
 (335 4
      (:REWRITE VL::STRINGP-WHEN-TRUE-LISTP))
 (312 312 (:REWRITE DEFAULT-CDR))
 (306 18
      (:REWRITE VL::NAT-LISTP-WHEN-NO-NILS-IN-VL-MAYBE-NAT-LISTP))
 (257 47 (:REWRITE SET::DOUBLE-CONTAINMENT))
 (243 13
      (:REWRITE TRUE-LISTP-WHEN-SYMBOL-LISTP-REWRITE))
 (208 13
      (:REWRITE TRUE-LISTP-WHEN-STRING-LISTP-REWRITE))
 (189 18
      (:REWRITE INTEGERP-OF-CAR-WHEN-NAT-LISTP))
 (186 11
      (:REWRITE VL::VL-ATTS-P-WHEN-NOT-CONSP))
 (180 9
      (:REWRITE VL::NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
 (180 9
      (:LINEAR LOWER-BOUND-OF-CAR-WHEN-NAT-LISTP))
 (174 13
      (:REWRITE TRUE-LISTP-WHEN-CHARACTER-LISTP-REWRITE))
 (171 18
      (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
 (170 170
      (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (170 170
      (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (170 170 (:LINEAR LEN-WHEN-PREFIXP))
 (166 10 (:REWRITE POSP-RW))
 (162 13 (:REWRITE TRUE-LISTP-WHEN-ATOM))
 (162 9
      (:REWRITE VL::POSP-OF-CAR-WHEN-POS-LISTP))
 (153 45 (:REWRITE NAT-LISTP-WHEN-NOT-CONSP))
 (149 30 (:REWRITE NTH-WHEN-ATOM))
 (149 30 (:REWRITE VL::NTH-OF-ATOM))
 (148 29 (:REWRITE DEFAULT-CAR))
 (138 20 (:REWRITE VL::INTEGERP-WHEN-NATP))
 (135 27
      (:REWRITE NAT-LISTP-OF-CDR-WHEN-NAT-LISTP))
 (135 10 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
 (114 57 (:REWRITE DEFAULT-<-2))
 (100 73
      (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
 (92 13
     (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (90 90
     (:REWRITE NAT-LISTP-WHEN-SUBSETP-EQUAL))
 (90 27
     (:REWRITE NATP-OF-CAR-WHEN-NAT-LISTP))
 (85 85 (:LINEAR LEQ-POSITION-EQUAL-LEN))
 (85 85 (:LINEAR INDEX-OF-<-LEN))
 (85 85
     (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
 (72 18
     (:REWRITE VL::POS-LISTP-WHEN-NOT-CONSP))
 (72 18
     (:REWRITE VL::NAT-LISTP-WHEN-NOT-CONSP))
 (72 18 (:REWRITE MEMBER-WHEN-ATOM))
 (72 18
     (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
 (70 70 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (70 10 (:REWRITE |(< 0 (len x))|))
 (66 33 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (65 10
     (:REWRITE VL::VL-TOKENLIST-P-OF-CAR-WHEN-VL-TOKENLISTLIST-P))
 (60 60
     (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
 (60 60
     (:REWRITE NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
 (60 13
     (:REWRITE VL::STRING-LISTP-WHEN-NO-NILS-IN-VL-MAYBE-STRING-LISTP))
 (60 10
     (:REWRITE VL::CONSP-OF-CAR-WHEN-VL-COMMENTMAP-P))
 (57 57 (:REWRITE DEFAULT-<-1))
 (57 57 (:META CANCEL_PLUS-LESSP-CORRECT))
 (57 3
     (:REWRITE VL::VL-IDTOKEN-P-WHEN-WRONG-TAG))
 (54 9
     (:REWRITE VL::POS-LISTP-OF-CDR-WHEN-POS-LISTP))
 (54 9
     (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
 (52 26
     (:REWRITE SYMBOL-LISTP-WHEN-SUBSETP-EQUAL))
 (47 47 (:META CANCEL_TIMES-EQUAL-CORRECT))
 (47 47 (:META CANCEL_PLUS-EQUAL-CORRECT))
 (45 45
     (:REWRITE NAT-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
 (45 10
     (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
 (45 10
     (:REWRITE VL::ALISTP-WHEN-ALL-HAVE-LEN))
 (44 20
     (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
 (40 40 (:TYPE-PRESCRIPTION POSP))
 (40 40
     (:REWRITE INTEGERP-WHEN-MEMBER-EQUAL-OF-INTEGER-LISTP))
 (39 13
     (:REWRITE VL::SYMBOL-LISTP-WHEN-SUBSETP-EQUAL-OF-SYMBOL-LISTP
               . 1))
 (38 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-EXTINTTOKEN-P))
 (36 36
     (:REWRITE VL::POS-LISTP-WHEN-SUBSETP-EQUAL))
 (36 36
     (:REWRITE VL::NAT-LISTP-WHEN-SUBSETP-EQUAL))
 (36 36
     (:REWRITE INTEGER-LISTP-WHEN-SUBSETP-EQUAL))
 (34 34
     (:REWRITE STRING-LISTP-WHEN-SUBSETP-EQUAL))
 (33 33 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (33 33 (:REWRITE SET::IN-SET))
 (33 33 (:REWRITE CONSP-BY-LEN))
 (32 2
     (:REWRITE VL::VL-EXTINTTOKEN-P-WHEN-TOKEN-OF-TYPE-EXTINTTOKEN))
 (31 31 (:REWRITE FN-CHECK-DEF-FORMALS))
 (30 30 (:REWRITE NTH-WHEN-ZP))
 (30 13
     (:REWRITE SYMBOL-LISTP-WHEN-BOOLEAN-LISTP))
 (30 4
     (:REWRITE VL::VL-TOKEN-P-WHEN-MEMBER-EQUAL-OF-VL-TOKENLIST-P))
 (29 29 (:REWRITE CAR-WHEN-ALL-EQUALP))
 (26 26 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
 (26 26
     (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
 (26 26
     (:REWRITE VL::SYMBOL-LISTP-WHEN-MEMBER-EQUAL-OF-SYMBOL-LIST-LISTP))
 (26 26
     (:REWRITE VL::SYMBOL-LISTP-OF-ALIST-VALS-OF-VL-FULL-KEYWORD-TABLE))
 (26 26
     (:REWRITE VL::STRING-LISTP-WHEN-MEMBER-EQUAL-OF-STRING-LIST-LISTP))
 (26 26
     (:REWRITE CHARACTER-LISTP-WHEN-SUBSETP-EQUAL))
 (26 13
     (:REWRITE STR::CHARACTER-LISTP-WHEN-OCT-DIGIT-CHAR-LISTP))
 (26 13
     (:REWRITE STR::CHARACTER-LISTP-WHEN-HEX-DIGIT-CHAR-LISTP))
 (26 13
     (:REWRITE STR::CHARACTER-LISTP-WHEN-DEC-DIGIT-CHAR-LISTP))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
               . 2))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
               . 1))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
               . 2))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
               . 1))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
               . 2))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
               . 1))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
               . 2))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
               . 1))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
               . 2))
 (24 24
     (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
               . 1))
 (21 17
     (:REWRITE STRING-LISTP-WHEN-NOT-CONSP))
 (20 20
     (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
 (20 20
     (:TYPE-PRESCRIPTION VL::ALL-HAVE-LEN))
 (20 20 (:TYPE-PRESCRIPTION ALISTP))
 (20 20
     (:REWRITE VL::VL-TOKENLISTLIST-P-WHEN-SUBSETP-EQUAL))
 (20 20
     (:REWRITE VL::VL-TOKENLIST-P-WHEN-SUBSETP-EQUAL))
 (20 20
     (:REWRITE VL::VL-TOKENLIST-P-WHEN-MEMBER-EQUAL-OF-VL-TOKENLISTLIST-P))
 (20 20
     (:REWRITE VL::VL-COMMENTMAP-P-WHEN-SUBSETP-EQUAL))
 (20 20 (:REWRITE SUBSETP-MEMBER . 2))
 (20 20 (:REWRITE SUBSETP-MEMBER . 1))
 (20 20
     (:REWRITE VL::POSP-WHEN-MEMBER-EQUAL-OF-POS-LISTP))
 (20 20 (:REWRITE NTH-WHEN-PREFIXP))
 (20 20
     (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
 (20 10
     (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
 (20 10
     (:REWRITE CONSP-OF-CAR-WHEN-ATOM-LISTP))
 (20 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-IDTOKEN-P))
 (19 19
     (:TYPE-PRESCRIPTION CONSP-MEMBER-EQUAL))
 (19 13
     (:REWRITE VL::VL-MATCH-TOKEN-FAILS-GRACEFULLY))
 (18 18 (:REWRITE SUBSETP-MEMBER . 4))
 (18 18 (:REWRITE SUBSETP-MEMBER . 3))
 (18 18 (:REWRITE INTERSECTP-MEMBER . 3))
 (18 18 (:REWRITE INTERSECTP-MEMBER . 2))
 (17 13
     (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
 (17 13
     (:REWRITE CHARACTER-LISTP-WHEN-NOT-CONSP))
 (16 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-TIMETOKEN-P))
 (16 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-SYSIDTOKEN-P))
 (16 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-STRINGTOKEN-P))
 (16 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-REALTOKEN-P))
 (16 2
     (:REWRITE VL::VL-TOKEN-P-WHEN-VL-INTTOKEN-P))
 (15 10
     (:REWRITE VL::VL-TOKENLISTLIST-P-WHEN-NOT-CONSP))
 (15 10
     (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
 (15 10
     (:REWRITE VL::ALL-HAVE-LEN-WHEN-NOT-CONSP))
 (15 10 (:REWRITE ALISTP-WHEN-ATOM))
 (13 13
     (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
 (13 13
     (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
 (13 13
     (:REWRITE VL::SYMBOL-LISTP-WHEN-SUBSETP-EQUAL-OF-SYMBOL-LISTP
               . 2))
 (13 13
     (:REWRITE VL::STRING-LISTP-WHEN-SUBSETP-EQUAL-OF-STRING-LISTP
               . 2))
 (13 13
     (:REWRITE VL::STRING-LISTP-WHEN-SUBSETP-EQUAL-OF-STRING-LISTP
               . 1))
 (10 10
     (:REWRITE VL::VL-IDTOKEN-P-WHEN-MEMBER-EQUAL-OF-VL-IDTOKEN-LIST-P))
 (10 10
     (:REWRITE VL::VL-COMMENTMAP-P-WHEN-NOT-CONSP))
 (10 10
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (10 2
     (:REWRITE VL::VL-TIMETOKEN-P-WHEN-TOKEN-OF-TYPE-TIMETOKEN))
 (10 2
     (:REWRITE VL::VL-SYSIDTOKEN-P-WHEN-TOKEN-OF-TYPE-SYSIDTOKEN))
 (10 2
     (:REWRITE VL::VL-STRINGTOKEN-P-WHEN-TOKEN-OF-TYPE-STRINGTOKEN))
 (10 2
     (:REWRITE VL::VL-REALTOKEN-P-WHEN-TOKEN-OF-TYPE-REALTOKEN))
 (10 2
     (:REWRITE VL::VL-INTTOKEN-P-WHEN-TOKEN-OF-TYPE-INTTOKEN))
 (8 8
    (:REWRITE VL::VL-PARSE-PROGRAM-DECLARATION-AUX-FAILS-GRACEFULLY))
 (8 8
    (:REWRITE STRINGP-WHEN-MEMBER-EQUAL-OF-STRING-LISTP))
 (7 7
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-TIMETOKEN-P))
 (7 7
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-SYSIDTOKEN-P))
 (7 7
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-STRINGTOKEN-P))
 (7 7
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-REALTOKEN-P))
 (7 7
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-INTTOKEN-P))
 (7 7
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-EXTINTTOKEN-P))
 (6 3
    (:REWRITE VL::TAG-WHEN-VL-TIMETOKEN-P))
 (6 3
    (:REWRITE VL::TAG-WHEN-VL-SYSIDTOKEN-P))
 (6 3
    (:REWRITE VL::TAG-WHEN-VL-STRINGTOKEN-P))
 (6 3
    (:REWRITE VL::TAG-WHEN-VL-REALTOKEN-P))
 (6 3 (:REWRITE VL::TAG-WHEN-VL-INTTOKEN-P))
 (6 3 (:REWRITE VL::TAG-WHEN-VL-IDTOKEN-P))
 (6 3
    (:REWRITE VL::TAG-WHEN-VL-EXTINTTOKEN-P))
 (6 2
    (:REWRITE VL::VL-TOKEN-P-WHEN-VL-PLAINTOKEN-P))
 (4 4
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-PLAINTOKEN-P))
 (4 4
    (:REWRITE-QUOTED-CONSTANT VL::MAYBE-STRING-FIX-UNDER-MAYBE-STRING-EQUIV))
 (1 1
    (:REWRITE-QUOTED-CONSTANT SYMBOL-FIX-UNDER-SYMBOL-EQUIV)))
(VL::VL-PARSE-PROGRAM-DECLARATION-FAILS-GRACEFULLY
 (246 123
      (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?-FN-WHEN-ATOM-OF-TOKENS))
 (118 59
      (:TYPE-PRESCRIPTION VL::RETURN-TYPE-OF-VL-IDTOKEN->NAME))
 (96 48
     (:TYPE-PRESCRIPTION VL::RETURN-TYPE-OF-VL-ENDINFO->NAME))
 (71 11
     (:REWRITE VL::VL-MATCH-TOKEN-FAILS-GRACEFULLY))
 (59 59
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-IDTOKEN-P))
 (48 48
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-ENDINFO-P))
 (36 3 (:REWRITE SET::DOUBLE-CONTAINMENT))
 (6 6 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (6 3 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (3 3 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (3 3 (:REWRITE SET::IN-SET))
 (3 3 (:META CANCEL_TIMES-EQUAL-CORRECT))
 (3 3 (:META CANCEL_PLUS-EQUAL-CORRECT))
 (2 2
    (:REWRITE-QUOTED-CONSTANT
         VL::VL-WARNINGLIST-FIX-UNDER-VL-WARNINGLIST-EQUIV))
 (2
  2
  (:REWRITE-QUOTED-CONSTANT VL::VL-COMMENTMAP-FIX-UNDER-VL-COMMENTMAP-EQUIV))
 (2 2
    (:REWRITE-QUOTED-CONSTANT SYMBOL-FIX-UNDER-SYMBOL-EQUIV))
 (2 2
    (:REWRITE-QUOTED-CONSTANT VL::MAYBE-STRING-FIX-UNDER-MAYBE-STRING-EQUIV))
 (2 2
    (:REWRITE VL::VL-PROGRAM-OF-VL-WARNINGLIST-FIX-WARNINGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MINLOC-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MAXLOC-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-PROGRAM-OF-VL-COMMENTMAP-FIX-COMMENTS-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-PROGRAM-OF-VL-ATTS-FIX-ATTS-NORMALIZE-CONST))
 (2 2
    (:REWRITE VL::VL-PROGRAM-OF-STR-FIX-NAME-NORMALIZE-CONST)))
(VL::VL-WARNING-P-OF-VL-PARSE-PROGRAM-DECLARATION
 (42 6
     (:REWRITE VL::VL-MATCH-TOKEN-FAILS-GRACEFULLY))
 (36 3 (:REWRITE SET::DOUBLE-CONTAINMENT))
 (30 15
     (:TYPE-PRESCRIPTION VL::RETURN-TYPE-OF-VL-IDTOKEN->NAME))
 (24 12
     (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?-FN-WHEN-ATOM-OF-TOKENS))
 (15 15
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-IDTOKEN-P))
 (12 12
     (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?$INLINE))
 (12 12 (:TYPE-PRESCRIPTION ATOM))
 (6 6 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (6 6
    (:REWRITE-QUOTED-CONSTANT
         VL::VL-WARNINGLIST-FIX-UNDER-VL-WARNINGLIST-EQUIV))
 (6
  6
  (:REWRITE-QUOTED-CONSTANT VL::VL-COMMENTMAP-FIX-UNDER-VL-COMMENTMAP-EQUIV))
 (6 6
    (:REWRITE-QUOTED-CONSTANT SYMBOL-FIX-UNDER-SYMBOL-EQUIV))
 (6 6
    (:REWRITE-QUOTED-CONSTANT VL::MAYBE-STRING-FIX-UNDER-MAYBE-STRING-EQUIV))
 (6 6
    (:REWRITE VL::VL-PROGRAM-OF-VL-WARNINGLIST-FIX-WARNINGS-NORMALIZE-CONST))
 (6 6
    (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MINLOC-NORMALIZE-CONST))
 (6 6
    (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MAXLOC-NORMALIZE-CONST))
 (6 6
    (:REWRITE VL::VL-PROGRAM-OF-VL-COMMENTMAP-FIX-COMMENTS-NORMALIZE-CONST))
 (6 6
    (:REWRITE VL::VL-PROGRAM-OF-VL-ATTS-FIX-ATTS-NORMALIZE-CONST))
 (6 6
    (:REWRITE VL::VL-PROGRAM-OF-STR-FIX-NAME-NORMALIZE-CONST))
 (6 3
    (:TYPE-PRESCRIPTION VL::RETURN-TYPE-OF-VL-ENDINFO->NAME))
 (6 3 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (3 3 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (3 3
    (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-ENDINFO-P))
 (3 3
    (:REWRITE VL::VL-PARSE-PROGRAM-DECLARATION-AUX-FAILS-GRACEFULLY))
 (3 3 (:REWRITE SET::IN-SET))
 (3 3 (:META CANCEL_TIMES-EQUAL-CORRECT))
 (3 3 (:META CANCEL_PLUS-EQUAL-CORRECT))
 (2 2
    (:REWRITE VL::VL-WARNING-P-WHEN-MEMBER-EQUAL-OF-VL-WARNINGLIST-P)))
(VL::VL-PARSE-PROGRAM-DECLARATION-RESULT
 (72 4
     (:REWRITE VL::VL-ATTS-P-WHEN-NOT-CONSP))
 (66 33
     (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?-FN-WHEN-ATOM-OF-TOKENS))
 (33 33 (:TYPE-PRESCRIPTION ATOM))
 (15 3 (:REWRITE SET::DOUBLE-CONTAINMENT))
 (8 8
    (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
 (8 8
    (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (8 4
    (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
 (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
 (4 4
    (:REWRITE-QUOTED-CONSTANT
         VL::VL-WARNINGLIST-FIX-UNDER-VL-WARNINGLIST-EQUIV))
 (4
  4
  (:REWRITE-QUOTED-CONSTANT VL::VL-COMMENTMAP-FIX-UNDER-VL-COMMENTMAP-EQUIV))
 (4 4
    (:REWRITE-QUOTED-CONSTANT SYMBOL-FIX-UNDER-SYMBOL-EQUIV))
 (4 4
    (:REWRITE-QUOTED-CONSTANT VL::MAYBE-STRING-FIX-UNDER-MAYBE-STRING-EQUIV))
 (4 4
    (:REWRITE VL::VL-PROGRAM-OF-VL-WARNINGLIST-FIX-WARNINGS-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MINLOC-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MAXLOC-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-PROGRAM-OF-VL-COMMENTMAP-FIX-COMMENTS-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-PROGRAM-OF-VL-ATTS-FIX-ATTS-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::VL-PROGRAM-OF-STR-FIX-NAME-NORMALIZE-CONST))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
              . 2))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
              . 1))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
              . 2))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
              . 1))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
              . 2))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
              . 1))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
              . 2))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
              . 1))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
              . 2))
 (4 4
    (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
              . 1))
 (4 4 (:REWRITE CONSP-BY-LEN))
 (3 3 (:META CANCEL_TIMES-EQUAL-CORRECT))
 (3 3 (:META CANCEL_PLUS-EQUAL-CORRECT))
 (2 2 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (2 2
    (:REWRITE VL::VL-PROGRAM-P-WHEN-MEMBER-EQUAL-OF-VL-PROGRAMLIST-P))
 (2 1 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (1 1 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (1 1 (:REWRITE SET::IN-SET)))
(VL::VL-PARSE-PROGRAM-DECLARATION-COUNT-STRONG
 (1636 4
       (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (1564 102 (:REWRITE LEN-WHEN-ATOM))
 (1476 4 (:REWRITE SUBLISTP-WHEN-PREFIXP))
 (1104 12
       (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
 (746 12 (:REWRITE PREFIXP-WHEN-PREFIXP))
 (220 220
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
 (220 220
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (220 110
      (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
 (148 12
      (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
 (148 12
      (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
 (110 110 (:TYPE-PRESCRIPTION TRUE-LISTP))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                . 2))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-IFDEF-USE-MAP-P
                . 1))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                . 2))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                . 1))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                . 2))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-DEF-USE-MAP-P
                . 1))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                . 2))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                . 1))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                . 2))
 (110 110
      (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                . 1))
 (110 110 (:REWRITE CONSP-BY-LEN))
 (100 50
      (:TYPE-PRESCRIPTION VL::RETURN-TYPE-OF-VL-ENDINFO->NAME))
 (98 49
     (:TYPE-PRESCRIPTION VL::RETURN-TYPE-OF-VL-IDTOKEN->NAME))
 (96 48
     (:TYPE-PRESCRIPTION VL::VL-IS-TOKEN?-FN-WHEN-ATOM-OF-TOKENS))
 (90 90
     (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
 (90 90
     (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
 (90 90 (:LINEAR LEN-WHEN-PREFIXP))
 (88 22
     (:REWRITE VL::VL-MATCH-TOKEN-UNDER-IFF))
 (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
 (72 4 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
 (70 10
     (:REWRITE VL::VL-MATCH-TOKEN-FAILS-GRACEFULLY))
 (56 4 (:REWRITE LEN-WHEN-PREFIXP))
 (54 54 (:LINEAR LEQ-POSITION-EQUAL-LEN))
 (54 54 (:LINEAR INDEX-OF-<-LEN))
 (52 11 (:REWRITE SET::DOUBLE-CONTAINMENT))
 (50 50
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-ENDINFO-P))
 (49 49
     (:TYPE-PRESCRIPTION VL::BOOLEANP-OF-VL-IDTOKEN-P))
 (48 48 (:TYPE-PRESCRIPTION ATOM))
 (45 45
     (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
 (28 28 (:TYPE-PRESCRIPTION PREFIXP))
 (24 24
     (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
 (12 12
     (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
 (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
 (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
 (12 12
     (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
 (12 12
     (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
 (11 11 (:META CANCEL_TIMES-EQUAL-CORRECT))
 (11 11 (:META CANCEL_PLUS-EQUAL-CORRECT))
 (10
    10
    (:REWRITE VL::VL-PROGRAM-OF-VL-WARNINGLIST-FIX-WARNINGS-NORMALIZE-CONST))
 (10 10
     (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MINLOC-NORMALIZE-CONST))
 (10 10
     (:REWRITE VL::VL-PROGRAM-OF-VL-LOCATION-FIX-MAXLOC-NORMALIZE-CONST))
 (10 10
     (:REWRITE VL::VL-PROGRAM-OF-VL-COMMENTMAP-FIX-COMMENTS-NORMALIZE-CONST))
 (10 10
     (:REWRITE VL::VL-PROGRAM-OF-VL-ATTS-FIX-ATTS-NORMALIZE-CONST))
 (9 9
    (:REWRITE-QUOTED-CONSTANT
         VL::VL-WARNINGLIST-FIX-UNDER-VL-WARNINGLIST-EQUIV))
 (9
  9
  (:REWRITE-QUOTED-CONSTANT VL::VL-COMMENTMAP-FIX-UNDER-VL-COMMENTMAP-EQUIV))
 (9 9
    (:REWRITE-QUOTED-CONSTANT SYMBOL-FIX-UNDER-SYMBOL-EQUIV))
 (9 9
    (:REWRITE-QUOTED-CONSTANT VL::MAYBE-STRING-FIX-UNDER-MAYBE-STRING-EQUIV))
 (8 8 (:TYPE-PRESCRIPTION SUBLISTP))
 (8 4 (:REWRITE DEFAULT-<-2))
 (8 4 (:REWRITE DEFAULT-<-1))
 (6 6 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (6 3 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (5 5
    (:REWRITE VL::VL-PARSE-PROGRAM-DECLARATION-AUX-FAILS-GRACEFULLY))
 (4 4 (:REWRITE SUBLISTP-COMPLETE))
 (4 4 (:META CANCEL_PLUS-LESSP-CORRECT))
 (3 3 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (3 3 (:REWRITE SET::IN-SET)))
