(JSON::VALID-JPAT-VARP)
(JSON::NULL-PATTERNP)
(JSON::TRUE-PATTERNP)
(JSON::FALSE-PATTERNP)
(JSON::STRING-PATTERNP-WITH-VARS)
(JSON::BOOLEANP-OF-STRING-PATTERNP-WITH-VARS.TRUE/FALSE
  (28 2
      (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (20 2 (:DEFINITION SYMBOL-LISTP))
  (15 3
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (13 13 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
  (13 13 (:REWRITE DEFAULT-CDR))
  (9 9 (:REWRITE DEFAULT-CAR))
  (4 4
     (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (2 2 (:REWRITE DEFAULT-SYMBOL-NAME))
  (2 2
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV))
  (2 2
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV)))
(JSON::SYMBOL-LISTP-OF-STRING-PATTERNP-WITH-VARS.PATVARS
  (95 6 (:DEFINITION SYMBOL-LISTP))
  (77 8
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (75 9
      (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (37 37 (:REWRITE DEFAULT-CDR))
  (26 26 (:REWRITE DEFAULT-CAR))
  (15 15
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (6 6 (:REWRITE DEFAULT-SYMBOL-NAME))
  (6 6
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV))
  (6 6
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV)))
(JSON::NUMBER-PATTERNP-WITH-VARS)
(JSON::BOOLEANP-OF-NUMBER-PATTERNP-WITH-VARS.TRUE/FALSE
  (28 2
      (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (20 2
      (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
  (20 2 (:DEFINITION SYMBOL-LISTP))
  (15 3
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (14 14 (:REWRITE DEFAULT-CDR))
  (13 13 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
  (13 2 (:DEFINITION RATIONAL-LISTP))
  (11 11 (:REWRITE DEFAULT-CAR))
  (8 8 (:TYPE-PRESCRIPTION RATIONAL-LISTP))
  (7 2
     (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
  (4 4
     (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (3 3
     (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
  (2 2 (:REWRITE DEFAULT-SYMBOL-NAME))
  (2 2
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV))
  (2 2
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV)))
(JSON::SYMBOL-LISTP-OF-NUMBER-PATTERNP-WITH-VARS.PATVARS
  (115 6 (:DEFINITION SYMBOL-LISTP))
  (97 8
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (75 9
      (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (40 4
      (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
  (39 39 (:REWRITE DEFAULT-CDR))
  (30 30 (:REWRITE DEFAULT-CAR))
  (26 4 (:DEFINITION RATIONAL-LISTP))
  (15 15
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (14 4
      (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
  (6 6
     (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
  (6 6 (:REWRITE DEFAULT-SYMBOL-NAME))
  (6 6
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV))
  (6 6
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV)))
(JSON::VALUE-PATTERNP-WITH-VARS
  (1486 483 (:REWRITE DEFAULT-+-2))
  (840 483 (:REWRITE DEFAULT-+-1))
  (784 88
       (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
  (784 88
       (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
  (642 60 (:DEFINITION RATIONAL-LISTP))
  (642 60 (:DEFINITION INTEGER-LISTP))
  (509 368 (:REWRITE DEFAULT-CDR))
  (417 201 (:REWRITE DEFAULT-<-1))
  (352 88 (:DEFINITION INTEGER-ABS))
  (329 201 (:REWRITE DEFAULT-<-2))
  (309 309 (:REWRITE DEFAULT-CAR))
  (212 78
       (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
  (212 78
       (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
  (141 141
       (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
  (141 94 (:REWRITE STR::CONSP-OF-EXPLODE))
  (120 19
       (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (104 104
       (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
  (104 104
       (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
  (102 9 (:DEFINITION SYMBOL-LISTP))
  (88 88 (:REWRITE DEFAULT-UNARY-MINUS))
  (52 9
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (47 47
      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
  (44 44 (:REWRITE DEFAULT-REALPART))
  (44 44 (:REWRITE DEFAULT-NUMERATOR))
  (44 44 (:REWRITE DEFAULT-IMAGPART))
  (44 44 (:REWRITE DEFAULT-DENOMINATOR))
  (16 8
      (:TYPE-PRESCRIPTION TRUE-LISTP-APPEND))
  (14 14
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (8 8 (:TYPE-PRESCRIPTION BINARY-APPEND))
  (5 5 (:REWRITE DEFAULT-SYMBOL-NAME))
  (5 5
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV))
  (4 4
     (:LINEAR ACL2-COUNT-OF-CONSP-POSITIVE))
  (1 1
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV)))
(JSON::PATTERN-CHECKERS-FLAG
  (1578 522 (:REWRITE DEFAULT-+-2))
  (893 522 (:REWRITE DEFAULT-+-1))
  (620 76
       (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
  (604 72
       (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
  (516 359 (:REWRITE DEFAULT-CDR))
  (492 46 (:DEFINITION RATIONAL-LISTP))
  (482 44 (:DEFINITION INTEGER-LISTP))
  (409 209 (:REWRITE DEFAULT-<-1))
  (400 100 (:DEFINITION INTEGER-ABS))
  (338 209 (:REWRITE DEFAULT-<-2))
  (311 301 (:REWRITE DEFAULT-CAR))
  (268 31
       (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (234 17 (:DEFINITION SYMBOL-LISTP))
  (158 1 (:DEFINITION O-P))
  (153 153
       (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
  (153 102 (:REWRITE STR::CONSP-OF-EXPLODE))
  (136 54
       (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
  (136 54
       (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
  (100 100 (:REWRITE DEFAULT-UNARY-MINUS))
  (99 5 (:REWRITE DEFAULT-SYMBOL-NAME))
  (87 1 (:DEFINITION O<))
  (84 25
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (82 82
      (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
  (80 80
      (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
  (58 8 (:DEFINITION O-FIRST-EXPT))
  (51 51
      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
  (50 50 (:REWRITE DEFAULT-REALPART))
  (50 50 (:REWRITE DEFAULT-NUMERATOR))
  (50 50 (:REWRITE DEFAULT-IMAGPART))
  (50 50 (:REWRITE DEFAULT-DENOMINATOR))
  (44 44
      (:TYPE-PRESCRIPTION TWO-NATS-MEASURE))
  (35 17 (:DEFINITION O-FINP))
  (34 34
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (24 5 (:DEFINITION O-FIRST-COEFF))
  (23 5
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
  (17 2
      (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
  (14 1 (:DEFINITION ACL2-NUMBER-LISTP))
  (12 4 (:DEFINITION O-RST))
  (9 9
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
  (6 6
     (:LINEAR ACL2-COUNT-OF-CONSP-POSITIVE))
  (5 5
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV))
  (3 1 (:DEFINITION POSP))
  (1 1
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV))
  (1 1
     (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP)))
(FLAG::FLAG-EQUIV-LEMMA)
(JSON::PATTERN-CHECKERS-FLAG-EQUIVALENCES)
(JSON::FLAG-LEMMA-FOR-RETURN-TYPE-OF-VALUE-PATTERNP-WITH-VARS.TRUE/FALSE
 (2122 2122 (:REWRITE DEFAULT-CDR))
 (1890 1890 (:REWRITE DEFAULT-CAR))
 (216 108 (:REWRITE DEFAULT-+-2))
 (129 129 (:REWRITE DEFAULT-SYMBOL-NAME))
 (108 108 (:REWRITE DEFAULT-+-1))
 (81 81
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV))
 (25 25
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV)))
(JSON::RETURN-TYPE-OF-VALUE-PATTERNP-WITH-VARS.TRUE/FALSE)
(JSON::RETURN-TYPE-OF-VALUE-PATTERNP-WITH-VARS.PATVARS)
(JSON::RETURN-TYPE-OF-ARRAY-PATTERNP-WITH-VARS.TRUE/FALSE)
(JSON::RETURN-TYPE-OF-ARRAY-PATTERNP-WITH-VARS.PATVARS)
(JSON::RETURN-TYPE-OF-ARRAY-ELEMENTS-PATTERNP-WITH-VARS.TRUE/FALSE)
(JSON::RETURN-TYPE-OF-ARRAY-ELEMENTS-PATTERNP-WITH-VARS.PATVARS)
(JSON::RETURN-TYPE-OF-OBJECT-PATTERNP-WITH-VARS.TRUE/FALSE)
(JSON::RETURN-TYPE-OF-OBJECT-PATTERNP-WITH-VARS.PATVARS)
(JSON::RETURN-TYPE-OF-OBJECT-MEMBERS-PATTERNP-WITH-VARS.TRUE/FALSE)
(JSON::RETURN-TYPE-OF-OBJECT-MEMBERS-PATTERNP-WITH-VARS.PATVARS)
(JSON::RETURN-TYPE-OF-MEMBER-PATTERNP-WITH-VARS.TRUE/FALSE)
(JSON::RETURN-TYPE-OF-MEMBER-PATTERNP-WITH-VARS.PATVARS)
(JSON::VALUE-PATTERNP-WITH-VARS
   (399 46
        (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
   (314 29 (:DEFINITION SYMBOL-LISTP))
   (228 37
        (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
   (163 2
        (:DEFINITION JSON::VALUE-PATTERNP-WITH-VARS))
   (98 98 (:REWRITE DEFAULT-CDR))
   (81 1
       (:DEFINITION JSON::OBJECT-MEMBERS-PATTERNP-WITH-VARS))
   (81 1
       (:DEFINITION JSON::ARRAY-ELEMENTS-PATTERNP-WITH-VARS))
   (77 77 (:REWRITE DEFAULT-CAR))
   (64 8 (:REWRITE APPEND-TO-NIL))
   (55 55
       (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
   (55 5
       (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
   (54 8 (:DEFINITION BINARY-APPEND))
   (54 1
       (:DEFINITION JSON::MEMBER-PATTERNP-WITH-VARS))
   (52 14 (:DEFINITION TRUE-LISTP))
   (39 4 (:DEFINITION RATIONAL-LISTP))
   (29 6
       (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
   (14 14 (:REWRITE DEFAULT-SYMBOL-NAME))
   (10 2 (:DEFINITION LEN))
   (8 8
      (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
   (6 6
      (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV))
   (4 2 (:REWRITE DEFAULT-+-2))
   (2 2 (:REWRITE DEFAULT-+-1)))
(JSON::VALUE-PATTERNP)
(JSON::BOOLEANP-OF-VALUE-PATTERNP)
(JSON::JSON-PATTERNP)
(JSON::BOOLEANP-OF-JSON-PATTERNP)
(JSON::ARRAY-PATTERNP)
(JSON::BOOLEANP-OF-ARRAY-PATTERNP)
(JSON::ARRAY-ELEMENTS-PATTERNP)
(JSON::BOOLEANP-OF-ARRAY-ELEMENTS-PATTERNP)
(JSON::OBJECT-PATTERNP)
(JSON::BOOLEANP-OF-OBJECT-PATTERNP)
(JSON::OBJECT-MEMBERS-PATTERNP)
(JSON::BOOLEANP-OF-OBJECT-MEMBERS-PATTERNP)
(JSON::MEMBER-PATTERNP)
(JSON::BOOLEANP-OF-MEMBER-PATTERNP)
(JSON::STRING-PATTERNP)
(JSON::BOOLEANP-OF-STRING-PATTERNP)
(JSON::NUMBER-PATTERNP)
(JSON::BOOLEANP-OF-NUMBER-PATTERNP)
(JSON::VALUE-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-VALUE-PATTERNP-DUPS-OK)
(JSON::ARRAY-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-ARRAY-PATTERNP-DUPS-OK)
(JSON::ARRAY-ELEMENTS-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-ARRAY-ELEMENTS-PATTERNP-DUPS-OK)
(JSON::OBJECT-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-OBJECT-PATTERNP-DUPS-OK)
(JSON::OBJECT-MEMBERS-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-OBJECT-MEMBERS-PATTERNP-DUPS-OK)
(JSON::MEMBER-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-MEMBER-PATTERNP-DUPS-OK)
(JSON::STRING-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-STRING-PATTERNP-DUPS-OK)
(JSON::NUMBER-PATTERNP-DUPS-OK)
(JSON::BOOLEANP-OF-NUMBER-PATTERNP-DUPS-OK)
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--STRING)
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--STRING.MATCH-REQTS
     (2 1 (:DEFINITION TRUE-LISTP))
     (1 1 (:REWRITE DEFAULT-SYMBOL-NAME))
     (1 1 (:REWRITE DEFAULT-CDR)))
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--STRING.VAR-BINDINGS
     (2 1 (:DEFINITION TRUE-LISTP))
     (1 1 (:REWRITE DEFAULT-SYMBOL-NAME))
     (1 1 (:REWRITE DEFAULT-CDR)))
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--NUMBER)
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--NUMBER.MATCH-REQTS
     (2 1 (:DEFINITION TRUE-LISTP))
     (1 1 (:REWRITE DEFAULT-SYMBOL-NAME))
     (1 1 (:REWRITE DEFAULT-CDR)))
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--NUMBER.VAR-BINDINGS
     (2 1 (:DEFINITION TRUE-LISTP))
     (1 1 (:REWRITE DEFAULT-SYMBOL-NAME))
     (1 1 (:REWRITE DEFAULT-CDR)))
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--MEMBER-NAME)
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--MEMBER-NAME.MATCH-REQTS
     (2 1 (:DEFINITION TRUE-LISTP))
     (1 1 (:REWRITE DEFAULT-SYMBOL-NAME))
     (1 1 (:REWRITE DEFAULT-CDR)))
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--MEMBER-NAME.VAR-BINDINGS
     (2 1 (:DEFINITION TRUE-LISTP))
     (1 1 (:REWRITE DEFAULT-SYMBOL-NAME))
     (1 1 (:REWRITE DEFAULT-CDR)))
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--VALUE
  (1265 424 (:REWRITE DEFAULT-+-2))
  (916 94
       (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
  (916 94
       (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
  (808 51 (:DEFINITION RATIONAL-LISTP))
  (808 51 (:DEFINITION INTEGER-LISTP))
  (722 424 (:REWRITE DEFAULT-+-1))
  (588 42 (:DEFINITION LENGTH))
  (520 92
       (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
  (520 92
       (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
  (484 358 (:REWRITE DEFAULT-CDR))
  (420 84 (:REWRITE COMMUTATIVITY-OF-+))
  (336 84 (:DEFINITION INTEGER-ABS))
  (260 260 (:REWRITE DEFAULT-CAR))
  (258 148 (:REWRITE DEFAULT-<-1))
  (204 148 (:REWRITE DEFAULT-<-2))
  (126 126
       (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
  (126 84 (:REWRITE STR::CONSP-OF-EXPLODE))
  (124 124
       (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
  (124 124
       (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
  (94 12
      (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (84 84 (:REWRITE DEFAULT-UNARY-MINUS))
  (84 42
      (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
  (80 6 (:DEFINITION SYMBOL-LISTP))
  (42 42
      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
  (42 42 (:REWRITE DEFAULT-REALPART))
  (42 42 (:REWRITE DEFAULT-NUMERATOR))
  (42 42 (:REWRITE DEFAULT-IMAGPART))
  (42 42 (:REWRITE DEFAULT-DENOMINATOR))
  (30 15
      (:TYPE-PRESCRIPTION TRUE-LISTP-APPEND))
  (26 8
      (:LINEAR ACL2-COUNT-OF-CONSP-POSITIVE))
  (16 8
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (15 15 (:TYPE-PRESCRIPTION BINARY-APPEND))
  (12 12
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (4 4 (:REWRITE DEFAULT-SYMBOL-NAME))
  (4 4
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV)))
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--RECUR-FLAG
  (1357 456 (:REWRITE DEFAULT-+-2))
  (932 98
       (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
  (916 94
       (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
  (818 53 (:DEFINITION RATIONAL-LISTP))
  (808 51 (:DEFINITION INTEGER-LISTP))
  (778 456 (:REWRITE DEFAULT-+-1))
  (644 46 (:DEFINITION LENGTH))
  (532 386 (:REWRITE DEFAULT-CDR))
  (520 92
       (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
  (520 92
       (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
  (460 92 (:REWRITE COMMUTATIVITY-OF-+))
  (368 92 (:DEFINITION INTEGER-ABS))
  (317 297 (:REWRITE DEFAULT-CAR))
  (279 159 (:REWRITE DEFAULT-<-1))
  (242 159 (:REWRITE DEFAULT-<-2))
  (202 1 (:DEFINITION O-P))
  (188 24
       (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (160 12 (:DEFINITION SYMBOL-LISTP))
  (138 138
       (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
  (138 92 (:REWRITE STR::CONSP-OF-EXPLODE))
  (126 126
       (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
  (124 124
       (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
  (98 4 (:REWRITE DEFAULT-SYMBOL-NAME))
  (97 1 (:DEFINITION O<))
  (92 92 (:REWRITE DEFAULT-UNARY-MINUS))
  (92 46
      (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
  (88 88
      (:TYPE-PRESCRIPTION TWO-NATS-MEASURE))
  (76 8 (:DEFINITION O-FIRST-EXPT))
  (53 17 (:DEFINITION O-FINP))
  (46 46
      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
  (46 46 (:REWRITE DEFAULT-REALPART))
  (46 46 (:REWRITE DEFAULT-NUMERATOR))
  (46 46 (:REWRITE DEFAULT-IMAGPART))
  (46 46 (:REWRITE DEFAULT-DENOMINATOR))
  (32 16
      (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (28 5 (:DEFINITION O-FIRST-COEFF))
  (26 8
      (:LINEAR ACL2-COUNT-OF-CONSP-POSITIVE))
  (25 5
      (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
  (24 24
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (17 2
      (:REWRITE ACL2-NUMBERP-OF-CAR-WHEN-ACL2-NUMBER-LISTP))
  (16 4 (:DEFINITION O-RST))
  (14 1 (:DEFINITION ACL2-NUMBER-LISTP))
  (9 9
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
  (4 4
     (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV))
  (3 1 (:DEFINITION POSP))
  (1 1
     (:REWRITE ACL2-NUMBER-LISTP-WHEN-NOT-CONSP)))
(FLAG::FLAG-EQUIV-LEMMA)
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--RECUR-FLAG-EQUIVALENCES)
(JSON::FLAG-LEMMA-FOR-RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--VALUE.MATCH-REQTS
  (1316 168
        (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
  (1120 84 (:DEFINITION SYMBOL-LISTP))
  (712 712 (:REWRITE DEFAULT-CDR))
  (527 527 (:REWRITE DEFAULT-CAR))
  (224 112
       (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
  (168 168
       (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
  (72 36 (:REWRITE DEFAULT-+-2))
  (63 63 (:REWRITE DEFAULT-SYMBOL-NAME))
  (60 20 (:DEFINITION BINARY-APPEND))
  (45 45
      (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV))
  (36 36 (:REWRITE DEFAULT-+-1)))
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--VALUE.MATCH-REQTS)
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--VALUE.VAR-BINDINGS)
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--ARRAY-ELEMENTS.MATCH-REQTS)
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--ARRAY-ELEMENTS.VAR-BINDINGS)
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--OBJECT-MEMBERS.MATCH-REQTS)
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--OBJECT-MEMBERS.VAR-BINDINGS)
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--MEMBER.MATCH-REQTS)
(JSON::RETURN-TYPE-OF-JPAT-COLLECT-MATCH-REQUIREMENTS--MEMBER.VAR-BINDINGS)
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--VALUE
 (2154 210
       (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
 (1533 155 (:DEFINITION SYMBOL-LISTP))
 (1360 1360 (:REWRITE DEFAULT-CAR))
 (1269 1269 (:REWRITE DEFAULT-CDR))
 (1076 199
       (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
 (612 74
      (:REWRITE RATIONALP-OF-CAR-WHEN-RATIONAL-LISTP))
 (608 76 (:REWRITE APPEND-TO-NIL))
 (506 74 (:DEFINITION BINARY-APPEND))
 (397 56 (:DEFINITION RATIONAL-LISTP))
 (297 38
      (:REWRITE TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (290 290
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
 (257 13 (:DEFINITION TRUE-LIST-LISTP))
 (220 51
      (:REWRITE RATIONAL-LISTP-OF-CDR-WHEN-RATIONAL-LISTP))
 (212
     212
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (125 125
      (:REWRITE CAR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-EQUIV))
 (97 1
     (:DEFINITION JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--MEMBER))
 (88 88
     (:REWRITE
          CDR-OF-SYMBOL-LIST-FIX-X-NORMALIZE-CONST-UNDER-SYMBOL-LIST-EQUIV))
 (85 85
     (:REWRITE RATIONAL-LISTP-WHEN-NOT-CONSP))
 (53 1
     (:DEFINITION JSON::JPAT-COLLECT-MATCH-REQUIREMENTS--VALUE))
 (34 17 (:REWRITE DEFAULT-+-2))
 (17 17 (:REWRITE DEFAULT-+-1))
 (15 2
     (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
 (14 14
     (:REWRITE TRUE-LIST-LISTP-WHEN-NOT-CONSP))
 (11 1 (:DEFINITION INTEGER-LISTP))
 (2 2
    (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
 (2 1
    (:REWRITE TRUE-LIST-LISTP-OF-CDR-WHEN-TRUE-LIST-LISTP))
 (2 1
    (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP)))
(JSON::ADD-MATCH-CHECK-TO-VAR-BIND-FORMS
 (125 11
      (:REWRITE TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (107 6 (:DEFINITION TRUE-LIST-LISTP))
 (34 7
     (:REWRITE TRUE-LIST-LISTP-OF-CDR-WHEN-TRUE-LIST-LISTP))
 (26 26 (:REWRITE DEFAULT-CDR))
 (24 24 (:TYPE-PRESCRIPTION TRUE-LISTP))
 (19 19 (:REWRITE DEFAULT-CAR))
 (15 3 (:DEFINITION LEN))
 (12 12
     (:REWRITE TRUE-LIST-LISTP-WHEN-NOT-CONSP))
 (6 3 (:REWRITE DEFAULT-+-2))
 (3 3 (:REWRITE DEFAULT-+-1))
 (2 2
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV)))
(JSON::DOUBLET-LISTP-OF-ADD-MATCH-CHECK-TO-VAR-BIND-FORMS
 (189 14
      (:REWRITE TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (147 7 (:DEFINITION TRUE-LIST-LISTP))
 (49 14 (:DEFINITION TRUE-LISTP))
 (42 41 (:REWRITE DEFAULT-CDR))
 (31 29 (:REWRITE DEFAULT-CAR))
 (28 28 (:TYPE-PRESCRIPTION TRUE-LISTP))
 (22 22 (:TYPE-PRESCRIPTION LEN))
 (16 8 (:REWRITE DEFAULT-+-2))
 (14 14
     (:REWRITE TRUE-LIST-LISTP-WHEN-NOT-CONSP))
 (14 7
     (:REWRITE TRUE-LIST-LISTP-OF-CDR-WHEN-TRUE-LIST-LISTP))
 (8 8 (:REWRITE DEFAULT-+-1))
 (3 3
    (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV)))
(JSON::JPAT-COLLECT-MATCH-REQUIREMENTS)
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS.MATCH-REQTS
     (2 2 (:REWRITE DEFAULT-CDR)))
(JSON::TRUE-LISTP-OF-JPAT-COLLECT-MATCH-REQUIREMENTS.VAR-BINDINGS
     (2 1 (:DEFINITION TRUE-LISTP))
     (1 1 (:REWRITE DEFAULT-CDR)))
