# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../Makefile-generic


# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

generic-theories.cert: generic-theories.lisp
 
generic-theory-alternative-induction-mult.cert: generic-theory-alternative-induction-mult.lisp
generic-theory-alternative-induction-mult.cert: ../../../../arithmetic-3/bind-free/top.cert
generic-theory-alternative-induction-mult.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
generic-theory-alternative-induction-mult.cert: generic-theories.cert
 
generic-theory-alternative-induction-sum.cert: generic-theory-alternative-induction-sum.lisp
generic-theory-alternative-induction-sum.cert: ../../../../arithmetic-3/bind-free/top.cert
generic-theory-alternative-induction-sum.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
generic-theory-alternative-induction-sum.cert: generic-theories.cert
 
generic-theory-loop-invariant-mult.cert: generic-theory-loop-invariant-mult.lisp
generic-theory-loop-invariant-mult.cert: ../../../../arithmetic-3/bind-free/top.cert
generic-theory-loop-invariant-mult.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
generic-theory-loop-invariant-mult.cert: generic-theories.cert
 
generic-theory-loop-invariant-sum.cert: generic-theory-loop-invariant-sum.lisp
generic-theory-loop-invariant-sum.cert: ../../../../arithmetic-3/bind-free/top.cert
generic-theory-loop-invariant-sum.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
generic-theory-loop-invariant-sum.cert: generic-theories.cert
 
generic-theory-tail-recursion-mult.cert: generic-theory-tail-recursion-mult.lisp
generic-theory-tail-recursion-mult.cert: ../../../../arithmetic-3/bind-free/top.cert
generic-theory-tail-recursion-mult.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
generic-theory-tail-recursion-mult.cert: generic-theories.cert
 
generic-theory-tail-recursion-sum.cert: generic-theory-tail-recursion-sum.lisp
generic-theory-tail-recursion-sum.cert: ../../../../arithmetic-3/bind-free/top.cert
generic-theory-tail-recursion-sum.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
generic-theory-tail-recursion-sum.cert: generic-theories.cert
 
proof-by-generalization-mult.cert: proof-by-generalization-mult.lisp
proof-by-generalization-mult.cert: ../../../../arithmetic-3/bind-free/top.cert
proof-by-generalization-mult.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
 
proof-by-generalization-sum.cert: proof-by-generalization-sum.lisp
proof-by-generalization-sum.cert: ../../../../arithmetic-3/bind-free/top.cert
proof-by-generalization-sum.cert: ../../../../arithmetic-3/floor-mod/floor-mod.cert
proof-by-generalization-sum.cert: generic-theories.cert
