#|-*-Lisp-*-=================================================================|#
#|                                                                           |#
#| coi: Computational Object Inference                                       |#
#|                                                                           |#
#|===========================================================================|#

include ../../../Makefile-generic
BOOKS = compiler-proof compiler zero
# The following certifies, but if so then it takes a long time:
# complex

-include Makefile-deps
