include ../../Makefile-generic
ACL2 = ../../../saved_acl2
# Dependencies:

fact.cert: fact.lisp

ac-example.cert: ac-example.lisp

insertion-sort.cert: insertion-sort.lisp

tree.cert: tree.lisp

adder.cert: adder.lisp 

compiler.cert: compiler.lisp 
