ACL2 ?= ../../../../saved_acl2
include ../../../Makefile-generic
-include Makefile-deps

BOOKS := apprentice-state demo idemo infinite-fair-schedule isort \
	jvm-fact-setup m5 partial perm universal-never-returns \
	universal utilities
# Add the following to the line above if desired (it takes about a half hour to
# an hour to certify in April 2008, depending on the machine and the Lisp):
#	apprentice
