(FUTER::TERMINOP)
(FUTER::UNO)
(FUTER::*)
(FUTER::TERMINO->ORDINAL)
(FUTER::<)
(FUTER::BOOLEANP-TERMINOP)
(FUTER::TERMINOP-*
 (3 3 (:REWRITE DEFAULT-<-2))
 (3 3 (:REWRITE DEFAULT-<-1))
 (1 1 (:REWRITE DEFAULT-+-2))
 (1 1 (:REWRITE DEFAULT-+-1))
 )
(FUTER::TERMINOP-UNO)
(FUTER::|a * b = b * a|)
(FUTER::|(a * b) * c = a * (b * c)|)
(FUTER::|1 * a = a|
 (1 1 (:REWRITE DEFAULT-<-2))
 (1 1 (:REWRITE DEFAULT-<-1))
 )
(FUTER::BUENA-FUNDAMENTACION-<
 (5 5 (:REWRITE DEFAULT-<-2))
 (5 5 (:REWRITE DEFAULT-<-1))
 (3 3 (:REWRITE DEFAULT-+-2))
 (3 3 (:REWRITE DEFAULT-+-1))
 )
(FUTER::|~(termino->ordinal(a) = 0)|)
(FUTER::|(termino->ordinal(a) >O 0)|
 (2 2 (:REWRITE DEFAULT-<-2))
 (2 2 (:REWRITE DEFAULT-<-1))
 (1 1 (:REWRITE DEFAULT-+-2))
 (1 1 (:REWRITE DEFAULT-+-1))
 )
(FUTER::|~(a < a)|)
(FUTER::|a < b => ~(b < a)|)
(FUTER::|a < b & b < c => a < c|)
(FUTER::|a < b or b < a or a = b|
 (4 4 (:REWRITE DEFAULT-<-2))
 (4 4 (:REWRITE DEFAULT-<-1))
 )
(FUTER::|a < b => a * c < b * c|)
(FUTER::|b < c => a * b < a * c|)
(FUTER::|a * 1 = a|)
(FUTER::|a * (b * c) = b * (a * c)|)
