(XDOC::FIX-REDUNDANT-ACL2-PARENTS
 (1 1 (:TYPE-PRESCRIPTION XDOC::FIX-REDUNDANT-ACL2-PARENTS))
 )
(XDOC::FIND-LONG-TOPICS
 (12 6 (:TYPE-PRESCRIPTION ASSOC-EQUAL-CONSP-OR-NIL))
 (6 6 (:TYPE-PRESCRIPTION ALISTP))
 )
