include ../../../../../../../../Makefile-generic


# Dependencies:

ma128serial-ma128.cert: ma128serial-ma128.lisp
ma128serial-ma128.cert: ma128serial.cert

ma128serial.cert: ma128serial.lisp
ma128serial.cert: serial.cert
ma128serial.cert: ../../../top/nth-thms.cert
ma128serial.cert: ../../../top/meta.cert
ma128serial.cert: ../../../top/defun-weak-sk.cert
ma128serial.cert: ../../top/det-encap-wfbisim.cert
ma128serial.cert: ../top/ma128.cert

serial.cert: serial.lisp
serial.cert: ../../../top/ihs.cert
