include ../../../../../../../Makefile-generic

ACL2 = ../../../../../../../../saved_acl2

# Dependencies:

det-encap-wfbisim.cert: det-encap-wfbisim.lisp
det-encap-wfbisim.cert: ../../top/defun-weak-sk.cert
det-encap-wfbisim.cert: ../../../../../../../ordinals/e0-ordinal.cert

det-macros.cert: det-macros.lisp

inst.cert: inst.lisp
