
all:

clean:

veryclean: clean
	rm -f *.cert *.*x64fsl *.port *.log *.lisp *.m *.types.h *.decs.h *.pc *.out *.ctos.cpp *.i imul/*.pc imul/*.cert imul/*.*x64fsl imul/*.port imul/*.log imul/imul.lisp imul/imul.ast.lisp imul/*.m imul/*.types.h imul/*.decs.h imul/*.out imul/*.ctos.cpp imul/*.i
