
all:

clean:

veryclean: clean
	rm -f *.cert *.cert.time *.fasl *.ast.lsp *.ast.pp *.*x64fsl *.port *.log *.lisp *.m *.types.h *.decs.h *.pc *.out *.ctos.cpp *.i imul/*.pc imul/*.cert imul/*.*x64fsl imul/*.port imul/*.log imul/imul.lisp imul/imul.ast.lsp imul/*.fasl imul/*.cert.time imul/*.m imul/*.types.h imul/*.decs.h imul/*.out imul/*.ctos.cpp imul/*.i
