(DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF
     (413 141
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (199 199
          (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (193 22 (:REWRITE SUBSETP-MEMBER . 1))
     (184 184
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (184 19 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (141 15 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (114 15 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (92 92 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (92 92 (:REWRITE CONSP-BY-LEN))
     (92 23
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (70 70 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (46 46
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (46 46 (:TYPE-PRESCRIPTION ALISTP))
     (41 41 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (38 19
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (32 4 (:REWRITE ALISTP-OF-CDR))
     (30 30 (:REWRITE DEFAULT-CDR))
     (25 25
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (24 24 (:REWRITE SUBSETP-MEMBER . 4))
     (24 24 (:REWRITE INTERSECTP-MEMBER . 3))
     (24 24 (:REWRITE INTERSECTP-MEMBER . 2))
     (23 23
         (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (23 23 (:REWRITE ALISTP-WHEN-ATOM))
     (22 22 (:REWRITE SUBSETP-MEMBER . 2))
     (20 20 (:REWRITE SUBSETP-TRANS2))
     (20 20 (:REWRITE SUBSETP-TRANS))
     (10 1 (:REWRITE SUBSETP-OF-CONS))
     (8 8 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (1 1
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY)))
(DEPGRAPH::TOPOLOGICALLY-ORDERED-P-AUX)
(DEPGRAPH::TOPOLOGICALLY-ORDERED-P)
(DEPGRAPH::DEPENDENCY-CHAIN-P
     (50 3 (:REWRITE SUBSETP-CAR-MEMBER))
     (48 4 (:REWRITE DEFAULT-CDR))
     (42 15
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (26 4 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (25 3 (:REWRITE MEMBER-WHEN-ATOM))
     (18 18
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (18 3 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (17 1
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (16 6 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (11 11 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (11 11 (:REWRITE CONSP-BY-LEN))
     (8 8 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (4 4 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (4 4 (:REWRITE SUBSETP-TRANS2))
     (4 4 (:REWRITE SUBSETP-TRANS))
     (3 3 (:REWRITE SUBSETP-MEMBER . 4))
     (3 3 (:REWRITE SUBSETP-MEMBER . 3))
     (3 3 (:REWRITE SUBSETP-MEMBER . 2))
     (3 3 (:REWRITE SUBSETP-MEMBER . 1))
     (3 3
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (3 3 (:REWRITE INTERSECTP-MEMBER . 3))
     (3 3 (:REWRITE INTERSECTP-MEMBER . 2))
     (3 3
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (3 3 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (2 2 (:REWRITE DEFAULT-CAR))
     (2 2 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(DEPGRAPH::TOPOSORT-MEASURE)
(DEPGRAPH::LEN-SD-CONS-RIGHT-1
     (166 60
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (134 16 (:REWRITE LEN-WHEN-ATOM))
     (117 42 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (88 88
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (81 9
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (75 32
         (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (74 3 (:REWRITE SUBSETP-OF-CONS))
     (68 68
         (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (46 46 (:REWRITE SUBSETP-TRANS2))
     (46 46 (:REWRITE SUBSETP-TRANS))
     (46 46
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (46 46
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (46 46 (:LINEAR LEN-WHEN-PREFIXP))
     (44 44 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (44 44 (:REWRITE CONSP-BY-LEN))
     (37 7 (:REWRITE MEMBER-WHEN-ATOM))
     (23 23 (:LINEAR INDEX-OF-<-LEN))
     (13 13 (:REWRITE SUBSETP-MEMBER . 2))
     (13 13
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (9 9 (:REWRITE SUBSETP-MEMBER . 4))
     (9 9 (:REWRITE SUBSETP-MEMBER . 3))
     (9 9 (:REWRITE INTERSECTP-MEMBER . 3))
     (9 9 (:REWRITE INTERSECTP-MEMBER . 2))
     (6 6 (:REWRITE DEFAULT-CDR))
     (6 6 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::LEN-SD-CONS-RIGHT-2
     (166 60
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (134 16 (:REWRITE LEN-WHEN-ATOM))
     (117 42 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (88 88
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (81 9
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (75 32
         (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (74 3 (:REWRITE SUBSETP-OF-CONS))
     (68 68
         (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (46 46 (:REWRITE SUBSETP-TRANS2))
     (46 46 (:REWRITE SUBSETP-TRANS))
     (44 44 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (44 44 (:REWRITE CONSP-BY-LEN))
     (37 7 (:REWRITE MEMBER-WHEN-ATOM))
     (22 22
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (22 22
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (22 22 (:LINEAR LEN-WHEN-PREFIXP))
     (16 8 (:REWRITE DEFAULT-<-2))
     (16 8 (:REWRITE DEFAULT-<-1))
     (16 8 (:REWRITE DEFAULT-+-2))
     (13 13
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (12 12 (:REWRITE SUBSETP-MEMBER . 2))
     (12 12 (:REWRITE SUBSETP-MEMBER . 1))
     (11 11 (:LINEAR INDEX-OF-<-LEN))
     (9 9 (:REWRITE SUBSETP-MEMBER . 4))
     (9 9 (:REWRITE INTERSECTP-MEMBER . 3))
     (9 9 (:REWRITE INTERSECTP-MEMBER . 2))
     (8 8 (:REWRITE DEFAULT-+-1))
     (7 7
        (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1))
     (6 6 (:REWRITE DEFAULT-CDR))
     (6 6 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::LEN-SD-CONS-RIGHT-3
     (707 193 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (575 30 (:REWRITE SUBSETP-OF-CONS))
     (526 76 (:REWRITE LEN-WHEN-ATOM))
     (450 450
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (298 146
          (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (238 238 (:REWRITE SUBSETP-TRANS2))
     (238 238 (:REWRITE SUBSETP-TRANS))
     (225 225 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (225 225 (:REWRITE CONSP-BY-LEN))
     (214 24
          (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (151 33 (:REWRITE MEMBER-WHEN-ATOM))
     (81 81
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (77 77 (:REWRITE SUBSETP-MEMBER . 2))
     (74 74
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (74 74
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (74 74 (:LINEAR LEN-WHEN-PREFIXP))
     (47 47 (:REWRITE SUBSETP-MEMBER . 4))
     (47 47 (:REWRITE INTERSECTP-MEMBER . 3))
     (47 47 (:REWRITE INTERSECTP-MEMBER . 2))
     (44 10
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (40 4 (:REWRITE LEN-WHEN-PREFIXP))
     (38 10
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (37 37 (:LINEAR INDEX-OF-<-LEN))
     (33 5 (:REWRITE LIST-EQUIV-WHEN-ATOM-RIGHT))
     (33 5 (:REWRITE LIST-EQUIV-WHEN-ATOM-LEFT))
     (32 4 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (32 4 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (30 30
         (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1))
     (29 16 (:REWRITE DEFAULT-+-2))
     (28 28 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (17 17 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (17 17 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (17 17
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (17 17
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (16 16 (:REWRITE DEFAULT-+-1))
     (15 15 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE SUBLISTP-COMPLETE))
     (8 4 (:REWRITE DEFAULT-<-2))
     (8 4 (:REWRITE DEFAULT-<-1))
     (2 2 (:REWRITE DEFAULT-CAR))
     (2 2 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(DEPGRAPH::EQUAL-OF-LEN-SD-CONS-RIGHT
     (431 16
          (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
     (413 164
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (350 120 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (270 270
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (241 32 (:REWRITE LEN-WHEN-ATOM))
     (160 17
          (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (135 135 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (135 135 (:REWRITE CONSP-BY-LEN))
     (128 128 (:REWRITE SUBSETP-TRANS2))
     (128 128 (:REWRITE SUBSETP-TRANS))
     (120 120
          (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (119 64
          (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (74 3 (:REWRITE SUBSETP-OF-CONS))
     (63 63
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (60 60
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (60 60
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (60 60 (:LINEAR LEN-WHEN-PREFIXP))
     (58 58 (:REWRITE SUBSETP-MEMBER . 2))
     (49 49 (:REWRITE SUBSETP-MEMBER . 4))
     (49 49 (:REWRITE INTERSECTP-MEMBER . 3))
     (49 49 (:REWRITE INTERSECTP-MEMBER . 2))
     (30 30 (:LINEAR INDEX-OF-<-LEN))
     (23 23 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (14 14 (:REWRITE DEFAULT-CDR)))
(DEPGRAPH::LEN-SD-CONS-RIGHT-STRONG
     (775 266
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (458 11 (:REWRITE LEN-WHEN-PREFIXP))
     (453 156 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (434 18
          (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
     (366 366
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (344 344
          (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (318 34
          (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (311 74 (:REWRITE LEN-WHEN-ATOM))
     (191 118
          (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (183 183 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (183 183 (:REWRITE CONSP-BY-LEN))
     (174 174 (:REWRITE SUBSETP-TRANS2))
     (174 174 (:REWRITE SUBSETP-TRANS))
     (101 101
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (96 19
         (:REWRITE LIST-EQUIV-WHEN-ATOM-RIGHT))
     (96 19 (:REWRITE LIST-EQUIV-WHEN-ATOM-LEFT))
     (91 11 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (91 11 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (85 85 (:REWRITE SUBSETP-MEMBER . 4))
     (85 85 (:REWRITE INTERSECTP-MEMBER . 3))
     (85 85 (:REWRITE INTERSECTP-MEMBER . 2))
     (80 80 (:REWRITE SUBSETP-MEMBER . 2))
     (76 76
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (76 76
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (76 76 (:LINEAR LEN-WHEN-PREFIXP))
     (74 3 (:REWRITE SUBSETP-OF-CONS))
     (40 40 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (38 38 (:LINEAR INDEX-OF-<-LEN))
     (30 6
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (30 6
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (25 25 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (25 25 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (25 25
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (25 25
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (22 11 (:REWRITE DEFAULT-<-2))
     (22 11 (:REWRITE DEFAULT-<-1))
     (17 17 (:REWRITE DEFAULT-CDR))
     (14 14 (:REWRITE SUBLISTP-COMPLETE))
     (4 2 (:REWRITE DEFAULT-+-2))
     (2 2 (:REWRITE DEFAULT-+-1)))
(DEPGRAPH::LEN-SD-CONS-RIGHT-WEAK
     (703 6
          (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (577 6 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (439 12
          (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (319 5
          (:REWRITE DEPGRAPH::EQUAL-OF-LEN-SD-CONS-RIGHT))
     (298 98
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (156 156
          (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (144 42 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (127 41 (:REWRITE SUBSETP-MEMBER . 1))
     (124 124
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (123 26 (:REWRITE MEMBER-WHEN-ATOM))
     (114 24 (:REWRITE LEN-WHEN-ATOM))
     (112 7
          (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
     (112 7
          (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
     (104 10
          (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (81 44
         (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (78 32 (:REWRITE SUBSETP-MEMBER . 3))
     (74 3 (:REWRITE SUBSETP-OF-CONS))
     (62 62 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (62 62 (:REWRITE CONSP-BY-LEN))
     (60 6 (:REWRITE LEN-WHEN-PREFIXP))
     (57 12
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (57 12
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (51 6 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (51 6 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (50 50 (:REWRITE SUBSETP-TRANS2))
     (50 50 (:REWRITE SUBSETP-TRANS))
     (46 46
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (41 41 (:REWRITE SUBSETP-MEMBER . 2))
     (35 10
         (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1))
     (32 32 (:REWRITE SUBSETP-MEMBER . 4))
     (32 32 (:REWRITE INTERSECTP-MEMBER . 3))
     (32 32 (:REWRITE INTERSECTP-MEMBER . 2))
     (30 30
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (30 30
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (30 30 (:LINEAR LEN-WHEN-PREFIXP))
     (24 24 (:TYPE-PRESCRIPTION PREFIXP))
     (15 15 (:LINEAR INDEX-OF-<-LEN))
     (12 12 (:TYPE-PRESCRIPTION SUBLISTP))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (12 6 (:REWRITE DEFAULT-<-2))
     (12 6 (:REWRITE DEFAULT-<-1))
     (10 10 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (6 6 (:REWRITE SUBLISTP-COMPLETE))
     (5 5 (:REWRITE SUBSETP-REFL))
     (4 4 (:REWRITE DEFAULT-CDR)))
(DEPGRAPH::LEN-SD-WHEN-SUBSET
     (408 126
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (235 55 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (228 228
          (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (182 36 (:REWRITE LEN-WHEN-ATOM))
     (144 144
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (123 70
          (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (93 9
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (80 8 (:REWRITE LEN-WHEN-PREFIXP))
     (75 16
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (75 16
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (74 59 (:REWRITE SUBSETP-TRANS))
     (74 3 (:REWRITE SUBSETP-OF-CONS))
     (72 72 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (72 72 (:REWRITE CONSP-BY-LEN))
     (67 8 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (67 8 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (48 48
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (48 48
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (48 48 (:LINEAR LEN-WHEN-PREFIXP))
     (24 24 (:LINEAR INDEX-OF-<-LEN))
     (17 17 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (17 17 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (17 17
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (17 17
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (16 8 (:REWRITE DEFAULT-<-2))
     (16 8 (:REWRITE DEFAULT-<-1))
     (13 3 (:REWRITE MEMBER-WHEN-ATOM))
     (11 7 (:REWRITE SUBSETP-MEMBER . 2))
     (9 9 (:REWRITE SUBLISTP-COMPLETE))
     (8 8
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (8 1 (:REWRITE LIST-EQUIV-WHEN-ATOM-RIGHT))
     (8 1 (:REWRITE LIST-EQUIV-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE SUBSETP-MEMBER . 1))
     (6 6 (:REWRITE DEFAULT-CDR))
     (6 6 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (4 4 (:REWRITE INTERSECTP-MEMBER . 3))
     (4 4 (:REWRITE INTERSECTP-MEMBER . 2))
     (3 3 (:REWRITE SUBSETP-MEMBER . 3)))
(DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET
     (3252 834 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (2886 137 (:REWRITE SUBSETP-OF-CONS))
     (1860 1860
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (1604 216 (:REWRITE LEN-WHEN-ATOM))
     (1404 1024 (:REWRITE SUBSETP-TRANS))
     (1124 19
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
     (982 19
          (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
     (930 930 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (930 930 (:REWRITE CONSP-BY-LEN))
     (869 410
          (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (564 53
          (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (523 100 (:REWRITE MEMBER-WHEN-ATOM))
     (349 349
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (150 150 (:REWRITE INTERSECTP-MEMBER . 3))
     (150 150 (:REWRITE INTERSECTP-MEMBER . 2))
     (142 142
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (142 142
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (142 142 (:LINEAR LEN-WHEN-PREFIXP))
     (79 18
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (71 71 (:LINEAR INDEX-OF-<-LEN))
     (70 7 (:REWRITE LEN-WHEN-PREFIXP))
     (67 18
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (56 7 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (56 7 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (47 47 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (33 19 (:REWRITE DEFAULT-+-2))
     (24 24 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (24 24 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (24 24
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (24 24
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (21 21 (:REWRITE DEFAULT-CDR))
     (19 19 (:REWRITE DEFAULT-+-1))
     (14 7 (:REWRITE DEFAULT-<-2))
     (12 7 (:REWRITE DEFAULT-<-1))
     (11 11 (:REWRITE SUBLISTP-COMPLETE))
     (4 4 (:REWRITE DEFAULT-CAR))
     (4 4 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (2 2 (:REWRITE LIST-EQUIV-WHEN-ATOM-RIGHT))
     (2 2 (:REWRITE LIST-EQUIV-WHEN-ATOM-LEFT)))
(DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2
     (49 3 (:REWRITE SUBSETP-MEMBER . 1))
     (46 2 (:REWRITE SUBSETP-CONS-2))
     (44 4
         (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
     (30 10 (:REWRITE SUBSETP-TRANS2))
     (29 9 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (25 1 (:REWRITE SUBSETP-MEMBER . 3))
     (24 9
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (21 1 (:REWRITE SUBSETP-OF-CONS))
     (19 9 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (16 2 (:REWRITE LEN-WHEN-ATOM))
     (14 14
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (12 1
         (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1))
     (10 10 (:REWRITE SUBSETP-TRANS))
     (9 4
        (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (8 8
        (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (7 7 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (7 7 (:REWRITE CONSP-BY-LEN))
     (3 3 (:REWRITE SUBSETP-MEMBER . 2))
     (3 3
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (1 1 (:REWRITE SUBSETP-MEMBER . 4))
     (1 1 (:REWRITE MEMBER-OF-CONS))
     (1 1 (:REWRITE INTERSECTP-MEMBER . 3))
     (1 1 (:REWRITE INTERSECTP-MEMBER . 2)))
(DEPGRAPH::TOPOSORT-AUX
     (366 114
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (316 6
          (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (244 6 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (203 73 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (201 27 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (193 193
          (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (169 13 (:REWRITE SUBSETP-CAR-MEMBER))
     (160 12
          (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (114 114
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (106 32 (:REWRITE LEN-WHEN-ATOM))
     (98 27 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (78 10
         (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
     (77 11 (:REWRITE MEMBER-WHEN-ATOM))
     (62 62 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (62 62 (:REWRITE CONSP-BY-LEN))
     (60 6 (:REWRITE LEN-WHEN-PREFIXP))
     (48 12
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (42 6 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (40 20 (:REWRITE DEFAULT-<-1))
     (33 12 (:REWRITE SUBSETP-MEMBER . 1))
     (32 32 (:REWRITE SUBSETP-TRANS2))
     (32 32 (:REWRITE SUBSETP-TRANS))
     (30 5 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (28 28
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (28 28
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (28 28 (:LINEAR LEN-WHEN-PREFIXP))
     (28 10
         (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (26 20 (:REWRITE DEFAULT-<-2))
     (24 24 (:TYPE-PRESCRIPTION PREFIXP))
     (19 19 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (19 1 (:REWRITE SUBSETP-CONS-2))
     (16 16
         (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (15 15 (:REWRITE DEFAULT-CAR))
     (15 15 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (14 14 (:LINEAR INDEX-OF-<-LEN))
     (13 13 (:REWRITE SUBSETP-MEMBER . 4))
     (13 13
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (13 13 (:REWRITE INTERSECTP-MEMBER . 3))
     (13 13 (:REWRITE INTERSECTP-MEMBER . 2))
     (12 12 (:TYPE-PRESCRIPTION SUBLISTP))
     (12 12 (:REWRITE SUBSETP-MEMBER . 2))
     (12 12
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (12 12
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (6 6 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (6 6 (:REWRITE SUBLISTP-COMPLETE))
     (5 5
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (1 1
        (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1)))
(DEPGRAPH::L0 (79275 105
                     (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
              (77521 105 (:REWRITE SUBLISTP-WHEN-PREFIXP))
              (75557 210
                     (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
              (37366 1467 (:REWRITE SUBSETP-CAR-MEMBER))
              (33273 8041
                     (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (32010 434
                     (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
              (30242 4525 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (24510 556
                     (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
              (24451 4525 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
              (17481 4511 (:REWRITE ALIST-KEYS-WHEN-ATOM))
              (16116 16116
                     (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
              (15535 250 (:REWRITE SUBSETP-OF-CONS))
              (15142 139
                     (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WEAK))
              (13139 1351
                     (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
              (11170 139
                     (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
              (11011 139
                     (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
              (7917 409
                    (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1))
              (6072 6072
                    (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (5656 884 (:REWRITE LEN-WHEN-ATOM))
              (5201 5201 (:REWRITE SUBSETP-TRANS2))
              (5201 5201 (:REWRITE SUBSETP-TRANS))
              (3409 3409 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (3409 3409 (:REWRITE CONSP-BY-LEN))
              (3128 3128
                    (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
              (3055 1351
                    (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
              (2954 422 (:REWRITE MEMBER-WHEN-ATOM))
              (2686 151 (:REWRITE MEMBER-OF-CONS))
              (1970 53
                    (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2))
              (1511 1511
                    (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (1490 1490 (:REWRITE SUBSETP-MEMBER . 2))
              (1050 105 (:REWRITE LEN-WHEN-PREFIXP))
              (967 53
                   (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
              (963 210
                   (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
              (931 931 (:REWRITE SUBSETP-MEMBER . 4))
              (931 931 (:REWRITE INTERSECTP-MEMBER . 3))
              (931 931 (:REWRITE INTERSECTP-MEMBER . 2))
              (902 902
                   (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
              (902 902
                   (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
              (902 902 (:LINEAR LEN-WHEN-PREFIXP))
              (858 105 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
              (852 142
                   (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
              (844 423 (:REWRITE DEFAULT-<-1))
              (590 590
                   (:LINEAR DEPGRAPH::LEN-SD-WHEN-SUBSET))
              (581 210
                   (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
              (526 423 (:REWRITE DEFAULT-<-2))
              (476 105 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
              (451 451 (:LINEAR INDEX-OF-<-LEN))
              (434 434
                   (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2))
              (420 420 (:TYPE-PRESCRIPTION PREFIXP))
              (418 38 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
              (318 318 (:REWRITE DEFAULT-CAR))
              (318 318 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (247 247 (:REWRITE CONSP-OF-CDR-BY-LEN))
              (210 210 (:TYPE-PRESCRIPTION SUBLISTP))
              (210 210 (:REWRITE PREFIXP-TRANSITIVE . 2))
              (210 210 (:REWRITE PREFIXP-TRANSITIVE . 1))
              (210 210
                   (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
              (210 210
                   (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
              (152 152 (:REWRITE CONSP-OF-CDDR-BY-LEN))
              (142 142
                   (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
              (105 105 (:REWRITE SUBLISTP-COMPLETE))
              (57 31 (:REWRITE DEFAULT-+-2))
              (31 31 (:REWRITE DEFAULT-+-1)))
(DEPGRAPH::L1 (1425 3 (:DEFINITION DEPGRAPH::TOPOSORT-AUX))
              (738 3 (:REWRITE O<-OF-TWO-NATS-MEASURE))
              (474 6
                   (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
              (402 6
                   (:DEFINITION DEPGRAPH::TOPOSORT-MEASURE))
              (378 6 (:REWRITE SUBLISTP-WHEN-PREFIXP))
              (281 86
                   (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (270 12
                   (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
              (204 204 (:TYPE-PRESCRIPTION LEN))
              (168 3
                   (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1))
              (150 18 (:REWRITE DEFAULT-CDR))
              (141 27
                   (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
              (140 50 (:REWRITE ALIST-KEYS-WHEN-ATOM))
              (114 3 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
              (108 18 (:DEFINITION NFIX))
              (105 3
                   (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
              (102 24 (:REWRITE LEN-WHEN-ATOM))
              (102 6 (:REWRITE SUBSETP-CAR-MEMBER))
              (98 26 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
              (96 6 (:REWRITE SUBSETP-CONS-2))
              (78 78
                  (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (74 26 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (72 72
                  (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
              (60 6 (:REWRITE LEN-WHEN-PREFIXP))
              (60 6 (:REWRITE ALIST-KEYS-OF-CONS))
              (51 12
                  (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
              (48 24 (:REWRITE DEFAULT-<-1))
              (48 6 (:DEFINITION HONS-GET))
              (45 27
                  (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
              (45 6 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
              (42 42 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (42 42 (:REWRITE CONSP-BY-LEN))
              (39 3
                  (:REWRITE DEPGRAPH::LEN-SD-WHEN-SUBSET))
              (36 36
                  (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
              (36 36
                  (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
              (36 36 (:LINEAR LEN-WHEN-PREFIXP))
              (36 6 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
              (33 12
                  (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
              (30 24 (:REWRITE DEFAULT-<-2))
              (28 4 (:REWRITE MEMBER-WHEN-ATOM))
              (27 6 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
              (26 26 (:REWRITE SUBSETP-TRANS2))
              (26 26 (:REWRITE SUBSETP-TRANS))
              (24 24 (:TYPE-PRESCRIPTION PREFIXP))
              (21 21
                  (:TYPE-PRESCRIPTION HONS-ASSOC-EQUAL))
              (18 18
                  (:LINEAR DEPGRAPH::LEN-SD-WHEN-SUBSET))
              (18 18 (:LINEAR INDEX-OF-<-LEN))
              (12 12 (:TYPE-PRESCRIPTION SUBLISTP))
              (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
              (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
              (12 12
                  (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
              (12 12
                  (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
              (12 12 (:REWRITE CONSP-OF-CDR-BY-LEN))
              (9 9 (:REWRITE DEFAULT-CAR))
              (9 9 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (9 9
                 (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2))
              (9 9
                 (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
              (9 9 (:DEFINITION HONS-ACONS))
              (7 7 (:REWRITE SUBSETP-MEMBER . 2))
              (7 7 (:REWRITE SUBSETP-MEMBER . 1))
              (7 7
                 (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (6 6 (:REWRITE SUBLISTP-COMPLETE))
              (6 6
                 (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
              (6 6 (:REWRITE CAR-CONS))
              (6 3 (:REWRITE MEMBER-OF-CONS))
              (4 4 (:REWRITE SUBSETP-MEMBER . 4))
              (4 4 (:REWRITE SUBSETP-MEMBER . 3))
              (4 4 (:REWRITE INTERSECTP-MEMBER . 3))
              (4 4 (:REWRITE INTERSECTP-MEMBER . 2)))
(DEPGRAPH::L2 (1872 3 (:DEFINITION DEPGRAPH::TOPOSORT-AUX))
              (1188 3 (:REWRITE O<-OF-TWO-NATS-MEASURE))
              (900 6
                   (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
              (804 6 (:REWRITE SUBLISTP-WHEN-PREFIXP))
              (696 12
                   (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
              (492 6
                   (:DEFINITION DEPGRAPH::TOPOSORT-MEASURE))
              (403 111
                   (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (303 39
                   (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
              (243 12
                   (:REWRITE DEPGRAPH::LEN-SD-CONS-RIGHT-1))
              (237 3
                   (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WEAK))
              (216 216 (:TYPE-PRESCRIPTION LEN))
              (197 57 (:REWRITE ALIST-KEYS-WHEN-ATOM))
              (150 30 (:REWRITE LEN-WHEN-ATOM))
              (140 41 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
              (122 41 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (108 18 (:DEFINITION NFIX))
              (104 104
                   (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (96 96
                  (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
              (87 3 (:REWRITE SUBSETP-CAR-MEMBER))
              (79 7 (:REWRITE MEMBER-WHEN-ATOM))
              (75 39
                  (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
              (66 3
                  (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
              (66 3
                  (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
              (63 3
                  (:REWRITE DEPGRAPH::LEN-SD-WHEN-SUBSET))
              (60 6 (:REWRITE LEN-WHEN-PREFIXP))
              (60 6 (:DEFINITION HONS-GET))
              (52 52 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (52 52 (:REWRITE CONSP-BY-LEN))
              (51 12
                  (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
              (48 24 (:REWRITE DEFAULT-<-1))
              (45 18 (:REWRITE DEFAULT-CDR))
              (45 6 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
              (42 42 (:REWRITE SUBSETP-TRANS2))
              (42 42 (:REWRITE SUBSETP-TRANS))
              (42 42
                  (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
              (42 42
                  (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
              (42 42 (:LINEAR LEN-WHEN-PREFIXP))
              (36 6 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
              (33 12
                  (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
              (33 3 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
              (30 24 (:REWRITE DEFAULT-<-2))
              (30 15
                  (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
              (27 6 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
              (24 24 (:TYPE-PRESCRIPTION PREFIXP))
              (24 24
                  (:TYPE-PRESCRIPTION HONS-ASSOC-EQUAL))
              (24 24
                  (:LINEAR DEPGRAPH::LEN-SD-WHEN-SUBSET))
              (21 21 (:LINEAR INDEX-OF-<-LEN))
              (20 20 (:REWRITE SUBSETP-MEMBER . 2))
              (20 20
                  (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (19 19 (:REWRITE DEFAULT-CAR))
              (19 19 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (15 15
                  (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2))
              (12 12 (:TYPE-PRESCRIPTION SUBLISTP))
              (12 12 (:REWRITE PREFIXP-TRANSITIVE . 2))
              (12 12 (:REWRITE PREFIXP-TRANSITIVE . 1))
              (12 12
                  (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
              (12 12
                  (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
              (12 12 (:REWRITE CONSP-OF-CDR-BY-LEN))
              (9 9 (:DEFINITION HONS-ACONS))
              (7 7 (:REWRITE SUBSETP-MEMBER . 4))
              (7 7 (:REWRITE SUBSETP-MEMBER . 3))
              (7 7 (:REWRITE INTERSECTP-MEMBER . 3))
              (7 7 (:REWRITE INTERSECTP-MEMBER . 2))
              (6 6 (:REWRITE SUBLISTP-COMPLETE))
              (6 6
                 (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
              (6 3 (:REWRITE MEMBER-OF-CONS)))
(DEPGRAPH::TOPOSORT-AUX
     (805 7
          (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (726 1 (:DEFINITION DEPGRAPH::TOPOSORT-AUX))
     (688 7 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (577 142
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (557 14
          (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (480 55
          (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
     (344 23 (:REWRITE SUBSETP-CONS-2))
     (306 74 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (276 14 (:REWRITE SUBSETP-CAR-MEMBER))
     (248 73 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (235 36 (:REWRITE LEN-WHEN-ATOM))
     (209 74 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (167 16
          (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
     (138 74 (:REWRITE SUBSETP-TRANS2))
     (136 136
          (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (109 55
          (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (108 108
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (92 14 (:REWRITE SUBSETP-MEMBER . 1))
     (86 1
         (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WEAK))
     (76 4
         (:REWRITE DEPGRAPH::LEN-SD-WHEN-SUBSET))
     (74 74 (:REWRITE SUBSETP-TRANS))
     (70 7 (:REWRITE LEN-WHEN-PREFIXP))
     (64 11 (:REWRITE DEFAULT-CDR))
     (61 14
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (56 56 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (56 56 (:REWRITE CONSP-BY-LEN))
     (54 7 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (53 27 (:REWRITE DEFAULT-<-1))
     (50 50
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (50 50
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (50 50 (:LINEAR LEN-WHEN-PREFIXP))
     (45 3
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (42 14
         (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (35 7 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (35 1
         (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
     (35 1
         (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
     (33 27 (:REWRITE DEFAULT-<-2))
     (28 28 (:TYPE-PRESCRIPTION PREFIXP))
     (28 4 (:REWRITE MEMBER-WHEN-ATOM))
     (25 25 (:LINEAR INDEX-OF-<-LEN))
     (24 4 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (15 15 (:REWRITE DEFAULT-CAR))
     (15 15 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (14 14 (:TYPE-PRESCRIPTION SUBLISTP))
     (14 14 (:REWRITE SUBSETP-MEMBER . 2))
     (14 14 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (14 14 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (14 14
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (14 14
         (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (14 14
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (13 13 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (11 1 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (7 7 (:REWRITE SUBLISTP-COMPLETE))
     (4 4 (:REWRITE SUBSETP-MEMBER . 4))
     (4 4 (:REWRITE SUBSETP-MEMBER . 3))
     (4 4 (:REWRITE INTERSECTP-MEMBER . 3))
     (4 4 (:REWRITE INTERSECTP-MEMBER . 2))
     (4 4
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(DEPGRAPH::CONS-LISTP-OF-TOPOSORT-AUX
     (56822 105
            (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (55068 105 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (53104 210
            (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (27279 4554
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (24880 1676
            (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
     (23826 236
            (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
     (20073 2365 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (18211 3658
            (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (17296 3270 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (14559 3270 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (11654 509 (:REWRITE SUBSETP-CAR-MEMBER))
     (8747 410
           (:LINEAR DEPGRAPH::LEN-SD-WHEN-SUBSET))
     (8056 3467 (:REWRITE SUBSETP-TRANS2))
     (7358 978 (:REWRITE LEN-WHEN-ATOM))
     (7258 243
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2))
     (3662 1676
           (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (3516 3467 (:REWRITE SUBSETP-TRANS))
     (3504 3504
           (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (3437 3437
           (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (3416 3416 (:REWRITE SUBSETP-MEMBER . 2))
     (2967 118
           (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (2875 31
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
     (2789 31
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WEAK))
     (2696 31
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
     (1912 1912 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1912 1912 (:REWRITE CONSP-BY-LEN))
     (1877 142
           (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (1779 141 (:REWRITE SUBSETP-MEMBER . 4))
     (1496 48 (:REWRITE SUBSETP-OF-CONS))
     (1050 105 (:REWRITE LEN-WHEN-PREFIXP))
     (963 210
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (858 105 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (844 423 (:REWRITE DEFAULT-<-1))
     (706 706
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (706 706
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (706 706 (:LINEAR LEN-WHEN-PREFIXP))
     (677 677 (:REWRITE DEFAULT-CAR))
     (677 677 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (636 636 (:REWRITE MEMBER-SELF))
     (608 38 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (581 210
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (526 423 (:REWRITE DEFAULT-<-2))
     (476 105 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (420 420 (:TYPE-PRESCRIPTION PREFIXP))
     (353 353 (:LINEAR INDEX-OF-<-LEN))
     (247 247 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (210 210 (:TYPE-PRESCRIPTION SUBLISTP))
     (210 210 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (210 210 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (210 210
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (210 210
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (180 40 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP))
     (168 24 (:REWRITE MEMBER-WHEN-ATOM))
     (152 152 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (142 142
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (141 141 (:REWRITE INTERSECTP-MEMBER . 3))
     (141 141 (:REWRITE INTERSECTP-MEMBER . 2))
     (112 112
          (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (105 105 (:REWRITE SUBLISTP-COMPLETE))
     (57 31 (:REWRITE DEFAULT-+-2))
     (31 31 (:REWRITE DEFAULT-+-1)))
(DEPGRAPH::SUBSETP-EQUAL-OF-ALIST-KEYS-OF-TOPOSORT-AUX
     (29143 105
            (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (27389 105 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (25425 210
            (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (15161 3787
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (13239 1245
            (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
     (10776 401 (:REWRITE SUBSETP-CAR-MEMBER))
     (9986 2255 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (8956 428
           (:LINEAR DEPGRAPH::LEN-SD-WHEN-SUBSET))
     (7839 2255 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7448 2088 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (4936 794 (:REWRITE LEN-WHEN-ATOM))
     (4740 245
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
     (3683 118
           (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (3034 3034
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (2935 2351 (:REWRITE SUBSETP-TRANS))
     (2769 1245
           (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (2768 2768
           (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (2299 31
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
     (2286 31
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WEAK))
     (1601 1601 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1601 1601 (:REWRITE CONSP-BY-LEN))
     (1407 31
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
     (1216 245
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2))
     (1050 105 (:REWRITE LEN-WHEN-PREFIXP))
     (963 210
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (858 143
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (858 105 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (844 423 (:REWRITE DEFAULT-<-1))
     (724 724
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (724 724
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (724 724 (:LINEAR LEN-WHEN-PREFIXP))
     (581 210
          (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (540 540 (:REWRITE DEFAULT-CAR))
     (540 540 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (526 423 (:REWRITE DEFAULT-<-2))
     (476 105 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (420 420 (:TYPE-PRESCRIPTION PREFIXP))
     (418 38 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (401 401
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (362 362 (:LINEAR INDEX-OF-<-LEN))
     (259 37 (:REWRITE MEMBER-WHEN-ATOM))
     (247 247 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (210 210 (:TYPE-PRESCRIPTION SUBLISTP))
     (210 210 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (210 210 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (210 210
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (210 210
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (152 152 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (143 143
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (137 137 (:REWRITE INTERSECTP-MEMBER . 3))
     (137 137 (:REWRITE INTERSECTP-MEMBER . 2))
     (105 105 (:REWRITE SUBLISTP-COMPLETE))
     (55 30 (:REWRITE DEFAULT-+-2))
     (30 30
         (:REWRITE SET-DIFFERENCE-EQUAL-OF-SELF))
     (30 30 (:REWRITE DEFAULT-+-1)))
(DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE
     (53019 192
            (:REWRITE LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (49810 192 (:REWRITE SUBLISTP-WHEN-PREFIXP))
     (46217 384
            (:REWRITE PREFIXP-WHEN-EQUAL-LENGTHS))
     (22359 5682
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (21058 2150
            (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-SUBSETP-EQUAL))
     (18665 360
            (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET))
     (14201 607 (:REWRITE SUBSETP-CAR-MEMBER))
     (13957 3899 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (11060 3899 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (10444 3014 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (8180 1352 (:REWRITE LEN-WHEN-ATOM))
     (7609 4097 (:REWRITE SUBSETP-TRANS2))
     (6428 646
           (:LINEAR DEPGRAPH::LEN-SD-WHEN-SUBSET))
     (6296 370
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WHEN-SUBSET-2))
     (4696 4696
           (:TYPE-PRESCRIPTION SET-DIFFERENCE-EQUAL))
     (4616 4616
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4448 2150
           (:REWRITE SET-DIFFERENCE-EQUAL-WHEN-ATOM))
     (4155 4097 (:REWRITE SUBSETP-TRANS))
     (3888 196
           (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (2761 37
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-2))
     (2679 37
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-WEAK))
     (2422 2422 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (2422 2422 (:REWRITE CONSP-BY-LEN))
     (1975 173 (:REWRITE SUBSETP-MEMBER . 4))
     (1920 192 (:REWRITE LEN-WHEN-PREFIXP))
     (1807 37
           (:LINEAR DEPGRAPH::LEN-SD-CONS-RIGHT-3))
     (1741 384
           (:REWRITE PREFIXP-WHEN-NOT-CONSP-RIGHT))
     (1680 280
           (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (1567 794 (:REWRITE DEFAULT-<-1))
     (1549 192 (:REWRITE SUBLISTP-WHEN-ATOM-RIGHT))
     (1182 1182
           (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (1182 1182
           (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (1182 1182 (:LINEAR LEN-WHEN-PREFIXP))
     (1084 384
           (:REWRITE PREFIXP-WHEN-NOT-CONSP-LEFT))
     (967 794 (:REWRITE DEFAULT-<-2))
     (938 938 (:REWRITE DEFAULT-CAR))
     (938 938 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (892 192 (:REWRITE SUBLISTP-WHEN-ATOM-LEFT))
     (768 768 (:TYPE-PRESCRIPTION PREFIXP))
     (725 25 (:REWRITE SUBSETP-OF-CONS))
     (682 62 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (607 607
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (591 591 (:LINEAR INDEX-OF-<-LEN))
     (550 550 (:REWRITE SUBSETP-MEMBER . 2))
     (438 438 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (384 384 (:TYPE-PRESCRIPTION SUBLISTP))
     (384 384 (:REWRITE PREFIXP-TRANSITIVE . 2))
     (384 384 (:REWRITE PREFIXP-TRANSITIVE . 1))
     (384 384
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 2))
     (384 384
          (:REWRITE PREFIXP-ONE-WAY-OR-ANOTHER . 1))
     (280 280
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (248 248 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (192 192 (:REWRITE SUBLISTP-COMPLETE))
     (173 173 (:REWRITE INTERSECTP-MEMBER . 3))
     (173 173 (:REWRITE INTERSECTP-MEMBER . 2))
     (154 22 (:REWRITE MEMBER-WHEN-ATOM))
     (67 37 (:REWRITE DEFAULT-+-2))
     (37 37 (:REWRITE DEFAULT-+-1)))
(DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER
     (102 7 (:REWRITE DEFAULT-CDR))
     (56 7 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (30 15
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (28 7
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (15 15 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (15 15 (:REWRITE CONSP-BY-LEN))
     (14 14
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (14 14 (:TYPE-PRESCRIPTION ALISTP))
     (14 14
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (7 7 (:REWRITE SUBSETP-TRANS2))
     (7 7 (:REWRITE SUBSETP-TRANS))
     (7 7 (:REWRITE SUBSETP-MEMBER . 2))
     (7 7 (:REWRITE SUBSETP-MEMBER . 1))
     (7 7 (:REWRITE MEMBER-SELF))
     (7 7
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (7 7 (:REWRITE ALISTP-WHEN-ATOM))
     (6 6
        (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (6 1 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP)))
(DEPGRAPH::TRUE-LISTP-OF-EXTRACT-TOPOLOGICAL-ORDER
     (100 10 (:REWRITE DEFAULT-CDR))
     (66 9
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (64 8 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (62 9 (:REWRITE TRUE-LISTP-WHEN-ATOM))
     (45 21
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (42 42
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (40 10 (:REWRITE DEFAULT-CAR))
     (32 8
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (21 21 (:REWRITE CONSP-BY-LEN))
     (18 18 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (18 9 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (16 16
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (16 16 (:TYPE-PRESCRIPTION ALISTP))
     (16 8
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (9 9 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (9 9 (:REWRITE SET::IN-SET))
     (8 8
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (8 8 (:REWRITE ALISTP-WHEN-ATOM)))
(DEPGRAPH::L0 (205 13 (:REWRITE SUBSETP-MEMBER . 3))
              (146 17 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
              (126 54
                   (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (116 11 (:REWRITE DEFAULT-CDR))
              (108 108
                   (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (105 17 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (81 11 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
              (77 77
                  (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER))
              (62 9 (:REWRITE MEMBER-WHEN-ATOM))
              (58 13 (:REWRITE DEFAULT-CAR))
              (54 54 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (54 54 (:REWRITE CONSP-BY-LEN))
              (49 1 (:REWRITE SUBSETP-OF-CONS))
              (40 10
                  (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
              (24 1 (:REWRITE SUBSETP-CAR-MEMBER))
              (22 22 (:REWRITE SUBSETP-TRANS2))
              (22 22 (:REWRITE SUBSETP-TRANS))
              (22 11
                  (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
              (20 20
                  (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
              (20 20 (:TYPE-PRESCRIPTION ALISTP))
              (14 14 (:REWRITE SUBSETP-MEMBER . 2))
              (14 14
                  (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (13 13 (:REWRITE SUBSETP-MEMBER . 4))
              (13 13 (:REWRITE INTERSECTP-MEMBER . 3))
              (13 13 (:REWRITE INTERSECTP-MEMBER . 2))
              (13 13 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (10 10
                  (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
              (10 10 (:REWRITE ALISTP-WHEN-ATOM)))
(DEPGRAPH::L1 (1090 165 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (540 540
                   (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (463 56 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
              (427 80 (:REWRITE DEFAULT-CAR))
              (333 50 (:REWRITE MEMBER-WHEN-ATOM))
              (270 270 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (270 270 (:REWRITE CONSP-BY-LEN))
              (228 57
                   (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
              (222 222
                   (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER))
              (179 179 (:REWRITE SUBSETP-TRANS2))
              (179 179 (:REWRITE SUBSETP-TRANS))
              (156 8 (:REWRITE SUBSETP-CAR-MEMBER))
              (124 5 (:REWRITE SUBSETP-OF-CONS))
              (114 114
                   (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
              (114 114 (:TYPE-PRESCRIPTION ALISTP))
              (112 56
                   (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
              (80 80 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (77 77
                  (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (73 73 (:REWRITE SUBSETP-MEMBER . 2))
              (64 8 (:REWRITE ALISTP-OF-CDR))
              (59 59 (:REWRITE SUBSETP-MEMBER . 4))
              (59 59 (:REWRITE INTERSECTP-MEMBER . 3))
              (59 59 (:REWRITE INTERSECTP-MEMBER . 2))
              (57 57
                  (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
              (57 57 (:REWRITE ALISTP-WHEN-ATOM))
              (31 31 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::SUBSETP-EQUAL-OF-EXTRACT-TOPOLOGICAL-ORDER
     (180 4
          (:DEFINITION DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER))
     (173 51
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (144 3
          (:REWRITE SUBSETP-OF-APPEND-WHEN-SUBSET-OF-EITHER))
     (141 10 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (84 84
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (73 10 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (72 12 (:REWRITE DEFAULT-CDR))
     (72 12 (:REWRITE DEFAULT-CAR))
     (64 8 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (63 13 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (46 46
         (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER))
     (42 42 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (42 42 (:REWRITE CONSP-BY-LEN))
     (39 3 (:REWRITE APPEND-UNDER-IFF))
     (32 8
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (24 4 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (23 3 (:REWRITE SUBSETP-MEMBER . 1))
     (21 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (16 16
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (16 16 (:TYPE-PRESCRIPTION ALISTP))
     (16 8
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (16 2 (:REWRITE MEMBER-WHEN-ATOM))
     (12 12 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (10 10 (:REWRITE SUBSETP-TRANS2))
     (10 10 (:REWRITE SUBSETP-TRANS))
     (8 8 (:TYPE-PRESCRIPTION CONS-LISTP))
     (8 8
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (8 8 (:REWRITE ALISTP-WHEN-ATOM))
     (6 1 (:REWRITE DEPGRAPH::L0))
     (4 4
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (3 3 (:REWRITE SUBSETP-MEMBER . 2))
     (2 2 (:REWRITE SUBSETP-MEMBER . 4))
     (2 2 (:REWRITE SUBSETP-MEMBER . 3))
     (2 2 (:REWRITE INTERSECTP-MEMBER . 3))
     (2 2 (:REWRITE INTERSECTP-MEMBER . 2)))
(DEPGRAPH::ETO)
(DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER-IS-ETO
     (481 59 (:REWRITE DEFAULT-CDR))
     (473 42 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (463 7 (:REWRITE REV-UNDER-IFF))
     (415 64 (:REWRITE DEFAULT-CAR))
     (398 6 (:REWRITE REV-WHEN-NOT-CONSP))
     (236 59
          (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (144 18 (:REWRITE ALISTP-OF-CDR))
     (124 124
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (118 118
          (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (118 118 (:TYPE-PRESCRIPTION ALISTP))
     (84 42
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (77 1 (:REWRITE CDR-OF-APPEND-WHEN-CONSP))
     (65 65 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (62 62 (:REWRITE CONSP-BY-LEN))
     (59 59
         (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (59 59 (:REWRITE ALISTP-WHEN-ATOM))
     (9 9 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (3 3 (:TYPE-PRESCRIPTION REVAPPEND))
     (1 1
        (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV)))
(DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-FINISHED
     (2522 280
           (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (2041 21 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
     (1978 21
           (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
     (1635 35 (:REWRITE SUBSETP-MEMBER . 3))
     (1231 25 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (1158 102 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (974 149 (:REWRITE DEFAULT-CAR))
     (888 32 (:REWRITE MEMBER-WHEN-ATOM))
     (576 144
          (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (435 25 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (384 48 (:REWRITE ALISTP-OF-CDR))
     (354 354
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (288 288
          (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (288 288 (:TYPE-PRESCRIPTION ALISTP))
     (204 102
          (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (198 198 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (198 198 (:REWRITE CONSP-BY-LEN))
     (176 176
          (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (149 149 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (144 144
          (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (144 144 (:REWRITE ALISTP-WHEN-ATOM))
     (136 65 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (36 36 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (35 35 (:REWRITE SUBSETP-MEMBER . 4))
     (35 35 (:REWRITE SUBSETP-MEMBER . 2))
     (35 35
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (35 35 (:REWRITE INTERSECTP-MEMBER . 3))
     (35 35 (:REWRITE INTERSECTP-MEMBER . 2))
     (27 27 (:REWRITE SUBSETP-TRANS2))
     (27 27 (:REWRITE SUBSETP-TRANS)))
(DEPGRAPH::TOPOSORT-AUX-GROWS-ETO
     (22021 2045
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (18041 31
            (:REWRITE DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-FINISHED))
     (15229 280 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (15160 147
            (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (12901 2205 (:REWRITE DEFAULT-CAR))
     (9926 813 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (4206 809
           (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (4156 280 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (3331 321
           (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (3068 3068
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (2205 2205 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (1791 809
           (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (1791 809 (:REWRITE ALISTP-WHEN-ATOM))
     (1640 1 (:REWRITE SUBSETP-OF-CONS))
     (1639 82 (:REWRITE MEMBER-WHEN-ATOM))
     (1631 1631 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1631 1631 (:REWRITE CONSP-BY-LEN))
     (1626 813
           (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (1622 1622 (:TYPE-PRESCRIPTION ALISTP))
     (1618 1618
           (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (1433 124 (:REWRITE SUBSETP-CAR-MEMBER))
     (1297 445 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (1168 1168
           (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (975 975 (:TYPE-PRESCRIPTION DEPGRAPH::ETO))
     (838 113 (:REWRITE DEFAULT-<-2))
     (737 71 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (588 147
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (496 113 (:REWRITE DEFAULT-<-1))
     (384 384 (:REWRITE SUBSETP-TRANS2))
     (384 384 (:REWRITE SUBSETP-TRANS))
     (291 291
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (186 186
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (185 185 (:REWRITE SUBSETP-MEMBER . 4))
     (185 185 (:REWRITE INTERSECTP-MEMBER . 3))
     (185 185 (:REWRITE INTERSECTP-MEMBER . 2))
     (138 138 (:REWRITE SUBSETP-MEMBER . 2))
     (71 71 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-IN-QUEUE
     (22879 3344 (:REWRITE DEFAULT-CAR))
     (22190 4014
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (19504 1668
            (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (13263 873 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (9096 974 (:REWRITE SUBSETP-TRANS))
     (7941 241 (:REWRITE SUBSETP-MEMBER . 4))
     (7904 1668
           (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (7080 281
           (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (6332 6332
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (3424 506
           (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (3347 3347 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (3347 3347 (:REWRITE CONSP-BY-LEN))
     (3344 3344 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (3336 3336
           (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (3336 3336 (:TYPE-PRESCRIPTION ALISTP))
     (3336 1668
           (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (2900 1668
           (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (2900 1668 (:REWRITE ALISTP-WHEN-ATOM))
     (2721 784 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (2048 2048
           (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (1957 165 (:REWRITE MEMBER-WHEN-ATOM))
     (1428 129 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (1403 977 (:REWRITE SUBSETP-TRANS2))
     (1332 171 (:REWRITE DEFAULT-<-2))
     (1232 308
           (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (1200 171 (:REWRITE DEFAULT-<-1))
     (972 291 (:REWRITE SUBSETP-MEMBER . 2))
     (435 435
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (429 429
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (241 241 (:REWRITE INTERSECTP-MEMBER . 3))
     (241 241 (:REWRITE INTERSECTP-MEMBER . 2))
     (215 215 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::QUEUE-IS-SUBSET-OF-ETO
     (238 5 (:DEFINITION DEPGRAPH::ETO))
     (181 35
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (149 7 (:REWRITE SUBSETP-TRANS))
     (135 7 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (90 15 (:REWRITE DEFAULT-CDR))
     (90 15 (:REWRITE DEFAULT-CAR))
     (80 10 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (54 54
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (54 7 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (40 10
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (39 9 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (27 27 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (27 27 (:REWRITE CONSP-BY-LEN))
     (27 2 (:REWRITE SUBSETP-MEMBER . 4))
     (24 24
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (20 20
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (20 20 (:TYPE-PRESCRIPTION ALISTP))
     (20 10
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (18 2 (:REWRITE MEMBER-WHEN-ATOM))
     (15 15 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (10 10 (:TYPE-PRESCRIPTION CONS-LISTP))
     (10 10
         (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (10 10 (:REWRITE ALISTP-WHEN-ATOM))
     (7 7 (:REWRITE SUBSETP-TRANS2))
     (7 3 (:REWRITE SUBSETP-MEMBER . 2))
     (5 5
        (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (3 3 (:REWRITE SUBSETP-MEMBER . 1))
     (3 3
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (2 2 (:REWRITE SUBSETP-MEMBER . 3))
     (2 2 (:REWRITE INTERSECTP-MEMBER . 3))
     (2 2 (:REWRITE INTERSECTP-MEMBER . 2)))
(DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER-INCLUDES-QUEUE
     (46 1 (:DEFINITION DEPGRAPH::ETO))
     (18 3 (:REWRITE DEFAULT-CDR))
     (18 3 (:REWRITE DEFAULT-CAR))
     (16 2 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (14 6
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (10 10
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (8 2
        (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (7 2 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (7 1 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (6 1 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (5 5 (:REWRITE CONSP-BY-LEN))
     (4 4
        (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (4 4
        (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (4 4 (:TYPE-PRESCRIPTION ALISTP))
     (4 2
        (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (3 3 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (2 2 (:TYPE-PRESCRIPTION CONS-LISTP))
     (2 2
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (2 2 (:REWRITE ALISTP-WHEN-ATOM))
     (1 1
        (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS)))
(DEPGRAPH::SEEN-REMAIN-SEEN
     (17556 1564
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (16417 518 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (15108 58
            (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (14943 240 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (8936 1582 (:REWRITE DEFAULT-CAR))
     (6916 532 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (6013 6 (:REWRITE SUBSETP-OF-CONS))
     (4540 141 (:REWRITE SUBSETP-CAR-MEMBER))
     (2660 532
           (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (2256 2256
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (1582 1582 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (1520 240 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (1502 264
           (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (1409 1409
           (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (1213 1213 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1213 1213 (:REWRITE CONSP-BY-LEN))
     (1064 1064
           (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (1064 1064 (:TYPE-PRESCRIPTION ALISTP))
     (1064 532
           (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (1064 532
           (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (1064 532 (:REWRITE ALISTP-WHEN-ATOM))
     (746 103 (:REWRITE DEFAULT-<-2))
     (669 66 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (532 133
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (464 103 (:REWRITE DEFAULT-<-1))
     (364 52 (:REWRITE MEMBER-WHEN-ATOM))
     (361 361 (:REWRITE SUBSETP-TRANS2))
     (361 361 (:REWRITE SUBSETP-TRANS))
     (264 264
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (173 173
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (167 167 (:REWRITE SUBSETP-MEMBER . 4))
     (167 167 (:REWRITE INTERSECTP-MEMBER . 3))
     (167 167 (:REWRITE INTERSECTP-MEMBER . 2))
     (118 118 (:REWRITE SUBSETP-MEMBER . 2))
     (66 66 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::ONLY-UNSEEN-CAN-BECOME-FINISHED
     (29651 2191
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (22139 385 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (20272 176
            (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (14337 2526 (:REWRITE DEFAULT-CAR))
     (11410 884 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (9903 50
           (:REWRITE DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-FINISHED))
     (6068 385 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (4989 876
           (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (3957 15
           (:REWRITE DEPGRAPH::TOPOSORT-AUX-GROWS-ETO))
     (3346 3346
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (2526 2526 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (2385 876
           (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (2385 876 (:REWRITE ALISTP-WHEN-ATOM))
     (2385 360
           (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (1797 1797 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1797 1797 (:REWRITE CONSP-BY-LEN))
     (1768 884
           (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (1760 1760 (:TYPE-PRESCRIPTION ALISTP))
     (1752 1752
           (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (1741 9 (:REWRITE SUBSETP-OF-CONS))
     (1687 151 (:REWRITE SUBSETP-CAR-MEMBER))
     (1254 48 (:REWRITE MEMBER-WHEN-ATOM))
     (1248 462 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (918 126 (:REWRITE DEFAULT-<-2))
     (887 15
          (:REWRITE DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-IN-QUEUE))
     (830 81 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (588 147
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (568 568 (:REWRITE SUBSETP-TRANS2))
     (568 568 (:REWRITE SUBSETP-TRANS))
     (468 126 (:REWRITE DEFAULT-<-1))
     (312 312
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (249 249
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (232 8
          (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (213 213 (:REWRITE SUBSETP-MEMBER . 4))
     (213 213 (:REWRITE INTERSECTP-MEMBER . 3))
     (213 213 (:REWRITE INTERSECTP-MEMBER . 2))
     (175 175 (:REWRITE SUBSETP-MEMBER . 2))
     (89 89 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::ETO-MEMBERS-ARE-SEEN
     (6338 709
           (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (3247 124 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (3056 260 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (2756 380 (:REWRITE DEFAULT-CAR))
     (2158 124 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (1580 21
           (:REWRITE DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-FINISHED))
     (1520 380
           (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (1395 56 (:REWRITE MEMBER-WHEN-ATOM))
     (1169 21 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
     (1128 21
           (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
     (1088 136 (:REWRITE ALISTP-OF-CDR))
     (896 896
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (760 760
          (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (760 760 (:TYPE-PRESCRIPTION ALISTP))
     (633 19 (:REWRITE SUBSETP-CAR-MEMBER))
     (520 260
          (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (501 212 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (490 4 (:REWRITE SUBSETP-OF-CONS))
     (469 469 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (469 469 (:REWRITE CONSP-BY-LEN))
     (380 380
          (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (380 380 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (380 380 (:REWRITE ALISTP-WHEN-ATOM))
     (165 21 (:DEFINITION HONS-GET))
     (147 147 (:REWRITE SUBSETP-TRANS2))
     (147 147 (:REWRITE SUBSETP-TRANS))
     (140 21
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (120 120
          (:TYPE-PRESCRIPTION HONS-ASSOC-EQUAL))
     (116 116 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (81 81
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (77 77 (:REWRITE SUBSETP-MEMBER . 4))
     (77 77 (:REWRITE INTERSECTP-MEMBER . 3))
     (77 77 (:REWRITE INTERSECTP-MEMBER . 2))
     (76 76 (:REWRITE SUBSETP-MEMBER . 2))
     (21 21 (:TYPE-PRESCRIPTION HONS-GET))
     (4 4
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY)))
(DEPGRAPH::STUPID-CONSEQUENCE
     (286 5 (:REWRITE SUBSETP-MEMBER . 3))
     (259 39
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (213 1 (:REWRITE SUBSETP-OF-CONS))
     (206 35 (:REWRITE DEFAULT-CDR))
     (167 32 (:REWRITE DEFAULT-CAR))
     (144 18 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (115 6 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (76 1
         (:REWRITE DEPGRAPH::ONLY-UNSEEN-CAN-BECOME-FINISHED))
     (72 18
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (67 6 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (64 64
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (63 5
         (:REWRITE DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-FINISHED))
     (60 1
         (:REWRITE DEPGRAPH::TOPOSORT-AUX-GROWS-ETO))
     (56 2 (:REWRITE MEMBER-WHEN-ATOM))
     (36 36
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (36 36 (:TYPE-PRESCRIPTION ALISTP))
     (36 18
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (34 34 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (34 34 (:REWRITE CONSP-BY-LEN))
     (32 32 (:TYPE-PRESCRIPTION DEPGRAPH::ETO))
     (32 32 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (24 2 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
     (22 6 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (22 2
         (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
     (18 18 (:TYPE-PRESCRIPTION CONS-LISTP))
     (18 18
         (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (18 18 (:REWRITE ALISTP-WHEN-ATOM))
     (15 2 (:DEFINITION HONS-GET))
     (13 2 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (9 9 (:TYPE-PRESCRIPTION HONS-ASSOC-EQUAL))
     (9 9 (:REWRITE SUBSETP-TRANS2))
     (9 9 (:REWRITE SUBSETP-TRANS))
     (9 9
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (8 8 (:REWRITE SUBSETP-MEMBER . 2))
     (7 1 (:REWRITE SUBSETP-CONS-2))
     (5 5 (:REWRITE SUBSETP-MEMBER . 4))
     (5 5 (:REWRITE INTERSECTP-MEMBER . 3))
     (5 5 (:REWRITE INTERSECTP-MEMBER . 2))
     (4 4
        (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (2 2 (:TYPE-PRESCRIPTION HONS-GET))
     (1 1
        (:REWRITE DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-IN-QUEUE)))
(DEPGRAPH::TOPOSORT-AUX-GROWS-ETO-WITHOUT-DUPES
     (12802 1936
            (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (10736 1624 (:REWRITE DEFAULT-CAR))
     (10546 99
            (:REWRITE DEPGRAPH::ETO-MEMBERS-ARE-SEEN))
     (9278 894 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (5212 172 (:REWRITE SUBSETP-CAR-MEMBER))
     (4780 243 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (4003 894
           (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (3312 66
           (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (3048 3048
           (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (2857 32
           (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-ATOM))
     (2857 32
           (:REWRITE NO-DUPLICATESP-EQUAL-NON-CONS))
     (2159 75
           (:REWRITE DEPGRAPH::MEMBER-EQUAL-ETO-WHEN-FINISHED))
     (1788 1788
           (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (1788 1788 (:TYPE-PRESCRIPTION ALISTP))
     (1788 894
           (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (1624 1624 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (1599 1599 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1599 1599 (:REWRITE CONSP-BY-LEN))
     (1321 894
           (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (1321 894 (:REWRITE ALISTP-WHEN-ATOM))
     (1086 1086 (:TYPE-PRESCRIPTION DEPGRAPH::ETO))
     (1079 224
           (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (948 298 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (796 796
          (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (719 243 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (472 59 (:REWRITE DEFAULT-<-2))
     (439 39 (:REWRITE HONS-ASSOC-EQUAL-OF-CONS))
     (424 106
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (400 59 (:REWRITE DEFAULT-<-1))
     (292 292 (:REWRITE SUBSETP-TRANS2))
     (292 292 (:REWRITE SUBSETP-TRANS))
     (224 224
          (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (223 49 (:REWRITE MEMBER-WHEN-ATOM))
     (172 172
          (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (153 153 (:REWRITE SUBSETP-MEMBER . 2))
     (98 98 (:REWRITE SUBSETP-MEMBER . 4))
     (98 98 (:REWRITE INTERSECTP-MEMBER . 3))
     (98 98 (:REWRITE INTERSECTP-MEMBER . 2))
     (39 39 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (34 34
         (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-DUPLICITY-BADGUY1))
     (32 32
         (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-HIGH-DUPLICITY))
     (32 32 (:REWRITE FN-CHECK-DEF-FORMALS)))
(DEPGRAPH::NO-DUPLICATESP-EQUAL-OF-EXTRACT-TOPOLOGICAL-ORDER
     (189 4 (:DEFINITION DEPGRAPH::ETO))
     (116 14
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (72 12 (:REWRITE DEFAULT-CDR))
     (72 12 (:REWRITE DEFAULT-CAR))
     (64 8 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (55 1
         (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-ATOM))
     (55 1
         (:REWRITE NO-DUPLICATESP-EQUAL-NON-CONS))
     (32 8
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (24 24
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (16 16
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (16 16 (:TYPE-PRESCRIPTION DEPGRAPH::ETO))
     (16 16 (:TYPE-PRESCRIPTION ALISTP))
     (16 8
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (12 12 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (12 12 (:REWRITE CONSP-BY-LEN))
     (12 12 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (8 8 (:TYPE-PRESCRIPTION CONS-LISTP))
     (8 8
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (8 8 (:REWRITE ALISTP-WHEN-ATOM))
     (1 1
        (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (1 1
        (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-HIGH-DUPLICITY))
     (1 1
        (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-DUPLICITY-BADGUY1))
     (1 1 (:REWRITE FN-CHECK-DEF-FORMALS)))
(DEPGRAPH::EXTRACT-TOPOLOGICAL-LOOP
     (102 7 (:REWRITE DEFAULT-CDR))
     (65 9 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (51 23
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (32 8
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (28 9 (:REWRITE DEFAULT-CAR))
     (22 2 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (21 21 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (21 21 (:REWRITE CONSP-BY-LEN))
     (19 19
         (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (16 16
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (16 16 (:TYPE-PRESCRIPTION ALISTP))
     (13 1 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (10 10 (:REWRITE SUBSETP-TRANS2))
     (10 10 (:REWRITE SUBSETP-TRANS))
     (10 10 (:REWRITE SUBSETP-MEMBER . 2))
     (10 10 (:REWRITE SUBSETP-MEMBER . 1))
     (9 9 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (8 8
        (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (8 8
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (8 8 (:REWRITE ALISTP-WHEN-ATOM))
     (8 3 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (7 7 (:REWRITE MEMBER-SELF))
     (7 1 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (7 1 (:REWRITE MEMBER-WHEN-ATOM))
     (6 6
        (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (6 1 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (1 1 (:REWRITE SUBSETP-MEMBER . 4))
     (1 1 (:REWRITE SUBSETP-MEMBER . 3))
     (1 1 (:REWRITE INTERSECTP-MEMBER . 3))
     (1 1 (:REWRITE INTERSECTP-MEMBER . 2)))
(DEPGRAPH::TRUE-LISTP-OF-EXTRACT-TOPOLOGICAL-LOOP
     (636 31 (:REWRITE DEFAULT-CDR))
     (368 8 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
     (344 8
          (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
     (229 92
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (220 38 (:REWRITE DEFAULT-CAR))
     (211 32 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (168 8 (:REWRITE SUBSETP-CAR-MEMBER))
     (136 136
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (100 25
          (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (86 11 (:REWRITE TRUE-LISTP-WHEN-ATOM))
     (81 11
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (76 76 (:REWRITE CONSP-BY-LEN))
     (72 8 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (64 64
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (64 32
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (64 24 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (56 8 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (56 8 (:REWRITE MEMBER-WHEN-ATOM))
     (50 50
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (50 50 (:TYPE-PRESCRIPTION ALISTP))
     (48 8 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (38 38 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (32 4 (:REWRITE ALISTP-OF-CDR))
     (25 25
         (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (25 25 (:REWRITE ALISTP-WHEN-ATOM))
     (22 22 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (22 11 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (16 16 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (11 11 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (11 11 (:REWRITE SET::IN-SET))
     (8 8 (:REWRITE SUBSETP-TRANS2))
     (8 8 (:REWRITE SUBSETP-TRANS))
     (8 8 (:REWRITE SUBSETP-MEMBER . 4))
     (8 8 (:REWRITE SUBSETP-MEMBER . 3))
     (8 8 (:REWRITE SUBSETP-MEMBER . 2))
     (8 8 (:REWRITE SUBSETP-MEMBER . 1))
     (8 8
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (8 8 (:REWRITE INTERSECTP-MEMBER . 3))
     (8 8 (:REWRITE INTERSECTP-MEMBER . 2))
     (8 8
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (2 2 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::L0 (705 33 (:REWRITE DEFAULT-CDR))
              (414 9 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
              (387 9
                   (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
              (374 148
                   (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (277 32 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
              (255 43 (:REWRITE DEFAULT-CAR))
              (242 242
                   (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (239 32 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (236 36 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
              (189 9 (:REWRITE SUBSETP-CAR-MEMBER))
              (169 22 (:REWRITE MEMBER-WHEN-ATOM))
              (130 130 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (130 130 (:REWRITE CONSP-BY-LEN))
              (114 102
                   (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-LOOP))
              (112 28
                   (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
              (72 72
                  (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
              (72 36
                  (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
              (72 27 (:REWRITE ALIST-KEYS-WHEN-ATOM))
              (56 56
                  (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
              (56 56 (:TYPE-PRESCRIPTION ALISTP))
              (54 9 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
              (43 43 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (38 38 (:REWRITE SUBSETP-TRANS2))
              (38 38 (:REWRITE SUBSETP-TRANS))
              (32 4 (:REWRITE ALISTP-OF-CDR))
              (28 28 (:REWRITE SUBSETP-MEMBER . 4))
              (28 28
                  (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (28 28 (:REWRITE INTERSECTP-MEMBER . 3))
              (28 28 (:REWRITE INTERSECTP-MEMBER . 2))
              (28 28
                  (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
              (28 28 (:REWRITE ALISTP-WHEN-ATOM))
              (26 26 (:REWRITE SUBSETP-MEMBER . 2))
              (9 9
                 (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
              (2 2 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::L1 (2095 290 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (2054 41 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
              (1931 41
                    (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
              (1344 211 (:REWRITE DEFAULT-CAR))
              (1199 57 (:REWRITE SUBSETP-CAR-MEMBER))
              (1192 1192
                    (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (1138 173 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
              (844 119 (:REWRITE MEMBER-WHEN-ATOM))
              (637 637 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (637 637 (:REWRITE CONSP-BY-LEN))
              (540 135
                   (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
              (395 13 (:REWRITE SUBSETP-OF-CONS))
              (346 173
                   (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
              (342 318
                   (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-LOOP))
              (318 318 (:REWRITE SUBSETP-TRANS2))
              (318 318 (:REWRITE SUBSETP-TRANS))
              (270 270
                   (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
              (270 270 (:TYPE-PRESCRIPTION ALISTP))
              (246 41
                   (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
              (211 211 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (160 20 (:REWRITE ALISTP-OF-CDR))
              (156 156
                   (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (150 150 (:REWRITE SUBSETP-MEMBER . 2))
              (135 135
                   (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
              (135 135 (:REWRITE ALISTP-WHEN-ATOM))
              (133 133 (:REWRITE SUBSETP-MEMBER . 4))
              (133 133 (:REWRITE INTERSECTP-MEMBER . 3))
              (133 133 (:REWRITE INTERSECTP-MEMBER . 2))
              (46 46 (:REWRITE CONSP-OF-CDR-BY-LEN))
              (37 37
                  (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY)))
(DEPGRAPH::SUBSETP-EQUAL-OF-EXTRACT-TOPOLOGICAL-LOOP
     (440 4
          (:DEFINITION DEPGRAPH::EXTRACT-TOPOLOGICAL-LOOP))
     (288 16 (:REWRITE DEFAULT-CDR))
     (241 75
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (188 4 (:REWRITE CONSP-OF-HONS-ASSOC-EQUAL))
     (176 4
          (:REWRITE DEPGRAPH::HONS-ASSOC-EQUAL-UNDER-IFF))
     (169 14 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (144 3
          (:REWRITE SUBSETP-OF-APPEND-WHEN-SUBSET-OF-EITHER))
     (109 14 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (108 108
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (95 25 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (84 4 (:REWRITE SUBSETP-CAR-MEMBER))
     (72 12 (:REWRITE DEFAULT-CAR))
     (68 12 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (58 58 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (58 58 (:REWRITE CONSP-BY-LEN))
     (46 46
         (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-LOOP))
     (44 6 (:REWRITE MEMBER-WHEN-ATOM))
     (39 3 (:REWRITE APPEND-UNDER-IFF))
     (32 8
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (32 4 (:DEFINITION HONS-GET))
     (27 7 (:REWRITE SUBSETP-MEMBER . 1))
     (24 12
         (:REWRITE CONSP-OF-CAR-WHEN-CONS-LISTP))
     (24 4 (:REWRITE HONS-ASSOC-EQUAL-WHEN-ATOM))
     (24 4 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (21 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (20 20
         (:TYPE-PRESCRIPTION HONS-ASSOC-EQUAL))
     (16 16
         (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (16 16 (:TYPE-PRESCRIPTION ALISTP))
     (14 14 (:REWRITE SUBSETP-TRANS2))
     (14 14 (:REWRITE SUBSETP-TRANS))
     (12 12 (:TYPE-PRESCRIPTION CONS-LISTP))
     (12 12 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (8 8
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (8 8
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (8 8 (:REWRITE ALISTP-WHEN-ATOM))
     (7 7 (:REWRITE SUBSETP-MEMBER . 2))
     (6 6 (:REWRITE SUBSETP-MEMBER . 4))
     (6 6 (:REWRITE SUBSETP-MEMBER . 3))
     (6 6 (:REWRITE INTERSECTP-MEMBER . 3))
     (6 6 (:REWRITE INTERSECTP-MEMBER . 2))
     (6 1 (:REWRITE DEPGRAPH::L0))
     (4 4
        (:REWRITE HONS-ASSOC-EQUAL-WHEN-FOUND-BY-FAL-FIND-ANY))
     (4 4 (:DEFINITION HONS-EQUAL)))
(DEPGRAPH::CONSP-OF-FIRST-WHEN-ALISTP
     (9 1
        (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (6 1
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (6 1 (:REWRITE ALISTP-WHEN-ATOM))
     (5 3
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (3 3 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (2 2
        (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (2 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(DEPGRAPH::CONSP-OF-FIRST-WHEN-CONS-LISTP
     (44 20
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (18 1
         (:REWRITE DEPGRAPH::CONSP-OF-FIRST-WHEN-ALISTP))
     (14 7
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (11 1 (:REWRITE MEMBER-OF-CAR))
     (11 1 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CONSP-BY-LEN))
     (10 2
         (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
     (10 1 (:REWRITE SUBSETP-CAR-MEMBER))
     (7 7 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (7 2 (:REWRITE ALISTP-WHEN-ATOM))
     (6 1
        (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
     (6 1 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP))
     (5 1 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
     (4 4 (:TYPE-PRESCRIPTION ALISTP))
     (2 2 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (2 2
        (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
     (2 2 (:REWRITE SUBSETP-MEMBER . 2))
     (2 2 (:REWRITE SUBSETP-MEMBER . 1))
     (2 2
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (2 2
        (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
     (2 2
        (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (1 1 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1 (:REWRITE SUBSETP-REFL))
     (1 1 (:REWRITE MEMBER-SELF))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(DEPGRAPH::TOPOSORT
     (33 11 (:REWRITE DEFAULT-CAR))
     (17 6
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (15 5 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (15 3 (:REWRITE LAST-WHEN-ATOM-OF-CDR))
     (14 2 (:REWRITE LEN-WHEN-ATOM))
     (11 11 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (10 10
         (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
     (10 10
         (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (8 8
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (6 3 (:REWRITE LAST-WHEN-ATOM))
     (6 3 (:REWRITE DEFAULT-CDR))
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::BOOLEANP-OF-TOPOSORT.SUCCESSP
     (16 4 (:REWRITE DEFAULT-CAR))
     (11 1
         (:REWRITE DEPGRAPH::CONSP-OF-FIRST-WHEN-CONS-LISTP))
     (8 1
        (:REWRITE DEPGRAPH::CONS-LISTP-OF-TOPOSORT-AUX))
     (7 2 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (7 1 (:REWRITE LEN-WHEN-ATOM))
     (6 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 4
        (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (4 4 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (3 3
        (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (2 2 (:TYPE-PRESCRIPTION CONS-LISTP))
     (2 2
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (2 2
        (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
     (2 2
        (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (2 1 (:REWRITE DEFAULT-CDR))
     (2 1 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP))
     (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1 1 (:TYPE-PRESCRIPTION LEN))
     (1 1 (:REWRITE CONSP-BY-LEN)))
(DEPGRAPH::TRUE-LISTP-OF-TOPOSORT.RESULT
     (32 8 (:REWRITE DEFAULT-CAR))
     (29 14 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (24 6 (:REWRITE LEN-WHEN-ATOM))
     (22 2
         (:REWRITE DEPGRAPH::CONSP-OF-FIRST-WHEN-CONS-LISTP))
     (20 7
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (16 2
         (:REWRITE DEPGRAPH::CONS-LISTP-OF-TOPOSORT-AUX))
     (12 12
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (8 8
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (8 8 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6
        (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (6 1 (:REWRITE TRUE-LISTP-WHEN-ATOM))
     (6 1
        (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (4 4
        (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
     (4 4
        (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (4 2 (:REWRITE DEFAULT-CDR))
     (4 2 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP))
     (2 2 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (2 2 (:TYPE-PRESCRIPTION LEN))
     (2 1 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (1 1 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (1 1 (:REWRITE SET::IN-SET)))
(DEPGRAPH::L1 (27 9
                  (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (22 4 (:REWRITE LEN-WHEN-ATOM))
              (16 16
                  (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
              (16 4 (:REWRITE DEFAULT-CAR))
              (11 1
                  (:REWRITE DEPGRAPH::CONSP-OF-FIRST-WHEN-CONS-LISTP))
              (10 10
                  (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (10 1 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (8 1
                 (:REWRITE DEPGRAPH::CONS-LISTP-OF-TOPOSORT-AUX))
              (7 1 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
              (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (5 5 (:REWRITE CONSP-BY-LEN))
              (4 4
                 (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER))
              (4 4
                 (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
              (4 4 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (3 3 (:REWRITE SUBSETP-TRANS2))
              (2 2 (:TYPE-PRESCRIPTION CONS-LISTP))
              (2 2
                 (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
              (2 2
                 (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
              (2 1 (:REWRITE DEFAULT-CDR))
              (2 1 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP)))
(DEPGRAPH::L2 (51 16
                  (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (51 8 (:REWRITE ALIST-KEYS-WHEN-ATOM))
              (16 8
                  (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (10 10 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
              (10 7 (:REWRITE DEFAULT-CAR))
              (9 4 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP))
              (8 8 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (8 8 (:REWRITE CONSP-BY-LEN))
              (8 8
                 (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
              (8 8
                 (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
              (7 7 (:REWRITE SUBSETP-MEMBER . 2))
              (7 7 (:REWRITE SUBSETP-MEMBER . 1))
              (7 7
                 (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
              (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (4 4 (:REWRITE MEMBER-SELF))
              (3 3 (:REWRITE DEFAULT-CDR))
              (3 3
                 (:REWRITE DEPGRAPH::CONSP-OF-FIRST-WHEN-CONS-LISTP))
              (3 3 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(DEPGRAPH::L3 (94 24 (:REWRITE DEFAULT-CAR))
              (79 25
                  (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
              (71 6
                  (:REWRITE DEPGRAPH::CONSP-OF-FIRST-WHEN-CONS-LISTP))
              (58 1 (:REWRITE SUBSETP-OF-CONS))
              (55 19 (:REWRITE LEN-WHEN-ATOM))
              (45 45
                  (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
              (36 6 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
              (33 6 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
              (28 28
                  (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
              (24 24 (:REWRITE CAR-WHEN-ALL-EQUALP))
              (24 1 (:REWRITE SUBSETP-CAR-MEMBER))
              (17 7 (:REWRITE DEFAULT-CDR))
              (14 14 (:TYPE-PRESCRIPTION TRUE-LISTP))
              (14 14 (:REWRITE CONSP-BY-LEN))
              (14 14
                  (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
              (14 14
                  (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
              (14 1 (:REWRITE SUBSETP-CONS-2))
              (9 9 (:REWRITE SUBSETP-TRANS2))
              (4 4
                 (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-LOOP))
              (3 3 (:REWRITE CONSP-OF-CDR-BY-LEN))
              (2 2 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
              (1 1 (:REWRITE SUBSETP-MEMBER . 2))
              (1 1 (:REWRITE SUBSETP-MEMBER . 1))
              (1 1
                 (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP)))
(DEPGRAPH::SUBSETP-EQUAL-OF-TOPOSORT
     (12 2 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (2 2 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (2 2 (:REWRITE CONSP-BY-LEN)))
(DEPGRAPH::COMPLETENESS-OF-TOPOSORT)
(DEPGRAPH::TOPOSORT-SET-EQUIV
     (6 1 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (2 2
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (2 1
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1 1 (:REWRITE CONSP-BY-LEN)))
(DEPGRAPH::NO-DUPLICATESP-EQUAL-OF-TOPOSORT
     (71 7
         (:REWRITE DEPGRAPH::CONSP-OF-FIRST-WHEN-CONS-LISTP))
     (56 7
         (:REWRITE DEPGRAPH::CONS-LISTP-OF-TOPOSORT-AUX))
     (55 13 (:REWRITE DEFAULT-CAR))
     (41 10 (:REWRITE DEFAULT-CDR))
     (36 13
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (23 8 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (22 4 (:REWRITE LEN-WHEN-ATOM))
     (20 20
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (20 2
         (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-ATOM))
     (20 2
         (:REWRITE NO-DUPLICATESP-EQUAL-NON-CONS))
     (16 16
         (:TYPE-PRESCRIPTION DEPGRAPH::EXTRACT-TOPOLOGICAL-ORDER))
     (14 14 (:TYPE-PRESCRIPTION CONS-LISTP))
     (14 14
         (:REWRITE CONS-LISTP-WHEN-SUBSETP-EQUAL))
     (14 14
         (:REWRITE CONS-LISTP-WHEN-MEMBER-EQUAL-OF-CONS-LIST-LISTP))
     (14 7 (:REWRITE CONS-LISTP-WHEN-NOT-CONSP))
     (13 13 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (12 12
         (:TYPE-PRESCRIPTION TRUE-LISTP-OF-ALIST-KEYS))
     (10 10 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (10 10 (:REWRITE CONSP-BY-LEN))
     (6 6
        (:REWRITE DEPGRAPH::TOPOSORT-AUX-CONSP-ON-FAILURE))
     (2 2
        (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-HIGH-DUPLICITY))
     (2 2
        (:REWRITE NO-DUPLICATESP-EQUAL-WHEN-DUPLICITY-BADGUY1))
     (2 2 (:REWRITE FN-CHECK-DEF-FORMALS)))
