(WRITE-STRINGS-TO-CHANNEL
 (6 6 (:REWRITE DEFAULT-CAR))
 (5 5 (:REWRITE DEFAULT-CDR))
 )
(STATE-P-OF-WRITE-STRINGS-TO-CHANNEL
 (5 5 (:REWRITE DEFAULT-CAR))
 (2 2 (:REWRITE DEFAULT-CDR))
 )
(STATE-P1-OF-WRITE-STRINGS-TO-CHANNEL
 (3 1 (:DEFINITION WRITE-STRINGS-TO-CHANNEL))
 (1 1 (:REWRITE DEFAULT-CDR))
 (1 1 (:REWRITE DEFAULT-CAR))
 )
(OPEN-OUTPUT-CHANNEL-P1-OF-WRITE-STRINGS-TO-CHANNEL
 (4 4 (:REWRITE DEFAULT-CAR))
 (2 2 (:REWRITE DEFAULT-CDR))
 )
(W-OF-WRITE-STRINGS-TO-CHANNEL
 (3 3 (:REWRITE DEFAULT-CAR))
 (2 2 (:REWRITE DEFAULT-CDR))
 )
