include ../../../../../Makefile-generic

ACL2 = ../../../../../../saved_acl2r

# Avoid provisional certification since we are not using Makefile-deps.
override ACL2_PCERT =

include Makefile-essence 
