include ../../../../Makefile-generic

# Matt K.: The following line was in the original Makefile, but I'm
# commenting it out because perm.lisp also certifies.
# BOOKS = instance-of-defspec closedMonoid

-include Makefile-deps
