include ../../Makefile-generic
ACL2 = ../../../saved_acl2
# Dependencies:

compress.cert: compress.lisp

encap.cert: encap.lisp
encap.cert: ../chap10/ac-example.cert

finite-sets.cert: finite-sets.lisp
finite-sets.cert: ../../ordinals/e0-ordinal.cert

how-many-soln1.cert: how-many-soln1.lisp
how-many-soln1.cert: perm.cert
how-many-soln1.cert: ../../arithmetic/top.cert

how-many-soln2.cert: how-many-soln2.lisp
how-many-soln2.cert: perm.cert

mergesort.cert: mergesort.lisp
mergesort.cert: perm.cert
mergesort.cert: perm-append.cert

perm-append.cert: perm-append.lisp
perm-append.cert: perm.cert

perm.cert: perm.lisp

qsort.cert: qsort.lisp
qsort.cert: perm-append.cert

starters.cert: starters.lisp
starters.cert: ../../ordinals/e0-ordinal.cert

summations-book.cert: summations-book.lisp
summations-book.cert: ../../arithmetic/top-with-meta.cert

summations.cert: summations.lisp
summations.cert: ../chap10/ac-example.cert

tautology.cert: tautology.lisp
tautology.cert: ../../ordinals/e0-ordinal.cert
tautology.cert: ../../arithmetic/top.cert

xtr2.cert: xtr2.lisp
xtr2.cert: ../../arithmetic/top-with-meta.cert

xtr.cert: xtr.lisp
