include ../../../../Makefile-generic
ACL2 = ../../../../../saved_acl2

# Dependencies:

top.cert: top.lisp
top.cert: ../lib1/rtl.cert
top.cert: ../lib1/rtlarr.cert
top.cert: ../lib1.delta1/basic.cert
top.cert: ../lib1/bits.cert
top.cert: ../lib1/log.cert
top.cert: ../lib1.delta1/float.cert
top.cert: ../lib1/reps.cert
top.cert: ../lib1.delta1/round.cert
top.cert: ../lib1/add.cert
top.cert: ../lib1.delta1/mult.cert
top.cert: ../lib1.delta1/arith.cert
top.cert: ../lib1/util.cert

