include ../../../../../Makefile-generic

# Pasted in from "make dependencies":


defmul.cert: defmul.lisp
defmul.cert: multiset.cert
defmul.cert: defmul.acl2

multiset.cert: multiset.lisp
# multiset.cert: $(ACL2_SYSTEM_BOOKS)/ordinals/e0-ordinal.cert
multiset.cert: multiset.acl2
