include ../../../../Makefile-generic

# Don't alphabetize this list!
# [Matt K.: Not sure why not, or why we even need this list!  So, I'm
# commenting it out.]
#BOOKS = float-extra2 round-extra2 mult-proofs float round mult basic-extra basic arith-extra arith bvecp-raw-helpers simple-loop-helpers-extra simple-loop-helpers bits-extra bits

-include Makefile-deps
