(VL::VL-MODULELIST-FLAT-WARNINGS-EXEC
     (6 6
        (:TYPE-PRESCRIPTION REVAPPEND-WITHOUT-GUARD)))
(VL::VL-MODULELIST-FLAT-WARNINGS (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(VL::VL-MODULELIST-FLAT-WARNINGS-EXEC-REMOVAL
     (190 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (125 30
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (70 5 (:REWRITE REV-WHEN-NOT-CONSP))
     (70 5 (:REWRITE REV-UNDER-IFF))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (25 25 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (25 25 (:REWRITE CONSP-BY-LEN))
     (20 20 (:TYPE-PRESCRIPTION REV))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(VL::SET-EQUIV-CONGRUENCE-OVER-VL-MODULELIST-FLAT-WARNINGS)
(VL::SUBSETP-OF-VL-MODULELIST-FLAT-WARNINGS-WHEN-SUBSETP)
(VL::MEMBER-IN-VL-MODULELIST-FLAT-WARNINGS)
(VL::VL-MODULELIST-FLAT-WARNINGS-OF-LIST-FIX)
(VL::VL-MODULELIST-FLAT-WARNINGS-OF-APPEND)
(VL::VL-MODULELIST-FLAT-WARNINGS-WHEN-NOT-CONSP)
(VL::VL-MODULELIST-FLAT-WARNINGS-OF-CONS)
(VL::VL-MODULELIST-FLAT-WARNINGS-EXEC
     (22 2
         (:REWRITE VL::VL-MODULE-P-WHEN-VL-MAYBE-MODULE-P))
     (18 1
         (:REWRITE VL::VL-MAYBE-MODULE-P-WHEN-VL-MODULE-P))
     (8 4
        (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
     (8 2
        (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
     (6 6 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (3 3 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (2 2
        (:TYPE-PRESCRIPTION VL::VL-MAYBE-MODULE-P))
     (2 2
        (:REWRITE VL::VL-MODULELIST-P-WHEN-NOT-CONSP))
     (2 2 (:REWRITE SUBSETP-TRANS2))
     (2 2 (:REWRITE SUBSETP-TRANS))
     (2 2
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 1))
     (2 2 (:REWRITE CONSP-BY-LEN))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR)))
(VL::VL-MODULELIST-FLAT-WARNINGS
     (91 6
         (:REWRITE VL::VL-MODULELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (70 5 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (38 18
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (20 20 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (17 17 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (17 17 (:REWRITE CONSP-BY-LEN))
     (15 1 (:REWRITE REV-WHEN-NOT-CONSP))
     (14 1
         (:REWRITE VL::VL-MODULELIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:TYPE-PRESCRIPTION LISTP))
     (2 2
        (:REWRITE VL::VL-MODULELIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-WARNINGLIST-P-OF-VL-MODULELIST-FLAT-WARNINGS
     (359 38
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (242 3
          (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
     (232 20
          (:REWRITE VL::VL-MODULELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (143 1 (:REWRITE SUBSETP-APPEND1))
     (126 4 (:REWRITE APPEND-UNDER-IFF))
     (108 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (50 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (43 43
         (:TYPE-PRESCRIPTION VL::VL-MODULELIST-FLAT-WARNINGS))
     (42 3 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (31 31 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (31 31 (:REWRITE CONSP-BY-LEN))
     (22 2
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (16 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-UDPLIST-FLAT-WARNINGS-EXEC
     (6 6
        (:TYPE-PRESCRIPTION REVAPPEND-WITHOUT-GUARD)))
(VL::VL-UDPLIST-FLAT-WARNINGS (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(VL::VL-UDPLIST-FLAT-WARNINGS-EXEC-REMOVAL
     (190 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (125 30
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (70 5 (:REWRITE REV-WHEN-NOT-CONSP))
     (70 5 (:REWRITE REV-UNDER-IFF))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (25 25 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (25 25 (:REWRITE CONSP-BY-LEN))
     (20 20 (:TYPE-PRESCRIPTION REV))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(VL::SET-EQUIV-CONGRUENCE-OVER-VL-UDPLIST-FLAT-WARNINGS)
(VL::SUBSETP-OF-VL-UDPLIST-FLAT-WARNINGS-WHEN-SUBSETP)
(VL::MEMBER-IN-VL-UDPLIST-FLAT-WARNINGS)
(VL::VL-UDPLIST-FLAT-WARNINGS-OF-LIST-FIX)
(VL::VL-UDPLIST-FLAT-WARNINGS-OF-APPEND)
(VL::VL-UDPLIST-FLAT-WARNINGS-WHEN-NOT-CONSP)
(VL::VL-UDPLIST-FLAT-WARNINGS-OF-CONS)
(VL::VL-UDPLIST-FLAT-WARNINGS-EXEC
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (4 2
        (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 1
        (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
     (2 2
        (:REWRITE VL::VL-UDPLIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 1))
     (2 2 (:REWRITE CONSP-BY-LEN))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(VL::VL-UDPLIST-FLAT-WARNINGS
     (91 6
         (:REWRITE VL::VL-UDPLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (70 5 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (38 18
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (20 20 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (17 17 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (17 17 (:REWRITE CONSP-BY-LEN))
     (15 1 (:REWRITE REV-WHEN-NOT-CONSP))
     (14 1
         (:REWRITE VL::VL-UDPLIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:TYPE-PRESCRIPTION LISTP))
     (2 2
        (:REWRITE VL::VL-UDPLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-WARNINGLIST-P-OF-VL-UDPLIST-FLAT-WARNINGS
     (359 38
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (242 3
          (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
     (232 20
          (:REWRITE VL::VL-UDPLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (143 1 (:REWRITE SUBSETP-APPEND1))
     (126 4 (:REWRITE APPEND-UNDER-IFF))
     (108 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (50 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (43 43
         (:TYPE-PRESCRIPTION VL::VL-UDPLIST-FLAT-WARNINGS))
     (42 3 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (31 31 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (31 31 (:REWRITE CONSP-BY-LEN))
     (22 2
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (16 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-PROGRAMLIST-FLAT-WARNINGS-EXEC
     (6 6
        (:TYPE-PRESCRIPTION REVAPPEND-WITHOUT-GUARD)))
(VL::VL-PROGRAMLIST-FLAT-WARNINGS (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(VL::VL-PROGRAMLIST-FLAT-WARNINGS-EXEC-REMOVAL
     (190 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (125 30
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (70 5 (:REWRITE REV-WHEN-NOT-CONSP))
     (70 5 (:REWRITE REV-UNDER-IFF))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (25 25 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (25 25 (:REWRITE CONSP-BY-LEN))
     (20 20 (:TYPE-PRESCRIPTION REV))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(VL::SET-EQUIV-CONGRUENCE-OVER-VL-PROGRAMLIST-FLAT-WARNINGS)
(VL::SUBSETP-OF-VL-PROGRAMLIST-FLAT-WARNINGS-WHEN-SUBSETP)
(VL::MEMBER-IN-VL-PROGRAMLIST-FLAT-WARNINGS)
(VL::VL-PROGRAMLIST-FLAT-WARNINGS-OF-LIST-FIX)
(VL::VL-PROGRAMLIST-FLAT-WARNINGS-OF-APPEND)
(VL::VL-PROGRAMLIST-FLAT-WARNINGS-WHEN-NOT-CONSP)
(VL::VL-PROGRAMLIST-FLAT-WARNINGS-OF-CONS)
(VL::VL-PROGRAMLIST-FLAT-WARNINGS-EXEC
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (4 2
        (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 1
        (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
     (2 2
        (:REWRITE VL::VL-PROGRAMLIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 1))
     (2 2 (:REWRITE CONSP-BY-LEN))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(VL::VL-PROGRAMLIST-FLAT-WARNINGS
     (91 6
         (:REWRITE VL::VL-PROGRAMLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (70 5 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (38 18
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (20 20 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (17 17 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (17 17 (:REWRITE CONSP-BY-LEN))
     (15 1 (:REWRITE REV-WHEN-NOT-CONSP))
     (14 1
         (:REWRITE VL::VL-PROGRAMLIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:TYPE-PRESCRIPTION LISTP))
     (2 2
        (:REWRITE VL::VL-PROGRAMLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-WARNINGLIST-P-OF-VL-PROGRAMLIST-FLAT-WARNINGS
     (359 38
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (242 3
          (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
     (232 20
          (:REWRITE VL::VL-PROGRAMLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (143 1 (:REWRITE SUBSETP-APPEND1))
     (126 4 (:REWRITE APPEND-UNDER-IFF))
     (108 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (50 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (43 43
         (:TYPE-PRESCRIPTION VL::VL-PROGRAMLIST-FLAT-WARNINGS))
     (42 3 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (31 31 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (31 31 (:REWRITE CONSP-BY-LEN))
     (22 2
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (16 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-CLASSLIST-FLAT-WARNINGS-EXEC
     (6 6
        (:TYPE-PRESCRIPTION REVAPPEND-WITHOUT-GUARD)))
(VL::VL-CLASSLIST-FLAT-WARNINGS (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(VL::VL-CLASSLIST-FLAT-WARNINGS-EXEC-REMOVAL
     (190 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (125 30
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (70 5 (:REWRITE REV-WHEN-NOT-CONSP))
     (70 5 (:REWRITE REV-UNDER-IFF))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (25 25 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (25 25 (:REWRITE CONSP-BY-LEN))
     (20 20 (:TYPE-PRESCRIPTION REV))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(VL::SET-EQUIV-CONGRUENCE-OVER-VL-CLASSLIST-FLAT-WARNINGS)
(VL::SUBSETP-OF-VL-CLASSLIST-FLAT-WARNINGS-WHEN-SUBSETP)
(VL::MEMBER-IN-VL-CLASSLIST-FLAT-WARNINGS)
(VL::VL-CLASSLIST-FLAT-WARNINGS-OF-LIST-FIX)
(VL::VL-CLASSLIST-FLAT-WARNINGS-OF-APPEND)
(VL::VL-CLASSLIST-FLAT-WARNINGS-WHEN-NOT-CONSP)
(VL::VL-CLASSLIST-FLAT-WARNINGS-OF-CONS)
(VL::VL-CLASSLIST-FLAT-WARNINGS-EXEC
     (5 1
        (:REWRITE VL::VL-CLASS-P-BY-TAG-WHEN-VL-MODELEMENT-P))
     (5 1
        (:REWRITE VL::VL-CLASS-P-BY-TAG-WHEN-VL-CTXELEMENT-P))
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (4 2
        (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
     (4 2 (:REWRITE SET::DOUBLE-CONTAINMENT))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 1
        (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
     (2 2 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (2 2
        (:REWRITE VL::VL-CLASSLIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 1))
     (2 2 (:REWRITE CONSP-BY-LEN))
     (2 2 (:META CANCEL_TIMES-EQUAL-CORRECT))
     (2 2 (:META CANCEL_PLUS-EQUAL-CORRECT))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(VL::VL-CLASSLIST-FLAT-WARNINGS
     (91 6
         (:REWRITE VL::VL-CLASSLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (70 5 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (38 18
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (20 20 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (17 17 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (17 17 (:REWRITE CONSP-BY-LEN))
     (15 1 (:REWRITE REV-WHEN-NOT-CONSP))
     (14 1
         (:REWRITE VL::VL-CLASSLIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:TYPE-PRESCRIPTION LISTP))
     (2 2
        (:REWRITE VL::VL-CLASSLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-WARNINGLIST-P-OF-VL-CLASSLIST-FLAT-WARNINGS
     (359 38
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (242 3
          (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
     (232 20
          (:REWRITE VL::VL-CLASSLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (143 1 (:REWRITE SUBSETP-APPEND1))
     (126 4 (:REWRITE APPEND-UNDER-IFF))
     (108 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (50 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (43 43
         (:TYPE-PRESCRIPTION VL::VL-CLASSLIST-FLAT-WARNINGS))
     (42 3 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (31 31 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (31 31 (:REWRITE CONSP-BY-LEN))
     (22 2
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (16 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-INTERFACELIST-FLAT-WARNINGS-EXEC
     (6 6
        (:TYPE-PRESCRIPTION REVAPPEND-WITHOUT-GUARD)))
(VL::VL-INTERFACELIST-FLAT-WARNINGS (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(VL::VL-INTERFACELIST-FLAT-WARNINGS-EXEC-REMOVAL
     (190 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (125 30
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (70 5 (:REWRITE REV-WHEN-NOT-CONSP))
     (70 5 (:REWRITE REV-UNDER-IFF))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (25 25 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (25 25 (:REWRITE CONSP-BY-LEN))
     (20 20 (:TYPE-PRESCRIPTION REV))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(VL::SET-EQUIV-CONGRUENCE-OVER-VL-INTERFACELIST-FLAT-WARNINGS)
(VL::SUBSETP-OF-VL-INTERFACELIST-FLAT-WARNINGS-WHEN-SUBSETP)
(VL::MEMBER-IN-VL-INTERFACELIST-FLAT-WARNINGS)
(VL::VL-INTERFACELIST-FLAT-WARNINGS-OF-LIST-FIX)
(VL::VL-INTERFACELIST-FLAT-WARNINGS-OF-APPEND)
(VL::VL-INTERFACELIST-FLAT-WARNINGS-WHEN-NOT-CONSP)
(VL::VL-INTERFACELIST-FLAT-WARNINGS-OF-CONS)
(VL::VL-INTERFACELIST-FLAT-WARNINGS-EXEC
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (4 2
        (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 1
        (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
     (2 2
        (:REWRITE VL::VL-INTERFACELIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 1))
     (2 2 (:REWRITE CONSP-BY-LEN))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(VL::VL-INTERFACELIST-FLAT-WARNINGS
     (91 6
         (:REWRITE VL::VL-INTERFACELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (70 5 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (38 18
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (20 20 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (17 17 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (17 17 (:REWRITE CONSP-BY-LEN))
     (15 1 (:REWRITE REV-WHEN-NOT-CONSP))
     (14 1
         (:REWRITE VL::VL-INTERFACELIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:TYPE-PRESCRIPTION LISTP))
     (2 2
        (:REWRITE VL::VL-INTERFACELIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-WARNINGLIST-P-OF-VL-INTERFACELIST-FLAT-WARNINGS
     (359 38
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (242 3
          (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
     (232 20
          (:REWRITE VL::VL-INTERFACELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (143 1 (:REWRITE SUBSETP-APPEND1))
     (126 4 (:REWRITE APPEND-UNDER-IFF))
     (108 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (50 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (43 43
         (:TYPE-PRESCRIPTION VL::VL-INTERFACELIST-FLAT-WARNINGS))
     (42 3 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (31 31 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (31 31 (:REWRITE CONSP-BY-LEN))
     (22 2
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (16 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-CONFIGLIST-FLAT-WARNINGS-EXEC
     (6 6
        (:TYPE-PRESCRIPTION REVAPPEND-WITHOUT-GUARD)))
(VL::VL-CONFIGLIST-FLAT-WARNINGS (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(VL::VL-CONFIGLIST-FLAT-WARNINGS-EXEC-REMOVAL
     (190 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (125 30
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (70 5 (:REWRITE REV-WHEN-NOT-CONSP))
     (70 5 (:REWRITE REV-UNDER-IFF))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (25 25 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (25 25 (:REWRITE CONSP-BY-LEN))
     (20 20 (:TYPE-PRESCRIPTION REV))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(VL::SET-EQUIV-CONGRUENCE-OVER-VL-CONFIGLIST-FLAT-WARNINGS)
(VL::SUBSETP-OF-VL-CONFIGLIST-FLAT-WARNINGS-WHEN-SUBSETP)
(VL::MEMBER-IN-VL-CONFIGLIST-FLAT-WARNINGS)
(VL::VL-CONFIGLIST-FLAT-WARNINGS-OF-LIST-FIX)
(VL::VL-CONFIGLIST-FLAT-WARNINGS-OF-APPEND)
(VL::VL-CONFIGLIST-FLAT-WARNINGS-WHEN-NOT-CONSP)
(VL::VL-CONFIGLIST-FLAT-WARNINGS-OF-CONS)
(VL::VL-CONFIGLIST-FLAT-WARNINGS-EXEC
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (4 2
        (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 1
        (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
     (2 2
        (:REWRITE VL::VL-CONFIGLIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 1))
     (2 2 (:REWRITE CONSP-BY-LEN))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(VL::VL-CONFIGLIST-FLAT-WARNINGS
     (91 6
         (:REWRITE VL::VL-CONFIGLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (70 5 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (38 18
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (20 20 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (17 17 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (17 17 (:REWRITE CONSP-BY-LEN))
     (15 1 (:REWRITE REV-WHEN-NOT-CONSP))
     (14 1
         (:REWRITE VL::VL-CONFIGLIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:TYPE-PRESCRIPTION LISTP))
     (2 2
        (:REWRITE VL::VL-CONFIGLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-WARNINGLIST-P-OF-VL-CONFIGLIST-FLAT-WARNINGS
     (359 38
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (242 3
          (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
     (232 20
          (:REWRITE VL::VL-CONFIGLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (143 1 (:REWRITE SUBSETP-APPEND1))
     (126 4 (:REWRITE APPEND-UNDER-IFF))
     (108 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (50 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (43 43
         (:TYPE-PRESCRIPTION VL::VL-CONFIGLIST-FLAT-WARNINGS))
     (42 3 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (31 31 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (31 31 (:REWRITE CONSP-BY-LEN))
     (22 2
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (16 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-PACKAGELIST-FLAT-WARNINGS-EXEC
     (6 6
        (:TYPE-PRESCRIPTION REVAPPEND-WITHOUT-GUARD)))
(VL::VL-PACKAGELIST-FLAT-WARNINGS (1 1 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(VL::VL-PACKAGELIST-FLAT-WARNINGS-EXEC-REMOVAL
     (190 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (125 30
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (70 5 (:REWRITE REV-WHEN-NOT-CONSP))
     (70 5 (:REWRITE REV-UNDER-IFF))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (60 60
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (25 25 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (25 25
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (25 25 (:REWRITE CONSP-BY-LEN))
     (20 20 (:TYPE-PRESCRIPTION REV))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (10 10 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(VL::SET-EQUIV-CONGRUENCE-OVER-VL-PACKAGELIST-FLAT-WARNINGS)
(VL::SUBSETP-OF-VL-PACKAGELIST-FLAT-WARNINGS-WHEN-SUBSETP)
(VL::MEMBER-IN-VL-PACKAGELIST-FLAT-WARNINGS)
(VL::VL-PACKAGELIST-FLAT-WARNINGS-OF-LIST-FIX)
(VL::VL-PACKAGELIST-FLAT-WARNINGS-OF-APPEND)
(VL::VL-PACKAGELIST-FLAT-WARNINGS-WHEN-NOT-CONSP)
(VL::VL-PACKAGELIST-FLAT-WARNINGS-OF-CONS)
(VL::VL-PACKAGELIST-FLAT-WARNINGS-EXEC
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (4 4
        (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (4 2
        (:TYPE-PRESCRIPTION TRUE-LISTP-MEMBER-EQUAL))
     (4 2
        (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (4 1
        (:REWRITE VL::MEMBER-EQUAL-WHEN-MEMBER-EQUAL-OF-CDR-UNDER-IFF))
     (2 2
        (:REWRITE VL::VL-PACKAGELIST-P-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                  . 1))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 2))
     (2 2
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                  . 1))
     (2 2 (:REWRITE CONSP-BY-LEN))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1
        (:REWRITE MEMBER-EQUAL-WHEN-ALL-EQUALP))
     (1 1 (:REWRITE DEFAULT-CDR))
     (1 1 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE CAR-WHEN-ALL-EQUALP)))
(VL::VL-PACKAGELIST-FLAT-WARNINGS
     (91 6
         (:REWRITE VL::VL-PACKAGELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (70 5 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (38 18
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (36 36
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (20 20 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (17 17 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (17 17
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (17 17 (:REWRITE CONSP-BY-LEN))
     (15 1 (:REWRITE REV-WHEN-NOT-CONSP))
     (14 1
         (:REWRITE VL::VL-PACKAGELIST-P-WHEN-NOT-CONSP))
     (7 7 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (4 4 (:TYPE-PRESCRIPTION LISTP))
     (2 2
        (:REWRITE VL::VL-PACKAGELIST-P-WHEN-SUBSETP-EQUAL))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-WARNINGLIST-P-OF-VL-PACKAGELIST-FLAT-WARNINGS
     (359 38
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (242 3
          (:REWRITE VL::VL-WARNINGLIST-P-WHEN-NOT-CONSP))
     (232 20
          (:REWRITE VL::VL-PACKAGELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (143 1 (:REWRITE SUBSETP-APPEND1))
     (126 4 (:REWRITE APPEND-UNDER-IFF))
     (108 3 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (76 76
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (50 3
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (43 43
         (:TYPE-PRESCRIPTION VL::VL-PACKAGELIST-FLAT-WARNINGS))
     (42 3 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (31 31 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (31 31
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (31 31 (:REWRITE CONSP-BY-LEN))
     (22 2
         (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
     (16 16 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (16 3 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (7 7 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE CAR-WHEN-ALL-EQUALP))
     (6 6 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (4 4 (:REWRITE CONSP-OF-CDDR-BY-LEN)))
(VL::VL-DESIGN-FLAT-WARNINGS
     (950 15
          (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (869 87
          (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (555 20 (:REWRITE APPEND-UNDER-IFF))
     (213 39 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (174 174
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (174 174
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (106 15
          (:REWRITE VL::VL-PROGRAMLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (105 14
          (:REWRITE VL::VL-CLASSLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (84 14 (:REWRITE REV-WHEN-NOT-CONSP))
     (79 14
         (:REWRITE VL::VL-INTERFACELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (76 11
         (:REWRITE VL::VL-PACKAGELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (60 6 (:REWRITE REV-UNDER-IFF))
     (27 27 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (27 27
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (27 27
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (27 27
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (27 27
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (27 27
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (27 27
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (27 27 (:REWRITE CONSP-BY-LEN))
     (24 11
         (:REWRITE VL::VL-UDPLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (19 19 (:TYPE-PRESCRIPTION CONSP-REVERSE))
     (18 5
         (:REWRITE VL::VL-MODULELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (18 5
         (:REWRITE VL::VL-CONFIGLIST-FLAT-WARNINGS-WHEN-NOT-CONSP)))
(VL::VL-WARNINGLIST-P-OF-VL-DESIGN-FLAT-WARNINGS
     (1416 17
           (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (1161 90
           (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (889 31 (:REWRITE APPEND-UNDER-IFF))
     (474 158
          (:TYPE-PRESCRIPTION TRUE-LISTP-APPEND))
     (180 180
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (180 180
          (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (158 158 (:TYPE-PRESCRIPTION BINARY-APPEND))
     (157 14
          (:REWRITE VL::VL-PROGRAMLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (144 14
          (:REWRITE VL::VL-PACKAGELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (113 9
          (:REWRITE VL::VL-UDPLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (106 106
          (:TYPE-PRESCRIPTION VL::VL-PACKAGELIST-FLAT-WARNINGS))
     (103 103
          (:TYPE-PRESCRIPTION VL::VL-PROGRAMLIST-FLAT-WARNINGS))
     (77 17 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (60 8
         (:REWRITE VL::VL-INTERFACELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (55 55
         (:TYPE-PRESCRIPTION VL::VL-INTERFACELIST-FLAT-WARNINGS))
     (54 54
         (:TYPE-PRESCRIPTION VL::VL-UDPLIST-FLAT-WARNINGS))
     (44 44
         (:TYPE-PRESCRIPTION VL::VL-CONFIGLIST-FLAT-WARNINGS))
     (44 5
         (:REWRITE VL::VL-MODULELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (38 38 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (38 38
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (38 38 (:REWRITE CONSP-BY-LEN))
     (31 31
         (:TYPE-PRESCRIPTION VL::VL-MODULELIST-FLAT-WARNINGS))
     (20 7
         (:REWRITE VL::VL-CONFIGLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (15 2
         (:REWRITE VL::VL-CLASSLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (12 12
         (:REWRITE VL::VL-WARNINGLIST-P-WHEN-SUBSETP-EQUAL))
     (4 4
        (:TYPE-PRESCRIPTION VL::VL-CLASSLIST-FLAT-WARNINGS)))
(VL::VL-DESIGN-FLAT-WARNINGS-OF-VL-DESIGN-FIX-X
     (132 12 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (76 26
         (:REWRITE CONSP-UNDER-IFF-WHEN-TRUE-LISTP))
     (52 52
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-CONS-LISTP))
     (52 52
         (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
     (30 4
         (:REWRITE VL::VL-UDPLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (30 4
         (:REWRITE VL::VL-PROGRAMLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (30 4
         (:REWRITE VL::VL-PACKAGELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (30 4
         (:REWRITE VL::VL-MODULELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (30 4
         (:REWRITE VL::VL-INTERFACELIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (30 4
         (:REWRITE VL::VL-CLASSLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (28 2
         (:REWRITE VL::VL-CONFIGLIST-FLAT-WARNINGS-WHEN-NOT-CONSP))
     (14 14 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (14 14
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 2))
     (14 14
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-GENCASELIST-P
                   . 1))
     (14 14
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 2))
     (14 14
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-COMMENTMAP-P
                   . 1))
     (14 14
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 2))
     (14 14
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-CASELIST-P
                   . 1))
     (14 14 (:REWRITE CONSP-BY-LEN))
     (8 8
        (:TYPE-PRESCRIPTION VL::VL-UDPLIST-FLAT-WARNINGS))
     (8 8
        (:TYPE-PRESCRIPTION VL::VL-PROGRAMLIST-FLAT-WARNINGS))
     (8 8
        (:TYPE-PRESCRIPTION VL::VL-PACKAGELIST-FLAT-WARNINGS))
     (8 8
        (:TYPE-PRESCRIPTION VL::VL-MODULELIST-FLAT-WARNINGS))
     (8 8
        (:TYPE-PRESCRIPTION VL::VL-INTERFACELIST-FLAT-WARNINGS))
     (8 8
        (:TYPE-PRESCRIPTION VL::VL-CLASSLIST-FLAT-WARNINGS))
     (8 1
        (:REWRITE VL::VL-DESIGN-FIX-WHEN-VL-DESIGN-P))
     (5 1
        (:REWRITE VL::VL-DESIGN-P-WHEN-VL-MAYBE-DESIGN-P))
     (3 3 (:TYPE-PRESCRIPTION VL::VL-DESIGN-P))
     (2 2
        (:TYPE-PRESCRIPTION VL::VL-MAYBE-DESIGN-P))
     (2 1
        (:REWRITE VL::VL-MAYBE-DESIGN-P-WHEN-VL-DESIGN-P)))
(VL::VL-DESIGN-FLAT-WARNINGS-VL-DESIGN-EQUIV-CONGRUENCE-ON-X)
