include ../../../../Makefile-generic

defcoerce.cert: defcoerce.lisp
defcoerce.cert: generic.cert
# defcoerce.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-2/meta/top.cert

defpun-exec.cert: defpun-exec.lisp
# defpun-exec.cert: defpun.cert # from a multi-line comment
# defpun-exec.cert: $(ACL2_SYSTEM_BOOKS)/misc/defpun.cert

generic.cert: generic.lisp
# generic.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-2/meta/top.cert
