# EDIT THE FOLLOWING by replacing the directory with your ACL2 distributed
# books directory.  You are welcome to omit this line, or not as you prefer, in
# your contribution.
ACL2_SYSTEM_BOOKS ?= ../../../..

include ${ACL2_SYSTEM_BOOKS}/Makefile-generic
ACL2 = $(ACL2_SYSTEM_BOOKS)/../saved_acl2

Rimlinger.cert: Rimlinger.lisp
