(SVL::WEAK-SVEX-SIMPLIFY-PRELOADED-P)
(RP::SIMPLE-META-RULE-ALISTP-OF-CREATE-SIMPLE-META-RULES-ALIST-AUX
     (77 69 (:REWRITE DEFAULT-CAR))
     (44 11 (:REWRITE O-P-O-INFP-CAR))
     (34 30 (:REWRITE DEFAULT-CDR))
     (22 22 (:TYPE-PRESCRIPTION O-P))
     (20 10 (:REWRITE SYMBOL-FIX-WHEN-SYMBOLP))
     (18 18
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (11 11 (:REWRITE O-P-DEF-O-FINP-1)))
(RP::SIMPLE-META-RULE-ALISTP-OF-CREATE-SIMPLE-META-RULES-ALIST)
(SVL::SVEX-SIMPLIFY-PRELOAD-FN
     (19 15 (:REWRITE DEFAULT-CAR))
     (12 3 (:REWRITE O-P-O-INFP-CAR))
     (9 9 (:REWRITE DEFAULT-CDR))
     (9 1 (:DEFINITION ASSOC-EQUAL))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (4 4
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (3 3 (:REWRITE O-P-DEF-O-FINP-1))
     (2 1 (:DEFINITION NTH))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP)))
(SVL::SVEX-SIMPLIFY-PRELOADED-GUARD)
(SVL::SVEX-RW-FREE-PRELOAD (36 9 (:REWRITE O-P-O-INFP-CAR))
                           (18 18 (:TYPE-PRESCRIPTION O-P))
                           (18 14 (:REWRITE DEFAULT-CDR))
                           (16 12 (:REWRITE DEFAULT-CAR))
                           (14 1 (:DEFINITION SYMBOL-ALISTP))
                           (14 1
                               (:DEFINITION RP::RULE-LIST-LIST-SYNTAXP))
                           (12 1 (:DEFINITION STRIP-CDRS))
                           (12 1 (:DEFINITION STRIP-CARS))
                           (11 1 (:DEFINITION ALISTP))
                           (9 9 (:REWRITE O-P-DEF-O-FINP-1))
                           (8 1 (:DEFINITION RP::RULE-LIST-SYNTAXP))
                           (7 1 (:DEFINITION SYMBOL-LISTP))
                           (2 2 (:TYPE-PRESCRIPTION STRIP-CDRS))
                           (2 2 (:TYPE-PRESCRIPTION STRIP-CARS))
                           (2 2
                              (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
                           (2 2 (:REWRITE FN-CHECK-DEF-FORMALS))
                           (1 1
                              (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
                           (1 1
                              (:TYPE-PRESCRIPTION RP::RULE-LIST-SYNTAXP)))
(SVL::RP-STATEP-UPDATE-NOT-SIMPLIFIED-ACTION
     (28 28 (:REWRITE NTH-WHEN-PREFIXP))
     (27 27 (:REWRITE DEFAULT-CDR))
     (24 6 (:REWRITE O-P-O-INFP-CAR))
     (9 9 (:REWRITE DEFAULT-CAR))
     (6 6 (:REWRITE O-P-DEF-O-FINP-1))
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 2 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (3 1 (:DEFINITION UPDATE-NTH))
     (3 1 (:DEFINITION TRUE-LISTP))
     (2 2
        (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (2 2
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (2 2
        (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (2 2 (:REWRITE DEFAULT-+-1)))
(SVL::RP-STATEP-RP-STATE-NEW-RUN
     (46 46 (:REWRITE NTH-WHEN-PREFIXP))
     (36 24 (:REWRITE DEFAULT-CDR))
     (36 4 (:DEFINITION UPDATE-NTH))
     (21 9 (:REWRITE DEFAULT-CAR))
     (21 3 (:DEFINITION ALISTP))
     (12 3 (:REWRITE O-P-O-INFP-CAR))
     (6 6 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1))
     (4 2 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE O-P-DEF-O-FINP-1))
     (3 1 (:DEFINITION TRUE-LISTP))
     (2 2
        (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (2 2
        (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (2 2 (:REWRITE DEFAULT-+-1))
     (1 1
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP)))
(SVL::SYMBOLP-NOT-SIMPLIFIED-ACTION)
(SVL::TO-SVEX-FNC)
(SVL::SVEX-P-OF-TO-SVEX-FNC.RES
     (6148 6148 (:REWRITE DEFAULT-CDR))
     (5218 200
           (:REWRITE SVL::INTEGERP-IMPLIES-4VECP))
     (4808 80 (:DEFINITION APPLY$-BADGEP))
     (4301 384 (:DEFINITION MEMBER-EQUAL))
     (3660 36 (:DEFINITION SUBSETP-EQUAL))
     (2892 144
           (:REWRITE SV::SVAR-P-OF-CAR-WHEN-SVARLIST-P))
     (2710 196
           (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (2540 48
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (2428 32
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (2124 862
           (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (2088 136
           (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (2028 300
           (:REWRITE SV::SVARLIST-P-OF-CDR-WHEN-SVARLIST-P))
     (2024 150
           (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
     (1804 1804 (:REWRITE DEFAULT-CAR))
     (1792 40 (:REWRITE SUBSETP-REFLEXIVE-LEMMA))
     (1298 200
           (:REWRITE SV::4VEC-P-WHEN-MAYBE-4VEC-P))
     (998 100
          (:REWRITE SV::MAYBE-4VEC-P-WHEN-4VEC-P))
     (888 888
          (:REWRITE SV::SVARLIST-P-WHEN-SUBSETP-EQUAL))
     (760 760 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (663 663
          (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (661 661 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (496 496
          (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (444 444
          (:REWRITE SV::SVARLIST-P-WHEN-NOT-CONSP))
     (400 400
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (396 396
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (392 98 (:REWRITE O-P-O-INFP-CAR))
     (300 300
          (:TYPE-PRESCRIPTION SV::MAYBE-4VEC-P))
     (300 300
          (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (300 200 (:REWRITE SVL::BITP-IMPLIES-4VECP))
     (274 274 (:TYPE-PRESCRIPTION SV::4VEC-P))
     (268 268
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (256 256 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (256 80 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (248 248
          (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (160 40
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (144 8 (:DEFINITION LOOP$-AS))
     (111 111 (:TYPE-PRESCRIPTION SV::SVAR-P))
     (100 100 (:TYPE-PRESCRIPTION BITP))
     (98 98 (:REWRITE O-P-DEF-O-FINP-1))
     (87 87
         (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (80 40
         (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (64 64 (:TYPE-PRESCRIPTION NATP))
     (50 50
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (50 50
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (50 50 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (48 8 (:DEFINITION CDR-LOOP$-AS-TUPLE))
     (48 8 (:DEFINITION CAR-LOOP$-AS-TUPLE))
     (40 8 (:DEFINITION EMPTY-LOOP$-AS-TUPLEP))
     (37 37 (:TYPE-PRESCRIPTION SV::FNSYM-P))
     (32 16
         (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (24 8 (:DEFINITION ALL-NILS))
     (16 16 (:TYPE-PRESCRIPTION LOOP$-AS))
     (16 8 (:DEFINITION TRUE-LISTP))
     (16 8 (:DEFINITION LEN))
     (8 8
        (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (8 8 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS)))
(SVL::SVEXL-NODE-P-OF-TO-SVEX-FNC.RES
     (4239 4239 (:REWRITE DEFAULT-CDR))
     (2609 100
           (:REWRITE SVL::INTEGERP-IMPLIES-4VECP))
     (2404 40 (:DEFINITION APPLY$-BADGEP))
     (1668 16 (:DEFINITION SUBSETP-EQUAL))
     (1480 120 (:DEFINITION MEMBER-EQUAL))
     (1446 72
           (:REWRITE SV::SVAR-P-OF-CAR-WHEN-SVARLIST-P))
     (1355 98
           (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (1270 24
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (1259 1259 (:REWRITE DEFAULT-CAR))
     (1214 16
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (1014 150
           (:REWRITE SV::SVARLIST-P-OF-CDR-WHEN-SVARLIST-P))
     (1012 75
           (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
     (932 64
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (888 16 (:REWRITE SUBSETP-REFLEXIVE-LEMMA))
     (819 782
          (:REWRITE SVL::SVEXL-NODELIST-P-WHEN-NOT-CONSP))
     (649 100
          (:REWRITE SV::4VEC-P-WHEN-MAYBE-4VEC-P))
     (499 50
          (:REWRITE SV::MAYBE-4VEC-P-WHEN-4VEC-P))
     (444 444
          (:REWRITE SV::SVARLIST-P-WHEN-SUBSETP-EQUAL))
     (248 248
          (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (240 240 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (222 222
          (:REWRITE SV::SVARLIST-P-WHEN-NOT-CONSP))
     (208 208 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (200 200
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (196 49 (:REWRITE O-P-O-INFP-CAR))
     (192 192
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (150 150
          (:TYPE-PRESCRIPTION SV::MAYBE-4VEC-P))
     (150 150
          (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (150 100 (:REWRITE SVL::BITP-IMPLIES-4VECP))
     (128 128 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (128 128
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (128 40 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (124 124 (:TYPE-PRESCRIPTION SV::4VEC-P))
     (124 124
          (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (80 20
         (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (50 50 (:TYPE-PRESCRIPTION BITP))
     (49 49 (:REWRITE O-P-DEF-O-FINP-1))
     (44 44 (:TYPE-PRESCRIPTION NATP))
     (40 20
         (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (36 36 (:TYPE-PRESCRIPTION SV::SVAR-P))
     (36 36 (:TYPE-PRESCRIPTION SV::FNSYM-P))
     (25 25
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (25 25
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (25 25 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (16 16 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (16 16
         (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (16 8
         (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (12 4 (:DEFINITION ALL-NILS))
     (8 4 (:DEFINITION TRUE-LISTP))
     (8 4 (:DEFINITION LEN))
     (4 4
        (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (4 4 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS)))
(SVL::EX-FROM-RP-IS-NONNIL (189 189 (:REWRITE DEFAULT-CDR))
                           (115 115 (:REWRITE DEFAULT-CAR))
                           (60 15 (:REWRITE O-P-O-INFP-CAR))
                           (15 15 (:REWRITE O-P-DEF-O-FINP-1))
                           (14 14 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
                           (10 2
                               (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
                           (2 2
                              (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP)))
(SVL::SVEX-P-TO-SVEX-FNC-QUOTE (51 51 (:REWRITE DEFAULT-CAR)))
(SVL::4VEC-TO-SVEX (939 85 (:REWRITE O<=-O-FINP-DEF))
                   (314 66 (:REWRITE O-P-O-INFP-CAR))
                   (245 97 (:REWRITE AC-<))
                   (182 95 (:REWRITE DEFAULT-<-2))
                   (174 48 (:REWRITE O-FIRST-EXPT-<))
                   (130 85 (:REWRITE O-INFP-O-FINP-O<=))
                   (116 66 (:REWRITE O-P-DEF-O-FINP-1))
                   (113 95
                        (:REWRITE RP::EQUALITY-MEASURE-LEMMA3))
                   (113 95
                        (:REWRITE RP::EQUALITY-MEASURE-LEMMA1))
                   (96 48 (:REWRITE O-FIRST-COEFF-<))
                   (95 95 (:REWRITE DEFAULT-<-1))
                   (78 39 (:REWRITE O-FIRST-EXPT-DEF-O-FINP))
                   (50 50 (:TYPE-PRESCRIPTION O-FINP))
                   (47 47
                       (:REWRITE RP::EQUALITY-MEASURE-LEMMA2))
                   (40 27 (:REWRITE DEFAULT-+-2))
                   (40 4
                       (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
                   (36 36
                       (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
                   (34 27 (:REWRITE DEFAULT-+-1))
                   (31 31 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
                   (27 9 (:REWRITE RP::M-MEASURE-LEMMA6))
                   (27 9 (:REWRITE RP::IS-IF-CONS-COUNT))
                   (24 4 (:REWRITE RP::RP-TERMP-CADR))
                   (9 9 (:REWRITE RP::MEASURE-LEMMA7-2))
                   (9 9 (:REWRITE RP::MEASURE-LEMMA7))
                   (9 9 (:REWRITE RP::MEASURE-LEMMA6-5))
                   (9 9 (:REWRITE RP::M-MEASURE-LEMMA11))
                   (8 8 (:REWRITE DEFAULT-UNARY-MINUS))
                   (6 6 (:REWRITE FOLD-CONSTS-IN-+))
                   (6 2
                      (:REWRITE RP::RP-TERMP-EXTRACT-FROM-RP))
                   (6 2 (:REWRITE RP::RP-TERMP-EX-FROM-RP))
                   (4 4
                      (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
                   (4 4 (:REWRITE O-INFP->NEQ-0))
                   (2 2
                      (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP)))
(SVL::4VEC-TO-SVEX-FLAG (976 88 (:REWRITE O<=-O-FINP-DEF))
                        (422 72 (:REWRITE O-P-O-INFP-CAR))
                        (255 100 (:REWRITE AC-<))
                        (206 72 (:REWRITE O-P-DEF-O-FINP-1))
                        (190 103 (:REWRITE DEFAULT-<-2))
                        (174 48 (:REWRITE O-FIRST-EXPT-<))
                        (137 88 (:REWRITE O-INFP-O-FINP-O<=))
                        (134 134 (:TYPE-PRESCRIPTION O-FINP))
                        (121 103
                             (:REWRITE RP::EQUALITY-MEASURE-LEMMA3))
                        (121 103
                             (:REWRITE RP::EQUALITY-MEASURE-LEMMA1))
                        (103 103 (:REWRITE DEFAULT-<-1))
                        (96 48 (:REWRITE O-FIRST-COEFF-<))
                        (80 8
                            (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
                        (78 39 (:REWRITE O-FIRST-EXPT-DEF-O-FINP))
                        (55 55
                            (:REWRITE RP::EQUALITY-MEASURE-LEMMA2))
                        (53 41 (:REWRITE DEFAULT-+-2))
                        (48 8 (:REWRITE RP::RP-TERMP-CADR))
                        (47 41 (:REWRITE DEFAULT-+-1))
                        (36 36
                            (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
                        (27 9 (:REWRITE RP::M-MEASURE-LEMMA6))
                        (27 9 (:REWRITE RP::IS-IF-CONS-COUNT))
                        (16 16 (:REWRITE DEFAULT-UNARY-MINUS))
                        (15 15 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
                        (12 4
                            (:REWRITE RP::RP-TERMP-EXTRACT-FROM-RP))
                        (12 4 (:REWRITE RP::RP-TERMP-EX-FROM-RP))
                        (9 9 (:REWRITE RP::MEASURE-LEMMA7-2))
                        (9 9 (:REWRITE RP::MEASURE-LEMMA7))
                        (9 9 (:REWRITE RP::MEASURE-LEMMA6-5))
                        (9 9 (:REWRITE RP::M-MEASURE-LEMMA11))
                        (8 8
                           (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
                        (8 8 (:REWRITE O-INFP->NEQ-0))
                        (6 6 (:REWRITE FOLD-CONSTS-IN-+))
                        (4 4
                           (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP)))
(FLAG::FLAG-EQUIV-LEMMA)
(SVL::4VEC-TO-SVEX-FLAG-EQUIVALENCES)
(SVL::4VEC-TO-SVEX-MEMOIZE-CONDITION)
(SVL::4VEC-TO-SVEX-MEMOIZE-CONDITION)
(SVL::FLAG-LEMMA-FOR-SVEXL-NODE-P-OF-4VEC-TO-SVEX
     (476 476
          (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (456 452
          (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (280 280
          (:REWRITE RP::EQUALITY-MEASURE-LEMMA1))
     (280 280 (:REWRITE DEFAULT-<-1))
     (210 210
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (210 198
          (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (207 54
          (:REWRITE SV::SVEX-P-OF-CAR-WHEN-SVEXLIST-P))
     (105 105 (:REWRITE SVL::BITP-IMPLIES-4VECP))
     (96 96
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (80 80 (:REWRITE O-INFP->NEQ-0))
     (59 59 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (48 48
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (40 5
         (:REWRITE SVL::SVEXL-NODE-P-OF-CAR-WHEN-SVEXL-NODELIST-P))
     (8 8 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (4 4 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (2 2 (:REWRITE RP::SYMBOLP-EX-FROM-RP)))
(SVL::SVEXL-NODE-P-OF-4VEC-TO-SVEX)
(SVL::SVEXL-NODELIST-P-OF-4VEC-TO-SVEX-LST)
(SVL::4VEC-TO-SVEX-TERMLIST-QUOTE)
(SVL::SVEXL-NODELIST-P-OF-4VEC-TO-SVEX-TERMLIST-QUOTE.RES
     (1146 134
           (:REWRITE SVL::SVEXLIST-P-IMPLIES-SVEXL-NODELIST-P))
     (969 190
          (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (836 96
          (:REWRITE SV::INTEGERP-OF-CDAR-WHEN-SVAR-BOOLMASKS-P))
     (792 132
          (:REWRITE SV::SVAR-P-OF-CAR-WHEN-SVARLIST-P))
     (747 723 (:REWRITE DEFAULT-CAR))
     (626 626
          (:REWRITE SV::SVEXLIST-P-WHEN-SUBSETP-EQUAL))
     (584 88
          (:REWRITE SV::SVEXLIST-P-OF-CDR-WHEN-SVEXLIST-P))
     (579 564 (:REWRITE DEFAULT-CDR))
     (452 88
          (:REWRITE SV::SVAR-BOOLMASKS-P-OF-CDR-WHEN-SVAR-BOOLMASKS-P))
     (438 114 (:REWRITE O-P-O-INFP-CAR))
     (433 433
          (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (380 380
          (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (314 44
          (:REWRITE SV::4VECLIST-P-OF-CDR-WHEN-4VECLIST-P))
     (313 313
          (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (294 50
          (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (278 190 (:REWRITE SVL::BITP-IMPLIES-4VECP))
     (274 274
          (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (271 46
          (:REWRITE SV::SVEX-P-OF-CAR-WHEN-SVEXLIST-P))
     (264 264
          (:REWRITE SV::SVARLIST-P-WHEN-SUBSETP-EQUAL))
     (264 264
          (:REWRITE SV::SVAR-P-WHEN-MEMBER-EQUAL-OF-SVARLIST-P))
     (184 184
          (:REWRITE SV::SVAR-BOOLMASKS-P-WHEN-NOT-CONSP))
     (152 48
          (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
     (137 137
          (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (134 134
          (:REWRITE SVL::SVEXL-NODELIST-P-WHEN-NOT-CONSP))
     (132 132 (:TYPE-PRESCRIPTION SV::SVAR-P))
     (132 132
          (:REWRITE SV::SVARLIST-P-WHEN-NOT-CONSP))
     (108 108 (:REWRITE O-P-DEF-O-FINP-1))
     (96 96
         (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
     (96 96
         (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (88 88 (:TYPE-PRESCRIPTION BITP))
     (74 2 (:REWRITE SV::SVEXLIST-P-OF-CONS))
     (44 44 (:TYPE-PRESCRIPTION SV::FNSYM-P))
     (44 44
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (44 44 (:REWRITE FN-CHECK-DEF-NOT-QUOTE)))
(SVL::SVEXLIST-P-OF-4VEC-TO-SVEX-TERMLIST-QUOTE
     (269 4 (:DEFINITION SUBSETP-EQUAL))
     (216 10
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (209 10 (:DEFINITION MEMBER-EQUAL))
     (183 1
          (:REWRITE SV::SVEX-P-OF-CAR-WHEN-SVEXLIST-P))
     (144 8 (:DEFINITION LOOP$-AS))
     (121 121 (:REWRITE DEFAULT-CAR))
     (86 86 (:REWRITE DEFAULT-CDR))
     (84 4
         (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (70 20
         (:REWRITE SV::4VEC-P-OF-CAR-WHEN-4VECLIST-P))
     (67 67 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (48 8 (:DEFINITION CDR-LOOP$-AS-TUPLE))
     (48 8 (:DEFINITION CAR-LOOP$-AS-TUPLE))
     (43 16 (:REWRITE O-P-O-INFP-CAR))
     (40 40
         (:REWRITE SV::4VEC-P-WHEN-MEMBER-EQUAL-OF-4VECLIST-P))
     (40 10
         (:REWRITE SV::INTEGERP-OF-CDAR-WHEN-SVAR-BOOLMASKS-P))
     (40 8 (:DEFINITION EMPTY-LOOP$-AS-TUPLEP))
     (31 31
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (25 25 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (20 20 (:REWRITE SVL::BITP-IMPLIES-4VECP))
     (20 20
         (:REWRITE SV::4VECLIST-P-WHEN-SUBSETP-EQUAL))
     (13 13
         (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (12 12 (:TYPE-PRESCRIPTION LOOP$-AS))
     (12 12
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (12 12
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (12 6 (:REWRITE SUBSETP-REFLEXIVE-LEMMA))
     (10 10
         (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (10 10
         (:REWRITE SV::SVAR-BOOLMASKS-P-WHEN-NOT-CONSP))
     (10 10
         (:REWRITE SV::4VECLIST-P-WHEN-NOT-CONSP))
     (9 9 (:REWRITE O-P-DEF-O-FINP-1)))
(SVL::4VEC-TO-SVEX-TERMLIST
     (3811 3 (:REWRITE O<=-O-FINP-DEF))
     (1639 562 (:REWRITE DEFAULT-+-2))
     (956 562 (:REWRITE DEFAULT-+-1))
     (645 43 (:DEFINITION LENGTH))
     (473 43 (:DEFINITION LEN))
     (455 326 (:REWRITE DEFAULT-CDR))
     (344 86 (:DEFINITION INTEGER-ABS))
     (319 81 (:DEFINITION APPLY$-BADGEP))
     (291 43
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (238 81 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (237 237 (:REWRITE DEFAULT-CAR))
     (200 50 (:REWRITE O-P-O-INFP-CAR))
     (190 38
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (129 129
          (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (129 86 (:REWRITE STR::CONSP-OF-EXPLODE))
     (124 124 (:REWRITE FOLD-CONSTS-IN-+))
     (101 91 (:REWRITE DEFAULT-<-2))
     (101 91 (:REWRITE DEFAULT-<-1))
     (86 86 (:REWRITE DEFAULT-UNARY-MINUS))
     (86 43
         (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
     (81 81 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (66 66
         (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-3))
     (50 50 (:REWRITE O-P-DEF-O-FINP-1))
     (45 45
         (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-2))
     (43 43 (:TYPE-PRESCRIPTION LEN))
     (43 43
         (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
     (43 43 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (43 43 (:REWRITE INTEGERP==>NUMERATOR-=-X))
     (43 43
         (:REWRITE INTEGERP==>DENOMINATOR-=-1))
     (43 43
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (43 43
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (43 43 (:REWRITE DEFAULT-REALPART))
     (43 43 (:REWRITE DEFAULT-NUMERATOR))
     (43 43 (:REWRITE DEFAULT-IMAGPART))
     (43 43 (:REWRITE DEFAULT-DENOMINATOR))
     (30 30
         (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-0))
     (23 23
         (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-1))
     (16 2 (:REWRITE O-FIRST-EXPT-<))
     (15 3 (:REWRITE AC-<))
     (12 4 (:REWRITE O-FIRST-EXPT-DEF-O-FINP))
     (9 3 (:REWRITE O-INFP-O-FINP-O<=))
     (6 2 (:REWRITE O-FIRST-COEFF-<))
     (3 3
        (:REWRITE |a < b & b < c  =>  a < c|)))
(SVL::SVEXL-NODELIST-P-OF-4VEC-TO-SVEX-TERMLIST.RES
     (332 52
          (:REWRITE SVL::SVEXLIST-P-IMPLIES-SVEXL-NODELIST-P))
     (106 106
          (:REWRITE SV::SVEXLIST-P-WHEN-SUBSETP-EQUAL))
     (53 53
         (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (52 52
         (:REWRITE SVL::SVEXL-NODELIST-P-WHEN-NOT-CONSP))
     (23 23 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (21 1 (:REWRITE SV::SVEXLIST-P-OF-CONS))
     (11 2
         (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (8 1
        (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
     (4 4 (:TYPE-PRESCRIPTION SV::SVEX-P))
     (4 4
        (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (3 3
        (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P)))
(SVL::SVEXLIST-P-OF-4VEC-TO-SVEX-TERMLIST
     (172 172 (:REWRITE DEFAULT-CDR))
     (97 2 (:DEFINITION SUBSETP-EQUAL))
     (78 78 (:REWRITE DEFAULT-CAR))
     (56 2
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (50 3 (:DEFINITION MEMBER-EQUAL))
     (36 2 (:DEFINITION LOOP$-AS))
     (19 19 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (17 17 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (12 2 (:DEFINITION CDR-LOOP$-AS-TUPLE))
     (12 2 (:DEFINITION CAR-LOOP$-AS-TUPLE))
     (10 2 (:DEFINITION EMPTY-LOOP$-AS-TUPLEP))
     (8 8
        (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (8 2 (:REWRITE O-P-O-INFP-CAR))
     (7 7 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (7 7 (:REWRITE CDR-CONS))
     (7 7 (:REWRITE CAR-CONS))
     (6 3 (:REWRITE SUBSETP-REFLEXIVE-LEMMA))
     (5 5
        (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (4 4 (:TYPE-PRESCRIPTION LOOP$-AS))
     (2 2 (:REWRITE O-P-DEF-O-FINP-1))
     (2 2
        (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (2 2
        (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2)))
(SVL::NATP-RP-RW-STEP-LIMIT)
(SVL::UNSIGNED-BYTE-P-RW-STEP-LIMIT)
(SVL::SVEXL-NODE-SIMPLIFY-FN
     (11282 6 (:DEFINITION RP::VALID-RULESP))
     (11214 6 (:DEFINITION RP::VALID-RULEP))
     (11196 6 (:DEFINITION RP::VALID-RULEP-SK))
     (11190 6 (:DEFINITION RP::VALID-RULEP-SK-BODY))
     (7540 4
           (:REWRITE RP::VALID-RULESP-IMPLIES-RULE-LIST-SYNTAXP))
     (6492 12 (:DEFINITION RP::VALID-SC-NT))
     (3806 2
           (:REWRITE RP::VALID-RULES-ALISTP-IMPLIES-RULES-ALISTP))
     (3800 2 (:DEFINITION RP::VALID-RULES-ALISTP))
     (3778 2 (:DEFINITION RP::RULE-LIST-SYNTAXP))
     (2936 1586 (:REWRITE O-P-O-INFP-CAR))
     (2700 24 (:DEFINITION RP::RP-TERMP))
     (2616 156 (:DEFINITION RP::INCLUDE-FNC))
     (1992 60
           (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT))
     (1596 12 (:DEFINITION RP::EVAL-AND-ALL-NT))
     (1332 12
           (:REWRITE RP::CAR-OF-EX-FROM-RP-IS-NOT-RP))
     (1248 24 (:DEFINITION RP::FALIST-CONSISTENT))
     (1080 24
           (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (828 60
          (:REWRITE RP::VALID-SC-NT-IS-VALID-SC))
     (720 6 (:REWRITE RP::RP-EVL-OF-RP-EQUAL2))
     (720 6
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-LOOSE))
     (624 624
          (:TYPE-PRESCRIPTION RP::INCLUDE-FNC))
     (578 386 (:REWRITE O-P-DEF-O-FINP-1))
     (564 564
          (:TYPE-PRESCRIPTION RP::INCLUDE-FNC-SUBTERMS))
     (472 472 (:TYPE-PRESCRIPTION RP::RP-TERMP))
     (372 48
          (:DEFINITION RP::INCLUDE-FNC-SUBTERMS))
     (360 60
          (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (336 72 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (276 24
          (:REWRITE RP::EVAL-AND-ALL-NT-IS-EVAL-AND-ALL))
     (270 114
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (240 240
          (:TYPE-PRESCRIPTION RP::IS-RP$INLINE))
     (240 96 (:REWRITE RP::RP-TERMP-IS-IF-LEMMA))
     (240 72 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (216 216
          (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (206 205 (:DEFINITION QUOTEP))
     (192 192 (:TYPE-PRESCRIPTION O-FINP))
     (192 96 (:REWRITE RP::IS-IF-RP-TERMP))
     (192 72
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (192 72 (:DEFINITION RP::IS-SYNP$INLINE))
     (186 6 (:REWRITE RP::RP-EVL-OF-RP-EQUAL))
     (162 6 (:DEFINITION RP::RP-EQUAL))
     (156 156
          (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (145 145
          (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (144 144
          (:TYPE-PRESCRIPTION RP::VALID-SC-NT))
     (144 24 (:DEFINITION RP::EX-FROM-RP))
     (121 121 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (120 120
          (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (120 36 (:REWRITE RP::NOT-INCLUDE-RP))
     (120 12
          (:REWRITE RP::VALID-SC-NT-SUBTERMS-VALID-SC-SUBTERMS))
     (120 12
          (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT-SUBTERMS))
     (114 114
          (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (108 24
          (:REWRITE RP::NOT-INCLUDE-EX-FROM-RP))
     (108 12
          (:REWRITE RP::EVAL-AND-ALL-NT-OF-CONTEXT-FROM-RP))
     (100 25
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (96 72 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (96 72
         (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (96 72
         (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (96 72
         (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (96 72 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (96 48 (:REWRITE RP::RP-TERMP-CADR))
     (96 48 (:REWRITE RP::RP-TERMP-CADDR))
     (96 48 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (72 72
         (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (72 72
         (:TYPE-PRESCRIPTION RP::CONTEXT-FROM-RP))
     (72 24
         (:REWRITE RP::QUOTEP-TERM-WITH-EX-FROM-RP))
     (60 60
         (:TYPE-PRESCRIPTION RP::EVAL-AND-ALL-NT))
     (52 25
         (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (49 49 (:TYPE-PRESCRIPTION QUOTEP))
     (48 12
         (:REWRITE RP::VALID-RULEP-IMPLIES-VALID-SC))
     (36 36 (:TYPE-PRESCRIPTION RP::VALID-RULEP))
     (30 30
         (:TYPE-PRESCRIPTION RP::VALID-RULESP))
     (24 24
         (:TYPE-PRESCRIPTION RP::VALID-SC-NT-SUBTERMS))
     (20 20
         (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
     (18 18 (:TYPE-PRESCRIPTION RP::RP-EQUAL))
     (12 12
         (:TYPE-PRESCRIPTION RP::RP-EQUAL-SUBTERMS))
     (12 12 (:REWRITE RP::VALID-RULES-SUBSETP))
     (11 1 (:DEFINITION RP::RP-TERM-LISTP))
     (10 10
         (:TYPE-PRESCRIPTION RP::VALID-RULES-ALISTP))
     (10 2 (:DEFINITION STRIP-CDRS))
     (10 2 (:DEFINITION STRIP-CARS))
     (10 1
         (:REWRITE SVL::SVEX-P-IMPLIES-SVEXL-NODE-P))
     (6 6
        (:REWRITE RP::RP-EQUAL-SUBTERMS-REFLEXIVE))
     (6 6 (:REWRITE RP::RP-EQUAL-REFLEXIVE))
     (6 6 (:DEFINITION IFF))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (5 1
        (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (4 4 (:REWRITE FN-CHECK-DEF-FORMALS))
     (3 3 (:TYPE-PRESCRIPTION SV::SVEX-P))
     (2 2 (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
     (2 2
        (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (2 1
        (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P)))
(SVL::SVEXL-NODE-P-OF-SVEXL-NODE-SIMPLIFY.NODE-NEW)
(SVL::RP-STATEP-OF-SVEXL-NODE-SIMPLIFY.RP-STATE-RES)
(SVL::SVEXL-NODELIST-SIMPLIFY-FN
     (3806 2
           (:REWRITE RP::VALID-RULES-ALISTP-IMPLIES-RULES-ALISTP))
     (3800 2 (:DEFINITION RP::VALID-RULES-ALISTP))
     (3758 2 (:DEFINITION RP::VALID-RULESP))
     (3738 2 (:DEFINITION RP::VALID-RULEP))
     (3732 2 (:DEFINITION RP::VALID-RULEP-SK))
     (3730 2 (:DEFINITION RP::VALID-RULEP-SK-BODY))
     (2164 4 (:DEFINITION RP::VALID-SC-NT))
     (992 532 (:REWRITE O-P-O-INFP-CAR))
     (900 8 (:DEFINITION RP::RP-TERMP))
     (872 52 (:DEFINITION RP::INCLUDE-FNC))
     (664 20
          (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT))
     (532 4 (:DEFINITION RP::EVAL-AND-ALL-NT))
     (444 4
          (:REWRITE RP::CAR-OF-EX-FROM-RP-IS-NOT-RP))
     (416 8 (:DEFINITION RP::FALIST-CONSISTENT))
     (360 8
          (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (276 20
          (:REWRITE RP::VALID-SC-NT-IS-VALID-SC))
     (240 2 (:REWRITE RP::RP-EVL-OF-RP-EQUAL2))
     (240 2
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-LOOSE))
     (208 208
          (:TYPE-PRESCRIPTION RP::INCLUDE-FNC))
     (196 132 (:REWRITE O-P-DEF-O-FINP-1))
     (188 188
          (:TYPE-PRESCRIPTION RP::INCLUDE-FNC-SUBTERMS))
     (160 160 (:TYPE-PRESCRIPTION RP::RP-TERMP))
     (124 16
          (:DEFINITION RP::INCLUDE-FNC-SUBTERMS))
     (120 20
          (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (112 24 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (100 40
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (92 8
         (:REWRITE RP::EVAL-AND-ALL-NT-IS-EVAL-AND-ALL))
     (80 80
         (:TYPE-PRESCRIPTION RP::IS-RP$INLINE))
     (80 32 (:REWRITE RP::RP-TERMP-IS-IF-LEMMA))
     (80 24 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (72 72
         (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (70 69 (:DEFINITION QUOTEP))
     (64 64 (:TYPE-PRESCRIPTION O-FINP))
     (64 32 (:REWRITE RP::IS-IF-RP-TERMP))
     (64 24
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (64 24 (:DEFINITION RP::IS-SYNP$INLINE))
     (62 2 (:REWRITE RP::RP-EVL-OF-RP-EQUAL))
     (54 2 (:DEFINITION RP::RP-EQUAL))
     (52 52
         (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (49 49
         (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (48 48 (:TYPE-PRESCRIPTION RP::VALID-SC-NT))
     (48 8 (:DEFINITION RP::EX-FROM-RP))
     (41 41 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (40 40
         (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (40 40
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (40 12 (:REWRITE RP::NOT-INCLUDE-RP))
     (40 4
         (:REWRITE RP::VALID-SC-NT-SUBTERMS-VALID-SC-SUBTERMS))
     (40 4
         (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT-SUBTERMS))
     (36 9
         (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (36 8 (:REWRITE RP::NOT-INCLUDE-EX-FROM-RP))
     (36 4
         (:REWRITE RP::EVAL-AND-ALL-NT-OF-CONTEXT-FROM-RP))
     (32 24 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (32 24
         (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (32 24
         (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (32 24
         (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (32 24 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (32 16 (:REWRITE RP::RP-TERMP-CADR))
     (32 16 (:REWRITE RP::RP-TERMP-CADDR))
     (32 16 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (24 24
         (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (24 24
         (:TYPE-PRESCRIPTION RP::CONTEXT-FROM-RP))
     (24 8
         (:REWRITE RP::QUOTEP-TERM-WITH-EX-FROM-RP))
     (20 20
         (:TYPE-PRESCRIPTION RP::EVAL-AND-ALL-NT))
     (20 9
         (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (17 17 (:TYPE-PRESCRIPTION QUOTEP))
     (16 4
         (:REWRITE RP::VALID-RULEP-IMPLIES-VALID-SC))
     (12 12 (:TYPE-PRESCRIPTION RP::VALID-RULEP))
     (11 1 (:DEFINITION RP::RP-TERM-LISTP))
     (10 10
         (:TYPE-PRESCRIPTION RP::VALID-RULESP))
     (10 10
         (:TYPE-PRESCRIPTION RP::VALID-RULES-ALISTP))
     (8 8
        (:TYPE-PRESCRIPTION RP::VALID-SC-NT-SUBTERMS))
     (6 6
        (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
     (6 6 (:TYPE-PRESCRIPTION RP::RP-EQUAL))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1
        (:REWRITE SVL::SVEXLIST-P-IMPLIES-SVEXL-NODELIST-P))
     (4 4
        (:TYPE-PRESCRIPTION RP::RP-EQUAL-SUBTERMS))
     (4 4 (:REWRITE RP::VALID-RULES-SUBSETP))
     (2 2
        (:REWRITE SV::SVEXLIST-P-WHEN-SUBSETP-EQUAL))
     (2 2
        (:REWRITE RP::RP-EQUAL-SUBTERMS-REFLEXIVE))
     (2 2 (:REWRITE RP::RP-EQUAL-REFLEXIVE))
     (2 2 (:DEFINITION IFF))
     (1 1
        (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (1 1
        (:REWRITE SVL::SVEXL-NODELIST-P-WHEN-NOT-CONSP)))
(SVL::SVEXL-NODELIST-P-OF-SVEXL-NODELIST-SIMPLIFY.NODE-NEW)
(SVL::RP-STATEP-OF-SVEXL-NODELIST-SIMPLIFY.RP-STATE-RES)
(SVL::SVEX-SIMPLIFY-LINEARIZE-AUX-FN)
(SVL::SVEXL-NODE-ALIST-P-OF-SVEX-SIMPLIFY-LINEARIZE-AUX.SVEXL-NEW
     (13 5 (:REWRITE DEFAULT-CDR))
     (9 3 (:REWRITE O-P-O-INFP-CAR))
     (6 5 (:REWRITE DEFAULT-CAR))
     (4 4 (:TYPE-PRESCRIPTION O-P))
     (2 2 (:REWRITE O-P-DEF-O-FINP-1)))
(SVL::RP-STATEP-OF-SVEX-SIMPLIFY-LINEARIZE-AUX.RP-STATE-RES
     (16 4 (:REWRITE DEFAULT-CDR))
     (13 4 (:REWRITE O-P-O-INFP-CAR))
     (6 6 (:TYPE-PRESCRIPTION O-P))
     (6 5 (:REWRITE DEFAULT-CAR))
     (3 3 (:REWRITE O-P-DEF-O-FINP-1)))
(SVL::LEMMA1)
(SVL::SVEX-SIMPLIFY-LINEARIZE-AUX-FN
     (236 68 (:REWRITE O-P-O-INFP-CAR))
     (129 104 (:REWRITE DEFAULT-CAR))
     (127 95 (:REWRITE DEFAULT-CDR))
     (66 6 (:DEFINITION STRIP-CDRS))
     (66 6 (:DEFINITION STRIP-CARS))
     (56 56 (:REWRITE O-P-DEF-O-FINP-1))
     (48 24
         (:REWRITE SVL::SVEXL-NODE-ALIST-P-WHEN-NOT-CONSP))
     (48 6 (:DEFINITION RP::RULE-LIST-SYNTAXP))
     (24 8
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (24 6
         (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (16 1
         (:REWRITE SVL::SVEX-P-IMPLIES-SVEXL-NODE-P))
     (12 12
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (12 12 (:REWRITE FN-CHECK-DEF-FORMALS))
     (12 1
         (:DEFINITION SVL::SVEX-SIMPLIFY-LINEARIZE-AUX-FN))
     (6 6
        (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
     (6 1
        (:REWRITE SV::SVEX-P-OF-CDAR-WHEN-SVEX-ALIST-P))
     (5 1
        (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (3 3 (:TYPE-PRESCRIPTION SV::SVEX-P))
     (2 2 (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
     (2 2
        (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (2 2
        (:REWRITE SV::SVEX-ALIST-P-WHEN-SUBSETP-EQUAL))
     (2 1
        (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
     (1 1
        (:REWRITE SV::SVEX-ALIST-P-WHEN-NOT-CONSP))
     (1 1 (:DEFINITION ACONS)))
(SVL::SVEX-SIMPLIFY-LINEARIZE-FN)
(SVL::SVEXL-P-OF-SVEX-SIMPLIFY-LINEARIZE.SVEXL-NEW
 (10 2
     (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
 (7 1
    (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
 (4 4
    (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
 (3 3 (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
 (1 1
    (:REWRITE SVL::SVEXL-OF-SVEXL-NODE-FIX-TOP-NODE-NORMALIZE-CONST))
 (1 1
    (:REWRITE SVL::SVEXL-OF-SVEXL-NODE-ALIST-FIX-NODE-ALIST-NORMALIZE-CONST))
 (1 1
    (:REWRITE SVL::SVEXL->TOP-NODE$INLINE-OF-SVEXL-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE SVL::SVEXL->NODE-ALIST$INLINE-OF-SVEXL-FIX-X-NORMALIZE-CONST)))
(SVL::RP-STATEP-OF-SVEX-SIMPLIFY-LINEARIZE.RP-STATE-RES
 (1 1
    (:REWRITE SVL::SVEXL-OF-SVEXL-NODE-FIX-TOP-NODE-NORMALIZE-CONST))
 (1 1
    (:REWRITE SVL::SVEXL-OF-SVEXL-NODE-ALIST-FIX-NODE-ALIST-NORMALIZE-CONST))
 (1 1
    (:REWRITE SVL::SVEXL->TOP-NODE$INLINE-OF-SVEXL-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE SVL::SVEXL->NODE-ALIST$INLINE-OF-SVEXL-FIX-X-NORMALIZE-CONST)))
(SVL::SVEXLIST-SIMPLIFY-LINEARIZE-FN)
(SVL::SVEXLLIST-P-OF-SVEXLIST-SIMPLIFY-LINEARIZE.SVEXLLIST-NEW
 (2 2
    (:REWRITE SV::SVEXLIST-P-WHEN-SUBSETP-EQUAL))
 (1 1
    (:REWRITE
         SVL::SVEXLLIST-OF-SVEXL-NODELIST-FIX-TOP-NODELIST-NORMALIZE-CONST))
 (1 1
    (:REWRITE
         SVL::SVEXLLIST-OF-SVEXL-NODE-ALIST-FIX-NODE-ALIST-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
     SVL::SVEXLLIST->TOP-NODELIST$INLINE-OF-SVEXLLIST-FIX-X-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
       SVL::SVEXLLIST->NODE-ALIST$INLINE-OF-SVEXLLIST-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP)))
(SVL::RP-STATEP-OF-SVEXLIST-SIMPLIFY-LINEARIZE.RP-STATE-RES
 (1 1
    (:REWRITE
         SVL::SVEXLLIST-OF-SVEXL-NODELIST-FIX-TOP-NODELIST-NORMALIZE-CONST))
 (1 1
    (:REWRITE
         SVL::SVEXLLIST-OF-SVEXL-NODE-ALIST-FIX-NODE-ALIST-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
     SVL::SVEXLLIST->TOP-NODELIST$INLINE-OF-SVEXLLIST-FIX-X-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
      SVL::SVEXLLIST->NODE-ALIST$INLINE-OF-SVEXLLIST-FIX-X-NORMALIZE-CONST)))
(SVL::CONS-COUNT-COMPARE)
(SVL::SVEX-SIMPLIFY-TO-4VEC-FN
     (451 41 (:DEFINITION RP::RP-TERM-LISTP))
     (441 91
          (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (301 49
          (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
     (228 57 (:REWRITE O-P-O-INFP-CAR))
     (182 182
          (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (164 41
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (164 41
          (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (133 133
          (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
     (119 39
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (82 41 (:DEFINITION QUOTEP))
     (57 57 (:REWRITE O-P-DEF-O-FINP-1))
     (41 41 (:TYPE-PRESCRIPTION QUOTEP))
     (41 41
         (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (41 41 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (32 22 (:REWRITE DEFAULT-<-2))
     (30 30 (:REWRITE NTH-WHEN-PREFIXP))
     (30 30 (:DEFINITION NTH))
     (30 30 (:DEFINITION ASSOC-EQUAL))
     (30 5 (:DEFINITION INTEGER-RANGE-P))
     (24 22 (:REWRITE DEFAULT-<-1))
     (20 20
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (14 7 (:REWRITE O-INFP->NEQ-0))
     (5 5
        (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP)))
(SVL::RP-STATEP-OF-SVEX-SIMPLIFY-TO-4VEC.RP-STATE-RES
     (1377 102 (:DEFINITION RP::RP-TERM-LISTP))
     (969 51
          (:REWRITE RP::RP-TERMP-RP-RW-SUBTERMS))
     (510 510 (:TYPE-PRESCRIPTION RP::RP-TERMP))
     (408 102
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (408 102
          (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (204 102 (:DEFINITION QUOTEP))
     (102 102 (:TYPE-PRESCRIPTION QUOTEP))
     (102 102
          (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (102 102 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (84 84 (:REWRITE NTH-WHEN-PREFIXP))
     (84 84 (:DEFINITION NTH))
     (84 84 (:DEFINITION ASSOC-EQUAL))
     (34 18 (:REWRITE DEFAULT-<-2))
     (30 30
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (18 18 (:REWRITE DEFAULT-<-1))
     (12 6 (:REWRITE O-INFP->NEQ-0)))
(SVL::SVEXLIST-SIMPLIFY-TO-4VEC-FN
     (451 41 (:DEFINITION RP::RP-TERM-LISTP))
     (228 57 (:REWRITE O-P-O-INFP-CAR))
     (164 41
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (164 41
          (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (119 39
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (82 41 (:DEFINITION QUOTEP))
     (57 57 (:REWRITE O-P-DEF-O-FINP-1))
     (42 42
         (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (41 41 (:TYPE-PRESCRIPTION QUOTEP))
     (41 41
         (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (41 41 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (32 22 (:REWRITE DEFAULT-<-2))
     (30 30 (:REWRITE NTH-WHEN-PREFIXP))
     (30 30 (:DEFINITION NTH))
     (30 30 (:DEFINITION ASSOC-EQUAL))
     (30 5 (:DEFINITION INTEGER-RANGE-P))
     (24 22 (:REWRITE DEFAULT-<-1))
     (20 20
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (14 7 (:REWRITE O-INFP->NEQ-0))
     (7 7
        (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (5 5
        (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP)))
(SVL::RP-STATEP-OF-SVEXLIST-SIMPLIFY-TO-4VEC.RP-STATE-RES
     (1377 102 (:DEFINITION RP::RP-TERM-LISTP))
     (969 51
          (:REWRITE RP::RP-TERMP-RP-RW-SUBTERMS))
     (510 510 (:TYPE-PRESCRIPTION RP::RP-TERMP))
     (408 102
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (408 102
          (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (204 102 (:DEFINITION QUOTEP))
     (102 102 (:TYPE-PRESCRIPTION QUOTEP))
     (102 102
          (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (102 102 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (84 84 (:REWRITE NTH-WHEN-PREFIXP))
     (84 84 (:DEFINITION NTH))
     (84 84 (:DEFINITION ASSOC-EQUAL))
     (34 18 (:REWRITE DEFAULT-<-2))
     (30 30
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (18 18 (:REWRITE DEFAULT-<-1))
     (12 6 (:REWRITE O-INFP->NEQ-0)))
(SVL::LOCALLY-SIMPLIFIED-TO-SVEX)
(SVL::SVEX-P-OF-LOCALLY-SIMPLIFIED-TO-SVEX.RES
     (15 15 (:REWRITE DEFAULT-CDR))
     (10 2
         (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (8 8 (:REWRITE DEFAULT-CAR))
     (7 1
        (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
     (4 4
        (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (4 1 (:REWRITE O-P-O-INFP-CAR))
     (3 3 (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
     (2 2 (:TYPE-PRESCRIPTION O-P))
     (1 1 (:REWRITE O-P-DEF-O-FINP-1))
     (1 1 (:REWRITE FN-CHECK-DEF-NOT-QUOTE)))
(SVL::LOCALLY-SIMPLIFIED-TO-SVEXLIST)
(SVL::SVEXLIST-P-OF-LOCALLY-SIMPLIFIED-TO-SVEXLIST.RES
     (15 15 (:REWRITE DEFAULT-CDR))
     (8 8 (:REWRITE DEFAULT-CAR))
     (4 1 (:REWRITE O-P-O-INFP-CAR))
     (2 2 (:TYPE-PRESCRIPTION O-P))
     (2 2
        (:REWRITE SV::SVEXLIST-P-WHEN-SUBSETP-EQUAL))
     (1 1
        (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (1 1 (:REWRITE O-P-DEF-O-FINP-1))
     (1 1 (:REWRITE FN-CHECK-DEF-NOT-QUOTE)))
(SVL::SVEX-SIMPLIFY-FN
     (72 18 (:REWRITE O-P-O-INFP-CAR))
     (35 27 (:REWRITE DEFAULT-CDR))
     (35 27 (:REWRITE DEFAULT-CAR))
     (26 6
         (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (24 2 (:DEFINITION STRIP-CDRS))
     (24 2 (:DEFINITION STRIP-CARS))
     (18 18 (:REWRITE O-P-DEF-O-FINP-1))
     (16 4
         (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
     (16 2 (:DEFINITION RP::RULE-LIST-SYNTAXP))
     (12 12
         (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (12 3
         (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (8 8 (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
     (4 4
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (4 4 (:REWRITE FN-CHECK-DEF-FORMALS))
     (4 2 (:REWRITE DEFAULT-<-1))
     (2 2
        (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
     (2 2 (:REWRITE DEFAULT-<-2)))
(SVL::SVEX-P-OF-SVEX-SIMPLIFY.RES
     (40 8
         (:REWRITE SV::SVEX-P-WHEN-MAYBE-SVEX-P))
     (28 4
         (:REWRITE SV::MAYBE-SVEX-P-WHEN-SVEX-P))
     (16 16
         (:REWRITE SV::SVEX-P-WHEN-MEMBER-EQUAL-OF-SVEXLIST-P))
     (12 12
         (:TYPE-PRESCRIPTION SV::MAYBE-SVEX-P))
     (6 3 (:REWRITE DEFAULT-<-2))
     (4 2 (:REWRITE O-INFP->NEQ-0))
     (3 3 (:REWRITE DEFAULT-<-1)))
(SVL::RP-STATEP-OF-SVEX-SIMPLIFY.RP-STATE-RES (4 2 (:REWRITE DEFAULT-<-2))
                                              (2 2 (:REWRITE DEFAULT-<-1))
                                              (2 1 (:REWRITE O-INFP->NEQ-0)))
(SVL::SVEXLIST-SIMPLIFY-FN
     (72 18 (:REWRITE O-P-O-INFP-CAR))
     (35 27 (:REWRITE DEFAULT-CDR))
     (35 27 (:REWRITE DEFAULT-CAR))
     (24 2 (:DEFINITION STRIP-CDRS))
     (24 2 (:DEFINITION STRIP-CARS))
     (18 18 (:REWRITE O-P-DEF-O-FINP-1))
     (16 2 (:DEFINITION RP::RULE-LIST-SYNTAXP))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (12 3
         (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (4 4
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (4 4 (:REWRITE FN-CHECK-DEF-FORMALS))
     (4 2 (:REWRITE DEFAULT-<-1))
     (2 2
        (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
     (2 2
        (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (2 2
        (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (2 2 (:REWRITE DEFAULT-<-2)))
(SVL::SVEXLIST-P-OF-SVEXLIST-SIMPLIFY.RES
     (8 8
        (:REWRITE SV::SVEXLIST-P-WHEN-SUBSETP-EQUAL))
     (6 3 (:REWRITE DEFAULT-<-2))
     (4 4
        (:REWRITE SV::SVEXLIST-P-WHEN-NOT-CONSP))
     (4 2 (:REWRITE O-INFP->NEQ-0))
     (3 3 (:REWRITE DEFAULT-<-1)))
(SVL::RP-STATEP-OF-SVEXLIST-SIMPLIFY.RP-STATE-RES
     (4 2 (:REWRITE DEFAULT-<-2))
     (2 2 (:REWRITE DEFAULT-<-1))
     (2 1 (:REWRITE O-INFP->NEQ-0)))
