; Automatically generated by jvm2m5

(in-package "M5")
(include-book "models/jvm/m5/m5" :dir :system)

(defconst *Container*
    (make-class-decl
     "Container"
     '("java/lang/Object")
     '(
      "counter:I")
     '()
     '(nil
       (methodref "java/lang/Object" "<init>:()V" 0)           ; 1
       (class (ref -1) "Container")                            ; 2
       (class (ref -1) "java/lang/Object")                     ; 3
       (utf8)                                                  ; 4
       (utf8)                                                  ; 5
       (utf8)                                                  ; 6
       (utf8)                                                  ; 7
       (utf8)                                                  ; 8
       (utf8)                                                  ; 9
       (utf8)                                                  ; 10
       (utf8)                                                  ; 11
       (name-and-type "<init>:()V")                            ; 12
       (utf8)                                                  ; 13
       (utf8)                                                  ; 14
      )
     (list
      '("<init>:()V" nil
        ; line_number #1
        (aload_0)                                               ; 0
        (invokespecial 1)                                       ; 1 java.lang.Object.<init>:()V
        (return)                                                ; 4
       ))
     '(ref -1)))