# Enter the names of the books to certify, e.g., BOOKS = book1 book2

ACL2_SYSTEM_BOOKS ?= ../../../..
include $(ACL2_SYSTEM_BOOKS)/Makefile-generic

# BOOKS = map-ec-call split phony-induction defung defung-test defung-stress rev3 ack-variants monadic

-include Makefile-deps
