include ../../../../../../../../Makefile-generic


# Dependencies:

ma128intnet-ma128intserial.cert: ma128intnet-ma128intserial.lisp
ma128intnet-ma128intserial.cert: ma128intnet.cert

ma128intnet.cert: ma128intnet.lisp
ma128intnet.cert: ../../../deterministic-systems/128/netlist/netlist.cert
ma128intnet.cert: ../serial/ma128intserial.cert
