(PRIMALITY-THEOREM-FOR-MAKE-R1CS-EVENT)
(MONTGOMERYDOUBLE-VARS)
(VAR-LISTP-OF-MONTGOMERYDOUBLE-VARS)
(MONTGOMERYDOUBLE-CONSTRAINTS)
(R1CS-CONSTRAINT-LISTP-OF-MONTGOMERYDOUBLE-CONSTRAINTS)
(GOOD-R1CS-CONSTRAINT-LISTP-OF-MONTGOMERYDOUBLE-CONSTRAINTS)
(MONTGOMERYDOUBLE-MAKE-R1CS)
(ZKSEMAPHORE::PRECOND)
(ZKSEMAPHORE::BOOLEANP-OF-PRECOND)
(ZKSEMAPHORE::MONTGOMERY-DOUBLE
     (47 47 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (47 37
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (44 44
         (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (42 21
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (41 37
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (34 34
         (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG2))
     (34 34
         (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG1))
     (30 21
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (24 24 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (8 8 (:REWRITE PFIELD::ADD-COMMUTATIVE-2))
     (8 8
        (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS))
     (6 3
        (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (6 2 (:DEFINITION NATP))
     (4 4
        (:REWRITE PFIELD::FEP-WHEN-FE-LISTP-AND-MEMBER-EQUAL))
     (4 3 (:REWRITE DEFAULT-<-1))
     (3 3
        (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (3 3 (:REWRITE DEFAULT-<-2))
     (2 2 (:TYPE-PRESCRIPTION NATP))
     (2 2 (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (2 2 (:REWRITE PFIELD::FEP-WHEN-CONSTANT))
     (1 1
        (:REWRITE PFIELD::MUL-OF-ADD-OF-MUL-COMBINE-CONSTANTS)))
(ZKSEMAPHORE::PFEP-OF-MONTGOMERY-DOUBLE.XD
     (46 23
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (38 38
         (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG2))
     (38 38
         (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG1))
     (36 23
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (34 34 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (32 23
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (28 28
         (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (25 23
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (10 10
         (:REWRITE PFIELD::MUL-COMBINE-CONSTANTS))
     (10 10 (:REWRITE PFIELD::ADD-COMMUTATIVE-2))
     (7 2 (:DEFINITION NATP))
     (6 6
        (:REWRITE PFIELD::FEP-WHEN-FE-LISTP-AND-MEMBER-EQUAL))
     (6 4 (:REWRITE PFIELD::FEP-WHEN-CONSTANT))
     (6 4 (:REWRITE DEFAULT-<-2))
     (6 4 (:REWRITE DEFAULT-<-1))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4 (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (4 4
        (:REWRITE PFIELD::NEG-OF-MUL-WHEN-CONSTANT))
     (1 1
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (1 1
        (:REWRITE PFIELD::MUL-OF-ADD-OF-MUL-COMBINE-CONSTANTS))
     (1 1
        (:REWRITE PFIELD::ADD-ASSOCIATIVE-WHEN-CONSTANT)))
(ZKSEMAPHORE::PFEP-OF-MONTGOMERY-DOUBLE.YD
     (46 23
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (38 38
         (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG2))
     (38 38
         (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG1))
     (36 23
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (34 34 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (32 23
         (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (28 28
         (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (25 23
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (10 10
         (:REWRITE PFIELD::MUL-COMBINE-CONSTANTS))
     (10 10 (:REWRITE PFIELD::ADD-COMMUTATIVE-2))
     (7 2 (:DEFINITION NATP))
     (6 6
        (:REWRITE PFIELD::FEP-WHEN-FE-LISTP-AND-MEMBER-EQUAL))
     (6 4 (:REWRITE PFIELD::FEP-WHEN-CONSTANT))
     (6 4 (:REWRITE DEFAULT-<-2))
     (6 4 (:REWRITE DEFAULT-<-1))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4 (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (4 4
        (:REWRITE PFIELD::NEG-OF-MUL-WHEN-CONSTANT))
     (1 1
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (1 1
        (:REWRITE PFIELD::MUL-OF-ADD-OF-MUL-COMBINE-CONSTANTS))
     (1 1
        (:REWRITE PFIELD::ADD-ASSOCIATIVE-WHEN-CONSTANT)))
(ZKSEMAPHORE::SPEC)
(ZKSEMAPHORE::AUXP)
(ZKSEMAPHORE::BOOLEANP-OF-AUXP)
(ZKSEMAPHORE::CIRCUIT-CORE
     (42 42 (:REWRITE DEFAULT-CAR))
     (36 36 (:REWRITE DEFAULT-CDR))
     (18 6 (:DEFINITION NATP))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6
        (:REWRITE PFIELD::FEP-WHEN-FE-LISTP-AND-MEMBER-EQUAL))
     (6 6 (:REWRITE PFIELD::FEP-WHEN-CONSTANT))
     (6 6 (:REWRITE DEFAULT-<-2))
     (6 6 (:REWRITE DEFAULT-<-1))
     (1 1
        (:REWRITE R1CS::R1CS-VALUATIONP-WHEN-NOT-CONSP)))
(ZKSEMAPHORE::BOOLEANP-OF-CIRCUIT-CORE)
(ZKSEMAPHORE::CIRCUIT)
(ZKSEMAPHORE::CIRCUIT-SUFF)
(ZKSEMAPHORE::BOOLEANP-OF-CIRCUIT)
(ZKSEMAPHORE::CIRCUIT)
(ZKSEMAPHORE::CIRCUIT-CORE-IMPLIES-SPEC
     (156 82
          (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (149 149
          (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG2))
     (149 149
          (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG1))
     (119 119 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (114 82
          (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (53 53
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-CONSP-CHEAP))
     (53 53
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (53 53 (:REWRITE DEFAULT-CAR))
     (43 43
         (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS))
     (43 40
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (40 40
         (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (32 26
         (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (25 25
         (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (20 13 (:REWRITE DEFAULT-<-1))
     (18 18
         (:TYPE-PRESCRIPTION R1CS::DOT-PRODUCT))
     (18 6 (:DEFINITION NATP))
     (17 17
         (:REWRITE PFIELD::ADD-ASSOCIATIVE-WHEN-CONSTANT))
     (16 16 (:REWRITE DEFAULT-CDR))
     (14 14
         (:REWRITE PFIELD::FEP-WHEN-FE-LISTP-AND-MEMBER-EQUAL))
     (13 13 (:REWRITE DEFAULT-<-2))
     (7 7
        (:REWRITE PFIELD::EQUAL-OF-ADD-COMBINE-CONSTANTS))
     (6 6 (:TYPE-PRESCRIPTION NATP))
     (6 6 (:REWRITE PFIELD::FEP-WHEN-CONSTANT))
     (6 6
        (:REWRITE PFIELD::EQUAL-OF-MUL-CONSTANTS))
     (2 2 (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (1 1
        (:TYPE-PRESCRIPTION PFIELD::NATP-OF-INV))
     (1 1
        (:REWRITE PFIELD::EQUAL-OF-CONSTANT-AND-ADD-OF-NEG-ARG1)))
(ZKSEMAPHORE::CIRCUIT-IMPLIES-SPEC)
(ZKSEMAPHORE::X^2-WITNESS)
(ZKSEMAPHORE::LAMBDA-WITNESS)
(ZKSEMAPHORE::SPEC-IMPLIES-CIRCUIT-CORE
     (2030 1045
           (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (1224 613
           (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (1190 1045
           (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (1173 613
           (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (1003 1003
           (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG2))
     (1003 1003
           (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG1))
     (931 931 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (75 75
         (:REWRITE PFIELD::ADD-ASSOCIATIVE-WHEN-CONSTANT))
     (63 53 (:REWRITE DEFAULT-CAR))
     (53 53
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-CONSP-CHEAP))
     (53 53
         (:REWRITE LOOKUP-EQUAL-WHEN-NOT-ASSOC-EQUAL-CHEAP))
     (26 26
         (:TYPE-PRESCRIPTION R1CS::DOT-PRODUCT))
     (24 8 (:DEFINITION NATP))
     (23 19
         (:REWRITE PFIELD::NEG-WHEN-NOT-INTEGERP-CHEAP))
     (22 16 (:REWRITE DEFAULT-CDR))
     (19 19
         (:REWRITE PFIELD::NEG-WHEN-CONSTANT-ARG1))
     (16 12 (:REWRITE DEFAULT-<-1))
     (12 12
         (:REWRITE PFIELD::FEP-WHEN-FE-LISTP-AND-MEMBER-EQUAL))
     (12 12 (:REWRITE DEFAULT-<-2))
     (8 8 (:TYPE-PRESCRIPTION NATP))
     (8 8 (:REWRITE PFIELD::FEP-WHEN-CONSTANT))
     (7 7
        (:REWRITE PFIELD::EQUAL-OF-ADD-COMBINE-CONSTANTS))
     (3 3
        (:REWRITE PFIELD::EQUAL-OF-0-AND-ADD-SAFE))
     (2 2 (:REWRITE PFIELD::SUB-WHEN-CONSTANTS))
     (1 1
        (:REWRITE PFIELD::EQUAL-OF-CONSTANT-AND-ADD-OF-NEG-ARG1)))
(ZKSEMAPHORE::AUXP-WHEN-PRECOND
     (12 4 (:DEFINITION NATP))
     (8 8
        (:REWRITE PFIELD::MUL-WHEN-CONSTANT-REDUCE-ARG1))
     (8 8 (:REWRITE PFIELD::MUL-BECOMES-NEG))
     (8 7
        (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (7 7
        (:REWRITE PFIELD::MUL-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (7 7 (:REWRITE PFIELD::MUL-COMMUTATIVE))
     (6 6
        (:TYPE-PRESCRIPTION PFIELD::NATP-OF-DIV))
     (6 6
        (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG2))
     (6 6
        (:REWRITE PFIELD::ADD-SUBST-CONSTANT-ARG1))
     (6 5 (:REWRITE DEFAULT-<-2))
     (6 5 (:REWRITE DEFAULT-<-1))
     (6 3
        (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG2-CHEAP))
     (5 5
        (:REWRITE PFIELD::FEP-WHEN-FE-LISTP-AND-MEMBER-EQUAL))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 4 (:REWRITE PFIELD::FEP-WHEN-CONSTANT))
     (4 4 (:REWRITE PFIELD::ADD-OF-CONSTANTS))
     (4 3
        (:REWRITE PFIELD::ADD-WHEN-NOT-INTEGERP-ARG1-CHEAP))
     (1 1
        (:TYPE-PRESCRIPTION PFIELD::NATP-OF-ADD))
     (1 1 (:REWRITE PFIELD::MUL-COMMUTATIVE-2))
     (1 1 (:REWRITE PFIELD::ADD-COMMUTATIVE-2))
     (1 1
        (:REWRITE PFIELD::ADD-COMBINE-CONSTANTS)))
(ZKSEMAPHORE::SPEC-IMPLIES-CIRCUIT)
(ZKSEMAPHORE::CIRCUIT-IS-SPEC)
