include ../../../../Makefile-generic

# We skip all books for "make fasl" etc., i.e., for compiling
# already-certified books, because the .acl2 files specify no
# compilation.
BOOKS_SKIP_COMP := $(BOOKS)

-include Makefile-deps
