# The following variable should represent the ACL2 books directory.  It is the
# only variable in this Makefile that may need to be edited.
ACL2_SYSTEM_BOOKS ?= ../../../..

DIRS = symbol-fns lists syntax bags
include $(ACL2_SYSTEM_BOOKS)/Makefile-subdirs
