# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../Makefile-generic

ACL2 = ../../../../../saved_acl2

# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

memory-taggings.cert: memory-taggings.lisp
memory-taggings.cert: ../../../../misc/records.cert
memory-taggings.cert: ../../../../arithmetic/top-with-meta.cert
memory-taggings.cert: ../../../../ordinals/e0-ordinal.cert
