#!/bin/sh

if [ $# != 2 ]
then echo "Give as parameters the GeNoC directory and the complete path to the ACL2 books..." ; exit
fi
if [ -d $1 ] 
then echo "In directory " $1 "..." ; \
      sed -i 's|\(ACL2_SYSTEM_BOOKS = \)\([[:print:]]*\)|\1'"$2"'|' $1/Makefile

     for fic in `ls $1`
     do
        $0 $1/$fic $2
     done
fi
