include ../../Makefile-generic
ACL2 = ../../../saved_acl2
# Dependencies:

solutions-logic-mode.cert: solutions-logic-mode.lisp
solutions-logic-mode.cert: ../../ihs/ihs-lemmas.cert

solutions-program-mode.cert: solutions-program-mode.lisp
