include ../../../../../Makefile-generic


BOOKS = efficient-simulator partial-clock-functions

efficient-simulator.cert: efficient-simulator.lisp
efficient-simulator.cert: partial-clock-functions.cert

partial-clock-functions.cert: partial-clock-functions.lisp
partial-clock-functions.cert: ../tiny-fib-example/defstobj+.cert
