include ../../../../../../Makefile-generic
ACL2 = ../../../../../../../saved_acl2

file-io-pkgs.cert: file-io-pkgs.lisp
file-io-pkgs.cert: ../../../../../../misc/file-io.cert

simplify-defuns.cert: simplify-defuns.lisp
simplify-defuns.cert: file-io-pkgs.cert

wrapper.cert: wrapper.lisp
