(EXLD::READ-MACH_HEADER
     (103 18 (:REWRITE LEN-WHEN-ATOM))
     (24 24
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (24 24
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (24 24
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (24 24
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (18 9 (:REWRITE DEFAULT-+-2))
     (10 9 (:REWRITE DEFAULT-CDR))
     (9 9 (:REWRITE DEFAULT-+-1))
     (9 9 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (9 1 (:REWRITE MAYBE-NATP-WHEN-NATP))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (3 1 (:REWRITE NATP-WHEN-GTE-0))
     (2 2 (:TYPE-PRESCRIPTION NATP))
     (2 2
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (2 2
        (:REWRITE VL::MAYBE-NATP-WHEN-MEMBER-EQUAL-OF-VL-MAYBE-NAT-LISTP))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS))
     (1 1 (:REWRITE NATP-WHEN-INTEGERP))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1)))
(EXLD::MACH-O-HEADER-P-OF-READ-MACH_HEADER)
(EXLD::UNSIGNED-BYTE-P-64-OF-MV-NTH-0-MERGE-FIRST-SPLIT-BYTES-4
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (1 1
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (1 1
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (1 1
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (1 1 (:REWRITE CONSP-BY-LEN)))
(EXLD::READ-SECTION_DATA_SZ_STRUCTURES
     (1033 46 (:REWRITE NFIX-WHEN-NOT-NATP))
     (1010 71 (:REWRITE NATP-WHEN-INTEGERP))
     (354 185 (:REWRITE DEFAULT-<-1))
     (242 39 (:REWRITE LEN-WHEN-ATOM))
     (192 192
          (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (185 185 (:REWRITE DEFAULT-<-2))
     (139 85 (:REWRITE DEFAULT-+-2))
     (136 8 (:DEFINITION LEN))
     (108 85 (:REWRITE DEFAULT-+-1))
     (68 4 (:DEFINITION TRUE-LISTP))
     (65 65 (:LINEAR LISTPOS-COMPLETE))
     (55 55
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (55 55
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (55 55
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (55 55
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (55 55 (:REWRITE CONSP-BY-LEN))
     (48 8
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (24 4 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (16 16 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (16 16
         (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (16 16
         (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
     (16 8 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (14 14 (:REWRITE DEFAULT-*-2))
     (14 14 (:REWRITE DEFAULT-*-1))
     (12 12 (:REWRITE DEFAULT-CDR))
     (10 6 (:REWRITE ZP-WHEN-GT-0))
     (8 8 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (8 8
        (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
     (8 8
        (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
     (8 8 (:REWRITE SET::IN-SET))
     (8 8 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (8 8
        (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (8 8
        (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (8 8 (:LINEAR LEN-WHEN-PREFIXP))
     (4 4
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (2 2 (:REWRITE SUBSETP-TRANS2))
     (2 2 (:REWRITE SUBSETP-TRANS))
     (2 2
        (:REWRITE INEQUALITY-WITH-NFIX-HYP-2)))
(EXLD::BYTE-LISTP-OF-READ-SECTION_DATA_SZ_STRUCTURES.FILE-BYTES
     (2143 358 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (1763 358 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (1584 264
           (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (905 905
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 2))
     (905 905
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 1))
     (905 905
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 2))
     (905 905
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 1))
     (905 905 (:REWRITE CONSP-BY-LEN))
     (381 381 (:REWRITE SUBSETP-TRANS2))
     (381 381 (:REWRITE SUBSETP-TRANS))
     (243 81 (:REWRITE ZP-WHEN-GT-0))
     (100 100 (:REWRITE DEFAULT-+-2))
     (100 100 (:REWRITE DEFAULT-+-1))
     (81 81 (:REWRITE ZP-WHEN-INTEGERP))
     (81 81 (:REWRITE ZP-OPEN))
     (81 81 (:REWRITE DEFAULT-<-2))
     (81 81 (:REWRITE DEFAULT-<-1))
     (33 1 (:REWRITE REVERSE-REMOVAL))
     (20 1 (:DEFINITION TRUE-LISTP))
     (16 2 (:REWRITE REV-WHEN-NOT-CONSP))
     (12 2
         (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (4 4
        (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
     (4 2 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (2 2
        (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (2 2 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (2 2
        (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
     (2 2
        (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
     (2 2 (:REWRITE SET::IN-SET))
     (2 1 (:REWRITE STR::CONSP-OF-EXPLODE))
     (1 1
        (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (1 1 (:REWRITE DEFAULT-CDR)))
(EXLD::GOOD-MACH-O-P-OF-READ-SECTION_DATA_SZ_STRUCTURES.NEW-MACH-O)
(EXLD::LEN-MV-NTH-1-READ-SECTION_DATA_SZ_STRUCTURES-SZ=4
     (996 24 (:DEFINITION BINARY-APPEND))
     (828 16 (:REWRITE REVERSE-REMOVAL))
     (816 48 (:DEFINITION LEN))
     (768 12 (:REWRITE REV-OF-CONS))
     (751 118 (:REWRITE LEN-WHEN-ATOM))
     (632 28 (:DEFINITION TRUE-LISTP))
     (540 12 (:REWRITE ASSOCIATIVITY-OF-APPEND))
     (420 48 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (360 360
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 2))
     (360 360
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 1))
     (360 360
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 2))
     (360 360
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 1))
     (360 360 (:REWRITE CONSP-BY-LEN))
     (336 56
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (292 100 (:REWRITE DEFAULT-CDR))
     (264 84 (:REWRITE CONSP-OF-REV))
     (264 22 (:REWRITE NFIX-WHEN-NOT-NATP))
     (216 24 (:REWRITE DEFAULT-CAR))
     (205 156 (:REWRITE DEFAULT-+-2))
     (160 156 (:REWRITE DEFAULT-+-1))
     (158 26 (:REWRITE NATP-WHEN-INTEGERP))
     (147 117 (:REWRITE DEFAULT-<-1))
     (136 20 (:REWRITE REV-WHEN-NOT-CONSP))
     (120 117 (:REWRITE DEFAULT-<-2))
     (118 118
          (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (112 112 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (112 112
          (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
     (112 56 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (104 104 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (90 15 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (72 72 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (57 19 (:REWRITE ZP-WHEN-GT-0))
     (56 56 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (56 56
         (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
     (56 56
         (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
     (56 56 (:REWRITE SET::IN-SET))
     (34 34 (:REWRITE DEFAULT-*-2))
     (34 34 (:REWRITE DEFAULT-*-1))
     (32 32
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (32 32
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (32 32 (:LINEAR LEN-WHEN-PREFIXP))
     (30 30
         (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (24 24
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (24 24
         (:REWRITE EXLD::!MACH-O-!MACH-O-SHADOW-WRITES))
     (16 16
         (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (15 15 (:REWRITE DEFAULT-UNARY-MINUS))
     (12 12 (:REWRITE CDR-CONS))
     (8 8
        (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (8 4 (:REWRITE STR::CONSP-OF-EXPLODE))
     (4 4
        (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (2 2
        (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
     (1 1
        (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
     (1 1 (:REWRITE SUBLISTP-COMPLETE)))
(EXLD::LEN-MV-NTH-1-READ-SECTION_DATA_SZ_STRUCTURES-SZ=8
     (996 24 (:DEFINITION BINARY-APPEND))
     (828 16 (:REWRITE REVERSE-REMOVAL))
     (816 48 (:DEFINITION LEN))
     (768 12 (:REWRITE REV-OF-CONS))
     (632 28 (:DEFINITION TRUE-LISTP))
     (619 96 (:REWRITE LEN-WHEN-ATOM))
     (540 12 (:REWRITE ASSOCIATIVITY-OF-APPEND))
     (420 48 (:REWRITE APPEND-WHEN-NOT-CONSP))
     (338 338
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 2))
     (338 338
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 1))
     (338 338
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 2))
     (338 338
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 1))
     (338 338 (:REWRITE CONSP-BY-LEN))
     (336 56
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (292 100 (:REWRITE DEFAULT-CDR))
     (288 24 (:REWRITE NFIX-WHEN-NOT-NATP))
     (264 84 (:REWRITE CONSP-OF-REV))
     (216 24 (:REWRITE DEFAULT-CAR))
     (209 160 (:REWRITE DEFAULT-+-2))
     (172 28 (:REWRITE NATP-WHEN-INTEGERP))
     (164 160 (:REWRITE DEFAULT-+-1))
     (149 119 (:REWRITE DEFAULT-<-1))
     (136 20 (:REWRITE REV-WHEN-NOT-CONSP))
     (126 126
          (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (122 119 (:REWRITE DEFAULT-<-2))
     (112 112 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (112 112
          (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
     (112 56 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (104 104 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (90 15 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (72 72 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (56 56 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (56 56
         (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
     (56 56
         (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
     (56 56 (:REWRITE SET::IN-SET))
     (54 18 (:REWRITE ZP-WHEN-GT-0))
     (34 34 (:REWRITE DEFAULT-*-2))
     (34 34 (:REWRITE DEFAULT-*-1))
     (30 30
         (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (26 26
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (26 26
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (26 26 (:LINEAR LEN-WHEN-PREFIXP))
     (24 24
         (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
     (24 24
         (:REWRITE EXLD::!MACH-O-!MACH-O-SHADOW-WRITES))
     (15 15 (:REWRITE DEFAULT-UNARY-MINUS))
     (13 13
         (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (12 12 (:REWRITE CDR-CONS))
     (8 8
        (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (8 4 (:REWRITE STR::CONSP-OF-EXPLODE))
     (7 7
        (:LINEAR EXLD::LEN-MV-NTH-1-READ-SECTION_DATA_SZ_STRUCTURES-SZ=4))
     (4 4
        (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (2 2
        (:REWRITE VL::PREFIXP-WHEN-MEMBER-EQUAL-OF-PREFIX-OF-EACHP))
     (1 1
        (:REWRITE VL::TRANSITIVITY-OF-PREFIXP))
     (1 1 (:REWRITE SUBLISTP-COMPLETE))
     (1 1 (:LINEAR LISTPOS-COMPLETE)))
(EXLD::READ-LOAD_COMMANDS
     (5154 260 (:REWRITE NFIX-WHEN-NATP))
     (5112 309 (:REWRITE NATP-WHEN-INTEGERP))
     (4000 260 (:REWRITE NFIX-WHEN-NOT-NATP))
     (2065 35 (:DEFINITION NTHCDR))
     (2011 1060 (:REWRITE DEFAULT-<-1))
     (1545 70 (:REWRITE NTHCDR-WHEN-ZP))
     (1300 1060 (:REWRITE DEFAULT-<-2))
     (927 579 (:REWRITE DEFAULT-+-2))
     (867 51 (:DEFINITION TRUE-LISTP))
     (787 579 (:REWRITE DEFAULT-+-1))
     (690 690
          (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (577 102
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (546 168 (:REWRITE LEN-WHEN-ATOM))
     (512 97 (:REWRITE ZP-WHEN-GT-0))
     (414 414 (:REWRITE SUBSETP-MEMBER . 4))
     (414 414 (:REWRITE SUBSETP-MEMBER . 3))
     (414 414 (:REWRITE SUBSETP-MEMBER . 2))
     (414 414 (:REWRITE SUBSETP-MEMBER . 1))
     (414 414 (:REWRITE INTERSECTP-MEMBER . 3))
     (414 414 (:REWRITE INTERSECTP-MEMBER . 2))
     (400 70 (:REWRITE NTHCDR-WHEN-ATOM))
     (318 318 (:LINEAR LISTPOS-COMPLETE))
     (306 18 (:DEFINITION LEN))
     (284 284
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 2))
     (284 284
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 1))
     (284 284
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 2))
     (284 284
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 1))
     (284 284 (:REWRITE CONSP-BY-LEN))
     (279 104 (:REWRITE DEFAULT-CDR))
     (222 37 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (204 204
          (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
     (190 190 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (190 95 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (140 35 (:REWRITE FOLD-CONSTS-IN-+))
     (114 57 (:REWRITE DEFAULT-UNARY-MINUS))
     (102 102
          (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
     (102 102
          (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
     (95 95 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (95 95 (:REWRITE SET::IN-SET))
     (60 60
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (60 60
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (60 60 (:LINEAR LEN-WHEN-PREFIXP))
     (59 31
         (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
     (53 53 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (48 30 (:REWRITE DEFAULT-*-2))
     (42 30 (:REWRITE DEFAULT-*-1))
     (35 35 (:REWRITE OPEN-SMALL-NTHCDR))
     (30 30
         (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (24 4 (:REWRITE REV-WHEN-NOT-CONSP))
     (1 1 (:REWRITE SUBSETP-TRANS2))
     (1 1 (:REWRITE SUBSETP-TRANS)))
(EXLD::BYTE-LISTP-OF-READ-LOAD_COMMANDS.FILE-BYTES
     (18115 1092 (:REWRITE NATP-WHEN-INTEGERP))
     (17966 598 (:REWRITE NFIX-WHEN-NATP))
     (13818 598 (:REWRITE NFIX-WHEN-NOT-NATP))
     (6854 3596 (:REWRITE DEFAULT-<-1))
     (6629 1092 (:REWRITE NATP-WHEN-GTE-0))
     (6549 111 (:DEFINITION NTHCDR))
     (4947 222 (:REWRITE NTHCDR-WHEN-ZP))
     (4330 3596 (:REWRITE DEFAULT-<-2))
     (3662 428 (:REWRITE ZP-WHEN-INTEGERP))
     (3415 570 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (2850 570 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (2730 455
           (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (2184 2184
           (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (2178 1328 (:REWRITE DEFAULT-+-2))
     (2141 2141
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                     . 2))
     (2141 2141
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                     . 1))
     (2141 2141
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                     . 2))
     (2141 2141
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                     . 1))
     (2141 2141 (:REWRITE CONSP-BY-LEN))
     (2007 428 (:REWRITE ZP-WHEN-GT-0))
     (1690 1328 (:REWRITE DEFAULT-+-1))
     (1576 256 (:REWRITE LEN-WHEN-ATOM))
     (1278 222 (:REWRITE NTHCDR-WHEN-ATOM))
     (1260 1260 (:LINEAR LISTPOS-COMPLETE))
     (1136 1136 (:TYPE-PRESCRIPTION LEN))
     (1092 1092 (:TYPE-PRESCRIPTION NATP))
     (717 162 (:REWRITE DEFAULT-CDR))
     (680 40 (:DEFINITION LEN))
     (609 609 (:REWRITE SUBSETP-TRANS2))
     (609 609 (:REWRITE SUBSETP-TRANS))
     (444 111 (:REWRITE FOLD-CONSTS-IN-+))
     (365 13 (:REWRITE REVERSE-REMOVAL))
     (296 148 (:REWRITE DEFAULT-UNARY-MINUS))
     (272 34 (:REWRITE REV-WHEN-NOT-CONSP))
     (240 240
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (240 240
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (240 240 (:LINEAR LEN-WHEN-PREFIXP))
     (220 11 (:DEFINITION TRUE-LISTP))
     (151 151 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (132 48
          (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
     (132 22
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (128 128 (:REWRITE ZP-OPEN))
     (120 120
          (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (111 111 (:REWRITE OPEN-SMALL-NTHCDR))
     (110 110 (:REWRITE SUBSETP-MEMBER . 4))
     (110 110 (:REWRITE SUBSETP-MEMBER . 3))
     (110 110 (:REWRITE SUBSETP-MEMBER . 2))
     (110 110 (:REWRITE SUBSETP-MEMBER . 1))
     (110 110 (:REWRITE INTERSECTP-MEMBER . 3))
     (110 110 (:REWRITE INTERSECTP-MEMBER . 2))
     (96 56 (:REWRITE DEFAULT-*-2))
     (72 56 (:REWRITE DEFAULT-*-1))
     (44 44 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (44 44
         (:REWRITE VL::TRUE-LISTP-WHEN-MEMBER-EQUAL-OF-TRUE-LIST-LISTP))
     (44 22 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (34 34
         (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (34 17 (:REWRITE STR::CONSP-OF-EXPLODE))
     (22 22 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (22 22
         (:REWRITE TRUE-LISTP-WHEN-UNSIGNED-BYTE-LISTP))
     (22 22
         (:REWRITE TRUE-LISTP-WHEN-SIGNED-BYTE-LISTP))
     (22 22 (:REWRITE SET::IN-SET))
     (17 17
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP)))
(EXLD::GOOD-MACH-O-P-OF-READ-LOAD_COMMANDS.NEW-MACH-O)
(EXLD::MACH-O-LEMMA-1)
(EXLD::MACH-O-LEMMA-2)
(EXLD::FILL-TEXT-TEXT-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-TEXT-TEXT-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-TEXT-TEXT-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::MACH-O-LEMMA-3)
(EXLD::MACH-O-LEMMA-4)
(EXLD::FILL-TEXT-CSTRING-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-TEXT-CSTRING-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-TEXT-CSTRING-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::MACH-O-LEMMA-5)
(EXLD::MACH-O-LEMMA-6)
(EXLD::FILL-TEXT-CONST-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-TEXT-CONST-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-TEXT-CONST-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::FILL-TEXT-SEGMENT-BYTES)
(EXLD::GOOD-MACH-O-P-OF-FILL-TEXT-SEGMENT-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-TEXT-SEGMENT-BYTES.NEW-STATE
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1)))
(EXLD::MACH-O-LEMMA-7)
(EXLD::MACH-O-LEMMA-8)
(EXLD::FILL-DATA-DATA-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-DATA-DATA-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-DATA-DATA-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::MACH-O-LEMMA-9)
(EXLD::MACH-O-LEMMA-10)
(EXLD::FILL-DATA-DYLD-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-DATA-DYLD-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-DATA-DYLD-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::MACH-O-LEMMA-11)
(EXLD::MACH-O-LEMMA-12)
(EXLD::FILL-DATA-CONST-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-DATA-CONST-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-DATA-CONST-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::MACH-O-LEMMA-13)
(EXLD::MACH-O-LEMMA-14)
(EXLD::FILL-DATA-BSS-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-DATA-BSS-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-DATA-BSS-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::MACH-O-LEMMA-15)
(EXLD::MACH-O-LEMMA-16)
(EXLD::FILL-DATA-COMMON-SECTION-BYTES
     (143 11 (:REWRITE NATP-WHEN-GTE-0))
     (118 62 (:REWRITE DEFAULT-+-2))
     (108 42 (:REWRITE DEFAULT-<-1))
     (90 62 (:REWRITE DEFAULT-+-1))
     (44 1 (:DEFINITION NTHCDR))
     (42 42 (:REWRITE DEFAULT-<-2))
     (38 2 (:REWRITE NTHCDR-WHEN-ZP))
     (32 32 (:REWRITE DEFAULT-UNARY-MINUS))
     (29 29 (:REWRITE FOLD-CONSTS-IN-+))
     (24 3 (:REWRITE ZP-WHEN-INTEGERP))
     (22 22
         (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (15 3 (:REWRITE ZP-WHEN-GT-0))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (6 1 (:REWRITE DEFAULT-CDR))
     (6 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (5 5 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                  . 1))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 2))
     (4 4
        (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                  . 1))
     (4 4 (:REWRITE CONSP-BY-LEN))
     (2 2 (:TYPE-PRESCRIPTION ZP))
     (2 2
        (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE CONSP-OF-CDR-BY-LEN)))
(EXLD::GOOD-MACH-O-P-OF-FILL-DATA-COMMON-SECTION-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-DATA-COMMON-SECTION-BYTES.NEW-STATE
     (305 1 (:DEFINITION TAKE))
     (246 2 (:REWRITE TAKE-OF-TOO-MANY))
     (182 2 (:REWRITE LEN-OF-NTHCDR))
     (154 9 (:DEFINITION LEN))
     (140 2 (:REWRITE TAKE-OF-LEN-FREE))
     (138 1 (:REWRITE CAR-OF-NTHCDR))
     (120 20 (:REWRITE LEN-WHEN-ATOM))
     (119 3 (:REWRITE CONSP-OF-NTHCDR))
     (81 1 (:DEFINITION NTH))
     (76 33 (:REWRITE DEFAULT-+-2))
     (69 69 (:TYPE-PRESCRIPTION LEN))
     (67 2 (:REWRITE NTH-WHEN-TOO-LARGE-CHEAP))
     (63 12 (:REWRITE DEFAULT-CDR))
     (61 2 (:REWRITE TAKE-WHEN-ATOM))
     (52 11 (:REWRITE NFIX-WHEN-NATP))
     (48 6 (:REWRITE ZP-WHEN-INTEGERP))
     (44 1 (:DEFINITION NTHCDR))
     (41 33 (:REWRITE DEFAULT-+-1))
     (40 2 (:REWRITE NTHCDR-WHEN-ZP))
     (34 3 (:REWRITE NATP-WHEN-GTE-0))
     (34 2 (:REWRITE NTH-WHEN-ZP))
     (32 16
         (:TYPE-PRESCRIPTION TRUE-LISTP-NTHCDR-TYPE-PRESCRIPTION))
     (32 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (30 23 (:REWRITE DEFAULT-<-2))
     (30 6 (:REWRITE ZP-WHEN-GT-0))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                   . 1))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 2))
     (29 29
         (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                   . 1))
     (29 29 (:REWRITE CONSP-BY-LEN))
     (28 23 (:REWRITE DEFAULT-<-1))
     (24 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
     (23 3 (:REWRITE NATP-WHEN-INTEGERP))
     (21 1 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (18 18
         (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (18 18
         (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (18 18 (:LINEAR LEN-WHEN-PREFIXP))
     (18 10 (:REWRITE DEFAULT-UNARY-MINUS))
     (16 16 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (16 16 (:REWRITE FOLD-CONSTS-IN-+))
     (14 14 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (13 2 (:REWRITE NTHCDR-WHEN-ATOM))
     (13 2 (:REWRITE NTH-WHEN-ATOM))
     (12 12 (:TYPE-PRESCRIPTION NFIX))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (9 9
        (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6
        (:REWRITE VL::NATP-WHEN-MEMBER-EQUAL-OF-NAT-LISTP))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (3 3 (:LINEAR LISTPOS-COMPLETE))
     (2 2 (:REWRITE REDUCE-INTEGERP-+-CONSTANT))
     (2 2 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (2 2
        (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-1))
     (1 1 (:REWRITE DEFAULT-CAR)))
(EXLD::FILL-DATA-SEGMENT-BYTES)
(EXLD::GOOD-MACH-O-P-OF-FILL-DATA-SEGMENT-BYTES.NEW-MACH-O)
(EXLD::STATE-P-OF-FILL-DATA-SEGMENT-BYTES.NEW-STATE
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1)))
(EXLD::MACH-O-LEMMA-17)
(EXLD::POPULATE-MACH-O-CONTENTS
     (3296 32 (:DEFINITION TAKE))
     (1930 106 (:DEFINITION LEN))
     (1706 64 (:REWRITE TAKE-OF-TOO-MANY))
     (1591 64 (:REWRITE TAKE-OF-LEN-FREE))
     (1209 214 (:REWRITE LEN-WHEN-ATOM))
     (390 390
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 2))
     (390 390
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                    . 1))
     (390 390
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 2))
     (390 390
          (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                    . 1))
     (390 390 (:REWRITE CONSP-BY-LEN))
     (322 142 (:REWRITE DEFAULT-CDR))
     (316 64 (:REWRITE TAKE-WHEN-ATOM))
     (238 238 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (212 106 (:REWRITE DEFAULT-+-2))
     (208 208
          (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (208 208
          (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (208 208 (:LINEAR LEN-WHEN-PREFIXP))
     (192 32 (:REWRITE DEFAULT-CAR))
     (106 106 (:REWRITE DEFAULT-+-1))
     (104 104
          (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (90 57 (:REWRITE DEFAULT-<-2))
     (64 64 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (64 57 (:REWRITE DEFAULT-<-1))
     (60 4 (:DEFINITION NTHCDR))
     (52 8 (:REWRITE NTHCDR-WHEN-ATOM))
     (36 12
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (36 6 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (34 34
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (34 34
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (24 24 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (22 11 (:REWRITE NFIX-WHEN-NOT-NATP))
     (19 19 (:REWRITE SUBSETP-TRANS2))
     (19 19 (:REWRITE SUBSETP-TRANS))
     (16 16
         (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (8 8 (:REWRITE NTHCDR-WHEN-ZP))
     (4 4 (:REWRITE OPEN-SMALL-NTHCDR))
     (1 1
        (:REWRITE-QUOTED-CONSTANT MAYBE-NATP-FIX-UNDER-MAYBE-NAT-EQUIV))
     (1 1 (:REWRITE CONSP-OF-TAKE)))
(EXLD::GOOD-MACH-O-P-OF-POPULATE-MACH-O-CONTENTS.NEW-MACH-O)
(EXLD::STATE-P-OF-POPULATE-MACH-O-CONTENTS.NEW-STATE
     (25235 245 (:DEFINITION TAKE))
     (13305 725 (:DEFINITION LEN))
     (13152 490 (:REWRITE TAKE-OF-TOO-MANY))
     (12912 490 (:REWRITE TAKE-OF-LEN-FREE))
     (8105 1450 (:REWRITE LEN-WHEN-ATOM))
     (4179 4179 (:TYPE-PRESCRIPTION LEN))
     (2812 2812
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                     . 2))
     (2812 2812
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-PREFIXMAP-P
                     . 1))
     (2812 2812
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                     . 2))
     (2812 2812
           (:REWRITE VL::CONSP-WHEN-MEMBER-EQUAL-OF-VL-NAMEDB-NAMESET-P
                     . 1))
     (2812 2812 (:REWRITE CONSP-BY-LEN))
     (2783 1068 (:REWRITE DEFAULT-CDR))
     (2305 490 (:REWRITE TAKE-WHEN-ATOM))
     (1884 1884
           (:LINEAR LOWER-BOUND-OF-LEN-WHEN-SUBLISTP))
     (1884 1884
           (:LINEAR LISTPOS-UPPER-BOUND-STRONG-2))
     (1884 1884 (:LINEAR LEN-WHEN-PREFIXP))
     (1803 1803 (:REWRITE CONSP-OF-CDR-BY-LEN))
     (1470 245 (:REWRITE DEFAULT-CAR))
     (1470 98 (:DEFINITION NTHCDR))
     (1450 725 (:REWRITE DEFAULT-+-2))
     (942 942
          (:LINEAR STR::COUNT-LEADING-CHARSET-LEN))
     (894 196 (:REWRITE NTHCDR-WHEN-ATOM))
     (725 725 (:REWRITE DEFAULT-+-1))
     (628 314 (:REWRITE DEFAULT-<-2))
     (490 490 (:REWRITE CONSP-OF-CDDR-BY-LEN))
     (337 337
          (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (337 337
          (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (314 314 (:TYPE-PRESCRIPTION NFIX))
     (314 314 (:REWRITE DEFAULT-<-1))
     (196 196 (:REWRITE NTHCDR-WHEN-ZP))
     (195 26 (:REWRITE BYTE-LISTP-WHEN-NOT-CONSP))
     (143 13 (:REWRITE BYTE-LISTP-OF-TAKE))
     (98 98 (:REWRITE OPEN-SMALL-NTHCDR))
     (52 52
         (:REWRITE BYTE-LISTP-WHEN-SUBSETP-EQUAL))
     (16 16
         (:REWRITE BITOPS::UNSIGNED-BYTE-P-INCR))
     (13 13 (:REWRITE CONSP-OF-TAKE))
     (12 6 (:REWRITE NFIX-WHEN-NOT-NATP)))
(EXLD::POPULATE-MACH-O)
(EXLD::GOOD-MACH-O-P-OF-POPULATE-MACH-O.NEW-MACH-O)
