include ../../../../Makefile-generic


# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

bv.cert: bv.lisp
bv.cert: ihs.cert
bv.cert: ../../../../arithmetic-2/pass1/top.cert
bv.cert: ../../../../ihs/quotient-remainder-lemmas.cert

ihs.cert: ihs.lisp
ihs.cert: ../../../../ihs/ihs-definitions.cert
ihs.cert: ../../../../ihs/logops-lemmas.cert
