# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../../Makefile-generic

ACL2 = ../../../../../../saved_acl2

# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

npol.cert: npol.lisp
npol.cert: upol-2.cert
# Added manually:
npol.cert: npol.acl2

upol-1.cert: upol-1.lisp
# Added manually:
upol-1.cert: upol-1.acl2

upol-2.cert: upol-2.lisp
# Added manually:
upol-2.cert: upol-2.acl2
