include ../../../../../../../Makefile-generic

ACL2 = ../../../../../../../../saved_acl2

# Dependencies:

inst.cert: inst.lisp

non-det-encap-wfbisim.cert: non-det-encap-wfbisim.lisp
non-det-encap-wfbisim.cert: ../../top/defun-weak-sk.cert
non-det-encap-wfbisim.cert: ../../../../../../../ordinals/e0-ordinal.cert

non-det-macros.cert: non-det-macros.lisp




