include ../../../Makefile-generic

BOOKS = basic bits log logn float reps round \
        rtl rtlarr bvecp-raw-helpers bvecp-helpers simple-loop-helpers \
        simplify-model-helpers util add rom-helpers clocks package-defs \
        openers mult \
	logn2log  srt sqrt masc  \
	top
 
# Dependencies:
-include Makefile-deps
