(SATLINK::LIT-TO-LRAT-LITERAL
     (9 3 (:REWRITE DEFAULT-*-2))
     (8 8
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (8 8
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
     (6 2 (:REWRITE DEFAULT-UNARY-MINUS))
     (5 2 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE DEFAULT-*-1))
     (2 2 (:REWRITE DEFAULT-+-1)))
(SATLINK::LITERALP-OF-LIT-TO-LRAT-LITERAL)
(SATLINK::NEGATE-OF-LIT-TO-LRAT-LITERAL
     (36 18 (:REWRITE DEFAULT-*-1))
     (34 18 (:REWRITE DEFAULT-*-2))
     (24 9 (:REWRITE DEFAULT-+-2))
     (16 1 (:REWRITE BFIX-WHEN-NOT-1))
     (15 15
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (15 15
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
     (15 9 (:REWRITE DEFAULT-+-1))
     (11 4 (:REWRITE DEFAULT-UNARY-MINUS))
     (3 1 (:REWRITE BFIX-WHEN-NOT-BITP))
     (2 2 (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (2 1 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (2 1 (:REWRITE BFIX-WHEN-BIT->BOOL)))
(SATLINK::LIT-FIX-IS-MAKE-LIT)
(SATLINK::EQUAL-OF-LIT-TO-LRAT-LITERAL
     (48 26 (:REWRITE DEFAULT-*-1))
     (46 46
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (46 46
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
     (46 26 (:REWRITE DEFAULT-*-2))
     (32 2 (:REWRITE BFIX-WHEN-NOT-1))
     (28 12 (:REWRITE DEFAULT-+-2))
     (22 22
         (:LINEAR SATLINK::INDEX-OF-LITERALS-IS-BOUNDED-BY-MAX-INDEX-CLAUSE))
     (16 12 (:REWRITE DEFAULT-+-1))
     (6 2 (:REWRITE BFIX-WHEN-NOT-BITP))
     (4 4 (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (4 2 (:REWRITE NFIX-WHEN-NOT-NATP))
     (4 2 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (4 2 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (3 3
        (:REWRITE SATLINK::EQUAL-OF-LIT->VAR-NEGATED-HYP))
     (3 3
        (:REWRITE SATLINK::EQUAL-OF-LIT->VAR-EQUAL-HYP)))
(SATLINK::ENV$-TO-LRAT-ASSIGNMENT
     (12 2 (:REWRITE BFIX-WHEN-NOT-1))
     (10 2 (:DEFINITION LEN))
     (9 7 (:REWRITE DEFAULT-<-1))
     (7 7 (:REWRITE DEFAULT-<-2))
     (5 3 (:REWRITE DEFAULT-+-2))
     (4 4 (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (4 2 (:REWRITE ZP-WHEN-GT-0))
     (4 2 (:REWRITE BFIX-WHEN-NOT-BITP))
     (4 2 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (4 2 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (3 3 (:REWRITE DEFAULT-CDR))
     (3 3 (:REWRITE DEFAULT-+-1))
     (3 1 (:REWRITE NATP-WHEN-GTE-0))
     (3 1 (:DEFINITION BITARR$AP))
     (2 2
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
     (2 2
        (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-NECC))
     (1 1 (:REWRITE NATP-WHEN-INTEGERP))
     (1 1 (:REWRITE DEFAULT-CAR)))
(SATLINK::LITERAL-LISTP-OF-ENV$-TO-LRAT-ASSIGNMENT
     (69 16
         (:REWRITE LRAT::BACKCHAIN-TO-CLAUSE-OR-ASSIGNMENT-P))
     (46 46
         (:TYPE-PRESCRIPTION LRAT::CLAUSE-OR-ASSIGNMENT-P))
     (21 7
         (:REWRITE LRAT::CLAUSE-OR-ASSIGNMENT-P-CDR))
     (18 6 (:REWRITE ZP-WHEN-GT-0))
     (9 8 (:REWRITE DEFAULT-CDR))
     (9 8 (:REWRITE DEFAULT-CAR))
     (6 6 (:REWRITE ZP-WHEN-INTEGERP))
     (6 6 (:REWRITE ZP-OPEN))
     (6 6 (:REWRITE DEFAULT-<-2))
     (6 6 (:REWRITE DEFAULT-<-1))
     (6 1 (:REWRITE BFIX-WHEN-NOT-1))
     (2 2 (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (2 2
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (2 2
        (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
     (2 2
        (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-NECC))
     (2 2 (:REWRITE DEFAULT-+-2))
     (2 2 (:REWRITE DEFAULT-+-1))
     (2 1 (:REWRITE BFIX-WHEN-NOT-BITP))
     (2 1 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (2 1 (:REWRITE BFIX-WHEN-BIT->BOOL)))
(SATLINK::NOT-MEMBER-LITERAL
     (79 5 (:DEFINITION MEMBER-EQUAL))
     (36 6 (:REWRITE BFIX-WHEN-NOT-1))
     (34 13 (:REWRITE SUBSETP-MEMBER . 1))
     (23 1 (:REWRITE SUBSETP-OF-CONS))
     (22 2
         (:REWRITE SATLINK::EQUAL-OF-LIT-FIX-BACKCHAIN))
     (19 13 (:REWRITE DEFAULT-<-1))
     (18 18
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (18 18
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
     (17 9 (:REWRITE NFIX-WHEN-NOT-NATP))
     (15 13 (:REWRITE DEFAULT-<-2))
     (15 5 (:REWRITE ZP-WHEN-GT-0))
     (13 13 (:REWRITE SUBSETP-MEMBER . 2))
     (12 12
         (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (12 12 (:REWRITE SUBSETP-MEMBER . 4))
     (12 12 (:REWRITE INTERSECTP-MEMBER . 3))
     (12 12 (:REWRITE INTERSECTP-MEMBER . 2))
     (12 6 (:REWRITE BFIX-WHEN-NOT-BITP))
     (12 6 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (12 6 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (8 8 (:TYPE-PRESCRIPTION NATP))
     (8 8
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (8 8
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (8 8
        (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
     (8 8
        (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-NECC))
     (8 4 (:REWRITE NATP-WHEN-GTE-0))
     (8 2 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (6 2
        (:REWRITE SATLINK::LIT->VAR-OF-MAKE-LIT))
     (5 5 (:REWRITE ZP-WHEN-INTEGERP))
     (5 5 (:REWRITE ZP-OPEN))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS))
     (5 5 (:REWRITE DEFAULT-CDR))
     (5 5 (:REWRITE DEFAULT-CAR))
     (5 5 (:REWRITE DEFAULT-+-2))
     (5 5 (:REWRITE DEFAULT-+-1))
     (5 5
        (:LINEAR SATLINK::INDEX-OF-LITERALS-IS-BOUNDED-BY-MAX-INDEX-CLAUSE))
     (5 2 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (4 4 (:TYPE-PRESCRIPTION SATLINK::LITP))
     (4 4 (:REWRITE NATP-WHEN-INTEGERP))
     (2 2
        (:REWRITE INEQUALITY-WITH-NFIX-HYP-1)))
(SATLINK::UNIQUE-LITERALSP-OF-ENV$-TO-LRAT-ASSIGNMENT
     (51 3 (:DEFINITION MEMBER-EQUAL))
     (42 6 (:REWRITE SUBSETP-CAR-MEMBER))
     (33 8
         (:REWRITE LRAT::BACKCHAIN-TO-CLAUSE-OR-ASSIGNMENT-P))
     (22 22
         (:TYPE-PRESCRIPTION LRAT::CLAUSE-OR-ASSIGNMENT-P))
     (18 3 (:REWRITE BFIX-WHEN-NOT-1))
     (13 11 (:REWRITE DEFAULT-CDR))
     (12 12 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (12 4 (:REWRITE ZP-WHEN-GT-0))
     (9 3
        (:REWRITE LRAT::CLAUSE-OR-ASSIGNMENT-P-CDR))
     (8 7 (:REWRITE DEFAULT-CAR))
     (6 6 (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (6 6
        (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (6 6
        (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (6 6
        (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
     (6 6 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (6 6 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (6 6 (:REWRITE SUBSETP-TRANS2))
     (6 6 (:REWRITE SUBSETP-TRANS))
     (6 6 (:REWRITE SUBSETP-MEMBER . 4))
     (6 6 (:REWRITE SUBSETP-MEMBER . 3))
     (6 6 (:REWRITE SUBSETP-MEMBER . 2))
     (6 6 (:REWRITE SUBSETP-MEMBER . 1))
     (6 6 (:REWRITE MEMBER-WHEN-ATOM))
     (6 6 (:REWRITE INTERSECTP-MEMBER . 3))
     (6 6 (:REWRITE INTERSECTP-MEMBER . 2))
     (6 6
        (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-NECC))
     (6 3 (:REWRITE BFIX-WHEN-NOT-BITP))
     (6 3 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (6 3 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (4 4 (:REWRITE ZP-WHEN-INTEGERP))
     (4 4 (:REWRITE ZP-OPEN))
     (4 4 (:REWRITE DEFAULT-<-2))
     (4 4 (:REWRITE DEFAULT-<-1))
     (3 3 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (3 3 (:REWRITE DEFAULT-+-2))
     (3 3 (:REWRITE DEFAULT-+-1))
     (2 2 (:REWRITE NFIX-WHEN-NOT-NATP))
     (1 1
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (1 1
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES)))
(SATLINK::NOT-CONFLICTING-LITERALSP-OF-ENV$-TO-LRAT-ASSIGNMENT
     (42 10
         (:REWRITE LRAT::BACKCHAIN-TO-CLAUSE-OR-ASSIGNMENT-P))
     (40 4 (:DEFINITION MEMBER-EQUAL))
     (30 5 (:REWRITE BFIX-WHEN-NOT-1))
     (28 28
         (:TYPE-PRESCRIPTION LRAT::CLAUSE-OR-ASSIGNMENT-P))
     (16 14 (:REWRITE DEFAULT-CDR))
     (15 5 (:REWRITE ZP-WHEN-GT-0))
     (12 4
         (:REWRITE LRAT::CLAUSE-OR-ASSIGNMENT-P-CDR))
     (10 10
         (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (10 10
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (10 10
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (10 10
         (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
     (10 9 (:REWRITE DEFAULT-CAR))
     (10 5 (:REWRITE BFIX-WHEN-NOT-BITP))
     (10 5 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (10 5 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (8 8 (:REWRITE SUBSETP-MEMBER . 4))
     (8 8 (:REWRITE SUBSETP-MEMBER . 3))
     (8 8 (:REWRITE SUBSETP-MEMBER . 2))
     (8 8 (:REWRITE SUBSETP-MEMBER . 1))
     (8 8 (:REWRITE MEMBER-WHEN-ATOM))
     (8 8 (:REWRITE INTERSECTP-MEMBER . 3))
     (8 8 (:REWRITE INTERSECTP-MEMBER . 2))
     (8 8
        (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-NECC))
     (8 4 (:REWRITE DEFAULT-UNARY-MINUS))
     (5 5 (:REWRITE ZP-WHEN-INTEGERP))
     (5 5 (:REWRITE ZP-OPEN))
     (5 5 (:REWRITE DEFAULT-<-2))
     (5 5 (:REWRITE DEFAULT-<-1))
     (4 4 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (4 4
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (4 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:REWRITE DEFAULT-+-1))
     (2 2 (:REWRITE NFIX-WHEN-NOT-NATP))
     (1 1
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (1 1
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES)))
(SATLINK::CLAUSE-OR-ASSIGNMENT-P-OF-ENV$-TO-LRAT-ASSIGNMENT)
(SATLINK::EVALUATE-LITERAL-OF-ENV$-TO-LRAT-ASSIGNMENT
     (230 35 (:REWRITE BFIX-WHEN-NOT-1))
     (172 172
          (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (172 172
          (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
     (140 10 (:DEFINITION MEMBER-EQUAL))
     (91 55 (:REWRITE DEFAULT-<-1))
     (82 82
         (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-NECC))
     (73 55 (:REWRITE DEFAULT-<-2))
     (70 35 (:REWRITE BFIX-WHEN-NOT-BITP))
     (70 35 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (70 35 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (56 40 (:REWRITE NFIX-WHEN-NOT-NATP))
     (50 8 (:REWRITE ZP-WHEN-INTEGERP))
     (49 1
         (:REWRITE SATLINK::LIT-NEGATE-NOT-EQUAL-WHEN-NEG-MATCHES))
     (48 48 (:REWRITE DEFAULT-+-2))
     (48 48 (:REWRITE DEFAULT-+-1))
     (46 2 (:REWRITE SUBSETP-OF-CONS))
     (42 42
         (:LINEAR SATLINK::INDEX-OF-LITERALS-IS-BOUNDED-BY-MAX-INDEX-CLAUSE))
     (40 16 (:REWRITE MEMBER-WHEN-ATOM))
     (38 38
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (38 38
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (38 38
         (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
     (35 1
         (:REWRITE SATLINK::LIT->NEG-OF-LIT-NEGATE))
     (34 34 (:REWRITE SUBSETP-MEMBER . 2))
     (32 32 (:REWRITE SUBSETP-MEMBER . 4))
     (32 32 (:REWRITE INTERSECTP-MEMBER . 3))
     (32 32 (:REWRITE INTERSECTP-MEMBER . 2))
     (17 7 (:REWRITE NATP-WHEN-GTE-0))
     (15 1
         (:REWRITE SATLINK::LIT-NEGATE-NOT-EQUAL-WHEN-VARS-MISMATCH))
     (14 14 (:TYPE-PRESCRIPTION SATLINK::LITP))
     (10 10 (:REWRITE SUBSETP-TRANS2))
     (10 10 (:REWRITE SUBSETP-TRANS))
     (10 10 (:REWRITE DEFAULT-CDR))
     (10 10 (:REWRITE DEFAULT-CAR))
     (7 7 (:REWRITE NATP-WHEN-INTEGERP))
     (2 2 (:REWRITE ZP-OPEN)))
(SATLINK::CLAUSE-TO-LRAT-CLAUSE
     (348 29 (:DEFINITION MEMBER-EQUAL))
     (110 20
          (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
     (80 10 (:DEFINITION TRUE-LISTP))
     (67 67 (:REWRITE SUBSETP-MEMBER . 4))
     (67 67 (:REWRITE INTERSECTP-MEMBER . 3))
     (67 67 (:REWRITE INTERSECTP-MEMBER . 2))
     (61 61 (:REWRITE SUBSETP-MEMBER . 2))
     (58 58 (:REWRITE MEMBER-WHEN-ATOM))
     (57 57 (:REWRITE DEFAULT-CDR))
     (55 55 (:REWRITE DEFAULT-CAR))
     (36 36 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
     (36 18 (:REWRITE SET::NONEMPTY-MEANS-SET))
     (18 18 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
     (18 18 (:REWRITE SET::IN-SET))
     (9 9 (:REWRITE SUBSETP-TRANS2))
     (9 9 (:REWRITE SUBSETP-TRANS)))
(SATLINK::LITERAL-LISTP-OF-CLAUSE-TO-LRAT-CLAUSE.LRAT-CLAUSE
     (213 48
          (:REWRITE LRAT::BACKCHAIN-TO-CLAUSE-OR-ASSIGNMENT-P))
     (180 15 (:DEFINITION MEMBER-EQUAL))
     (142 142
          (:TYPE-PRESCRIPTION LRAT::CLAUSE-OR-ASSIGNMENT-P))
     (69 23
         (:REWRITE LRAT::CLAUSE-OR-ASSIGNMENT-P-CDR))
     (57 57 (:REWRITE DEFAULT-CAR))
     (52 52 (:REWRITE DEFAULT-CDR))
     (35 35 (:REWRITE SUBSETP-MEMBER . 4))
     (35 35 (:REWRITE INTERSECTP-MEMBER . 3))
     (35 35 (:REWRITE INTERSECTP-MEMBER . 2))
     (32 32 (:REWRITE SUBSETP-MEMBER . 2))
     (30 30 (:REWRITE MEMBER-WHEN-ATOM))
     (5 5 (:REWRITE SUBSETP-TRANS2))
     (5 5 (:REWRITE SUBSETP-TRANS)))
(SATLINK::UNIQUE-LITERALS-OF-CLAUSE-TO-LRAT-CLAUSE
     (227 16 (:DEFINITION MEMBER-EQUAL))
     (98 14 (:REWRITE SUBSETP-CAR-MEMBER))
     (69 16
         (:REWRITE LRAT::BACKCHAIN-TO-CLAUSE-OR-ASSIGNMENT-P))
     (46 46
         (:TYPE-PRESCRIPTION LRAT::CLAUSE-OR-ASSIGNMENT-P))
     (38 38 (:REWRITE SUBSETP-MEMBER . 4))
     (38 38 (:REWRITE INTERSECTP-MEMBER . 3))
     (38 38 (:REWRITE INTERSECTP-MEMBER . 2))
     (34 34 (:REWRITE SUBSETP-MEMBER . 2))
     (34 34 (:REWRITE DEFAULT-CDR))
     (34 34 (:REWRITE DEFAULT-CAR))
     (32 32 (:REWRITE MEMBER-WHEN-ATOM))
     (21 7
         (:REWRITE LRAT::CLAUSE-OR-ASSIGNMENT-P-CDR))
     (20 20 (:REWRITE SUBSETP-TRANS2))
     (20 20 (:REWRITE SUBSETP-TRANS))
     (18 18
         (:TYPE-PRESCRIPTION SATLINK::LIT-TO-LRAT-LITERAL))
     (14 14 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (14 14 (:REWRITE SUBSETP-WHEN-ATOM-LEFT)))
(SATLINK::NOT-CONFLICTING-LITERALS-OF-CLAUSE-TO-LRAT-CLAUSE
     (212 19 (:DEFINITION MEMBER-EQUAL))
     (78 18
         (:REWRITE LRAT::BACKCHAIN-TO-CLAUSE-OR-ASSIGNMENT-P))
     (52 52
         (:TYPE-PRESCRIPTION LRAT::CLAUSE-OR-ASSIGNMENT-P))
     (44 44 (:REWRITE SUBSETP-MEMBER . 4))
     (44 44 (:REWRITE INTERSECTP-MEMBER . 3))
     (44 44 (:REWRITE INTERSECTP-MEMBER . 2))
     (40 40 (:REWRITE SUBSETP-MEMBER . 2))
     (40 40 (:REWRITE DEFAULT-CDR))
     (39 39 (:REWRITE DEFAULT-CAR))
     (38 38 (:REWRITE MEMBER-WHEN-ATOM))
     (24 8
         (:REWRITE LRAT::CLAUSE-OR-ASSIGNMENT-P-CDR))
     (22 22
         (:TYPE-PRESCRIPTION SATLINK::LIT-TO-LRAT-LITERAL))
     (16 8 (:REWRITE DEFAULT-UNARY-MINUS))
     (8 8
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (6 6 (:REWRITE SUBSETP-TRANS2))
     (6 6 (:REWRITE SUBSETP-TRANS)))
(SATLINK::CLAUSE-OR-ASSIGNMENT-P-OF-CLAUSE-TO-LRAT-CLAUSE)
(SATLINK::EVAL-CLAUSE-WHEN-TRUE-MEMBER
     (442 35 (:DEFINITION MEMBER-EQUAL))
     (108 18 (:REWRITE BFIX-WHEN-NOT-1))
     (79 79 (:REWRITE SUBSETP-MEMBER . 4))
     (79 79 (:REWRITE INTERSECTP-MEMBER . 3))
     (79 79 (:REWRITE INTERSECTP-MEMBER . 2))
     (74 74 (:REWRITE SUBSETP-MEMBER . 2))
     (69 69 (:REWRITE DEFAULT-CAR))
     (49 49 (:REWRITE DEFAULT-CDR))
     (36 36
         (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (36 18 (:REWRITE BFIX-WHEN-NOT-BITP))
     (36 18 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (36 18 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (25 1
         (:REWRITE SATLINK::EQUAL-OF-LIT-FIX-BACKCHAIN))
     (18 18 (:REWRITE SUBSETP-TRANS2))
     (18 18 (:REWRITE SUBSETP-TRANS))
     (16 16
         (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-IMPLIES-NOT-LIT-EVAL))
     (16 16
         (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-IMPLIES-LIT-EVAL))
     (15 15
         (:REWRITE SATLINK::EVAL-CLAUSE-WHEN-SOME-TRUE-LITERAL))
     (13 1 (:REWRITE SUBSETP-OF-CONS))
     (11 11
         (:TYPE-PRESCRIPTION SATLINK::VARP-OF-LIT->VAR))
     (10 2 (:REWRITE SATLINK::LIT-FIX-OF-LIT))
     (8 8 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (8 8 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (4 4 (:TYPE-PRESCRIPTION SATLINK::LITP))
     (4 1
        (:REWRITE SATLINK::LITP-OF-CAR-WHEN-LIT-LISTP))
     (3 3
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (3 3
        (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
     (3 3
        (:LINEAR SATLINK::INDEX-OF-LITERALS-IS-BOUNDED-BY-MAX-INDEX-CLAUSE))
     (3 1
        (:REWRITE SATLINK::LIT->VAR$INLINE-OF-LIT-FIX-LIT))
     (2 2
        (:TYPE-PRESCRIPTION SATLINK::LIT-LISTP))
     (1 1
        (:REWRITE SATLINK::LIT-LISTP-WHEN-NOT-CONSP))
     (1 1
        (:REWRITE SATLINK::EQUAL-OF-LIT->VAR-NEGATED-HYP))
     (1 1
        (:REWRITE SATLINK::EQUAL-OF-LIT->VAR-EQUAL-HYP)))
(SATLINK::CLAUSE-TO-LRAT-CLAUSE-TAUTOLOGYP-IMPLIES
     (379 34 (:REWRITE BFIX-WHEN-NOT-1))
     (252 21 (:DEFINITION MEMBER-EQUAL))
     (96 34 (:REWRITE BFIX-WHEN-NOT-BITP))
     (68 68
         (:TYPE-PRESCRIPTION BIT->BOOL$INLINE))
     (68 34 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
     (68 34 (:REWRITE BFIX-WHEN-BIT->BOOL))
     (52 52 (:REWRITE SUBSETP-MEMBER . 4))
     (52 52 (:REWRITE INTERSECTP-MEMBER . 3))
     (52 52 (:REWRITE INTERSECTP-MEMBER . 2))
     (52 52 (:REWRITE DEFAULT-CAR))
     (46 46 (:REWRITE SUBSETP-MEMBER . 2))
     (42 42
         (:TYPE-PRESCRIPTION SATLINK::LIT-TO-LRAT-LITERAL))
     (42 42 (:REWRITE MEMBER-WHEN-ATOM))
     (37 37 (:REWRITE DEFAULT-CDR))
     (32 32
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
     (32 32
         (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
     (28 28
         (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
     (28 28
         (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
     (28 28
         (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
     (22 22
         (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-NECC))
     (11 11
         (:REWRITE SATLINK::EVAL-CLAUSE-WHEN-SOME-TRUE-LITERAL))
     (10 10 (:REWRITE SUBSETP-TRANS2))
     (10 10 (:REWRITE SUBSETP-TRANS))
     (9 9
        (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-IMPLIES-NOT-LIT-EVAL))
     (9 9
        (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-IMPLIES-LIT-EVAL)))
(SATLINK::EVAL-OF-CLAUSE-TO-LRAT-CLAUSE
  (3779 277 (:DEFINITION MEMBER-EQUAL))
  (2272 66
        (:REWRITE SATLINK::INDEX-OF-LITERALS-IS-BOUNDED-BY-MAX-INDEX-CLAUSE))
  (1414 132 (:REWRITE SUBSETP-CAR-MEMBER))
  (1396 63
        (:REWRITE SATLINK::CLAUSE-TO-LRAT-CLAUSE-TAUTOLOGYP-IMPLIES))
  (571 571 (:REWRITE DEFAULT-CAR))
  (570 570 (:REWRITE DEFAULT-CDR))
  (560 560 (:REWRITE SUBSETP-MEMBER . 2))
  (490 70
       (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
  (437 437 (:REWRITE SUBSETP-MEMBER . 4))
  (437 437 (:REWRITE INTERSECTP-MEMBER . 3))
  (437 437 (:REWRITE INTERSECTP-MEMBER . 2))
  (422 422
       (:TYPE-PRESCRIPTION SATLINK::LIT-TO-LRAT-LITERAL))
  (422 422 (:REWRITE MEMBER-WHEN-ATOM))
  (280 144 (:REWRITE DEFAULT-<-1))
  (220 144 (:REWRITE DEFAULT-<-2))
  (217 217 (:REWRITE SUBSETP-TRANS2))
  (217 217 (:REWRITE SUBSETP-TRANS))
  (202 202 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
  (202 202 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
  (144 40 (:REWRITE NFIX-WHEN-NOT-NATP))
  (138 70 (:REWRITE NATP-WHEN-GTE-0))
  (118 59 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
  (118 59 (:REWRITE BFIX-WHEN-BIT->BOOL))
  (114 57 (:REWRITE BFIX-WHEN-NOT-BITP))
  (95 95
      (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COND-COMPONENT-REWRITES))
  (95 95
      (:REWRITE SATLINK::EQUAL-OF-LIT-NEGATE-COMPONENT-REWRITES))
  (70 70 (:REWRITE NATP-WHEN-INTEGERP))
  (61 61
      (:REWRITE SATLINK::EVAL-CLAUSE-WHEN-SOME-TRUE-LITERAL))
  (57 57
      (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-IMPLIES-NOT-LIT-EVAL))
  (57 57
      (:REWRITE SATLINK::ENV-SATISFIES-ASSUMS-IMPLIES-LIT-EVAL))
  (57 57
      (:LINEAR SATLINK::INDEX-OF-LITERALS-IS-BOUNDED-BY-MAX-INDEX-CLAUSE))
  (28 28
      (:LINEAR SATLINK::MAX-INDEX-CLAUSE-IS-BOUNDED-BY-MAX-INDEX-FORMULA))
  (21 1
      (:REWRITE SATLINK::EVAL-LIT-OF-LIT-NEGATE))
  (18 1 (:DEFINITION B-NOT$INLINE))
  (6 6 (:REWRITE MV-NTH-OF-CONS))
  (3 1 (:REWRITE ZP-WHEN-GT-0))
  (1 1 (:REWRITE ZP-WHEN-INTEGERP))
  (1 1 (:REWRITE ZP-OPEN)))
(SATLINK::FORMULA-TRUEP-REDEF
     (646 38 (:DEFINITION MEMBER-EQUAL))
     (612 84 (:REWRITE SUBSETP-CAR-MEMBER))
     (482 474 (:REWRITE DEFAULT-CAR))
     (256 92
          (:REWRITE NO-DUPLICATESP-EQUAL-NON-CONS))
     (220 110
          (:TYPE-PRESCRIPTION LRAT::TRUE-LISTP-LOOKUP-FORMULA-INDEX))
     (168 168 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (110 110
          (:TYPE-PRESCRIPTION LRAT::FORMULA-P))
     (108 84 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (108 84 (:REWRITE MEMBER-WHEN-ATOM))
     (92 92 (:REWRITE FN-CHECK-DEF-FORMALS))
     (84 84 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (84 84 (:REWRITE SUBSETP-TRANS2))
     (84 84 (:REWRITE SUBSETP-TRANS))
     (84 84 (:REWRITE SUBSETP-MEMBER . 4))
     (84 84 (:REWRITE SUBSETP-MEMBER . 3))
     (84 84 (:REWRITE SUBSETP-MEMBER . 2))
     (84 84 (:REWRITE SUBSETP-MEMBER . 1))
     (84 84 (:REWRITE INTERSECTP-MEMBER . 3))
     (84 84 (:REWRITE INTERSECTP-MEMBER . 2))
     (38 38 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (37 37 (:REWRITE LRAT::FORMULA-TRUEP-NECC)))
(SATLINK::FORMULA-TRUEP-OF-CONS (182 23 (:REWRITE SUBSETP-CAR-MEMBER))
                                (152 8 (:DEFINITION MEMBER-EQUAL))
                                (130 116 (:REWRITE DEFAULT-CDR))
                                (124 117 (:REWRITE DEFAULT-CAR))
                                (85 30
                                    (:REWRITE NO-DUPLICATESP-EQUAL-NON-CONS))
                                (46 46 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
                                (44 23 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
                                (44 23 (:REWRITE MEMBER-WHEN-ATOM))
                                (32 32 (:REWRITE LRAT::FORMULA-TRUEP-NECC))
                                (30 30 (:REWRITE FN-CHECK-DEF-FORMALS))
                                (23 23 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
                                (23 23 (:REWRITE SUBSETP-TRANS2))
                                (23 23 (:REWRITE SUBSETP-TRANS))
                                (23 23 (:REWRITE SUBSETP-MEMBER . 4))
                                (23 23 (:REWRITE SUBSETP-MEMBER . 3))
                                (23 23 (:REWRITE SUBSETP-MEMBER . 2))
                                (23 23 (:REWRITE SUBSETP-MEMBER . 1))
                                (23 23 (:REWRITE INTERSECTP-MEMBER . 3))
                                (23 23 (:REWRITE INTERSECTP-MEMBER . 2))
                                (16 16 (:REWRITE ALIST-KEYS-WHEN-ATOM)))
(SATLINK::FORMULA-TO-LRAT-FORMULA
     (5 5
        (:REWRITE SATLINK::LIT-LIST-LISTP-WHEN-NOT-CONSP))
     (2 2 (:REWRITE DEFAULT-CDR))
     (2 2 (:REWRITE DEFAULT-CAR))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1 (:REWRITE DEFAULT-+-2))
     (1 1 (:REWRITE DEFAULT-+-1)))
(SATLINK::FORMULA-P-OF-FORMULA-TO-LRAT-FORMULA
     (68 21 (:REWRITE ZP-WHEN-GT-0))
     (52 4 (:REWRITE POS-FIX-WHEN-POSP))
     (39 13
         (:REWRITE LRAT::CLAUSE-OR-ASSIGNMENT-P-CDR))
     (37 36 (:REWRITE DEFAULT-CAR))
     (34 33 (:REWRITE DEFAULT-CDR))
     (30 30 (:REWRITE DEFAULT-<-2))
     (30 30 (:REWRITE DEFAULT-<-1))
     (21 21 (:REWRITE ZP-WHEN-INTEGERP))
     (8 4 (:REWRITE DEFAULT-+-2))
     (4 4 (:TYPE-PRESCRIPTION ZP))
     (4 4 (:TYPE-PRESCRIPTION POSP))
     (4 4 (:REWRITE DEFAULT-+-1)))
(SATLINK::FORMULA-TO-LRAT-FORMULA-LOOKUP-KEY-TOO-SMALL
     (132 12 (:REWRITE POSP-REDEFINITION))
     (48 24 (:REWRITE ZP-WHEN-GT-0))
     (37 34 (:REWRITE DEFAULT-CAR))
     (26 19 (:REWRITE DEFAULT-<-2))
     (25 19 (:REWRITE DEFAULT-<-1))
     (24 24 (:REWRITE ZP-WHEN-INTEGERP))
     (24 24 (:REWRITE ZP-OPEN))
     (23 22 (:REWRITE DEFAULT-CDR))
     (16 8 (:REWRITE DEFAULT-+-2))
     (12 12 (:TYPE-PRESCRIPTION ZP))
     (12 12 (:TYPE-PRESCRIPTION POSP))
     (8 8 (:REWRITE DEFAULT-+-1))
     (8 2 (:REWRITE FOLD-CONSTS-IN-+))
     (6 6
        (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP)))
(SATLINK::NO-DUPLICATE-KEYS-OF-FORMULA-TO-LRAT-FORMULA
     (85 5 (:DEFINITION MEMBER-EQUAL))
     (70 10 (:REWRITE SUBSETP-CAR-MEMBER))
     (55 5 (:REWRITE POSP-REDEFINITION))
     (31 12
         (:REWRITE NO-DUPLICATESP-EQUAL-NON-CONS))
     (30 28 (:REWRITE DEFAULT-CDR))
     (24 6 (:REWRITE ALIST-KEYS-WHEN-ATOM))
     (22 21 (:REWRITE DEFAULT-CAR))
     (20 20 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (20 10 (:REWRITE ZP-WHEN-GT-0))
     (14 11 (:REWRITE MEMBER-WHEN-ATOM))
     (14 7 (:REWRITE DEFAULT-+-2))
     (12 12 (:REWRITE FN-CHECK-DEF-FORMALS))
     (11 11 (:REWRITE SUBSETP-MEMBER . 4))
     (11 11 (:REWRITE SUBSETP-MEMBER . 3))
     (11 11 (:REWRITE SUBSETP-MEMBER . 2))
     (11 11 (:REWRITE SUBSETP-MEMBER . 1))
     (11 11 (:REWRITE INTERSECTP-MEMBER . 3))
     (11 11 (:REWRITE INTERSECTP-MEMBER . 2))
     (10 10 (:REWRITE ZP-WHEN-INTEGERP))
     (10 10 (:REWRITE ZP-OPEN))
     (10 10 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
     (10 10 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
     (10 10 (:REWRITE SUBSETP-TRANS2))
     (10 10 (:REWRITE SUBSETP-TRANS))
     (8 2 (:REWRITE FOLD-CONSTS-IN-+))
     (7 7 (:REWRITE DEFAULT-+-1))
     (5 5 (:TYPE-PRESCRIPTION ZP))
     (5 5 (:TYPE-PRESCRIPTION POSP))
     (5 5 (:REWRITE DEFAULT-<-2))
     (5 5 (:REWRITE DEFAULT-<-1)))
(SATLINK::EVAL-OF-FORMULA-TO-LRAT-FORMULA
  (1496 44
        (:REWRITE SATLINK::MAX-INDEX-CLAUSE-IS-BOUNDED-BY-MAX-INDEX-FORMULA))
  (924 88 (:REWRITE SUBSETP-CAR-MEMBER))
  (814 44 (:DEFINITION MEMBER-EQUAL))
  (391 381 (:REWRITE DEFAULT-CDR))
  (308 44
       (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
  (305 300 (:REWRITE DEFAULT-CAR))
  (272 34 (:DEFINITION LRAT::EVALUATE-CLAUSE))
  (264 264 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
  (231 21 (:REWRITE POSP-REDEFINITION))
  (220 220 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
  (211 109 (:REWRITE DEFAULT-<-1))
  (159 109 (:REWRITE DEFAULT-<-2))
  (132 132 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
  (132 132 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
  (132 132 (:REWRITE SUBSETP-TRANS2))
  (132 132 (:REWRITE SUBSETP-TRANS))
  (131 35 (:REWRITE ALIST-KEYS-WHEN-ATOM))
  (108 108 (:REWRITE LRAT::FORMULA-TRUEP-NECC))
  (93 93 (:REWRITE SUBSETP-MEMBER . 2))
  (93 93 (:REWRITE SUBSETP-MEMBER . 1))
  (87 43 (:REWRITE ZP-WHEN-GT-0))
  (80 38 (:REWRITE NATP-WHEN-GTE-0))
  (78 39 (:REWRITE BFIX-WHEN-NOT-BIT->BOOL))
  (78 39 (:REWRITE BFIX-WHEN-BIT->BOOL))
  (74 18 (:REWRITE NFIX-WHEN-NOT-NATP))
  (70 35 (:REWRITE BFIX-WHEN-NOT-BITP))
  (68 68
      (:TYPE-PRESCRIPTION LRAT::EVALUATE-LITERAL))
  (62 31 (:REWRITE DEFAULT-+-2))
  (56 56
      (:REWRITE SATLINK::MAX-INDEX-CLAUSE-WHEN-ATOM))
  (49 49
      (:REWRITE SATLINK::EVAL-FORMULA-WHEN-SOME-FALSE-CLAUSE))
  (43 43 (:REWRITE ZP-WHEN-INTEGERP))
  (43 43 (:REWRITE ZP-OPEN))
  (40 10 (:REWRITE FOLD-CONSTS-IN-+))
  (38 38 (:REWRITE NATP-WHEN-INTEGERP))
  (34 34 (:DEFINITION LRAT::UNDEFP$INLINE))
  (31 31 (:REWRITE DEFAULT-+-1))
  (29 29
      (:REWRITE SATLINK::EVAL-CLAUSE-WHEN-SOME-TRUE-LITERAL))
  (29 29
      (:REWRITE SATLINK::EVAL-CLAUSE-WHEN-ATOM))
  (21 21 (:TYPE-PRESCRIPTION ZP))
  (21 21 (:TYPE-PRESCRIPTION POSP))
  (20 5 (:REWRITE MEMBER-WHEN-ATOM))
  (18 18
      (:LINEAR SATLINK::MAX-INDEX-CLAUSE-IS-BOUNDED-BY-MAX-INDEX-FORMULA))
  (10 5
      (:REWRITE NO-DUPLICATESP-EQUAL-NON-CONS))
  (7 7
     (:LINEAR SATLINK::INDEX-OF-LITERALS-IS-BOUNDED-BY-MAX-INDEX-CLAUSE))
  (5 5
     (:REWRITE-QUOTED-CONSTANT NFIX-UNDER-NAT-EQUIV))
  (5 5
     (:REWRITE-QUOTED-CONSTANT IFIX-UNDER-INT-EQUIV))
  (5 5
     (:REWRITE-QUOTED-CONSTANT BFIX-UNDER-BIT-EQUIV))
  (5 5 (:REWRITE SUBSETP-MEMBER . 4))
  (5 5 (:REWRITE SUBSETP-MEMBER . 3))
  (5 5 (:REWRITE INTERSECTP-MEMBER . 3))
  (5 5 (:REWRITE INTERSECTP-MEMBER . 2))
  (5 5 (:REWRITE FN-CHECK-DEF-FORMALS)))
