include ../../../../Makefile-generic

# BOOKS = base arith basic bits log logn logn2log float reps round add mult \
#         rtl rtlarr bvecp-raw-helpers bvecp-helpers simple-loop-helpers \
#         simplify-model-helpers util top rom-helpers clocks package-defs \
#         openers
 
# Dependencies:
-include Makefile-deps
