include ../../../../Makefile-generic

# These books are obtained from certify.lisp.  The file bis.lisp is a
# bisimulation book that was provided by Rob Sumners and is referenced in the
# paper.
BOOKS = total-order apply-total-order records sets ltl conjunction bisimilarity \
	circuit-bisim circuits cone-of-influence reductions impl-hack concrete-ltl 

-include Makefile-deps
