(RP::WEAK-RP-CL-HINTS-P)
(RP::RP-CL-HINTS-P)
(RP::CREATE-SIMPLE-META-RULES-ALIST-AUX
     (261 261 (:REWRITE DEFAULT-CAR))
     (236 59 (:REWRITE O-P-O-INFP-CAR))
     (173 146 (:REWRITE DEFAULT-CDR))
     (171 57 (:REWRITE SYMBOL-FIX-WHEN-SYMBOLP))
     (118 118 (:TYPE-PRESCRIPTION O-P))
     (59 59 (:REWRITE O-P-DEF-O-FINP-1))
     (57 57
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (57 57
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP)))
(RP::GET-META-RULES (47 22 (:REWRITE DEFAULT-+-2))
                    (31 22 (:REWRITE DEFAULT-+-1))
                    (30 2 (:DEFINITION LENGTH))
                    (30 1 (:REWRITE O<=-O-FINP-DEF))
                    (22 2 (:DEFINITION LEN))
                    (16 4 (:REWRITE COMMUTATIVITY-OF-+))
                    (16 4 (:DEFINITION INTEGER-ABS))
                    (14 8 (:REWRITE DEFAULT-CDR))
                    (7 7 (:REWRITE FOLD-CONSTS-IN-+))
                    (7 5 (:REWRITE DEFAULT-<-2))
                    (6 6
                       (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
                    (6 6 (:REWRITE DEFAULT-CAR))
                    (6 5 (:REWRITE DEFAULT-<-1))
                    (6 4 (:REWRITE STR::CONSP-OF-EXPLODE))
                    (4 4 (:REWRITE DEFAULT-UNARY-MINUS))
                    (4 4
                       (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-3))
                    (4 2
                       (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
                    (4 1 (:REWRITE O-P-O-INFP-CAR))
                    (4 1 (:REWRITE AC-<))
                    (3 3
                       (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-2))
                    (2 2 (:TYPE-PRESCRIPTION LEN))
                    (2 2
                       (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
                    (2 2 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
                    (2 2 (:REWRITE INTEGERP==>NUMERATOR-=-X))
                    (2 2 (:REWRITE INTEGERP==>DENOMINATOR-=-1))
                    (2 2
                       (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
                    (2 2
                       (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
                    (2 2 (:REWRITE DEFAULT-REALPART))
                    (2 2 (:REWRITE DEFAULT-NUMERATOR))
                    (2 2 (:REWRITE DEFAULT-IMAGPART))
                    (2 2 (:REWRITE DEFAULT-DENOMINATOR))
                    (2 2
                       (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-1))
                    (2 2
                       (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-0))
                    (2 2 (:DEFINITION NOT))
                    (2 1 (:REWRITE O-INFP-O-FINP-O<=))
                    (1 1 (:REWRITE |a < b & b < c  =>  a < c|))
                    (1 1 (:REWRITE O-P-DEF-O-FINP-1)))
(RP::CREATE-SIMPLE-META-RULES-ALIST
     (16 4 (:REWRITE O-P-O-INFP-CAR))
     (13 9 (:REWRITE DEFAULT-CAR))
     (10 2
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (9 1 (:DEFINITION ASSOC-EQUAL))
     (6 6 (:TYPE-PRESCRIPTION MAKE-FAST-ALIST))
     (6 6 (:REWRITE DEFAULT-CDR))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (4 4 (:REWRITE O-P-DEF-O-FINP-1))
     (2 2
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (2 1 (:DEFINITION NTH))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP)))
(RP::SIMPLE-META-RULE-ALISTP-OF-CREATE-SIMPLE-META-RULES-ALIST-AUX
     (77 69 (:REWRITE DEFAULT-CAR))
     (60 15 (:REWRITE O-P-O-INFP-CAR))
     (34 30 (:REWRITE DEFAULT-CDR))
     (34 18
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (30 30 (:TYPE-PRESCRIPTION O-P))
     (30 10 (:REWRITE SYMBOL-FIX-WHEN-SYMBOLP))
     (18 18
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (15 15 (:REWRITE O-P-DEF-O-FINP-1)))
(RP::SIMPLE-META-RULE-ALISTP-OF-CREATE-SIMPLE-META-RULES-ALIST)
(RP::RP-CLAUSE-PROCESSOR-AUX
     (17072 6 (:DEFINITION RP::VALID-RULESP))
     (16992 6 (:DEFINITION RP::VALID-RULEP))
     (16968 6 (:DEFINITION RP::VALID-RULEP-SK))
     (16962 6 (:DEFINITION RP::VALID-RULEP-SK-BODY))
     (11400 4
            (:REWRITE RP::VALID-RULESP-IMPLIES-RULE-LIST-SYNTAXP))
     (9624 12 (:DEFINITION RP::VALID-SC-NT))
     (7348 27 (:DEFINITION RP::RP-TERMP))
     (5888 2
           (:REWRITE RP::VALID-RULES-ALISTP-IMPLIES-RULES-ALISTP))
     (5738 2 (:DEFINITION RP::VALID-RULES-ALISTP))
     (5714 2 (:DEFINITION RP::RULE-LIST-SYNTAXP))
     (5565 27 (:DEFINITION RP::FALIST-CONSISTENT))
     (5138 173 (:DEFINITION RP::INCLUDE-FNC))
     (4326 27
           (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (4068 72
           (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT))
     (3906 3882 (:REWRITE DEFAULT-CDR))
     (3240 12
           (:REWRITE RP::CAR-OF-EX-FROM-RP-IS-NOT-RP))
     (3082 1627 (:REWRITE O-P-O-INFP-CAR))
     (2603 2575 (:REWRITE DEFAULT-CAR))
     (1776 12 (:DEFINITION RP::EVAL-AND-ALL-NT))
     (1668 6 (:REWRITE RP::RP-EVL-OF-RP-EQUAL2))
     (1668 6
           (:REWRITE RP::RP-EVL-OF-RP-EQUAL-LOOSE))
     (1188 72
           (:REWRITE RP::VALID-SC-NT-IS-VALID-SC))
     (1156 74 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (1008 74 (:DEFINITION RP::IS-SYNP$INLINE))
     (613 421 (:REWRITE O-P-DEF-O-FINP-1))
     (588 588
          (:TYPE-PRESCRIPTION RP::INCLUDE-FNC-SUBTERMS))
     (468 48
          (:DEFINITION RP::INCLUDE-FNC-SUBTERMS))
     (451 224 (:DEFINITION QUOTEP))
     (372 62
          (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (330 6 (:REWRITE RP::RP-EVL-OF-RP-EQUAL))
     (324 24
          (:REWRITE RP::EVAL-AND-ALL-NT-IS-EVAL-AND-ALL))
     (306 6 (:DEFINITION RP::RP-EQUAL))
     (299 122
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (252 24 (:DEFINITION RP::EX-FROM-RP))
     (246 74 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (240 12
          (:REWRITE RP::VALID-SC-NT-SUBTERMSOF-EX-FROM-RP))
     (232 106 (:REWRITE RP::IS-IF-RP-TERMP))
     (219 219
          (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (194 74
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (192 192 (:TYPE-PRESCRIPTION O-FINP))
     (180 180
          (:TYPE-PRESCRIPTION RP::VALID-SC-NT))
     (169 39 (:REWRITE RP::NOT-INCLUDE-RP))
     (159 159
          (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (144 24
          (:REWRITE RP::NOT-INCLUDE-EX-FROM-RP))
     (144 12
          (:REWRITE RP::VALID-SC-NT-SUBTERMS-VALID-SC-SUBTERMS))
     (144 12
          (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT-SUBTERMS))
     (144 12
          (:REWRITE RP::EVAL-AND-ALL-NT-OF-CONTEXT-FROM-RP))
     (144 2
          (:REWRITE RP::VALID-RULES-ALISTP-GET-RULES))
     (141 27
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (138 138 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (124 124
          (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (122 122
          (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (116 53 (:REWRITE RP::RP-TERMP-CADR))
     (116 53 (:REWRITE RP::RP-TERMP-CADDR))
     (116 53 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (98 74 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (98 74
         (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (98 74
         (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (98 74
         (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (98 74 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (96 24
         (:REWRITE RP::VALID-RULEP-IMPLIES-VALID-SC))
     (96 24
         (:REWRITE RP::QUOTEP-TERM-WITH-EX-FROM-RP))
     (74 74
         (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (72 72 (:TYPE-PRESCRIPTION RP::VALID-RULEP))
     (72 72
         (:TYPE-PRESCRIPTION RP::CONTEXT-FROM-RP))
     (60 60
         (:TYPE-PRESCRIPTION RP::EVAL-AND-ALL-NT))
     (60 27
         (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (51 51 (:TYPE-PRESCRIPTION QUOTEP))
     (46 2 (:DEFINITION FGETPROP))
     (30 30
         (:TYPE-PRESCRIPTION RP::VALID-RULESP))
     (27 3 (:DEFINITION ASSOC-EQUAL))
     (24 24
         (:TYPE-PRESCRIPTION RP::VALID-SC-NT-SUBTERMS))
     (24 12 (:REWRITE RP::VALID-SC-NT-CADDDR))
     (20 20
         (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
     (20 2 (:DEFINITION STRIP-CDRS))
     (20 2 (:DEFINITION STRIP-CARS))
     (18 18 (:TYPE-PRESCRIPTION RP::RP-EQUAL))
     (12 12
         (:TYPE-PRESCRIPTION RP::RP-EQUAL-SUBTERMS))
     (12 12
         (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (12 12 (:REWRITE RP::VALID-RULES-SUBSETP))
     (12 4
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (11 11
         (:TYPE-PRESCRIPTION RP::EX-FROM-SYNP))
     (10 10
         (:TYPE-PRESCRIPTION RP::VALID-RULES-ALISTP))
     (8 8
        (:REWRITE RP::REMOVE-WARNING-FROM-RULE-SYNTAXP))
     (6 6
        (:REWRITE RP::RP-EQUAL-SUBTERMS-REFLEXIVE))
     (6 6 (:REWRITE RP::RP-EQUAL-REFLEXIVE))
     (6 6 (:DEFINITION IFF))
     (6 3 (:DEFINITION NTH))
     (4 4 (:REWRITE FN-CHECK-DEF-FORMALS))
     (3 3 (:REWRITE NTH-WHEN-PREFIXP)))
(RP::CORRECTNESS-OF-RP-CLAUSE-PROCESSOR-AUX
     (629896 221 (:DEFINITION PSEUDO-TERMP))
     (401411 2893 (:DEFINITION RP::RP-TERMP))
     (325577 153
             (:DEFINITION RP::BETA-SEARCH-REDUCE))
     (295844 1187
             (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (286455 449 (:DEFINITION TRUE-LISTP))
     (286163 1397
             (:DEFINITION RP::FALIST-CONSISTENT))
     (267855 3877
             (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (249063 526
             (:REWRITE RP::RP-TERMP-IMPLIES-PSEUDO-TERMP))
     (241261 1149 (:DEFINITION RP::RP-TERM-LISTP))
     (222488 1385
             (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (219946 4340 (:DEFINITION QUOTEP))
     (209885 1034
             (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (208545 670 (:DEFINITION APPLY$-BADGEP))
     (196599 195927 (:REWRITE DEFAULT-CDR))
     (173096 1456 (:DEFINITION SUBSETP-EQUAL))
     (143976 10920 (:DEFINITION MEMBER-EQUAL))
     (111333 3877
             (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (94248 3640 (:REWRITE SUBSETP-REFLEXIVE-LEMMA))
     (93401 249
            (:REWRITE RP::RP-TERM-LIST-IMPLIES-PSEUDO-TERM-LISTP))
     (90440 5824
            (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (84472 7400 (:REWRITE RP::IS-IF-RP-TERMP))
     (73150 3593 (:REWRITE RP::RP-TERMP-CADR))
     (68644 20818 (:REWRITE O-P-O-INFP-CAR))
     (31000 31000 (:TYPE-PRESCRIPTION O-P))
     (21840 21840 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (19740 236 (:REWRITE RP::CDR-PSEUDO-TERMP))
     (18928 18928 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (17472 17472
            (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (16826 15500 (:REWRITE O-P-DEF-O-FINP-1))
     (16075 16075
            (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (11897 11897
            (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (11648 11648
            (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (10385 1401 (:DEFINITION LEN))
     (10192 10192
            (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (10136 2435
            (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (9996 2923 (:REWRITE RP::RP-TERMP-CADDR))
     (9996 2923 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (9061 663 (:DEFINITION LENGTH))
     (8058 8058 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (6916 728 (:DEFINITION NATP))
     (4690 4690 (:TYPE-PRESCRIPTION LEN))
     (4420 884 (:REWRITE RP::RP-TERMP-CADDDR))
     (4113 4113 (:TYPE-PRESCRIPTION QUOTEP))
     (3885 3885 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (3640 3640
           (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (3536 221 (:DEFINITION SYMBOL-LISTP))
     (2802 1401 (:REWRITE DEFAULT-+-2))
     (2435 2435
           (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (2184 1092
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (2184 364 (:DEFINITION ALL-NILS))
     (2142 153 (:DEFINITION LAMBDA-EXPR-P))
     (2068 670 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (2062 1031
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (1820 1820 (:TYPE-PRESCRIPTION ALL-NILS))
     (1563 267
           (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (1401 1401
           (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (1401 1401 (:REWRITE DEFAULT-+-1))
     (1326 1326 (:TYPE-PRESCRIPTION O-FINP))
     (1187 1187
           (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (1092 1092
           (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (848 848
          (:TYPE-PRESCRIPTION RP::EX-FROM-SYNP))
     (730 226 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (728 728 (:LINEAR LEN-WHEN-PREFIXP))
     (728 364
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (728 364
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (663 663
          (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (663 442 (:REWRITE STR::CONSP-OF-EXPLODE))
     (606 606 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (539 77 (:DEFINITION ALISTP))
     (526 526
          (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
     (521 521
          (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (447 239
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (442 442 (:REWRITE FN-CHECK-DEF-FORMALS))
     (442 221
          (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
     (438 74 (:DEFINITION RP::INCLUDE-FNC))
     (364 364 (:REWRITE DEFAULT-<-2))
     (364 364 (:REWRITE DEFAULT-<-1))
     (364 364 (:LINEAR BOUNDS-POSITION-EQUAL-AC))
     (364 364 (:LINEAR BOUNDS-POSITION-EQUAL))
     (291 239 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (291 239
          (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (291 239
          (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (291 239 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (278 226
          (:REWRITE RP::RP-EVL-OF-FNCALL-ARGS))
     (221 221 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
     (221 221
          (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (101 101
          (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
     (86 71 (:REWRITE RP::NOT-INCLUDE-RP))
     (68 68 (:REWRITE RP::RP-EVL-DISJOIN-ATOM))
     (13 13
         (:REWRITE RP::RP-EVL-META-EXTRACT-FN-CHECK-DEF))
     (10 5 (:DEFINITION NTH))
     (7 7 (:TYPE-PRESCRIPTION RP::RULES-ALISTP))
     (7 7
        (:TYPE-PRESCRIPTION RP::RP-STATE-NEW-RUN))
     (7 7 (:TYPE-PRESCRIPTION RP::RP-RW-AUX))
     (7 7 (:TYPE-PRESCRIPTION MAKE-FAST-ALIST))
     (7 7 (:TYPE-PRESCRIPTION RP::GET-RULES-FN))
     (7 7
        (:TYPE-PRESCRIPTION RP::GET-ENABLED-RULES-FROM-TABLE))
     (7 7
        (:TYPE-PRESCRIPTION RP::CREATE-SIMPLE-META-RULES-ALIST))
     (5 5 (:REWRITE NTH-WHEN-PREFIXP))
     (1 1
        (:REWRITE RP::RP-EVL-CONJOIN-CLAUSES-ATOM)))
(RP::RP-REWRITER)
(RP::RP-REWRITER)
(RP::CORRECTNESS-OF-RP-CLAUSE-PROCESSOR-LEMMA
     (1142 1 (:DEFINITION PSEUDO-TERM-LISTP))
     (870 2
          (:REWRITE RP::RP-TERM-LIST-IMPLIES-PSEUDO-TERM-LISTP))
     (584 2 (:DEFINITION RP::RP-TERM-LISTP))
     (562 5
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (553 6 (:DEFINITION QUOTEP))
     (551 2 (:DEFINITION RP::RP-TERMP))
     (537 2
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (535 1 (:DEFINITION APPLY$-BADGEP))
     (430 4 (:DEFINITION SUBSETP-EQUAL))
     (414 2 (:DEFINITION RP::FALIST-CONSISTENT))
     (373 373 (:REWRITE DEFAULT-CDR))
     (350 30 (:DEFINITION MEMBER-EQUAL))
     (322 2
          (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (285 5
          (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (283 1
          (:REWRITE RP::RP-TERMP-IMPLIES-PSEUDO-TERMP))
     (239 10 (:REWRITE SUBSETP-REFLEXIVE-LEMMA))
     (220 16
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (194 194 (:REWRITE DEFAULT-CAR))
     (92 26 (:REWRITE O-P-O-INFP-CAR))
     (60 60 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (57 57 (:TYPE-PRESCRIPTION RP::RP-TERMP))
     (52 52 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (48 48
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (44 44 (:TYPE-PRESCRIPTION O-P))
     (32 32
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (28 28 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (28 2 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (24 2 (:DEFINITION RP::IS-SYNP$INLINE))
     (22 22 (:REWRITE O-P-DEF-O-FINP-1))
     (20 9 (:REWRITE RP::IS-IF-RP-TERMP))
     (19 2 (:DEFINITION NATP))
     (18 18
         (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (16 16
         (:TYPE-PRESCRIPTION RP::RP-TERM-LISTP))
     (16 16
         (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (14 14 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (13 4
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (12 5 (:REWRITE RP::RP-TERMP-CADR))
     (12 2
         (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (11 11 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (10 10
         (:TYPE-PRESCRIPTION RP::IS-RP$INLINE))
     (10 10
         (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (10 1 (:DEFINITION TRUE-LISTP))
     (8 4 (:REWRITE RP::RP-TERMP-CADDR))
     (8 4 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (8 4
        (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (7 7 (:TYPE-PRESCRIPTION LEN))
     (7 1 (:DEFINITION LEN))
     (7 1 (:DEFINITION ALISTP))
     (6 6 (:TYPE-PRESCRIPTION QUOTEP))
     (6 3
        (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (6 1 (:DEFINITION DISJOIN))
     (6 1 (:DEFINITION ALL-NILS))
     (5 5 (:TYPE-PRESCRIPTION ALL-NILS))
     (5 1 (:REWRITE RP::CDR-PSEUDO-TERMP))
     (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (4 4
        (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (4 4
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (4 2
        (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (4 1 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (3 3
        (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (3 1 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (2 2
        (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (2 2
        (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (2 2
        (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
     (2 2 (:LINEAR LEN-WHEN-PREFIXP))
     (2 1 (:REWRITE DEFAULT-+-2))
     (2 1
        (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (2 1
        (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (1 1 (:TYPE-PRESCRIPTION PSEUDO-TERMP))
     (1 1 (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
     (1 1 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (1 1
        (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (1 1
        (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (1 1
        (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (1 1 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (1 1 (:REWRITE RP::RP-EVL-DISJOIN-ATOM))
     (1 1 (:REWRITE RP::RP-EVL-CONJOIN-ATOM))
     (1 1 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1 (:REWRITE DEFAULT-+-1))
     (1 1 (:LINEAR BOUNDS-POSITION-EQUAL-AC))
     (1 1 (:LINEAR BOUNDS-POSITION-EQUAL))
     (1 1 (:DEFINITION DISJOIN2)))
(RP::CORRECTNESS-OF-RP-CLAUSE-PROCESSOR
     (2284 2 (:DEFINITION PSEUDO-TERM-LISTP))
     (1740 4
           (:REWRITE RP::RP-TERM-LIST-IMPLIES-PSEUDO-TERM-LISTP))
     (1168 4 (:DEFINITION RP::RP-TERM-LISTP))
     (1124 10
           (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (1106 12 (:DEFINITION QUOTEP))
     (1102 4 (:DEFINITION RP::RP-TERMP))
     (1074 4
           (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (1070 2 (:DEFINITION APPLY$-BADGEP))
     (860 8 (:DEFINITION SUBSETP-EQUAL))
     (828 4 (:DEFINITION RP::FALIST-CONSISTENT))
     (748 748 (:REWRITE DEFAULT-CDR))
     (700 60 (:DEFINITION MEMBER-EQUAL))
     (644 4
          (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (570 10
          (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (566 2
          (:REWRITE RP::RP-TERMP-IMPLIES-PSEUDO-TERMP))
     (478 20 (:REWRITE SUBSETP-REFLEXIVE-LEMMA))
     (440 32
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (379 379 (:REWRITE DEFAULT-CAR))
     (184 52 (:REWRITE O-P-O-INFP-CAR))
     (120 120 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (114 114 (:TYPE-PRESCRIPTION RP::RP-TERMP))
     (104 104 (:REWRITE SUBSETP-IMPLIES-MEMBER))
     (96 96
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (88 88 (:TYPE-PRESCRIPTION O-P))
     (72 5 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (64 64
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (61 5 (:DEFINITION RP::IS-SYNP$INLINE))
     (56 56 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (44 44 (:REWRITE O-P-DEF-O-FINP-1))
     (40 18 (:REWRITE RP::IS-IF-RP-TERMP))
     (38 4 (:DEFINITION NATP))
     (36 36
         (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (32 32
         (:TYPE-PRESCRIPTION RP::RP-TERM-LISTP))
     (32 32
         (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (30 5
         (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (29 11
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (28 28 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (24 10 (:REWRITE RP::RP-TERMP-CADR))
     (23 23
         (:TYPE-PRESCRIPTION RP::IS-RP$INLINE))
     (22 22 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (20 20
         (:REWRITE TRANSITIVITY-OF-SUBSETP-EQUAL))
     (20 2 (:DEFINITION TRUE-LISTP))
     (16 8 (:REWRITE RP::RP-TERMP-CADDR))
     (16 8 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (16 8
         (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (15 5 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (14 14 (:TYPE-PRESCRIPTION LEN))
     (14 2 (:DEFINITION LEN))
     (14 2 (:DEFINITION ALISTP))
     (12 12 (:TYPE-PRESCRIPTION QUOTEP))
     (12 6
         (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (12 2 (:DEFINITION ALL-NILS))
     (11 11
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (10 10
         (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (10 10 (:TYPE-PRESCRIPTION ALL-NILS))
     (10 2 (:REWRITE RP::CDR-PSEUDO-TERMP))
     (8 8 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (8 4
        (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (8 2 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (7 7
        (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (6 6
        (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (5 5 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (5 5
        (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (5 5
        (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (5 5
        (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (5 5 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (4 4
        (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (4 4
        (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
     (4 4 (:LINEAR LEN-WHEN-PREFIXP))
     (4 2 (:REWRITE DEFAULT-+-2))
     (4 2
        (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (4 2
        (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (2 2 (:TYPE-PRESCRIPTION PSEUDO-TERMP))
     (2 2 (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
     (2 2 (:REWRITE RP::RP-EVL-DISJOIN-ATOM))
     (2 2 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (2 2 (:REWRITE DEFAULT-<-2))
     (2 2 (:REWRITE DEFAULT-<-1))
     (2 2 (:REWRITE DEFAULT-+-1))
     (2 2 (:LINEAR BOUNDS-POSITION-EQUAL-AC))
     (2 2 (:LINEAR BOUNDS-POSITION-EQUAL))
     (1 1
        (:REWRITE RP::RP-EVL-CONJOIN-CLAUSES-ATOM)))
