(RP::CUSTOM-REWRITE-FROM-FORMULA)
(RP::IF-TO-AND-LIST (174 15 (:DEFINITION APPLY$-BADGEP))
                    (144 69 (:REWRITE DEFAULT-+-2))
                    (138 4 (:REWRITE O<=-O-FINP-DEF))
                    (120 102 (:REWRITE DEFAULT-CDR))
                    (99 9
                        (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
                    (93 69 (:REWRITE DEFAULT-+-1))
                    (90 6 (:DEFINITION NATP))
                    (90 6 (:DEFINITION LENGTH))
                    (82 9
                        (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
                    (66 6 (:DEFINITION LEN))
                    (48 48 (:REWRITE DEFAULT-CAR))
                    (48 48
                        (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-3))
                    (48 15 (:DEFINITION WEAK-APPLY$-BADGE-P))
                    (48 12 (:DEFINITION INTEGER-ABS))
                    (45 45 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
                    (33 25 (:REWRITE DEFAULT-<-2))
                    (33 9
                        (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
                    (32 32
                        (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-2))
                    (32 25 (:REWRITE DEFAULT-<-1))
                    (31 9
                        (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
                    (20 20
                        (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-0))
                    (18 18
                        (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
                    (18 12 (:REWRITE STR::CONSP-OF-EXPLODE))
                    (18 3 (:REWRITE O-FIRST-EXPT-<))
                    (16 16
                        (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-1))
                    (13 4 (:REWRITE AC-<))
                    (12 12
                        (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
                    (12 12 (:REWRITE DEFAULT-UNARY-MINUS))
                    (12 6 (:REWRITE O-FIRST-EXPT-DEF-O-FINP))
                    (12 6
                        (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
                    (12 3 (:REWRITE O-P-O-INFP-CAR))
                    (8 4 (:REWRITE O-INFP-O-FINP-O<=))
                    (6 6 (:TYPE-PRESCRIPTION LEN))
                    (6 6
                       (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
                    (6 6 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
                    (6 6 (:REWRITE INTEGERP==>NUMERATOR-=-X))
                    (6 6 (:REWRITE INTEGERP==>DENOMINATOR-=-1))
                    (6 6
                       (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
                    (6 6 (:REWRITE DEFAULT-REALPART))
                    (6 6 (:REWRITE DEFAULT-NUMERATOR))
                    (6 6 (:REWRITE DEFAULT-IMAGPART))
                    (6 6 (:REWRITE DEFAULT-DENOMINATOR))
                    (6 3 (:REWRITE O-FIRST-COEFF-<))
                    (4 4 (:REWRITE |a < b & b < c  =>  a < c|))
                    (3 3 (:REWRITE O-P-DEF-O-FINP-1)))
(RP::SC-RULE-P)
(RP::NOT-TO-EQUAL-NIL (1 1
                         (:TYPE-PRESCRIPTION RP::NOT-TO-EQUAL-NIL)))
(RP::NOT-TO-EQUAL-NIL-LIST (1 1
                              (:TYPE-PRESCRIPTION RP::NOT-TO-EQUAL-NIL)))
(RP::MAKE-RULE-BETTER-AUX1)
(RP::MAKE-FORMULA-BETTER)
(RP::INSERT-IFF-TO-FORCE
     (1771 851 (:REWRITE DEFAULT-+-2))
     (1290 86 (:DEFINITION LENGTH))
     (1170 851 (:REWRITE DEFAULT-+-1))
     (1091 35 (:REWRITE O<=-O-FINP-DEF))
     (946 86 (:DEFINITION LEN))
     (835 577 (:REWRITE DEFAULT-CDR))
     (688 172 (:DEFINITION INTEGER-ABS))
     (410 29 (:DEFINITION APPLY$-BADGEP))
     (299 228 (:REWRITE DEFAULT-<-2))
     (272 228 (:REWRITE DEFAULT-<-1))
     (258 258
          (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
     (258 172 (:REWRITE STR::CONSP-OF-EXPLODE))
     (257 27
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (241 241 (:REWRITE DEFAULT-CAR))
     (230 230
          (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-3))
     (222 21
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (172 172 (:REWRITE DEFAULT-UNARY-MINUS))
     (172 86
          (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
     (162 12 (:DEFINITION NATP))
     (160 160
          (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-2))
     (140 35 (:REWRITE O-P-O-INFP-CAR))
     (132 35 (:REWRITE AC-<))
     (104 104
          (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-0))
     (101 101 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (98 98
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (90 90
         (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-1))
     (86 86 (:TYPE-PRESCRIPTION LEN))
     (86 86
         (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
     (86 86 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (86 86 (:REWRITE INTEGERP==>NUMERATOR-=-X))
     (86 86
         (:REWRITE INTEGERP==>DENOMINATOR-=-1))
     (86 86
         (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
     (86 86 (:REWRITE DEFAULT-REALPART))
     (86 86 (:REWRITE DEFAULT-NUMERATOR))
     (86 86 (:REWRITE DEFAULT-IMAGPART))
     (86 86 (:REWRITE DEFAULT-DENOMINATOR))
     (82 29 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (70 35 (:REWRITE O-INFP-O-FINP-O<=))
     (64 18
         (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (54 9 (:REWRITE O-FIRST-EXPT-<))
     (36 18 (:REWRITE O-FIRST-EXPT-DEF-O-FINP))
     (36 18
         (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (35 35
         (:REWRITE |a < b & b < c  =>  a < c|))
     (35 35 (:REWRITE O-P-DEF-O-FINP-1))
     (18 9 (:REWRITE O-FIRST-COEFF-<))
     (1 1 (:REWRITE FN-CHECK-DEF-NOT-QUOTE)))
(RP::FORMULAS-TO-RULES)
(RP::CUSTOM-REWRITE-WITH-META-EXTRACT)
(RP::ATTACH-SC-LIST-TO-RHS (6 6 (:TYPE-PRESCRIPTION RP::ATTACH-SC)))
(RP::ATTACH-SC-TO-RULE
     (7034 37 (:DEFINITION RP::RP-TERMP))
     (6245 1 (:DEFINITION SUBSETP-EQUAL))
     (5236 2 (:REWRITE PLAIN-UQI-TRUE-LIST-LISTP))
     (5048 18
           (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (4897 6 (:DEFINITION TRUE-LISTP))
     (4854 23 (:DEFINITION RP::FALIST-CONSISTENT))
     (4399 2 (:DEFINITION MEMBER-EQUAL))
     (4285 12 (:DEFINITION ALWAYS$))
     (4163 41
           (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (3720 23
           (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (3609 4
           (:REWRITE TRUE-LIST-LISTP-IMPLIES-ALWAYS$-TRUE-LISTP))
     (3597 4 (:DEFINITION TRUE-LIST-LISTP))
     (2918 2752 (:REWRITE DEFAULT-CDR))
     (1979 184 (:REWRITE RP::IS-IF-RP-TERMP))
     (1952 1878 (:REWRITE DEFAULT-CAR))
     (1905 12 (:REWRITE APPLY$-SYMBOL-ARITY-1))
     (1845 12 (:REWRITE APPLY$-PRIMITIVE))
     (1821 12 (:META APPLY$-PRIM-META-FN-CORRECT))
     (1477 88 (:REWRITE RP::RP-TERMP-CADR))
     (1090 303 (:REWRITE O-P-O-INFP-CAR))
     (970 12 (:DEFINITION RP::RP-TERM-LISTP))
     (833 11 (:DEFINITION APPLY$-BADGEP))
     (816 41
          (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (708 61 (:DEFINITION QUOTEP))
     (550 21
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (520 66 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (496 66 (:REWRITE RP::RP-TERMP-CADDR))
     (447 2 (:REWRITE PLAIN-UQI-INTEGER-LISTP))
     (279 4
          (:REWRITE INTEGER-LISTP-IMPLIES-ALWAYS$-INTEGERP))
     (273 257 (:REWRITE O-P-DEF-O-FINP-1))
     (268 268
          (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (268 27
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (267 4 (:DEFINITION INTEGER-LISTP))
     (253 37
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (194 18 (:DEFINITION NATP))
     (159 159
          (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (156 2 (:REWRITE PLAIN-UQI-SYMBOL-LISTP))
     (143 143 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (128 2
          (:REWRITE PLAIN-UQI-ACL2-NUMBER-LISTP))
     (125 10
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (124 20 (:DEFINITION RP::INCLUDE-FNC))
     (110 2 (:REWRITE PLAIN-UQI-RATIONAL-LISTP))
     (92 30 (:REWRITE RP::RP-TERMP-CADDDR))
     (91 91 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (84 2
         (:REWRITE PLAIN-UQI-RATIONAL-LIST-LISTP))
     (82 4
         (:REWRITE SYMBOL-LISTP-IMPLIES-ALWAYS$-SYMBOLP))
     (72 11 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (66 4 (:DEFINITION SYMBOL-LISTP))
     (63 63 (:TYPE-PRESCRIPTION LEN))
     (63 9 (:DEFINITION LEN))
     (63 6 (:DEFINITION RATIONAL-LISTP))
     (61 4
         (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ALWAYS$-ACL2-NUMBERP))
     (61 2
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (60 60 (:TYPE-PRESCRIPTION ALWAYS$))
     (54 9 (:DEFINITION ALL-NILS))
     (51 24
         (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (50 4
         (:REWRITE RATIONAL-LISTP-IMPLIES-ALWAYS$-RATIONALP))
     (49 4 (:DEFINITION ACL2-NUMBER-LISTP))
     (48 24 (:REWRITE APPLY$-PRIMP-BADGE))
     (45 45 (:TYPE-PRESCRIPTION ALL-NILS))
     (42 2 (:DEFINITION LOOP$-AS))
     (41 41 (:TYPE-PRESCRIPTION QUOTEP))
     (37 37
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (36 36 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (36 36 (:TYPE-PRESCRIPTION APPLY$-PRIMP))
     (30 30 (:TYPE-PRESCRIPTION RATIONAL-LISTP))
     (29 29
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (24 24 (:LINEAR LEN-WHEN-PREFIXP))
     (21 9
         (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (20 20 (:TYPE-PRESCRIPTION TRUE-LIST-LISTP))
     (20 20 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
     (20 20 (:TYPE-PRESCRIPTION INTEGER-LISTP))
     (20 20
         (:TYPE-PRESCRIPTION ACL2-NUMBER-LISTP))
     (18 18
         (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (18 9 (:REWRITE DEFAULT-+-2))
     (18 6
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (16 6 (:REWRITE RP::NOT-INCLUDE-RP))
     (14 14
         (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
     (13 2 (:DEFINITION EMPTY-LOOP$-AS-TUPLEP))
     (13 2 (:DEFINITION CDR-LOOP$-AS-TUPLE))
     (13 2 (:DEFINITION CAR-LOOP$-AS-TUPLE))
     (12 12 (:REWRITE DEFAULT-<-2))
     (12 12 (:REWRITE DEFAULT-<-1))
     (12 12 (:REWRITE APPLY$-CONSP-ARITY-1))
     (12 12
         (:REWRITE ALWAYS$-P-LST-IMPLIES-P-ELEMENT))
     (9 9 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (9 9 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (9 9 (:REWRITE DEFAULT-+-1))
     (8 8 (:REWRITE FN-CHECK-DEF-FORMALS))
     (6 6 (:REWRITE CDR-CONS))
     (6 6 (:REWRITE CAR-CONS))
     (6 6
        (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ACL2-NUMBERP))
     (4 4 (:TYPE-PRESCRIPTION LOOP$-AS))
     (2 2 (:REWRITE PLAIN-UQI-ALWAYS$))
     (2 2
        (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (2 2
        (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2)))
(RP::UPDATE-RULE-WITH-SC-AUX)
(RP::UPDATE-RULE-WITH-SC-AUX
     (6873 3 (:DEFINITION SUBSETP-EQUAL))
     (4605 36 (:DEFINITION ALWAYS$))
     (3999 6 (:DEFINITION MEMBER-EQUAL))
     (3756 6 (:REWRITE PLAIN-UQI-TRUE-LIST-LISTP))
     (3174 54
           (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (2790 18 (:DEFINITION TRUE-LISTP))
     (2772 36 (:DEFINITION RP::RP-TERM-LISTP))
     (2499 33 (:DEFINITION APPLY$-BADGEP))
     (2469 12
           (:REWRITE TRUE-LIST-LISTP-IMPLIES-ALWAYS$-TRUE-LISTP))
     (2433 12 (:DEFINITION TRUE-LIST-LISTP))
     (2211 36 (:REWRITE APPLY$-SYMBOL-ARITY-1))
     (2031 36 (:REWRITE APPLY$-PRIMITIVE))
     (1959 36 (:META APPLY$-PRIM-META-FN-CORRECT))
     (1902 54
           (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (1650 63
           (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (1359 6 (:REWRITE PLAIN-UQI-INTEGER-LISTP))
     (1062 1062
           (:TYPE-PRESCRIPTION RP::IF-TO-AND-LIST))
     (990 15
          (:DEFINITION RP::ATTACH-SC-LIST-TO-RHS))
     (918 831 (:REWRITE DEFAULT-CAR))
     (837 12
          (:REWRITE INTEGER-LISTP-IMPLIES-ALWAYS$-INTEGERP))
     (804 81
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (801 12 (:DEFINITION INTEGER-LISTP))
     (792 171 (:REWRITE O-P-O-INFP-CAR))
     (582 54 (:DEFINITION NATP))
     (486 6 (:REWRITE PLAIN-UQI-SYMBOL-LISTP))
     (426 54
          (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (402 6
          (:REWRITE PLAIN-UQI-ACL2-NUMBER-LISTP))
     (375 30
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (348 6 (:REWRITE PLAIN-UQI-RATIONAL-LISTP))
     (324 60
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (315 15 (:DEFINITION RP::ATTACH-SC))
     (279 171 (:REWRITE O-P-DEF-O-FINP-1))
     (273 273 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (270 66 (:REWRITE RP::RP-TERMP-CADR))
     (270 6
          (:REWRITE PLAIN-UQI-RATIONAL-LIST-LISTP))
     (255 78 (:REWRITE RP::IS-IF-RP-TERMP))
     (246 12
          (:REWRITE SYMBOL-LISTP-IMPLIES-ALWAYS$-SYMBOLP))
     (216 33 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (189 189 (:TYPE-PRESCRIPTION LEN))
     (189 27 (:DEFINITION LEN))
     (189 18 (:DEFINITION RATIONAL-LISTP))
     (186 186
          (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (183 12
          (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ALWAYS$-ACL2-NUMBERP))
     (183 6
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (180 180 (:TYPE-PRESCRIPTION ALWAYS$))
     (162 27 (:DEFINITION ALL-NILS))
     (153 72
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (150 12
          (:REWRITE RATIONAL-LISTP-IMPLIES-ALWAYS$-RATIONALP))
     (147 12 (:DEFINITION ACL2-NUMBER-LISTP))
     (144 72 (:REWRITE APPLY$-PRIMP-BADGE))
     (135 135 (:TYPE-PRESCRIPTION ALL-NILS))
     (126 6 (:DEFINITION LOOP$-AS))
     (120 15 (:REWRITE RP::NOT-INCLUDE-RP))
     (109 109 (:REWRITE FN-CHECK-DEF-FORMALS))
     (108 108 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (108 108 (:TYPE-PRESCRIPTION APPLY$-PRIMP))
     (99 99 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (87 87
         (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (72 72 (:TYPE-PRESCRIPTION O-FINP))
     (72 72 (:LINEAR LEN-WHEN-PREFIXP))
     (63 27
         (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (60 60
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (54 54 (:TYPE-PRESCRIPTION QUOTEP))
     (54 54
         (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (54 27 (:REWRITE DEFAULT-+-2))
     (54 18
         (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (48 48 (:REWRITE CAR-CONS))
     (48 16
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (42 42
         (:TYPE-PRESCRIPTION RP::ATTACH-SC-TO-RULE))
     (42 42
         (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
     (39 6 (:DEFINITION EMPTY-LOOP$-AS-TUPLEP))
     (39 6 (:DEFINITION CDR-LOOP$-AS-TUPLE))
     (39 6 (:DEFINITION CAR-LOOP$-AS-TUPLE))
     (36 36 (:REWRITE DEFAULT-<-2))
     (36 36 (:REWRITE DEFAULT-<-1))
     (36 36 (:REWRITE APPLY$-CONSP-ARITY-1))
     (36 36
         (:REWRITE ALWAYS$-P-LST-IMPLIES-P-ELEMENT))
     (30 12 (:REWRITE RP::RP-TERMP-CADDR))
     (30 12 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (27 27 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (27 27 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (27 27 (:REWRITE DEFAULT-+-1))
     (18 18 (:REWRITE CDR-CONS))
     (18 18
         (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ACL2-NUMBERP))
     (15 15
         (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (12 12 (:TYPE-PRESCRIPTION LOOP$-AS))
     (6 6 (:REWRITE PLAIN-UQI-ALWAYS$))
     (6 6
        (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (6 6
        (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2)))
(RP::SYMBOL-SYMBOL-ALISTP)
(RP::UPDATE-RULE-WITH-SC)
(RP::UPDATE-RULE-WITH-SC (5304 5304
                               (:TYPE-PRESCRIPTION RP::EX-FROM-SYNP))
                         (1314 657 (:DEFINITION RP::INCLUDE-FNC))
                         (1184 296 (:REWRITE O-P-O-INFP-CAR))
                         (970 214
                              (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
                         (661 661 (:TYPE-PRESCRIPTION QUOTEP))
                         (378 18
                              (:REWRITE SYMBOL-LISTP-CDR-ASSOC-EQUAL))
                         (330 15 (:DEFINITION SYMBOL-LIST-LISTP))
                         (296 296 (:REWRITE O-P-DEF-O-FINP-1))
                         (220 220 (:REWRITE FN-CHECK-DEF-FORMALS))
                         (214 214
                              (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
                         (162 2
                              (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
                         (160 1 (:DEFINITION APPLY$-BADGEP))
                         (91 1 (:DEFINITION SUBSETP-EQUAL))
                         (80 14 (:DEFINITION MEMBER-EQUAL))
                         (75 75
                             (:TYPE-PRESCRIPTION SYMBOL-LIST-LISTP))
                         (42 7
                             (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
                         (31 31 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
                         (21 21
                             (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
                         (16 2 (:DEFINITION NATP))
                         (14 14
                             (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
                         (14 2
                             (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
                         (14 1 (:DEFINITION TRUE-LISTP))
                         (9 9 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
                         (8 4
                            (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
                         (7 7 (:TYPE-PRESCRIPTION LEN))
                         (6 2
                            (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
                         (6 1 (:DEFINITION LEN))
                         (5 5 (:TYPE-PRESCRIPTION ALL-NILS))
                         (4 4 (:TYPE-PRESCRIPTION TRUE-LISTP))
                         (4 4 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
                         (4 4 (:LINEAR LEN-WHEN-PREFIXP))
                         (4 1 (:DEFINITION ALL-NILS))
                         (2 2
                            (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
                         (2 2
                            (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
                         (2 2
                            (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
                         (2 2 (:REWRITE DEFAULT-<-2))
                         (2 2 (:REWRITE DEFAULT-<-1))
                         (2 1 (:REWRITE DEFAULT-+-2))
                         (2 1
                            (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
                         (2 1
                            (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
                         (2 1
                            (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
                         (1 1 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
                         (1 1 (:REWRITE DEFAULT-+-1))
                         (1 1 (:DEFINITION WEAK-APPLY$-BADGE-P)))
(RP::UPDATE-RULES-WITH-SC
     (104983 24
             (:REWRITE RP::VALID-RULESP-IMPLIES-RULE-LIST-SYNTAXP))
     (104908 25 (:DEFINITION RP::VALID-RULESP))
     (94373 25 (:DEFINITION RP::VALID-RULEP))
     (44418 350
            (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (44398 190 (:DEFINITION APPLY$-BADGEP))
     (33889 33217 (:REWRITE DEFAULT-CDR))
     (32405 5 (:DEFINITION RP::VALID-RULEP-SK))
     (32400 5 (:DEFINITION RP::VALID-RULEP-SK-BODY))
     (31136 195
            (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (27708 42 (:DEFINITION RP::VALID-SC))
     (25344 116
            (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (24326 23894 (:REWRITE DEFAULT-CAR))
     (24073 10
            (:REWRITE RP::VALID-SC-NT-IS-VALID-SC))
     (20916 58 (:DEFINITION TRUE-LISTP))
     (18551 481
            (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (16886 2412 (:REWRITE RP::IS-IF-RP-TERMP))
     (15450 132 (:REWRITE RP::VALID-SC-CADDR))
     (13668 58 (:DEFINITION SUBSETP-EQUAL))
     (12914 812 (:DEFINITION MEMBER-EQUAL))
     (12624 186 (:REWRITE RP::VALID-SC-CADR))
     (12554 3875 (:REWRITE O-P-O-INFP-CAR))
     (10590 1017 (:REWRITE RP::RP-TERMP-CADR))
     (8184 406
           (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (8082 90 (:REWRITE RP::VALID-SC-CADDDR))
     (6610 116 (:DEFINITION RP::RP-TERM-LISTP))
     (5816 640 (:REWRITE RP::RP-TERMP-CADDDR))
     (5796 42 (:DEFINITION RP::EVAL-AND-ALL))
     (4440 6 (:REWRITE RP::RP-EVL-OF-RP-EQUAL2))
     (4180 481
           (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (4170 6 (:DEFINITION RP::RP-EQUAL2))
     (3990 300
           (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC))
     (3942 186 (:DEFINITION RP::EX-FROM-RP))
     (3630 24 (:DEFINITION RP::RP-EQUAL))
     (3468 18
           (:REWRITE RP::RP-EQUAL-IMPLIES-RP-EQUAL2))
     (3451 3451
           (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (3200 787 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (3048 84 (:DEFINITION RP::RP-TRANS))
     (3005 2837 (:REWRITE O-P-DEF-O-FINP-1))
     (2554 497
           (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (2416 779 (:REWRITE RP::RP-TERMP-CADDR))
     (1914 133 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (1798 1798 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (1720 139 (:DEFINITION RP::IS-SYNP$INLINE))
     (1560 1560
           (:TYPE-PRESCRIPTION RP::INCLUDE-FNC-SUBTERMS))
     (1478 1478 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (1296 84
           (:REWRITE RP::RP-TRANS-IS-TERM-WHEN-LIST-IS-ABSENT))
     (1296 72 (:DEFINITION RP::TRANS-LIST))
     (1218 1218
           (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (1162 116 (:DEFINITION NATP))
     (1154 1154 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (1004 1004
           (:TYPE-PRESCRIPTION RP::RP-TERM-LISTP))
     (924 924 (:TYPE-PRESCRIPTION RP::VALID-SC))
     (824 304
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (812 812
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (726 121
          (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (714 42 (:REWRITE RP::VALID-SC-EX-FROM-RP))
     (648 648
          (:TYPE-PRESCRIPTION RP::RP-TRANS-LST))
     (638 22
          (:DEFINITION RP::SYMBOL-SYMBOL-ALISTP))
     (600 84 (:DEFINITION RP::IS-FALIST))
     (545 545 (:TYPE-PRESCRIPTION QUOTEP))
     (504 42
          (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-LST))
     (497 497
          (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (496 190 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (464 232
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (414 48
          (:REWRITE RP::NOT-INCLUDE-EX-FROM-RP))
     (406 406 (:TYPE-PRESCRIPTION LEN))
     (406 58 (:DEFINITION LEN))
     (388 133 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (378 42
          (:DEFINITION RP::INCLUDE-FNC-SUBTERMS))
     (348 174
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (348 58 (:DEFINITION ALL-NILS))
     (324 42
          (:REWRITE RP::CAR-OF-EX-FROM-RP-IS-NOT-RP))
     (290 290 (:TYPE-PRESCRIPTION ALL-NILS))
     (288 288 (:REWRITE RP::CONSP-RP-TRANS-LST))
     (288 12
          (:REWRITE RP::EXTRACT-FROM-SYNP-TO-EX-FROM-RP))
     (284 284
          (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (276 12 (:DEFINITION RP::EX-FROM-SYNP))
     (246 6 (:REWRITE RP::RP-EVL-OF-RP-EQUAL))
     (232 232 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (232 232 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (220 22 (:DEFINITION SYMBOL-LISTP))
     (216 48
          (:REWRITE RP::QUOTEP-TERM-WITH-EX-FROM-RP))
     (210 210
          (:TYPE-PRESCRIPTION RP::EVAL-AND-ALL))
     (210 210
          (:TYPE-PRESCRIPTION RP::CONTEXT-FROM-RP))
     (206 133 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (197 133
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (192 12 (:REWRITE RP::NOT-INCLUDE-SYNP))
     (176 82
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (174 174
          (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (168 168 (:TYPE-PRESCRIPTION O-FINP))
     (158 133 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (158 133
          (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (158 133 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (156 42
          (:REWRITE RP::VALID-SC-OF-EX-FROM-RP))
     (146 133 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (133 133
          (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (132 12
          (:DEFINITION RP::SHOULD-TERM-BE-IN-CONS$INLINE))
     (126 6
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-LOOSE))
     (116 116
          (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (116 116 (:LINEAR LEN-WHEN-PREFIXP))
     (116 58 (:REWRITE DEFAULT-+-2))
     (108 6 (:DEFINITION RP::RP-EQUAL-LOOSE))
     (96 6
         (:REWRITE RP::RP-EQUAL-SUBTERMS-IMPLIES-RP-EQUAL2-SUBTERMS))
     (84 84
         (:TYPE-PRESCRIPTION RP::VALID-SC-SUBTERMS))
     (78 13 (:REWRITE RP::EX-FROM-RP-LEMMA1))
     (72 12
         (:DEFINITION RP::IS-QUOTED-PAIR$INLINE))
     (72 6 (:DEFINITION RP::RP-EQUAL-SUBTERMS))
     (60 60 (:TYPE-PRESCRIPTION RP::RP-EQUAL))
     (60 60 (:REWRITE CAR-CONS))
     (58 58 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (58 58 (:REWRITE DEFAULT-<-2))
     (58 58 (:REWRITE DEFAULT-<-1))
     (58 58 (:REWRITE DEFAULT-+-1))
     (54 54
         (:TYPE-PRESCRIPTION RP::RP-EQUAL-SUBTERMS))
     (48 48 (:TYPE-PRESCRIPTION RP::RP-EQUAL2))
     (48 6 (:DEFINITION RP::IS-CONS$INLINE))
     (44 44 (:REWRITE FN-CHECK-DEF-FORMALS))
     (42 42
         (:TYPE-PRESCRIPTION RP::VALID-RULESP))
     (42 42
         (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (42 6
         (:DEFINITION RP::PUT-TERM-IN-CONS$INLINE))
     (30 30 (:REWRITE RP::VALID-RULES-SUBSETP))
     (30 30 (:REWRITE RP::RP-EQUAL-REFLEXIVE))
     (30 30 (:REWRITE CDR-CONS))
     (24 24
         (:REWRITE RP::SHOULD-TERM-BE-IN-CONS-LEMMA2))
     (24 24
         (:REWRITE RP::RP-EQUAL-SUBTERMS-REFLEXIVE))
     (22 22 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
     (20 5 (:DEFINITION RP::RP-IFF-FLAG$INLINE))
     (18 18
         (:TYPE-PRESCRIPTION RP::RP-EQUAL-LOOSE))
     (18 18 (:REWRITE RP::RP-EQUAL2-REFLEXIVE))
     (12 12
         (:TYPE-PRESCRIPTION RP::RP-EQUAL2-SUBTERMS))
     (12 12
         (:TYPE-PRESCRIPTION RP::RP-EQUAL-LOOSE-SUBTERMS))
     (6 6
        (:REWRITE RP::RP-EQUAL2-SUBTERMS-REFLEXIVE))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (5 5 (:DEFINITION IFF))
     (1 1
        (:TYPE-PRESCRIPTION RP::UPDATE-RULE-WITH-SC)))
(RP::ADD-RULE-TO-ALIST
     (140 35 (:REWRITE O-P-O-INFP-CAR))
     (72 72 (:REWRITE DEFAULT-CDR))
     (70 54 (:REWRITE DEFAULT-CAR))
     (37 10
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (36 4 (:DEFINITION ASSOC-EQUAL))
     (35 35 (:REWRITE O-P-DEF-O-FINP-1))
     (12 3 (:DEFINITION RP::RP-TERMP))
     (10 10
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (3 3
        (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS)))
(RP::CHECK-IF-DEF-RULE-SHOULD-BE-SAVED)
(RP::UPDATE-RULE-WITH-SC-AUX-RETURNS-RULE-LIST-SYNTAXP
     (189910 72 (:REWRITE PLAIN-UQI-TRUE-LIST-LISTP))
     (182740 650
             (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (177302 217 (:DEFINITION TRUE-LISTP))
     (161136 86 (:DEFINITION MEMBER-EQUAL))
     (157576 432 (:DEFINITION ALWAYS$))
     (149229 1189
             (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (130596 144
             (:REWRITE TRUE-LIST-LISTP-IMPLIES-ALWAYS$-TRUE-LISTP))
     (130164 144 (:DEFINITION TRUE-LIST-LISTP))
     (71480 432 (:REWRITE APPLY$-SYMBOL-ARITY-1))
     (69320 432 (:REWRITE APPLY$-PRIMITIVE))
     (68456 432 (:META APPLY$-PRIM-META-FN-CORRECT))
     (42291 2970 (:REWRITE RP::IS-IF-RP-TERMP))
     (31361 418 (:DEFINITION APPLY$-BADGEP))
     (29430 1822 (:REWRITE RP::RP-TERMP-CADR))
     (29359 7687 (:REWRITE O-P-O-INFP-CAR))
     (21217 779
            (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (16674 72 (:REWRITE PLAIN-UQI-INTEGER-LISTP))
     (15750 248
            (:DEFINITION RP::ATTACH-SC-LIST-TO-RHS))
     (13941 1151 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (10156 144
            (:REWRITE INTEGER-LISTP-IMPLIES-ALWAYS$-INTEGERP))
     (10070 975
            (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (9724 144 (:DEFINITION INTEGER-LISTP))
     (8338 6667 (:REWRITE O-P-DEF-O-FINP-1))
     (7675 650 (:DEFINITION NATP))
     (6038 72 (:REWRITE PLAIN-UQI-SYMBOL-LISTP))
     (5305 5305
           (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (5030 72
           (:REWRITE PLAIN-UQI-ACL2-NUMBER-LISTP))
     (4646 361
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (4590 248 (:DEFINITION RP::ATTACH-SC))
     (4382 72 (:REWRITE PLAIN-UQI-RATIONAL-LISTP))
     (3781 3781 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (3446 72
           (:REWRITE PLAIN-UQI-RATIONAL-LIST-LISTP))
     (3308 3308 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (2952 144
           (:REWRITE SYMBOL-LISTP-IMPLIES-ALWAYS$-SYMBOLP))
     (2640 418 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (2419 325 (:DEFINITION LEN))
     (2376 144 (:DEFINITION SYMBOL-LISTP))
     (2310 79
           (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (2275 2275 (:TYPE-PRESCRIPTION LEN))
     (2268 216 (:DEFINITION RATIONAL-LISTP))
     (2196 144
           (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ALWAYS$-ACL2-NUMBERP))
     (2180 868
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (2160 2160 (:TYPE-PRESCRIPTION ALWAYS$))
     (1950 325 (:DEFINITION ALL-NILS))
     (1800 144
           (:REWRITE RATIONAL-LISTP-IMPLIES-ALWAYS$-RATIONALP))
     (1764 144 (:DEFINITION ACL2-NUMBER-LISTP))
     (1728 864 (:REWRITE APPLY$-PRIMP-BADGE))
     (1625 1625 (:TYPE-PRESCRIPTION ALL-NILS))
     (1512 72 (:DEFINITION LOOP$-AS))
     (1314 1314 (:REWRITE CDR-CONS))
     (1300 1300 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1296 1296 (:TYPE-PRESCRIPTION APPLY$-PRIMP))
     (1162 1162 (:REWRITE CAR-CONS))
     (1080 1080
           (:TYPE-PRESCRIPTION RATIONAL-LISTP))
     (1047 1047
           (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (937 937
          (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (866 866 (:LINEAR LEN-WHEN-PREFIXP))
     (854 325
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (808 808 (:TYPE-PRESCRIPTION O-FINP))
     (720 720
          (:TYPE-PRESCRIPTION TRUE-LIST-LISTP))
     (720 720 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
     (720 720 (:TYPE-PRESCRIPTION INTEGER-LISTP))
     (720 720
          (:TYPE-PRESCRIPTION ACL2-NUMBER-LISTP))
     (650 650
          (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (650 325 (:REWRITE DEFAULT-+-2))
     (648 216
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (504 504
          (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
     (468 72 (:DEFINITION EMPTY-LOOP$-AS-TUPLEP))
     (468 72 (:DEFINITION CDR-LOOP$-AS-TUPLE))
     (468 72 (:DEFINITION CAR-LOOP$-AS-TUPLE))
     (433 433 (:REWRITE DEFAULT-<-2))
     (433 433 (:REWRITE DEFAULT-<-1))
     (432 432 (:REWRITE APPLY$-CONSP-ARITY-1))
     (432 432
          (:REWRITE ALWAYS$-P-LST-IMPLIES-P-ELEMENT))
     (325 325
          (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (325 325 (:REWRITE DEFAULT-+-1))
     (288 288 (:REWRITE FN-CHECK-DEF-FORMALS))
     (248 248
          (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (216 216
          (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ACL2-NUMBERP))
     (144 144 (:TYPE-PRESCRIPTION LOOP$-AS))
     (93 93
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (86 86
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (72 72 (:REWRITE PLAIN-UQI-ALWAYS$))
     (6 6
        (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE)))
(RP::UPDATE-RULES-WITH-SC-RETURNS-RULE-LIST-SYNTAXP
     (283612 1288 (:DEFINITION RP::RP-TERMP))
     (252316 35
             (:DEFINITION RP::UPDATE-RULE-WITH-SC-AUX))
     (242691 35 (:DEFINITION RP::ATTACH-SC-TO-RULE))
     (223651 35 (:DEFINITION SUBSETP-EQUAL))
     (193129 1148
             (:DEFINITION RP::FALIST-CONSISTENT))
     (190762 29 (:DEFINITION RP::VALID-RULEP))
     (190675 29 (:DEFINITION RP::VALID-RULEP-SK))
     (190646 29
             (:DEFINITION RP::VALID-RULEP-SK-BODY))
     (185856 70 (:REWRITE PLAIN-UQI-TRUE-LIST-LISTP))
     (178850 630
             (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (173565 210 (:DEFINITION TRUE-LISTP))
     (157693 70 (:DEFINITION MEMBER-EQUAL))
     (154246 420 (:DEFINITION ALWAYS$))
     (154136 64 (:DEFINITION RP::VALID-SC-NT))
     (145341 1778
             (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (144023 956
             (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (133076 1077 (:DEFINITION RP::INCLUDE-FNC))
     (132239 118317 (:REWRITE DEFAULT-CDR))
     (127785 140
             (:REWRITE TRUE-LIST-LISTP-IMPLIES-ALWAYS$-TRUE-LISTP))
     (127365 140 (:DEFINITION TRUE-LIST-LISTP))
     (125158 320
             (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT))
     (120614 64
             (:REWRITE RP::CAR-OF-EX-FROM-RP-IS-NOT-RP))
     (88098 6220 (:REWRITE RP::IS-IF-RP-TERMP))
     (82745 78929 (:REWRITE DEFAULT-CAR))
     (70928 27696 (:REWRITE O-P-O-INFP-CAR))
     (70036 420 (:REWRITE APPLY$-SYMBOL-ARITY-1))
     (67936 420 (:REWRITE APPLY$-PRIMITIVE))
     (67096 420 (:META APPLY$-PRIM-META-FN-CORRECT))
     (41976 3310 (:REWRITE RP::RP-TERMP-CADR))
     (36050 420 (:DEFINITION RP::RP-TERM-LISTP))
     (34756 2316 (:REWRITE RP::RP-TERMP-CADDR))
     (34756 2316 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (32260 594 (:REWRITE RP::RP-TERMP-CADDDR))
     (31360 385 (:DEFINITION APPLY$-BADGEP))
     (30835 1778
            (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (30229 3193 (:DEFINITION QUOTEP))
     (29015 29015
            (:TYPE-PRESCRIPTION RP::IF-TO-AND-LIST))
     (26040 26040 (:TYPE-PRESCRIPTION O-P))
     (21455 735
            (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (17192 13020 (:REWRITE O-P-DEF-O-FINP-1))
     (16421 70 (:REWRITE PLAIN-UQI-INTEGER-LISTP))
     (13860 210
            (:DEFINITION RP::ATTACH-SC-LIST-TO-RHS))
     (11124 2588
            (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (10290 945
            (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (10010 140
            (:REWRITE INTEGER-LISTP-IMPLIES-ALWAYS$-INTEGERP))
     (9882 9882
           (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (9590 140 (:DEFINITION INTEGER-LISTP))
     (9472 64 (:DEFINITION RP::EVAL-AND-ALL-NT))
     (9078 32 (:REWRITE RP::RP-EVL-OF-RP-EQUAL2))
     (9078 32
           (:REWRITE RP::RP-EVL-OF-RP-EQUAL-LOOSE))
     (8260 630 (:DEFINITION NATP))
     (7571 7571
           (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (6900 387 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (6322 320
           (:REWRITE RP::VALID-SC-NT-IS-VALID-SC))
     (6117 387 (:DEFINITION RP::IS-SYNP$INLINE))
     (5886 70 (:REWRITE PLAIN-UQI-SYMBOL-LISTP))
     (5751 5751 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (4906 70
           (:REWRITE PLAIN-UQI-ACL2-NUMBER-LISTP))
     (4690 350
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (4536 4536
           (:TYPE-PRESCRIPTION RP::RP-TERM-LISTP))
     (4410 210 (:DEFINITION RP::ATTACH-SC))
     (4276 70 (:REWRITE PLAIN-UQI-RATIONAL-LISTP))
     (3670 3670
           (:TYPE-PRESCRIPTION RP::IS-RP$INLINE))
     (3573 3573
           (:TYPE-PRESCRIPTION RP::INCLUDE-FNC))
     (3366 70
           (:REWRITE PLAIN-UQI-RATIONAL-LIST-LISTP))
     (3324 384 (:DEFINITION RP::RP-RHS$INLINE))
     (3290 3290 (:TYPE-PRESCRIPTION O-FINP))
     (3185 3185 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (3008 3008
           (:TYPE-PRESCRIPTION RP::INCLUDE-FNC-SUBTERMS))
     (2876 2876
           (:TYPE-PRESCRIPTION RP::UPDATE-RULE-WITH-SC-AUX))
     (2870 140
           (:REWRITE SYMBOL-LISTP-IMPLIES-ALWAYS$-SYMBOLP))
     (2687 437 (:REWRITE RP::NOT-INCLUDE-RP))
     (2588 2588
           (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (2520 840
           (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (2520 385 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (2520 315 (:DEFINITION LEN))
     (2496 256
           (:DEFINITION RP::INCLUDE-FNC-SUBTERMS))
     (2376 32 (:REWRITE RP::RP-EVL-OF-RP-EQUAL))
     (2310 140 (:DEFINITION SYMBOL-LISTP))
     (2205 2205 (:TYPE-PRESCRIPTION LEN))
     (2205 210 (:DEFINITION RATIONAL-LISTP))
     (2204 32 (:DEFINITION RP::RP-EQUAL))
     (2138 151 (:DEFINITION RP::RP-HYP$INLINE))
     (2135 140
           (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ALWAYS$-ACL2-NUMBERP))
     (2135 70
           (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (2100 2100 (:TYPE-PRESCRIPTION ALWAYS$))
     (1938 323
           (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (1916 128 (:DEFINITION RP::EX-FROM-RP))
     (1906 1906 (:TYPE-PRESCRIPTION QUOTEP))
     (1890 315 (:DEFINITION ALL-NILS))
     (1877 387
           (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (1750 140
           (:REWRITE RATIONAL-LISTP-IMPLIES-ALWAYS$-RATIONALP))
     (1728 128
           (:REWRITE RP::EVAL-AND-ALL-NT-IS-EVAL-AND-ALL))
     (1715 140 (:DEFINITION ACL2-NUMBER-LISTP))
     (1680 840 (:REWRITE APPLY$-PRIMP-BADGE))
     (1575 1575 (:TYPE-PRESCRIPTION ALL-NILS))
     (1504 387 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (1470 70 (:DEFINITION LOOP$-AS))
     (1260 1260 (:TYPE-PRESCRIPTION TRUE-LISTP))
     (1260 1260 (:TYPE-PRESCRIPTION APPLY$-PRIMP))
     (1050 1050
           (:TYPE-PRESCRIPTION RATIONAL-LISTP))
     (1015 1015
           (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (945 315
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (840 840 (:LINEAR LEN-WHEN-PREFIXP))
     (800 128
          (:REWRITE RP::NOT-INCLUDE-EX-FROM-RP))
     (800 64
          (:REWRITE RP::EVAL-AND-ALL-NT-OF-CONTEXT-FROM-RP))
     (780 780
          (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (768 768
          (:TYPE-PRESCRIPTION RP::VALID-SC-NT))
     (768 64
          (:REWRITE RP::VALID-SC-NT-SUBTERMS-VALID-SC-SUBTERMS))
     (768 64
          (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT-SUBTERMS))
     (700 700 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
     (700 700 (:TYPE-PRESCRIPTION INTEGER-LISTP))
     (700 700
          (:TYPE-PRESCRIPTION ACL2-NUMBER-LISTP))
     (688 387 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (688 387
          (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (688 387
          (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (688 387
          (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (688 387 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (665 665 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (630 630
          (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (630 315 (:REWRITE DEFAULT-+-2))
     (630 210
          (:REWRITE RATIONALP-IMPLIES-ACL2-NUMBERP))
     (630 70 (:DEFINITION ASSOC-EQUAL))
     (512 128
          (:REWRITE RP::QUOTEP-TERM-WITH-EX-FROM-RP))
     (490 490
          (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
     (455 70 (:DEFINITION EMPTY-LOOP$-AS-TUPLEP))
     (455 70 (:DEFINITION CDR-LOOP$-AS-TUPLE))
     (455 70 (:DEFINITION CAR-LOOP$-AS-TUPLE))
     (420 420 (:REWRITE DEFAULT-<-2))
     (420 420 (:REWRITE DEFAULT-<-1))
     (420 420 (:REWRITE APPLY$-CONSP-ARITY-1))
     (420 420
          (:REWRITE ALWAYS$-P-LST-IMPLIES-P-ELEMENT))
     (414 29 (:DEFINITION RP::RP-IFF-FLAG$INLINE))
     (405 405
          (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (402 67 (:REWRITE RP::EX-FROM-RP-LEMMA1))
     (384 384
          (:TYPE-PRESCRIPTION RP::CONTEXT-FROM-RP))
     (345 58 (:DEFINITION RP::RP-LHS$INLINE))
     (320 320
          (:TYPE-PRESCRIPTION RP::EVAL-AND-ALL-NT))
     (315 315 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (315 315
          (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (315 315 (:REWRITE DEFAULT-+-1))
     (280 280 (:REWRITE FN-CHECK-DEF-FORMALS))
     (274 274
          (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (210 210
          (:REWRITE ACL2-NUMBER-LISTP-IMPLIES-ACL2-NUMBERP))
     (140 140 (:TYPE-PRESCRIPTION LOOP$-AS))
     (128 128
          (:TYPE-PRESCRIPTION RP::VALID-SC-NT-SUBTERMS))
     (96 96 (:TYPE-PRESCRIPTION RP::RP-EQUAL))
     (76 32 (:REWRITE RP::RP-EQUAL-REFLEXIVE))
     (70 70 (:REWRITE PLAIN-UQI-ALWAYS$))
     (70 70
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (70 70
         (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (64 64
         (:TYPE-PRESCRIPTION RP::RP-EQUAL-SUBTERMS))
     (59 59 (:REWRITE RP::VALID-RULES-SUBSETP))
     (32 32
         (:REWRITE RP::RP-EQUAL-SUBTERMS-REFLEXIVE))
     (29 29 (:DEFINITION IFF)))
(RP::TRY-TO-ADD-RULE-FNC (11 11 (:REWRITE DEFAULT-CDR))
                         (8 8 (:REWRITE DEFAULT-CAR))
                         (8 2 (:REWRITE O-P-O-INFP-CAR))
                         (2 2 (:REWRITE O-P-DEF-O-FINP-1)))
(RP::GET-RULE-LIST
     (192756 48
             (:REWRITE RP::VALID-RULESP-IMPLIES-RULE-LIST-SYNTAXP))
     (192624 28 (:DEFINITION RP::VALID-RULESP))
     (192264 28 (:DEFINITION RP::VALID-RULEP))
     (192180 28 (:DEFINITION RP::VALID-RULEP-SK))
     (192152 28
             (:DEFINITION RP::VALID-RULEP-SK-BODY))
     (168576 24 (:DEFINITION RP::RULE-LIST-SYNTAXP))
     (144692 56 (:DEFINITION RP::VALID-SC-NT))
     (128256 601 (:DEFINITION RP::RP-TERMP))
     (125372 728 (:DEFINITION RP::INCLUDE-FNC))
     (118596 280
             (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT))
     (114116 56
             (:REWRITE RP::CAR-OF-EX-FROM-RP-IS-NOT-RP))
     (81416 600 (:DEFINITION RP::FALIST-CONSISTENT))
     (59568 432
            (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (48048 45972 (:REWRITE DEFAULT-CDR))
     (46164 3256 (:REWRITE RP::IS-IF-RP-TERMP))
     (35314 17078 (:REWRITE O-P-O-INFP-CAR))
     (34064 504 (:REWRITE RP::RP-TERMP-CADDDR))
     (32212 31772 (:REWRITE DEFAULT-CAR))
     (18324 1040 (:REWRITE RP::RP-TERMP-CADDR))
     (18324 1040 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (16784 1712 (:REWRITE RP::RP-TERMP-CADR))
     (8288 56 (:DEFINITION RP::EVAL-AND-ALL-NT))
     (8232 28 (:REWRITE RP::RP-EVL-OF-RP-EQUAL2))
     (8232 28
           (:REWRITE RP::RP-EVL-OF-RP-EQUAL-LOOSE))
     (7460 5388 (:REWRITE O-P-DEF-O-FINP-1))
     (6272 280
           (:REWRITE RP::VALID-SC-NT-IS-VALID-SC))
     (5936 336 (:REWRITE RP::EX-FROM-SYNP-LEMMA1))
     (5264 336 (:DEFINITION RP::IS-SYNP$INLINE))
     (5010 1589
           (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (4633 4633
           (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (3888 1440 (:DEFINITION QUOTEP))
     (3120 3120
           (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (3000 600
           (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (2912 2912
           (:TYPE-PRESCRIPTION RP::INCLUDE-FNC))
     (2632 2632
           (:TYPE-PRESCRIPTION RP::INCLUDE-FNC-SUBTERMS))
     (2268 28 (:REWRITE RP::RP-EVL-OF-RP-EQUAL))
     (2264 2264
           (:TYPE-PRESCRIPTION RP::IS-RP$INLINE))
     (2184 224
           (:DEFINITION RP::INCLUDE-FNC-SUBTERMS))
     (2072 2072 (:TYPE-PRESCRIPTION O-FINP))
     (2044 28 (:DEFINITION RP::RP-EQUAL))
     (2016 2016 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (1792 112 (:DEFINITION RP::EX-FROM-RP))
     (1680 280
           (:REWRITE RP::EVL-OF-EXTRACT-FROM-RP-2))
     (1589 1589
           (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (1568 336
           (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-SUBTERMS-CALL))
     (1568 112 (:DEFINITION RP::RP-HYP$INLINE))
     (1512 112
           (:REWRITE RP::EVAL-AND-ALL-NT-IS-EVAL-AND-ALL))
     (1344 168 (:DEFINITION RP::RP-RHS$INLINE))
     (1232 336 (:REWRITE RP::RP-EVL-OF-VARIABLE))
     (1200 1200
           (:TYPE-PRESCRIPTION RP::RP-TERM-LISTP))
     (1200 600
           (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (1008 168 (:REWRITE RP::NOT-INCLUDE-RP))
     (784 112
          (:REWRITE RP::NOT-INCLUDE-EX-FROM-RP))
     (784 56
          (:REWRITE RP::EVAL-AND-ALL-NT-OF-CONTEXT-FROM-RP))
     (712 712 (:TYPE-PRESCRIPTION QUOTEP))
     (672 672
          (:TYPE-PRESCRIPTION RP::VALID-SC-NT))
     (672 672
          (:TYPE-PRESCRIPTION RP::IS-RP-LOOSE$INLINE))
     (672 56
          (:REWRITE RP::VALID-SC-NT-SUBTERMS-VALID-SC-SUBTERMS))
     (672 56
          (:REWRITE RP::NOT-INCLUDE-RP-MEANS-VALID-SC-NT-SUBTERMS))
     (560 336 (:REWRITE RP::RP-EVL-OF-ZP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-UNARY-/-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-UNARY---CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-TYPESPEC-CHECK-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-SYNP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-SYMBOLP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-SYMBOL-PACKAGE-NAME-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-SYMBOL-NAME-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-STRINGP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-SUBTERMS-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CNT-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-RP-EQUAL-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-RP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-RETURN-LAST-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-REALPART-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-RATIONALP-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-QUOTE))
     (560 336
          (:REWRITE RP::RP-EVL-OF-NUMERATOR-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-NOT-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-NATP-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-LAMBDA))
     (560 336
          (:REWRITE RP::RP-EVL-OF-INTERN-IN-PACKAGE-OF-SYMBOL-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-INTEGERP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-IMPLIES-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-IMAGPART-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-IFF-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-IF-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-HIDE-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-FORCE-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-FALIST-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-EQUAL-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-DENOMINATOR-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-CONSP-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-CONS-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-COMPLEX-RATIONALP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-COERCE-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-CODE-CHAR-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-CHARACTERP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-CHAR-CODE-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-CDR-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-CAR-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-BITP-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-BINARY-+-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-BINARY-*-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-BAD-ATOM<=-CALL))
     (560 336
          (:REWRITE RP::RP-EVL-OF-ACL2-NUMBERP-CALL))
     (560 336 (:REWRITE RP::RP-EVL-OF-<-CALL))
     (448 112
          (:REWRITE RP::QUOTEP-TERM-WITH-EX-FROM-RP))
     (392 28 (:DEFINITION RP::RP-IFF-FLAG$INLINE))
     (336 336
          (:TYPE-PRESCRIPTION RP::IS-SYNP$INLINE))
     (336 336
          (:TYPE-PRESCRIPTION RP::CONTEXT-FROM-RP))
     (336 56 (:REWRITE RP::EX-FROM-RP-LEMMA1))
     (336 56 (:DEFINITION RP::RP-LHS$INLINE))
     (280 280
          (:TYPE-PRESCRIPTION RP::EVAL-AND-ALL-NT))
     (240 24 (:DEFINITION SYMBOL-LISTP))
     (140 140
          (:TYPE-PRESCRIPTION RP::VALID-RULESP))
     (140 28 (:REWRITE RP::RP-EQUAL-REFLEXIVE))
     (112 112
          (:TYPE-PRESCRIPTION RP::VALID-SC-NT-SUBTERMS))
     (108 108
          (:TYPE-PRESCRIPTION RP::RULE-SYNTAXP-FN))
     (108 12 (:DEFINITION ASSOC-EQUAL))
     (84 84 (:TYPE-PRESCRIPTION RP::RP-EQUAL))
     (56 56
         (:TYPE-PRESCRIPTION RP::RP-EQUAL-SUBTERMS))
     (56 56
         (:TYPE-PRESCRIPTION RP::IS-IF$INLINE))
     (56 56 (:REWRITE RP::VALID-RULES-SUBSETP))
     (48 48 (:REWRITE FN-CHECK-DEF-FORMALS))
     (30 10
         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (28 28
         (:REWRITE RP::RP-EQUAL-SUBTERMS-REFLEXIVE))
     (28 28 (:DEFINITION IFF))
     (3 3 (:TYPE-PRESCRIPTION TRUE-LISTP)))
(RP::TO-FAST-ALIST (47 22 (:REWRITE DEFAULT-+-2))
                   (31 22 (:REWRITE DEFAULT-+-1))
                   (30 2 (:DEFINITION LENGTH))
                   (30 1 (:REWRITE O<=-O-FINP-DEF))
                   (22 2 (:DEFINITION LEN))
                   (16 4 (:REWRITE COMMUTATIVITY-OF-+))
                   (16 4 (:DEFINITION INTEGER-ABS))
                   (14 8 (:REWRITE DEFAULT-CDR))
                   (7 7 (:REWRITE FOLD-CONSTS-IN-+))
                   (7 5 (:REWRITE DEFAULT-<-2))
                   (6 6
                      (:TYPE-PRESCRIPTION STR::TRUE-LISTP-OF-EXPLODE))
                   (6 6 (:REWRITE DEFAULT-CAR))
                   (6 5 (:REWRITE DEFAULT-<-1))
                   (6 4 (:REWRITE STR::CONSP-OF-EXPLODE))
                   (4 4 (:REWRITE DEFAULT-UNARY-MINUS))
                   (4 4
                      (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-3))
                   (4 2
                      (:REWRITE STR::COERCE-TO-LIST-REMOVAL))
                   (4 1 (:REWRITE O-P-O-INFP-CAR))
                   (4 1 (:REWRITE AC-<))
                   (3 3
                      (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-2))
                   (2 2 (:TYPE-PRESCRIPTION LEN))
                   (2 2
                      (:REWRITE RATIONAL-LISTP-IMPLIES-RATIONALP))
                   (2 2 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
                   (2 2 (:REWRITE INTEGERP==>NUMERATOR-=-X))
                   (2 2 (:REWRITE INTEGERP==>DENOMINATOR-=-1))
                   (2 2
                      (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
                   (2 2
                      (:REWRITE STR::EXPLODE-WHEN-NOT-STRINGP))
                   (2 2 (:REWRITE DEFAULT-REALPART))
                   (2 2 (:REWRITE DEFAULT-NUMERATOR))
                   (2 2 (:REWRITE DEFAULT-IMAGPART))
                   (2 2 (:REWRITE DEFAULT-DENOMINATOR))
                   (2 2
                      (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-1))
                   (2 2
                      (:LINEAR MEMBER-EQUAL-ACL2-COUNT-SMALLER-0))
                   (2 2 (:DEFINITION NOT))
                   (2 1 (:REWRITE O-INFP-O-FINP-O<=))
                   (1 1
                      (:TYPE-PRESCRIPTION RP::TO-FAST-ALIST))
                   (1 1 (:REWRITE |a < b & b < c  =>  a < c|))
                   (1 1 (:REWRITE O-P-DEF-O-FINP-1)))
(RP::RULE-LIST-TO-ALIST)
(RP::RULE-LIST-TO-ALIST-RETURNS-ALIST
     (3032 694 (:REWRITE O-P-O-INFP-CAR))
     (1405 137 (:DEFINITION ASSOC-EQUAL))
     (950 694 (:REWRITE O-P-DEF-O-FINP-1))
     (391 199
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (199 199
          (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (192 192 (:TYPE-PRESCRIPTION O-FINP))
     (152 38 (:DEFINITION RP::RP-TERMP))
     (8 8
        (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS)))
(RP::RULE-LIST-TO-ALIST (74 18 (:REWRITE O-P-O-INFP-CAR))
                        (42 1 (:DEFINITION RP::RULE-LIST-TO-ALIST))
                        (39 1 (:DEFINITION RP::ADD-RULE-TO-ALIST))
                        (37 25 (:REWRITE DEFAULT-CAR))
                        (29 29 (:REWRITE DEFAULT-CDR))
                        (20 18 (:REWRITE O-P-DEF-O-FINP-1))
                        (12 1 (:DEFINITION PUT-ASSOC-EQUAL))
                        (11 1 (:DEFINITION ASSOC-EQUAL))
                        (2 2 (:TYPE-PRESCRIPTION O-FINP))
                        (1 1
                           (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
                        (1 1
                           (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP)))
(RP::GET-RULES-FN (92 23 (:REWRITE O-P-O-INFP-CAR))
                  (59 43 (:REWRITE DEFAULT-CAR))
                  (50 10
                      (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
                  (39 31 (:REWRITE DEFAULT-CDR))
                  (30 3 (:DEFINITION SYMBOL-LISTP))
                  (27 3 (:DEFINITION ASSOC-EQUAL))
                  (23 23 (:REWRITE O-P-DEF-O-FINP-1))
                  (23 1 (:DEFINITION FGETPROP))
                  (10 10
                      (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
                  (6 6 (:TYPE-PRESCRIPTION MAKE-FAST-ALIST))
                  (6 6 (:REWRITE FN-CHECK-DEF-FORMALS))
                  (6 3 (:DEFINITION NTH))
                  (6 2
                     (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
                  (3 3 (:REWRITE NTH-WHEN-PREFIXP)))
(RP::E/D-RP-RULES-FN (254 65 (:REWRITE O-P-O-INFP-CAR))
                     (250 166 (:REWRITE DEFAULT-CAR))
                     (213 137 (:REWRITE DEFAULT-CDR))
                     (207 9 (:DEFINITION FGETPROP))
                     (108 12 (:DEFINITION ASSOC-EQUAL))
                     (108 9 (:DEFINITION HONS-ASSOC-EQUAL))
                     (63 63 (:REWRITE O-P-DEF-O-FINP-1))
                     (47 10
                         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
                     (24 12 (:DEFINITION NTH))
                     (24 8
                         (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
                     (12 12 (:REWRITE NTH-WHEN-PREFIXP))
                     (10 10
                         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
                     (9 9 (:DEFINITION HONS-EQUAL))
                     (4 1 (:DEFINITION RP::RP-TERMP))
                     (1 1
                        (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS)))
(RP::GET-DISABLED-EXC-RULES-FROM-TABLE)
(RP::GET-ENABLED-RULES-FROM-TABLE-AUX)
(RP::TRUE-LISTP-GET-ENABLED-RULES-FROM-TABLE-AUX-FOR-GUARDS
     (52028 204
            (:REWRITE RP::RP-TERM-LISTP-IS-TRUE-LISTP))
     (50736 68 (:DEFINITION TRUE-LISTP))
     (32580 136 (:DEFINITION RP::RP-TERM-LISTP))
     (30744 272
            (:REWRITE RP::RP-TERMP-IMPLIES-SUBTERMS))
     (30132 272 (:DEFINITION QUOTEP))
     (29384 136
            (:LINEAR APPLY$-BADGEP-PROPERTIES . 1))
     (29248 68 (:DEFINITION APPLY$-BADGEP))
     (23808 68 (:DEFINITION SUBSETP-EQUAL))
     (22924 952 (:DEFINITION MEMBER-EQUAL))
     (19244 272
            (:REWRITE RP::RP-TERMP-IMPLIES-CDR-LISTP))
     (18496 68 (:DEFINITION RP::RP-TERMP))
     (17363 15545 (:REWRITE DEFAULT-CDR))
     (14784 476
            (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-1))
     (14076 68 (:DEFINITION RP::FALIST-CONSISTENT))
     (10948 68
            (:DEFINITION RP::FALIST-CONSISTENT-AUX))
     (9972 9972 (:REWRITE DEFAULT-CAR))
     (7524 627 (:DEFINITION HONS-ASSOC-EQUAL))
     (5996 1601 (:REWRITE O-P-O-INFP-CAR))
     (2108 2108 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (1465 1465 (:REWRITE O-P-DEF-O-FINP-1))
     (1428 1428
           (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-3))
     (1292 136 (:DEFINITION NATP))
     (952 952
          (:REWRITE MEMBER-EQUAL-NEWVAR-COMPONENTS-2))
     (884 884
          (:TYPE-PRESCRIPTION RP::RP-TERM-LISTP))
     (816 340 (:REWRITE RP::IS-IF-RP-TERMP))
     (680 680 (:TYPE-PRESCRIPTION APPLY$-BADGEP))
     (627 627 (:DEFINITION HONS-EQUAL))
     (612 612
          (:TYPE-PRESCRIPTION RP::FALIST-CONSISTENT-AUX))
     (612 612
          (:REWRITE RP::RP-TERMP-SHOULD-TERM-BE-IN-CONS-LHS))
     (544 544 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
     (544 204 (:REWRITE RP::RP-TERMP-CADR))
     (476 476 (:TYPE-PRESCRIPTION LEN))
     (476 68 (:DEFINITION LEN))
     (408 204
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 3))
     (408 204
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 1))
     (408 68 (:DEFINITION ALL-NILS))
     (340 340 (:TYPE-PRESCRIPTION ALL-NILS))
     (340 68
          (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (272 272 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (272 272 (:TYPE-PRESCRIPTION QUOTEP))
     (272 136 (:REWRITE RP::RP-TERMP-CADDR))
     (272 136 (:REWRITE RP::IS-RP-PSEUDO-TERMP))
     (272 68 (:DEFINITION WEAK-APPLY$-BADGE-P))
     (204 204
          (:REWRITE TRUE-LIST-LISTP-IMPLIES-TRUE-LISTP))
     (204 204
          (:REWRITE INTEGER-LISTP-IMPLIES-INTEGERP))
     (136 136
          (:TYPE-PRESCRIPTION RP::IS-RP$INLINE))
     (136 136 (:LINEAR LEN-WHEN-PREFIXP))
     (136 68 (:REWRITE DEFAULT-+-2))
     (136 68
          (:REWRITE APPLY$-BADGEP-PROPERTIES . 2))
     (136 68
          (:LINEAR APPLY$-BADGEP-PROPERTIES . 2))
     (68 68
         (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (68 68 (:REWRITE LEN-MEMBER-EQUAL-LOOP$-AS))
     (68 68 (:REWRITE DEFAULT-<-2))
     (68 68 (:REWRITE DEFAULT-<-1))
     (68 68 (:REWRITE DEFAULT-+-1)))
(RP::GET-ENABLED-RULES-FROM-TABLE
     (64 16 (:REWRITE O-P-O-INFP-CAR))
     (46 2 (:DEFINITION FGETPROP))
     (43 31 (:REWRITE DEFAULT-CAR))
     (38 22 (:REWRITE DEFAULT-CDR))
     (30 6
         (:REWRITE RP::ATOM-RP-TERMP-IS-SYMBOLP))
     (26 26 (:TYPE-PRESCRIPTION MAKE-FAST-ALIST))
     (16 16 (:REWRITE O-P-DEF-O-FINP-1))
     (9 1 (:DEFINITION ASSOC-EQUAL))
     (6 6
        (:REWRITE SYMBOL-LISTP-IMPLIES-SYMBOLP))
     (6 2
        (:REWRITE STATE-P-IMPLIES-AND-FORWARD-TO-STATE-P1))
     (2 1
        (:TYPE-PRESCRIPTION TRUE-LISTP-APPEND))
     (2 1 (:DEFINITION NTH))
     (1 1 (:TYPE-PRESCRIPTION BINARY-APPEND))
     (1 1 (:REWRITE NTH-WHEN-PREFIXP)))
