all:
	cd Util; make
	cd Base; make
	cd AvD; make
	cd Collins; make
	cd DPSS-B; make

clean:
	cd Util; make clean
	cd Base; make clean
	cd AvD; make clean
	cd Collins; make clean
	cd DPSS-B; make clean
