include ../../../../../Makefile-generic

BOOKS = symbol-fns symbol-fns-exports

# Dependencies:

symbol-fns.cert: symbol-fns.lisp
symbol-fns.cert: symbol-fns.acl2
symbol-fns.acl2: symbol-fns-exports.cert

symbol-fns-exports.cert: symbol-fns-exports.lisp
symbol-fns-exports.cert: symbol-fns-exports.acl2
