include ../../../../../../Makefile-generic

ACL2 = ../../../../../../../saved_acl2

# Dependencies:

ackermann.cert: ackermann.lisp
ackermann.cert: ../../defmul.cert
ackermann.cert: ../../../../../../ordinals/e0-ordinal.cert
