# Instructions:

# Before starting, see "Dependencies" below.

# In the shell, execute
# make
# to certify all books.
# To clean up (removing files *.cert, *.o, *.fasl, etc.), in the shell execute
# make clean

include ../../../../Makefile-generic

ACL2 = ../../../../../saved_acl2

# Dependencies:
# In the shell, execute
# make -s dependencies
# to obtain the result below.

records.cert: records.lisp
records.cert: ../../../../misc/total-order.cert

records0.cert: records0.lisp
records0.cert: ../../../../misc/total-order.cert

sets.cert: sets.lisp
sets.cert: ../../../../misc/total-order.cert
