include ../../Makefile-generic
ACL2 = ../../../saved_acl2

# Dependencies:

# From make dependencies:

defpun-exec-domain-example.cert: defpun-exec-domain-example.lisp
# defpun-exec-domain-example.cert: $(ACL2_SYSTEM_BOOKS)/misc/defpun.cert

misc.cert: misc.lisp
# misc.cert: $(ACL2_SYSTEM_BOOKS)/rtl/rel7/arithmetic/top.cert
