include ../../../../Makefile-generic

# Don't alphabetize this list!
# [Matt K.: Not sure why not, or why we even need this list!  So, I'm
# commenting it out.]
#BOOKS = bits-new-proofs bits-new \
#        log-new-proofs log-new \
#        rtl-new-proofs rtl-new \
#        float-new-proofs float-new \
#        round-new-proofs round-new \
#	add-new-proofs add-new \
#	log-support-proofs log-support \
#        mult-new-proofs mult-new \
#        reps-new-proofs reps-new \
#        rtlarr-new  \
#        bits-proofs bits \
#        log-proofs log \
#	rtl-proofs rtl \
#        float-proofs float  \
#	round-proofs round \
#        reps-proofs reps \
#	add-proofs add \
#	mult-proofs mult \
#	rtlarr \
#	logn-new-proofs logn-new \
#	logn-proofs logn \
#	bvecp-raw-helpers-proofs  bvecp-raw-helpers \
#	simple-loop-helpers-proofs simple-loop-helpers \
#	arith \
#	bvecp-helpers \
#	simplify-model-helpers-new-proofs simplify-model-helpers-new \
#	simplify-model-helpers-proofs simplify-model-helpers \
#	util \
#	log-support-proofs log-support \
#	logn2log-proofs logn2log \
#	top

-include Makefile-deps
