include $(ACL2_SYSTEM_BOOKS)/Makefile-generic
INHIBIT = (assign inhibit-output-lst (list (quote proof-tree) (quote prove) (quote observation) (quote event) (quote expansion)))
BOOKS = bandb

bandb.cert: bandb.lisp
bandb.cert: ../tree-gen-helper/basics.cert

