include ../../Makefile-generic
ACL2 = ../../../saved_acl2
# Dependencies:

selected-solutions.cert: selected-solutions.lisp
selected-solutions.cert: ../../ordinals/e0-ordinal.cert
selected-solutions.cert: ../../arithmetic/top-with-meta.cert
