include ../../../../Makefile-generic

# Override default setting since TMP.lisp, TMP1.lisp, and
# dag-unification-examples.lisp are not intended to be certified.
BOOKS = basic dag-unification dags defpun terms

clean-TMPs:
	rm -f TMP.lisp TMP1.lisp

-include Makefile-deps
