include ../../../../../Makefile-generic
-include Makefile-deps

# make sure all these books get recertified if either certdep is updated
UNIVERSAL_DEPS := \
  ../../../../../build/acl2-version.certdep \
  ../../../../../build/universal-dependency.certdep

$(BOOKS_CERT): $(UNIVERSAL_DEPS)
