(TEST-CONVERSION-TO-ARRAY
 (9 9 (:REWRITE BV-ARRAY-WRITE-WHEN-LEN-IS-NOT-NATP))
 (9 9 (:REWRITE BV-ARRAY-WRITE-WHEN-INDEX-NOT-INTEGER-CHEAP))
 (4 4 (:REWRITE BV-ARRAY-WRITE-OF-BV-ARRAY-WRITE-DIFF-CONSTANT-INDICES-GEN))
 (3 3 (:REWRITE LEN-WHEN-NOT-CONSP-CHEAP))
 )
