(FGL::BVAR-DB-BFRLIST-AUX
 (112 27 (:REWRITE NFIX-WHEN-NOT-NATP))
 (62 41 (:REWRITE DEFAULT-<-1))
 (52 8 (:REWRITE ZP-WHEN-GT-0))
 (50 41 (:REWRITE DEFAULT-<-2))
 (46 26 (:REWRITE DEFAULT-+-2))
 (35 26 (:REWRITE DEFAULT-+-1))
 (32 16 (:REWRITE DEFAULT-UNARY-MINUS))
 (27 27
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (9 1
    (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (6 1 (:DEFINITION EQ))
 (4 4
    (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
 (4 4
    (:LINEAR FGL::TERM-BVAR-GTE-BASE-BVAR$A))
 (4 4
    (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES))
 (2 2 (:REWRITE FOLD-CONSTS-IN-+))
 (2 1 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (1 1 (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
 (1 1
    (:REWRITE FGL::GET-BVAR->TERM$A-OF-NFIX-N-NORMALIZE-CONST))
 (1
  1
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (1 1
    (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC)))
(FGL::BFRLIST-AUX-OF-GET-BVAR->TERM
 (674 15 (:DEFINITION MEMBER-EQUAL))
 (511 32 (:REWRITE SUBSETP-MEMBER . 3))
 (400 400
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (290 68 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (283 68 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (176 11 (:DEFINITION BINARY-APPEND))
 (156 13
      (:REWRITE SUBSETP-IMPLIES-SUBSETP-CDR))
 (153 17
      (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (135 30 (:REWRITE MEMBER-WHEN-ATOM))
 (132 22
      (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
 (115 52 (:REWRITE NFIX-WHEN-NOT-NATP))
 (102 17 (:DEFINITION EQ))
 (99 22 (:REWRITE APPEND-WHEN-NOT-CONSP))
 (81 33 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (77 53 (:REWRITE DEFAULT-+-2))
 (73 35 (:REWRITE NATP-WHEN-GTE-0))
 (70 70 (:REWRITE SUBSETP-TRANS2))
 (70 70 (:REWRITE SUBSETP-TRANS))
 (68 47 (:REWRITE DEFAULT-<-2))
 (60 13
     (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
 (59 53 (:REWRITE DEFAULT-+-1))
 (59 47 (:REWRITE DEFAULT-<-1))
 (51 8 (:REWRITE COMMUTATIVITY-OF-+))
 (42 5 (:REWRITE ZP-WHEN-INTEGERP))
 (40 40
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (36 3 (:REWRITE COMMUTATIVITY-2-OF-+))
 (35 35 (:REWRITE NATP-WHEN-INTEGERP))
 (32 32 (:REWRITE SUBSETP-MEMBER . 4))
 (32 32 (:REWRITE SUBSETP-MEMBER . 2))
 (30 30 (:TYPE-PRESCRIPTION BOOLEANP))
 (30 15 (:REWRITE DEFAULT-UNARY-MINUS))
 (26 26 (:REWRITE DEFAULT-CDR))
 (26 26 (:REWRITE DEFAULT-CAR))
 (24 12 (:REWRITE FOLD-CONSTS-IN-+))
 (18 18
     (:REWRITE FGL::GET-BVAR->TERM$A-OF-NFIX-N-NORMALIZE-CONST))
 (18 18
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (18 18
     (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC))
 (17
  17
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (17 17
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (11 1 (:REWRITE NFIX-EQUAL-TO-NONZERO))
 (10 10
     (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
 (10 10
     (:LINEAR FGL::TERM-BVAR-GTE-BASE-BVAR$A))
 (10 10
     (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES))
 (1 1
    (:REWRITE NFIX-EQUAL-TO-NONZERO-CONST)))
(FGL::BFRLIST-AUX-OF-ADD-TERM-BVAR
 (536 68 (:REWRITE NFIX-WHEN-NOT-NATP))
 (275 19 (:REWRITE ZP-WHEN-GT-0))
 (215 140 (:REWRITE DEFAULT-<-1))
 (203 6 (:REWRITE NFIX-EQUAL-TO-NONZERO))
 (198 140 (:REWRITE DEFAULT-<-2))
 (160 16 (:DEFINITION BINARY-APPEND))
 (146 74 (:REWRITE DEFAULT-+-2))
 (144 32 (:REWRITE APPEND-WHEN-NOT-CONSP))
 (144 16
      (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (137 57
      (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (113 74 (:REWRITE DEFAULT-+-1))
 (102 30 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (96 96
     (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (96 16 (:DEFINITION EQ))
 (77 22
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (75 15
     (:REWRITE FGL::BVAR-DB-EXTENSION-P-OF-ADD-TERM-BVAR))
 (45 45
     (:TYPE-PRESCRIPTION FGL::BVAR-DB-EXTENSION-P))
 (40 20 (:REWRITE DEFAULT-UNARY-MINUS))
 (30 15
     (:REWRITE FGL::BVAR-DB-EXTENSION-P-TRANSITIVE))
 (24 24
     (:TYPE-PRESCRIPTION FGL::TYPE-OF-GET-TERM->BVAR$A))
 (23 23
     (:LINEAR FGL::TERM-BVAR-GTE-BASE-BVAR$A))
 (22 22
     (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC))
 (20 8 (:REWRITE FOLD-CONSTS-IN-+))
 (16
  16
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (16 16
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (16 16 (:REWRITE DEFAULT-CDR))
 (16 16 (:REWRITE DEFAULT-CAR))
 (16 2 (:REWRITE COMMUTATIVITY-2-OF-+))
 (15 15
     (:REWRITE FGL::GET-BVAR->TERM$A-OF-NFIX-N-NORMALIZE-CONST))
 (12 12 (:TYPE-PRESCRIPTION BOOLEANP))
 (12 12
     (:REWRITE FGL::GET-TERM->BVAR$A-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (12 12
     (:REWRITE FGL::BVAR-DB-TERM->BVAR-EXTENSION-P-NECC))
 (12 12
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-TERM->BVAR))
 (7 7
    (:REWRITE FGL::ADD-TERM-BVAR$A-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (6 6
    (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
 (6 6
    (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES))
 (5 5
    (:REWRITE NFIX-EQUAL-TO-NONZERO-CONST)))
(FGL::BFRLIST-AUX-OF-UPDATE-TERM-EQUIVS
 (226 32 (:REWRITE NFIX-WHEN-NATP))
 (200 8 (:REWRITE ZP-WHEN-GT-0))
 (172 32 (:REWRITE NFIX-WHEN-NOT-NATP))
 (150 38 (:REWRITE NATP-WHEN-INTEGERP))
 (100 38 (:REWRITE NATP-WHEN-GTE-0))
 (100 10 (:DEFINITION BINARY-APPEND))
 (92 46 (:REWRITE DEFAULT-+-2))
 (83 51 (:REWRITE DEFAULT-<-2))
 (80 20 (:REWRITE APPEND-WHEN-NOT-CONSP))
 (74 46 (:REWRITE DEFAULT-+-1))
 (74 10
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (72 16
     (:LINEAR FGL::NEXT-BVAR-GTE-BASE-BVAR$A))
 (71 51 (:REWRITE DEFAULT-<-1))
 (68 68 (:TYPE-PRESCRIPTION NATP))
 (60 36
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (56 56
     (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (55 13 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (48 8 (:DEFINITION EQ))
 (40 40
     (:TYPE-PRESCRIPTION FGL::FGL-OBJECT-KIND$INLINE))
 (35 15
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (33 33
     (:TYPE-PRESCRIPTION FGL::BVAR-DB-EXTENSION-P))
 (28 14 (:REWRITE DEFAULT-UNARY-MINUS))
 (24 24
     (:TYPE-PRESCRIPTION FGL::TYPE-OF-NEXT-BVAR$A))
 (22 11
     (:REWRITE FGL::BVAR-DB-EXTENSION-P-TRANSITIVE))
 (15 15
     (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC))
 (10 10 (:TYPE-PRESCRIPTION BOOLEANP))
 (10 10
     (:REWRITE FGL::GET-BVAR->TERM$A-OF-NFIX-N-NORMALIZE-CONST))
 (10 10
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (10 10 (:REWRITE DEFAULT-CDR))
 (10 10 (:REWRITE DEFAULT-CAR))
 (8
  8
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (8 8
    (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
 (8 8
    (:LINEAR FGL::TERM-BVAR-GTE-BASE-BVAR$A))
 (8 8
    (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES))
 (5
  5
  (:REWRITE
       FGL::UPDATE-TERM-EQUIVS$A-OF-TERM-EQUIVS-FIX-EQUIVS-NORMALIZE-CONST)))
(FGL::SUBSETP-BFRLIST-OF-BVAR-DB-BFRLIST-AUX
 (151 2
      (:DEFINITION FGL::BVAR-DB-BFRLIST-AUX))
 (37 13 (:REWRITE NFIX-WHEN-NOT-NATP))
 (37 5
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (34 2 (:DEFINITION MEMBER-EQUAL))
 (31 5 (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
 (29 1
     (:REWRITE COMMUTATIVITY-OF-APPEND-UNDER-SET-EQUIV))
 (28 28
     (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (28 14 (:REWRITE NATP-WHEN-GTE-0))
 (26 2 (:DEFINITION BINARY-APPEND))
 (24 4 (:DEFINITION EQ))
 (24 2 (:REWRITE ZP-WHEN-GT-0))
 (21 15 (:REWRITE DEFAULT-<-2))
 (19 15 (:REWRITE DEFAULT-<-1))
 (18 6 (:DEFINITION LNFIX$INLINE))
 (18 4 (:REWRITE MEMBER-WHEN-ATOM))
 (18 4 (:REWRITE APPEND-WHEN-NOT-CONSP))
 (14 14 (:REWRITE NATP-WHEN-INTEGERP))
 (14 6 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (12 2
     (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
 (10 10
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (8 6 (:REWRITE DEFAULT-+-2))
 (8 2 (:DEFINITION FGL::GET-BVAR->TERM))
 (8 1 (:REWRITE ZP-WHEN-INTEGERP))
 (6 6 (:REWRITE DEFAULT-+-1))
 (5 5
    (:REWRITE FGL::GET-BVAR->TERM$A-OF-NFIX-N-NORMALIZE-CONST))
 (5 5
    (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (5 5
    (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC))
 (4 4 (:TYPE-PRESCRIPTION BOOLEANP))
 (4 4 (:REWRITE SUBSETP-MEMBER . 4))
 (4 4 (:REWRITE SUBSETP-MEMBER . 3))
 (4 4 (:REWRITE SUBSETP-MEMBER . 2))
 (4 4 (:REWRITE SUBSETP-MEMBER . 1))
 (4
  4
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (4 4 (:REWRITE DEFAULT-CDR))
 (4 4 (:REWRITE DEFAULT-CAR))
 (4 2 (:REWRITE DEFAULT-UNARY-MINUS))
 (4 2 (:DEFINITION FGL::BASE-BVAR))
 (3 3
    (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
 (3 3
    (:LINEAR FGL::TERM-BVAR-GTE-BASE-BVAR$A))
 (3 3
    (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES))
 (1 1 (:REWRITE SUBSETP-TRANS2))
 (1 1 (:REWRITE SUBSETP-TRANS)))
(FGL::BVAR-DB-BFRLIST)
(FGL::BFRLIST-OF-GET-BVAR->TERM
     (6 2 (:REWRITE NFIX-WHEN-NOT-NATP))
     (4 4 (:TYPE-PRESCRIPTION NATP))
     (4 2 (:REWRITE NATP-WHEN-GTE-0))
     (2 2 (:REWRITE NATP-WHEN-INTEGERP))
     (1 1 (:REWRITE SUBSETP-MEMBER . 4))
     (1 1 (:REWRITE SUBSETP-MEMBER . 3))
     (1 1 (:REWRITE SUBSETP-MEMBER . 2))
     (1 1 (:REWRITE DEFAULT-<-2))
     (1 1 (:REWRITE DEFAULT-<-1))
     (1 1
        (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
     (1 1
        (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
     (1 1
        (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES)))
(FGL::BVAR-DB-BFRLIST-OF-ADD-TERM-BVAR
 (50 5 (:DEFINITION BINARY-APPEND))
 (45 10 (:REWRITE APPEND-WHEN-NOT-CONSP))
 (45 5
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (30 30
     (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (30 5 (:DEFINITION EQ))
 (29 14 (:REWRITE DEFAULT-+-2))
 (24 12 (:REWRITE NFIX-WHEN-NOT-NATP))
 (24 2 (:REWRITE ZP-WHEN-INTEGERP))
 (20 14 (:REWRITE DEFAULT-+-1))
 (19 9
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (14 5 (:REWRITE DEFAULT-<-2))
 (10 5 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (10 2 (:DEFINITION NOT))
 (8 3
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (7 2
    (:REWRITE FGL::BVAR-DB-EXTENSION-P-OF-ADD-TERM-BVAR))
 (6 6
    (:TYPE-PRESCRIPTION FGL::BVAR-DB-EXTENSION-P))
 (6 5 (:REWRITE DEFAULT-<-1))
 (6 3 (:REWRITE DEFAULT-UNARY-MINUS))
 (5
  5
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (5 5
    (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (5 5 (:REWRITE DEFAULT-CDR))
 (5 5 (:REWRITE DEFAULT-CAR))
 (4 2
    (:REWRITE FGL::BVAR-DB-EXTENSION-P-TRANSITIVE))
 (3 3
    (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC))
 (3 3
    (:LINEAR FGL::TERM-BVAR-GTE-BASE-BVAR$A))
 (2 2
    (:TYPE-PRESCRIPTION FGL::TYPE-OF-GET-TERM->BVAR$A))
 (2 2
    (:REWRITE FGL::GET-BVAR->TERM$A-OF-NFIX-N-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::ADD-TERM-BVAR$A-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (2 2
    (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
 (2 2
    (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES))
 (1 1
    (:REWRITE FGL::GET-TERM->BVAR$A-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::BVAR-DB-TERM->BVAR-EXTENSION-P-NECC))
 (1 1
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-TERM->BVAR)))
(FGL::SUBSETP-BFRLIST-OF-BVAR-DB-BFRLIST
 (16 4 (:REWRITE NFIX-WHEN-NOT-NATP))
 (13 2 (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
 (12 12 (:TYPE-PRESCRIPTION NATP))
 (12 6 (:REWRITE NATP-WHEN-GTE-0))
 (9 6 (:REWRITE DEFAULT-<-2))
 (9 1
    (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (8 6 (:REWRITE DEFAULT-<-1))
 (6 6 (:REWRITE NATP-WHEN-INTEGERP))
 (6 1 (:DEFINITION EQ))
 (3 3
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (2 1 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (1 1
    (:REWRITE FGL::GET-BVAR->TERM$A-OF-NFIX-N-NORMALIZE-CONST))
 (1
  1
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (1 1
    (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC))
 (1 1
    (:LINEAR FGL::TERM-BVAR-LESS-THAN-NEXT-BVAR$A))
 (1 1
    (:LINEAR FGL::TERM-BVAR-GTE-BASE-BVAR$A))
 (1 1
    (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES)))
(FGL::BVAR-DB-BFRLIST-OF-ADD-TERM-BVAR-UNIQUE
 (160 10 (:DEFINITION BINARY-APPEND))
 (105 20
      (:REWRITE APPEND-ATOM-UNDER-LIST-EQUIV))
 (104 104
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (93 13
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (75 20 (:REWRITE APPEND-WHEN-NOT-CONSP))
 (60 10 (:DEFINITION EQ))
 (24 4 (:REWRITE SUBSETP-WHEN-ATOM-RIGHT))
 (24 4 (:REWRITE SUBSETP-WHEN-ATOM-LEFT))
 (21 21
     (:REWRITE FGL::GET-TERM->BVAR$A-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (21 21
     (:REWRITE FGL::BVAR-DB-TERM->BVAR-EXTENSION-P-NECC))
 (21 21
     (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-TERM->BVAR))
 (20 10 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (20 5 (:REWRITE SUBSETP-TRANS))
 (18 4 (:REWRITE NFIX-WHEN-NOT-NATP))
 (16 4 (:REWRITE NATP-WHEN-GTE-0))
 (13 13
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (10
  10
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (10 10 (:REWRITE DEFAULT-CDR))
 (10 10 (:REWRITE DEFAULT-CAR))
 (9 9
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-BASE-BVAR))
 (8 4 (:REWRITE DEFAULT-<-2))
 (6 4 (:REWRITE DEFAULT-<-1))
 (4 4 (:TYPE-PRESCRIPTION NATP))
 (4 4
    (:REWRITE FGL::BVAR-DB-EXTENSION-PRESERVES-GET-BVAR->TERM))
 (4 4
    (:REWRITE FGL::BVAR-DB-BVAR->TERM-EXTENSION-P-NECC))
 (3 3
    (:REWRITE FGL::ADD-TERM-BVAR-UNIQUE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::ADD-TERM-BVAR$A-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (2 2 (:REWRITE INEQUALITY-WITH-NFIX-HYP-2))
 (2 2
    (:LINEAR FGL::BVAR-DB-EXTENSION-INCREASES)))
