(FGL::TOP-FORMULA-CHECKS)
(FGL::WORLD-EQUIV-IMPLIES-EQUAL-TOP-FORMULA-CHECKS-1
     (553 185
          (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
     (368 368 (:TYPE-PRESCRIPTION BOOLEANP)))
(FGL::META-EXTRACT-FORMULA-+CARRY-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-+CARRY-EXT-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-+CARRY-TRUNC-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-=-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-AIG-ATOM-P$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-AIG-ENV-LOOKUP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-AIG-EVAL-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-AIG-EVAL-LIST-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-ASH-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-ATOM-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BINARY-LOGAND-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BINARY-LOGEQV-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BINARY-LOGIOR-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BINARY-LOGXOR-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BITP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BOOL->BIT$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BOOL-FIX$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-BOOLEANP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-BITP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-BOOLEANP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-CONSP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-DCL-GUARDIAN-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-EQUAL-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-INT-ENDP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-INTEGERP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-NATP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-NON-BOOLEANP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-NON-CONSP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-NON-INTEGERP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-SIGNED-BYTE-P-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-TRUE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CHECK-UNSIGNED-BYTE-P-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-CREATE-FGARRAY$A-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-EQ-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-EQL-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-EVENP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-EXPT-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-EXPT2$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FAST-ALIST-CLEAN-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FAST-ALIST-FORK-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGARRAY->ALIST$A-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGARRAY-COMPRESS$A-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGARRAY-COMPRESS$A-AUX-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGARRAY-GET$A-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGARRAY-INIT$A-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGARRAY-MAX-KEY-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGARRAY-SET$A-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGL-GLOBAL-TRANSFORM-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGL-PATHCOND-FIX-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FGL-SIMPLIFY-OBJECT-FN-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FIX-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-FLOOR-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-GATECOUNT-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-HONS-ACONS-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-HONS-ASSOC-EQUAL-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-HONS-EQUAL-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-HONS-GET-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-IF!-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-IFIX-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-IFLOOR$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-IMOD$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-INTEGER-LENGTH-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-INTEGER-LENGTH-BOUND-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-INTEGER-RANGE-P-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LAST-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LIFIX$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LNFIX$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGAPP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGBITP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGEXT-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGHEAD$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGMASK$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGNOT-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGORC1-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-LOGTAIL$INLINE-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-MAKE-FAST-ALIST-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-MAX-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-MOD-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-MV-NTH-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-NATP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-NFIX-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-NONNEGATIVE-INTEGER-QUOTIENT-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-ODDP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-SAT-CHECK-RAW-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-SAT-CHECK-WITH-WITNESS-RAW-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-SIGNED-BYTE-P-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-SUPPORT-VARS-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-THE-CHECK-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-THROW-NONEXEC-ERROR-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-UNSIGNED-BYTE-P-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-ZIP-WHEN-TOP-FORMULA-CHECKS)
(FGL::META-EXTRACT-FORMULA-ZP-WHEN-TOP-FORMULA-CHECKS)
(FGL::SAT-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::GATECOUNT-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::FGL-SIMPLIFY-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::GLOBAL-TRANS-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::CHECKS-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::BITOPS-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::FGL-PATHCOND-FIX-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::AIG-EVAL-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::FGARRAY-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::FAST-ALIST-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::PRIMITIVES-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS)
(FGL::TOP-PRIMITIVE-FNCALL (664 332
                                (:TYPE-PRESCRIPTION LRAT::NTH-N59-LISTP))
                           (664 332
                                (:TYPE-PRESCRIPTION LRAT::NTH-I60-LISTP))
                           (332 332
                                (:TYPE-PRESCRIPTION LRAT::N59-LISTP))
                           (332 332
                                (:TYPE-PRESCRIPTION LRAT::I60-LISTP)))
(FGL::FGL-PRIMITIVE-CONSTRAINT-OF-TOP-PRIMITIVE-FNCALL
 (1131 87
       (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (870 87
      (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (774 129
      (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (435 87 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (261 261 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (261 261 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (258 258 (:TYPE-PRESCRIPTION BOOLEANP))
 (174 174
      (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (174 87 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (174 87 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (87 87
     (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (30 10
     (:REWRITE FGL::BITOPS-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (18 6
     (:REWRITE FGL::PRIMITIVES-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (15 5
     (:REWRITE FGL::FGARRAY-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (15 5
     (:REWRITE FGL::FAST-ALIST-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (10 10
     (:REWRITE FGL::BITOPS-FORMULA-CHECKS-SIMPLIFY-STATE))
 (6 6
    (:REWRITE FGL::PRIMITIVES-FORMULA-CHECKS-SIMPLIFY-STATE))
 (5 5
    (:REWRITE FGL::FGARRAY-FORMULA-CHECKS-SIMPLIFY-STATE))
 (5 5
    (:REWRITE FGL::FAST-ALIST-FORMULA-CHECKS-SIMPLIFY-STATE))
 (3 1
    (:REWRITE FGL::GLOBAL-TRANS-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (3 1
    (:REWRITE FGL::FGL-SIMPLIFY-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (3 1
    (:REWRITE FGL::FGL-PATHCOND-FIX-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (3 1
    (:REWRITE FGL::AIG-EVAL-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (2
  2
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::GLOBAL-TRANS-FORMULA-CHECKS-SIMPLIFY-STATE))
 (1 1
    (:REWRITE FGL::FGL-SIMPLIFY-FORMULA-CHECKS-SIMPLIFY-STATE))
 (1 1
    (:REWRITE FGL::FGL-PATHCOND-FIX-FORMULA-CHECKS-SIMPLIFY-STATE))
 (1 1
    (:REWRITE FGL::AIG-EVAL-FORMULA-CHECKS-SIMPLIFY-STATE)))
(FGL::TOP-PRIMITIVE-FNCALL-OF-PSEUDO-FNSYM-FIX-PRIMFN
 (516 86 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (172 172 (:TYPE-PRESCRIPTION BOOLEANP))
 (15 3
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (10 1 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (5 1 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (4 4
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (3 3 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (3 3 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (2
  2
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 1 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (2 1 (:REWRITE PSEUDO-FN-P-WHEN-CONSP)))
(FGL::TOP-PRIMITIVE-FNCALL-OF-PSEUDO-FNSYM-FIX-PRIMFN-NORMALIZE-CONST)
(FGL::TOP-PRIMITIVE-FNCALL-PSEUDO-FNSYM-EQUIV-CONGRUENCE-ON-PRIMFN)
(FGL::TOP-PRIMITIVE-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN
 (516 86 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (172 172 (:TYPE-PRESCRIPTION BOOLEANP))
 (39 3
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (30 3 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (15 3 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (9 9 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (9 9 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (6 3 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (6 3 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (3 3
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
   3
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
   3
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
   3
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
   3
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::TOP-PRIMITIVE-FNCALL-OF-PSEUDO-FNSYM-FIX-PRIMFN-NORMALIZE-CONST)))
(FGL::TOP-PRIMITIVE-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST)
(FGL::TOP-PRIMITIVE-FNCALL-PSEUDO-FNSYM-EQUIV-CONGRUENCE-ON-ORIGFN)
(FGL::TOP-PRIMITIVE-FNCALL-OF-FGL-OBJECTLIST-FIX-ARGS
 (516 86 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (172 172 (:TYPE-PRESCRIPTION BOOLEANP))
 (26 2
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (20 2 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (10 2 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (8 1
    (:REWRITE FGL::FGL-OBJECTLIST-FIX-WHEN-FGL-OBJECTLIST-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (4 4 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (4 2 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (4 2 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (4 1
    (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-NOT-CONSP))
 (3
  3
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
   3
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
   3
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:TYPE-PRESCRIPTION FGL::FGL-OBJECTLIST-P))
 (2
  2
  (:REWRITE
       FGL::TOP-PRIMITIVE-FNCALL-OF-PSEUDO-FNSYM-FIX-PRIMFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::TOP-PRIMITIVE-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-UNARY---PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-MV-NTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-MAKE-FAST-ALIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-LOGTAIL$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGNOT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-LOGAPP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INTEGERP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-INTEGER-LENGTH-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::FGL-INTCONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-INTCAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-INT-ENDP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IFIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-IF!-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-HONS-GET-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-HONS-ACONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-SIMPLIFY-OBJECT-FN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-PATHCOND-FIX-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGL-GLOBAL-TRANSFORM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-SET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-INIT$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-GET$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FGARRAY-COMPRESS$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-FORK-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-FAST-ALIST-CLEAN-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-EQUAL-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-ENDINT-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-CREATE-FGARRAY$A-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::FGL-CONSP-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CONS-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CDR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-CAR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BOOL-FIX$INLINE-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGXOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGIOR-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGEQV-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-BINARY-LOGAND-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::FGL-BINARY-+-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::FGL-ATOM-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-AIG-EVAL-LIST-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE FGL::FGL-<-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::FGL-+CARRY-TRUNC-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::FGL-+CARRY-PRIMITIVE-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (1 1
    (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-FGL-BFR-OBJECTLIST-P))
 (1 1
    (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST)))
(FGL::TOP-PRIMITIVE-FNCALL-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST)
(FGL::TOP-PRIMITIVE-FNCALL-FGL-OBJECTLIST-EQUIV-CONGRUENCE-ON-ARGS)
(FGL::TOP-META-FNCALL (664 332
                           (:TYPE-PRESCRIPTION LRAT::NTH-N59-LISTP))
                      (664 332
                           (:TYPE-PRESCRIPTION LRAT::NTH-I60-LISTP))
                      (332 332
                           (:TYPE-PRESCRIPTION LRAT::N59-LISTP))
                      (332 332
                           (:TYPE-PRESCRIPTION LRAT::I60-LISTP)))
(FGL::FGL-META-CONSTRAINT-OF-TOP-META-FNCALL
 (65 5
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (50 5 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (36 6 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (25 5 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (15 15 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (15 15 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (12 12 (:TYPE-PRESCRIPTION BOOLEANP))
 (10 10 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (10 5 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (10 5 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (6 2
    (:REWRITE FGL::BITOPS-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (5 5
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::LOGAPP-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::LOGAPP-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::BITOPS-FORMULA-CHECKS-SIMPLIFY-STATE)))
(FGL::TOP-META-FNCALL-OF-PSEUDO-FNSYM-FIX-METAFN
 (24 4 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (15 3
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (10 1 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (8 8 (:TYPE-PRESCRIPTION BOOLEANP))
 (5 1 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (4 4
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (3 3 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (3 3 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (2
   2
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::LOGAPP-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::LOGAPP-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 1 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (2 1 (:REWRITE PSEUDO-FN-P-WHEN-CONSP)))
(FGL::TOP-META-FNCALL-OF-PSEUDO-FNSYM-FIX-METAFN-NORMALIZE-CONST)
(FGL::TOP-META-FNCALL-PSEUDO-FNSYM-EQUIV-CONGRUENCE-ON-METAFN)
(FGL::TOP-META-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN
 (39 3
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (30 3 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (24 4 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (15 3 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (9 9 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (9 9 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (8 8 (:TYPE-PRESCRIPTION BOOLEANP))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (6 3 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (6 3 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (3 3
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (3
   3
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3
   3
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::LOGAPP-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::LOGAPP-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::TOP-META-FNCALL-OF-PSEUDO-FNSYM-FIX-METAFN-NORMALIZE-CONST)))
(FGL::TOP-META-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST)
(FGL::TOP-META-FNCALL-PSEUDO-FNSYM-EQUIV-CONGRUENCE-ON-ORIGFN)
(FGL::TOP-META-FNCALL-OF-FGL-OBJECTLIST-FIX-ARGS
 (26 2
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (24 4 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (20 2 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (10 2 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (8 8 (:TYPE-PRESCRIPTION BOOLEANP))
 (8 1
    (:REWRITE FGL::FGL-OBJECTLIST-FIX-WHEN-FGL-OBJECTLIST-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (4 4 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (4 2 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (4 2 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (4 1
    (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-NOT-CONSP))
 (3
   3
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::LOGAPP-EXPAND-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:TYPE-PRESCRIPTION FGL::FGL-OBJECTLIST-P))
 (2
  2
  (:REWRITE FGL::TOP-META-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE FGL::TOP-META-FNCALL-OF-PSEUDO-FNSYM-FIX-METAFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::LOGTAIL-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::LOGAPP-EXPAND-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (1 1
    (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-FGL-BFR-OBJECTLIST-P))
 (1 1
    (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST)))
(FGL::TOP-META-FNCALL-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST)
(FGL::TOP-META-FNCALL-FGL-OBJECTLIST-EQUIV-CONGRUENCE-ON-ARGS)
(FGL::TOP-BINDER-FNCALL (664 332
                             (:TYPE-PRESCRIPTION LRAT::NTH-N59-LISTP))
                        (664 332
                             (:TYPE-PRESCRIPTION LRAT::NTH-I60-LISTP))
                        (332 332
                             (:TYPE-PRESCRIPTION LRAT::N59-LISTP))
                        (332 332
                             (:TYPE-PRESCRIPTION LRAT::I60-LISTP)))
(FGL::FGL-BINDER-CONSTRAINT-OF-TOP-BINDER-FNCALL
 (481 37
      (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (370 37
      (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (324 54 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (185 37 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (111 111 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (111 111 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (108 108 (:TYPE-PRESCRIPTION BOOLEANP))
 (74 74 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (74 37 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (74 37 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (42 14
     (:REWRITE FGL::CHECKS-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (37 37
     (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (14 14
     (:REWRITE FGL::CHECKS-FORMULA-CHECKS-SIMPLIFY-STATE))
 (6 2
    (:REWRITE FGL::SAT-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (6 2
    (:REWRITE FGL::GATECOUNT-FORMULA-CHECKS-WHEN-TOP-FORMULA-CHECKS))
 (2
  2
  (:REWRITE FGL::SUPPORT-VARS-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::SUPPORT-VARS-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::SAT-FORMULA-CHECKS-SIMPLIFY-STATE))
 (2
  2
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::SAT-CHECK-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::SAT-CHECK-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
    FGL::INTEGER-LENGTH-BOUND-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::INTEGER-LENGTH-BOUND-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::GATECOUNT-FORMULA-CHECKS-SIMPLIFY-STATE))
 (2 2
    (:REWRITE FGL::GATECOUNT-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::GATECOUNT-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-TRUE-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-TRUE-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-NON-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-NON-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-NON-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::CHECK-NON-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-NON-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-NON-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-NATP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-NATP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-INT-ENDP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-INT-ENDP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::CHECK-EQUAL-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-EQUAL-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::CHECK-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-BITP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-BITP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST)))
(FGL::TOP-BINDER-FNCALL-OF-PSEUDO-FNSYM-FIX-BINDFN
 (216 36 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (72 72 (:TYPE-PRESCRIPTION BOOLEANP))
 (15 3
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (10 1 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (5 1 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (4 4
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (3 3 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (3 3 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (2 2 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (2
  2
  (:REWRITE FGL::SUPPORT-VARS-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE
        FGL::SUPPORT-VARS-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::SAT-CHECK-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
       FGL::SAT-CHECK-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
    FGL::INTEGER-LENGTH-BOUND-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::INTEGER-LENGTH-BOUND-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::GATECOUNT-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::GATECOUNT-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-TRUE-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-TRUE-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-NON-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-NON-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-NON-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::CHECK-NON-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-NON-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CHECK-NON-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-NATP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-NATP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-INT-ENDP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-INT-ENDP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::CHECK-EQUAL-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-EQUAL-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::CHECK-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-BITP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-BITP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 1 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (2 1 (:REWRITE PSEUDO-FN-P-WHEN-CONSP)))
(FGL::TOP-BINDER-FNCALL-OF-PSEUDO-FNSYM-FIX-BINDFN-NORMALIZE-CONST)
(FGL::TOP-BINDER-FNCALL-PSEUDO-FNSYM-EQUIV-CONGRUENCE-ON-BINDFN)
(FGL::TOP-BINDER-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN
 (216 36 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (72 72 (:TYPE-PRESCRIPTION BOOLEANP))
 (39 3
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (30 3 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (15 3 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (9 9 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (9 9 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (6 3 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (6 3 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (3
  3
  (:REWRITE FGL::SUPPORT-VARS-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
   3
   (:REWRITE
        FGL::SUPPORT-VARS-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::SAT-CHECK-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::SAT-CHECK-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
    FGL::INTEGER-LENGTH-BOUND-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTEGER-LENGTH-BOUND-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::GATECOUNT-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::GATECOUNT-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::CHECK-TRUE-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-TRUE-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-NON-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-NON-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-NON-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::CHECK-NON-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-NON-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-NON-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::CHECK-NATP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-NATP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-INT-ENDP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-INT-ENDP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
   3
   (:REWRITE FGL::CHECK-EQUAL-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-EQUAL-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
   3
   (:REWRITE FGL::CHECK-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::CHECK-BITP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-BITP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::TOP-BINDER-FNCALL-OF-PSEUDO-FNSYM-FIX-BINDFN-NORMALIZE-CONST)))
(FGL::TOP-BINDER-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST)
(FGL::TOP-BINDER-FNCALL-PSEUDO-FNSYM-EQUIV-CONGRUENCE-ON-ORIGFN)
(FGL::TOP-BINDER-FNCALL-OF-FGL-OBJECTLIST-FIX-ARGS
 (216 36 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (72 72 (:TYPE-PRESCRIPTION BOOLEANP))
 (26 2
     (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (20 2 (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (10 2 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (8 1
    (:REWRITE FGL::FGL-OBJECTLIST-FIX-WHEN-FGL-OBJECTLIST-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (6 6 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (4 4 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (4 2 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (4 2 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (4 1
    (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-NOT-CONSP))
 (3
   3
   (:REWRITE
        FGL::SUPPORT-VARS-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
       FGL::SAT-CHECK-RAW-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTEGER-LENGTH-BOUND-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::GATECOUNT-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-TRUE-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-NON-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
     FGL::CHECK-NON-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::CHECK-NON-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-NATP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-INTEGERP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-INT-ENDP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-EQUAL-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-CONSP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
      FGL::CHECK-BOOLEANP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (3 3
    (:REWRITE
         FGL::CHECK-BITP-BINDER-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST))
 (2 2
    (:TYPE-PRESCRIPTION FGL::FGL-OBJECTLIST-P))
 (2 2
    (:REWRITE
         FGL::TOP-BINDER-FNCALL-OF-PSEUDO-FNSYM-FIX-ORIGFN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::TOP-BINDER-FNCALL-OF-PSEUDO-FNSYM-FIX-BINDFN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE FGL::SUPPORT-VARS-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::SAT-CHECK-WITH-WITNESS-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::SAT-CHECK-RAW-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
    FGL::INTEGER-LENGTH-BOUND-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::GATECOUNT-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (2
  2
  (:REWRITE
   FGL::CHECK-UNSIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-TRUE-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
     FGL::CHECK-SIGNED-BYTE-P-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-NON-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-NON-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
      FGL::CHECK-NON-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-NATP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-INTEGERP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-INT-ENDP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::CHECK-EQUAL-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2
   2
   (:REWRITE FGL::CHECK-CONSP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE
         FGL::CHECK-BOOLEANP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (2 2
    (:REWRITE FGL::CHECK-BITP-BINDER-OF-PSEUDO-FNSYM-FIX-FN-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-FGL-BFR-OBJECTLIST-P))
 (1 1
    (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST)))
(FGL::TOP-BINDER-FNCALL-OF-FGL-OBJECTLIST-FIX-ARGS-NORMALIZE-CONST)
(FGL::TOP-BINDER-FNCALL-FGL-OBJECTLIST-EQUIV-CONGRUENCE-ON-ARGS)
(FGL::PSEUDO-FNSYM-FIX-EQUAL-FORWARD)
(FGL::TOP-FANCY-EV-PRIMITIVES
 (3285 2180
       (:TYPE-PRESCRIPTION LRAT::NTH-N59-LISTP))
 (3285 2180
       (:TYPE-PRESCRIPTION LRAT::NTH-I60-LISTP))
 (1833 13 (:DEFINITION TRUE-LISTP))
 (1388 114
       (:REWRITE INTEGERP-OF-CAR-WHEN-INTEGER-LISTP))
 (1221 1221
       (:TYPE-PRESCRIPTION LRAT::N59-LISTP))
 (1221 1221
       (:TYPE-PRESCRIPTION LRAT::I60-LISTP))
 (1078 26 (:REWRITE LRAT::N59-LISTP-FORWARD))
 (1078 26 (:REWRITE LRAT::I60-LISTP-FORWARD))
 (1008 22 (:DEFINITION LRAT::N59-LISTP))
 (1008 22 (:DEFINITION LRAT::I60-LISTP))
 (980 70 (:DEFINITION INTEGER-LISTP))
 (762 15 (:DEFINITION SYMBOL-LISTP))
 (692 8
      (:REWRITE TRUE-LISTP-OF-CAR-WHEN-TRUE-LIST-LISTP))
 (684 96
      (:REWRITE INTEGER-LISTP-OF-CDR-WHEN-INTEGER-LISTP))
 (676 4 (:DEFINITION TRUE-LIST-LISTP))
 (672 672
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (601 26
      (:REWRITE SYMBOLP-OF-CAR-WHEN-SYMBOL-LISTP))
 (542 542 (:TYPE-PRESCRIPTION INTEGER-LISTP))
 (521 38
      (:REWRITE FGL::SYMBOL-LISTP-WHEN-PSEUDO-VAR-LIST-P))
 (504 40 (:REWRITE CONSP-OF-CAR-WHEN-ALISTP))
 (488 8
      (:REWRITE PSEUDO-TERMP-CAR-WHEN-PSEUDO-TERM-LISTP))
 (357 309 (:REWRITE DEFAULT-CAR))
 (346 346
      (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (337 19 (:REWRITE PSEUDO-TERMP-OPENER))
 (316 31
      (:REWRITE CMR::PSEUDO-VAR-LIST-P-OF-CDR-WHEN-PSEUDO-VAR-LIST-P))
 (316 28
      (:REWRITE PSEUDO-TERM-LISTP-CDR-WHEN-PSEUDO-TERM-LISTP))
 (298 166
      (:REWRITE INTEGER-LISTP-WHEN-NOT-CONSP))
 (280 52
      (:REWRITE CMR::PSEUDO-TERM-LIST-P-WHEN-PSEUDO-VAR-LIST-P))
 (278 89
      (:REWRITE CMR::PSEUDO-VAR-LIST-P-WHEN-NOT-CONSP))
 (240 48
      (:REWRITE ALISTP-WHEN-HONS-DUPLICITY-ALIST-P))
 (235 223 (:REWRITE DEFAULT-CDR))
 (216 12 (:DEFINITION LEN))
 (206 26
      (:REWRITE TRUE-LISTP-WHEN-CHARACTER-LISTP-REWRITE))
 (178 178
      (:TYPE-PRESCRIPTION CMR::PSEUDO-VAR-LIST-P))
 (152 16 (:REWRITE ALISTP-OF-CDR))
 (140 140
      (:TYPE-PRESCRIPTION PSEUDO-TERM-LISTP))
 (136 26
      (:REWRITE SET::SETS-ARE-TRUE-LISTS-CHEAP))
 (120 28 (:REWRITE PSEUDO-TERMP-LIST-CDR))
 (116 65 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (107 38
      (:REWRITE SYMBOL-LISTP-WHEN-NOT-CONSP))
 (104 92 (:REWRITE DEFAULT-<-1))
 (104 12
      (:REWRITE FGL::SYMBOLP-OF-CAAR-WHEN-FGL-FUNCTION-MODE-ALIST-P))
 (101 101 (:TYPE-PRESCRIPTION SYMBOL-LISTP))
 (98 15
     (:REWRITE SYMBOL-LISTP-OF-CDR-WHEN-SYMBOL-LISTP))
 (96 96
     (:TYPE-PRESCRIPTION HONS-DUPLICITY-ALIST-P))
 (96 48
     (:REWRITE HONS-DUPLICITY-ALIST-P-WHEN-NOT-CONSP))
 (96 48 (:REWRITE ALISTP-WHEN-ATOM))
 (93 92 (:REWRITE DEFAULT-<-2))
 (93 3 (:REWRITE NATP-WHEN-GTE-0))
 (91 13
     (:REWRITE FGL::BFR-LISTP$-WHEN-NOT-CONSP))
 (81 9
     (:REWRITE FGL::FGL-OBJECT-BFRLIST-WHEN-G-VAR))
 (76 8 (:REWRITE PSEUDO-TERMP-CAR))
 (72 36
     (:REWRITE CONSP-OF-CAR-WHEN-ATOM-LISTP))
 (72 24 (:REWRITE LRAT::LEN-A$))
 (68 68
     (:REWRITE CAR-OF-TRUE-LIST-LIST-FIX-X-NORMALIZE-CONST-UNDER-LIST-EQUIV))
 (68 4
     (:REWRITE FGL::NOT-QUOTE-WHEN-PSEUDO-FNSYM-P))
 (57 57 (:TYPE-PRESCRIPTION CHARACTER-LISTP))
 (52 52
     (:REWRITE FGL::TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
 (52 52 (:REWRITE PSEUDO-TERM-LISTP-OF-ATOM))
 (51 51
     (:REWRITE TERM-LISTP-IMPLIES-PSEUDO-TERM-LISTP))
 (48 48 (:TYPE-PRESCRIPTION LRAT::A$P))
 (44 44 (:TYPE-PRESCRIPTION SET::SETP-TYPE))
 (44 44 (:TYPE-PRESCRIPTION ATOM-LISTP))
 (44 44
     (:REWRITE CHARACTER-LISTP-WHEN-SUBSETP-EQUAL))
 (44 22 (:REWRITE SET::NONEMPTY-MEANS-SET))
 (44 22
     (:REWRITE STR::CHARACTER-LISTP-WHEN-DIGIT-LISTP))
 (44 4
     (:REWRITE PSEUDO-TERMP-CADR-FROM-PSEUDO-TERM-LISTP))
 (40 5
     (:REWRITE FGL::FGL-OBJECT-P-NTH-OF-FGL-OBJECTLIST-P))
 (40
  4
  (:REWRITE
       FGL::FGL-FUNCTION-MODE-ALIST-P-OF-CDR-WHEN-FGL-FUNCTION-MODE-ALIST-P))
 (39 3 (:REWRITE NATP-WHEN-INTEGERP))
 (38 38 (:REWRITE FN-CHECK-DEF-FORMALS))
 (36 4
     (:REWRITE CONSP-OF-NTH-WHEN-ATOM-LISTP))
 (26 13
     (:REWRITE CHARACTER-LISTP-OF-CDR-WHEN-CHARACTER-LISTP))
 (25 5 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (24 24
     (:TYPE-PRESCRIPTION FGL::FGL-FUNCTION-MODE-ALIST-P))
 (24 12
     (:REWRITE FGL::FGL-FUNCTION-MODE-ALIST-P-WHEN-NOT-CONSP))
 (24 12 (:REWRITE DEFAULT-+-2))
 (22 22 (:TYPE-PRESCRIPTION SET::EMPTY-TYPE))
 (22 22
     (:TYPE-PRESCRIPTION STR::DIGIT-LISTP))
 (22 22 (:REWRITE SET::IN-SET))
 (22 22
     (:REWRITE CHARACTER-LISTP-WHEN-NOT-CONSP))
 (21 21
     (:TYPE-PRESCRIPTION FGL::RETURN-TYPE-OF-FGL-OBJECT-BFRLIST.BFRLIST))
 (21 3
     (:REWRITE AIGNET::NATP-OF-NTH-WHEN-POS-LIST-P))
 (20 8
     (:REWRITE TRUE-LIST-LISTP-WHEN-NOT-CONSP))
 (20 8
     (:REWRITE FGL::FGL-OBJECT-BINDINGS-P-WHEN-NOT-CONSP))
 (20 5
     (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-NOT-CONSP))
 (19 19
     (:REWRITE AIGNET::VALS-EQUIV-UNDER-MASKS-NECC))
 (19 19
     (:REWRITE FGL::TERMP-IMPLIES-PSEUDO-TERMP))
 (19 19 (:REWRITE NTH-WHEN-PREFIXP))
 (18 18
     (:TYPE-PRESCRIPTION FGL::FGL-OBJECT-BINDINGS-BFRLIST))
 (18 18 (:TYPE-PRESCRIPTION BOOLEANP))
 (17 17
     (:REWRITE FGL::LOGICMAN->BFRSTATE-UPDATER-INDEPENDENCE))
 (17 17
     (:REWRITE FGL::INTERP-ST->LOGICMAN-OF-UPDATE))
 (17 17
     (:REWRITE FGL::BFR-LISTP-WHEN-LOGICMAN-EXTENSION))
 (17 17
     (:REWRITE FGL::BFR-LISTP-WHEN-BFRSTATE>=))
 (17 17
     (:REWRITE FGL::BFR-LISTP$-OF-INTERP-ST->LOGICMAN-EXTENSION))
 (17 17
     (:REWRITE FGL::BFR-LISTP$-OF-BFRSTATE-FIX-BFRSTATE-NORMALIZE-CONST))
 (16
  16
  (:REWRITE
   FGL::FGL-OBJECT-BINDINGS-P-WHEN-MEMBER-EQUAL-OF-FGL-OBJECT-BINDINGSLIST-P))
 (16 8
     (:REWRITE BOOLEANP-OF-CAR-WHEN-BOOLEAN-LISTP))
 (16 4
     (:REWRITE CMR::PSEUDO-FNSYM-P-OF-CAR-WHEN-EQUIV-CONTEXTSP))
 (16 4 (:REWRITE ATOM-LISTP-WHEN-NOT-CONSP))
 (15 15
     (:REWRITE TERMP-IMPLIES-PSEUDO-TERMP))
 (14 14
     (:REWRITE FGL::FGL-OBJECT-P-WHEN-FGL-BFR-OBJECT-P))
 (12 12 (:REWRITE DEFAULT-+-1))
 (12 6 (:LINEAR LRAT::NTH-N59-LISTP))
 (12 6 (:LINEAR LRAT::NTH-I60-LISTP))
 (12 3
     (:REWRITE AIGNET::POS-LIST-P-WHEN-NOT-CONSP))
 (10 10 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (10 10
     (:TYPE-PRESCRIPTION FGL::FGL-OBJECTLIST-P))
 (10 10
     (:REWRITE FGL::INTERP-ST-BFRS-OK-UPDATER-INDEPENDENCE))
 (10 5 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (9
  9
  (:REWRITE FGL::FGL-OBJECT-KIND$INLINE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (9 9
    (:REWRITE FGL::FGL-OBJECT-BFRLIST-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (8 8
    (:TYPE-PRESCRIPTION CMR::EQUIV-CONTEXTSP))
 (8 8 (:TYPE-PRESCRIPTION BOOLEAN-LISTP))
 (8
  8
  (:REWRITE
   FGL::FGL-OBJECT-BINDINGS-BFRLIST-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (8 8
    (:REWRITE ATOM-LISTP-WHEN-SUBSETP-EQUAL))
 (8 4
    (:REWRITE TRUE-LIST-LISTP-OF-CDR-WHEN-TRUE-LIST-LISTP))
 (8 2
    (:REWRITE FGL::OBJ-ALIST-P-WHEN-NOT-CONSP))
 (8 2
    (:REWRITE FGL::MAJOR-STACK-P-WHEN-NOT-CONSP))
 (8 2
    (:REWRITE FGL::CGRAPH-ALIST-P-WHEN-NOT-CONSP))
 (6 6
    (:TYPE-PRESCRIPTION AIGNET::POS-LIST-P))
 (6 6 (:REWRITE SUBSETP-TRANS2))
 (6 6 (:REWRITE SUBSETP-TRANS))
 (5 5
    (:REWRITE FGL::FGL-OBJECTLIST-P-WHEN-FGL-BFR-OBJECTLIST-P))
 (4 4 (:REWRITE FN-CHECK-DEF-NOT-QUOTE))
 (4 4
    (:REWRITE FGL::FGL-BFR-OBJECT-P-WHEN-LOGICMAN-EXTENSION))
 (4 4
    (:REWRITE CMR::EQUIV-CONTEXTSP-WHEN-NOT-CONSP))
 (4
  4
  (:REWRITE
       AIGNET::CDR-OF-NODE-LIST-FIX-X-NORMALIZE-CONST-UNDER-NODE-LIST-EQUIV))
 (3 3
    (:REWRITE FGL::STACK$A-FRAMES-OF-MAJOR-STACK-FIX-X-NORMALIZE-CONST))
 (3 3
    (:REWRITE FGL::INTERP-ST->STACK-OF-UPDATE))
 (1 1
    (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST)))
(FGL::INTERP-ST-GET-OF-TOP-FANCY-EV-PRIMITIVES
 (4368 336
       (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (3865 1162
       (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (3360 336
       (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (1680 336 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (1386 462
       (:REWRITE FGL::INTERP-ST-FIELD-FIX-IDEMPOTENT))
 (1008 1008
       (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (1008 1008 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (924 924
      (:TYPE-PRESCRIPTION FGL::INTERP-ST-FIELD-P))
 (826 826 (:TYPE-PRESCRIPTION BOOLEANP))
 (674 674
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (672 672
      (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (672 336 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (672 336 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (670
    670
    (:REWRITE FGL::INTERP-ST-GET-OF-INTERP-ST-FIELD-FIX-KEY-NORMALIZE-CONST))
 (479 479 (:REWRITE SUBSETP-MEMBER . 2))
 (479 479 (:REWRITE SUBSETP-MEMBER . 1))
 (479 479
      (:REWRITE SV::REWRITE-MEMBER-OF-APPEND-UNDER-SET-EQUIV))
 (351 351 (:REWRITE SUBSETP-MEMBER . 4))
 (351 351 (:REWRITE SUBSETP-MEMBER . 3))
 (337 337
      (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (336 336
      (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (176 176 (:REWRITE DEFAULT-CAR))
 (59 59
     (:REWRITE AIGNET::VALS-EQUIV-UNDER-MASKS-NECC))
 (59 59 (:REWRITE NTH-WHEN-PREFIXP))
 (34 34 (:REWRITE DEFAULT-CDR))
 (19
    19
    (:REWRITE
         FGL::INTERP-ST-COUNTEREX-VALUE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (19
  19
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS/PRINT-ERRORS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (19
  19
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (18
    18
    (:REWRITE AIGNET::CAR-OF-POS-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (18 18
     (:REWRITE CAR-OF-NAT-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (18 18
     (:REWRITE CAR-OF-INTEGER-LIST-FIX-X-NORMALIZE-CONST-UNDER-INT-EQUIV))
 (18
  18
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECT-BINDINGSLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-BINDINGS-EQUIV))
 (9
  9
  (:REWRITE
    FGL::CAR-OF-FGL-OBJECTLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-EQUIV))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-PSEUDO-TERM-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-NFIX-RECLIMIT-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::INTERP-ST->USER-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->TRACE-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->RECLIMIT-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->NEXT-FGARRAY-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->FLAGS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->ERRMSG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->EQUIV-CONTEXTS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-STACK-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-INFO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONSTRAINT-DB-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONFIG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-MEMO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-INDEX-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->BACKCHAIN-LIMIT-OF-UPDATE)))
(FGL::INTERP-ST-BFRS-OK-OF-TOP-FANCY-EV-PRIMITIVES
 (520 40
      (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (480 80 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (400 40
      (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (364
    364
    (:REWRITE FGL::INTERP-ST-GET-OF-INTERP-ST-FIELD-FIX-KEY-NORMALIZE-CONST))
 (200 40 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (160 160 (:TYPE-PRESCRIPTION BOOLEANP))
 (130 130
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (120 120 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (120 120 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (80 80 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (80 40 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (80 40 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (65 65
     (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (40 40
     (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (40 40 (:REWRITE DEFAULT-CAR))
 (35 35
     (:REWRITE AIGNET::VALS-EQUIV-UNDER-MASKS-NECC))
 (35 35 (:REWRITE NTH-WHEN-PREFIXP))
 (10 10 (:REWRITE DEFAULT-CDR))
 (3 3
    (:REWRITE
         FGL::INTERP-ST-COUNTEREX-VALUE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS/PRINT-ERRORS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE AIGNET::CAR-OF-POS-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (2 2
    (:REWRITE CAR-OF-NAT-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (2 2
    (:REWRITE CAR-OF-INTEGER-LIST-FIX-X-NORMALIZE-CONST-UNDER-INT-EQUIV))
 (2
  2
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECT-BINDINGSLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-BINDINGS-EQUIV))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-PSEUDO-TERM-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-NFIX-RECLIMIT-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::INTERP-ST->USER-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->TRACE-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->RECLIMIT-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->NEXT-FGARRAY-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->FLAGS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->ERRMSG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->EQUIV-CONTEXTS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-STACK-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-INFO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONSTRAINT-DB-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONFIG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-MEMO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-INDEX-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->BACKCHAIN-LIMIT-OF-UPDATE))
 (1
  1
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECTLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-EQUIV)))
(FGL::ERRMSG-OF-TOP-FANCY-EV-PRIMITIVES
 (520 40
      (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (480 80 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (400 40
      (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (200 40 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (160 160 (:TYPE-PRESCRIPTION BOOLEANP))
 (130 130
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (120 120 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (120 120 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (80 80 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (80 40 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (80 40 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (70
    70
    (:REWRITE FGL::INTERP-ST-GET-OF-INTERP-ST-FIELD-FIX-KEY-NORMALIZE-CONST))
 (65 65
     (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (40 40
     (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (40 40 (:REWRITE DEFAULT-CAR))
 (35 35
     (:REWRITE AIGNET::VALS-EQUIV-UNDER-MASKS-NECC))
 (35 35 (:REWRITE NTH-WHEN-PREFIXP))
 (10 10 (:REWRITE DEFAULT-CDR))
 (3 3
    (:REWRITE
         FGL::INTERP-ST-COUNTEREX-VALUE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS/PRINT-ERRORS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE AIGNET::CAR-OF-POS-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (2 2
    (:REWRITE CAR-OF-NAT-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (2 2
    (:REWRITE CAR-OF-INTEGER-LIST-FIX-X-NORMALIZE-CONST-UNDER-INT-EQUIV))
 (2
  2
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECT-BINDINGSLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-BINDINGS-EQUIV))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-PSEUDO-TERM-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-NFIX-RECLIMIT-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::INTERP-ST->USER-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->TRACE-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->RECLIMIT-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->NEXT-FGARRAY-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->FLAGS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->EQUIV-CONTEXTS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-STACK-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-INFO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONSTRAINT-DB-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONFIG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-MEMO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-INDEX-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->BACKCHAIN-LIMIT-OF-UPDATE))
 (1
  1
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECTLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-EQUIV)))
(FGL::INTERP-ST->ERRMSG-EQUAL-UNREACHABLE-OF-TOP-FANCY-EV-PRIMITIVES
 (609 123
      (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (520 40
      (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (400 40
      (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (246 246 (:TYPE-PRESCRIPTION BOOLEANP))
 (200 40 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (130 130
      (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (120 120 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (120 120 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (80 80 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (80 40 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (80 40 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (78
    78
    (:REWRITE FGL::INTERP-ST-GET-OF-INTERP-ST-FIELD-FIX-KEY-NORMALIZE-CONST))
 (65 65
     (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (40 40
     (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (40 40 (:REWRITE DEFAULT-CAR))
 (35 35
     (:REWRITE AIGNET::VALS-EQUIV-UNDER-MASKS-NECC))
 (35 35 (:REWRITE NTH-WHEN-PREFIXP))
 (10 10 (:REWRITE DEFAULT-CDR))
 (4 2
    (:REWRITE FGL::INTERP-ST-GET-OF-INTERP-ST-RUN-CTREX))
 (4 2
    (:REWRITE FGL::INTERP-ST-GET-OF-FGL-INTERP-STORE-DEBUG-INFO))
 (4 2
    (:REWRITE FGL::FGL-INTERP-STORE-DEBUG-INFO-PRESERVES-ERROR))
 (4 2
    (:REWRITE FGL::ERRMSG-OF-INTERP-ST-RUN-CTREX))
 (3 3
    (:REWRITE
         FGL::INTERP-ST-COUNTEREX-VALUE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS/PRINT-ERRORS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (2 2
    (:REWRITE AIGNET::CAR-OF-POS-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (2 2
    (:REWRITE CAR-OF-NAT-LIST-FIX-X-NORMALIZE-CONST-UNDER-NAT-EQUIV))
 (2 2
    (:REWRITE CAR-OF-INTEGER-LIST-FIX-X-NORMALIZE-CONST-UNDER-INT-EQUIV))
 (2
  2
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECT-BINDINGSLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-BINDINGS-EQUIV))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-PSEUDO-TERM-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-NFIX-RECLIMIT-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::INTERP-ST->USER-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->TRACE-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->RECLIMIT-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->NEXT-FGARRAY-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->FLAGS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->EQUIV-CONTEXTS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-STACK-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-INFO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONSTRAINT-DB-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONFIG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-MEMO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-INDEX-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->BACKCHAIN-LIMIT-OF-UPDATE))
 (1
  1
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECTLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-EQUIV)))
(FGL::W-STATE-OF-TOP-FANCY-EV-PRIMITIVES
 (321 54 (:REWRITE EQUAL-OF-BOOLEANS-REWRITE))
 (169 13
      (:REWRITE PSEUDO-FNSYM-FIX-WHEN-PSEUDO-FNSYM-P))
 (130 13
      (:REWRITE PSEUDO-FN-P-WHEN-NOT-CONSP))
 (108 108 (:TYPE-PRESCRIPTION BOOLEANP))
 (82 82
     (:REWRITE CONSP-WHEN-MEMBER-EQUAL-OF-ATOM-LISTP))
 (65 13 (:REWRITE PSEUDO-FN-P-WHEN-LAMBDA))
 (41 41
     (:REWRITE CONSP-OF-NODE-LIST-FIX-X-NORMALIZE-CONST))
 (39 39 (:TYPE-PRESCRIPTION PSEUDO-FNSYM-P))
 (39 39 (:TYPE-PRESCRIPTION PSEUDO-FN-P))
 (31 31
     (:REWRITE AIGNET::VALS-EQUIV-UNDER-MASKS-NECC))
 (31 31 (:REWRITE NTH-WHEN-PREFIXP))
 (28 28 (:REWRITE DEFAULT-CAR))
 (26 26 (:TYPE-PRESCRIPTION PSEUDO-LAMBDA-P))
 (26 13 (:REWRITE PSEUDO-FN-P-WHEN-FNSYM))
 (26 13 (:REWRITE PSEUDO-FN-P-WHEN-CONSP))
 (13 13
     (:REWRITE PSEUDO-FNSYM-FIX-OF-PSEUDO-FNSYM-FIX-X-NORMALIZE-CONST))
 (8 8 (:REWRITE DEFAULT-CDR))
 (3 3
    (:REWRITE
         FGL::INTERP-ST-COUNTEREX-VALUE-OF-FGL-OBJECT-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS/PRINT-ERRORS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (3
  3
  (:REWRITE
   FGL::INTERP-ST-COUNTEREX-BINDINGS-OF-FGL-OBJECT-BINDINGS-FIX-X-NORMALIZE-CONST))
 (2
  2
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECT-BINDINGSLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-BINDINGS-EQUIV))
 (1
  1
  (:REWRITE
   FGL::UPDATE-INTERP-ST->NEXT-FGARRAY$INLINE-OF-NFIX-NEXT-FGARRAY-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
   FGL::UPDATE-INTERP-ST->FLAGS$INLINE-OF-INTERP-FLAGS-FIX-FLAGS-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
   FGL::UPDATE-INTERP-ST->CONFIG$INLINE-OF-FGL-CONFIG-FIX-CONFIG-NORMALIZE-CONST))
 (1
  1
  (:REWRITE
   FGL::UPDATE-INTERP-ST->CGRAPH-INDEX$INLINE-OF-NFIX-CGRAPH-INDEX-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-PSEUDO-TERM-FIX-X-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::MAGITASTIC-EV-OF-NFIX-RECLIMIT-NORMALIZE-CONST))
 (1 1
    (:REWRITE FGL::INTERP-ST->USER-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->TRACE-SCRATCH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->RECLIMIT-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->NEXT-FGARRAY-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->FLAGS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->ERRMSG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->EQUIV-CONTEXTS-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-STACK-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->DEBUG-INFO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONSTRAINT-DB-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CONFIG-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-MEMO-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->CGRAPH-INDEX-OF-UPDATE))
 (1 1
    (:REWRITE FGL::INTERP-ST->BACKCHAIN-LIMIT-OF-UPDATE))
 (1
  1
  (:REWRITE
   FGL::CAR-OF-FGL-OBJECTLIST-FIX-X-NORMALIZE-CONST-UNDER-FGL-OBJECT-EQUIV)))
