include ../../Makefile-generic
ACL2 = ../../../saved_acl2

halt-flg.cert: halt-flg.lisp
# halt-flg.cert: $(ACL2_SYSTEM_BOOKS)/misc/defpun.cert

memory-clearing.cert: memory-clearing.lisp
# memory-clearing.cert: $(ACL2_SYSTEM_BOOKS)/misc/defpun.cert

realistic.cert: realistic.lisp
# realistic.cert: $(ACL2_SYSTEM_BOOKS)/misc/records.cert
# realistic.cert: $(ACL2_SYSTEM_BOOKS)/misc/defpun.cert
