include ../../../../Makefile-generic


# BOOKS = base arith basic bits log float reps round \
#         rtl rtlarr bvecp-raw-helpers bvecp-helpers simple-loop-helpers \
#         simplify-model-helpers util add top rom-helpers clocks package-defs \
#         openers mult 
 
# Dependencies:
-include Makefile-deps
