(SBYTE2-LISTP)
(STD::DEFLIST-LOCAL-BOOLEANP-ELEMENT-THM)
(STD::DEFLIST-LOCAL-ELEMENTP-OF-NIL-THM)
(SBYTE2-LISTP-OF-CONS)
(SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP)
(SBYTE2-LISTP-WHEN-NOT-CONSP)
(SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP)
(TRUE-LISTP-WHEN-SBYTE2-LISTP)
(SBYTE2-LISTP-OF-LIST-FIX)
(SBYTE2-LISTP-OF-SFIX)
(SBYTE2-LISTP-OF-INSERT)
(SBYTE2-LISTP-OF-DELETE)
(SBYTE2-LISTP-OF-MERGESORT)
(SBYTE2-LISTP-OF-UNION)
(SBYTE2-LISTP-OF-INTERSECT-1)
(SBYTE2-LISTP-OF-INTERSECT-2)
(SBYTE2-LISTP-OF-DIFFERENCE)
(SBYTE2-LISTP-OF-DUPLICATED-MEMBERS)
(SBYTE2-LISTP-OF-REV)
(SBYTE2-LISTP-OF-APPEND)
(SBYTE2-LISTP-OF-RCONS)
(SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP)
(SBYTE2-LISTP-WHEN-SUBSETP-EQUAL)
(SBYTE2-LISTP-OF-SET-DIFFERENCE-EQUAL)
(SBYTE2-LISTP-OF-INTERSECTION-EQUAL-1)
(SBYTE2-LISTP-OF-INTERSECTION-EQUAL-2)
(SBYTE2-LISTP-OF-UNION-EQUAL)
(SBYTE2-LISTP-OF-TAKE)
(SBYTE2-LISTP-OF-REPEAT)
(SBYTE2P-OF-NTH-WHEN-SBYTE2-LISTP)
(SBYTE2-LISTP-OF-UPDATE-NTH)
(SBYTE2-LISTP-OF-BUTLAST)
(SBYTE2-LISTP-OF-NTHCDR)
(SBYTE2-LISTP-OF-LAST)
(SBYTE2-LISTP-OF-REMOVE)
(SBYTE2-LISTP-OF-REVAPPEND)
(SBYTE2-LIST-FIX$INLINE)
(SBYTE2-LISTP-OF-SBYTE2-LIST-FIX
     (30 1 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
     (22 2
         (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
     (18 10
         (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
     (15 1 (:DEFINITION SBYTE2-LISTP))
     (12 6
         (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
     (9 5
        (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
     (8 8 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (4 4 (:TYPE-PRESCRIPTION SBYTE2P))
     (4 4 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (2 2
        (:REWRITE FTY::OPEN-MEMBER-EQUAL-ON-LIST-OF-TAGS))
     (2 1
        (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP)))
(SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP
     (32 4
         (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
     (28 24
         (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
     (13 3
         (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
     (9 6
        (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
     (4 4 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (2 2 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (1 1
        (:REWRITE FTY::OPEN-MEMBER-EQUAL-ON-LIST-OF-TAGS)))
(SBYTE2-LIST-FIX$INLINE
     (8 8
        (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
     (6 1
        (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
     (6 1
        (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
     (4 4
        (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP)))
(FTY::TMP-DEFFIXTYPE-IDEMPOTENT
     (2 2
        (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1
        (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP)))
(SBYTE2-LIST-EQUIV$INLINE)
(SBYTE2-LIST-EQUIV-IS-AN-EQUIVALENCE)
(SBYTE2-LIST-EQUIV-IMPLIES-EQUAL-SBYTE2-LIST-FIX-1)
(SBYTE2-LIST-FIX-UNDER-SBYTE2-LIST-EQUIV)
(EQUAL-OF-SBYTE2-LIST-FIX-1-FORWARD-TO-SBYTE2-LIST-EQUIV)
(EQUAL-OF-SBYTE2-LIST-FIX-2-FORWARD-TO-SBYTE2-LIST-EQUIV)
(SBYTE2-LIST-EQUIV-OF-SBYTE2-LIST-FIX-1-FORWARD)
(SBYTE2-LIST-EQUIV-OF-SBYTE2-LIST-FIX-2-FORWARD)
(CAR-OF-SBYTE2-LIST-FIX-X-UNDER-SBYTE2-EQUIV
     (33 3 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
     (18 3
         (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
     (18 2
         (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
     (12 12 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
     (12 12
         (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
     (6 6 (:TYPE-PRESCRIPTION SBYTE2P))
     (6 6
        (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
     (6 6
        (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
     (6 1
        (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
     (3 3
        (:TYPE-PRESCRIPTION SBYTE2-LIST-FIX$INLINE)))
(CAR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-EQUIV)
(CAR-SBYTE2-LIST-EQUIV-CONGRUENCE-ON-X-UNDER-SBYTE2-EQUIV)
(CDR-OF-SBYTE2-LIST-FIX-X-UNDER-SBYTE2-LIST-EQUIV
     (41 3
         (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
     (22 2 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
     (20 20
         (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
     (12 2
         (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
     (4 4 (:TYPE-PRESCRIPTION SBYTE2P))
     (4 4
        (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP)))
(CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)
(CDR-SBYTE2-LIST-EQUIV-CONGRUENCE-ON-X-UNDER-SBYTE2-LIST-EQUIV)
(CONS-OF-SBYTE2-FIX-X-UNDER-SBYTE2-LIST-EQUIV
  (34 4
      (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
  (17 2 (:REWRITE SBYTE2-LISTP-OF-CONS))
  (10 10
      (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
  (8 8
     (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
  (6 6 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
  (5 5
     (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
  (2 2
     (:REWRITE
          CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)))
(CONS-OF-SBYTE2-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)
(CONS-SBYTE2-EQUIV-CONGRUENCE-ON-X-UNDER-SBYTE2-LIST-EQUIV)
(CONS-OF-SBYTE2-LIST-FIX-Y-UNDER-SBYTE2-LIST-EQUIV
  (20 2 (:REWRITE SBYTE2-LISTP-OF-CONS))
  (8 8 (:TYPE-PRESCRIPTION SBYTE2P))
  (8 8
     (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
  (8 8
     (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
  (6 2 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
  (5 4
     (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
  (2 2
     (:REWRITE CONS-OF-SBYTE2-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
  (2 2
     (:REWRITE
          CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)))
(CONS-OF-SBYTE2-LIST-FIX-Y-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)
(CONS-SBYTE2-LIST-EQUIV-CONGRUENCE-ON-Y-UNDER-SBYTE2-LIST-EQUIV)
(CONSP-OF-SBYTE2-LIST-FIX
  (18 2
      (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
  (11 1 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
  (8 8 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
  (8 8
     (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
  (6 1
     (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
  (6 1
     (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
  (4 4
     (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
  (2 2 (:TYPE-PRESCRIPTION SBYTE2P))
  (2 2
     (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
  (1 1
     (:REWRITE
          CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)))
(SBYTE2-LIST-FIX-UNDER-IFF
  (18 2
      (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
  (11 1 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
  (8 8 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
  (8 8
     (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
  (6 1
     (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
  (6 1
     (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
  (4 4
     (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
  (2 2 (:TYPE-PRESCRIPTION SBYTE2P))
  (2 2
     (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
  (1 1
     (:REWRITE
          CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)))
(SBYTE2-LIST-FIX-OF-CONS
  (21 3
      (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
  (9 1 (:REWRITE SBYTE2-LISTP-OF-CONS))
  (6 6
     (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
  (6 2 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
  (4 4 (:TYPE-PRESCRIPTION SBYTE2P))
  (4 4 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
  (4 4
     (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
  (3 3
     (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
  (1 1
     (:REWRITE
          CONS-OF-SBYTE2-LIST-FIX-Y-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
  (1 1
     (:REWRITE CONS-OF-SBYTE2-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
  (1 1
     (:REWRITE
          CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)))
(LEN-OF-SBYTE2-LIST-FIX
   (35 4
       (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
   (14 14
       (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
   (13 13 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
   (12 2
       (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
   (11 1 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
   (7 7
      (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
   (6 1
      (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
   (2 2 (:TYPE-PRESCRIPTION SBYTE2P))
   (2 2
      (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
   (2 2
      (:REWRITE
           CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
   (1 1 (:REWRITE FTY::EQUAL-OF-LEN)))
(SBYTE2-LIST-FIX-OF-APPEND
  (114 10
       (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
  (58 2 (:REWRITE SBYTE2-LISTP-OF-APPEND))
  (40 36
      (:REWRITE SBYTE2-LISTP-WHEN-SUBSETP-EQUAL))
  (29 29 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
  (24 2 (:REWRITE SBYTE2-LISTP-OF-LIST-FIX))
  (22 16
      (:REWRITE SBYTE2-LISTP-WHEN-NOT-CONSP))
  (14 4
      (:REWRITE SBYTE2-LISTP-OF-CDR-WHEN-SBYTE2-LISTP))
  (12 12 (:TYPE-PRESCRIPTION TRUE-LIST-FIX))
  (12 2 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
  (6 1
     (:REWRITE SBYTE2P-OF-CAR-WHEN-SBYTE2-LISTP))
  (4 4 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
  (2 2 (:TYPE-PRESCRIPTION SBYTE2P))
  (2 2
     (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
  (2 2
     (:REWRITE
          CDR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
  (1 1
     (:REWRITE
          CONS-OF-SBYTE2-LIST-FIX-Y-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
  (1 1
     (:REWRITE CONS-OF-SBYTE2-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
  (1 1
     (:REWRITE CAR-OF-SBYTE2-LIST-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-EQUIV)))
(SBYTE2-LIST-FIX-OF-REPEAT
 (20 2
     (:REWRITE SBYTE2-LIST-FIX-WHEN-SBYTE2-LISTP))
 (16 4 (:REWRITE SBYTE2-FIX-WHEN-SBYTE2P))
 (12 2 (:REWRITE SBYTE2-LISTP-OF-REPEAT))
 (10 10 (:TYPE-PRESCRIPTION SBYTE2P))
 (10 10
     (:REWRITE SBYTE2P-WHEN-MEMBER-EQUAL-OF-SBYTE2-LISTP))
 (2 2 (:TYPE-PRESCRIPTION SBYTE2-LISTP))
 (1 1
    (:REWRITE-QUOTED-CONSTANT SBYTE2-LIST-FIX-UNDER-SBYTE2-LIST-EQUIV))
 (1 1
    (:REWRITE
         CONS-OF-SBYTE2-LIST-FIX-Y-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV))
 (1 1
    (:REWRITE CONS-OF-SBYTE2-FIX-X-NORMALIZE-CONST-UNDER-SBYTE2-LIST-EQUIV)))
(SBYTE2-LISTP-FORWARD-SIGNED-BYTE-LISTP)
(SBYTE2-LISTP-REWRITE-SIGNED-BYTE-LISTP)
(SIGNED-BYTE-LISTP-REWRITE-SBYTE2-LISTP)
(TRUE-LISTP-WHEN-SBYTE2-LISTP-REWRITE (2 2 (:DEFINITION TRUE-LISTP)))
(SBYTE2-LIST-FIX-OF-TAKE)
(SBYTE2-LIST-FIX-OF-RCONS)
