(UBYTE1-LISTP)
(STD::DEFLIST-LOCAL-BOOLEANP-ELEMENT-THM)
(STD::DEFLIST-LOCAL-ELEMENTP-OF-NIL-THM)
(UBYTE1-LISTP-OF-CONS)
(UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP)
(UBYTE1-LISTP-WHEN-NOT-CONSP)
(UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP)
(TRUE-LISTP-WHEN-UBYTE1-LISTP)
(UBYTE1-LISTP-OF-LIST-FIX)
(UBYTE1-LISTP-OF-SFIX)
(UBYTE1-LISTP-OF-INSERT)
(UBYTE1-LISTP-OF-DELETE)
(UBYTE1-LISTP-OF-MERGESORT)
(UBYTE1-LISTP-OF-UNION)
(UBYTE1-LISTP-OF-INTERSECT-1)
(UBYTE1-LISTP-OF-INTERSECT-2)
(UBYTE1-LISTP-OF-DIFFERENCE)
(UBYTE1-LISTP-OF-DUPLICATED-MEMBERS)
(UBYTE1-LISTP-OF-REV)
(UBYTE1-LISTP-OF-APPEND)
(UBYTE1-LISTP-OF-RCONS)
(UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP)
(UBYTE1-LISTP-WHEN-SUBSETP-EQUAL)
(UBYTE1-LISTP-OF-SET-DIFFERENCE-EQUAL)
(UBYTE1-LISTP-OF-INTERSECTION-EQUAL-1)
(UBYTE1-LISTP-OF-INTERSECTION-EQUAL-2)
(UBYTE1-LISTP-OF-UNION-EQUAL)
(UBYTE1-LISTP-OF-TAKE)
(UBYTE1-LISTP-OF-REPEAT)
(UBYTE1P-OF-NTH-WHEN-UBYTE1-LISTP)
(UBYTE1-LISTP-OF-UPDATE-NTH)
(UBYTE1-LISTP-OF-BUTLAST)
(UBYTE1-LISTP-OF-NTHCDR)
(UBYTE1-LISTP-OF-LAST)
(UBYTE1-LISTP-OF-REMOVE)
(UBYTE1-LISTP-OF-REVAPPEND)
(UBYTE1-LIST-FIX$INLINE)
(UBYTE1-LISTP-OF-UBYTE1-LIST-FIX
     (30 1 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
     (22 2
         (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
     (18 10
         (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
     (15 1 (:DEFINITION UBYTE1-LISTP))
     (12 6
         (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
     (9 5
        (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
     (8 8 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (4 4 (:TYPE-PRESCRIPTION UBYTE1P))
     (4 4 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (2 2
        (:REWRITE FTY::OPEN-MEMBER-EQUAL-ON-LIST-OF-TAGS))
     (2 1
        (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP)))
(UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP
     (32 4
         (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
     (28 24
         (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
     (13 3
         (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
     (9 6
        (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
     (4 4 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
     (2 2 (:TYPE-PRESCRIPTION MEMBER-EQUAL))
     (1 1
        (:REWRITE FTY::OPEN-MEMBER-EQUAL-ON-LIST-OF-TAGS)))
(UBYTE1-LIST-FIX$INLINE
     (8 8
        (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
     (6 1
        (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
     (6 1
        (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
     (4 4
        (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
     (2 2
        (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP)))
(FTY::TMP-DEFFIXTYPE-IDEMPOTENT
     (2 2
        (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
     (1 1
        (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP)))
(UBYTE1-LIST-EQUIV$INLINE)
(UBYTE1-LIST-EQUIV-IS-AN-EQUIVALENCE)
(UBYTE1-LIST-EQUIV-IMPLIES-EQUAL-UBYTE1-LIST-FIX-1)
(UBYTE1-LIST-FIX-UNDER-UBYTE1-LIST-EQUIV)
(EQUAL-OF-UBYTE1-LIST-FIX-1-FORWARD-TO-UBYTE1-LIST-EQUIV)
(EQUAL-OF-UBYTE1-LIST-FIX-2-FORWARD-TO-UBYTE1-LIST-EQUIV)
(UBYTE1-LIST-EQUIV-OF-UBYTE1-LIST-FIX-1-FORWARD)
(UBYTE1-LIST-EQUIV-OF-UBYTE1-LIST-FIX-2-FORWARD)
(CAR-OF-UBYTE1-LIST-FIX-X-UNDER-UBYTE1-EQUIV
     (33 3 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
     (18 3
         (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
     (18 2
         (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
     (12 12 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
     (12 12
         (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
     (6 6 (:TYPE-PRESCRIPTION UBYTE1P))
     (6 6
        (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
     (6 6
        (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
     (6 1
        (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
     (3 3
        (:TYPE-PRESCRIPTION UBYTE1-LIST-FIX$INLINE)))
(CAR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-EQUIV)
(CAR-UBYTE1-LIST-EQUIV-CONGRUENCE-ON-X-UNDER-UBYTE1-EQUIV)
(CDR-OF-UBYTE1-LIST-FIX-X-UNDER-UBYTE1-LIST-EQUIV
     (41 3
         (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
     (22 2 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
     (20 20
         (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
     (12 2
         (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
     (4 4 (:TYPE-PRESCRIPTION UBYTE1P))
     (4 4
        (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP)))
(CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)
(CDR-UBYTE1-LIST-EQUIV-CONGRUENCE-ON-X-UNDER-UBYTE1-LIST-EQUIV)
(CONS-OF-UBYTE1-FIX-X-UNDER-UBYTE1-LIST-EQUIV
  (34 4
      (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
  (17 2 (:REWRITE UBYTE1-LISTP-OF-CONS))
  (10 10
      (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
  (8 8
     (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
  (6 6 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
  (5 5
     (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
  (2 2
     (:REWRITE
          CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)))
(CONS-OF-UBYTE1-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)
(CONS-UBYTE1-EQUIV-CONGRUENCE-ON-X-UNDER-UBYTE1-LIST-EQUIV)
(CONS-OF-UBYTE1-LIST-FIX-Y-UNDER-UBYTE1-LIST-EQUIV
  (20 2 (:REWRITE UBYTE1-LISTP-OF-CONS))
  (8 8 (:TYPE-PRESCRIPTION UBYTE1P))
  (8 8
     (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
  (8 8
     (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
  (6 2 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
  (5 4
     (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
  (2 2
     (:REWRITE CONS-OF-UBYTE1-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
  (2 2
     (:REWRITE
          CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)))
(CONS-OF-UBYTE1-LIST-FIX-Y-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)
(CONS-UBYTE1-LIST-EQUIV-CONGRUENCE-ON-Y-UNDER-UBYTE1-LIST-EQUIV)
(CONSP-OF-UBYTE1-LIST-FIX
  (18 2
      (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
  (11 1 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
  (8 8 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
  (8 8
     (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
  (6 1
     (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
  (6 1
     (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
  (4 4
     (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
  (2 2 (:TYPE-PRESCRIPTION UBYTE1P))
  (2 2
     (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
  (1 1
     (:REWRITE
          CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)))
(UBYTE1-LIST-FIX-UNDER-IFF
  (18 2
      (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
  (11 1 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
  (8 8 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
  (8 8
     (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
  (6 1
     (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
  (6 1
     (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
  (4 4
     (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
  (2 2 (:TYPE-PRESCRIPTION UBYTE1P))
  (2 2
     (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
  (1 1
     (:REWRITE
          CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)))
(UBYTE1-LIST-FIX-OF-CONS
  (21 3
      (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
  (9 1 (:REWRITE UBYTE1-LISTP-OF-CONS))
  (6 6
     (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
  (6 2 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
  (4 4 (:TYPE-PRESCRIPTION UBYTE1P))
  (4 4 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
  (4 4
     (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
  (3 3
     (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
  (1 1
     (:REWRITE
          CONS-OF-UBYTE1-LIST-FIX-Y-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
  (1 1
     (:REWRITE CONS-OF-UBYTE1-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
  (1 1
     (:REWRITE
          CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)))
(LEN-OF-UBYTE1-LIST-FIX
   (35 4
       (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
   (14 14
       (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
   (13 13 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
   (12 2
       (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
   (11 1 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
   (7 7
      (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
   (6 1
      (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
   (2 2 (:TYPE-PRESCRIPTION UBYTE1P))
   (2 2
      (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
   (2 2
      (:REWRITE
           CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
   (1 1 (:REWRITE FTY::EQUAL-OF-LEN)))
(UBYTE1-LIST-FIX-OF-APPEND
  (114 10
       (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
  (58 2 (:REWRITE UBYTE1-LISTP-OF-APPEND))
  (40 36
      (:REWRITE UBYTE1-LISTP-WHEN-SUBSETP-EQUAL))
  (29 29 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
  (24 2 (:REWRITE UBYTE1-LISTP-OF-LIST-FIX))
  (22 16
      (:REWRITE UBYTE1-LISTP-WHEN-NOT-CONSP))
  (14 4
      (:REWRITE UBYTE1-LISTP-OF-CDR-WHEN-UBYTE1-LISTP))
  (12 12 (:TYPE-PRESCRIPTION TRUE-LIST-FIX))
  (12 2 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
  (6 1
     (:REWRITE UBYTE1P-OF-CAR-WHEN-UBYTE1-LISTP))
  (4 4 (:TYPE-PRESCRIPTION SUBSETP-EQUAL))
  (2 2 (:TYPE-PRESCRIPTION UBYTE1P))
  (2 2
     (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
  (2 2
     (:REWRITE
          CDR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
  (1 1
     (:REWRITE
          CONS-OF-UBYTE1-LIST-FIX-Y-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
  (1 1
     (:REWRITE CONS-OF-UBYTE1-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
  (1 1
     (:REWRITE CAR-OF-UBYTE1-LIST-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-EQUIV)))
(UBYTE1-LIST-FIX-OF-REPEAT
 (20 2
     (:REWRITE UBYTE1-LIST-FIX-WHEN-UBYTE1-LISTP))
 (16 4 (:REWRITE UBYTE1-FIX-WHEN-UBYTE1P))
 (12 2 (:REWRITE UBYTE1-LISTP-OF-REPEAT))
 (10 10 (:TYPE-PRESCRIPTION UBYTE1P))
 (10 10
     (:REWRITE UBYTE1P-WHEN-MEMBER-EQUAL-OF-UBYTE1-LISTP))
 (2 2 (:TYPE-PRESCRIPTION UBYTE1-LISTP))
 (1 1
    (:REWRITE-QUOTED-CONSTANT UBYTE1-LIST-FIX-UNDER-UBYTE1-LIST-EQUIV))
 (1 1
    (:REWRITE
         CONS-OF-UBYTE1-LIST-FIX-Y-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV))
 (1 1
    (:REWRITE CONS-OF-UBYTE1-FIX-X-NORMALIZE-CONST-UNDER-UBYTE1-LIST-EQUIV)))
(UBYTE1-LISTP-FORWARD-UNSIGNED-BYTE-LISTP)
(UBYTE1-LISTP-REWRITE-UNSIGNED-BYTE-LISTP)
(UNSIGNED-BYTE-LISTP-REWRITE-UBYTE1-LISTP)
(TRUE-LISTP-WHEN-UBYTE1-LISTP-REWRITE (2 2 (:DEFINITION TRUE-LISTP)))
(UBYTE1-LIST-FIX-OF-TAKE)
(UBYTE1-LIST-FIX-OF-RCONS)
