ACL2 ?= ../../../saved_acl2
include ../../Makefile-generic

BOOKS = gacc-pkg gacc-exports abstract-gacc addr-range bits mem-fast mem \
	list-ops-common list-ops-fast wrap ram3 ram2b ram2  list-ops ram0 block \
	ram gacc gacc2 gax finite gacc3 top fr-path-connection tr-path-connection

-include Makefile-deps
