include ../../../../../../Makefile-generic

# Pasted in from "make dependencies":

2D-mesh-nodeset.cert: 2D-mesh-nodeset.lisp
2D-mesh-nodeset.cert: ../../generic-modules/GeNoC-nodeset.cert

octagon-nodeset.cert: octagon-nodeset.lisp
octagon-nodeset.cert: ../../generic-modules/GeNoC-nodeset.cert




