include ../../../../Makefile-generic

# Don't alphabetize this list!
# [Matt K.: Not sure why not, or why we even need this list!  So, I'm
# commenting it out.]
#BOOKS = base \
#	add-lib \
#	log bits add 

-include Makefile-deps
