include ../../../../../../../Makefile-generic

# Pasted in from "make dependencies":

xy-routing.cert: xy-routing.lisp
xy-routing.cert: ../../../generic-modules/GeNoC-routing.cert
xy-routing.cert: ../../nodeset/2D-mesh-nodeset.cert
# xy-routing.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/bind-free/top.cert
# xy-routing.cert: $(ACL2_SYSTEM_BOOKS)/arithmetic-3/floor-mod/floor-mod.cert
