(MILAWA::TACTIC.APPLY-STRATEGY-STEP
 (600 20
      (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (480 10
      (:REWRITE MILAWA::ELIM.NAMESP-WHEN-NOT-CONSP))
 (416 8 (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP))
 (408 6
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (396 6
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (300 10
      (:REWRITE MILAWA::SYMBOLP-WHEN-CONSP-CHEAP))
 (288 60
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (140 60
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (140 10
      (:REWRITE MILAWA::SYMBOLP-WHEN-LOGIC.FUNCTION-NAMEP))
 (120 30
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (120 20
      (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (110
   10
   (:REWRITE MILAWA::LOGIC.FUNCTION-NAMEP-WHEN-LOOKUP-IN-LOGIC.ARITY-TABLEP))
 (100 10
      (:REWRITE MILAWA::SYMBOLP-WHEN-LOGIC.VARIABLEP))
 (84 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP))
 (70 70
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (70 70
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (64 64
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (64 64
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (64 64 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (60 60
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (60 10
     (:REWRITE MILAWA::SYMBOLP-WHEN-NATP-CHEAP))
 (54 6
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
 (54 6
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
 (50 10
     (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-LOOKUP-IN-ELIM.NAMESP))
 (48 48
     (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (48 48
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (44 44
     (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (44 44
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (44 44
     (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (40 8
     (:REWRITE MILAWA::NFIX-WHEN-NOT-NATP-CHEAP))
 (30 30
     (:REWRITE MILAWA::LOOKUP-WHEN-MEMBERP-OF-SUBMAPP1))
 (30 30
     (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-TWO))
 (30 30
     (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-ONE))
 (30 30
     (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (30 30
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (30 30
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (24 8 (:REWRITE MILAWA::NFIX-WHEN-ZP-CHEAP))
 (18 18
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (18 18
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (18 18
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (18 18
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (12 12 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (12 12
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (12 12
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (12 12 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (12 12
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (12 12
     (:REWRITE MILAWA::|(< b d) when (= (+ a (+ b c)) d)|))
 (12 12
     (:REWRITE MILAWA::|(< b c) when (= (+ a b) c)|))
 (12 12
     (:REWRITE MILAWA::|(< a c) when (= (+ a b) c)|))
 (10 10
     (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (10 10
     (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
 (10 10
     (:REWRITE MILAWA::SYMBOLP-WHEN-MEMBERP-OF-SYMBOL-LISTP-ALT))
 (10 10
     (:REWRITE MILAWA::SYMBOLP-WHEN-MEMBERP-OF-SYMBOL-LISTP))
 (10 10
     (:REWRITE MILAWA::SYMBOLP-WHEN-LOOKUP-IN-RW.TYPED-RULEMAPP))
 (10 10
     (:REWRITE MILAWA::SYMBOLP-WHEN-LOOKUP-IN-RW.THEORY-MAPP))
 (10 10
     (:REWRITE MILAWA::SYMBOLP-WHEN-BOOLEANP-CHEAP))
 (10 10
     (:REWRITE
          MILAWA::LOGIC.VARIABLEP-WHEN-MEMBERP-OF-LOGIC.VARIABLE-LISTP-ALT))
 (10 10
     (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-MEMBERP-OF-LOGIC.VARIABLE-LISTP))
 (10 10
     (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-LOOKUP-IN-LOGIC.SIGMAP))
 (10 10
     (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-LOOKUP-IN-LOGIC.SIGMA-ATBLP))
 (10
  10
  (:REWRITE
   MILAWA::LOGIC.FUNCTION-NAMEP-WHEN-MEMBERP-OF-LOGIC.FUNCTION-SYMBOL-LISTP-ALT))
 (10
  10
  (:REWRITE
   MILAWA::LOGIC.FUNCTION-NAMEP-WHEN-MEMBERP-OF-LOGIC.FUNCTION-SYMBOL-LISTP))
 (10 10
     (:REWRITE MILAWA::ELIM.NAMESP-OF-SUBSET-WHEN-ELIM.NAMESP-ALT))
 (10 10
     (:REWRITE MILAWA::ELIM.NAMESP-OF-SUBSET-WHEN-ELIM.NAMESP))
 (8 8
    (:REWRITE MILAWA::ZP-WHEN-NOT-NATP-CHEAP))
 (8 8 (:REWRITE MILAWA::ZP-WHEN-NATP-CHEAP))
 (8 8
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.UPDATE-NOEXEC-OKP))
 (8 8
    (:REWRITE
         MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.SIMPLE-CHANGE-WORLD-OKP))
 (8 8
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.RESTRICT-OKP))
 (8 8
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.E/D-OKP))
 (8 8
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.CREATE-THEORY-OKP))
 (8 8
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.CHEAPEN-OKP))
 (8 8 (:REWRITE MILAWA::LEN-WHEN-TUPLEP))
 (8 8
    (:REWRITE MILAWA::LEN-WHEN-NOT-CONSP-OF-CDR-CHEAP))
 (8 8
    (:REWRITE MILAWA::FORCING-TRUE-LISTP-OF-TACTIC.SKELETON->GOALS))
 (6 6
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (6 6
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (6 6
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (6 6
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (6 6
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (6 6
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (6 6
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS)))
(MILAWA::TACTIC.SKELETONP-OF-TACTIC.APPLY-STRATEGY-STEP
  (476 7
       (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
  (462 7
       (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
  (432 9
       (:REWRITE MILAWA::ELIM.NAMESP-WHEN-NOT-CONSP))
  (123 23
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
  (68 23
      (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
  (63 7
      (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
  (63 7
      (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
  (59 23
      (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
  (23 23
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
  (23 23
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
  (18 18
      (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
  (18 18
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
  (18 18
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
  (14 14 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
  (14 14
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
  (14 14
      (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
  (14 14 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
  (14 14
      (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
  (14 14
      (:REWRITE MILAWA::|(< b d) when (= (+ a (+ b c)) d)|))
  (14 14
      (:REWRITE MILAWA::|(< b c) when (= (+ a b) c)|))
  (14 14
      (:REWRITE MILAWA::|(< a c) when (= (+ a b) c)|))
  (9 9
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
  (9 9
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
  (9 9
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
  (9 9
     (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
  (9 9
     (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
  (9 9
     (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
  (9 9 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
  (9 9
     (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
  (9 9
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
  (9 9
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
  (9 9 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
  (9 9
     (:REWRITE MILAWA::ELIM.NAMESP-OF-SUBSET-WHEN-ELIM.NAMESP-ALT))
  (9 9
     (:REWRITE MILAWA::ELIM.NAMESP-OF-SUBSET-WHEN-ELIM.NAMESP))
  (7 7
     (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
  (7 7
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
  (7 7
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
  (7 7
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
  (7 7
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
  (7 7
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS)))
(MILAWA::TACTIC.APPLY-STRATEGY
 (58 2
     (:REWRITE MILAWA::RANK-WHEN-NOT-CONSP))
 (18 2
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (15 2
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (11 2
     (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
 (9 1
    (:REWRITE MILAWA::RANK-WHEN-LOGIC.SUBTERM-OF-SOMEP-WEAK))
 (9 1
    (:REWRITE MILAWA::RANK-WHEN-LOGIC.SUBTERM-OF-SOMEP))
 (8 4
    (:REWRITE MILAWA::LOGIC.SUBTERMP-IS-WEAKLY-ANTISYMMETRIC))
 (7 1
    (:REWRITE MILAWA::RANK-WHEN-LOGIC.SUBTERMP-WEAK))
 (7 1
    (:REWRITE MILAWA::RANK-WHEN-LOGIC.SUBTERMP))
 (6 6
    (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (6 6
    (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (6 6
    (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (4 4
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (4 4
    (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (4 4 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (4 4
    (:REWRITE MILAWA::LOGIC.SUBTERMP-IS-TRANSITIVE-TWO))
 (4 4
    (:REWRITE MILAWA::LOGIC.SUBTERMP-IS-TRANSITIVE))
 (4 1
    (:REWRITE MILAWA::RANK-WHEN-MEMBERP-WEAK))
 (4 1 (:REWRITE MILAWA::RANK-WHEN-MEMBERP))
 (3 3
    (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (3 3
    (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (3 1
    (:REWRITE MILAWA::NATP-OF-CDR-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (2 2 (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (2 2
    (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-SUBTERM-AND-LOGIC.ALL-SUBTERM-OF-SOMEP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-SUBTERM-AND-LOGIC.ALL-SUBTERM-OF-SOMEP))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-MEMBERP-OF-LOGIC.ALL-SUBTERM-OF-SOMEP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-MEMBERP-OF-LOGIC.ALL-SUBTERM-OF-SOMEP))
 (2 2
    (:REWRITE
         MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-MEMBERP-IS-LOGIC.SUBTERMP-ALT))
 (2 2
    (:REWRITE MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-MEMBERP-IS-LOGIC.SUBTERMP))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-LOGIC.SUBTERMP-AND-LOGIC.SUBTERM-OF-SOMEP-ALT))
 (2
  2
  (:REWRITE
   MILAWA::LOGIC.SUBTERM-OF-SOMEP-WHEN-LOGIC.SUBTERMP-AND-LOGIC.SUBTERM-OF-SOMEP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (2 2
    (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (1 1 (:REWRITE MILAWA::TRUE-LISTP-OF-CDR))
 (1 1
    (:REWRITE MILAWA::CONSP-OF-CDR-WITH-LEN-FREE))
 (1 1
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-3-CHEAP))
 (1 1
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-TUPLEP-2-CHEAP))
 (1 1
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-MEMBERP-NOT-CAR-CHEAP))
 (1 1
    (:REWRITE MILAWA::CONSP-OF-CDR-WHEN-LEN-TWO-CHEAP))
 (1 1
    (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
 (1 1 (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
 (1 1 (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
 (1 1
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
 (1 1
    (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
 (1 1
    (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
 (1 1
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP-ALT))
 (1 1
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP))
 (1 1
    (:REWRITE MILAWA::|(< b d) when (= (+ a (+ b c)) d)|))
 (1 1
    (:REWRITE MILAWA::|(< b c) when (= (+ a b) c)|))
 (1 1
    (:REWRITE MILAWA::|(< a c) when (= (+ a b) c)|)))
(MILAWA::TACTIC.SKELETONP-OF-TACTIC.APPLY-STRATEGY
  (336 7
       (:REWRITE MILAWA::ELIM.NAMESP-WHEN-NOT-CONSP))
  (195 23
       (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
  (128 23
       (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
  (107 23
       (:REWRITE MILAWA::CONSP-WHEN-TRUE-LISTP-CHEAP))
  (68 1
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
  (66 1
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
  (65 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP))
  (56 56
      (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
  (56 56
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
  (56 56
      (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
  (24 24
      (:REWRITE MILAWA::CAR-WHEN-NOT-CONSP))
  (24 24
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-OF-SINGLETON-LIST-CHEAP))
  (24 24
      (:REWRITE MILAWA::CAR-WHEN-MEMBERP-AND-NOT-MEMBERP-OF-CDR-CHEAP))
  (24 24
      (:REWRITE MILAWA::CAR-WHEN-ALL-EQUALP))
  (23 23
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
  (23 23
      (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
  (23 23
      (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
  (21 21
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
  (21 21
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
  (21 21
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
  (21 21
      (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
  (21 21
      (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
  (21 21
      (:REWRITE MILAWA::NATP-WHEN-NOT-ZP-CHEAP))
  (21 21
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
  (21 21
      (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
  (21 21 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
  (10 10
      (:REWRITE MILAWA::CDR-WHEN-TRUE-LISTP-WITH-LEN-FREE-PAST-THE-END))
  (10 10
      (:REWRITE MILAWA::CDR-WHEN-NOT-CONSP))
  (9 1
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS-TWO))
  (9 1
     (:REWRITE MILAWA::NOT-EQUAL-WHEN-LESS))
  (7 7
     (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
  (7 7
     (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
  (7 7
     (:REWRITE MILAWA::ELIM.NAMESP-OF-SUBSET-WHEN-ELIM.NAMESP-ALT))
  (7 7
     (:REWRITE MILAWA::ELIM.NAMESP-OF-SUBSET-WHEN-ELIM.NAMESP))
  (2 2 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
  (2 2
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
  (2 2
     (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
  (2 2 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
  (2 2
     (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
  (2 2
     (:REWRITE MILAWA::|(< b d) when (= (+ a (+ b c)) d)|))
  (2 2
     (:REWRITE MILAWA::|(< b c) when (= (+ a b) c)|))
  (2 2
     (:REWRITE MILAWA::|(< a c) when (= (+ a b) c)|))
  (1 1
     (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
  (1 1
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
  (1 1
     (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
  (1 1
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
  (1 1
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
  (1 1
     (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS)))
(MILAWA::TACTIC.AUTO-TAC
 (207 6
      (:REWRITE MILAWA::SAME-LENGTH-PREFIXES-EQUAL-CHEAP))
 (198 3
      (:REWRITE MILAWA::PREFIXP-WHEN-NOT-CONSP-TWO))
 (181 1
      (:REWRITE MILAWA::MINUS-WHEN-NOT-LESS))
 (180 6
      (:REWRITE MILAWA::BOOLEANP-WHEN-CONSP-CHEAP))
 (172 1 (:REWRITE MILAWA::LESS-OF-ONE-LEFT))
 (114 36
      (:REWRITE MILAWA::NATP-WHEN-ZP-CHEAP))
 (90 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP))
 (90 3
     (:REWRITE MILAWA::SYMBOLP-WHEN-CONSP-CHEAP))
 (56 16
     (:REWRITE MILAWA::ZP-WHEN-NOT-NATP-CHEAP))
 (48 1
     (:REWRITE MILAWA::ELIM.NAMESP-WHEN-NOT-CONSP))
 (42 3
     (:REWRITE MILAWA::SYMBOLP-WHEN-LOGIC.FUNCTION-NAMEP))
 (39 39
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP-ALT))
 (39 39
     (:REWRITE MILAWA::NATP-WHEN-MEMBERP-OF-NAT-LISTP))
 (39 39 (:REWRITE MILAWA::NATP-OF-LEN-FREE))
 (36 6
     (:REWRITE MILAWA::BOOLEANP-WHEN-NATP-CHEAP))
 (33
   3
   (:REWRITE MILAWA::LOGIC.FUNCTION-NAMEP-WHEN-LOOKUP-IN-LOGIC.ARITY-TABLEP))
 (30 3
     (:REWRITE MILAWA::SYMBOLP-WHEN-LOGIC.VARIABLEP))
 (27 27
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-REWRITE.SYNTAXP-ARITY-TABLE))
 (27 27
     (:REWRITE MILAWA::LOGIC.ARITY-TABLEP-OF-LOGIC.INITIAL-ARITY-TABLE))
 (27 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-NONEMPTY-SUBSET-CHEAP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.TYPED-RULEMAPP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.THEORY-MAPP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.FAST-CACHEMAPP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-RW.CACHEMAPP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMAP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.SIGMA-ATBLP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAPP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.CALLMAP-ATBLP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-LOGIC.ARITY-TABLEP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-ELIM.NAMESP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP-ALT))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-CONS-LISTP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-CHEAP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.LAMBDAP-CHEAP))
 (24 24
     (:REWRITE MILAWA::CONSP-WHEN-LOGIC.FUNCTIONP-CHEAP))
 (20 2
     (:REWRITE MILAWA::SUBSETP-OF-REMOVE-DUPLICATES-ONE-INDIRECT))
 (19 5
     (:REWRITE MILAWA::NFIX-WHEN-NOT-NATP-CHEAP))
 (18 8
     (:REWRITE MILAWA::CONSP-WHEN-NATP-CHEAP))
 (18 3
     (:REWRITE MILAWA::SYMBOLP-WHEN-NATP-CHEAP))
 (15 15
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP-ALT))
 (15 15
     (:REWRITE MILAWA::CONSP-WHEN-MEMBERP-OF-NONE-CONSP))
 (15 3
     (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-LOOKUP-IN-ELIM.NAMESP))
 (10 1
     (:REWRITE MILAWA::|a < b --> a <= b-1|))
 (9 9
    (:REWRITE MILAWA::LOOKUP-WHEN-MEMBERP-OF-SUBMAPP1))
 (9 9
    (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-TWO))
 (9 9
    (:REWRITE MILAWA::LOOKUP-WHEN-LOOKUP-IN-SUBMAPP-ONE))
 (9 9
    (:REWRITE MILAWA::FORCING-LOOKUP-OF-LOGIC.FUNCTION-NAME-FREE))
 (9 5 (:REWRITE MILAWA::NFIX-WHEN-ZP-CHEAP))
 (8 8
    (:REWRITE MILAWA::|(< b d) when (= (+ a (+ b c)) d)|))
 (8 8
    (:REWRITE MILAWA::|(< b c) when (= (+ a b) c)|))
 (8 8
    (:REWRITE MILAWA::|(< a c) when (= (+ a b) c)|))
 (7 7
    (:REWRITE MILAWA::MEMBERP-WHEN-MEMBERP-OF-CDR))
 (7 7
    (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-TWO))
 (7 7
    (:REWRITE MILAWA::IN-SUPERSET-WHEN-IN-SUBSET-ONE))
 (6 6
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-TWO))
 (6 6
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-THREE))
 (6 6
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP-ALT))
 (6 6
    (:REWRITE MILAWA::EQUAL-WHEN-MEMBERP-OF-ALL-EQUALP))
 (6 6
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PORS))
 (6 6
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PNOTS))
 (6 6
    (:REWRITE MILAWA::AGGRESSIVE-EQUAL-OF-LOGIC.PEQUALS))
 (6 2 (:REWRITE MILAWA::ZP-OF-NFIX))
 (5 5
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP-ALT))
 (5 5
    (:REWRITE MILAWA::<-WHEN-MEMBERP-OF-ALL-AT-LEASTP))
 (4 4 (:REWRITE MILAWA::TRICHOTOMY-OF-<))
 (3 3
    (:REWRITE MILAWA::TRANSITIVITY-OF-<-FOUR))
 (3 3 (:REWRITE MILAWA::TRANSITIVITY-OF-<))
 (3 3
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP-ALT))
 (3 3
    (:REWRITE MILAWA::TACTIC.WORLDP-WHEN-MEMBERP-OF-TACTIC.WORLD-LISTP))
 (3 3
    (:REWRITE MILAWA::SYMBOLP-WHEN-MEMBERP-OF-SYMBOL-LISTP-ALT))
 (3 3
    (:REWRITE MILAWA::SYMBOLP-WHEN-MEMBERP-OF-SYMBOL-LISTP))
 (3 3
    (:REWRITE MILAWA::SYMBOLP-WHEN-LOOKUP-IN-RW.TYPED-RULEMAPP))
 (3 3
    (:REWRITE MILAWA::SYMBOLP-WHEN-LOOKUP-IN-RW.THEORY-MAPP))
 (3 3
    (:REWRITE MILAWA::SYMBOLP-WHEN-BOOLEANP-CHEAP))
 (3 3
    (:REWRITE
         MILAWA::LOGIC.VARIABLEP-WHEN-MEMBERP-OF-LOGIC.VARIABLE-LISTP-ALT))
 (3 3
    (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-MEMBERP-OF-LOGIC.VARIABLE-LISTP))
 (3 3
    (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-LOOKUP-IN-LOGIC.SIGMAP))
 (3 3
    (:REWRITE MILAWA::LOGIC.VARIABLEP-WHEN-LOOKUP-IN-LOGIC.SIGMA-ATBLP))
 (3
  3
  (:REWRITE
   MILAWA::LOGIC.FUNCTION-NAMEP-WHEN-MEMBERP-OF-LOGIC.FUNCTION-SYMBOL-LISTP-ALT))
 (3
  3
  (:REWRITE
   MILAWA::LOGIC.FUNCTION-NAMEP-WHEN-MEMBERP-OF-LOGIC.FUNCTION-SYMBOL-LISTP))
 (3 3
    (:REWRITE MILAWA::LESS-WHEN-ZP-LEFT-CHEAP))
 (3 3
    (:REWRITE MILAWA::FORCING-PREFIXP-WHEN-NOT-PREFIXP-BADGUY))
 (3 3
    (:REWRITE MILAWA::EQUAL-OF-BOOLEANS-REWRITE))
 (3 3
    (:REWRITE MILAWA::ELIM.NAMESP-OF-SUBSET-WHEN-ELIM.NAMESP-ALT))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-TUPLEP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-NOT-CONSP))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP-ALT))
 (2 2
    (:REWRITE MILAWA::TRUE-LISTP-WHEN-MEMBERP-OF-TRUE-LIST-LISTP))
 (2 2
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.UPDATE-NOEXEC-OKP))
 (2 2
    (:REWRITE
         MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.SIMPLE-CHANGE-WORLD-OKP))
 (2 2
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.RESTRICT-OKP))
 (2 2
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.E/D-OKP))
 (2 2
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.CREATE-THEORY-OKP))
 (2 2
    (:REWRITE MILAWA::TACTIC.SKELETON->GOALS-WHEN-TACTIC.CHEAPEN-OKP))
 (2 2
    (:REWRITE MILAWA::REMOVE-DUPLICATES-WHEN-UNIQUE))
 (2 2
    (:REWRITE MILAWA::REMOVE-DUPLICATES-WHEN-NOT-CONSP))
 (2 2
    (:REWRITE MILAWA::ORDERED-SUBSETP-IS-TRANSITIVE))
 (1 1
    (:REWRITE MILAWA::|b <= c, a <= b --> a < 1+c|))
 (1 1
    (:REWRITE MILAWA::|a <= b, b <= c --> a < 1+c|))
 (1 1
    (:REWRITE MILAWA::PLUS-WHEN-ZP-RIGHT-CHEAP))
 (1 1
    (:REWRITE MILAWA::PLUS-WHEN-ZP-LEFT-CHEAP))
 (1 1
    (:REWRITE MILAWA::MINUS-WHEN-ZP-RIGHT-CHEAP))
 (1 1
    (:REWRITE MILAWA::MINUS-WHEN-ZP-LEFT-CHEAP))
 (1 1 (:REWRITE MILAWA::IRREFLEXIVITY-OF-<))
 (1 1
    (:REWRITE MILAWA::GATHER-CONSTANTS-FROM-LESS-OF-PLUS-TWO)))
(MILAWA::%TACTIC.AUTO-TAC-WRAPPER)
